### ISSUE TITLE
Inference of tensorrt model export with batch size > 1

### ISSUE THREAD

**Issue by jakovlovric** [open-mmlab/mmdeploy#1032]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I am unable to run the inference of the tensorrt export of Faster RCNN model from mmdetection with batch size > 1. 

### Reproduction

Tensorrt export (ends successfully): 
`python mmdeploy/tools/deploy.py mmdeploy/configs/mmdet/py_config.py mmdet_configs/faster_rcnn/faster_rcnn_r50_fpn_tnr-pretrain_1x_coco.py checkpoints/faster_rcnn_r50_fpn_tnr-pretrain_1x_coco_20220320_085147-efedfda4.pth data/coco/val2017/000000274708.jpg --work-dir test_issue/ --device cuda`

Inference (Fails to run): 
`python mmdeploy/tools/test.py mmdeploy/configs/mmdet/my_config.py mmdet_configs/faster_rcnn/faster_rcnn_r50_fpn_tnr-pretrain_1x_coco.py --model test_issue/end2end.engine --out test_issue/test.pkl --device cuda --batch-size 2`

my_config.py (same as configs/mmdet/_base_/base_tensorrt_dynamic-320x320-1344x1344.py but with different max_shape parameter):
```
_base_ = ['./_base_/base_dynamic.py', '../_base_/backends/tensorrt.py']

backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 320, 320],
                    opt_shape=[1, 3, 800, 1344],
                    max_shape=[2, 3, 1344, 1344])))
    ])
```

### Environment

```Shell
2022-09-12 12:15:19,018 - mmdeploy - INFO - 

2022-09-12 12:15:19,018 - mmdeploy - INFO - **********Environmental information**********
2022-09-12 12:15:20,374 - mmdeploy - INFO - sys.platform: linux
2022-09-12 12:15:20,375 - mmdeploy - INFO - Python: 3.9.9 (main, Aug 30 2022, 11:22:56) [GCC 9.3.0]
2022-09-12 12:15:20,375 - mmdeploy - INFO - CUDA available: True
2022-09-12 12:15:20,375 - mmdeploy - INFO - GPU 0,1,2,3: NVIDIA GeForce RTX 2080 Ti
2022-09-12 12:15:20,375 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2022-09-12 12:15:20,375 - mmdeploy - INFO - NVCC: Build cuda_11.1.TC455_06.29190527_0
2022-09-12 12:15:20,375 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
2022-09-12 12:15:20,375 - mmdeploy - INFO - PyTorch: 1.11.0+cu113
2022-09-12 12:15:20,375 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

2022-09-12 12:15:20,375 - mmdeploy - INFO - TorchVision: 0.12.0+cu113
2022-09-12 12:15:20,375 - mmdeploy - INFO - OpenCV: 4.6.0
2022-09-12 12:15:20,375 - mmdeploy - INFO - MMCV: 1.4.8
2022-09-12 12:15:20,375 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2022-09-12 12:15:20,375 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2022-09-12 12:15:20,375 - mmdeploy - INFO - MMDeploy: 0.7.0+3b32b50
2022-09-12 12:15:20,375 - mmdeploy - INFO - 

2022-09-12 12:15:20,375 - mmdeploy - INFO - **********Backend information**********
2022-09-12 12:15:20,949 - mmdeploy - INFO - onnxruntime: 1.8.0  ops_is_avaliable : True
2022-09-12 12:15:20,977 - mmdeploy - INFO - tensorrt: 8.4.1.5   ops_is_avaliable : True
2022-09-12 12:15:21,031 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-09-12 12:15:21,038 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-09-12 12:15:21,045 - mmdeploy - INFO - openvino_is_avaliable: False
2022-09-12 12:15:21,073 - mmdeploy - INFO - snpe_is_available: False
2022-09-12 12:15:21,137 - mmdeploy - INFO - ascend_is_available: False
2022-09-12 12:15:21,149 - mmdeploy - INFO - coreml_is_available: False
2022-09-12 12:15:21,149 - mmdeploy - INFO - 

2022-09-12 12:15:21,149 - mmdeploy - INFO - **********Codebase information**********
2022-09-12 12:15:21,151 - mmdeploy - INFO - mmdet:      2.25.1
2022-09-12 12:15:21,151 - mmdeploy - INFO - mmseg:      None
2022-09-12 12:15:21,151 - mmdeploy - INFO - mmcls:      None
2022-09-12 12:15:21,151 - mmdeploy - INFO - mmocr:      None
2022-09-12 12:15:21,151 - mmdeploy - INFO - mmedit:     None
2022-09-12 12:15:21,151 - mmdeploy - INFO - mmdet3d:    None
2022-09-12 12:15:21,151 - mmdeploy - INFO - mmpose:     None
2022-09-12 12:15:21,151 - mmdeploy - INFO - mmrotate:   None
```

### Error traceback

```Shell
/home/jakov/.pyenv/versions/deployment/lib/python3.9/site-packages/mmdet/datasets/utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
loading annotations into memory...                                   
Done (t=0.53s)                                           
creating index...                                      
index created!                                                    
2022-09-12 12:07:37,947 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /data/nas/users/jakov/projects/xxx/deployment/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
2022-09-12 12:07:37,947 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /data/nas/users/jakov/projects/xxx/deployment/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
[09/12/2022-12:07:39] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.0.5
[09/12/2022-12:07:39] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.0.5
[                                                  ] 0/5000, elapsed: 0s, ETA:[09/12/2022-12:07:41] [TRT] [E] 7: [shapeMachine.cpp::execute::702] Error Code 7: Internal Error (IShuffleLayer Reshape_794: reshaping failed for tensor: y.28
reshape would change volume                                                                                                                  
Instruction: RESHAPE_ZERO_IS_PLACEHOLDER{2000 5} {1 1000 5}                                                                                  
)                                                                                                                                            
Traceback (most recent call last):                                   
  File "/data/nas/users/jakov/projects/xxx/doc_detection_mmdetect/../deployment/mmdeploy/tools/test.py", line 151, in <module>
    main()                                                          
  File "/data/nas/users/jakov/projects/xxx/doc_detection_mmdetect/../deployment/mmdeploy/tools/test.py", line 141, in main
    outputs = task_processor.single_gpu_test(model, data_loader, args.show,
  File "/data/nas/users/jakov/projects/xxx/deployment/mmdeploy/mmdeploy/codebase/base/task.py", line 139, in single_gpu_test
    return self.codebase_class.single_gpu_test(model, data_loader, show,
  File "/data/nas/users/jakov/projects/xxx/deployment/mmdeploy/mmdeploy/codebase/mmdet/deploy/mmdetection.py", line 142, in single_gpu_test
    outputs = single_gpu_test(model, data_loader, show, out_dir, **kwargs)
  File "/home/jakov/.pyenv/versions/deployment/lib/python3.9/site-packages/mmdet/apis/test.py", line 29, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/jakov/.pyenv/versions/deployment/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jakov/.pyenv/versions/deployment/lib/python3.9/site-packages/mmcv/parallel/data_parallel.py", line 50, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/jakov/.pyenv/versions/deployment/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/jakov/.pyenv/versions/deployment/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/nas/users/jakov/projects/xxx/deployment/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 198, in forward
    outputs = self.forward_test(input_img, img_metas, *args, **kwargs) 
  File "/data/nas/users/jakov/projects/xxx/deployment/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 274, in forward_test
    outputs = self.wrapper({self.input_name: imgs})
  File "/home/jakov/.pyenv/versions/deployment/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/nas/users/jakov/projects/xxx/deployment/mmdeploy/mmdeploy/backend/tensorrt/wrapper.py", line 158, in forward
    shape = tuple(self.context.get_binding_shape(idx))
ValueError: __len__() should return >= 0
```

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by grimoire** [comment]
https://github.com/open-mmlab/mmdeploy/pull/1033

**Comment by jakovlovric** [comment]
Problem solved. Thank you.
