### ISSUE TITLE
CoreML: Broadcastable tensor index not supported.

### ISSUE THREAD

**Issue by Typiqally** [open-mmlab/mmdeploy#1038]
I'm trying to convert the pre-trained version of the [faster_rcnn_regnetx-3.2GF_fpn_1x_coco](https://github.com/open-mmlab/mmdetection/blob/master/configs/regnet/faster_rcnn_regnetx-3.2GF_fpn_1x_coco.py) model to CoreML. This model raises an issue in the internally used [coremltools](https://github.com/apple/coremltools):

```python
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mmlabs/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mmlabs/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/typically/Workspace/vbti-plant-morphology/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/Users/typically/Workspace/vbti-plant-morphology/mmdeploy/mmdeploy/apis/pytorch2torchscript.py", line 78, in torch2torchscript
    trace(
  File "/Users/typically/Workspace/vbti-plant-morphology/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/Users/typically/Workspace/vbti-plant-morphology/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/Users/typically/Workspace/vbti-plant-morphology/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/Users/typically/Workspace/vbti-plant-morphology/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/Users/typically/Workspace/vbti-plant-morphology/mmdeploy/mmdeploy/apis/torch_jit/trace.py", line 137, in trace
    model = ct.convert(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mmlabs/lib/python3.8/site-packages/coremltools/converters/_converters_entry.py", line 451, in convert
    mlmodel = mil_convert(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mmlabs/lib/python3.8/site-packages/coremltools/converters/mil/converter.py", line 193, in mil_convert
    return _mil_convert(model, convert_from, convert_to, ConverterRegistry, MLModel, compute_units, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mmlabs/lib/python3.8/site-packages/coremltools/converters/mil/converter.py", line 220, in _mil_convert
    proto, mil_program = mil_convert_to_proto(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mmlabs/lib/python3.8/site-packages/coremltools/converters/mil/converter.py", line 283, in mil_convert_to_proto
    prog = frontend_converter(model, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mmlabs/lib/python3.8/site-packages/coremltools/converters/mil/converter.py", line 115, in __call__
    return load(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mmlabs/lib/python3.8/site-packages/coremltools/converters/mil/frontend/torch/load.py", line 53, in load
    return _perform_torch_convert(converter, debug)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mmlabs/lib/python3.8/site-packages/coremltools/converters/mil/frontend/torch/load.py", line 100, in _perform_torch_convert
    raise e
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mmlabs/lib/python3.8/site-packages/coremltools/converters/mil/frontend/torch/load.py", line 92, in _perform_torch_convert
    prog = converter.convert()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mmlabs/lib/python3.8/site-packages/coremltools/converters/mil/frontend/torch/converter.py", line 269, in convert
    convert_nodes(self.context, self.graph)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mmlabs/lib/python3.8/site-packages/coremltools/converters/mil/frontend/torch/ops.py", line 92, in convert_nodes
    add_op(context, node)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mmlabs/lib/python3.8/site-packages/coremltools/converters/mil/frontend/torch/ops.py", line 3207, in index
    raise NotImplementedError("Broadcasable tensor index not supported.")
NotImplementedError: Broadcasable tensor index not supported.
```

I am not fully aware of why this exception is raised, but I believe it has something to do with multi-class non-maximum suppression. The exception is raised because the two inputs from the index operation do not match in shape, see screenshot:

```python
    for indice in valid_indices:
        if not is_compatible_symbolic_vector(indice.shape, valid_indices[0].shape):
            raise NotImplementedError("Broadcasable tensor index not supported.")
```

![image](https://user-images.githubusercontent.com/12190745/189889115-3ca5ef61-b27a-49e1-af16-b4ad204540cb.png)

I'm not certain why the `prior` and `topk` operations are used together within the `index` operation. Perhaps someone could provide me with a lead.

**Comment by grimoire** [comment]
- [nms](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS15.tensor_operation.non_maximum_suppression) in coreml do support batched inference. The asserting is caused by the gather topk index. multi-index gather like `data[batch_index, topk_index, ...]` is not allowed in CoreML for now. That block the batched inference.
- It should be ok if you convert a model with static shape and batch_size==1, but it is hard to support `dynamic shape` and `multi-batch`. There are many limitation like:
  - Upsampling with dynamic `size` is not allowed. you can only use `scale_factor`
  - `repeat` with dynamic shape is not allowed.
  - broadcast indexing is not allowed.
  - `where` op can not be broadcasted.
  - etc
- You can add these supports with custom ops, the difficulty is determined by what you want to do.
- Here are some links that might be helpful
  - https://coremltools.readme.io/docs/custom-operators how to bind the ops. Note that for pytorch, you might need to add a dummy torchscript ops to do the mapping like [this](https://github.com/open-mmlab/mmdeploy/blob/master/csrc/mmdeploy/backend_ops/torchscript/ops/coreml_nms/coreml_nms_cpu.cpp) and bind the ops like [this](https://github.com/open-mmlab/mmdeploy/blob/b87afb9ebb24fe46bf8ae4728a354bdcc1afee50/mmdeploy/backend/coreml/ops.py#L9)
  - [mlcustomlayer](https://developer.apple.com/documentation/coreml/mlcustomlayer?language=objc) is about how to implement the ops with obj-c or swift.
  - What if you want to make use of the hardware acceleration of M1, you can implement the kernel with MPS like [this](https://github.com/grimoire/TorchMPSCustomOpsDemo).

**Comment by Typiqally** [comment]
Excuse me for editing this issue, I thought the assertion was thrown, but it was simply a warning during torch tracing. However, I believe the model I'm trying to convert has a static shape, still it is not being handled correctly by coremltools.

**Comment by grimoire** [comment]
Sure I see. I can reproduce the error now. Please allow me some time.

**Comment by grimoire** [comment]
Hi, I am so sorry. We might have broken the two-stage detector support for CoreML by accident. Please try [this](https://github.com/open-mmlab/mmdeploy/pull/1044) branch. It is still static shape and non-batch, but at least it works. Please feel free to report any bugs to us. Thank you.

**Comment by Typiqally** [comment]
I am happy to report that I was able to get it working with your branch. Thank you! So far, I have been able to convert the following models using this patch:

- https://github.com/open-mmlab/mmdetection/blob/master/configs/regnet/mask_rcnn_regnetx-3.2GF_fpn_mstrain_3x_coco.py
- https://github.com/open-mmlab/mmdetection/blob/master/configs/regnet/faster_rcnn_regnetx-3.2GF_fpn_1x_coco.py

It appears to be stable now.
