### ISSUE TITLE
FileNotFoundError :  _base_/default_runtime.py"

### ISSUE THREAD

**Issue by naveenkumarkr723** [open-mmlab/mmdeploy#1098]
Hi i run this command but iam getting the below error i dont know what is the issue is 

python mmdeploy/tools/deploy.py  mmdeploy/configs/mmocr/text-recognition/text-recognition_tensorrt_dynamic-32x32-32x640.py crnn_academic_dataset.py https://download.openmmlab.com/mmocr/textrecog/crnn/crnn_academic-a723a1c5.pth img8.png --work-dir mmdeploy_model/rcnn_trt --device cuda:1   --dump-info

Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 448, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 119, in main
    deploy_cfg, model_cfg = load_config(deploy_cfg_path, model_cfg_path)
  File "/usr/local/lib/python3.8/dist-packages/mmdeploy/utils/config_utils.py", line 29, in load_config
    configs = [_load_config(cfg) for cfg in args]
  File "/usr/local/lib/python3.8/dist-packages/mmdeploy/utils/config_utils.py", line 29, in <listcomp>
    configs = [_load_config(cfg) for cfg in args]
  File "/usr/local/lib/python3.8/dist-packages/mmdeploy/utils/config_utils.py", line 22, in _load_config
    cfg = mmcv.Config.fromfile(cfg)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/config.py", line 340, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/config.py", line 252, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/config.py", line 183, in _file2dict
    check_file_exist(filename)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/workspace/cv/NaveenJadi/_base_/default_runtime.py" does not exist

someone help me

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by AllentDan** [comment]
CRNN accepts 1 channel input and `crnn_academic_dataset.py` needs base configs as well.

**Comment by nonononanana** [comment]
这解答啥意思啊
