### ISSUE TITLE
Convert onnxruntime error

### ISSUE THREAD

**Issue by David-19940718** [open-mmlab/mmdeploy#1114]
`# run the command to start model conversion
python3 mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet/detection/detection_onnxruntime_static.py \
    mmdetection/configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py \
    mmdetection/checkpoints/rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth \
    mmdetection/demo/demo.jpg \
    --work-dir mmdeploy/onnxruntime/rtmdet \
    --device cpu \
    --dump-info
`

This is my script to convert model, when i run it, got:
`Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 448, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 125, in main
    export2SDK(
  File "/volume/2/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/sdk/export_info.py", line 403, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/volume/2/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/sdk/export_info.py", line 322, in get_deploy
    _, customs = get_model_name_customs(
  File "/volume/2/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/sdk/export_info.py", line 59, in get_model_name_customs
    task_processor = build_task_processor(
  File "/volume/2/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/utils/utils.py", line 40, in build_task_processor
    import_codebase(codebase_type)
  File "/volume/2/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/codebase/__init__.py", line 33, in import_codebase
    importlib.import_module(f'mmdeploy.codebase.{lib}')
  File "/volume/2/miniconda3/envs/mmdeploy/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/volume/2/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/__init__.py", line 2, in <module>
    from .core import *  # noqa: F401,F403
  File "/volume/2/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401,F403
  File "/volume/2/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/core/bbox/__init__.py", line 3, in <module>
    from .distance_point_bbox_coder import *  # noqa: F401,F403
  File "/volume/2/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/core/bbox/distance_point_bbox_coder.py", line 2, in <module>
    import mmdet.core.bbox.transforms
  File "/volume/1/workspace_jack/custom/mmdetection/mmdet/__init__.py", line 16, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.6.1 is used but incompatible. Please install mmcv>=2.0.0rc0, <2.1.0.`

And then, I followed the instruction to install 'mmcv>=2.0.0rc1', but i got another iuuse:
`Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 12, in <module>
    from mmdeploy.apis import (create_calib_input_data, extract_model,
  File "/volume/2/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/__init__.py", line 4, in <module>
    from mmdeploy.utils import get_root_logger
  File "/volume/2/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/utils/__init__.py", line 18, in <module>
    from .config_utils import (cfg_apply_marks, get_backend,
  File "/volume/2/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/utils/config_utils.py", line 10, in <module>
    def load_config(*args) -> List[mmcv.Config]:
AttributeError: module 'mmcv' has no attribute 'Config'`

How can I slove this issue?

**Comment by hanrui1sensetime** [comment]
Please use dev-1.x branch of mmdeploy.

**Comment by David-19940718** [comment]
> 

Hi, it still got same issue despite switch into dev-1.x branch, is there exist other solution?

**Comment by David-19940718** [comment]
> Please use `dev-1.x` branch of mmdeploy.

Or, can u provide a document to guide me how to convert the lastest RTMDet to *.onnx model, which developed in the mmdetection-3.x branch. I have tried many versions to attempt match the mmdet & mmdeploy, it is, however, everything gonna be failed.

**Comment by kingoo123** [comment]
I try to deploy in dev-1.x with mmcv=2.0.0rc2, but also appeared “AttributeError: module 'mmcv' has no attribute 'Config'”. how to solve？Thanks.
