### ISSUE TITLE
Export swin to TensorRT on Jetson AGX Orin

### ISSUE THREAD

**Issue by habjoel** [open-mmlab/mmdeploy#1125]
Hey there, 

I am currently trying to convert the [swin-t](https://github.com/open-mmlab/mmdetection/blob/master/configs/swin/mask_rcnn_swin-t-p4-w7_fpn_fp16_ms-crop-3x_coco.py) model from mmdetection to TensorRT on my Jetson AGX Orin using [tools/deploy.py](https://github.com/open-mmlab/mmdeploy/blob/master/tools/deploy.py).

I previously done this with this  [mask_rcnn](https://github.com/open-mmlab/mmdetection/blob/master/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py) model, with great success. However, it does not work using swin. Apparently, I think the conversion from onnx to tensorrt requires too much RAM for the Orin (32GB) to handle. Do you know how if there's a way to decrease the RAM requirements for the conversion? Any help is greatly appreciated!

I am using static configs and fp16. I am required to export to and input size of 3.1MP (1544x2064). I know those are quite large image sizes. Here's my conversion config:

```
_base_ = [
    '../_base_/base_instance-seg_static.py',
    '../../_base_/backends/tensorrt-fp16.py'
]

onnx_config = dict(input_shape=(2080, 1568))
backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 1568, 2080],
                    opt_shape=[1, 3, 1568, 2080],
                    max_shape=[1, 3, 1568, 2080])))
    ])
```

The error message looks as follows:
```
...
[09/28/2022-08:49:38] [TRT] [I] [GpuLayer] CONVOLUTION: Conv_1492 + Relu_1493
[09/28/2022-08:49:38] [TRT] [I] [GpuLayer] CONVOLUTION: Conv_1494 + Relu_1495
[09/28/2022-08:49:38] [TRT] [I] [GpuLayer] CONVOLUTION: Conv_1496 + Relu_1497
[09/28/2022-08:49:38] [TRT] [I] [GpuLayer] DECONVOLUTION: ConvTranspose_1498 + Relu_1499
[09/28/2022-08:49:38] [TRT] [I] [GpuLayer] CONVOLUTION: Conv_1500
[09/28/2022-08:49:38] [TRT] [I] [GpuLayer] MYELIN: {ForeignNode[Sigmoid_1502...Reshape_1516 + Unsqueeze_1517 + Reshape_1525]}
[09/28/2022-08:49:39] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +534, GPU +502, now: CPU 1942, GPU 10852 (MiB)
[09/28/2022-08:49:39] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +84, GPU +98, now: CPU 2026, GPU 10950 (MiB)
[09/28/2022-08:49:39] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[09/28/2022-08:57:10] [TRT] [E] 2: [helpers.h::numericCast::38] Error Code 2: Internal Error (Assertion src <= val failed. )
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mmdeploy_installs/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/mmdeploy_installs/mmdeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "/mmdeploy_installs/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 215, in from_onnx
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine
2022-09-28 08:57:11,339 - mmdeploy - ERROR - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed. exit.
```

**Comment by AllentDan** [comment]
Did you succeed converting swin with small resolution in Orin?

**Comment by habjoel** [comment]
Yes, I did. I tried with a static config to size 480x640 and that worked. I would really like to achieve it for the higher resolution but maybe it's just not feasible...

**Comment by AllentDan** [comment]
If it is converting to TensorRT failed. Maybe you could try to set a bigger `max_workspace_size` when using `deploy.py`. Besides, perhaps you could use trtexec to convert the onnx model directly.

**Comment by habjoel** [comment]
thanks @AllentDan. I tried both and I'm still getting the same error message. Unfortunate but probably the RAM requirements are just too big for this application. Thanks anyways :)

**Comment by AllentDan** [comment]
You are welcome. Close the issue then.
