### ISSUE TITLE
Critical issue when running MMPose, Hard to understand the issue

### ISSUE THREAD

**Issue by venkatshivap** [open-mmlab/mmdeploy#1129]
Could someone please help me.

Python 3.8
PYTORCH 1.12
CUDA 11.4

python tools/deploy.py configs/mmpose/pose-detection_tensorrt_static-256x192.py /home/digit7-o1/Downloads/mmdeploy/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py $MMPOSE_DIR/checkpoints/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth $MMDEPLOY_DIR/demo/resources/human-pose.jpg --work-dir work-dirs/mmpose/topdown/hrnet/trt --device cuda

/.local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "tools/deploy.py", line 448, in <module>
    main()
  File "tools/deploy.py", line 119, in main
    deploy_cfg, model_cfg = load_config(deploy_cfg_path, model_cfg_path)
  File "/home/digit7-o1/Downloads/mmdeploy/mmdeploy/utils/config_utils.py", line 29, in load_config
    configs = [_load_config(cfg) for cfg in args]
  File "/home/digit7-o1/Downloads/mmdeploy/mmdeploy/utils/config_utils.py", line 29, in <listcomp>
    configs = [_load_config(cfg) for cfg in args]
  File "/home/digit7-o1/Downloads/mmdeploy/mmdeploy/utils/config_utils.py", line 22, in _load_config
    cfg = mmcv.Config.fromfile(cfg)
  File "/home/digit7-o1/Downloads/mmdeploy/mmcv/mmcv/utils/config.py", line 340, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/home/digit7-o1/Downloads/mmdeploy/mmcv/mmcv/utils/config.py", line 252, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/digit7-o1/Downloads/mmdeploy/mmcv/mmcv/utils/config.py", line 208, in _file2dict
    mod = import_module(temp_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp2qyernc4/tmpn21wwffz.py", line 17, in <module>
ImportError: attempted relative import with no known parent package

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by RunningLeon** [comment]
@venkatshivap Hi, pls. provide necessary such what script you ran, env info of running `python tools/check_env.py`  to reproduce

**Comment by venkatshivap** [comment]
I tried running below script

**`python3 tools/deploy.py configs/mmpose/pose-detection_tensorrt_static-256x192.py hrnet_w48_coco_256x192.py hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth $MMDEPLOY_DIR/demo/resources/human-pose.jpg --work-dir work-dirs/mmpose/topdown/hrnet/trt --device cuda`**





Traceback (most recent call last):
  File "tools/deploy.py", line 450, in <module>
    main()
  File "tools/deploy.py", line 121, in main
    deploy_cfg, model_cfg = load_config(deploy_cfg_path, model_cfg_path)
  File "/Downloads/mmdeploy/mmdeploy/utils/config_utils.py", line 36, in load_config
    configs.append(_load_config(cfg))
  File "/Downloads/mmdeploy/mmdeploy/utils/config_utils.py", line 22, in _load_config
    cfg = mmcv.Config.fromfile(cfg)
  File "/Downloads/mmdeploy/mmcv/mmcv/utils/config.py", line 340, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/Downloads/mmdeploy/mmcv/mmcv/utils/config.py", line 252, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/Downloads/mmdeploy/mmcv/mmcv/utils/config.py", line 183, in _file2dict
    check_file_exist(filename)
  File "/Downloads/mmdeploy/mmcv/mmcv/utils/path.py", line 24, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/_base_/default_runtime.py" does not exist

**Comment by RunningLeon** [comment]
@venkatshivap Hi, something wrong with your model config`hrnet_w48_coco_256x192.py`. It seems the base config path is not right `/base/default_runtime.py`. Pls make sure you are using the right config or if you modified config correctly.
