### ISSUE TITLE
10/03 12:43:16 - mmengine - ERROR - /project/openmmlab2/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed.

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdeploy#1154]
![image](https://user-images.githubusercontent.com/25839884/193504747-bd3b19d9-1b28-4d14-beb3-1b39994c1f31.png)

ONNX is success, trt failed

```shell
(mmyolo) ➜  mmdeploy git:(dev-1.x) ✗ python ./tools/deploy.py \
    configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py \
    $PATH_TO_MMDET/configs/yolo/yolov3_d53_8xb8-ms-608-273e_coco.py \
    https://download.openmmlab.com/mmdetection/v2.0/yolo/yolov3_d53_mstrain-608_273e_coco/yolov3_d53_mstrain-608_273e_coco_20210518_115020-a2c3acb8.pth \
    $PATH_TO_MMDET/demo/demo.jpg \
    --work-dir work_dir \
    --show \
    --device cuda:0 \
--dump-info 
[2022-10-03 12:56:42.756] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
[2022-10-03 12:56:44.517] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:45 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
[2022-10-03 12:56:47.396] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
10/03 12:56:47 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
10/03 12:56:48 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:48 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/03 12:56:48 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
http loads checkpoint from path: https://download.openmmlab.com/mmdetection/v2.0/yolo/yolov3_d53_mstrain-608_273e_coco/yolov3_d53_mstrain-608_273e_coco_20210518_115020-a2c3acb8.pth
10/03 12:56:51 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
10/03 12:56:51 - mmengine - INFO - Export PyTorch model to ONNX: work_dir/end2end.onnx.
10/03 12:56:51 - mmengine - WARNING - Can not find mmdet.models.detectors.rpn.RPN.simple_test, function rewrite will not be applied
10/03 12:56:51 - mmengine - WARNING - Can not find mmdet.models.utils.transformer.PatchMerging.forward, function rewrite will not be applied
/project/openmmlab2/mmdeploy/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/project/openmmlab2/mmdetection/mmdet/models/task_modules/prior_generators/anchor_generator.py:341: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/project/openmmlab2/mmdetection/mmdet/models/task_modules/prior_generators/anchor_generator.py:377: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  warnings.warn(
/project/openmmlab2/mmdetection/mmdet/models/task_modules/coders/yolo_bbox_coder.py:76: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(-1) == bboxes.size(-1) == 4
/project/openmmlab2/mmdeploy/mmdeploy/pytorch/functions/topk.py:56: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k > size:
/project/openmmlab2/mmdeploy/mmdeploy/codebase/mmdet/models/dense_heads/yolo_head.py:145: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  [topk_inds // self.num_classes, topk_inds % self.num_classes])
/project/openmmlab2/mmdeploy/mmdeploy/codebase/mmdet/models/layers/bbox_nms.py:259: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  dets, labels = TRTBatchedNMSop.apply(boxes, scores, int(scores.shape[-1]),
/project/openmmlab2/mmdeploy/mmdeploy/mmcv/ops/nms.py:178: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out_boxes = min(num_boxes, after_topk)
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
10/03 12:57:01 - mmengine - INFO - Execute onnx optimize passes.
10/03 12:57:03 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
[2022-10-03 12:57:06.548] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
10/03 12:57:06 - mmengine - INFO - Start pipeline mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt in subprocess
10/03 12:57:06 - mmengine - INFO - Successfully loaded tensorrt plugins from /project/openmmlab2/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
[10/03/2022-12:57:07] [TRT] [I] [MemUsageChange] Init CUDA: CPU +316, GPU +0, now: CPU 400, GPU 248 (MiB)
[10/03/2022-12:57:07] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 400 MiB, GPU 248 MiB
[10/03/2022-12:57:07] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 535 MiB, GPU 282 MiB
[10/03/2022-12:57:08] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[10/03/2022-12:57:08] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[10/03/2022-12:57:09] [TRT] [I] No importer registered for op: Mod. Attempting to import as plugin.
[10/03/2022-12:57:09] [TRT] [I] Searching for plugin: Mod, plugin_version: 1, plugin_namespace: 
Process Process-3:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/mmyolo/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ubuntu/miniconda3/envs/mmyolo/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/project/openmmlab2/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/project/openmmlab2/mmdeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "/project/openmmlab2/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 113, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 473 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

10/03 12:57:10 - mmengine - ERROR - /project/openmmlab2/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed.
```

# My Env

```shell
(mmyolo) ➜  mmdeploy git:(dev-1.x) ✗ python tools/check_env.py 
10/03 12:52:23 - mmengine - INFO - 

10/03 12:52:23 - mmengine - INFO - **********Environmental information**********
10/03 12:52:24 - mmengine - INFO - sys.platform: linux
10/03 12:52:24 - mmengine - INFO - Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
10/03 12:52:24 - mmengine - INFO - CUDA available: True
10/03 12:52:24 - mmengine - INFO - numpy_random_seed: 2147483648
10/03 12:52:24 - mmengine - INFO - GPU 0: Tesla T4
10/03 12:52:24 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.1
10/03 12:52:24 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.1, V11.1.74
10/03 12:52:24 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
10/03 12:52:24 - mmengine - INFO - PyTorch: 1.12.1
10/03 12:52:24 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

10/03 12:52:24 - mmengine - INFO - TorchVision: 0.13.1
10/03 12:52:24 - mmengine - INFO - OpenCV: 4.6.0
10/03 12:52:24 - mmengine - INFO - MMEngine: 0.1.0
10/03 12:52:24 - mmengine - INFO - MMCV: 2.0.0rc1
10/03 12:52:24 - mmengine - INFO - MMCV Compiler: GCC 7.5
10/03 12:52:24 - mmengine - INFO - MMCV CUDA Compiler: 11.1
10/03 12:52:24 - mmengine - INFO - MMDeploy: 0.7.0+d7cbb39
10/03 12:52:24 - mmengine - INFO - 

10/03 12:52:24 - mmengine - INFO - **********Backend information**********
10/03 12:52:24 - mmengine - INFO - onnxruntime: 1.8.1   ops_is_avaliable : True
10/03 12:52:24 - mmengine - INFO - tensorrt: 8.2.3.0    ops_is_avaliable : True
10/03 12:52:24 - mmengine - INFO - ncnn: None   ops_is_avaliable : False
10/03 12:52:24 - mmengine - INFO - pplnn_is_avaliable: False
10/03 12:52:24 - mmengine - INFO - openvino_is_avaliable: False
10/03 12:52:24 - mmengine - INFO - snpe_is_available: False
10/03 12:52:24 - mmengine - INFO - 

10/03 12:52:24 - mmengine - INFO - **********Codebase information**********
10/03 12:52:24 - mmengine - INFO - mmdet:       3.0.0rc1
10/03 12:52:24 - mmengine - INFO - mmseg:       None
10/03 12:52:24 - mmengine - INFO - mmcls:       1.0.0rc1
10/03 12:52:24 - mmengine - INFO - mmocr:       None
10/03 12:52:24 - mmengine - INFO - mmedit:      None
10/03 12:52:24 - mmengine - INFO - mmdet3d:     None
10/03 12:52:24 - mmengine - INFO - mmpose:      None
10/03 12:52:24 - mmengine - INFO - mmrotate:    None

```

**Comment by vansin** [comment]
```shell
(mmyolo) ➜  mmdeploy git:(dev-1.x) ✗ echo $LD_LIBRARY_PATH
/home/ubuntu/TensorRT-8.2.3.0/lib:/home/ubuntu/cuda/lib64:/home/ubuntu/onnxruntime-linux-x64-1.8.1/lib:/usr/local/cuda-11.1/lib64:/home/ubuntu/TensorRT-8.2.3.0
```

**Comment by vansin** [comment]
```shell
(mmyolo) ➜  mmdeploy git:(dev-1.x) ✗ pip list
Package            Version   Editable project location
------------------ --------- ------------------------------------
addict             2.4.0
aenum              3.1.11
albumentations     1.0.1
appdirs            1.4.4
asynctest          0.13.0
attributee         0.1.7
attrs              22.1.0
autopep8           1.7.0
brotlipy           0.7.0
certifi            2022.9.14
cffi               1.15.1
cfgv               3.3.1
charset-normalizer 2.1.1
cityscapesScripts  2.2.0
click              8.1.3
codecov            2.1.12
colorama           0.4.5
coloredlogs        15.0.1
commonmark         0.9.1
contourpy          1.0.5
coverage           6.5.0
cryptography       37.0.1
cycler             0.11.0
Cython             0.29.32
dill               0.3.5.1
distlib            0.3.6
docker-pycreds     0.4.0
dotty-dict         1.3.1
filelock           3.8.0
flake8             5.0.4
flatbuffers        22.9.24
fonttools          4.37.3
gitdb              4.0.9
GitPython          3.1.27
grpcio             1.49.1
h5py               3.7.0
humanfriendly      10.0
identify           2.5.5
idna               3.4
imagecorruptions   1.1.2
imageio            2.22.0
importlib-metadata 4.12.0
iniconfig          1.1.1
interrogate        1.5.0
isort              4.3.21
joblib             1.2.0
kiwisolver         1.4.4
kwarray            0.6.4
lap                0.4.0
Mako               1.2.3
Markdown           3.4.1
MarkupSafe         2.1.1
matplotlib         3.6.0
mccabe             0.7.0
mkl-fft            1.3.1
mkl-random         1.2.2
mkl-service        2.4.0
mmcls              1.0.0rc1  /project/openmmlab2/mmclassification
mmcv               2.0.0rc1  /project/openmmlab2/mmcv
mmdeploy           0.7.0     /project/openmmlab2/mmdeploy
mmdet              3.0.0rc1  /project/openmmlab2/mmdetection
mmengine           0.1.0     /project/openmmlab2/mmengine
mmyolo             0.1.1     /project/openmmlab2/mmyolo
model-index        0.1.11
motmetrics         1.2.5
mpmath             1.2.1
multiprocess       0.70.13
networkx           2.8.6
ninja              1.10.2.4
nodeenv            1.7.0
numpy              1.22.4
onnx               1.12.0
onnxruntime        1.8.1
opencv-python      4.6.0.66
openmim            0.3.1
ordered-set        4.1.0
packaging          21.3
pandas             1.3.5
pathtools          0.1.2
Pillow             9.2.0
pip                22.1.2
platformdirs       2.5.2
pluggy             1.0.0
pre-commit         2.20.0
promise            2.3
protobuf           3.20.1
psutil             5.9.2
py                 1.11.0
pycocotools        2.0.5
pycodestyle        2.9.1
pycparser          2.21
pycuda             2022.1
pyflakes           2.5.0
Pygments           2.13.0
pyOpenSSL          22.0.0
pyparsing          3.0.9
pyquaternion       0.9.9
PySocks            1.7.1
pytest             7.1.3
python-dateutil    2.8.2
pytools            2022.1.12
pytz               2022.2.1
PyWavelets         1.4.1
PyYAML             6.0
requests           2.28.1
rich               12.5.1
scikit-image       0.19.3
scikit-learn       1.1.2
scipy              1.7.3
seaborn            0.12.0
sentry-sdk         1.9.8
setproctitle       1.3.2
setuptools         63.4.1
shortuuid          1.0.9
six                1.16.0
sklearn            0.0
smmap              5.0.0
sympy              1.11.1
tabulate           0.8.10
tensorrt           8.2.3.0
termcolor          2.0.1
terminaltables     3.1.10
threadpoolctl      3.1.0
tifffile           2022.8.12
timm               0.6.7
toml               0.10.2
tomli              2.0.1
torch              1.12.1
torchvision        0.13.1
tqdm               4.64.1
typing             3.7.4.3
typing_extensions  4.3.0
ubelt              1.2.2
urllib3            1.26.12
virtualenv         20.16.5
wandb              0.13.3
wheel              0.37.1
xdoctest           1.1.0
xmltodict          0.13.0
yapf               0.32.0
zipp               3.8.1
```

**Comment by vansin** [comment]
The Pytorch 1.12.1 is too high, and success in pytorch 1.12.1

**Comment by Louis8582** [comment]
> The Pytorch 1.12.1 is too high, and success in pytorch 1.12.1

I have the same error. But I cant get your info. Could you talk to me whitch version is success?
