### ISSUE TITLE
UT ImportError: libnvonnxparser.so.8 cannot open shared object file

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmdeploy#116]
Thanks for your bug report. We appreciate it a lot.

**Checklist**

**Describe the bug**

```
[2022-01-28T05:06:01.903Z] [2022-01-28 13:06:00.295] [mmdeploy] [info] Register 'DirectoryModel'

[2022-01-28T05:06:01.904Z] Traceback (most recent call last):

[2022-01-28T05:06:01.904Z]   File "tools/check_env.py", line 108, in <module>

[2022-01-28T05:06:01.904Z]     check_backend()

[2022-01-28T05:06:01.904Z]   File "tools/check_env.py", line 25, in check_backend

[2022-01-28T05:06:01.904Z]     import mmdeploy.apis.onnxruntime as ort_apis

[2022-01-28T05:06:01.904Z]   File "/opt/mmdeploy/mmdeploy/apis/onnxruntime/__init__.py", line 2, in <module>

[2022-01-28T05:06:01.904Z]     from mmdeploy.backend.onnxruntime import is_available, is_plugin_available

[2022-01-28T05:06:01.904Z]   File "/opt/mmdeploy/mmdeploy/backend/__init__.py", line 7, in <module>

[2022-01-28T05:06:01.904Z]     from mmdeploy.backend.tensorrt import is_available as trt_available

[2022-01-28T05:06:01.904Z]   File "/opt/mmdeploy/mmdeploy/backend/tensorrt/__init__.py", line 33, in <module>

[2022-01-28T05:06:01.904Z]     from .utils import create_trt_engine, load_trt_engine, save_trt_engine

[2022-01-28T05:06:01.904Z]   File "/opt/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 6, in <module>

[2022-01-28T05:06:01.904Z]     import tensorrt as trt

[2022-01-28T05:06:01.904Z]   File "/opt/conda/lib/python3.7/site-packages/tensorrt/__init__.py", line 67, in <module>

[2022-01-28T05:06:01.904Z]     from .tensorrt import *

[2022-01-28T05:06:01.904Z] ImportError: libnvonnxparser.so.8: cannot open shared object file: No such file or directory

```
**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

**Environment**

```

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:57,995 - mmdeploy - INFO - **********Environmental information**********

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,898 - mmdeploy - INFO - sys.platform: linux

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,899 - mmdeploy - INFO - Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,899 - mmdeploy - INFO - CUDA available: True

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,899 - mmdeploy - INFO - GPU 0: Tesla T4

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,900 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,900 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.89

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,900 - mmdeploy - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,900 - mmdeploy - INFO - PyTorch: 1.9.0

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,900 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:

[2022-01-28T05:06:01.903Z]   - GCC 7.3

[2022-01-28T05:06:01.903Z]   - C++ Version: 201402

[2022-01-28T05:06:01.903Z]   - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications

[2022-01-28T05:06:01.903Z]   - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)

[2022-01-28T05:06:01.903Z]   - OpenMP 201511 (a.k.a. OpenMP 4.5)

[2022-01-28T05:06:01.903Z]   - NNPACK is enabled

[2022-01-28T05:06:01.903Z]   - CPU capability usage: AVX

[2022-01-28T05:06:01.903Z]   - CUDA Runtime 10.2

[2022-01-28T05:06:01.903Z]   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37

[2022-01-28T05:06:01.903Z]   - CuDNN 7.6.5

[2022-01-28T05:06:01.903Z]   - Magma 2.5.2

[2022-01-28T05:06:01.903Z]   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

[2022-01-28T05:06:01.903Z] 

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,900 - mmdeploy - INFO - TorchVision: 0.10.0

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,901 - mmdeploy - INFO - OpenCV: 4.5.4

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,901 - mmdeploy - INFO - MMCV: 1.4.0

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,901 - mmdeploy - INFO - MMCV Compiler: GCC 7.5

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,901 - mmdeploy - INFO - MMCV CUDA Compiler: 10.2

[2022-01-28T05:06:01.903Z] 2022-01-28 13:05:59,901 - mmdeploy - INFO - MMDeployment: 0.1.0+230596b

```

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by RunningLeon** [comment]
Maybe TensorRT required cuda version is not met in your env. Could try to reinstall TensorRT.

**Comment by RunningLeon** [comment]
closed due to age.

**Comment by JinqingZhengTju** [comment]
I also encountered this problem, have you solved it?
