### ISSUE TITLE
GFLHead(mmdetection) + TensorRT error.

### ISSUE THREAD

**Issue by Richard-mei** [open-mmlab/mmdeploy#120]
### run:
```shell
python ./tools/deploy.py configs/mmdet/detection/detection_tensorrt_dynamic-160x160-608x608.py ../mmdetection/configs/gfl/gfl_r50_fpn_1x_coco.py ../mmdetection/checkpoints/gfl_r50_fpn_1x_coco_20200629_121244-25944287.pth ../mmdetection/demo/demo.jpg --work-dir test_work/test_gfl/ --show --device cuda:0`
```

### `base_dense_head` error:
```shell
2022-01-29:01:55:51,root ERROR    [utils.py:41] 
Traceback (most recent call last):
  File "/home/richard/Projects/MMDeploy/mmdeploy/utils/utils.py", line 36, in target_wrapper
    result = target(*args, **kwargs)
  File "/home/richard/Projects/MMDeploy/mmdeploy/apis/pytorch2onnx.py", line 92, in torch2onnx
    torch2onnx_impl(
  File "/home/richard/Projects/MMDeploy/mmdeploy/apis/pytorch2onnx.py", line 42, in torch2onnx_impl
    torch.onnx.export(
  File "/home/richard/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/richard/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/richard/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 691, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/richard/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 454, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args,
  File "/home/richard/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 417, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/richard/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 377, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/richard/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/jit/_trace.py", line 1139, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/richard/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/richard/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/jit/_trace.py", line 125, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/richard/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/jit/_trace.py", line 116, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/richard/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/richard/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/richard/Projects/MMDeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 177, in wrapper
    return self.func(self, *args, **kwargs)
  File "/home/richard/Projects/MMDeploy/mmdeploy/codebase/mmdet/models/detectors/base.py", line 69, in base_detector__forward
    return __forward_impl(ctx, self, img, img_metas=img_metas, **kwargs)
  File "/home/richard/Projects/MMDeploy/mmdeploy/core/optimizers/function_marker.py", line 247, in g
    rets = f(*args, **kwargs)
  File "/home/richard/Projects/MMDeploy/mmdeploy/codebase/mmdet/models/detectors/base.py", line 28, in __forward_impl
    return self.simple_test(img, img_metas, **kwargs)
  File "/home/richard/Projects/MMDeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 177, in wrapper
    return self.func(self, *args, **kwargs)
  File "/home/richard/Projects/MMDeploy/mmdeploy/codebase/mmdet/models/detectors/single_stage.py", line 28, in single_stage_detector__simple_test
    return self.bbox_head.simple_test(feat, img_metas, **kwargs)
  File "/home/richard/Projects/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 360, in simple_test
    return self.simple_test_bboxes(feats, img_metas, rescale=rescale)
  File "/home/richard/Projects/mmdetection/mmdet/models/dense_heads/dense_test_mixins.py", line 37, in simple_test_bboxes
    results_list = self.get_bboxes(
  File "/home/richard/Projects/MMDeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 177, in wrapper
    return self.func(self, *args, **kwargs)
  File "/home/richard/Projects/MMDeploy/mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py", line 219, in base_dense_head__get_bbox
    batch_bboxes = self.bbox_coder.decode(
  File "/home/richard/Projects/mmdetection/mmdet/core/bbox/coder/distance_point_bbox_coder.py", line 59, in decode
    assert points.size(-1) == 2
AssertionError
2022-01-29 01:55:51,883 - mmdeploy - ERROR - torch2onnx failed.
```

**Comment by RunningLeon** [comment]
@Richard-mei Hi, sorry to say that GFL is not supported up to now as suggested [here](https://mmdeploy.readthedocs.io/en/latest/codebases/mmdet.html#list-of-mmdetection-models-supported-by-mmdeploy). If it is OK, you can support it by your self.

**Comment by Richard-mei** [comment]
> @RunningLeon 
OK，thank you for your reply.

**Comment by Richard-mei** [comment]
I have initially solved this problem，but the code is rough.  
the main problems are as follows：  
- 1. GFLHead use `anchor_center` to convert `xyxy` box to `xy`，and then use `distance2bbox` decode;
- 2. bbox_pred must scale to ori image on inference;
- 3. most important：`Integral` module should computed in `forward` for inference. (mmdetection)

**Comment by RunningLeon** [comment]
> I have initially solved this problem，but the code is rough. the main problems are as follows：
> 
>     * 1. GFLHead use `anchor_center` to convert `xyxy` box to `xy`，and then use `distance2bbox` decode;
> 
>     * 2. bbox_pred must scale to ori image on inference;
> 
>     * 3. most important：`Integral` module should computed in `forward` for inference. (mmdetection)

@Richard-mei Great, good to hear that. Looking forward to your PR if possible. :nerd_face:

**Comment by cydiachen** [comment]
> > I have initially solved this problem，but the code is rough. the main problems are as follows：
> > ```
> > * 1. GFLHead use `anchor_center` to convert `xyxy` box to `xy`，and then use `distance2bbox` decode;
> > 
> > * 2. bbox_pred must scale to ori image on inference;
> > 
> > * 3. most important：`Integral` module should computed in `forward` for inference. (mmdetection)
> > ```
> 
> @Richard-mei Great, good to hear that. Looking forward to your PR if possible. 🤓


> I have initially solved this problem，but the code is rough. the main problems are as follows：
> 
> * 1. GFLHead use `anchor_center` to convert `xyxy` box to `xy`，and then use `distance2bbox` decode;
> * 2. bbox_pred must scale to ori image on inference;
> * 3. most important：`Integral` module should computed in `forward` for inference. (mmdetection)

hello, Richard. I am now working on intergrating post_process procedure into onnx model. But I have some issues on rescaling bbox_pred. I am glad if you can provide me with some kindly help.

**Comment by Richard-mei** [comment]
@cydiachen Hi，what's your problem?
