### ISSUE TITLE
Error when export swin model to onnx.

### ISSUE THREAD

**Issue by abetancordelrosario** [open-mmlab/mmdeploy#1202]
Error when export to onnx

Are Swin models supported for mmseg?

---------------------------------------------------------------------------------
python mmdeploy/tools/deploy.py     mmdeploy/configs/mmseg/segmentation_tensorrt_static-512x1024.py     mmsegmentation/configs/swin/upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_22K.py      mmsegmentation/checkpoints/upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_22K_20210531_125459-429057bf.pth     mmsegmentation/demo/demo.png     --work-dir mmdeploy/work-dir --show --device cuda:0 --dump-info                             
..........
..........
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
2022-10-14 09:51:01,738 - mmdeploy - INFO - Execute onnx optimize passes.
2022-10-14 09:51:46,852 - mmdeploy - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
2022-10-14 09:52:12,573 - mmdeploy - INFO - Start pipeline mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt in subprocess
2022-10-14 09:52:13,049 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /code/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
Process Process-3:
Traceback (most recent call last):
  File "/root/archiconda3/envs/mmdeploy/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/root/archiconda3/envs/mmdeploy/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/code/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/code/mmdeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 88, in onnx2tensorrt
    device_id=device_id)
  File "/code/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 165, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node -1 (importPad): UNSUPPORTED_NODE: Assertion failed: inputs.at(1).is_weights()

2022-10-14 09:52:28,598 - mmdeploy - ERROR - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed. exit.

**Comment by RunningLeon** [comment]
@abetancordelrosario Hi, could you run `python tools/check_env.py` and post env info here?

**Comment by abetancordelrosario** [comment]
2022-10-17 07:08:56,185 - mmdeploy - INFO -

2022-10-17 07:08:56,186 - mmdeploy - INFO - **********Environmental information**********
2022-10-17 07:09:02,456 - mmdeploy - INFO - sys.platform: linux
2022-10-17 07:09:02,457 - mmdeploy - INFO - Python: 3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 19:12:04) [GCC 9.4.0]
2022-10-17 07:09:02,457 - mmdeploy - INFO - CUDA available: True
2022-10-17 07:09:02,457 - mmdeploy - INFO - GPU 0: Xavier
2022-10-17 07:09:02,457 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2022-10-17 07:09:02,458 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.89
2022-10-17 07:09:02,458 - mmdeploy - INFO - GCC: gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
2022-10-17 07:09:02,458 - mmdeploy - INFO - PyTorch: 1.10.0
2022-10-17 07:09:02,458 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_53,code=sm_53;-gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72
  - CuDNN 8.0
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=8.0.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -DMISSING_ARM_VST1 -DMISSING_ARM_VLD1 -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=open, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON,

2022-10-17 07:09:02,459 - mmdeploy - INFO - TorchVision: 0.11.1
2022-10-17 07:09:02,459 - mmdeploy - INFO - OpenCV: 4.6.0
2022-10-17 07:09:02,459 - mmdeploy - INFO - MMCV: 1.4.0
2022-10-17 07:09:02,459 - mmdeploy - INFO - MMCV Compiler: GCC 7.5
2022-10-17 07:09:02,459 - mmdeploy - INFO - MMCV CUDA Compiler: 10.2
2022-10-17 07:09:02,460 - mmdeploy - INFO - MMDeploy: 0.9.0+c35099e
2022-10-17 07:09:02,460 - mmdeploy - INFO -

2022-10-17 07:09:02,460 - mmdeploy - INFO - **********Backend information**********
2022-10-17 07:09:05,102 - mmdeploy - INFO - onnxruntime: None   ops_is_avaliable : False
2022-10-17 07:09:05,218 - mmdeploy - INFO - tensorrt: 7.1.3.0   ops_is_avaliable : True
2022-10-17 07:09:05,282 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-10-17 07:09:05,286 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-10-17 07:09:05,288 - mmdeploy - INFO - openvino_is_avaliable: False
2022-10-17 07:09:05,353 - mmdeploy - INFO - snpe_is_available: False
2022-10-17 07:09:05,357 - mmdeploy - INFO - ascend_is_available: False
2022-10-17 07:09:05,360 - mmdeploy - INFO - coreml_is_available: False
2022-10-17 07:09:05,360 - mmdeploy - INFO -

2022-10-17 07:09:05,360 - mmdeploy - INFO - **********Codebase information**********
2022-10-17 07:09:05,369 - mmdeploy - INFO - mmdet:      2.25.2
2022-10-17 07:09:05,369 - mmdeploy - INFO - mmseg:      0.28.0
2022-10-17 07:09:05,369 - mmdeploy - INFO - mmcls:      None
2022-10-17 07:09:05,369 - mmdeploy - INFO - mmocr:      None
2022-10-17 07:09:05,370 - mmdeploy - INFO - mmedit:     None
2022-10-17 07:09:05,370 - mmdeploy - INFO - mmdet3d:    None
2022-10-17 07:09:05,370 - mmdeploy - INFO - mmpose:     None
2022-10-17 07:09:05,370 - mmdeploy - INFO - mmrotate:   None

**Comment by RunningLeon** [comment]
@abetancordelrosario Hi, pls update your tensorrt to 8.2. works fine on my side.

**Comment by abetancordelrosario** [comment]
Where can I download tensorrt 8.2 for cuda10.2 and ARM?

**Comment by RunningLeon** [comment]
> Where can I download tensorrt 8.2 for cuda10.2 and ARM?

pls. refer to this [doc](https://mmdeploy.readthedocs.io/en/latest/05-supported-backends/tensorrt.html#install-tensorrt)
