### ISSUE TITLE
When convert .onnx model to TensorRT model and set the batchsize more than 1, it reports the error: assert engine is not None, 'Failed to create TensorRT engine'. 

### ISSUE THREAD

**Issue by JinqingZhengTju** [open-mmlab/mmdeploy#1212]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

When convert .onnx model to TensorRT model and set the batchsize more than 1, it reports the error: assert engine is not None, 'Failed to create TensorRT engine'. That is the builded engine is None. I don't know the reason. When set the batchsize is 1, it can convert the model successfully. But when set as follows, it occurs error. The configs are as follows:

_base_ = ['./rotated-detection_static.py', '../_base_/backends/tensorrt.py']

onnx_config = dict(
output_names=['dets', 'labels'],
input_shape=None,
dynamic_axes={
'input': {
0: 'batch',
2: 'height',
3: 'width'
},
'dets': {
0: 'batch',
1: 'num_dets',
},
'labels': {
0: 'batch',
1: 'num_dets',
},
},
)

backend_config = dict(
common_config=dict(max_workspace_size=1 << 30),
model_inputs=[
dict(
input_shapes=dict(
input=dict(
min_shape=[1, 3, 320, 320],
opt_shape=[4, 3, 1024, 1024],
max_shape=[8, 3, 1024, 1024])))
])

### Reproduction

1. The script is: rotated-detection_tensorrt_dynamic-320x320-1024x1024.py
2. I modify it as follows:

backend_config = dict(
common_config=dict(max_workspace_size=1 << 30),
model_inputs=[
dict(
input_shapes=dict(
input=dict(
min_shape=[1, 3, 320, 320],
opt_shape=[4, 3, 1024, 1024],
max_shape=[8, 3, 1024, 1024])))
])

### Environment

```Shell
2022-10-17 19:27:35,666 - mmdeploy - INFO - 

2022-10-17 19:27:35,666 - mmdeploy - INFO - **********Environmental information**********
2022-10-17 19:27:35,783 - mmdeploy - INFO - sys.platform: linux
2022-10-17 19:27:35,783 - mmdeploy - INFO - Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
2022-10-17 19:27:35,783 - mmdeploy - INFO - CUDA available: True
2022-10-17 19:27:35,783 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3090
2022-10-17 19:27:35,783 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2022-10-17 19:27:35,783 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.109
2022-10-17 19:27:35,783 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2022-10-17 19:27:35,783 - mmdeploy - INFO - PyTorch: 1.10.2
2022-10-17 19:27:35,783 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
- GCC 7.3
- C++ Version: 201402
- Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
- Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
- OpenMP 201511 (a.k.a. OpenMP 4.5)
- LAPACK is enabled (usually provided by MKL)
- NNPACK is enabled
- CPU capability usage: AVX512
- CUDA Runtime 11.3
- NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
- CuDNN 8.2
- Magma 2.5.2
- Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

2022-10-17 19:27:35,783 - mmdeploy - INFO - TorchVision: 0.11.3
2022-10-17 19:27:35,783 - mmdeploy - INFO - OpenCV: 4.6.0
2022-10-17 19:27:35,783 - mmdeploy - INFO - MMCV: 1.6.0
2022-10-17 19:27:35,783 - mmdeploy - INFO - MMCV Compiler: GCC 9.4
2022-10-17 19:27:35,783 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2022-10-17 19:27:35,783 - mmdeploy - INFO - MMDeploy: 0.7.0+8a40f19
2022-10-17 19:27:35,783 - mmdeploy - INFO - 

2022-10-17 19:27:35,783 - mmdeploy - INFO - **********Backend information**********
2022-10-17 19:27:36,981 - mmdeploy - INFO - onnxruntime: 1.10.0 ops_is_avaliable : True
2022-10-17 19:27:37,012 - mmdeploy - INFO - tensorrt: 8.2.3.0 ops_is_avaliable : True
2022-10-17 19:27:37,046 - mmdeploy - INFO - ncnn: None ops_is_avaliable : False
2022-10-17 19:27:37,047 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-10-17 19:27:37,054 - mmdeploy - INFO - openvino_is_avaliable: False
2022-10-17 19:27:37,093 - mmdeploy - INFO - snpe_is_available: False
2022-10-17 19:27:37,093 - mmdeploy - INFO - 

2022-10-17 19:27:37,093 - mmdeploy - INFO - **********Codebase information**********
2022-10-17 19:27:37,094 - mmdeploy - INFO - mmdet: 2.25.1
2022-10-17 19:27:37,094 - mmdeploy - INFO - mmseg: None
2022-10-17 19:27:37,094 - mmdeploy - INFO - mmcls: 0.23.2
2022-10-17 19:27:37,094 - mmdeploy - INFO - mmocr: None
2022-10-17 19:27:37,094 - mmdeploy - INFO - mmedit: None
2022-10-17 19:27:37,094 - mmdeploy - INFO - mmdet3d: None
2022-10-17 19:27:37,094 - mmdeploy - INFO - mmpose: None
2022-10-17 19:27:37,094 - mmdeploy - INFO - mmrotate: 0.3.2
```

**Comment by grimoire** [comment]
Which model are you using? I can not reproduce the same error.

**Comment by JinqingZhengTju** [comment]
> Which model are you using? I can not reproduce the same error.

The model I used is oriented R-CNN. The training cfg is oriented_rcnn_r50_fpn_3x_dota_le90.py and the deploy cfg is rotated-detection_tensorrt-int8_dynamic-320x320-1024x1024.py  which is modified by myself. The deploy cfg is:
_base_ = ['./rotated-detection_tensorrt_dynamic-320x320-1024x1024.py']

backend_config = dict(common_config=dict(int8_mode=True))

calib_config = dict(create_calib=True, calib_file='calib_data.h5')

**Comment by grimoire** [comment]
Ok. If you want to do the calibration. The opt_shape should have batch_size==1 since the calibration data would be created follow that shape.

**Comment by JinqingZhengTju** [comment]
> Ok. If you want to do the calibration. The opt_shape should have batch_size==1 since the calibration data would be created follow that shape.

I have tried this solution. The config is as follows:
backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 320, 320],
                    opt_shape=[1, 3, 1024, 1024],
                    max_shape=[8, 3, 1024, 1024])))
    ])
But the result is the same as before. When run deploy.py, the error is reported as follows:
Process Process-4:
Traceback (most recent call last):
  File "/home/zjq/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/zjq/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zjq/open-mmlab/MMDeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/zjq/open-mmlab/MMDeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 88, in onnx2tensorrt
    device_id=device_id)
  File "/home/zjq/open-mmlab/MMDeploy/mmdeploy/backend/tensorrt/utils.py", line 153, in from_onnx
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine
2022-10-21 18:42:48,550 - mmdeploy - ERROR - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 2 failed. exit.

**Comment by JinqingZhengTju** [comment]
> Ok. If you want to do the calibration. The opt_shape should have batch_size==1 since the calibration data would be created follow that shape.

It can run successfully when set the config as follows:
backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[2, 3, 320, 320],
                    opt_shape=[2, 3, 1024, 1024],
                    max_shape=[2, 3, 1024, 1024])))
    ])
But this kind of config only supports the fixed inference batch size.

**Comment by grimoire** [comment]
Still can not reproduce the error. Is `oriented_rcnn_r50_fpn_3x_dota_le90.py` share same model as `oriented_rcnn_r50_fpn_1x_dota_le90.py`? Can you provide full error log?

**Comment by JinqingZhengTju** [comment]
> Still can not reproduce the error. Is `oriented_rcnn_r50_fpn_3x_dota_le90.py` share same model as `oriented_rcnn_r50_fpn_1x_dota_le90.py`? Can you provide full error log?

I find converting rotated models with dynamic batch size all has this error. This is the total error when running the deploy.py with this kind of config:
[10/30/2022-11:59:12] [TRT] [W] Skipping tactic 0 due to insuficient memory on requested size of 6968647680 detected for tactic 0.
Process Process-4:
Traceback (most recent call last):
  File "/home/zjq/anaconda3/envs/svd/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/zjq/anaconda3/envs/svd/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/media/zjq/Data/Ubuntu_Project/svd/MMDeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/media/zjq/Data/Ubuntu_Project/svd/MMDeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 88, in onnx2tensorrt
    device_id=device_id)
  File "/media/zjq/Data/Ubuntu_Project/svd/MMDeploy/mmdeploy/backend/tensorrt/utils.py", line 215, in from_onnx
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine
[10/30/2022-11:59:12] [TRT] [E] 10: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[Unsqueeze_419...Slice_725]}.)
2022-10-30 11:59:13,464 - mmdeploy - ERROR - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 2 failed. exit.

Process finished with exit code 1

**Comment by grimoire** [comment]
Ok, I see.
TensorRT will fuse some ops, which might require more workspace. `{ForeignNode[Unsqueeze_419...Slice_725]}` might be a fused node. And there are reports about extremely high workspace usage on the special TensorRT version. 
It looks like your conversion meets the same circumstance. Try switching to a new TensorRT version. (Note that TensorRT8.4 has issue about dynamic batch gather. )

**Comment by JinqingZhengTju** [comment]
> 

Thanks for your reply. I will try to switch to TensorRT8.5 to see whether this problem can be solved.

**Comment by SirojbekSafarov** [comment]
> > 
> 
> Thanks for your reply. I will try to switch to TensorRT8.5 to see whether this problem can be solved.

Hello, I am also faced with this problem did you solve it? When you faced this problem what was your trt version?

**Comment by SirojbekSafarov** [comment]
I tried TensorRT 8.5 but it didn't work. Dou you have any idea how to solve this?

**Comment by grimoire** [comment]
@SirojbekSafarov  please provide your config and environment.
