### ISSUE TITLE
[Bug] `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit

### ISSUE THREAD

**Issue by yitian8377** [open-mmlab/mmdeploy#1228]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

/home/yt/.conda/envs/mmdeploy/bin/python /data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/tools/deploy.py mmdeploy_v0.9.0/configs/mmdet/detection/single-stage_ncnn_static-416x416.py mmdetection_v2.25.2/configs/yolox/yolox_tiny_8x8_300e_coco.py checkpoints/yolox_tiny_8x8_300e_coco_20211124_171234-b4047906.pth mmdetection_v2.25.2/demo/demo.jpg --device cuda --work-dir mmdeploy_model/yolox --dump-info
2022-10-20 11:19:02,026 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
load checkpoint from local path: checkpoints/yolox_tiny_8x8_300e_coco_20211124_171234-b4047906.pth
2022-10-20 11:19:05,193 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-10-20 11:19:05,194 - mmdeploy - INFO - Export PyTorch model to ONNX: mmdeploy_model/yolox/end2end.onnx.
/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/pytorch/functions/getattribute.py:18: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ret = torch.Size([int(s) for s in ret])
/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/codebase/mmdet/models/detectors/base.py:24: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  img_shape = [int(val) for val in img_shape]
/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/codebase/mmdet/models/detectors/base.py:24: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  img_shape = [int(val) for val in img_shape]
Process Process-2:
Traceback (most recent call last):
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/apis/pytorch2onnx.py", line 96, in torch2onnx
    export(
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/apis/onnx/export.py", line 122, in export
    torch.onnx.export(
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/core/rewriters/rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/apis/onnx/optimizer.py", line 10, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 727, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 602, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 517, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/jit/_trace.py", line 1175, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/core/rewriters/rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/codebase/mmdet/models/detectors/base.py", line 70, in base_detector__forward
    return __forward_impl(ctx, self, img, img_metas=img_metas, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/core/optimizers/function_marker.py", line 261, in g
    rets = f(*args, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/codebase/mmdet/models/detectors/base.py", line 26, in __forward_impl
    return self.simple_test(img, img_metas, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/core/rewriters/rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdeploy_v0.9.0/mmdeploy/codebase/mmdet/models/detectors/single_stage.py", line 27, in single_stage_detector__simple_test
    feat = self.extract_feat(img)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdetection_v2.25.2/mmdet/models/detectors/single_stage.py", line 45, in extract_feat
    x = self.neck(x)
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yt/.conda/envs/mmdeploy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yt/Python/MMCV/mmdetection_v2.25.2/mmdet/models/necks/yolox_pafpn.py", line 139, in forward
    torch.cat([upsample_feat, feat_low], 1))
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 36 but got size 35 for tensor number 1 in the list.
2022-10-20 11:19:06,754 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

Process finished with exit code 1

### Reproduction

command: 1)  python3 tools/scripts/build_ubuntu_x64_ncnn.py
                       2)   python mmdeploy_v0.9.0/tools/deploy.py
                              mmdeploy_v0.9.0/configs/mmdet/detection/single-stage_ncnn_static-416x416.py
                             mmdetection_v2.25.2/configs/yolox/yolox_tiny_8x8_300e_coco.py
                             checkpoints/yolox_tiny_8x8_300e_coco_20211124_171234-b4047906.pth
                             mmdetection_v2.25.2/demo/demo.jpg
                             --device cuda
                             --work-dir
                            mmdeploy_model/yolox
                             --dump-info

### Environment

```Shell
python  mmdeploy_v0.9.0/tools/check_env.py
2022-10-20 11:11:19,674 - mmdeploy - INFO - 

2022-10-20 11:11:19,674 - mmdeploy - INFO - **********Environmental information**********
2022-10-20 11:11:20,086 - mmdeploy - INFO - sys.platform: linux
2022-10-20 11:11:20,087 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
2022-10-20 11:11:20,087 - mmdeploy - INFO - CUDA available: True
2022-10-20 11:11:20,087 - mmdeploy - INFO - GPU 0,1,2,3,4,5,6,7: NVIDIA TITAN Xp
2022-10-20 11:11:20,087 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda-10.2
2022-10-20 11:11:20,087 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.8
2022-10-20 11:11:20,087 - mmdeploy - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
2022-10-20 11:11:20,087 - mmdeploy - INFO - PyTorch: 1.12.1
2022-10-20 11:11:20,087 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

2022-10-20 11:11:20,087 - mmdeploy - INFO - TorchVision: 0.13.1
2022-10-20 11:11:20,087 - mmdeploy - INFO - OpenCV: 4.6.0
2022-10-20 11:11:20,087 - mmdeploy - INFO - MMCV: 1.6.2
2022-10-20 11:11:20,087 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2022-10-20 11:11:20,087 - mmdeploy - INFO - MMCV CUDA Compiler: 10.2
2022-10-20 11:11:20,087 - mmdeploy - INFO - MMDeploy: 0.9.0+917643f
2022-10-20 11:11:20,087 - mmdeploy - INFO - 

2022-10-20 11:11:20,087 - mmdeploy - INFO - **********Backend information**********
2022-10-20 11:11:20,773 - mmdeploy - INFO - onnxruntime: 1.12.1	ops_is_avaliable : False
2022-10-20 11:11:20,813 - mmdeploy - INFO - tensorrt: 8.2.3.0	ops_is_avaliable : False
2022-10-20 11:11:20,833 - mmdeploy - INFO - ncnn: 1.0.20221017	ops_is_avaliable : True
2022-10-20 11:11:20,834 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-10-20 11:11:20,835 - mmdeploy - INFO - openvino_is_avaliable: False
2022-10-20 11:11:20,854 - mmdeploy - INFO - snpe_is_available: False
2022-10-20 11:11:20,855 - mmdeploy - INFO - ascend_is_available: False
2022-10-20 11:11:20,856 - mmdeploy - INFO - coreml_is_available: False
2022-10-20 11:11:20,856 - mmdeploy - INFO - 

2022-10-20 11:11:20,857 - mmdeploy - INFO - **********Codebase information**********
2022-10-20 11:11:20,858 - mmdeploy - INFO - mmdet:	2.25.2
2022-10-20 11:11:20,858 - mmdeploy - INFO - mmseg:	None
2022-10-20 11:11:20,858 - mmdeploy - INFO - mmcls:	None
2022-10-20 11:11:20,858 - mmdeploy - INFO - mmocr:	None
2022-10-20 11:11:20,858 - mmdeploy - INFO - mmedit:	None
2022-10-20 11:11:20,858 - mmdeploy - INFO - mmdet3d:	None
2022-10-20 11:11:20,858 - mmdeploy - INFO - mmpose:	None
2022-10-20 11:11:20,858 - mmdeploy - INFO - mmrotate:	None

Process finished with exit code 0
```

**Comment by Louis8582** [comment]
I have the same error.  Do you know how to solved now?

**Comment by sebos123** [comment]
Same problem here.

**Comment by lizheng1992** [comment]
I have the same error. Do you know how to solved now?
