### ISSUE TITLE
[Bug] 使用deploy.py转换模型时报错

### ISSUE THREAD

**Issue by kc-w** [open-mmlab/mmdeploy#1281]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

转换模型时报
Process Process-2:
Traceback (most recent call last):
  File "D:\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "E:\projectTest\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "E:\projectTest\mmdeploy\mmdeploy\apis\pytorch2onnx.py", line 63, in torch2onnx
    data, model_inputs = task_processor.create_input(img, input_shape)
  File "E:\projectTest\mmdeploy\mmdeploy\codebase\mmseg\deploy\segmentation.py", line 128, in create_input
    cfg = process_model_config(self.model_cfg, imgs, input_shape)
  File "E:\projectTest\mmdeploy\mmdeploy\codebase\mmseg\deploy\segmentation.py", line 35, in process_model_config
    cfg.data.test.pipeline[0] = LoadImage()
  File "e:\projecttest\mmcv\mmcv\utils\config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'data'
2022-11-01 19:39:44,034 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

### Reproduction

    parser = argparse.ArgumentParser(description='Export model to backends.')
    parser.add_argument('--deploy_cfg', default='E:/projectTest/mmdeploy/configs/mmseg/segmentation_tensorrt-fp16_dynamic-512x1024-2048x2048.py',
                        help='deploy config path')
    parser.add_argument('--model_cfg', default='E:/projectTest/mmsegmentation/configs/_base_/models/pspnet_r50-d8.py',
                        help='model config path')
    parser.add_argument('--checkpoint', default='E:/projectTest/mmsegmentation/result/iter_200.pth',
                        help='model checkpoint path')
    parser.add_argument('--img', default='D:/images/mask/img_dir/train/Image_20220626151509704.jpg',
                        help='image used to convert model model')

### Environment

```Shell
2022-11-01 19:19:35,472 - mmdeploy - INFO - **********Environmental information**********
2022-11-01 19:19:40,942 - mmdeploy - INFO - sys.platform: win32
2022-11-01 19:19:40,942 - mmdeploy - INFO - Python: 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]
2022-11-01 19:19:40,942 - mmdeploy - INFO - CUDA available: True
2022-11-01 19:19:40,942 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3060
2022-11-01 19:19:40,942 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
2022-11-01 19:19:40,942 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.109
2022-11-01 19:19:40,942 - mmdeploy - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30146 版
2022-11-01 19:19:40,942 - mmdeploy - INFO - GCC: n/a
2022-11-01 19:19:40,942 - mmdeploy - INFO - PyTorch: 1.11.0+cu113
2022-11-01 19:19:40,942 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

2022-11-01 19:19:40,942 - mmdeploy - INFO - TorchVision: 0.12.0+cu113
2022-11-01 19:19:40,942 - mmdeploy - INFO - OpenCV: 4.5.4
2022-11-01 19:19:40,942 - mmdeploy - INFO - MMCV: 1.6.2
2022-11-01 19:19:40,942 - mmdeploy - INFO - MMCV Compiler: MSVC 192930146
2022-11-01 19:19:40,942 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2022-11-01 19:19:40,942 - mmdeploy - INFO - MMDeploy: 0.9.0+c5be297
2022-11-01 19:19:40,942 - mmdeploy - INFO - 

2022-11-01 19:19:40,942 - mmdeploy - INFO - **********Backend information**********
2022-11-01 19:19:44,107 - mmdeploy - INFO - onnxruntime: 1.13.1	ops_is_avaliable : False
```

**Comment by RunningLeon** [comment]
@kc-w Hi, should not use base model config. Pls. find the right config and ckpt from the [docs](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/pspnet#results-and-models).
