### ISSUE TITLE
[Bug]  ERROR - tools/deploy.py - main - 234 - ncnn support is not available

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdeploy#1288]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I run `tools/scripts/build_ubuntu_x64_ncnn.py` success, but follow convert failed~

```shell
cd /project/mmdeploy

python tools/deploy.py \
	configs/mmdet/detection/single-stage_ncnn_dynamic.py \
	/project/mmdetection/configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py \
	/project/mmdetection/rtmdet_tiny_8xb32-300e_coco.pth \
	/project/mmdeploy/data/coco/val2017/000000000110.jpg \
	--work-dir /project/mmdeploy/work_dir/rtmdet/ncnn \
	--dump-info
```

```shell
root@project-10489-instance-20306-ov-ide-674f4b55ff-2bjl6:~/mmdeploy# python tools/deploy.py \
> configs/mmdet/detection/single-stage_ncnn_dynamic.py \
> /project/mmdetection/configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py \
> /project/mmdetection/rtmdet_tiny_8xb32-300e_coco.pth \
> /project/mmdeploy/data/coco/val2017/000000000110.jpg \
> --work-dir /project/mmdeploy/work_dir/rtmdet/ncnn \
> --dump-infocd /project/mmdeploy
cd /project/mmdeploy

python tools/deploy.py \
        configs/mmdet/detection/single-stage_ncnn_dynamic.py \
        /project/mmdetection/configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py \
        /project/mmdetection/rtmdet_tiny_8xb32-300e_coco.pth \
        /project/mmdeploy/data/coco/val2017/000000000110.jpg \
        --work-dir /project/mmdeploy/work_dir/rtmdet/ncnn \
        --dump-info^CTraceback (most recent call last):
  File "tools/deploy.py", line 8, in <module>
^C  File "/usr/local/lib/python3.7/dist-packages/mmengine/__init__.py", line 3, in <module>





    from .config import *
  File "/usr/local/lib/python3.7/dist-packages/mmengine/config/__init__.py", line 2, in <module>
    from .config import Config, ConfigDict, DictAction
  File "/usr/local/lib/python3.7/dist-packages/mmengine/config/config.py", line 7, in <module>
    import shutil
  File "/usr/lib/python3.7/shutil.py", line 10, in <module>
    import fnmatch
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 812, in get_code
  File "<frozen importlib._bootstrap_external>", line 953, in path_stats
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
KeyboardInterrupt
root@project-10489-instance-20306-ov-ide-674f4b55ff-2bjl6:~/mmdeploy# 
root@project-10489-instance-20306-ov-ide-674f4b55ff-2bjl6:~/mmdeploy# 
root@project-10489-instance-20306-ov-ide-674f4b55ff-2bjl6:~/mmdeploy# 
root@project-10489-instance-20306-ov-ide-674f4b55ff-2bjl6:~/mmdeploy# 
root@project-10489-instance-20306-ov-ide-674f4b55ff-2bjl6:~/mmdeploy# 
root@project-10489-instance-20306-ov-ide-674f4b55ff-2bjl6:~/mmdeploy# cd /project/mmdeploy
root@project-10489-instance-20306-ov-ide-674f4b55ff-2bjl6:~/mmdeploy# 
root@project-10489-instance-20306-ov-ide-674f4b55ff-2bjl6:~/mmdeploy# python tools/deploy.py \
> configs/mmdet/detection/single-stage_ncnn_dynamic.py \
> /project/mmdetection/configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py \
> /project/mmdetection/rtmdet_tiny_8xb32-300e_coco.pth \
> /project/mmdeploy/data/coco/val2017/000000000110.jpg \
> --work-dir /project/mmdeploy/work_dir/rtmdet/ncnn \
> --dump-info
[2022-11-02 15:09:11.858] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
[2022-11-02 15:09:14.212] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:15 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
[2022-11-02 15:09:17.917] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
11/02 15:09:17 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
11/02 15:09:19 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:19 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/02 15:09:19 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
local loads checkpoint from path: /project/mmdetection/rtmdet_tiny_8xb32-300e_coco.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std

11/02 15:09:20 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
11/02 15:09:20 - mmengine - INFO - Export PyTorch model to ONNX: /project/mmdeploy/work_dir/rtmdet/ncnn/end2end.onnx.
11/02 15:09:20 - mmengine - WARNING - Can not find mmdet.models.dense_heads.RPNHead.get_bboxes, function rewrite will not be applied
/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py:1294: UserWarning: Provided key dets for dynamic axes is not a valid input/output name
  warnings.warn("Provided key {} for dynamic axes is not a valid input/output name".format(key))
/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py:1294: UserWarning: Provided key labels for dynamic axes is not a valid input/output name
  warnings.warn("Provided key {} for dynamic axes is not a valid input/output name".format(key))
/project/mmdeploy/mmdeploy/pytorch/functions/getattribute.py:18: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ret = torch.Size([int(s) for s in ret])
/project/mmdeploy/mmdeploy/pytorch/functions/size.py:22: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ret = [int(r) for r in ret]
/usr/local/lib/python3.7/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/project/mmdeploy/mmdeploy/pytorch/functions/size.py:18: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ret = int(ret)
/project/mmdeploy/mmdeploy/codebase/mmdet/models/layers/bbox_nms.py:93: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  iou_threshold = torch.tensor([iou_threshold], dtype=torch.float32)
/project/mmdeploy/mmdeploy/codebase/mmdet/models/layers/bbox_nms.py:94: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  score_threshold = torch.tensor([score_threshold], dtype=torch.float32)
/project/mmdeploy/mmdeploy/pytorch/functions/topk.py:28: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  k = torch.tensor(k, device=input.device, dtype=torch.long)
/project/mmdeploy/mmdeploy/pytorch/functions/topk.py:33: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return ctx.origin_func(input, k, dim=dim, largest=largest, sorted=sorted)
/project/mmdeploy/mmdeploy/mmcv/ops/nms.py:40: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  score_threshold = float(score_threshold)
/project/mmdeploy/mmdeploy/mmcv/ops/nms.py:41: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  iou_threshold = float(iou_threshold)
/usr/local/lib/python3.7/dist-packages/mmcv/ops/nms.py:30: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if max_num > 0:
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
/usr/local/lib/python3.7/dist-packages/torch/onnx/symbolic_opset9.py:2819: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  "If indices include negative values, the exported graph will produce incorrect results.")
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
11/02 15:09:35 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
11/02 15:09:35 - mmengine - ERROR - tools/deploy.py - main - 234 - ncnn support is not available, please make sure                 1) `mmdeploy_onnx2ncnn` existed in `PATH`                 2) python import ncnn success

```

### Reproduction

```shell
cd /project/mmdeploy

python tools/deploy.py \
	configs/mmdet/detection/single-stage_ncnn_dynamic.py \
	/project/mmdetection/configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py \
	/project/mmdetection/rtmdet_tiny_8xb32-300e_coco.pth \
	/project/mmdeploy/data/coco/val2017/000000000110.jpg \
	--work-dir /project/mmdeploy/work_dir/rtmdet/ncnn \
	--dump-info
```

### Environment

```Shell
root@project-10489-instance-20306-ov-ide-674f4b55ff-2bjl6:~/mmdeploy# python tools/check_env.py 
11/02 15:07:15 - mmengine - INFO - 

11/02 15:07:15 - mmengine - INFO - **********Environmental information**********
11/02 15:07:16 - mmengine - INFO - sys.platform: linux
11/02 15:07:16 - mmengine - INFO - Python: 3.7.5 (default, Dec  9 2021, 17:04:37) [GCC 8.4.0]
11/02 15:07:16 - mmengine - INFO - CUDA available: True
11/02 15:07:16 - mmengine - INFO - numpy_random_seed: 2147483648
11/02 15:07:16 - mmengine - INFO - GPU 0: GeForce RTX 2080 Ti
11/02 15:07:16 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
11/02 15:07:16 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.1, V11.1.105
11/02 15:07:16 - mmengine - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
11/02 15:07:16 - mmengine - INFO - PyTorch: 1.10.0+cu111
11/02 15:07:16 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

11/02 15:07:16 - mmengine - INFO - TorchVision: 0.11.0+cu111
11/02 15:07:16 - mmengine - INFO - OpenCV: 4.5.5
11/02 15:07:16 - mmengine - INFO - MMEngine: 0.2.0
11/02 15:07:16 - mmengine - INFO - MMCV: 2.0.0rc2
11/02 15:07:16 - mmengine - INFO - MMCV Compiler: GCC 7.3
11/02 15:07:16 - mmengine - INFO - MMCV CUDA Compiler: 11.1
11/02 15:07:16 - mmengine - INFO - MMDeploy: 0.9.0+185d838
11/02 15:07:16 - mmengine - INFO - 

11/02 15:07:16 - mmengine - INFO - **********Backend information**********
11/02 15:07:17 - mmengine - INFO - onnxruntime: 1.8.1   ops_is_avaliable : True
11/02 15:07:17 - mmengine - INFO - tensorrt: None       ops_is_avaliable : False
11/02 15:07:17 - mmengine - INFO - ncnn: None   ops_is_avaliable : True
11/02 15:07:17 - mmengine - INFO - pplnn_is_avaliable: False
11/02 15:07:17 - mmengine - INFO - openvino_is_avaliable: True
11/02 15:07:17 - mmengine - INFO - snpe_is_available: False
11/02 15:07:17 - mmengine - INFO - ascend_is_available: False
11/02 15:07:17 - mmengine - INFO - coreml_is_available: False
11/02 15:07:17 - mmengine - INFO - 

11/02 15:07:17 - mmengine - INFO - **********Codebase information**********
11/02 15:07:17 - mmengine - INFO - mmdet:       3.0.0rc2
11/02 15:07:17 - mmengine - INFO - mmseg:       None
11/02 15:07:17 - mmengine - INFO - mmcls:       None
11/02 15:07:17 - mmengine - INFO - mmocr:       None
11/02 15:07:17 - mmengine - INFO - mmedit:      None
11/02 15:07:17 - mmengine - INFO - mmdet3d:     None
11/02 15:07:17 - mmengine - INFO - mmpose:      None
11/02 15:07:17 - mmengine - INFO - mmrotate:    None
11/02 15:07:17 - mmengine - INFO - mmaction:    None
root@project-10489-instance-20306-ov-ide-674f4b55ff-2bjl6:~/mmdeploy#
```

**Comment by tpoisonooo** [comment]
After `tools/scripts/build_ubuntu_x64_ncnn.py`, there is a tips `source ~/mmdeploy.env`

Have you execute `source ~/mmdeploy.env` ?

**Comment by vansin** [comment]
> After `tools/scripts/build_ubuntu_x64_ncnn.py`, there is a tips `source ~/mmdeploy.env`
> 
> Have you execute `source ~/mmdeploy.env` ?

thanks

**Comment by vansin** [comment]
11/03 13:23:36 - mmengine - ERROR - tools/deploy.py - create_process - 78 - visualize ncnn model failed.
```shell
  warnings.warn("Exporting aten::index operator of advanced indexing in opset " +
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
11/03 13:23:31 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
11/03 13:23:32 - mmengine - INFO - Start pipeline mmdeploy.backend.ncnn.onnx2ncnn.from_onnx in main process
Unknown data type 0
Unknown data type 0
Unknown data type 0
Unknown data type 0
Unknown data type 0
Unknown data type 0
Less not supported yet!
Not not supported yet!
Unsupported Flatten axis 2!
Unsupported Gather axis: 0
Unknown data type 0
Unknown data type 0
Unsupported Flatten axis 2!
Unsupported Gather axis: 0
Unknown data type 0
Unknown data type 0
Unsupported Flatten axis 3!
Unsupported Gather axis: 0
Unknown data type 0
Unsupported Flatten axis 2!
Unsupported Gather axis: 0
Unknown data type 0
Unknown data type 0
Unsupported Flatten axis 2!
Unsupported Gather axis: 0
Unknown data type 0
Unknown data type 0
Unsupported Flatten axis 2!
Unsupported Gather axis: 0
Unknown data type 0
onnx2ncnn finish
11/03 13:23:32 - mmengine - INFO - Finish pipeline mmdeploy.backend.ncnn.onnx2ncnn.from_onnx
11/03 13:23:32 - mmengine - INFO - visualize ncnn model start.
[2022-11-03 13:23:35.070] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
11/03 13:23:36 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/03 13:23:36 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/03 13:23:36 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/03 13:23:36 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "backend_detectors" registry tree. As a workaround, the current "backend_detectors" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
param is too old, please regenerate!
layer load_param 303 ReduceMax_325 failed
layer Less not exists or registered
11/03 13:23:36 - mmengine - ERROR - tools/deploy.py - create_process - 78 - visualize ncnn model failed.
root@container-8eb211b4ac-3b1e22f2:~/mmdeploy# 
```

**Comment by hanrui1sensetime** [comment]
Deploy detection models by ncnn should use ncnn `detection_output` layer and `prior_box` layer.
`base_dense_head__predict_by_feat__ncnn` in `https://github.com/open-mmlab/mmdeploy/blob/dev-1.x/mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py` is an example.
