### ISSUE TITLE
[Bug] Fail to convert model from onnx to tensorrt

### ISSUE THREAD

**Issue by yeungkong** [open-mmlab/mmdeploy#1335]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hi. Since it fails to convert my model from pytorch to tensorrt directly, I am trying to convert my maskrcnn model from pytorch to tensorrt using two-step convertion which converts the model to onnx first. The convertion to onnx is ok, but then the convertion from onnx to tensorrt fails.  How can I fix the problem? Please kindly give me some help.

### Reproduction
```

from mmdeploy.apis import torch2onnx
from mmdeploy.apis.tensorrt import onnx2tensorrt
from mmdeploy.backend.sdk.export_info import export2SDK
import os

img = 'D:\Programs\...\mmdetection\demo/demo.png'
work_dir = 'D:\Programs\...\mmdeploy\work_dirs_maskrcnn'
save_file = 'end2end.onnx'
deploy_cfg = 'D:\Programs\...\mmdeploy\configs\mmdet\instance-seg/instance-seg_onnxruntime_static.py'
model_cfg = 'D:/Programs/.../mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py'
model_checkpoint = 'D:/Programs/.../mmdetection/work_dirs_maskrcnn/epoch_1983.pth '
device = 'cpu'

# 1. convert model to IR(onnx)
torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  model_checkpoint, device)

# 2. convert IR to tensorrt
onnx_model = os.path.join(work_dir, save_file)
save_file = 'end2end.engine'
deploy_cfg = 'D:\Programs\...\mmdeploy\configs\mmdet\instance-seg/instance-seg_tensorrt_static-800x1344.py'
model_id = 0
device = 'cuda'
onnx2tensorrt(work_dir, save_file, model_id, deploy_cfg, onnx_model, device)

# 3. extract pipeline info for sdk use (dump-info)
export2SDK(deploy_cfg, model_cfg, work_dir, pth=model_checkpoint, device=device)
```

### Environment

```Shell
2022-11-09 13:54:32,022 - mmdeploy - INFO - sys.platform: win32
2022-11-09 13:54:32,022 - mmdeploy - INFO - Python: 3.7.13 (default, Mar 28 2022, 08:03:21) [MSC v.1916 64 bit (AMD64)]
2022-11-09 13:54:32,022 - mmdeploy - INFO - CUDA available: True
2022-11-09 13:54:32,022 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3060 Ti
2022-11-09 13:54:32,022 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
2022-11-09 13:54:32,023 - mmdeploy - INFO - NVCC: Not Available
2022-11-09 13:54:32,023 - mmdeploy - INFO - GCC: n/a
2022-11-09 13:54:32,023 - mmdeploy - INFO - PyTorch: 1.11.0
2022-11-09 13:54:32,023 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,c
ode=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -o
penmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF
_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

2022-11-09 13:54:32,024 - mmdeploy - INFO - TorchVision: 0.12.0
2022-11-09 13:54:32,024 - mmdeploy - INFO - OpenCV: 4.5.4
2022-11-09 13:54:32,024 - mmdeploy - INFO - MMCV: 1.4.8
2022-11-09 13:54:32,024 - mmdeploy - INFO - MMCV Compiler: MSVC 192930140
2022-11-09 13:54:32,024 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2022-11-09 13:54:32,024 - mmdeploy - INFO - MMDeploy: 0.9.0+
2022-11-09 13:54:32,024 - mmdeploy - INFO -

2022-11-09 13:54:32,024 - mmdeploy - INFO - **********Backend information**********
2022-11-09 13:54:32,633 - mmdeploy - INFO - onnxruntime: 1.8.1  ops_is_avaliable : True
2022-11-09 13:54:32,658 - mmdeploy - INFO - tensorrt: 8.4.3.1   ops_is_avaliable : False
2022-11-09 13:54:32,696 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-11-09 13:54:32,700 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-11-09 13:54:32,722 - mmdeploy - INFO - openvino_is_avaliable: True
2022-11-09 13:54:32,766 - mmdeploy - INFO - snpe_is_available: False
2022-11-09 13:54:32,772 - mmdeploy - INFO - ascend_is_available: False
2022-11-09 13:54:32,775 - mmdeploy - INFO - coreml_is_available: False
2022-11-09 13:54:32,775 - mmdeploy - INFO -

2022-11-09 13:54:32,776 - mmdeploy - INFO - **********Codebase information**********
2022-11-09 13:54:32,783 - mmdeploy - INFO - mmdet:      2.23.0
2022-11-09 13:54:32,783 - mmdeploy - INFO - mmseg:      0.29.0
2022-11-09 13:54:32,783 - mmdeploy - INFO - mmcls:      0.23.0
2022-11-09 13:54:32,783 - mmdeploy - INFO - mmocr:      None
2022-11-09 13:54:32,784 - mmdeploy - INFO - mmedit:     0.15.2
2022-11-09 13:54:32,784 - mmdeploy - INFO - mmdet3d:    None
2022-11-09 13:54:32,784 - mmdeploy - INFO - mmpose:     0.25.1
2022-11-09 13:54:32,784 - mmdeploy - INFO - mmrotate:   None
```

### Error traceback

```
.............
2022-11-09 10:25:28,921 - mmdeploy - INFO - Execute onnx optimize passes.
2022-11-09 10:25:29,632 - mmdeploy - WARNING - Could not load the library of tensorrt plugins.             Because the file does not exist: 
[11/09/2022-10:25:29] [TRT] [I] [MemUsageChange] Init CUDA: CPU +353, GPU +0, now: CPU 8798, GPU 1187 (MiB)
[11/09/2022-10:25:30] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +339, GPU +104, now: CPU 9325, GPU 1291 (MiB)
[11/09/2022-10:25:31] [TRT] [W] onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Traceback (most recent call last):
  File "D:/Programs/.../mmdetection/torch2tensorrt.py", line 24, in <module>
    onnx2tensorrt(work_dir, save_file, model_id, deploy_cfg, onnx_model, device)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\backend\tensorrt\onnx2tensorrt.py", line 88, in onnx2tensorrt
    device_id=device_id)
  File "d:\programs\...\mmdeploy\mmdeploy\backend\tensorrt\utils.py", line 165, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 12 (parseGraph): INVALID_NODE: Invalid Node - Pad_12
[shuffleNode.cpp::nvinfer1::builder::ShuffleNode::symbolicExecute::392] Error Code 4: Internal Error (Reshape_4: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])

[11/09/2022-10:25:31] [TRT] [W] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[11/09/2022-10:25:31] [TRT] [E] [shuffleNode.cpp::nvinfer1::builder::ShuffleNode::symbolicExecute::392] Error Code 4: Internal Error (Reshape_4: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])

Process finished with exit code 1
```

**Comment by grimoire** [comment]
You should use the same deploy_cfg for both `torch2onnx` and `onnx2tensorrt`. The config will guide the tools to generate a model special for TensorRT.
Don't forget to build tensorrt ops follow [documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/windows.md#install-inference-engines-for-mmdeploy).

**Comment by yeungkong** [comment]
If I use instance-seg_tensorrt_static-800x1344.py for both deploy_cfg, the following error message occurs.

```
Traceback (most recent call last):
  File "D:/Programs/.../mmdetection/torch2tensorrt.py", line 19, in <module>
    model_checkpoint, device)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\pytorch2onnx.py", line 60, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\utils\utils.py", line 38, in build_task_processor
    check_backend_device(deploy_cfg=deploy_cfg, device=device)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\utils\utils.py", line 23, in check_backend_device
    raise ValueError(f'{device} is invalid for the backend {backend}')
ValueError: cpu is invalid for the backend tensorrt
```

If I use instance-seg_onnxruntime_static.py for both deploy_cfg, obviously this is not correct. If I use instance-seg_tensorrt_static-800x1344.py for both deploy_cfg and change the first device to 'cuda', the following error message occurs.

```
2022-11-09 16:06:12,901 - mmdeploy - INFO - Execute onnx optimize passes.
2022-11-09 16:06:13,965 - mmdeploy - WARNING - Could not load the library of tensorrt plugins.             Because the file does not exist: 
[11/09/2022-16:06:14] [TRT] [I] [MemUsageChange] Init CUDA: CPU +295, GPU +0, now: CPU 9553, GPU 8015 (MiB)
[11/09/2022-16:06:15] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +337, GPU +104, now: CPU 10075, GPU 8119 (MiB)
[11/09/2022-16:06:15] [TRT] [W] onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[11/09/2022-16:06:15] [TRT] [W] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[11/09/2022-16:06:17] [TRT] [I] No importer registered for op: GatherTopk. Attempting to import as plugin.
[11/09/2022-16:06:17] [TRT] [I] Searching for plugin: GatherTopk, plugin_version: 1, plugin_namespace: 
Traceback (most recent call last):
  File "D:/Programs/.../mmdetection/torch2tensorrt.py", line 27, in <module>
    onnx2tensorrt(work_dir, save_file, model_id, deploy_cfg, onnx_model, device)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\backend\tensorrt\onnx2tensorrt.py", line 88, in onnx2tensorrt
    device_id=device_id)
  File "d:\programs\...\mmdeploy\mmdeploy\backend\tensorrt\utils.py", line 165, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 1121 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"


Process finished with exit code 1
```

**Comment by grimoire** [comment]
The log indicates that mmdeploy can not find the custom ops library. Check the ops support with the apis below.
```python
from mmdeploy.backend.tensorrt import is_custom_ops_available, get_ops_path
```

**Comment by yeungkong** [comment]
@grimoire I see. I have rebuilt the tensorrt ops. I think now mmdeploy_tensorrt_ops.dll is loaded successfully. 
If I use the following command, 
```
from mmdeploy.apis import torch2onnx
from mmdeploy.apis.tensorrt import onnx2tensorrt
from mmdeploy.backend.sdk.export_info import export2SDK
import os

img = 'D:\Programs\...\mmdetection\demo/demo.png'
work_dir = 'D:\Programs\...\mmdeploy\work_dirs_maskrcnn'
save_file = 'end2end.onnx'
deploy_cfg = 'D:\Programs\...\mmdeploy\configs\mmdet\instance-seg/instance-seg_tensorrt_static-800x1344.py'
model_cfg = 'D:/Programs/.../mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py'
model_checkpoint = 'D:/Programs/.../mmdetection/work_dirs_maskrcnn/epoch_1983.pth '
device = 'cuda'

# 1. convert model to IR(onnx)
torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  model_checkpoint, device)

# 2. convert IR to tensorrt
onnx_model = os.path.join(work_dir, save_file)
save_file = 'end2end.engine'
model_id = 0
onnx2tensorrt(work_dir, save_file, model_id, deploy_cfg, onnx_model, device)

# 3. extract pipeline info for sdk use (dump-info)
export2SDK(deploy_cfg, model_cfg, work_dir, pth=model_checkpoint, device=device)
```
the following is the error message.
```
2022-11-09 19:27:52,782 - mmdeploy - INFO - Execute onnx optimize passes.
2022-11-09 19:27:53,874 - mmdeploy - INFO - Successfully loaded tensorrt plugins from d:\programs\...\mmdeploy\mmdeploy\lib\mmdeploy_tensorrt_ops.dll
[11/09/2022-19:27:55] [TRT] [I] [MemUsageChange] Init CUDA: CPU +262, GPU +0, now: CPU 10508, GPU 8015 (MiB)
[11/09/2022-19:27:56] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +334, GPU +104, now: CPU 11024, GPU 8119 (MiB)
[11/09/2022-19:27:57] [TRT] [W] onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[11/09/2022-19:27:57] [TRT] [W] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[11/09/2022-19:27:58] [TRT] [I] No importer registered for op: GatherTopk. Attempting to import as plugin.
[11/09/2022-19:27:58] [TRT] [I] Searching for plugin: GatherTopk, plugin_version: 1, plugin_namespace: 
[11/09/2022-19:27:58] [TRT] [I] Successfully created plugin: GatherTopk
[11/09/2022-19:27:58] [TRT] [I] No importer registered for op: GatherTopk. Attempting to import as plugin.
[11/09/2022-19:27:58] [TRT] [I] Searching for plugin: GatherTopk, plugin_version: 1, plugin_namespace: 
[11/09/2022-19:27:58] [TRT] [I] Successfully created plugin: GatherTopk
[11/09/2022-19:27:58] [TRT] [I] No importer registered for op: GatherTopk. Attempting to import as plugin.
[11/09/2022-19:27:58] [TRT] [I] Searching for plugin: GatherTopk, plugin_version: 1, plugin_namespace: 
[11/09/2022-19:27:58] [TRT] [I] Successfully created plugin: GatherTopk
[11/09/2022-19:27:58] [TRT] [I] No importer registered for op: GatherTopk. Attempting to import as plugin.
[11/09/2022-19:27:58] [TRT] [I] Searching for plugin: GatherTopk, plugin_version: 1, plugin_namespace: 
[11/09/2022-19:27:58] [TRT] [I] Successfully created plugin: GatherTopk
[11/09/2022-19:27:59] [TRT] [I] No importer registered for op: GatherTopk. Attempting to import as plugin.
[11/09/2022-19:27:59] [TRT] [I] Searching for plugin: GatherTopk, plugin_version: 1, plugin_namespace: 
[11/09/2022-19:27:59] [TRT] [I] Successfully created plugin: GatherTopk
[11/09/2022-19:27:59] [TRT] [I] No importer registered for op: GatherTopk. Attempting to import as plugin.
[11/09/2022-19:27:59] [TRT] [I] Searching for plugin: GatherTopk, plugin_version: 1, plugin_namespace: 
[11/09/2022-19:27:59] [TRT] [I] Successfully created plugin: GatherTopk
[11/09/2022-19:27:59] [TRT] [W] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[11/09/2022-19:27:59] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[11/09/2022-19:27:59] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace: 
[11/09/2022-19:27:59] [TRT] [I] Successfully created plugin: TRTBatchedNMS
[11/09/2022-19:27:59] [TRT] [I] No importer registered for op: MMCVMultiLevelRoiAlign. Attempting to import as plugin.
[11/09/2022-19:27:59] [TRT] [I] Searching for plugin: MMCVMultiLevelRoiAlign, plugin_version: 1, plugin_namespace: 
[11/09/2022-19:27:59] [TRT] [I] Successfully created plugin: MMCVMultiLevelRoiAlign
[11/09/2022-19:27:59] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
[11/09/2022-19:27:59] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[11/09/2022-19:27:59] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace: 
[11/09/2022-19:27:59] [TRT] [I] Successfully created plugin: TRTBatchedNMS
[11/09/2022-19:27:59] [TRT] [I] No importer registered for op: MMCVMultiLevelRoiAlign. Attempting to import as plugin.
[11/09/2022-19:27:59] [TRT] [I] Searching for plugin: MMCVMultiLevelRoiAlign, plugin_version: 1, plugin_namespace: 
[11/09/2022-19:27:59] [TRT] [I] Successfully created plugin: MMCVMultiLevelRoiAlign
[11/09/2022-19:28:01] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +47, GPU +64, now: CPU 11132, GPU 8183 (MiB)
[11/09/2022-19:28:01] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +232, GPU +8, now: CPU 11364, GPU 8191 (MiB)
[11/09/2022-19:28:01] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.2.0
[11/09/2022-19:28:01] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[11/09/2022-19:28:01] [TRT] [E] 1: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::131] Error Code 1: Cuda Driver (invalid argument)
[11/09/2022-19:28:01] [TRT] [W] Requested amount of GPU memory (1024 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[11/09/2022-19:28:02] [TRT] [E] 2: [globWriter.cpp::nvinfer1::builder::HybridGlobWriter::HybridGlobWriter::383] Error Code 2: OutOfMemory (no further information)
Traceback (most recent call last):
  File "D:/Programs/.../mmdetection/torch2tensorrt.py", line 28, in <module>
    onnx2tensorrt(work_dir, save_file, model_id, deploy_cfg, onnx_model, device)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\backend\tensorrt\onnx2tensorrt.py", line 88, in onnx2tensorrt
    device_id=device_id)
  File "d:\programs\...\mmdeploy\mmdeploy\backend\tensorrt\utils.py", line 215, in from_onnx
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine

Process finished with exit code 1
```
On the other hand, if I use the following command,
```
from mmdeploy.apis import torch2onnx
from mmdeploy.apis.tensorrt import onnx2tensorrt
from mmdeploy.backend.sdk.export_info import export2SDK
import os

img = 'D:\Programs\...\mmdetection\demo/demo.png'
work_dir = 'D:\Programs\...\mmdeploy\work_dirs_maskrcnn'
save_file = 'end2end.onnx'
deploy_cfg = 'D:\Programs\...\mmdeploy\configs\mmdet\instance-seg/instance-seg_tensorrt_static-800x1344.py'
model_cfg = 'D:/Programs/.../mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py'
model_checkpoint = 'D:/Programs/.../mmdetection/work_dirs_maskrcnn/epoch_1983.pth '
device = 'cpu'

# 1. convert model to IR(onnx)
torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  model_checkpoint, device)

# 2. convert IR to tensorrt
onnx_model = os.path.join(work_dir, save_file)
save_file = 'end2end.engine'
model_id = 0
device = 'cuda'
onnx2tensorrt(work_dir, save_file, model_id, deploy_cfg, onnx_model, device)

# 3. extract pipeline info for sdk use (dump-info)
export2SDK(deploy_cfg, model_cfg, work_dir, pth=model_checkpoint, device=device)
```
the following is the error message.
```
Traceback (most recent call last):
  File "D:/Programs/.../mmdetection/torch2tensorrt.py", line 20, in <module>
    model_checkpoint, device)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\pytorch2onnx.py", line 60, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\utils\utils.py", line 38, in build_task_processor
    check_backend_device(deploy_cfg=deploy_cfg, device=device)
  File "d:\programs\...\mmdeploy\mmdeploy\apis\utils\utils.py", line 23, in check_backend_device
    raise ValueError(f'{device} is invalid for the backend {backend}')
ValueError: cpu is invalid for the backend tensorrt
```
What can be done further in order to convert the model to tensorrt successfully?

**Comment by grimoire** [comment]
The log provides lots of information which can help you solve the problem:
```
[11/09/2022-19:28:01] [TRT] [W] Requested amount of GPU memory (1024 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[11/09/2022-19:28:02] [TRT] [E] 2: [globWriter.cpp::nvinfer1::builder::HybridGlobWriter::HybridGlobWriter::383] Error Code 2: OutOfMemory (no further information)
```

Note that PyTorch will not share the cuda memory with TensorRT, that's why we encourage users to convert ONNX and TensorRT in different processes.

**Comment by yeungkong** [comment]
@grimoire I converted my model to onnx and tensorrt in two separate processes. I think it works properly now. Thank you very much.
