### ISSUE TITLE
[Bug] mmdeploy-master cannot convert torch model generated by mmdetection-3.x

### ISSUE THREAD

**Issue by WuChannn** [open-mmlab/mmdeploy#1355]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

**mmdeploy in master branch cannot convert torch model generated by mmdetection in 3.x branch:**

the log is

/data_local/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components relate
d to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/
mmcv/blob/master/docs/en/compatibility.md for more details.                                                                                                                              
  warnings.warn(                                                                                                                                                                         
[2022-11-11 06:52:22.965] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'                                                                                                     
/data_local/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components relate
d to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.                                                                                                                              
  warnings.warn(                                                                                                                                                                         
[2022-11-11 06:52:25.923] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
Traceback (most recent call last):
  File "./tools/deploy.py", line 446, in <module>                                                                                                                                        
    main()                                    
  File "./tools/deploy.py", line 125, in main
    export2SDK(                               
  File "/data_local/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/sdk/export_info.py", line 407, in export2SDK
    pipeline_info = get_pipeline(deploy_cfg, model_cfg, work_dir, device)                                                                                                                
  File "/data_local/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/sdk/export_info.py", line 345, in get_pipeline
    preprocess = get_preprocess(deploy_cfg, model_cfg, device)                                                                                                                           
  File "/data_local/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/sdk/export_info.py", line 219, in get_preprocess
    pipeline = task_processor.get_preprocess()                                                                                                                                           
  File "/data_local/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 294, in get_preprocess
    model_cfg = process_model_config(self.model_cfg, [''], input_shape)                                                                                                                  
  File "/data_local/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 53, in process_model_config
    cfg.data.test.pipeline = replace_ImageToTensor(cfg.data.test.pipeline)                                                                                                               
  File "/data_local/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'data'

### Reproduction

python ./tools/deploy.py \
    ./configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py \
   {path to mmdetection 3.x branch}/configs/mask_rcnn/mask-rcnn_r50_fpn_1x_coco.py \
    {path to mmdetection 3.x branch}/work_dirs/mask_rcnn_r50_fpn_1x_coco/epoch_12.pth \
    {path to mmdetection 3.x branch}/demo/demo.jpg \
    --work-dir {path to mmdetection 3.x branch}work_dirs/mask-rcnn_r50_fpn_1x_coco/mask-rcnn \
    --device cuda \
    --dump-info

### Environment

```Shell
/data_local/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove comp
onents related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See http
s://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.                                                                                       
  warnings.warn(                                                                      
2022-11-11 08:08:36,541 - mmdeploy - INFO -                                           

2022-11-11 08:08:36,541 - mmdeploy - INFO - **********Environmental information**********                                                                                   
2022-11-11 08:08:37,084 - mmdeploy - INFO - sys.platform: linux                                                                                                             
2022-11-11 08:08:37,084 - mmdeploy - INFO - Python: 3.8.13 (default, Oct 21 2022, 23:50:54) [GCC 11.2.0]
2022-11-11 08:08:37,084 - mmdeploy - INFO - CUDA available: True                                                                                                            
2022-11-11 08:08:37,084 - mmdeploy - INFO - GPU 0,1,2,3,4,5,6: GeForce GTX 1080 Ti                                                                                          
2022-11-11 08:08:37,084 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda                                                                                                      
2022-11-11 08:08:37,084 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.2, V11.2.152
2022-11-11 08:08:37,084 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0                                                                                   
2022-11-11 08:08:37,084 - mmdeploy - INFO - PyTorch: 1.12.1                                                                                                                 
2022-11-11 08:08:37,084 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:                                                                                  
  - GCC 9.3                                                                           
  - C++ Version: 201402                                                               
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)                                                                                             
  - OpenMP 201511 (a.k.a. OpenMP 4.5)                                                 
  - LAPACK is enabled (usually provided by MKL)                                                                                                                             
  - NNPACK is enabled                                                                 
  - CPU capability usage: AVX2                                                        
  - CUDA Runtime 11.3                                                                 
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61
;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,co
de=compute_37                              
  - CuDNN 8.3.2  (built against CUDA 11.5)                                            
  - Magma 2.5.2                                                                       
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=
11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE
_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bound
s -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=depreca
ted-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-u$
used-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WI
TH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=O
FF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,
2022-11-11 08:08:37,084 - mmdeploy - INFO - TorchVision: 0.13.1                                                                                                             
2022-11-11 08:08:37,084 - mmdeploy - INFO - OpenCV: 4.6.0                                                                                                                   
2022-11-11 08:08:37,084 - mmdeploy - INFO - MMCV: 1.7.0                                                                                                                     
2022-11-11 08:08:37,084 - mmdeploy - INFO - MMCV Compiler: GCC 9.3                                                                                                          
2022-11-11 08:08:37,085 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3                                                                                                        
2022-11-11 08:08:37,085 - mmdeploy - INFO - MMDeploy: 0.10.0+ff7b8fb                                                                                                        
2022-11-11 08:08:37,085 - mmdeploy - INFO -                                           

2022-11-11 08:08:37,085 - mmdeploy - INFO - **********Backend information**********                                                                                         
2022-11-11 08:08:38,086 - mmdeploy - INFO - onnxruntime: 1.13.1 ops_is_avaliable : True                                                                                     
2022-11-11 08:08:38,088 - mmdeploy - INFO - tensorrt: None      ops_is_avaliable : False                                                                                    
2022-11-11 08:08:38,177 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False                                                                                            
2022-11-11 08:08:38,179 - mmdeploy - INFO - pplnn_is_avaliable: False                                                                                                       
2022-11-11 08:08:38,180 - mmdeploy - INFO - openvino_is_avaliable: False                                                                                                    
2022-11-11 08:08:38,219 - mmdeploy - INFO - snpe_is_available: False                                                                                                        
2022-11-11 08:08:38,241 - mmdeploy - INFO - ascend_is_available: False                                                                                                      
2022-11-11 08:08:38,243 - mmdeploy - INFO - coreml_is_available: False                                                                                                      
2022-11-11 08:08:38,243 - mmdeploy - INFO -                                           

2022-11-11 08:08:38,243 - mmdeploy - INFO - **********Codebase information**********                                                                                        
2022-11-11 08:08:38,245 - mmdeploy - INFO - mmdet:      2.25.3                                                                                                              
2022-11-11 08:08:38,245 - mmdeploy - INFO - mmseg:      None                                                                                                                
2022-11-11 08:08:38,246 - mmdeploy - INFO - mmcls:      None                                                                                                                
2022-11-11 08:08:38,246 - mmdeploy - INFO - mmocr:      0.6.3                                                                                                               
2022-11-11 08:08:38,246 - mmdeploy - INFO - mmedit:     None                                                                                                                
2022-11-11 08:08:38,246 - mmdeploy - INFO - mmdet3d:    None                                                                                                                
2022-11-11 08:08:38,246 - mmdeploy - INFO - mmpose:     None                                                                                                                
2022-11-11 08:08:38,246 - mmdeploy - INFO - mmrotate:   None
```

**Comment by tpoisonooo** [comment]
I think that mmdet3.x depends on mmdeploy dev-1.x branch. https://github.com/open-mmlab/mmdeploy/tree/dev-1.x

**Comment by WuChannn** [comment]
@tpoisonooo hi, have you tried mmdeploy dev-1.x to convert mmdet3.x ?

**Comment by lvhan028** [comment]
@

**Comment by WuChannn** [comment]
@lvhan028 that's great, i am happy to join our beta testing group. I have tried dev-1.x, onnx model can be converted sucessfully. However, I can't get right output with the onnx model:

```
 def preporcess_image(img):
        if len(img.shape) < 3:
            img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB).astype(np.float32)

        ori_height, ori_width = img.shape[:2]

        scale = min(self.input_size / ori_width, self.input_size / ori_height)
        new_width, new_height = int(scale * ori_width), int(scale * ori_height)
        img_resized = cv2.resize(img, (new_width, new_height))

        img_padded = np.full(shape=[self.input_size, self.input_size, 3], fill_value=128.0)
        dw, dh = (self.input_size - new_width) // 2, (self.input_size - new_height) // 2
        img_padded[dh:new_height + dh, dw:new_width + dw, :] = img_resized

        img = np.array(img_padded, np.float32)

        return img

img = preporcess_image(image)
img = np.transpose(img, (2, 0, 1))
img = img[np.newaxis, ...]

ort_session = ort.InferenceSession(pb_dir + '/fasterrcnn.onnx')
output_names = [x.name for x in ort_session.get_outputs()]
ort_outputs = ort_session.run(output_names, {ort_session.get_inputs()[0].name: img})

print(ort_outputs)
```

the faster-rcnn onnx model is generated following [get_started](https://github.com/open-mmlab/mmdeploy/blob/dev-1.x/docs/en/get_started.md), the test image is ![demo](https://user-images.githubusercontent.com/25492462/202352596-e71eb35d-5492-4c6a-9a86-b645a632d320.jpg)
the generated onnx is , 
链接: https://pan.baidu.com/s/1CB5CL6QvjqxUd84PImmYag  密码: ra1q

**Comment by lvhan028** [comment]
> @lvhan028 @tpoisonooo that's great, i am happy to join our beta testing group. my wechat number is WuChannn. I have tried dev-1.x, onnx model can be converted sucessfully. However, I can't get right output with the onnx model:
> 
> ```
>  def preporcess_image(img):
>         if len(img.shape) < 3:
>             img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
>         img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB).astype(np.float32)
> 
>         ori_height, ori_width = img.shape[:2]
> 
>         scale = min(self.input_size / ori_width, self.input_size / ori_height)
>         new_width, new_height = int(scale * ori_width), int(scale * ori_height)
>         img_resized = cv2.resize(img, (new_width, new_height))
> 
>         img_padded = np.full(shape=[self.input_size, self.input_size, 3], fill_value=128.0)
>         dw, dh = (self.input_size - new_width) // 2, (self.input_size - new_height) // 2
>         img_padded[dh:new_height + dh, dw:new_width + dw, :] = img_resized
> 
>         img = np.array(img_padded, np.float32)
> 
>         return img
> 
> img = preporcess_image(image)
> img = np.transpose(img, (2, 0, 1))
> img = img[np.newaxis, ...]
> 
> ort_session = ort.InferenceSession(pb_dir + '/fasterrcnn.onnx')
> output_names = [x.name for x in ort_session.get_outputs()]
> ort_outputs = ort_session.run(output_names, {ort_session.get_inputs()[0].name: img})
> 
> print(ort_outputs)
> ```
> 
> the faster-rcnn onnx model is generated following [get_started](https://github.com/open-mmlab/mmdeploy/blob/dev-1.x/docs/en/get_started.md), the test image is ![demo](https://user-images.githubusercontent.com/25492462/202352596-e71eb35d-5492-4c6a-9a86-b645a632d320.jpg) the generated onnx is , 链接: https://pan.baidu.com/s/1CB5CL6QvjqxUd84PImmYag 密码: ra1q

Have you tried to use MMDeploy's visualization API to confirm the result?

```python
def visualize_model(model_cfg: Union[str, mmcv.Config],
                    deploy_cfg: Union[str, mmcv.Config],
                    model: Union[str, Sequence[str], BaseTask],
                    img: Union[str, np.ndarray],
                    device: str,
                    backend: Optional[Backend] = None,
                    output_file: Optional[str] = None,
                    show_result: bool = False,
                    **kwargs)
```
