### ISSUE TITLE
[Bug] Error when breaking point in symbolic function

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdeploy#1358]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

![image](https://user-images.githubusercontent.com/25839884/201451322-328c051b-ed00-4024-91ac-afe91914b2a4.png)

```shell
(mmdeploy-ncnn) ➜  mmdeploy git:(debug) ✗ python -m debugpy --listen 5678 --wait-for-client ./tools/deploy.py \
/project/mmdeploy-ncnn/mmdeploy/configs/mmdet/detection/single-stage_ncnn_static-800x1344.py \
/project/mmdeploy-ncnn/mmdetection/configs/yolo/yolov3_d53_8xb8-320-273e_coco.py \
"/project/mmdeploy-ncnn/mmdeploy_checkpoints/mmdet/yolov3/yolov3_d53_320_273e_coco-421362b6.pth" \
"../mmdetection/demo/demo.jpg"  \
--work-dir "../mmdeploy_regression_working_dir/mmdet/yolov3/ncnn/static/fp32/yolov3_d53_320_273e_coco-421362b6"  \
--device cpu  \
--log-level INFO \
--test-img ./tests/data/tiger.jpeg

[2022-11-12 09:58:05.200] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
[2022-11-12 09:58:08.174] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
[2022-11-12 09:58:10.960] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
11/12 09:58:10 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
11/12 09:58:11 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/12 09:58:11 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/12 09:58:11 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
local loads checkpoint from path: /project/mmdeploy-ncnn/mmdeploy_checkpoints/mmdet/yolov3/yolov3_d53_320_273e_coco-421362b6.pth
11/12 09:58:12 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
11/12 09:58:12 - mmengine - INFO - Export PyTorch model to ONNX: ../mmdeploy_regression_working_dir/mmdet/yolov3/ncnn/static/fp32/yolov3_d53_320_273e_coco-421362b6/end2end.onnx.
11/12 09:58:12 - mmengine - WARNING - Can not find mmdet.models.dense_heads.RPNHead.get_bboxes, function rewrite will not be applied
/project/mmdeploy-ncnn/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/single_stage.py:66: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  img_shape = [int(val) for val in img_shape]
/project/mmdeploy-ncnn/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/single_stage.py:66: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  img_shape = [int(val) for val in img_shape]
/project/mmdeploy-ncnn/mmdeploy/mmdeploy/pytorch/functions/getattribute.py:18: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ret = torch.Size([int(s) for s in ret])
/project/mmdeploy-ncnn/mmdeploy/mmdeploy/pytorch/functions/getattribute.py:18: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ret = torch.Size([int(s) for s in ret])
WARNING: The shape inference of mmdeploy::Yolov3DetectionOutput type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::Yolov3DetectionOutput type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::Yolov3DetectionOutput type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
11/12 09:58:27 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
11/12 09:58:28 - mmengine - INFO - Start pipeline mmdeploy.backend.ncnn.onnx2ncnn.from_onnx in main process
/project/mmdeploy-ncnn/mmdeploy/mmdeploy/backend/ncnn/mmdeploy_onnx2ncnn: error while loading shared libraries: libprotobuf.so.31: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/site-packages/debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/site-packages/debugpy/server/cli.py", line 430, in main
    run()
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/site-packages/debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "./tools/deploy.py", line 627, in <module>
    main()
  File "./tools/deploy.py", line 426, in main
    ncnn_api.from_onnx(onnx_path, osp.join(args.work_dir, onnx_name))
  File "/project/mmdeploy-ncnn/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/project/mmdeploy-ncnn/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/project/mmdeploy-ncnn/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/project/mmdeploy-ncnn/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/project/mmdeploy-ncnn/mmdeploy/mmdeploy/backend/ncnn/onnx2ncnn.py", line 72, in from_onnx
    assert ret_code == 0, 'onnx2ncnn failed'
AssertionError: onnx2ncnn failed
```

### Reproduction

```shell
(mmdeploy-ncnn) ➜  mmdeploy git:(debug) ✗ python -m debugpy --listen 5678 --wait-for-client ./tools/deploy.py \
/project/mmdeploy-ncnn/mmdeploy/configs/mmdet/detection/single-stage_ncnn_static-800x1344.py \
/project/mmdeploy-ncnn/mmdetection/configs/yolo/yolov3_d53_8xb8-320-273e_coco.py \
"/project/mmdeploy-ncnn/mmdeploy_checkpoints/mmdet/yolov3/yolov3_d53_320_273e_coco-421362b6.pth" \
"../mmdetection/demo/demo.jpg"  \
--work-dir "../mmdeploy_regression_working_dir/mmdet/yolov3/ncnn/static/fp32/yolov3_d53_320_273e_coco-421362b6"  \
--device cpu  \
--log-level INFO \
--test-img ./tests/data/tiger.jpeg

[2022-11-12 09:58:05.200] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
[2022-11-12 09:58:08.174] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
[2022-11-12 09:58:10.960] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
11/12 09:58:10 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
11/12 09:58:11 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/12 09:58:11 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/12 09:58:11 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
local loads checkpoint from path: /project/mmdeploy-ncnn/mmdeploy_checkpoints/mmdet/yolov3/yolov3_d53_320_273e_coco-421362b6.pth
11/12 09:58:12 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
11/12 09:58:12 - mmengine - INFO - Export PyTorch model to ONNX: ../mmdeploy_regression_working_dir/mmdet/yolov3/ncnn/static/fp32/yolov3_d53_320_273e_coco-421362b6/end2end.onnx.
11/12 09:58:12 - mmengine - WARNING - Can not find mmdet.models.dense_heads.RPNHead.get_bboxes, function rewrite will not be applied
/project/mmdeploy-ncnn/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/single_stage.py:66: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  img_shape = [int(val) for val in img_shape]
/project/mmdeploy-ncnn/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/single_stage.py:66: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  img_shape = [int(val) for val in img_shape]
/project/mmdeploy-ncnn/mmdeploy/mmdeploy/pytorch/functions/getattribute.py:18: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ret = torch.Size([int(s) for s in ret])
/project/mmdeploy-ncnn/mmdeploy/mmdeploy/pytorch/functions/getattribute.py:18: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ret = torch.Size([int(s) for s in ret])
WARNING: The shape inference of mmdeploy::Yolov3DetectionOutput type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::Yolov3DetectionOutput type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::Yolov3DetectionOutput type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
11/12 09:58:27 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
11/12 09:58:28 - mmengine - INFO - Start pipeline mmdeploy.backend.ncnn.onnx2ncnn.from_onnx in main process
/project/mmdeploy-ncnn/mmdeploy/mmdeploy/backend/ncnn/mmdeploy_onnx2ncnn: error while loading shared libraries: libprotobuf.so.31: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/site-packages/debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/site-packages/debugpy/server/cli.py", line 430, in main
    run()
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/site-packages/debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/huwenxing/miniconda3/envs/mmdeploy-ncnn/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "./tools/deploy.py", line 627, in <module>
    main()
  File "./tools/deploy.py", line 426, in main
    ncnn_api.from_onnx(onnx_path, osp.join(args.work_dir, onnx_name))
  File "/project/mmdeploy-ncnn/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/project/mmdeploy-ncnn/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/project/mmdeploy-ncnn/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/project/mmdeploy-ncnn/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/project/mmdeploy-ncnn/mmdeploy/mmdeploy/backend/ncnn/onnx2ncnn.py", line 72, in from_onnx
    assert ret_code == 0, 'onnx2ncnn failed'
AssertionError: onnx2ncnn failed
```

### Environment

```Shell
(mmdeploy-ncnn) ➜  mmdeploy git:(debug) ✗ python tools/check_env.py 
11/12 10:03:38 - mmengine - INFO - 

11/12 10:03:38 - mmengine - INFO - **********Environmental information**********
11/12 10:03:38 - mmengine - INFO - sys.platform: linux
11/12 10:03:38 - mmengine - INFO - Python: 3.8.13 (default, Oct 21 2022, 23:50:54) [GCC 11.2.0]
11/12 10:03:38 - mmengine - INFO - CUDA available: True
11/12 10:03:38 - mmengine - INFO - numpy_random_seed: 2147483648
11/12 10:03:38 - mmengine - INFO - GPU 0: NVIDIA GeForce GTX 1660 Ti
11/12 10:03:38 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.3
11/12 10:03:38 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.58
11/12 10:03:38 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
11/12 10:03:38 - mmengine - INFO - PyTorch: 1.10.0+cu113
11/12 10:03:38 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

11/12 10:03:38 - mmengine - INFO - TorchVision: 0.11.0+cu113
11/12 10:03:38 - mmengine - INFO - OpenCV: 4.6.0
11/12 10:03:38 - mmengine - INFO - MMEngine: 0.3.0
11/12 10:03:38 - mmengine - INFO - MMCV: 2.0.0rc2
11/12 10:03:38 - mmengine - INFO - MMCV Compiler: GCC 9.3
11/12 10:03:38 - mmengine - INFO - MMCV CUDA Compiler: 11.3
11/12 10:03:38 - mmengine - INFO - MMDeploy: 0.10.0+194795a
11/12 10:03:38 - mmengine - INFO - 

11/12 10:03:38 - mmengine - INFO - **********Backend information**********
11/12 10:03:39 - mmengine - INFO - onnxruntime: None    ops_is_avaliable : False
11/12 10:03:39 - mmengine - INFO - tensorrt: None       ops_is_avaliable : False
11/12 10:03:39 - mmengine - INFO - ncnn: 1.0.20221110   ops_is_avaliable : True
11/12 10:03:39 - mmengine - INFO - pplnn_is_avaliable: False
11/12 10:03:39 - mmengine - INFO - openvino_is_avaliable: False
11/12 10:03:39 - mmengine - INFO - snpe_is_available: False
11/12 10:03:39 - mmengine - INFO - ascend_is_available: False
11/12 10:03:39 - mmengine - INFO - coreml_is_available: False
11/12 10:03:39 - mmengine - INFO - 

11/12 10:03:39 - mmengine - INFO - **********Codebase information**********
11/12 10:03:39 - mmengine - INFO - mmdet:       3.0.0rc3
11/12 10:03:39 - mmengine - INFO - mmseg:       None
11/12 10:03:39 - mmengine - INFO - mmcls:       None
11/12 10:03:39 - mmengine - INFO - mmocr:       None
11/12 10:03:39 - mmengine - INFO - mmedit:      None
11/12 10:03:39 - mmengine - INFO - mmdet3d:     None
11/12 10:03:39 - mmengine - INFO - mmpose:      None
11/12 10:03:39 - mmengine - INFO - mmrotate:    None
11/12 10:03:39 - mmengine - INFO - mmaction:    None
```

**Comment by grimoire** [comment]
Honestly, I don't know. The log comes from pybind11 and I am not a pro at that.
PyTorch would call the symbolic method in `torch._C._jit_pass_onnx`
https://github.com/pytorch/pytorch/blob/bdc9911575277848ccac56b344dd624aa97fb87d/torch/csrc/jit/passes/onnx.cpp#L544

Which would load the method through pybind11. I guess the debugger/tracer broke something, but I have no idea how to fix it.
It would be a good idea to send an issue to PyTorch, they might have a fix.
