### ISSUE TITLE
AssertionError: The backend config of deploy configrequires a "type" field

### ISSUE THREAD

**Issue by bunengxiu** [open-mmlab/mmdeploy#1387]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

根据mmdeploy文档 -> 快速上手 -> 操作概述 -> 模型转换， 执行：
`python mmdeploy/tools/torch2onnx.py mmdeploy/configs/mmedit/super-resolution/super-resolution_static.py mmediting/configs/restorers/edsr/edsr_x4c64b16_g1_300k_div2k.py mmediting/checkpoint/edsr_x4c64b16_1x16_300k_div2k_20200608-3c2af8a3.pth mmediting/tests/data/lq/baboon_x4.png --work-dir mmdeploy/work_dir/`
报错：
`2022-11-17 22:04:22,762 - mmdeploy - INFO - torch2onnx: 
	model_cfg: mmediting/configs/restorers/edsr/edsr_x4c64b16_g1_300k_div2k.py 
	deploy_cfg: mmdeploy/configs/mmedit/super-resolution/super-resolution_static.py
Traceback (most recent call last):
  File "/home/wjh/software/pycharm-2020.3.5/plugins/python/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/wjh/software/pycharm-2020.3.5/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/wjh/learn/super_resolution_project/mmdeploy/tools/torch2onnx.py", line 85, in <module>
    main()
  File "/home/wjh/learn/super_resolution_project/mmdeploy/tools/torch2onnx.py", line 54, in main
    device=args.device)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/pytorch2onnx.py", line 60, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/utils/utils.py", line 38, in build_task_processor
    check_backend_device(deploy_cfg=deploy_cfg, device=device)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/utils/utils.py", line 16, in check_backend_device
    backend = get_backend(deploy_cfg).value
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/utils/config_utils.py", line 106, in get_backend
    assert 'type' in backend_config, 'The backend config of deploy config'\
AssertionError: The backend config of deploy configrequires a "type" field`

### Reproduction

根据mmdeploy文档 -> 快速上手 -> 操作概述 -> 模型转换， 执行：
`python mmdeploy/tools/torch2onnx.py mmdeploy/configs/mmedit/super-resolution/super-resolution_static.py mmediting/configs/restorers/edsr/edsr_x4c64b16_g1_300k_div2k.py mmediting/checkpoint/edsr_x4c64b16_1x16_300k_div2k_20200608-3c2af8a3.pth mmediting/tests/data/lq/baboon_x4.png --work-dir mmdeploy/work_dir/`

### Environment

```Shell
2022-11-17 23:06:16,909 - mmdeploy - INFO - 

2022-11-17 23:06:16,909 - mmdeploy - INFO - **********Environmental information**********
2022-11-17 23:06:17,233 - mmdeploy - INFO - sys.platform: linux
2022-11-17 23:06:17,233 - mmdeploy - INFO - Python: 3.7.15 (default, Nov 16 2022, 23:35:12) [GCC 11.3.0]
2022-11-17 23:06:17,233 - mmdeploy - INFO - CUDA available: True
2022-11-17 23:06:17,233 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3060
2022-11-17 23:06:17,233 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda-11.7
2022-11-17 23:06:17,233 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.99
2022-11-17 23:06:17,233 - mmdeploy - INFO - GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
2022-11-17 23:06:17,233 - mmdeploy - INFO - PyTorch: 1.13.0+cu117
2022-11-17 23:06:17,233 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.6  (built against CUDA 11.8)
    - Built with CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

2022-11-17 23:06:17,233 - mmdeploy - INFO - TorchVision: 0.14.0+cu117
2022-11-17 23:06:17,233 - mmdeploy - INFO - OpenCV: 4.5.4
2022-11-17 23:06:17,233 - mmdeploy - INFO - MMCV: 1.7.0
2022-11-17 23:06:17,233 - mmdeploy - INFO - MMCV Compiler: GCC 9.3
2022-11-17 23:06:17,234 - mmdeploy - INFO - MMCV CUDA Compiler: 11.7
2022-11-17 23:06:17,234 - mmdeploy - INFO - MMDeploy: 0.10.0+99040d5
2022-11-17 23:06:17,234 - mmdeploy - INFO - 

2022-11-17 23:06:17,234 - mmdeploy - INFO - **********Backend information**********
2022-11-17 23:06:17,636 - mmdeploy - INFO - onnxruntime: 1.13.1	ops_is_avaliable : True
2022-11-17 23:06:17,637 - mmdeploy - INFO - tensorrt: None	ops_is_avaliable : False
2022-11-17 23:06:17,653 - mmdeploy - INFO - ncnn: None	ops_is_avaliable : False
2022-11-17 23:06:17,653 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-11-17 23:06:17,654 - mmdeploy - INFO - openvino_is_avaliable: False
2022-11-17 23:06:17,669 - mmdeploy - INFO - snpe_is_available: False
2022-11-17 23:06:17,670 - mmdeploy - INFO - ascend_is_available: False
2022-11-17 23:06:17,671 - mmdeploy - INFO - coreml_is_available: False
2022-11-17 23:06:17,671 - mmdeploy - INFO - 

2022-11-17 23:06:17,671 - mmdeploy - INFO - **********Codebase information**********
2022-11-17 23:06:17,672 - mmdeploy - INFO - mmdet:	None
2022-11-17 23:06:17,672 - mmdeploy - INFO - mmseg:	None
2022-11-17 23:06:17,672 - mmdeploy - INFO - mmcls:	None
2022-11-17 23:06:17,672 - mmdeploy - INFO - mmocr:	None
2022-11-17 23:06:17,672 - mmdeploy - INFO - mmedit:	0.16.0
2022-11-17 23:06:17,672 - mmdeploy - INFO - mmdet3d:	None
2022-11-17 23:06:17,672 - mmdeploy - INFO - mmpose:	None
2022-11-17 23:06:17,672 - mmdeploy - INFO - mmrotate:	None
```

### Error traceback

```Shell
`2022-11-17 22:04:22,762 - mmdeploy - INFO - torch2onnx: 
	model_cfg: mmediting/configs/restorers/edsr/edsr_x4c64b16_g1_300k_div2k.py 
	deploy_cfg: mmdeploy/configs/mmedit/super-resolution/super-resolution_static.py
Traceback (most recent call last):
  File "/home/wjh/software/pycharm-2020.3.5/plugins/python/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/wjh/software/pycharm-2020.3.5/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/wjh/learn/super_resolution_project/mmdeploy/tools/torch2onnx.py", line 85, in <module>
    main()
  File "/home/wjh/learn/super_resolution_project/mmdeploy/tools/torch2onnx.py", line 54, in main
    device=args.device)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/pytorch2onnx.py", line 60, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/utils/utils.py", line 38, in build_task_processor
    check_backend_device(deploy_cfg=deploy_cfg, device=device)
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/apis/utils/utils.py", line 16, in check_backend_device
    backend = get_backend(deploy_cfg).value
  File "/home/wjh/venv/learn/super_resolution/lib/python3.7/site-packages/mmdeploy/utils/config_utils.py", line 106, in get_backend
    assert 'type' in backend_config, 'The backend config of deploy config'\
AssertionError: The backend config of deploy configrequires a "type" field`
```

**Comment by cooltd** [comment]
I meet the same error. How do you solve this problem? thanks

**Comment by aldazhu** [comment]
Same Error.

**Comment by KeyKy** [comment]
Same Error
