### ISSUE TITLE
when deploy  got MMCVRoiAlign is not a registered

### ISSUE THREAD

**Issue by txlcx** [open-mmlab/mmdeploy#139]
when i use deploy.py  got this log ,  MMCVRoiAlign is not a registered  how can i fix it
```
/opt/conda/lib/python3.7/site-packages/mmdet/datasets/utils.py:69: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
2022-02-08:08:35:57,root INFO     [deploy.py:72] torch2onnx start.
load checkpoint from local path: model/latest.pth
/opt/conda/lib/python3.7/site-packages/mmdet/datasets/utils.py:69: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/opt/conda/lib/python3.7/site-packages/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
/opt/conda/lib/python3.7/site-packages/mmdet/core/anchor/anchor_generator.py:333: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/opt/conda/lib/python3.7/site-packages/mmdet/core/anchor/anchor_generator.py:370: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '
/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py:77: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/pytorch/functions/topk.py:27: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  k = torch.tensor(k, device=input.device, dtype=torch.long)
/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/pytorch/functions/topk.py:32: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return ctx.origin_func(input, k, dim=dim, largest=largest, sorted=sorted)
/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
111111111111111111111
{'score_threshold': 0.05, 'confidence_threshold': 0.005, 'iou_threshold': 0.5, 'max_output_boxes_per_class': 200, 'pre_top_k': 5000, 'keep_top_k': 100, 'background_label_id': -1}
{'nms_across_levels': False, 'nms_pre': 1000, 'nms_post': 1000, 'max_num': 1000, 'nms_thr': 0.7, 'min_bbox_size': 0, 'nms': {'type': 'nms', 'iou_threshold': 0.5}}
/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:109: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  iou_threshold = torch.tensor([iou_threshold], dtype=torch.float32)
/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:110: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  score_threshold = torch.tensor([score_threshold], dtype=torch.float32)
/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/mmcv/ops/nms.py:40: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  score_threshold = float(score_threshold)
/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/mmcv/ops/nms.py:41: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  iou_threshold = float(iou_threshold)
/opt/conda/lib/python3.7/site-packages/mmcv/ops/nms.py:159: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
/opt/conda/lib/python3.7/site-packages/mmcv/ops/nms.py:160: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
/opt/conda/lib/python3.7/site-packages/mmcv/ops/nms.py:29: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if max_num > 0:
/opt/conda/lib/python3.7/site-packages/mmcv/ops/roi_align.py:80: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert rois.size(1) == 5, 'RoI must be (idx, x1, y1, x2, y2)!'
/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/codebase/mmdet/models/roi_heads/single_level_roi_extractor.py:138: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  dtype=inds.dtype), inds + num_levels * 2
/opt/conda/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:2607: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  "If indices include negative values, the exported graph will produce incorrect results.")
2022-02-08:08:36:55,root INFO     [deploy.py:86] torch2onnx success.
2022-02-08:08:36:55,root INFO     [deploy.py:72] visualize onnxruntime model start.
2022-02-08:08:37:04,root WARNING  [wrapper.py:52] The library of onnxruntime custom ops does             not exist: 
2022-02-08:08:37:04,root ERROR    [deploy.py:67] [ONNXRuntimeError] : 1 : FAIL : Load model from model/out1/end2end.onnx failed:Fatal error: MMCVRoiAlign is not a registered function/op
Traceback (most recent call last):
  File "/data/sdv3/lcx/mmdeploy/mmdeploy-master/tools/deploy.py", line 62, in target_wrapper
    result = target(*args, **kwargs)
  File "/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/apis/visualize.py", line 55, in visualize_model
    model = task_processor.init_backend_model(model)
  File "/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 75, in init_backend_model
    model_files, self.model_cfg, self.deploy_cfg, device=self.device)
  File "/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 651, in build_object_detection_model
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 34, in __build_backend_model
    **kwargs)
  File "/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 59, in __init__
    backend=backend, backend_files=backend_files, device=device)
  File "/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 76, in _init_wrapper
    output_names=output_names)
  File "/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/codebase/base/backend_model.py", line 55, in _build_wrapper
    output_names=output_names)
  File "/data/sdv3/lcx/mmdeploy/mmdeploy-master/mmdeploy/backend/onnxruntime/wrapper.py", line 58, in __init__
    onnx_file, session_options, providers=providers)
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 368, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from model/out1/end2end.onnx failed:Fatal error: MMCVRoiAlign is not a registered function/op
2022-02-08:08:37:05,root ERROR    [deploy.py:83] visualize onnxruntime model failed.
```

**Comment by RunningLeon** [comment]
> 2022-02-08:08:37:04,root WARNING  [wrapper.py:52] The library of onnxruntime custom ops does             not exist: 


@txlcx Hi, as warning message suggests, you have to build onnxruntime custom ops. You can refer to here https://mmdeploy.readthedocs.io/en/latest/backends/onnxruntime.html#build-custom-ops

**Comment by txlcx** [comment]
> > 2022-02-08:08:37:04,root WARNING [wrapper.py:52] onnxruntime 自定义操作库不存在：
> 
> @txlcx嗨，正如警告消息所示，您必须构建 onnxruntime 自定义操作。您可以参考这里https://mmdeploy.readthedocs.io/en/latest/backends/onnxruntime.html#build-custom-ops

i install onnxruntime use pip install ,  my onnxruntime version is 1.10.0.
i always nend to build custom ops ?

**Comment by RunningLeon** [comment]
> > > 2022-02-08:08:37:04,root WARNING [wrapper.py:52] onnxruntime 自定义操作库不存在：
> > 
> > 
> > @txlcx嗨，正如警告消息所示，您必须构建 onnxruntime 自定义操作。您可以参考这里https://mmdeploy.readthedocs.io/en/latest/backends/onnxruntime.html#build-custom-ops
> 
> i install onnxruntime use pip install , my onnxruntime version is 1.10.0. i nend to build custom ops ?

@txlcx Yes, you have to build. ` MMCVRoiAlign` is a custom operator for onnxruntime and is put [here](https://github.com/open-mmlab/mmdeploy/blob/cce81d3ce01f67fb68247a13f3af323c574c5b9c/csrc/backend_ops/onnxruntime/roi_align/roi_align.h#L42)

**Comment by txlcx** [comment]
> > > > 2022-02-08:08:37:04,root WARNING [wrapper.py:52] onnxruntime 自定义操作库不存在：
> > > 
> > > 
> > > @txlcx嗨，正如警告消息所示，您必须构建 onnxruntime 自定义操作。您可以参考这里https://mmdeploy.readthedocs.io/en/latest/backends/onnxruntime.html#build-custom-ops
> > 
> > 
> > i install onnxruntime use pip install , my onnxruntime version is 1.10.0. i nend to build custom ops ?
> 
> @txlcx Yes, you have to build. ` MMCVRoiAlign` is a custom operator for onnxruntime and is put [here](https://github.com/open-mmlab/mmdeploy/blob/cce81d3ce01f67fb68247a13f3af323c574c5b9c/csrc/backend_ops/onnxruntime/roi_align/roi_align.h#L42)

![image](https://user-images.githubusercontent.com/78129052/153136133-71585943-6ec1-41df-9250-ef7b60591d2c.png)
this is the list of onnx support , does it mean roialign only support CPU not GPU

**Comment by txlcx** [comment]
> > > > > 2022-02-08:08:37:04,root WARNING [wrapper.py:52] The library of onnxruntime custom ops does not exist:
> > > > 
> > > > 
> > > > @txlcxHi, as warning message suggests, you have to build onnxruntime custom ops. You can refer to here
> > > > https://mmdeploy.readthedocs.io/en/latest/backends/onnxruntime.html#build-custom-ops
> > > 
> > > 
> > > i install onnxruntime use pip install , my onnxruntime version is 1.10.0. i nend to build custom ops ?
> > 
> > 
> > @txlcx Yes, you have to build. ` MMCVRoiAlign` is a custom operator for onnxruntime and is put [here](https://github.com/open-mmlab/mmdeploy/blob/cce81d3ce01f67fb68247a13f3af323c574c5b9c/csrc/backend_ops/onnxruntime/roi_align/roi_align.h#L42)
> 
> ![image](https://user-images.githubusercontent.com/78129052/153136133-71585943-6ec1-41df-9250-ef7b60591d2c.png) this is the list of onnx support , does it mean roialign only support CPU not GPU

**Comment by RunningLeon** [comment]
@txlcx Yes, `MMCVRoiAlign` op only supports CPU. But you can still run with onnxruntime-gpu and it would fallback to CPU on this op automatically.

**Comment by RunningLeon** [comment]
closed due to age.

**Comment by dungng27** [comment]
> > 2022-02-08:08:37:04,root WARNING  [wrapper.py:52] The library of onnxruntime custom ops does             not exist:
> 
> @txlcx Hi, as warning message suggests, you have to build onnxruntime custom ops. You can refer to here https://mmdeploy.readthedocs.io/en/latest/backends/onnxruntime.html#build-custom-ops

The link seems to die. Could you send it again?

**Comment by RunningLeon** [comment]
> > > 2022-02-08:08:37:04,root WARNING  [wrapper.py:52] The library of onnxruntime custom ops does             not exist:
> > 
> > 
> > @txlcx Hi, as warning message suggests, you have to build onnxruntime custom ops. You can refer to here https://mmdeploy.readthedocs.io/en/latest/backends/onnxruntime.html#build-custom-ops
> 
> The link seems to die. I tried to build custom ops but it doesn't work. Could you send the link again?

Hi, this is the new link: https://mmdeploy.readthedocs.io/en/latest/05-supported-backends/onnxruntime.html#build-custom-ops
