### ISSUE TITLE
[Bug]  ImportError: cannot import name 'create_calib_input_data' from 'mmdeploy.apis' 

### ISSUE THREAD

**Issue by SHX9610** [open-mmlab/mmdeploy#1405]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

RUN python tools/deploy.py configs/mmcls/classification_tensorrt_dynamic-224x224-224x224.py ../mmclassification/configs/mobilenet_v2/mobilenet-v2_8xb32_in1k.py ../mmclassification/work-dirs/version1-11212022/epoch_600.pt 128x128.jpg --work-dir ../mmdeploy_out/lsri/dynamictrt/ --device cuda --show --dump-info

I got an error,
Traceback (most recent call last):
  File "tools/deploy.py", line 12, in <module>
    from mmdeploy.apis import (create_calib_input_data, extract_model,
ImportError: cannot import name 'create_calib_input_data' from 'mmdeploy.apis' (/root/workspace/mmdeploy/mmdeploy/apis/__init__.py)

I have re-install mmdeploy and cuda/cudnn, but not work.......

 

### Reproduction

NONE

### Environment

```Shell
In docker, environment is checked
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "tools/deploy.py", line 12, in <module>
    from mmdeploy.apis import (create_calib_input_data, extract_model,
ImportError: cannot import name 'create_calib_input_data' from 'mmdeploy.apis' (/root/workspace/mmdeploy/mmdeploy/apis/__init__.py)
```

**Comment by hanrui1sensetime** [comment]
Please try to comment the try except in [here](https://github.com/open-mmlab/mmdeploy/blob/master/mmdeploy/apis/__init__.py#L4), but do not comment the import code, i.e. only execute the import code without try except statements. It can expose what package you are really missing.

**Comment by mikeklm** [comment]
I get the same error when I try to deploy a mask-rcnn model with swin backbone to onnx.

If I move the import statement out of the try/except block, I get the same traceback
Traceback (most recent call last):
  File "tools/deploy.py", line 12, in <module>
    from mmdeploy.apis import (create_calib_input_data, extract_model,
ImportError: cannot import name 'create_calib_input_data' from 'mmdeploy.apis' (/home/mkraus/onnx_export/mmdeploy/mmdeploy/apis/__init__.py)

**Comment by hanrui1sensetime** [comment]
> I get the same error when I try to deploy a mask-rcnn model with swin backbone to onnx.
> 
> If I move the import statement out of the try/except block, I get the same traceback Traceback (most recent call last): File "tools/deploy.py", line 12, in from mmdeploy.apis import (create_calib_input_data, extract_model, ImportError: cannot import name 'create_calib_input_data' from 'mmdeploy.apis' (/home/mkraus/onnx_export/mmdeploy/mmdeploy/apis/**init**.py)

You can have a small try first: start python, and import mmdeploy. Then see whether the import failed or not.
If import mmdeploy failed. Please check into mmdeploy direction, and execute `pip install -e .`

**Comment by SHX9610** [comment]
> > I get the same error when I try to deploy a mask-rcnn model with swin backbone to onnx.
> > If I move the import statement out of the try/except block, I get the same traceback Traceback (most recent call last): File "tools/deploy.py", line 12, in from mmdeploy.apis import (create_calib_input_data, extract_model, ImportError: cannot import name 'create_calib_input_data' from 'mmdeploy.apis' (/home/mkraus/onnx_export/mmdeploy/mmdeploy/apis/**init**.py)
> 
> You can have a small try first: start python, and import mmdeploy. Then see whether the import failed or not. If import mmdeploy failed. Please check into mmdeploy direction, and execute `pip install -e .`


Import mmdeploy is okay.
And I cd mmdeloy dir, "pip install -e ."
The error still exists. So I was confused.

I reused the container that didn't report this error before.  and I no longer explored this error.
If someone has found the root of the problem, plz post it, thx.

**Comment by mikeklm** [comment]
I decided to write the model using torchvision only,  and was able to export it to onnx without any issues.
