### ISSUE TITLE
Convert retinanet_r50 error

### ISSUE THREAD

**Issue by JeffDing** [open-mmlab/mmdeploy#1414]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Convert retinet_ R50 model, After the prompt：ATC start working now, ,it will run for a long time. The CPU occupancy is always 100%. After running for a period of time, it will be stuck, and then an error message will appear.

### Reproduction

python tools/deploy.py configs/mmdet/detection/detection_ascend_static-800x1344.py retinanet_r50_fpn_1x_coco.py retinanet_r50_fpn_1x_coco_20200130-c2398f9e.pth demo/resources/det.jpg --work-dir mmdeploy_models/mmdet/retinanet/cann --device cpu --dump-info

### Environment

```Shell
CPU：Kunpeng 920*1
Memory：4GB
NPU:Ascend 310
```

### Error traceback

```Shell
error information:
2022-11-22 20:20:53,377 - mmdeploy - INFO - Execute onnx optimize passes.
2022-11-22 20:20:54,057 - mmdeploy - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
2022-11-22 20:20:54,550 - mmdeploy - INFO - Start pipeline mmdeploy.backend.ascend.onnx2ascend.from_onnx in main process
2022-11-22 20:20:55,078 - mmdeploy - INFO - atc --model=mmdeploy_models/mmdet/retinanet/cann/end2end.onnx --framework=5 --output=mmdeploy_models/mmdet/retinanet/cann/end2end --soc_version=Ascend310 --input_format=NCHW --input_shape=input:1,3,800,1344
ATC start working now, please wait for a moment.
Process ForkServerProcess-2:
Traceback (most recent call last):
  File "/home/HwHiAiUser/miniconda3/envs/mmlab/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/HwHiAiUser/miniconda3/envs/mmlab/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 75, in wrapper
    raise exp
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 72, in wrapper
    func(*args, **kwargs)
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/tbe/common/repository_manager/route.py", line 355, in server
    conn.send(json.dumps({
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by lvhan028** [comment]
@JeffDing would you mind updating your investigation here?
