### ISSUE TITLE
[Bug] branch 'dev-1.x' cannot generate the onnx model

### ISSUE THREAD

**Issue by labmanno004** [open-mmlab/mmdeploy#1438]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I used the docker file in the branch 'dev-1. x' to build the docker image and run the docker container.

question1：I configure the environment strictly according to the installation steps of the documents in branch ‘dev-1.x’. The installation instruction for mmcv in this branch is 'mim install "mmcv>=2.0.0rc2"', which seems incorrect, because running 'mmdeploy/tools/check_env.py' will report an error of 'ImportError: cannot import name 'get_git_hash' from 'mmcv.utils''(*error1*).So I replace 'mim install "mmcv>=2.0.0rc2"' with 'mim install mmcv-full'.

question2:  Refer to question 1. If I use 'mmcv2.0.0rc2', the command(*command1*) to  generate the onnx model will report an error of 'AttributeError: module 'mmcv' has no attribute 'Config''(*error2*). If I use 'mmcv-full1.7.0', the error 'AttributeError: 'list' object has no attribute 'icdar2015_textdet_train''(*error3*) will be reported.

### Reproduction

command1: python mmdeploy/tools/deploy.py mmdeploy/configs/mmocr/text-detection/text-detection_onnxruntime_dynamic.py mmocr/configs/textdet/dbnet/dbnet_resnet18_fpnc_1200e_icdar2015.py checkpoints/dbnet_resnet18_fpnc_1200e_icdar2015_20220825_221614-7c0e94f2.pth mmocr/demo/demo_text_det.jpg --work-dir mmdeploy_model/dbnet --device cpu --dump-info

### Environment

```Shell
Use mmcv-full-1.7.0 to replace mmcv-2.0.0rc2 required in the document, because if I do not replace, run check_ Env.py will report an error.

/opt/conda/lib/python3.7/site-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
2022-11-25 05:16:17,820 - mmdeploy - INFO - 

2022-11-25 05:16:17,820 - mmdeploy - INFO - **********Environmental information**********
fatal: not a git repository (or any of the parent directories): .git
2022-11-25 05:16:18,021 - mmdeploy - INFO - sys.platform: linux
2022-11-25 05:16:18,021 - mmdeploy - INFO - Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
2022-11-25 05:16:18,021 - mmdeploy - INFO - CUDA available: False
2022-11-25 05:16:18,021 - mmdeploy - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
2022-11-25 05:16:18,021 - mmdeploy - INFO - PyTorch: 1.10.0+cpu
2022-11-25 05:16:18,021 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, 

2022-11-25 05:16:18,021 - mmdeploy - INFO - TorchVision: 0.11.0+cpu
2022-11-25 05:16:18,021 - mmdeploy - INFO - OpenCV: 4.5.3-openvino
2022-11-25 05:16:18,021 - mmdeploy - INFO - MMCV: 1.7.0
2022-11-25 05:16:18,021 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2022-11-25 05:16:18,021 - mmdeploy - INFO - MMCV CUDA Compiler: not available
2022-11-25 05:16:18,021 - mmdeploy - INFO - MMDeploy: 0.10.0+
2022-11-25 05:16:18,022 - mmdeploy - INFO - 

2022-11-25 05:16:18,022 - mmdeploy - INFO - **********Backend information**********
2022-11-25 05:16:18,665 - mmdeploy - INFO - onnxruntime: 1.8.1  ops_is_avaliable : True
2022-11-25 05:16:18,667 - mmdeploy - INFO - tensorrt: None      ops_is_avaliable : False
2022-11-25 05:16:18,691 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : True
2022-11-25 05:16:18,692 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-11-25 05:16:18,716 - mmdeploy - INFO - openvino_is_avaliable: True
2022-11-25 05:16:18,739 - mmdeploy - INFO - snpe_is_available: False
2022-11-25 05:16:18,740 - mmdeploy - INFO - ascend_is_available: False
2022-11-25 05:16:18,741 - mmdeploy - INFO - coreml_is_available: False
2022-11-25 05:16:18,741 - mmdeploy - INFO - 

2022-11-25 05:16:18,741 - mmdeploy - INFO - **********Codebase information**********
2022-11-25 05:16:18,760 - mmdeploy - INFO - mmdet:      None
2022-11-25 05:16:18,760 - mmdeploy - INFO - mmseg:      None
2022-11-25 05:16:18,760 - mmdeploy - INFO - mmcls:      None
2022-11-25 05:16:18,760 - mmdeploy - INFO - mmocr:      None
2022-11-25 05:16:18,760 - mmdeploy - INFO - mmedit:     None
2022-11-25 05:16:18,760 - mmdeploy - INFO - mmdet3d:    None
2022-11-25 05:16:18,760 - mmdeploy - INFO - mmpose:     None
2022-11-25 05:16:18,760 - mmdeploy - INFO - mmrotate:   None
2022-11-25 05:16:18,760 - mmdeploy - INFO - mmaction:   None
```

### Error traceback

```Shell
error1: Traceback (most recent call last):
  File "/root/workspace/mmdeploy/tools/check_env.py", line 4, in <module>
    from mmcv.utils import get_git_hash
ImportError: cannot import name 'get_git_hash' from 'mmcv.utils' (/opt/conda/lib/python3.7/site-packages/mmcv/utils/__init__.py)
error2: Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 12, in <module>
    from mmdeploy.apis import (create_calib_input_data, extract_model,
  File "/root/workspace/mmdeploy/mmdeploy/__init__.py", line 4, in <module>
    from mmdeploy.utils import get_root_logger
  File "/root/workspace/mmdeploy/mmdeploy/utils/__init__.py", line 18, in <module>
    from .config_utils import (cfg_apply_marks, get_backend,
  File "/root/workspace/mmdeploy/mmdeploy/utils/config_utils.py", line 10, in <module>
    def load_config(*args) -> List[mmcv.Config]:
AttributeError: module 'mmcv' has no attribute 'Config'
error3: /opt/conda/lib/python3.7/site-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
/opt/conda/lib/python3.7/site-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 447, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 119, in main
    deploy_cfg, model_cfg = load_config(deploy_cfg_path, model_cfg_path)
  File "/root/workspace/mmdeploy/mmdeploy/utils/config_utils.py", line 29, in load_config
    configs = [_load_config(cfg) for cfg in args]
  File "/root/workspace/mmdeploy/mmdeploy/utils/config_utils.py", line 29, in <listcomp>
    configs = [_load_config(cfg) for cfg in args]
  File "/root/workspace/mmdeploy/mmdeploy/utils/config_utils.py", line 22, in _load_config
    cfg = mmcv.Config.fromfile(cfg)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 341, in fromfile
    use_predefined_variables)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 208, in _file2dict
    mod = import_module(temp_module_name)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpytvktudk/tmpn1785u7q.py", line 9, in <module>
AttributeError: 'list' object has no attribute 'icdar2015_textdet_train'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f3e76fd57a0>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/opt/conda/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpytvktudk/tmpn1785u7q.py'
```

**Comment by AllentDan** [comment]
Hi, please install mmengine, use mmdet 3.x, mmocr 1.x and mmcv 2.x.

BTW, paste the error log even if `python tool/check_env.py` failed.

**Comment by labmanno004** [comment]
> Hi, please install mmengine, use mmdet 3.x, mmocr 1.x and mmcv 2.x.
> 
> BTW, paste the error log even if `python tool/check_env.py` failed.

(base) root@sse-lg-112-41:~/workspace# mim list
/opt/conda/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Package    Version    Source
---------  ---------  -----------------------------------------
mmcv       2.0.0rc2   https://github.com/open-mmlab/mmcv
mmdet      3.0.0rc3   https://github.com/open-mmlab/mmdetection
mmengine   0.3.1      https://github.com/open-mmlab/mmengine
mmocr      1.0.0rc3   /root/workspace/mmocr
(base) root@sse-lg-112-41:~/workspace# /opt/conda/bin/python /root/workspace/mmdeploy/tools/check_env.py
Traceback (most recent call last):
  File "/root/workspace/mmdeploy/tools/check_env.py", line 4, in <module>
    from mmcv.utils import get_git_hash
ImportError: cannot import name 'get_git_hash' from 'mmcv.utils' (/opt/conda/lib/python3.7/site-packages/mmcv/utils/__init__.py)

**Comment by AllentDan** [comment]
Hi, seems you are using pre-built mmcv package instead of local mmcv.

**Comment by labmanno004** [comment]
> Hi, seems you are using pre-built mmcv package instead of local mmcv.

But I configure the environment according to the tutorial. You mean I must build mmcv from source?

**Comment by AllentDan** [comment]
You can also use pre-built package. But the version `>=2.0.0rc1` should be used rather than master.

**Comment by labmanno004** [comment]
> You can also use pre-built package. But the version `>=2.0.0rc1` should be used rather than master.

So as I described above, there should be no errors in my environment configuration.

**Comment by AllentDan** [comment]
I see. You are not using mmdeploy dev-1.x. You are using master branch. Check [this](https://github.com/open-mmlab/mmdeploy/blob/e6b0b8c00a6f638283ca93d675dff857dfe909dc/tools/check_env.py#L4) out please.

**Comment by labmanno004** [comment]
> I see. You are not using mmdeploy dev-1.x. You are using master branch. Check [this](https://github.com/open-mmlab/mmdeploy/blob/e6b0b8c00a6f638283ca93d675dff857dfe909dc/tools/check_env.py#L4) out please.

NO.I am using mmdeploy dev-1.x.The environment I use is built with the docker file in mmdeploy dev-1. x.

**Comment by AllentDan** [comment]
Got you. It was a bug in the docker file. I will fix it ASAP.

**Comment by AllentDan** [comment]
Hi, @labmanno004 . Pull the latest dev-1.x please. The bug was fixed.
