### ISSUE TITLE
[Bug] RuntimeError: invalid unordered_map<K, T> key 

### ISSUE THREAD

**Issue by caj-github** [open-mmlab/mmdeploy#1448]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

RuntimeError: invalid unordered_map<K, T> key error

### Reproduction

when i run deply.py in mmdeploy-dev-1.x, report a  RuntimeError: invalid unordered_map<K, T> key error,
the model is retinanet

### Environment

```Shell
win10 TensorRT-8.5.1.7 cuda11.7 mmdeploy-dev-1.x
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "D:\anaconda3\envs\mmcv\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\anaconda3\envs\mmcv\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\apis\pytorch2onnx.py", line 96, in torch2onnx
    export(
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\apis\onnx\export.py", line 122, in export
    torch.onnx.export(
  File "D:\anaconda3\envs\mmcv\lib\site-packages\torch\onnx\utils.py", line 504, in export
    _export(
  File "D:\anaconda3\envs\mmcv\lib\site-packages\torch\onnx\utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\core\rewriters\rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\apis\onnx\optimizer.py", line 10, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "D:\anaconda3\envs\mmcv\lib\site-packages\torch\onnx\utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "D:\anaconda3\envs\mmcv\lib\site-packages\torch\onnx\utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "D:\anaconda3\envs\mmcv\lib\site-packages\torch\onnx\utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "D:\anaconda3\envs\mmcv\lib\site-packages\torch\jit\_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "D:\anaconda3\envs\mmcv\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda3\envs\mmcv\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "D:\anaconda3\envs\mmcv\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "D:\anaconda3\envs\mmcv\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda3\envs\mmcv\lib\site-packages\torch\nn\modules\module.py", line 1178, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\core\rewriters\rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\codebase\mmdet\models\detectors\single_stage.py", line 74, in single_stage_detector__forward
    return __forward_impl(
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\core\optimizers\function_marker.py", line 261, in g
    rets = f(*args, **kwargs)
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\codebase\mmdet\models\detectors\single_stage.py", line 24, in __forward_impl
    output = self.bbox_head.predict(x, data_samples, rescale=False)
  File "D:\anaconda3\envs\mmcv\lib\site-packages\mmdet\models\dense_heads\base_dense_head.py", line 197, in predict
    predictions = self.predict_by_feat(
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\core\rewriters\rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\codebase\mmdet\models\dense_heads\base_dense_head.py", line 73, in base_dense_head__predict_by_feat
    mlvl_priors = self.prior_generator.grid_priors(
  File "D:\anaconda3\envs\mmcv\lib\site-packages\mmdet\models\task_modules\prior_generators\anchor_generator.py", line 242, in grid_priors
    anchors = self.single_level_grid_priors(
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\core\rewriters\rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "e:\dnntrain\test\mmdeploy-dev-1.x\mmdeploy\codebase\mmdet\models\task_modules\prior_generators\anchor.py", line 100, in anchorgenerator__single_level_grid_priors__trt
    return grid_priors_trt(base_anchors, feat_h, feat_w, stride_h, stride_w)
RuntimeError: invalid unordered_map<K, T> key
```

**Comment by lvhan028** [comment]
Could you run `python tools/check_env.py` and paste its output here?

**Comment by caj-github** [comment]
11/29 14:44:09 - mmengine - INFO - **********Environmental information**********
11/29 14:44:11 - mmengine - INFO - sys.platform: win32
11/29 14:44:11 - mmengine - INFO - Python: 3.8.13 (default, Oct 19 2022, 22:38:03) [MSC v.1916 64 bit (AMD64)]
11/29 14:44:11 - mmengine - INFO - CUDA available: True
11/29 14:44:11 - mmengine - INFO - numpy_random_seed: 2147483648
11/29 14:44:11 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3090
11/29 14:44:11 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
11/29 14:44:11 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.99
11/29 14:44:11 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.31.31106.2 版
11/29 14:44:11 - mmengine - INFO - GCC: n/a
11/29 14:44:11 - mmengine - INFO - PyTorch: 1.13.0+cu117
11/29 14:44:11 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

11/29 14:44:11 - mmengine - INFO - TorchVision: 0.14.0+cu117
11/29 14:44:11 - mmengine - INFO - OpenCV: 4.6.0
11/29 14:44:11 - mmengine - INFO - MMEngine: 0.3.2
11/29 14:44:11 - mmengine - INFO - MMCV: 2.0.0rc3
11/29 14:44:11 - mmengine - INFO - MMCV Compiler: MSVC 192829924
11/29 14:44:11 - mmengine - INFO - MMCV CUDA Compiler: 11.7
11/29 14:44:11 - mmengine - INFO - MMDeploy: 0.10.0+
11/29 14:44:11 - mmengine - INFO -

11/29 14:44:11 - mmengine - INFO - **********Backend information**********
11/29 14:44:13 - mmengine - INFO - onnxruntime: 1.12.1  ops_is_avaliable : True
11/29 14:44:13 - mmengine - INFO - tensorrt: 8.5.1.7    ops_is_avaliable : True
11/29 14:44:13 - mmengine - INFO - ncnn: None   ops_is_avaliable : False
11/29 14:44:14 - mmengine - INFO - pplnn_is_avaliable: False   
11/29 14:44:14 - mmengine - INFO - openvino_is_avaliable: False
11/29 14:44:14 - mmengine - INFO - snpe_is_available: False
11/29 14:44:14 - mmengine - INFO - ascend_is_available: False
11/29 14:44:14 - mmengine - INFO - coreml_is_available: False
11/29 14:44:14 - mmengine - INFO -

11/29 14:44:14 - mmengine - INFO - **********Codebase information**********
11/29 14:44:14 - mmengine - INFO - mmdet:       3.0.0rc4
11/29 14:44:14 - mmengine - INFO - mmseg:       1.0.0rc1
11/29 14:44:14 - mmengine - INFO - mmcls:       1.0.0rc3
11/29 14:44:14 - mmengine - INFO - mmocr:       1.0.0rc3
11/29 14:44:14 - mmengine - INFO - mmedit:      None
11/29 14:44:14 - mmengine - INFO - mmdet3d:     None
11/29 14:44:14 - mmengine - INFO - mmpose:      None
11/29 14:44:14 - mmengine - INFO - mmrotate:    None
11/29 14:44:14 - mmengine - INFO - mmaction:    None

**Comment by lvhan028** [comment]
@grimoire could you help investigate it?

**Comment by grimoire** [comment]
Please provide more detail about the model you are using and the script you used to convert the model.
I can not reproduce the error.

**Comment by caj-github** [comment]
i found it is same problem in other model, i degraded pytorch to 1.13 to 1.12.1+cu113 and recopile, it works now

**Comment by grimoire** [comment]
I see. PyTorch has update the export logic which include some ... trick.
I am trying to fix it in https://github.com/open-mmlab/mmdeploy/pull/1483 , Please have a try if you want to use PyTorch>=1.13
