### ISSUE TITLE
[Bug] ImportError: cannot import name 'register_all_modules' from 'mmcls.utils.setup_env'

### ISSUE THREAD

**Issue by Tender-hjd** [open-mmlab/mmdeploy#1480]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

- ImportError: cannot import name 'register_all_modules' from 'mmcls.utils.setup_env'

### Reproduction

When I run the demo in https://mmdeploy.readthedocs.io/en/latest/02-how-to-run/prebuilt_package_windows.html#onnx-runtime-example

### Environment

```Shell
12/02 16:50:54 - mmengine - INFO - **********Environmental information**********
fatal: not a git repository (or any of the parent directories): .git
12/02 16:50:59 - mmengine - INFO - sys.platform: win32
12/02 16:50:59 - mmengine - INFO - Python: 3.8.15 (default, Nov 24 2022, 14:38:14) [MSC v.1916 64 bit (AMD64)]
12/02 16:50:59 - mmengine - INFO - CUDA available: True
12/02 16:50:59 - mmengine - INFO - GPU 0: NVIDIA GeForce GTX 1650
12/02 16:50:59 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
12/02 16:50:59 - mmengine - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.8
12/02 16:50:59 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30146 版
12/02 16:50:59 - mmengine - INFO - GCC: n/a
12/02 16:50:59 - mmengine - INFO - PyTorch: 1.11.0+cu113
12/02 16:50:59 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

12/02 16:50:59 - mmengine - INFO - TorchVision: 0.12.0+cu113
12/02 16:50:59 - mmengine - INFO - OpenCV: 4.6.0
12/02 16:50:59 - mmengine - INFO - MMCV: 1.7.0
12/02 16:50:59 - mmengine - INFO - MMCV Compiler: MSVC 192829924
12/02 16:50:59 - mmengine - INFO - MMCV CUDA Compiler: 11.3
12/02 16:50:59 - mmengine - INFO - MMDeploy: 1.0.0rc0+
12/02 16:50:59 - mmengine - INFO -

12/02 16:50:59 - mmengine - INFO - **********Backend information**********
12/02 16:51:00 - mmengine - INFO - onnxruntime: 1.8.1   ops_is_avaliable : False
12/02 16:51:00 - mmengine - INFO - tensorrt: 8.5.1.7    ops_is_avaliable : True
12/02 16:51:00 - mmengine - INFO - ncnn: None   ops_is_avaliable : False
12/02 16:51:00 - mmengine - INFO - pplnn_is_avaliable: False
12/02 16:51:00 - mmengine - INFO - openvino_is_avaliable: False
12/02 16:51:00 - mmengine - INFO - snpe_is_available: False
12/02 16:51:00 - mmengine - INFO - ascend_is_available: False
12/02 16:51:00 - mmengine - INFO - coreml_is_available: False
12/02 16:51:00 - mmengine - INFO - 

12/02 16:51:00 - mmengine - INFO - **********Codebase information**********
12/02 16:51:00 - mmengine - INFO - mmdet:       2.26.0
12/02 16:51:00 - mmengine - INFO - mmseg:       None
12/02 16:51:00 - mmengine - INFO - mmcls:       0.24.1
12/02 16:51:00 - mmengine - INFO - mmocr:       None
12/02 16:51:00 - mmengine - INFO - mmedit:      None
12/02 16:51:00 - mmengine - INFO - mmdet3d:     None
12/02 16:51:00 - mmengine - INFO - mmpose:      None
12/02 16:51:00 - mmengine - INFO - mmrotate:    None
12/02 16:51:00 - mmengine - INFO - mmaction:    None
```

### Error traceback

```Shell
Traceback (most recent call last):
  File ".\demo.py", line 13, in <module>
    torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg, model_checkpoint, device)
  File "D:\conda_envs\tensorrt_deploy\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap     
    return self.call_function(func_name_, *args, **kwargs)
  File "D:\conda_envs\tensorrt_deploy\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "D:\conda_envs\tensorrt_deploy\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "D:\conda_envs\tensorrt_deploy\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__  
    ret = func(*args, **kwargs)
  File "D:\conda_envs\tensorrt_deploy\lib\site-packages\mmdeploy\apis\pytorch2onnx.py", line 59, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "D:\conda_envs\tensorrt_deploy\lib\site-packages\mmdeploy\apis\utils\utils.py", line 42, in build_task_processor 
    import_codebase(codebase_type, custom_module_list)
  File "D:\conda_envs\tensorrt_deploy\lib\site-packages\mmdeploy\codebase\__init__.py", line 36, in import_codebase     
    codebase.register_all_modules()
  File "D:\conda_envs\tensorrt_deploy\lib\site-packages\mmdeploy\codebase\mmcls\deploy\classification.py", line 34, in register_all_modules
    from mmcls.utils.setup_env import register_all_modules
ImportError: cannot import name 'register_all_modules' from 'mmcls.utils.setup_env' (d:\py-projects\tensorrt_deploy\mmclassification\mmcls\utils\setup_env.py)
```

**Comment by lvhan028** [comment]
According to the log, you are using `MMDeploy: 1.0.0rc0+` that comes from mmdeploy dev-1.x.
`dev-1.x` is implemented for OpenMMLab 2.0. Please refer to the release notes for the supported codebase version.

**Comment by irexyc** [comment]
If you use master branch of mmdet and mmcls, please use master branch of mmdeploy.

Or you should use dev-1.x branch of these repos. The dev-1.x doc link is https://mmdeploy.readthedocs.io/en/dev-1.x/02-how-to-run/prebuilt_package_windows.html

**Comment by Tender-hjd** [comment]
Thanks, let me have a try!
