### ISSUE TITLE
[Bug] AssertionError: The backend config of deploy configrequires a "type" field

### ISSUE THREAD

**Issue by cooltd** [open-mmlab/mmdeploy#1501]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I tried to deploy model from pytorch to onnx.
I follow the guide but it meet something wrong.

### Reproduction

python mmdeploy/tools/deploy.py \
    ./mmdeploy/configs/mmdet3d/voxel-detection/voxel-detection_static.py \
    ./mmdetection3d/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py \
    ./mmdetection3d/checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth \
    ./mmdetection3d/demo/data/kitti/kitti_000008.bin \
    --work-dir work-dir \
    --device cpu \
    --show

### Environment

```Shell
No CUDA runtime is found, using CUDA_HOME='/usr'
2022-12-08 14:40:01,411 - mmdeploy - INFO - 

2022-12-08 14:40:01,411 - mmdeploy - INFO - **********Environmental information**********
2022-12-08 14:40:01,621 - mmdeploy - INFO - sys.platform: linux
2022-12-08 14:40:01,622 - mmdeploy - INFO - Python: 3.8.15 (default, Nov 24 2022, 15:19:38) [GCC 11.2.0]
2022-12-08 14:40:01,622 - mmdeploy - INFO - CUDA available: False
2022-12-08 14:40:01,622 - mmdeploy - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
2022-12-08 14:40:01,622 - mmdeploy - INFO - PyTorch: 1.13.0
2022-12-08 14:40:01,622 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

2022-12-08 14:40:01,622 - mmdeploy - INFO - TorchVision: 0.14.0
2022-12-08 14:40:01,622 - mmdeploy - INFO - OpenCV: 4.6.0
2022-12-08 14:40:01,622 - mmdeploy - INFO - MMCV: 1.6.0
2022-12-08 14:40:01,622 - mmdeploy - INFO - MMCV Compiler: GCC 7.5
2022-12-08 14:40:01,622 - mmdeploy - INFO - MMCV CUDA Compiler: not available
2022-12-08 14:40:01,622 - mmdeploy - INFO - MMDeploy: 0.11.0+4046e13
2022-12-08 14:40:01,622 - mmdeploy - INFO - 

2022-12-08 14:40:01,622 - mmdeploy - INFO - **********Backend information**********
2022-12-08 14:40:01,895 - mmdeploy - INFO - onnxruntime: 1.8.1  ops_is_avaliable : True
2022-12-08 14:40:01,895 - mmdeploy - INFO - tensorrt: None      ops_is_avaliable : False
2022-12-08 14:40:01,907 - mmdeploy - INFO - ncnn: 1.0.20221208  ops_is_avaliable : False
2022-12-08 14:40:01,907 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-12-08 14:40:01,908 - mmdeploy - INFO - openvino_is_avaliable: False
2022-12-08 14:40:01,918 - mmdeploy - INFO - snpe_is_available: False
2022-12-08 14:40:01,918 - mmdeploy - INFO - ascend_is_available: False
2022-12-08 14:40:01,919 - mmdeploy - INFO - coreml_is_available: False
2022-12-08 14:40:01,919 - mmdeploy - INFO - 

2022-12-08 14:40:01,919 - mmdeploy - INFO - **********Codebase information**********
2022-12-08 14:40:01,930 - mmdeploy - INFO - mmdet:      None
2022-12-08 14:40:01,930 - mmdeploy - INFO - mmseg:      0.29.1
2022-12-08 14:40:01,930 - mmdeploy - INFO - mmcls:      0.24.1
2022-12-08 14:40:01,930 - mmdeploy - INFO - mmocr:      None
2022-12-08 14:40:01,930 - mmdeploy - INFO - mmedit:     None
2022-12-08 14:40:01,930 - mmdeploy - INFO - mmdet3d:    None
2022-12-08 14:40:01,930 - mmdeploy - INFO - mmpose:     None
2022-12-08 14:40:01,931 - mmdeploy - INFO - mmrotate:   None
2022-12-08 14:40:01,931 - mmdeploy - INFO - mmaction:   None
```

### Error traceback

```Shell
2022-12-08 14:34:22,362 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
Process Process-2:
Traceback (most recent call last):
  File "/home/tengda/anaconda3/envs/pointpillarsmmd/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/tengda/anaconda3/envs/pointpillarsmmd/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tengda/anaconda3/envs/pointpillarsmmd/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/tengda/anaconda3/envs/pointpillarsmmd/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 60, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/home/tengda/anaconda3/envs/pointpillarsmmd/lib/python3.8/site-packages/mmdeploy/apis/utils/utils.py", line 38, in build_task_processor
    check_backend_device(deploy_cfg=deploy_cfg, device=device)
  File "/home/tengda/anaconda3/envs/pointpillarsmmd/lib/python3.8/site-packages/mmdeploy/apis/utils/utils.py", line 16, in check_backend_device
    backend = get_backend(deploy_cfg).value
  File "/home/tengda/anaconda3/envs/pointpillarsmmd/lib/python3.8/site-packages/mmdeploy/utils/config_utils.py", line 106, in get_backend
    assert 'type' in backend_config, 'The backend config of deploy config'\
AssertionError: The backend config of deploy configrequires a "type" field
2022-12-08 14:34:22,535 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by tpoisonooo** [comment]
use `onnxruntime_dynamic` instead of `xx_static.py`.

AKA, try this deploy config:

```bash
python mmdeploy/tools/deploy.py
./mmdeploy/configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime_dynamic.py
./mmdetection3d/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py
./mmdetection3d/checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth
./mmdetection3d/demo/data/kitti/kitti_000008.bin
--work-dir work-dir
--device cpu
--show
```

**Comment by cooltd** [comment]
thank you for replying.
I tried this but it doesn't work.

**Comment by aldazhu** [comment]
@cooltd 
Hello! I encountered the same error when using `torch2onnx.py` to convert a PyTorch model to ONNX. I used `segmentation_static.py` as the reference config and noticed that it only contains "codebase_config" and "onnx_config" but no "backend_config". To resolve this, I added "backend_config = dict(type='onnxruntime')" to the deploy config, and it worked.

The final deploy config is as follows:
```
backend_config = dict(type='onnxruntime')
onnx_config = dict(
    type='onnx',
    export_params=True,
    keep_initializers_as_inputs=False,
    opset_version=11,
    save_file='chase_unet.onnx',
    input_names=['input'],
    output_names=['output'],
    input_shape=[512, 512],
    optimize=True
)
codebase_config = dict(type='mmseg', task='Segmentation', with_argmax=True)
```
