### ISSUE TITLE
[Bug] executing 'video_recognition' demo failed

### ISSUE THREAD

**Issue by blue-q** [open-mmlab/mmdeploy#1584]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I want to use video_recognition and slowfast to reason the video. First of all, I used script1 to generate the engine model. The error message is as shown in ERROR1, but the engine model can be generated normally in this process. Then execute script2 using video_recognition generated by natically compiled mmdeploy. In the process I modify video_recognition.cpp( int clip_len = 32;int frame_interval = 2; int num_clips = 1;) After executing script2, the error message is ERROR2. Since I can't read the video, then I try to read the picture and execute script3 with ERROR3.

### Reproduction

script1：python ./tools/deploy.py /home/dell/qiuzx/mmdeploy/configs/mmaction/video-recognition/video-recognition_3d_tensorrt_static-256x256.py /home/dell/qiuzx/mmaction2/configs/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb.py /home/dell/qiuzx/mmaction2/checkpoints/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb_20200826-f85b90c5.pth  /home/dell/qiuzx/mmaction2/demo/demo1.mp4 --work-dir /home/dell/qiuzx/mmdeploy/enginemodel/slowfast_video/ --dump-info --device cuda:0

script2：./video_recognition cuda /home/dell/qiuzx/mmdeploy/enginemodel/slowfast_video/ /home/dell/qiuzx/mmaction2/demo/demo1.mp4 

I just modify video_recognition.cpp as follows：
  int clip_len = 32;
  int frame_interval = 2;
  int num_clips = 1;

script3：./video_recognition3d cuda /home/dell/qiuzx/mmdeploy/enginemodel/slowfast_video/ /home/dell/qiuzx/mmaction2/demo/test1.png 

### Environment

```Shell
2022-12-28 10:32:23,272 - mmdeploy - INFO - 

2022-12-28 10:32:23,272 - mmdeploy - INFO - **********Environmental information**********
2022-12-28 10:32:24,531 - mmdeploy - INFO - sys.platform: linux
2022-12-28 10:32:24,531 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
2022-12-28 10:32:24,531 - mmdeploy - INFO - CUDA available: True
2022-12-28 10:32:24,531 - mmdeploy - INFO - GPU 0,1: NVIDIA GeForce RTX 2080 Ti
2022-12-28 10:32:24,531 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2022-12-28 10:32:24,531 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.89
2022-12-28 10:32:24,531 - mmdeploy - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
2022-12-28 10:32:24,531 - mmdeploy - INFO - PyTorch: 1.8.0
2022-12-28 10:32:24,531 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

2022-12-28 10:32:24,531 - mmdeploy - INFO - TorchVision: 0.9.0
2022-12-28 10:32:24,531 - mmdeploy - INFO - OpenCV: 4.6.0
2022-12-28 10:32:24,531 - mmdeploy - INFO - MMCV: 1.3.18
2022-12-28 10:32:24,531 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2022-12-28 10:32:24,531 - mmdeploy - INFO - MMCV CUDA Compiler: 10.2
2022-12-28 10:32:24,531 - mmdeploy - INFO - MMDeploy: 0.11.0+85b7b96
2022-12-28 10:32:24,532 - mmdeploy - INFO - 

2022-12-28 10:32:24,532 - mmdeploy - INFO - **********Backend information**********
2022-12-28 10:32:24,584 - mmdeploy - INFO - tensorrt:   7.2.3.4
2022-12-28 10:32:24,584 - mmdeploy - INFO - tensorrt custom ops:        Available
2022-12-28 10:32:24,611 - mmdeploy - INFO - ONNXRuntime:        1.8.1
2022-12-28 10:32:24,611 - mmdeploy - INFO - ONNXRuntime-gpu:    None
2022-12-28 10:32:24,611 - mmdeploy - INFO - ONNXRuntime custom ops:     NotAvailable
2022-12-28 10:32:24,612 - mmdeploy - INFO - pplnn:      None
2022-12-28 10:32:24,635 - mmdeploy - INFO - ncnn:       1.0.20221216
2022-12-28 10:32:24,635 - mmdeploy - INFO - ncnn custom ops:    NotAvailable
2022-12-28 10:32:24,636 - mmdeploy - INFO - snpe:       None
2022-12-28 10:32:24,637 - mmdeploy - INFO - openvino:   None
2022-12-28 10:32:24,638 - mmdeploy - INFO - torchscript:        1.8.0
2022-12-28 10:32:24,638 - mmdeploy - INFO - torchscript custom ops:     NotAvailable
2022-12-28 10:32:24,666 - mmdeploy - INFO - rknn-toolkit:       None
2022-12-28 10:32:24,666 - mmdeploy - INFO - rknn2-toolkit:      None
2022-12-28 10:32:24,667 - mmdeploy - INFO - ascend:     None
2022-12-28 10:32:24,667 - mmdeploy - INFO - coreml:     None
2022-12-28 10:32:24,668 - mmdeploy - INFO - tvm:        None
2022-12-28 10:32:24,668 - mmdeploy - INFO - 

2022-12-28 10:32:24,668 - mmdeploy - INFO - **********Codebase information**********
2022-12-28 10:32:24,670 - mmdeploy - INFO - mmdet:      2.25.0
2022-12-28 10:32:24,670 - mmdeploy - INFO - mmseg:      None
2022-12-28 10:32:24,670 - mmdeploy - INFO - mmcls:      None
2022-12-28 10:32:24,670 - mmdeploy - INFO - mmocr:      None
2022-12-28 10:32:24,670 - mmdeploy - INFO - mmedit:     None
2022-12-28 10:32:24,670 - mmdeploy - INFO - mmdet3d:    None
2022-12-28 10:32:24,670 - mmdeploy - INFO - mmpose:     0.28.0
2022-12-28 10:32:24,670 - mmdeploy - INFO - mmrotate:   None
2022-12-28 10:32:24,670 - mmdeploy - INFO - mmaction:   0.24.1
```

### Error traceback

```Shell
Error1：2022-12-28 10:20:13,743 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
load checkpoint from local path: /home/dell/qiuzx/mmaction2/checkpoints/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb_20200826-f85b90c5.pth
2022-12-28 10:20:38,110 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-12-28 10:20:38,111 - mmdeploy - INFO - Export PyTorch model to ONNX: /home/dell/qiuzx/mmdeploy/enginemodel/slowfast_video/end2end.onnx.
2022-12-28 10:20:38,177 - mmdeploy - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
2022-12-28 10:20:38,178 - mmdeploy - WARNING - Can not find torch.nn.functional._scaled_dot_product_attention, function rewrite will not be applied
2022-12-28 10:20:38,179 - mmdeploy - WARNING - Can not find torch._C._jit_pass_onnx_deduplicate_initializers, function rewrite will not be applied
/home/dell/miniconda3/envs/mma2/lib/python3.8/site-packages/torch/nn/functional.py:3499: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn(
2022-12-28 10:20:44,677 - mmdeploy - INFO - Execute onnx optimize passes.
2022-12-28 10:20:45,483 - mmdeploy - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
2022-12-28 10:20:47,287 - mmdeploy - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in subprocess
2022-12-28 10:20:47,319 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /home/dell/qiuzx/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[TensorRT] INFO: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[TensorRT] INFO: Detected 1 inputs and 1 output network tensors.
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
2022-12-28 10:20:59,452 - mmdeploy - INFO - Finish pipeline mmdeploy.apis.utils.utils.to_backend
2022-12-28 10:21:00,183 - mmdeploy - INFO - visualize tensorrt model start.
2022-12-28 10:21:07,245 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /home/dell/qiuzx/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
2022-12-28:10:21:07 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /home/dell/qiuzx/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
2022-12-28:10:21:07 - root - ERROR - TorchAllocator: No constructor defined!
Traceback (most recent call last):
  File "/home/dell/qiuzx/mmdeploy/mmdeploy/utils/utils.py", line 41, in target_wrapper
    result = target(*args, **kwargs)
  File "/home/dell/qiuzx/mmdeploy/mmdeploy/apis/visualize.py", line 66, in visualize_model
    model = task_processor.init_backend_model(model, **kwargs)
  File "/home/dell/qiuzx/mmdeploy/mmdeploy/codebase/mmaction/deploy/video_recognition.py", line 69, in init_backend_model
    model = build_video_recognition_model(
  File "/home/dell/qiuzx/mmdeploy/mmdeploy/codebase/mmaction/deploy/video_recognition_model.py", line 181, in build_video_recognition_model
    backend_video_recognizer = __BACKEND_MODEL.build(
  File "/home/dell/miniconda3/envs/mma2/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/dell/qiuzx/mmdeploy/mmdeploy/codebase/mmaction/deploy/video_recognition_model.py", line 15, in __build_backend_model
    return registry.module_dict[cls_name](*args, **kwargs)
  File "/home/dell/qiuzx/mmdeploy/mmdeploy/codebase/mmaction/deploy/video_recognition_model.py", line 45, in __init__
    self._init_wrapper(
  File "/home/dell/qiuzx/mmdeploy/mmdeploy/codebase/mmaction/deploy/video_recognition_model.py", line 53, in _init_wrapper
    self.wrapper = BaseBackendModel._build_wrapper(
  File "/home/dell/qiuzx/mmdeploy/mmdeploy/codebase/base/backend_model.py", line 63, in _build_wrapper
    return backend_mgr.build_wrapper(backend_files, device, input_names,
  File "/home/dell/qiuzx/mmdeploy/mmdeploy/backend/tensorrt/backend_manager.py", line 34, in build_wrapper
    return TRTWrapper(engine=backend_files[0], output_names=output_names)
  File "/home/dell/qiuzx/mmdeploy/mmdeploy/backend/tensorrt/wrapper.py", line 85, in __init__
    self.allocator = TorchAllocator(device_id)
  File "/home/dell/qiuzx/mmdeploy/mmdeploy/backend/tensorrt/torch_allocator.py", line 12, in __init__
    super().__init__()
TypeError: TorchAllocator: No constructor defined!
Exception ignored in: <function TorchAllocator.__del__ at 0x7fab92b545e0>
Traceback (most recent call last):
  File "/home/dell/qiuzx/mmdeploy/mmdeploy/backend/tensorrt/torch_allocator.py", line 19, in __del__
    mems = self.mems.copy()
AttributeError: 'TorchAllocator' object has no attribute 'mems'
2022-12-28 10:21:07,475 - mmdeploy - ERROR - visualize tensorrt model failed.


ERROR2：failed to load video: /home/dell/qiuzx/mmaction2/demo/demo1.mp4


ERROR3:num_frames 1
[2022-12-28 10:23:25.413] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/home/dell/qiuzx/mmdeploy/enginemodel/slowfast_video/"
[2022-12-28 10:23:25.540] [mmdeploy] [info] [inference.cpp:44] {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "pipeline": {
    "input": [
      "img"
    ],
    "output": [
      "post_output"
    ],
    "tasks": [
      {
        "input": [
          "img"
        ],
        "module": "Transform",
        "name": "Preprocess",
        "output": [
          "prep_output"
        ],
        "transforms": [
          {
            "transforms": [
              {
                "type": "LoadImageFromFile"
              },
              {
                "size": [
                  256,
                  -1
                ],
                "type": "Resize"
              },
              {
                "mean": [
                  123.675,
                  116.28,
                  103.53
                ],
                "std": [
                  58.395,
                  57.12,
                  57.375
                ],
                "to_bgr": false,
                "to_rgb": true,
                "type": "Normalize"
              },
              {
                "crop_size": 256,
                "type": "ThreeCrop"
              }
            ],
            "type": "Lift"
          },
          {
            "input_format": "NCTHW",
            "type": "FormatShape"
          },
          {
            "keys": [
              "img"
            ],
            "meta_keys": [
              "flip",
              "img_shape",
              "filename",
              "ori_filename",
              "pad_shape",
              "flip_direction",
              "scale_factor",
              "img_norm_cfg",
              "valid_ratio",
              "ori_shape"
            ],
            "type": "Collect"
          }
        ],
        "type": "Task"
      },
      {
        "input": [
          "prep_output"
        ],
        "input_map": {
          "img": "input"
        },
        "is_batched": false,
        "module": "Net",
        "name": "resnet3dslowfast",
        "output": [
          "infer_output"
        ],
        "output_map": {},
        "type": "Task"
      },
      {
        "component": "BaseHead",
        "input": [
          "infer_output"
        ],
        "module": "mmaction",
        "name": "postprocess",
        "output": [
          "post_output"
        ],
        "params": {
          "num_classes": 400,
          "topk": 1
        },
        "type": "Task"
      }
    ]
  }
}
[2022-12-28 10:23:26.888] [mmdeploy] [warning] [trt_net.cpp:24] TRTNet: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[2022-12-28 10:23:27.074] [mmdeploy] [warning] [trt_net.cpp:24] TRTNet: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[2022-12-28 10:23:27.215] [mmdeploy] [info] [inference.cpp:56] ["img"] <- ["video"]
[2022-12-28 10:23:27.215] [mmdeploy] [info] [inference.cpp:67] ["post_output"] -> ["label"]
[2022-12-28 10:23:27.257] [mmdeploy] [error] [trt_net.cpp:28] TRTNet: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]
terminate called after throwing an instance of 'system_error2::status_error<mmdeploy::StatusDomain>'
  what():  unknown (6) @ /home/dell/qiuzx/mmdeploy/csrc/mmdeploy/net/trt/trt_net.cpp:173
已放弃 (核心已转储)
```

**Comment by irexyc** [comment]
When convert the model, it read `test_pipeline ` to make the model input, the default value of num_clips is 10 according to the [config](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb.py#L54), so,  the video clip config should be:
```
int clip_len = 32;
int frame_interval = 2;
int num_clips = 1;
```

**Comment by blue-q** [comment]
I modified video_recognition.cpp as follows：
int clip_len = 32;
int frame_interval = 2;
int num_clips = 1;

executed script2：./video_recognition cuda /home/dell/qiuzx/mmdeploy/enginemodel/slowfast_video/ /home/dell/qiuzx/mmaction2/demo/demo1.mp4

ERROR2：failed to load video: /home/dell/qiuzx/mmaction2/demo/demo1.mp4

is this the problem of opencv？

i installed opencv with script "sudo apt-get install libopencv-dev" in Ubuntu18.04

**Comment by irexyc** [comment]
My mistake, the num_clips should be same with config when convert the model, so it should be 10.

**Comment by blue-q** [comment]
Thanks，It's running successfully.

**Comment by irexyc** [comment]
To read video file, you should build opencv from source.

Make sure the ffmpeg is YES when configure the project.
```
--   Video I/O:
--     DC1394:                      NO
--     FFMPEG:                      YES
--       avcodec:                   YES (58.54.100)
--       avformat:                  YES (58.29.100)
--       avutil:                    YES (56.31.100)
--       swscale:                   YES (5.5.100)
--       avresample:                NO
--     GStreamer:                   NO
--     v4l/v4l2:                    YES (linux/videodev2.h)
```
