### ISSUE TITLE
将mmdetection中tood的.pth导出为.onnx时报错TypeError: i_(): incompatible function arguments. The following argument types are supported:     1. (self: torch._C.Node, arg0: str, arg1: int) -> torch._C.Node

### ISSUE THREAD

**Issue by VJoer** [open-mmlab/mmdeploy#161]
我之前使用过mmdeploy将mmdetection中yolox sdd retinanet等多个检测模型导出为onnx格式都没有问题，且测试正常，今天我将训练的mmdetection中tood的模型导出为onnx时报错

python tools/deploy.py configs/mmdet/detection/detection_onnxruntime_static.py /home/jiangxiaowei/mmdetection/configs/tood/tood_r50_fpn_1x_coco.py /home/jiangxiaowei/mmdetection/work_dirs/tood_r50_fpn_1x_coco/epoch_24.pth images/1183.jpg --work-dir work_dir/tood_16_640 --device cuda:0

Traceback (most recent call last):
  File "/home/jiangxiaowei/MMDeploy/mmdeploy/utils/utils.py", line 36, in target_wrapper
    result = target(*args, **kwargs)
  File "/home/jiangxiaowei/MMDeploy/mmdeploy/apis/pytorch2onnx.py", line 92, in torch2onnx
    torch2onnx_impl(
  File "/home/jiangxiaowei/MMDeploy/mmdeploy/apis/pytorch2onnx.py", line 42, in torch2onnx_impl
    torch.onnx.export(
  File "/home/jiangxiaowei/anaconda3/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/jiangxiaowei/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/jiangxiaowei/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/jiangxiaowei/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 463, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/jiangxiaowei/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/jiangxiaowei/anaconda3/lib/python3.8/site-packages/torch/onnx/__init__.py", line 318, in _run_symbolic_method
    return utils._run_symbolic_method(*args, **kwargs)
  File "/home/jiangxiaowei/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 779, in _run_symbolic_method
    return symbolic_fn(g, *args)
  File "/home/jiangxiaowei/anaconda3/lib/python3.8/site-packages/mmcv/ops/deform_conv.py", line 36, in symbolic
    return g.op(
  File "/home/jiangxiaowei/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 885, in _graph_op
    n = g.insertNode(_newNode(g, opname, outputs, *args, **kwargs))
  File "/home/jiangxiaowei/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 838, in _newNode
    _add_attribute(n, k, v, aten=aten)
  File "/home/jiangxiaowei/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 816, in _add_attribute
    return getattr(node, kind + "_")(name, value)
TypeError: i_(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.Node, arg0: str, arg1: int) -> torch._C.Node

Invoked with: %2117 : Tensor = mmcv::MMCVDeformConv2d[bias=0](%2077, %2100, %2116)
, 'deform_groups', 2107 defined in (%2107 : Long(device=cpu) = onnx::Gather[axis=0](%2104, %2106) # /home/jiangxiaowei/anaconda3/lib/python3.8/site-packages/mmdet/models/dense_heads/tood_head.py:282:0
) (occurred when translating DeformConv2dFunction)
2022-02-16 12:19:03,509 - mmdeploy - ERROR - torch2onnx failed.

请问这个问题如何解决？谢谢

**Comment by grimoire** [comment]
tood is not supported for now. It is not hard to support it by adding some rewrite in [dense_head](https://github.com/open-mmlab/mmdeploy/tree/master/mmdeploy/codebase/mmdet/models/dense_heads). Please have a try.

**Comment by hhaAndroid** [comment]
@grimoire It includes the dcn module, is it supported too?

**Comment by grimoire** [comment]
> @grimoire It includes the dcn module, is it supported too?

https://github.com/open-mmlab/mmdeploy/pull/205 It would be supported in v0.4.0

**Comment by VJoer** [comment]
> #205 It would be supported in v0.4.0

Hi, I tried to torch to onnx in the latest mmdeploy failed,  

cmd: python tools/deploy.py configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py test/tood/tood_r50_fpn_1x_coco.py test/tood/best_bbox_mAP_50_epoch_11.pth deploy.jpg --work-dir /world/data test/tood/trt --device cuda:0

2022-04-06:12:12:40,root ERROR    [utils.py:43] 'int' object is not iterable (occurred when translating DeformConv2dFunction)
Traceback (most recent call last):
  File "/world/data-c9/train_envs/mmdeploy/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "/world/data-c9/train_envs/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 109, in torch2onnx
    torch2onnx_impl(
  File "/world/data-c9/train_envs/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 44, in torch2onnx_impl
    torch.onnx.export(
  File "/world/data-c9/train_envs/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/onnx/__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/world/data-c9/train_envs/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/world/data-c9/train_envs/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/onnx/utils.py", line 719, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/world/data-c9/train_envs/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/onnx/utils.py", line 503, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/world/data-c9/train_envs/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/onnx/utils.py", line 232, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/world/data-c9/train_envs/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/onnx/__init__.py", line 359, in _run_symbolic_method
    return utils._run_symbolic_method(*args, **kwargs)
  File "/world/data-c9/train_envs/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/onnx/utils.py", line 846, in _run_symbolic_method
    return symbolic_fn(g, *args)
  File "/world/data-c9/train_envs/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 360, in __call__
    return self.func(self, *args, **kwargs)
  File "/world/data-c9/train_envs/mmdeploy/mmdeploy/mmcv/ops/deform_conv.py", line 26, in deform_conv__default
    padding_i=[p for pair in zip(padding, padding) for p in pair],
TypeError: 'int' object is not iterable (occurred when translating DeformConv2dFunction)
2022-04-06 12:12:41,107 - mmdeploy - ERROR - torch2onnx failed.

**Comment by grimoire** [comment]
@VJoer #205 does support DCN, but tood has not been supported yet.

**Comment by lvhan028** [comment]
Close it because of no activity for a long time.
