### ISSUE TITLE
[Bug] Win10 Prebuild Package: "ValueError: cpu is invalid for the backend tensorrt"

### ISSUE THREAD

**Issue by Tender-hjd** [open-mmlab/mmdeploy#1634]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

When I use the Win10 prebuild package of MMDeploy for TensorRT following the offical docs,
I meet a raised Exception located in "mmdeploy/mmdeploy/apis/utils/utils.py" during executing this function:
```python
def check_backend_device(deploy_cfg: mmcv.Config, device: str):
    """Check if device is appropriate for the backend.

    Args:
        deploy_cfg (str | mmcv.Config): Deployment config file.
        device (str): A string specifying device type.
    """
    backend = get_backend(deploy_cfg).value
    device_id = parse_device_id(device)
    mismatch = dict(
        tensorrt=lambda id: id == -1,
        openvino=lambda id: id > -1,
    )
    if backend in mismatch and mismatch[backend](device_id):
        raise ValueError(f'{device} is invalid for the backend {backend}')
```
But When I remove the code raising this "ValueError", to my surprise, it unexpectedly works well.
The prebuild package exports torch model to onnx(IR) and then to TensorRT(engine) sucessfully!
I guess this function exists any logic error.

### Reproduction
```python
from mmdeploy.apis import torch2onnx
from mmdeploy.apis.tensorrt import onnx2tensorrt
from mmdeploy.backend.sdk.export_info import export2SDK
import os

img = 'mmclassification/demo/demo.JPEG'
work_dir = 'work_dir/trt/resnet'
save_file = 'end2end.onnx'
deploy_cfg = 'mmdeploy/configs/mmcls/classification_tensorrt_static-224x224.py'
model_cfg = 'mmclassification/configs/resnet/resnet18_8xb32_in1k.py'
model_checkpoint = 'resnet18_8xb32_in1k_20210831-fbbb1da6.pth'
device = 'cpu'

# 1. convert model to IR(onnx)
torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  model_checkpoint, device)

# 2. convert IR to tensorrt
onnx_model = os.path.join(work_dir, save_file)
save_file = 'end2end.engine'
model_id = 0
device = 'cuda'
onnx2tensorrt(work_dir, save_file, model_id, deploy_cfg, onnx_model, device)

# 3. extract pipeline info for sdk use (dump-info)
export2SDK(deploy_cfg, model_cfg, work_dir, pth=model_checkpoint, device=device)
```

### Environment

```Shell
D:\conda_envs\mmdeploy_tensorrt_prebuild\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
2023-01-10 22:27:37,570 - mmdeploy - INFO - 

2023-01-10 22:27:37,571 - mmdeploy - INFO - **********Environmental information**********
fatal: not a git repository (or any of the parent directories): .git
2023-01-10 22:27:44,492 - mmdeploy - INFO - sys.platform: win32
2023-01-10 22:27:44,492 - mmdeploy - INFO - Python: 3.8.15 (default, Nov 24 2022, 14:38:14) [MSC v.1916 64 bit (AMD64)]
2023-01-10 22:27:44,493 - mmdeploy - INFO - CUDA available: True
2023-01-10 22:27:44,493 - mmdeploy - INFO - GPU 0: NVIDIA GeForce GTX 1650
2023-01-10 22:27:44,493 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
2023-01-10 22:27:44,493 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.58
2023-01-10 22:27:44,493 - mmdeploy - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30146 版
2023-01-10 22:27:44,494 - mmdeploy - INFO - GCC: n/a
2023-01-10 22:27:44,494 - mmdeploy - INFO - PyTorch: 1.12.1+cu113
2023-01-10 22:27:44,494 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
2023-01-10 22:27:44,922 - mmdeploy - INFO -

2023-01-10 22:27:44,922 - mmdeploy - INFO - **********Codebase information**********2023-01-10 22:27:44,937 - mmdeploy - INFO - mmdet:      2.27.02023-01-10 22:27:44,937 - mmdeploy - INFO - mmseg:      None2023-01-10 22:27:44,937 - mmdeploy - INFO - mmcls:      0.25.02023-01-10 22:27:44,938 - mmdeploy - INFO - mmocr:      None2023-01-10 22:27:44,938 - mmdeploy - INFO - mmedit:     None
2023-01-10 22:27:44,938 - mmdeploy - INFO - mmdet3d:    None
2023-01-10 22:27:44,938 - mmdeploy - INFO - mmpose:     None
2023-01-10 22:27:44,938 - mmdeploy - INFO - mmrotate:   None
2023-01-10 22:27:44,939 - mmdeploy - INFO - mmaction:   None
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "d:\py-projects\tensorrt_sdk_deploy\playground.py", line 15, in <module>
    torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  File "D:\conda_envs\mmdeploy_tensorrt_prebuild\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap    
    return self.call_function(func_name_, *args, **kwargs)
  File "D:\conda_envs\mmdeploy_tensorrt_prebuild\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "D:\conda_envs\mmdeploy_tensorrt_prebuild\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "D:\conda_envs\mmdeploy_tensorrt_prebuild\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__ 
    ret = func(*args, **kwargs)
  File "D:\conda_envs\mmdeploy_tensorrt_prebuild\lib\site-packages\mmdeploy\apis\pytorch2onnx.py", line 62, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "D:\conda_envs\mmdeploy_tensorrt_prebuild\lib\site-packages\mmdeploy\apis\utils\utils.py", line 42, in build_task_processor
    check_backend_device(deploy_cfg=deploy_cfg, device=device)
  File "D:\conda_envs\mmdeploy_tensorrt_prebuild\lib\site-packages\mmdeploy\apis\utils\utils.py", line 27, in check_backend_device
    raise ValueError(f'{device} is invalid for the backend {backend}')
ValueError: cpu is invalid for the backend tensorrt
```

**Comment by irexyc** [comment]
When use `torch2onnx`, please use device = 'cuda' temporarily.  We will update related content soon.

**Comment by Tender-hjd** [comment]
Everything is OK, Thanks!
