### ISSUE TITLE
[Bug] Deploying FCOS3D missing cam_intrinsics.

### ISSUE THREAD

**Issue by thisistejaspandey** [open-mmlab/mmdeploy#1656]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Error when deploying FCOS3D to TensorRT backend.

    mmdet/lib/python3.8/site-packages/mmdeploy/codebase/mmdet3d/deploy/monocular_detection.py", line 126, in create_input
        dict(cam_intrinsic=img_info['cam_intrinsic']))
    UnboundLocalError: local variable 'img_info' referenced before assignment

Code expects img_info to contain cam_intrinsics.

    # camera points to image conversion
    if box_mode_3d == Box3DMode.CAM:
        data['img_info'].update(
            dict(cam_intrinsic=img_info['cam_intrinsic']))

img_info only contains filename.

    'img_info': {'filename': 'n008-2018-05-21-11-06-59-0400__CAM_FRONT__1526915244012465.jpg'}

### Reproduction

    /home/tp1056/gits/mmdeploy/tools/deploy.py \
    /media/raid/gits/mmdeploy/configs/mmdet3d/monocular-detection/monocular-detection_tensorrt_dynamic-320x320-1600x1600.py \
    /media/raid/gits/mmdetection3d/configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune.py \
    /media/raid/gits/mmdetection3d/models/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210717_095645-8d806dc2.pth \
    ~/datasets/nuscenes/samples/CAM_FRONT/n008-2018-05-21-11-06-59-0400__CAM_FRONT__1526915244012465.jpg \
    --work-dir /media/raid/gits/mmdeploy/exports \
    --device cuda:0 

### Environment

```Shell
2023-01-13 15:53:06,730 - mmdeploy - INFO -

2023-01-13 15:53:06,730 - mmdeploy - INFO - **********Environmental information**********
2023-01-13 15:53:06,936 - mmdeploy - INFO - sys.platform: linux
2023-01-13 15:53:06,936 - mmdeploy - INFO - Python: 3.8.15 (default, Nov 24 2022, 15:19:38) [GCC 11.2.0]
2023-01-13 15:53:06,936 - mmdeploy - INFO - CUDA available: True
2023-01-13 15:53:06,936 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3090
2023-01-13 15:53:06,936 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2023-01-13 15:53:06,936 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.124
2023-01-13 15:53:06,936 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2023-01-13 15:53:06,936 - mmdeploy - INFO - PyTorch: 1.13.1+cu116
2023-01-13 15:53:06,936 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.6  (built against CUDA 11.8)
    - Built with CuDNN 8.3.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

2023-01-13 15:53:06,936 - mmdeploy - INFO - TorchVision: 0.14.1+cu116
2023-01-13 15:53:06,936 - mmdeploy - INFO - OpenCV: 4.7.0
2023-01-13 15:53:06,936 - mmdeploy - INFO - MMCV: 1.7.0
2023-01-13 15:53:06,936 - mmdeploy - INFO - MMCV Compiler: GCC 9.3
2023-01-13 15:53:06,936 - mmdeploy - INFO - MMCV CUDA Compiler: 11.6
2023-01-13 15:53:06,937 - mmdeploy - INFO - MMDeploy: 0.12.0+968b4b0
2023-01-13 15:53:06,937 - mmdeploy - INFO -

2023-01-13 15:53:06,937 - mmdeploy - INFO - **********Backend information**********
2023-01-13 15:53:07,021 - mmdeploy - INFO - tensorrt:   8.5.2.2
2023-01-13 15:53:07,021 - mmdeploy - INFO - tensorrt custom ops:        Available
2023-01-13 15:53:07,021 - mmdeploy - INFO - ONNXRuntime:        None
2023-01-13 15:53:07,021 - mmdeploy - INFO - pplnn:      None
2023-01-13 15:53:07,022 - mmdeploy - INFO - ncnn:       None
2023-01-13 15:53:07,022 - mmdeploy - INFO - snpe:       None
2023-01-13 15:53:07,023 - mmdeploy - INFO - openvino:   None
2023-01-13 15:53:07,023 - mmdeploy - INFO - torchscript:        1.13.1+cu116
2023-01-13 15:53:07,024 - mmdeploy - INFO - torchscript custom ops:     NotAvailable
2023-01-13 15:53:07,043 - mmdeploy - INFO - rknn-toolkit:       None
2023-01-13 15:53:07,043 - mmdeploy - INFO - rknn2-toolkit:      None
2023-01-13 15:53:07,044 - mmdeploy - INFO - ascend:     None
2023-01-13 15:53:07,044 - mmdeploy - INFO - coreml:     None
2023-01-13 15:53:07,044 - mmdeploy - INFO - tvm:        None
2023-01-13 15:53:07,044 - mmdeploy - INFO -

2023-01-13 15:53:07,044 - mmdeploy - INFO - **********Codebase information**********
2023-01-13 15:53:07,045 - mmdeploy - INFO - mmdet:      2.27.0
2023-01-13 15:53:07,045 - mmdeploy - INFO - mmseg:      0.30.0
2023-01-13 15:53:07,045 - mmdeploy - INFO - mmcls:      0.25.0
2023-01-13 15:53:07,045 - mmdeploy - INFO - mmocr:      None
2023-01-13 15:53:07,045 - mmdeploy - INFO - mmedit:     None
2023-01-13 15:53:07,045 - mmdeploy - INFO - mmdet3d:    1.0.0rc6
2023-01-13 15:53:07,045 - mmdeploy - INFO - mmpose:     None
2023-01-13 15:53:07,045 - mmdeploy - INFO - mmrotate:   None
2023-01-13 15:53:07,045 - mmdeploy - INFO - mmaction:   None
```

### Error traceback

    cd /home/tp1056/gits/mmdeploy ; /usr/bin/env /home/tp1056/miniconda3/envs/mmdet/bin/python /home/tp1056/.vscode-server/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 46757 -- /home/tp1056/gits/mmdeploy/tools/deploy.py /media/raid/gits/mmdeploy/configs/mmdet3d/monocular-detection/monocular-detection_tensorrt_dynamic-320x320-1600x1600.py /media/raid/gits/mmdetection3d/configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune.py /media/raid/gits/mmdetection3d/models/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210717_095645-8d806dc2.pth ~/datasets/nuscenes/samples/CAM_FRONT/n008-2018-05-21-11-06-59-0400__CAM_FRONT__1526915244012465.jpg --work-dir /media/raid/gits/mmdeploy/exports --device cuda:0 
    /home/tp1056/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
      warnings.warn(
    /home/tp1056/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
      warnings.warn(
    /home/tp1056/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
      warnings.warn(
    2023-01-13 15:28:55,895 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
    load checkpoint from local path: /media/raid/gits/mmdetection3d/models/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210717_095645-8d806dc2.pth
    Process Process-2:
    Traceback (most recent call last):
      File "/home/tp1056/miniconda3/envs/mmdet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
        self.run()
      File "/home/tp1056/miniconda3/envs/mmdet/lib/python3.8/multiprocessing/process.py", line 108, in run
        self._target(*self._args, **self._kwargs)
      File "/home/tp1056/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
        ret = func(*args, **kwargs)
      File "/home/tp1056/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 65, in torch2onnx
        data, model_inputs = task_processor.create_input(img, input_shape)
      File "/home/tp1056/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmdeploy/codebase/mmdet3d/deploy/monocular_detection.py", line 126, in create_input
        dict(cam_intrinsic=img_info['cam_intrinsic']))
    UnboundLocalError: local variable 'img_info' referenced before assignment
    2023-01-13 15:30:44,615 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

**Comment by tpoisonooo** [comment]
`requirements/codebased.txt`  updated here https://github.com/open-mmlab/mmdeploy/blob/master/requirements/codebases.txt

mmdeploy 0.12.0 only support  mmdet3d 0.x.x

Please install mmdeploy v1.0.0rc1 to support mmdet3d 1.x.x

**Comment by tpoisonooo** [comment]
https://github.com/open-mmlab/mmdeploy/tree/v1.0.0rc1

**Comment by thisistejaspandey** [comment]
Thank you that fixed it!

**Comment by happyday-lkj** [comment]
> 

In mmdeploy v1.0.0rc1 , there is no configs about monocular-detection

**Comment by happyday-lkj** [comment]
> Thank you that fixed it!

how did you solve it? when I install mmdeploy v1.0.0rc1, there is no configs about monocular-detection, then I copy the config file, but when I run the code "python tools/deploy.py", I meet the error `KeyError: 'mmdet3d is not in the Codebases registry. Please check whether the value of `mmdet3d` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'`

**Comment by Superyanzhuang** [comment]
I encountered this problem when converting FCOS3D to onnx, how to solve it?
![image](https://user-images.githubusercontent.com/88640736/223351989-c2560dfe-d6e3-47b1-a756-efe94e89dc9b.png)
Environment：
![image](https://user-images.githubusercontent.com/88640736/223352372-27365183-fc34-4451-b53a-f99849769c50.png)
