### ISSUE TITLE
[Bug] KeyError: 'YOLODetector is not in the models registry'

### ISSUE THREAD

**Issue by SuFIND** [open-mmlab/mmdeploy#1671]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

我正在使用mmyolo，训练一个自定义数据的yolov5s模型，完成训练后依照[该文档](https://github.com/open-mmlab/mmyolo/blob/main/docs/zh_cn/deploy/yolov5_deployment.md)来到mmdeploy项目尝试部署时遇到了该报错

## exec
```shell
$ cd $mmdeploy_path
$ python tools/deploy.py 
configs/det_custom/detection_tensorrt_static-576x1024.py \
../mmyolo/work_dirs/yolov5_s-v61_syncbn_fast_1xb4-300e/yolov5_s-v61_syncbn_fast_1xb4-300e.py \
../mmyolo/work_dirs/yolov5_s-v61_syncbn_fast_1xb4-300e/best_coco/bbox_mAP_epoch_294.pth \ ../mmyolo/data/after_split/triangle_1/images/1674196031282185800.jpg \
--work-dir work_dir \
--show \
--device cuda:0
```

## detection_tensorrt_static-576x1024.py
```python
_base_ = ['../mmdet/_base_/base_static.py', '../_base_/backends/tensorrt.py']

onnx_config = dict(input_shape=(1024, 574))

backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 574, 1024],
                    opt_shape=[1, 3, 574, 1024],
                    max_shape=[1, 3, 2560, 1440])))
    ])
use_efficientnms = False
```

## yolov5_s-v61_syncbn_fast_1xb4-300e.py
```python
default_scope = 'mmyolo'
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=1),
    param_scheduler=dict(
        type='YOLOv5ParamSchedulerHook',
        scheduler_type='linear',
        lr_factor=0.01,
        max_epochs=300),
    checkpoint=dict(
        type='CheckpointHook', interval=2, save_best='auto', max_keep_ckpts=3),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='mmdet.DetVisualizationHook'))
env_cfg = dict(
    cudnn_benchmark=True,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='mmdet.DetLocalVisualizer',
    vis_backends=[dict(type='LocalVisBackend')],
    name='visualizer')
log_processor = dict(type='LogProcessor', window_size=50, by_epoch=True)
log_level = 'INFO'
load_from = None
resume = False
file_client_args = dict(backend='disk')
data_root = 'data/after_split/triangle_1/'
dataset_type = 'YOLOv5CocoDataset'
num_classes = 9
img_scale = (1024, 576)
deepen_factor = 0.33
widen_factor = 0.5
max_epochs = 300
save_epoch_intervals = 2
train_batch_size_per_gpu = 4
train_num_workers = 2
val_batch_size_per_gpu = 1
val_num_workers = 2
persistent_workers = True
base_lr = 0.04
batch_shapes_cfg = dict(
    type='BatchShapePolicy',
    batch_size=1,
    img_size=img_scale[0],
    size_divisor=32,
    extra_pad_ratio=0.5)
anchors = [[(11, 11), (20, 7), (71, 20)], [(94, 31), (71, 50), (100, 70)],
           [(118, 128), (113, 198), (238, 189)]]
strides = [8, 16, 32]
num_det_layers = 3
model = dict(
    type='YOLODetector',
    data_preprocessor=dict(
        type='YOLOv5DetDataPreprocessor',
        mean=[0.0, 0.0, 0.0],
        std=[255.0, 255.0, 255.0],
        bgr_to_rgb=True),
    backbone=dict(
        type='YOLOv5CSPDarknet',
        deepen_factor=0.33,
        widen_factor=0.5,
        norm_cfg=dict(type='BN', momentum=0.03, eps=0.001),
        act_cfg=dict(type='SiLU', inplace=True)),
    neck=dict(
        type='YOLOv5PAFPN',
        deepen_factor=0.33,
        widen_factor=0.5,
        in_channels=[256, 512, 1024],
        out_channels=[256, 512, 1024],
        num_csp_blocks=3,
        norm_cfg=dict(type='BN', momentum=0.03, eps=0.001),
        act_cfg=dict(type='SiLU', inplace=True)),
    bbox_head=dict(
        type='YOLOv5Head',
        head_module=dict(
            type='YOLOv5HeadModule',
            num_classes=9,
            in_channels=[256, 512, 1024],
            widen_factor=0.5,
            featmap_strides=[8, 16, 32],
            num_base_priors=3),
        prior_generator=dict(
            type='mmdet.YOLOAnchorGenerator',
            base_sizes=[[(11, 11), (20, 7), (71, 20)],
                        [(94, 31), (71, 50), (100, 70)],
                        [(118, 128), (113, 198), (238, 189)]],
            strides=[8, 16, 32]),
        loss_cls=dict(
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=True,
            reduction='mean',
            loss_weight=0.05625),
        loss_bbox=dict(
            type='IoULoss',
            iou_mode='ciou',
            bbox_format='xywh',
            eps=1e-07,
            reduction='mean',
            loss_weight=0.05,
            return_iou=True),
        loss_obj=dict(
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=True,
            reduction='mean',
            loss_weight=2.5600000000000005),
        prior_match_thr=4.0,
        obj_level_weights=[4.0, 1.0, 0.4]),
    test_cfg=dict(
        multi_label=True,
        nms_pre=30000,
        score_thr=0.001,
        nms=dict(type='nms', iou_threshold=0.65),
        max_per_img=300))
albu_train_transforms = [
    dict(type='Blur', p=0.01),
    dict(type='MedianBlur', p=0.01),
    dict(type='ToGray', p=0.01),
    dict(type='CLAHE', p=0.01)
]
pre_transform = [
    dict(type='LoadImageFromFile', file_client_args=dict(backend='disk')),
    dict(type='LoadAnnotations', with_bbox=True)
]
train_pipeline = [
    dict(type='LoadImageFromFile', file_client_args=dict(backend='disk')),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='Mosaic',
        img_scale=(1024, 576),
        pad_val=114.0,
        pre_transform=[
            dict(
                type='LoadImageFromFile',
                file_client_args=dict(backend='disk')),
            dict(type='LoadAnnotations', with_bbox=True)
        ]),
    dict(
        type='YOLOv5RandomAffine',
        max_rotate_degree=0.0,
        max_shear_degree=0.0,
        scaling_ratio_range=(0.5, 1.5),
        border=(-512, -288),
        border_val=(114, 114, 114)),
    dict(
        type='mmdet.Albu',
        transforms=[
            dict(type='Blur', p=0.01),
            dict(type='MedianBlur', p=0.01),
            dict(type='ToGray', p=0.01),
            dict(type='CLAHE', p=0.01)
        ],
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_bboxes_labels', 'gt_ignore_flags']),
        keymap=dict(img='image', gt_bboxes='bboxes')),
    dict(type='YOLOv5HSVRandomAug'),
    dict(type='mmdet.RandomFlip', prob=0.5),
    dict(
        type='mmdet.PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'flip',
                   'flip_direction'))
]
train_dataloader = dict(
    batch_size=4,
    num_workers=2,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='YOLOv5CocoDataset',
        data_root='data/after_split/triangle_1/',
        ann_file='annotations/train.json',
        data_prefix=dict(img='images/'),
        filter_cfg=dict(filter_empty_gt=False, min_size=32),
        pipeline=[
            dict(
                type='LoadImageFromFile',
                file_client_args=dict(backend='disk')),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                type='Mosaic',
                img_scale=(640, 640),
                pad_val=114.0,
                pre_transform=[
                    dict(
                        type='LoadImageFromFile',
                        file_client_args=dict(backend='disk')),
                    dict(type='LoadAnnotations', with_bbox=True)
                ]),
            dict(
                type='YOLOv5RandomAffine',
                max_rotate_degree=0.0,
                max_shear_degree=0.0,
                scaling_ratio_range=(0.5, 1.5),
                border=(-320, -320),
                border_val=(114, 114, 114)),
            dict(
                type='mmdet.Albu',
                transforms=[
                    dict(type='Blur', p=0.01),
                    dict(type='MedianBlur', p=0.01),
                    dict(type='ToGray', p=0.01),
                    dict(type='CLAHE', p=0.01)
                ],
                bbox_params=dict(
                    type='BboxParams',
                    format='pascal_voc',
                    label_fields=['gt_bboxes_labels', 'gt_ignore_flags']),
                keymap=dict(img='image', gt_bboxes='bboxes')),
            dict(type='YOLOv5HSVRandomAug'),
            dict(type='mmdet.RandomFlip', prob=0.5),
            dict(
                type='mmdet.PackDetInputs',
                meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                           'flip', 'flip_direction'))
        ],
        metainfo=dict(
            classes=('FindNPCUI', 'CallPlaceItem', 'MyFavoriteLocation',
                     'BagUI', 'CallVolume', 'TriangleMarker', 'BossMagram',
                     'BossKhalk', 'TaskOver'),
            palette=[(220, 20, 60), (202, 75, 211), (44, 209, 148),
                     (210, 126, 79), (61, 161, 214), (197, 25, 2),
                     (189, 175, 82), (221, 218, 33), (73, 234, 225),
                     (28, 146, 30)])),
    collate_fn=dict(type='yolov5_collate'))
test_pipeline = [
    dict(type='LoadImageFromFile', file_client_args=dict(backend='disk')),
    dict(type='YOLOv5KeepRatioResize', scale=(1024, 576)),
    dict(
        type='LetterResize',
        scale=(1024, 576),
        allow_scale_up=False,
        pad_val=dict(img=114)),
    dict(type='LoadAnnotations', with_bbox=True, _scope_='mmdet'),
    dict(
        type='mmdet.PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                   'scale_factor', 'pad_param'))
]
val_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    pin_memory=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='YOLOv5CocoDataset',
        data_root='data/after_split/triangle_1/',
        test_mode=True,
        data_prefix=dict(img='images/'),
        ann_file='annotations/trainval.json',
        pipeline=[
            dict(
                type='LoadImageFromFile',
                file_client_args=dict(backend='disk')),
            dict(type='YOLOv5KeepRatioResize', scale=(640, 640)),
            dict(
                type='LetterResize',
                scale=(640, 640),
                allow_scale_up=False,
                pad_val=dict(img=114)),
            dict(type='LoadAnnotations', with_bbox=True, _scope_='mmdet'),
            dict(
                type='mmdet.PackDetInputs',
                meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                           'scale_factor', 'pad_param'))
        ],
        batch_shapes_cfg=dict(
            type='BatchShapePolicy',
            batch_size=1,
            img_size=640,
            size_divisor=32,
            extra_pad_ratio=0.5),
        metainfo=dict(
            classes=('FindNPCUI', 'CallPlaceItem', 'MyFavoriteLocation',
                     'BagUI', 'CallVolume', 'TriangleMarker', 'BossMagram',
                     'BossKhalk', 'TaskOver'),
            palette=[(220, 20, 60), (202, 75, 211), (44, 209, 148),
                     (210, 126, 79), (61, 161, 214), (197, 25, 2),
                     (189, 175, 82), (221, 218, 33), (73, 234, 225),
                     (28, 146, 30)])))
test_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    pin_memory=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='YOLOv5CocoDataset',
        data_root='data/after_split/triangle_1/',
        test_mode=True,
        data_prefix=dict(img='images/'),
        ann_file='annotations/trainval.json',
        pipeline=[
            dict(
                type='LoadImageFromFile',
                file_client_args=dict(backend='disk')),
            dict(type='YOLOv5KeepRatioResize', scale=(640, 640)),
            dict(
                type='LetterResize',
                scale=(640, 640),
                allow_scale_up=False,
                pad_val=dict(img=114)),
            dict(type='LoadAnnotations', with_bbox=True, _scope_='mmdet'),
            dict(
                type='mmdet.PackDetInputs',
                meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                           'scale_factor', 'pad_param'))
        ],
        batch_shapes_cfg=dict(
            type='BatchShapePolicy',
            batch_size=1,
            img_size=640,
            size_divisor=32,
            extra_pad_ratio=0.5),
        metainfo=dict(
            classes=('FindNPCUI', 'CallPlaceItem', 'MyFavoriteLocation',
                     'BagUI', 'CallVolume', 'TriangleMarker', 'BossMagram',
                     'BossKhalk', 'TaskOver'),
            palette=[(220, 20, 60), (202, 75, 211), (44, 209, 148),
                     (210, 126, 79), (61, 161, 214), (197, 25, 2),
                     (189, 175, 82), (221, 218, 33), (73, 234, 225),
                     (28, 146, 30)])))
param_scheduler = None
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(
        type='SGD',
        lr=0.04,
        momentum=0.937,
        weight_decay=0.0005,
        nesterov=True,
        batch_size_per_gpu=16),
    constructor='YOLOv5OptimizerConstructor')
custom_hooks = [
    dict(
        type='EMAHook',
        ema_type='ExpMomentumEMA',
        momentum=0.0001,
        update_buffers=True,
        strict_load=False,
        priority=49)
]
val_evaluator = dict(
    type='mmdet.CocoMetric',
    proposal_nums=(100, 1, 10),
    ann_file='data/after_split/triangle_1/annotations/trainval.json',
    metric='bbox')
test_evaluator = dict(
    type='mmdet.CocoMetric',
    proposal_nums=(100, 1, 10),
    ann_file='data/after_split/triangle_1/annotations/trainval.json',
    metric='bbox')
train_cfg = dict(
    type='EpochBasedTrainLoop', max_epochs=300, val_interval=2, val_begin=20)
val_cfg = dict(type='ValLoop')
# test_cfg = dict(type='TestLoop')
class_name = ('FindNPCUI', 'CallPlaceItem', 'MyFavoriteLocation', 'BagUI',
              'CallVolume', 'TriangleMarker', 'BossMagram', 'BossKhalk',
              'TaskOver')
metainfo = dict(
    classes=('FindNPCUI', 'CallPlaceItem', 'MyFavoriteLocation', 'BagUI',
             'CallVolume', 'TriangleMarker', 'BossMagram', 'BossKhalk',
             'TaskOver'),
    palette=[(220, 20, 60), (202, 75, 211), (44, 209, 148), (210, 126, 79),
             (61, 161, 214), (197, 25, 2), (189, 175, 82), (221, 218, 33),
             (73, 234, 225), (28, 146, 30)])
launcher = 'none'
work_dir = './work_dirs\\yolov5_s-v61_syncbn_fast_1xb4-300e'

```

### Environment

```Shell
2023-01-24 00:52:36,084 - mmdeploy - INFO - **********Environmental information**********
2023-01-24 00:52:39,106 - mmdeploy - INFO - sys.platform: win32
2023-01-24 00:52:39,106 - mmdeploy - INFO - Python: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:41:22) [MSC v.1929 64 bit (AMD64)]
2023-01-24 00:52:39,106 - mmdeploy - INFO - CUDA available: True
2023-01-24 00:52:39,106 - mmdeploy - INFO - GPU 0: NVIDIA GeForce GTX 1060 6GB
2023-01-24 00:52:39,106 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
2023-01-24 00:52:39,106 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.8, V11.8.89
2023-01-24 00:52:39,106 - mmdeploy - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.34.31937 版
2023-01-24 00:52:39,106 - mmdeploy - INFO - GCC: n/a
2023-01-24 00:52:39,106 - mmdeploy - INFO - PyTorch: 1.13.1
2023-01-24 00:52:39,106 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

2023-01-24 00:52:39,106 - mmdeploy - INFO - TorchVision: 0.14.1
2023-01-24 00:52:39,106 - mmdeploy - INFO - OpenCV: 4.7.0
2023-01-24 00:52:39,106 - mmdeploy - INFO - MMCV: 1.7.1
2023-01-24 00:52:39,106 - mmdeploy - INFO - MMCV Compiler: MSVC 192829924
2023-01-24 00:52:39,106 - mmdeploy - INFO - MMCV CUDA Compiler: 11.7
2023-01-24 00:52:39,106 - mmdeploy - INFO - MMDeploy: 0.12.0+8a050f1
2023-01-24 00:52:39,106 - mmdeploy - INFO - 

2023-01-24 00:52:39,106 - mmdeploy - INFO - **********Backend information**********
2023-01-24 00:52:39,188 - mmdeploy - INFO - tensorrt:	8.5.2.2
2023-01-24 00:52:39,189 - mmdeploy - INFO - tensorrt custom ops:	NotAvailable
2023-01-24 00:52:39,264 - mmdeploy - INFO - ONNXRuntime:	1.8.1
2023-01-24 00:52:39,264 - mmdeploy - INFO - ONNXRuntime-gpu:	None
2023-01-24 00:52:39,264 - mmdeploy - INFO - ONNXRuntime custom ops:	NotAvailable
2023-01-24 00:52:39,272 - mmdeploy - INFO - pplnn:	None
2023-01-24 00:52:39,330 - mmdeploy - INFO - ncnn:	None
2023-01-24 00:52:39,398 - mmdeploy - INFO - snpe:	None
2023-01-24 00:52:39,408 - mmdeploy - INFO - openvino:	None
2023-01-24 00:52:39,422 - mmdeploy - INFO - torchscript:	1.13.1
2023-01-24 00:52:39,422 - mmdeploy - INFO - torchscript custom ops:	NotAvailable
2023-01-24 00:52:39,497 - mmdeploy - INFO - rknn-toolkit:	None
2023-01-24 00:52:39,497 - mmdeploy - INFO - rknn2-toolkit:	None
2023-01-24 00:52:39,515 - mmdeploy - INFO - ascend:	None
2023-01-24 00:52:39,524 - mmdeploy - INFO - coreml:	None
2023-01-24 00:52:39,547 - mmdeploy - INFO - tvm:	None
2023-01-24 00:52:39,547 - mmdeploy - INFO - 

2023-01-24 00:52:39,547 - mmdeploy - INFO - **********Codebase information**********
2023-01-24 00:52:39,558 - mmdeploy - INFO - mmdet:	2.27.0
2023-01-24 00:52:39,558 - mmdeploy - INFO - mmseg:	None
2023-01-24 00:52:39,558 - mmdeploy - INFO - mmcls:	None
2023-01-24 00:52:39,558 - mmdeploy - INFO - mmocr:	None
2023-01-24 00:52:39,558 - mmdeploy - INFO - mmedit:	None
2023-01-24 00:52:39,558 - mmdeploy - INFO - mmdet3d:	None
2023-01-24 00:52:39,558 - mmdeploy - INFO - mmpose:	None
2023-01-24 00:52:39,558 - mmdeploy - INFO - mmrotate:	None
2023-01-24 00:52:39,558 - mmdeploy - INFO - mmaction:	None
```

### Error traceback

```Shell
2023-01-24 00:53:49,589 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\mmdeploy\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\admin\anaconda3\envs\mmdeploy\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\project\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "D:\project\mmdeploy\mmdeploy\apis\pytorch2onnx.py", line 64, in torch2onnx
    torch_model = task_processor.init_pytorch_model(model_checkpoint)
  File "D:\project\mmdeploy\mmdeploy\codebase\mmdet\deploy\object_detection.py", line 102, in init_pytorch_model
    model = init_detector(self.model_cfg, model_checkpoint, self.device,
  File "d:\project\mmdetection\mmdet\apis\inference.py", line 44, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "d:\project\mmdetection\mmdet\models\builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "C:\Users\admin\anaconda3\envs\mmdeploy\lib\site-packages\mmcv\utils\registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "C:\Users\admin\anaconda3\envs\mmdeploy\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\admin\anaconda3\envs\mmdeploy\lib\site-packages\mmcv\utils\registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'YOLODetector is not in the models registry'
2023-01-24 00:53:52,078 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by AllentDan** [comment]
`mmyolo` requires mmcv 2.x and mmengine.

**Comment by AllentDan** [comment]
[dependencies](https://github.com/open-mmlab/mmyolo/blob/main/docs/zh_cn/get_started.md#%E4%BE%9D%E8%B5%96) FYI.

**Comment by SuFIND** [comment]
> `mmyolo` requires mmcv 2.x and mmengine.

thks. I remember the mmdeploy required mmcv maximum version must be <2.0 in main branch. Because I got the Error about **mmcv.Config has been remove in mmcv 2.x ** when I try it first time. To this end, I built a new environment in conda to ensure that the mmdeploy project works properly. 

the code like this:
```python
def load_config(*args) -> List[mmcv.Config]:
```

**Comment by AllentDan** [comment]
Yeah, you are expected to use mmdeploy 1.x or dev-1.x as well. Any way, close the issue since it got resolved. Feel free to reopen it or launch a new one if you have further questions.

**Comment by SuFIND** [comment]
> Yeah, you are expected to use mmdeploy 1.x or dev-1.x as well. Any way, close the issue since it got resolved. Feel free to reopen it or launch a new one if you have further questions.
I haven't actually managed to export the onnx or tensorRT files success.

Can I make sure what I need to do? follow this is ok？
1. create a new env for mmdeploy
2. install [get_start.py](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/get_started.md) required pytorch ,openmim, mmcv-full 
3. **download release 1.0.0rc1 pre-build pkg**
4. follow [the windows pre-build readme](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/02-how-to-run/prebuilt_package_windows.md) to install it,
5. clone mmdeploy project and checkout to branch 1.x
6. run dump script to model file

**Comment by AllentDan** [comment]
All you need to do is to use MMDeploy 1.0.0rc1+ and mmcv 2.x. There is no need to do all the steps again. Just change the mmdeploy version in the env.

**Comment by SuFIND** [comment]
> All you need to do is to use MMDeploy 1.0.0rc1+ and mmcv 2.x. There is no need to do all the steps again. Just change the mmdeploy version in the env.

thks, it's work for me.
