### ISSUE TITLE
[Bug] ImportError when converting to CoreML

### ISSUE THREAD

**Issue by JohannesBauer97** [open-mmlab/mmdeploy#1675]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

```
!python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet/detection/detection_coreml_static-800x1344.py \
    mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    mmdetection/demo/demo.jpg \
    --work-dir mmdeploy_model/faster-rcnn \
    --device cpu \
    --dump-info
```
fails with following output:
```
/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 308, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 129, in main
    export2SDK(
  File "/usr/local/lib/python3.8/dist-packages/mmdeploy/backend/sdk/export_info.py", line 456, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/usr/local/lib/python3.8/dist-packages/mmdeploy/backend/sdk/export_info.py", line 376, in get_deploy
    models = get_models(deploy_cfg, model_cfg, work_dir, device)
  File "/usr/local/lib/python3.8/dist-packages/mmdeploy/backend/sdk/export_info.py", line 148, in get_models
    from mmdeploy.backend.coreml import get_model_suffix
ImportError: cannot import name 'get_model_suffix' from 'mmdeploy.backend.coreml' (/usr/local/lib/python3.8/dist-packages/mmdeploy/backend/coreml/__init__.py)
```

### Reproduction

I'm doing everything in Google Colab.

**1. Installing according the docs**
```python
%cd /content
!pip install -U openmim
!mim install mmcv-full

# install MMDeploy
!wget https://github.com/open-mmlab/mmdeploy/releases/download/v0.12.0/mmdeploy-0.12.0-linux-x86_64-onnxruntime1.8.1.tar.gz
!tar -zxvf mmdeploy-0.12.0-linux-x86_64-onnxruntime1.8.1.tar.gz
%cd mmdeploy-0.12.0-linux-x86_64-onnxruntime1.8.1
!pip install dist/mmdeploy-0.12.0-py3-none-linux_x86_64.whl
!pip install sdk/python/mmdeploy_python-0.12.0-cp38-none-linux_x86_64.whl
%cd ..
# install inference engine: ONNX Runtime
!pip install onnxruntime==1.8.1
!wget https://github.com/microsoft/onnxruntime/releases/download/v1.8.1/onnxruntime-linux-x64-1.8.1.tgz
!tar -zxvf onnxruntime-linux-x64-1.8.1.tgz

import os
%env ONNXRUNTIME_DIR=/content/onnxruntime-linux-x64-1.8.1
lib_path = os.environ.get('LD_LIBRARY_PATH') + ":" + "/content/onnxruntime-linux-x64-1.8.1/lib"
%env LD_LIBRARY_PATH=$lib_path

print(os.environ.get('ONNXRUNTIME_DIR'))
print(os.environ.get('LD_LIBRARY_PATH'))
```
(Setting environment variables in Jupyter is done by `os`, `!export` is not working there)

**2. Just to verify my installation is working I converted to onnx (this is working)**
```python
# clone mmdeploy to get the deployment config. `--recursive` is not necessary
!git clone https://github.com/open-mmlab/mmdeploy.git

# clone mmdetection repo. We have to use the config file to build PyTorch nn module
!git clone https://github.com/open-mmlab/mmdetection.git
%cd mmdetection
!pip install -v -e .
%cd ..

# download Faster R-CNN checkpoint
!wget -P checkpoints https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth

# run the command to start model conversion
!python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py \
    mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    mmdetection/demo/demo.jpg \
    --work-dir mmdeploy_model/faster-rcnn \
    --device cpu \
    --dump-info
```

**3. Trying to convert to CoreML, but fails**
```python
!python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet/detection/detection_coreml_static-800x1344.py \
    mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    mmdetection/demo/demo.jpg \
    --work-dir mmdeploy_model/faster-rcnn \
    --device cpu \
    --dump-info
```
Output:
```
/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 308, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 129, in main
    export2SDK(
  File "/usr/local/lib/python3.8/dist-packages/mmdeploy/backend/sdk/export_info.py", line 456, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/usr/local/lib/python3.8/dist-packages/mmdeploy/backend/sdk/export_info.py", line 376, in get_deploy
    models = get_models(deploy_cfg, model_cfg, work_dir, device)
  File "/usr/local/lib/python3.8/dist-packages/mmdeploy/backend/sdk/export_info.py", line 148, in get_models
    from mmdeploy.backend.coreml import get_model_suffix
ImportError: cannot import name 'get_model_suffix' from 'mmdeploy.backend.coreml' (/usr/local/lib/python3.8/dist-packages/mmdeploy/backend/coreml/__init__.py)
```

### Environment

```Shell
/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
2023-01-26 16:48:49,119 - mmdeploy - INFO - 

2023-01-26 16:48:49,119 - mmdeploy - INFO - **********Environmental information**********
fatal: not a git repository (or any of the parent directories): .git
2023-01-26 16:48:49,539 - mmdeploy - INFO - sys.platform: linux
2023-01-26 16:48:49,539 - mmdeploy - INFO - Python: 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
2023-01-26 16:48:49,539 - mmdeploy - INFO - CUDA available: True
2023-01-26 16:48:49,539 - mmdeploy - INFO - GPU 0: Tesla T4
2023-01-26 16:48:49,539 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2023-01-26 16:48:49,539 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.2, V11.2.152
2023-01-26 16:48:49,539 - mmdeploy - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2023-01-26 16:48:49,539 - mmdeploy - INFO - PyTorch: 1.13.1+cu116
2023-01-26 16:48:49,540 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

2023-01-26 16:48:49,540 - mmdeploy - INFO - TorchVision: 0.14.1+cu116
2023-01-26 16:48:49,540 - mmdeploy - INFO - OpenCV: 4.6.0
2023-01-26 16:48:49,540 - mmdeploy - INFO - MMCV: 1.7.1
2023-01-26 16:48:49,540 - mmdeploy - INFO - MMCV Compiler: GCC 9.3
2023-01-26 16:48:49,540 - mmdeploy - INFO - MMCV CUDA Compiler: 11.6
2023-01-26 16:48:49,540 - mmdeploy - INFO - MMDeploy: 0.12.0+
2023-01-26 16:48:49,540 - mmdeploy - INFO - 

2023-01-26 16:48:49,540 - mmdeploy - INFO - **********Backend information**********
2023-01-26 16:48:49,548 - mmdeploy - INFO - tensorrt:	None
2023-01-26 16:48:49,612 - mmdeploy - INFO - ONNXRuntime:	1.8.1
2023-01-26 16:48:49,612 - mmdeploy - INFO - ONNXRuntime-gpu:	None
2023-01-26 16:48:49,612 - mmdeploy - INFO - ONNXRuntime custom ops:	Available
2023-01-26 16:48:49,613 - mmdeploy - INFO - pplnn:	None
2023-01-26 16:48:49,614 - mmdeploy - INFO - ncnn:	None
2023-01-26 16:48:49,615 - mmdeploy - INFO - snpe:	None
2023-01-26 16:48:49,616 - mmdeploy - INFO - openvino:	None
2023-01-26 16:48:49,617 - mmdeploy - INFO - torchscript:	1.13.1+cu116
2023-01-26 16:48:49,618 - mmdeploy - INFO - torchscript custom ops:	NotAvailable
2023-01-26 16:48:49,720 - mmdeploy - INFO - rknn-toolkit:	None
2023-01-26 16:48:49,720 - mmdeploy - INFO - rknn2-toolkit:	None
2023-01-26 16:48:49,721 - mmdeploy - INFO - ascend:	None
2023-01-26 16:48:49,721 - mmdeploy - INFO - coreml:	None
2023-01-26 16:48:49,722 - mmdeploy - INFO - tvm:	None
2023-01-26 16:48:49,722 - mmdeploy - INFO - 

2023-01-26 16:48:49,722 - mmdeploy - INFO - **********Codebase information**********
2023-01-26 16:48:49,723 - mmdeploy - INFO - mmdet:	2.27.0
2023-01-26 16:48:49,723 - mmdeploy - INFO - mmseg:	None
2023-01-26 16:48:49,723 - mmdeploy - INFO - mmcls:	None
2023-01-26 16:48:49,723 - mmdeploy - INFO - mmocr:	None
2023-01-26 16:48:49,723 - mmdeploy - INFO - mmedit:	None
2023-01-26 16:48:49,723 - mmdeploy - INFO - mmdet3d:	None
2023-01-26 16:48:49,723 - mmdeploy - INFO - mmpose:	None
2023-01-26 16:48:49,723 - mmdeploy - INFO - mmrotate:	None
2023-01-26 16:48:49,723 - mmdeploy - INFO - mmaction:	None
```

### Error traceback

```Shell
/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 308, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 129, in main
    export2SDK(
  File "/usr/local/lib/python3.8/dist-packages/mmdeploy/backend/sdk/export_info.py", line 456, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/usr/local/lib/python3.8/dist-packages/mmdeploy/backend/sdk/export_info.py", line 376, in get_deploy
    models = get_models(deploy_cfg, model_cfg, work_dir, device)
  File "/usr/local/lib/python3.8/dist-packages/mmdeploy/backend/sdk/export_info.py", line 148, in get_models
    from mmdeploy.backend.coreml import get_model_suffix
ImportError: cannot import name 'get_model_suffix' from 'mmdeploy.backend.coreml' (/usr/local/lib/python3.8/dist-packages/mmdeploy/backend/coreml/__init__.py)
```

**Comment by lvhan028** [comment]
It seems you haven't installed `coreml`

-------------------------------------------------------------------------------------------------------
2023-01-26 16:48:49,540 - mmdeploy - INFO - **********Backend information**********
2023-01-26 16:48:49,548 - mmdeploy - INFO - tensorrt:	None
2023-01-26 16:48:49,612 - mmdeploy - INFO - ONNXRuntime:	1.8.1
2023-01-26 16:48:49,612 - mmdeploy - INFO - ONNXRuntime-gpu:	None
2023-01-26 16:48:49,612 - mmdeploy - INFO - ONNXRuntime custom ops:	Available
2023-01-26 16:48:49,613 - mmdeploy - INFO - pplnn:	None
2023-01-26 16:48:49,614 - mmdeploy - INFO - ncnn:	None
2023-01-26 16:48:49,615 - mmdeploy - INFO - snpe:	None
2023-01-26 16:48:49,616 - mmdeploy - INFO - openvino:	None
2023-01-26 16:48:49,617 - mmdeploy - INFO - torchscript:	1.13.1+cu116
2023-01-26 16:48:49,618 - mmdeploy - INFO - torchscript custom ops:	NotAvailable
2023-01-26 16:48:49,720 - mmdeploy - INFO - rknn-toolkit:	None
2023-01-26 16:48:49,720 - mmdeploy - INFO - rknn2-toolkit:	None
2023-01-26 16:48:49,721 - mmdeploy - INFO - ascend:	None
**2023-01-26 16:48:49,721 - mmdeploy - INFO - coreml:	None**
2023-01-26 16:48:49,722 - mmdeploy - INFO - tvm:	None

**Comment by JohannesBauer97** [comment]
Ah, what a mistake...
But still, it's not possible to convert the checkpoint to CoreML using MMDeploy due to another issue which as I understand is an incompatibility with the faster rcnn architecture? 

I created an example, you can copy and tryout: https://colab.research.google.com/drive/1_V8S3UICyr9Uj3GT8xoBHk-mf-tf2AQF?usp=sharing

```python
#coremltools otherwise throws warnings that torch versions above 1.12.1 arent supported
!pip install torch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 torchtext==0.13.1
!pip install coremltools
!pip install opencv-python
!pip3 install openmim
!mim install mmcv-full

# clone mmdeploy to get the deployment config. `--recursive` is not necessary
!git clone https://github.com/open-mmlab/mmdeploy.git
%cd mmdeploy
!pip install -v -e .
%cd ..

# clone mmdetection repo. We have to use the config file to build PyTorch nn module
!git clone https://github.com/open-mmlab/mmdetection.git
%cd mmdetection
!pip install -v -e .
%cd ..

# download Faster R-CNN checkpoint
!wget -P checkpoints https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth

# run the command to start model conversion
!python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet/detection/detection_coreml_static-800x1344.py \
    mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    mmdetection/demo/demo.jpg \
    --work-dir mmdeploy_model/faster-rcnn \
    --device cpu \
    --dump-info
```

**Relevant Output**
```
Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 308, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 129, in main
    export2SDK(
  File "/content/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 456, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/content/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 376, in get_deploy
    models = get_models(deploy_cfg, model_cfg, work_dir, device)
  File "/content/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 148, in get_models
    from mmdeploy.backend.coreml import get_model_suffix
  File "/content/mmdeploy/mmdeploy/backend/coreml/__init__.py", line 12, in <module>
    from . import ops
  File "/content/mmdeploy/mmdeploy/backend/coreml/ops.py", line 28, in <module>
    def log2(context, node):
  File "/usr/local/lib/python3.8/dist-packages/coremltools/converters/mil/frontend/torch/torch_op_registry.py", line 58, in register_torch_op
    return func_wrapper(_func)
  File "/usr/local/lib/python3.8/dist-packages/coremltools/converters/mil/frontend/torch/torch_op_registry.py", line 42, in func_wrapper
    raise ValueError("Torch op {} already registered.".format(f_name))
ValueError: Torch op log2 already registered.
```

**!python mmdeploy/tools/check_env.py**
```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
2023-02-03 16:01:42,685 - mmdeploy - INFO - 

2023-02-03 16:01:42,685 - mmdeploy - INFO - **********Environmental information**********
fatal: not a git repository (or any of the parent directories): .git
2023-02-03 16:01:43,085 - mmdeploy - INFO - sys.platform: linux
2023-02-03 16:01:43,085 - mmdeploy - INFO - Python: 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
2023-02-03 16:01:43,085 - mmdeploy - INFO - CUDA available: False
2023-02-03 16:01:43,085 - mmdeploy - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2023-02-03 16:01:43,085 - mmdeploy - INFO - PyTorch: 1.12.1+cu102
2023-02-03 16:01:43,085 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

2023-02-03 16:01:43,085 - mmdeploy - INFO - TorchVision: 0.13.1+cu102
2023-02-03 16:01:43,085 - mmdeploy - INFO - OpenCV: 4.6.0
2023-02-03 16:01:43,085 - mmdeploy - INFO - MMCV: 1.7.1
2023-02-03 16:01:43,085 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2023-02-03 16:01:43,085 - mmdeploy - INFO - MMCV CUDA Compiler: 10.2
2023-02-03 16:01:43,085 - mmdeploy - INFO - MMDeploy: 0.12.0+
2023-02-03 16:01:43,085 - mmdeploy - INFO - 

2023-02-03 16:01:43,085 - mmdeploy - INFO - **********Backend information**********
2023-02-03 16:01:43,101 - mmdeploy - INFO - tensorrt:	None
2023-02-03 16:01:43,104 - mmdeploy - INFO - ONNXRuntime:	None
2023-02-03 16:01:43,106 - mmdeploy - INFO - pplnn:	None
2023-02-03 16:01:43,110 - mmdeploy - INFO - ncnn:	None
2023-02-03 16:01:43,113 - mmdeploy - INFO - snpe:	None
2023-02-03 16:01:43,115 - mmdeploy - INFO - openvino:	None
2023-02-03 16:01:43,121 - mmdeploy - INFO - torchscript:	1.12.1
2023-02-03 16:01:43,121 - mmdeploy - INFO - torchscript custom ops:	NotAvailable
2023-02-03 16:01:43,361 - mmdeploy - INFO - rknn-toolkit:	None
2023-02-03 16:01:43,361 - mmdeploy - INFO - rknn2-toolkit:	None
2023-02-03 16:01:43,364 - mmdeploy - INFO - ascend:	None
2023-02-03 16:01:48,691 - mmdeploy - INFO - coreml:	6.1
INFO:mmdeploy:coreml:	6.1
2023-02-03 16:01:48,694 - mmdeploy - INFO - tvm:	None
INFO:mmdeploy:tvm:	None
2023-02-03 16:01:48,694 - mmdeploy - INFO - 

INFO:mmdeploy:

2023-02-03 16:01:48,694 - mmdeploy - INFO - **********Codebase information**********
INFO:mmdeploy:**********Codebase information**********
2023-02-03 16:01:48,696 - mmdeploy - INFO - mmdet:	2.28.1
INFO:mmdeploy:mmdet:	2.28.1
2023-02-03 16:01:48,696 - mmdeploy - INFO - mmseg:	None
INFO:mmdeploy:mmseg:	None
2023-02-03 16:01:48,696 - mmdeploy - INFO - mmcls:	None
INFO:mmdeploy:mmcls:	None
2023-02-03 16:01:48,696 - mmdeploy - INFO - mmocr:	None
INFO:mmdeploy:mmocr:	None
2023-02-03 16:01:48,696 - mmdeploy - INFO - mmedit:	None
INFO:mmdeploy:mmedit:	None
2023-02-03 16:01:48,696 - mmdeploy - INFO - mmdet3d:	None
INFO:mmdeploy:mmdet3d:	None
2023-02-03 16:01:48,696 - mmdeploy - INFO - mmpose:	None
INFO:mmdeploy:mmpose:	None
2023-02-03 16:01:48,696 - mmdeploy - INFO - mmrotate:	None
INFO:mmdeploy:mmrotate:	None
2023-02-03 16:01:48,696 - mmdeploy - INFO - mmaction:	None
INFO:mmdeploy:mmaction:	None
```

**Comment by JohannesBauer97** [comment]
I'll close this issue, since the original problem was solved.
