### ISSUE TITLE
[Questionnaire] Which model do you want to support in mmdeploy?

### ISSUE THREAD

**Issue by VVsssssk** [open-mmlab/mmdeploy#170]
Which model do you want to support in mmdeploy? Comment here. You can like a comment to increase model priority.
|      | Model            | Codebase | Backend  | Number of likes |
| :--- | :--------------- | :------- | :------- | :---- |
| 1    | Swin-Transformer | mmcls    | tensorrt | 1     |

**Comment by VVsssssk** [comment]
E.g:
Swin-Transformer  mmcls tensorrt

**Comment by OrcunCanDeniz** [comment]
second  mmdet3d tensorrt

**Comment by haofanwang** [comment]
[htc](https://github.com/open-mmlab/mmdetection/tree/master/configs/htc) mmdetection tensorrt

**Comment by haofanwang** [comment]
[UPerNet](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/upernet) mmsegmentation tensorrt

**Comment by starhou** [comment]
[swin-transformer](https://github.
com/microsoft/Swin-Transformer.) 

[A ConvNet for the 2020s](https://github.com/facebookresearch/ConvNeXt)

Come on guys, looking forward to your updates

**Comment by starhou** [comment]
I haven't tried the conversion yet, I just used your example fater-rcnn. Maybe now, need to try.

**Comment by RunningLeon** [comment]
> [segmenter](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/segmenter) mmsegmentation tensorrt

@haofanwang Have you tried segmenter with mmdeploy?

**Comment by haofanwang** [comment]
> > [segmenter](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/segmenter) mmsegmentation tensorrt
> 
> @haofanwang Have you tried segmenter with mmdeploy?

@RunningLeon , Yes, but I receive error messages as below

```
TypeError: upsample_bicubic2d() received an invalid combination of arguments - got (Tensor, NoneType, bool, list), but expected one of:
 * (Tensor input, tuple of ints output_size, bool align_corners, tuple of floats scale_factors)
      didn't match because some of the arguments have invalid types: (Tensor, NoneType, bool, list)
 * (Tensor input, tuple of ints output_size, bool align_corners, float scales_h, float scales_w, *, Tensor out)
```

And my command is

```
python ./tools/deploy.py \
    ./configs/mmseg/segmentation_tensorrt-fp16_dynamic-512x1024-2048x2048.py \
    ./mmsegmentation/configs/segmenter/segmenter_vit-l_mask_8x1_512x512_160k_ade20k.py \
    ./mmsegmentation/checkpoints/segmenter_vit-l_mask_8x1_512x512_160k_ade20k_20220105_162750-7ef345be.pth \
    ./mmsegmentation/demo/demo.png \
    --work-dir work_dir\
    --device cuda\
    --dump-in
```

**Comment by RunningLeon** [comment]
> 512x512
@haofanwang 
Try with static config with 512x512. You can change in config file.

**Comment by eliabruni** [comment]
[maskformer](https://github.com/open-mmlab/mmdetection/tree/master/configs/maskformer) mmdet tensorrt

**Comment by Bryce-HJ** [comment]
[swin-transformer](https://github.com/microsoft/Swin-Transformer) mmdet onnx

**Comment by Siannodel** [comment]
Swin-Transformer mmcls tensorrt

**Comment by awesome01010** [comment]
SATRN for ocr, to onnx and tensorrt pls!

**Comment by summerlvsong** [comment]
SATRN for ocr, to onnx and tensorrt pls!

**Comment by Xiangxu-0103** [comment]
dynamic_voxelization mmdet3d onnxruntime and tensorrt

**Comment by YongboLiang** [comment]
Swin-Transformer Second  Segmenter

**Comment by xuhui1994** [comment]
> 

psenet mmocr tensorrt

**Comment by hust-lidelong** [comment]
[Oriented R-CNN](https://github.com/open-mmlab/mmrotate/blob/main/configs/oriented_rcnn/README.md)，[S2A-Net](https://github.com/open-mmlab/mmrotate/blob/main/configs/s2anet/README.md) for mmrotate tensorrt, please!

**Comment by eliabruni** [comment]
[mask2former](https://github.com/open-mmlab/mmdetection/tree/master/configs/mask2former) mmdet tensorrt

**Comment by jianghaijun007** [comment]
monoflex tensorrt

**Comment by gzxy-0102** [comment]
mmtracking

**Comment by troyliu0105** [comment]
AssociativeEmbedding pose detection in `mmpose`

**Comment by SpaceView** [comment]
mmocr

**Comment by rickvanveen** [comment]
yolact

**Comment by LeoRainly** [comment]
K-Net

**Comment by leemengwei** [comment]
htc

**Comment by s95huang** [comment]
Smoke, mmdetection3d , tensorrt

**Comment by manhtd98** [comment]
Swin-Transformer mmcls tensorrt

**Comment by zhangzscn** [comment]
yolact mmdetection onnx

**Comment by Liuhongmiao** [comment]
a vote to TOOD

**Comment by wwcc1107** [comment]
deformable detr！，detr！，transformer系列

**Comment by lvhan028** [comment]
> [segmenter](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/segmenter) mmsegmentation tensorrt

Done. It's been supported in v0.6.0

**Comment by lvhan028** [comment]
> Swin-Transformer mmdetection tensorrt

Done. It's been supported in v0.6.0

**Comment by DoubleChuang** [comment]
solov2 onnx tensorrt

**Comment by KooSung** [comment]
TSM/TSN... mmaction2 tensorrt

**Comment by oYAYAYo** [comment]
mmdetection3d SMOKE

**Comment by zml24** [comment]
deepfillv2 mmediting tensorrt

**Comment by MaxeeCR** [comment]
[TSM](https://github.com/open-mmlab/mmaction2/tree/master/configs/recognition/tsm)、[Video swin-transformer](https://github.com/SwinTransformer/Video-Swin-Transformer/tree/master/configs/recognition/swin) mmaction2 tensorrt :heart_eyes: :pray:

**Comment by machine52vision** [comment]
solov2

**Comment by machine52vision** [comment]
mmdetection solov2

**Comment by 421psh** [comment]
solov2 tensorrt

**Comment by FDInSky** [comment]
fcos3d in mmdetection3d

**Comment by elepherai** [comment]
solov2 tensorrt

**Comment by eliabruni** [comment]
@VVsssssk : Given that both MaskFormer and Mask2Former got lots of votes, is there any plan to support them? They are not even on the table on top, any specific reason? Thank you!

**Comment by KongCang** [comment]
solov2 onnx tensorrt

**Comment by kishcs** [comment]
SAR model

**Comment by kelvinwang139** [comment]
ConvNeXt

**Comment by awarebayes** [comment]
[ConvNext](https://github.com/open-mmlab/mmdetection/tree/master/configs/convnext) mmdet tensorrt

**Comment by nikky4D** [comment]
HTC segmentation object detection, onnx tensorrt

**Comment by mayunjie** [comment]
basicvsr

**Comment by luvwinnie** [comment]
HTC segmentation object detection, onnx tensorrt, which having 3 heads.

**Comment by S1mKu** [comment]
RobustScanner mmocr tensorrt

**Comment by JordanH-app** [comment]
AttentionRPN MMFewShot ONNX

**Comment by cloudpanl** [comment]
3D Unet ONNX

**Comment by majintao1994** [comment]
mmyolo mmdetection3

**Comment by RunningLeon** [comment]
> mmyolo mmdetection3
@majintao1994 Hi,Note that these two codebases are supported in mmdeploy.

**Comment by hoangkhoiLE** [comment]
poseC3D mmaction2

**Comment by XianminMo** [comment]
MVXnet mmdetection3d onnx

**Comment by buerger-pascal** [comment]
Mask2former ONNX TensorRT

**Comment by Kiryuumaru** [comment]
Multimodal donut (https://huggingface.co/docs/transformers/model_doc/donut) TensorRT

**Comment by eliabruni** [comment]
Vision Transformer (RKNN)

**Comment by shudct** [comment]
DINO mmdet tensorrt

**Comment by kelvinwang139** [comment]
> Which model do you want to support in mmdeploy? Comment here. You can like a comment to increase model priority.
> 
> Model	Codebase	Backend	Number of likes	Released
> 1	Swin-Transformer	mmcls	tensorrt	2	v0.6.0
> 2	Second	mmdet3d	tensorrt	1	
> 3	htc	mmdet	tensorrt	1	
> 4	Segmenter	mmseg	tensorrt	1	v0.6.0
> 5	ConvNeXt	mmcls	tensorrt	1	
> 6	MASTER	mmocr	tensorrt	1	
> 7	ABINet	mmocr	tensorrt	1	
> 8	BEVFormer	mmdet3d	tensorrt	1	
> 9	Oriented R-CNN	mmrotate	tensorrt	1	v0.6.0
> 10	SAR	mmocr	tensorrt	1	
> Reference:
> 
> * [ ]  MASTER: [ocr识别模型master // Can MASTER from mmocr be deployed?  #623](https://github.com/open-mmlab/mmdeploy/issues/623)
> * [ ]  ABINet: [ABINet deployment #689](https://github.com/open-mmlab/mmdeploy/issues/689)
> * [ ]  BEVFormer: [Need to deploy MultiViewImage Model BEVFormer based on mmdet3d #688](https://github.com/open-mmlab/mmdeploy/issues/688)
> * [ ]  SAR: [cannot find ResizeOCR implementation on specific platform cuda #630](https://github.com/open-mmlab/mmdeploy/issues/630)

mask2former mmsegmentation tensorRT
mask2former mmdetection tensorRT
[mask2former](https://github.com/open-mmlab/mmsegmentation/tree/main/configs/mask2former)

**Comment by liuch37** [comment]
[PIDNet](https://github.com/open-mmlab/mmsegmentation/tree/main/configs/pidnet) mmsegmentation ONNX TensorRT

**Comment by lixumin-zai** [comment]
DINO mmdet tensorrt

**Comment by xenocloud7732** [comment]
UniFormer V2 mmaction2 tensorrt

**Comment by xiaotaw** [comment]
Segment Anything, tensorrt

**Comment by h030162** [comment]
UniFormer V2 mmaction2 onnx

**Comment by lucianzhong** [comment]
BEVFusion, tensorrt int8

**Comment by CerPhd** [comment]
TC-Former! [(https://github.com/zengwang430521/TCFormer](url) Already implemented on previous version of MMpose.

**Comment by Charlyo** [comment]
DetectoRS in tensorrt

**Comment by WeitaoVan** [comment]
mmtracking sot model

**Comment by PancakeAwesome** [comment]
mmyolo yolox int8 quantization

**Comment by RunningLeon** [comment]
> 

@PancakeAwesome which backend? mmyolo:yolox is supported with ort, trt.

**Comment by idonahum1** [comment]
DINO in mmdetection

**Comment by diwgan32** [comment]
posec3d from mmaction2!

**Comment by GeorgePearse** [comment]
DetectoRS in tensorrt and ONNX

**Comment by rpl-alan-shangguan** [comment]
panoptic-fpn from mmdet, in tensorrt and onnx.

**Comment by wanghlsara** [comment]
vitpose in onnx and tensorrt

**Comment by wanghlsara** [comment]
vitpose+

**Comment by RobinHan24** [comment]
DINO mmdet tensorrt

**Comment by sibet-lb** [comment]
deformable detr mmdet tensorrt

**Comment by RunningLeon** [comment]
> [maskformer](https://github.com/open-mmlab/mmdetection/tree/master/configs/maskformer) mmdet tensorrt

@eliabruni hi. If you have time, pls. try this PR https://github.com/open-mmlab/mmdeploy/pull/2347. Any comment on the PR is greatly appreciated.

**Comment by ycdhqzhiai** [comment]
fcos3d mmdet3d tensorrt

**Comment by Zaughter** [comment]
dab-detr onnx

**Comment by RunningLeon** [comment]
> dab-detr onnx
@Zaughter @DuckJ @sibet-lb @RobinHan24 @idonahum1 
hi, for DETR, DINO, Dab-DETR, Conditional-DETR, could try this PR#https://github.com/open-mmlab/mmdeploy/pull/2410

**Comment by RobinHan24** [comment]
> > dab-detr onnx
> 
> @Zaughter @DuckJ @sibet-lb @RobinHan24 @idonahum1 hi, for DETR, DINO, Dab-DETR, Conditional-DETR, could try this PR##2410

I just tried it, but error.

2023-09-10:10:53:30 - root - ERROR - execute_async_v2(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.IExecutionContext, bindings: List[int], stream_handle: int, input_consumed: capsule = None) -> bool

Invoked with: <tensorrt.tensorrt.IExecutionContext object at 0x7f01857b5bb0>, [139631165177856, None, 139634709371904, 139634709365760], 0
Traceback (most recent call last):
  File "/mnt/sda/qilibin/project/mmdeploy-support_detr_multi-batch/mmdeploy/utils/utils.py", line 41, in target_wrapper
    result = target(*args, **kwargs)
  File "/mnt/sda/qilibin/project/mmdeploy-support_detr_multi-batch/mmdeploy/apis/visualize.py", line 72, in visualize_model
    result = model.test_step(model_inputs)[0]
  File "/mnt/sda/qilibin/miniconda3/envs/py3.9/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/mnt/sda/qilibin/miniconda3/envs/py3.9/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/mnt/sda/qilibin/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/sda/qilibin/project/mmdeploy-support_detr_multi-batch/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 299, in forward
    outputs = self.predict(inputs, shape_info)
  File "/mnt/sda/qilibin/project/mmdeploy-support_detr_multi-batch/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 323, in predict
    outputs = self.wrapper(inputs)
  File "/mnt/sda/qilibin/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/sda/qilibin/project/mmdeploy-support_detr_multi-batch/mmdeploy/backend/tensorrt/wrapper.py", line 174, in forward
    self.__trt_execute(bindings=bindings)
  File "/mnt/sda/qilibin/project/mmdeploy-support_detr_multi-batch/mmdeploy/utils/timer.py", line 67, in fun
    result = func(*args, **kwargs)
  File "/mnt/sda/qilibin/project/mmdeploy-support_detr_multi-batch/mmdeploy/backend/tensorrt/wrapper.py", line 185, in __trt_execute
    self.context.execute_async_v2(bindings,
TypeError: execute_async_v2(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.IExecutionContext, bindings: List[int], stream_handle: int, input_consumed: capsule = None) -> bool

Invoked with: <tensorrt.tensorrt.IExecutionContext object at 0x7f01857b5bb0>, [139631165177856, None, 139634709371904, 139634709365760], 0
09/10 10:53:32 - mmengine - ERROR - /mnt/sda/qilibin/project/mmdeploy-support_detr_multi-batch/tools/deploy.py - create_process - 82 - visualize tensorrt model failed.

tensorrt version: 8.6.1.6

command:
python tools/deploy.py configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py dino/dino-4scale_r50_8xb2-36e_coco.py dino-4scale_r50_8xb2-12e_coco_20221202_182705-55b2bba2.pth demo/resources/det.jpg  --work-dir mmdeploy_models/mmdet/dino --device cuda --show --dump-info

could you please help me？

**Comment by RobinHan24** [comment]
> > dab-detr onnx
> 
> @Zaughter @DuckJ @sibet-lb @RobinHan24 @idonahum1 hi, for DETR, DINO, Dab-DETR, Conditional-DETR, could try this PR##2410
thanks a lot, I have got the tensorrt model. But how to infer with trt model sdk?
my code:
from mmdeploy_runtime import Detector
import cv2

img = cv2.imread('./demo/resources/det.jpg')

# create a detector
detector = Detector(model_path='mmdeploy_models/mmdet/dino0910', device_name='cuda', device_id=0)
# perform inference
res = detector(img)
print (res)
# visualize inference result
indices = [i for i in range(len(bboxes))]
for index, bbox, label_id in zip(indices, bboxes, labels):
  [left, top, right, bottom], score = bbox[0:4].astype(int), bbox[4]
  if score < 0.3:
    continue

  cv2.rectangle(img, (left, top), (right, bottom), (0, 255, 0))

cv2.imwrite('output_detection.png', img)


error:
[2023-09-10 12:51:09.788] [mmdeploy] [error] [net_module.cpp:130] sample 0 missing key shape

can you help me, thanks.

**Comment by MarouaneMja** [comment]
CO-DETR [https://github.com/Sense-X/Co-DETR](url)

**Comment by x-yy0** [comment]
mvxnet mmdet3d tensorrt

**Comment by mjehanzaib999** [comment]
slowonly(spatiotemporal) mmaction tensorrt

**Comment by DoctorDream** [comment]
Co-DETR please!

**Comment by Mayyyybe** [comment]
Co-DETR to onnx please！！！

**Comment by MarouaneMja** [comment]
@DoctorDream @Mayyyybe I already mentionned CO-DETR,  Could you please upvote my suggestion , so that it could increase this model priority?

**Comment by Baboom-l** [comment]
Grounding DINO mmdetection tensorrt

**Comment by xinlin-xiao** [comment]
> CO-DETR [https://github.com/Sense-X/Co-DETR](url) -> onnx and tensorrt

CO-DETR->onnx ,TorchScript,tensorrt

**Comment by OSSome01** [comment]
KNet mmsegmentaion
ConvNext mmsegmentation

**Comment by WaseemDR** [comment]
TensorRT for Grounding Dino

**Comment by Jialeen** [comment]
TensorRT for Detic

**Comment by iceriver97** [comment]
> fcos3d mmdet3d tensorrt

这个目前实现了吗？

**Comment by chunxt** [comment]
tood. thanks

**Comment by Nieees** [comment]
htc Series models （scnet， detectRS） Is there any progress so far?

**Comment by monologuesmw** [comment]
TOOD model. Thanks!

**Comment by monkeycc** [comment]
YOLOv8
[Detect]
[Segment]
[Classify]
[Pose]
[OBB]

**Comment by ZJU-lishuang** [comment]
glip | mmdet | tensorrt

**Comment by chenzhutian** [comment]
3D pose in mmPose

**Comment by xlg-go** [comment]
SVTR for ocr, to onnx and tensorRT pls!

**Comment by MarouaneMja** [comment]
> CO-DETR [https://github.com/Sense-X/Co-DETR](url) -> onnx and tensorrt

Hello  @VVsssssk ,

Any updates about the exportation of Co-DETR to onnx and tensorrt please?

Best regards,
Marouane

**Comment by songkemail** [comment]
superpoint superglue

**Comment by sjtu-cz** [comment]
Swin-Transformer v2 mmpretrain tensorRT

**Comment by wostons** [comment]
grounding_dino

**Comment by Liufanfanfan** [comment]
ddrnet-slim mmseg

**Comment by yu1206** [comment]
grounding dino  转onnx  AttributeError: 'DetDataSample' object has no attribute 'text'

**Comment by DataXujing** [comment]
> CO-DETR [https://github.com/Sense-X/Co-DETR](url) -> onnx and tensorrt

https://github.com/open-mmlab/mmdeploy/issues/2487#issuecomment-2401133051

**Comment by yu1206** [comment]
&nbsp;请问什么时候能支持 grounding dino训练输出的模型 转成Onnx格式

**Comment by kkangshen** [comment]
maprt-v2

**Comment by sjtu-cz** [comment]
您好，你的邮件我已经收到~

**Comment by Petros626** [comment]
Does anybody add support for more `MMRotate` models.  For example  I want to deploy `H2RBox(-v2)` to `TensorRT`.

**Comment by jodyngo** [comment]
BEVFusion - onnx

**Comment by WingsofFAN** [comment]
mmation2 video-detection slowfast

**Comment by Petros626** [comment]
@jodyngo, @WingsofFAN  do you think, that still models will be deployed?

**Comment by jodyngo** [comment]
> [@jodyngo](https://github.com/jodyngo), [@WingsofFAN](https://github.com/WingsofFAN) do you think, that still models will be deployed?

Yes, sure. I need to deploy Bevfusion.

**Comment by Petros626** [comment]
> > [@jodyngo](https://github.com/jodyngo), [@WingsofFAN](https://github.com/WingsofFAN) do you think, that still models will be deployed?
> 
> Yes, sure. I need to deploy Bevfusion.

Are you one of the openmmlab maintainers or how can you know this?

**Comment by ctgushiwei** [comment]
grounding_dino

**Comment by dutian312** [comment]
mmocr svrt
