### ISSUE TITLE
[Bug] run deploy example on ubuntu with onnx tells: RuntimeError: _Map_base::at

### ISSUE THREAD

**Issue by XiaotaoChen** [open-mmlab/mmdeploy#1769]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [x] 3. The bug has not been fixed in the latest version.

### Describe the bug

I'm trying mmdeploy according to the docs: https://mmdeploy.readthedocs.io/zh_CN/latest/get_started.html, but can't run the example correctly. according to the error info, it seems like pytorch version and onnx version dismatch, there are relative issues:  https://github.com/onnx/onnx/issues/2458 https://github.com/onnx/onnx/issues/2417. i try to fix it, but can't work.
### mmdeploy envs
```shell
mmcv-full                1.6.0
mmdeploy                 0.10.0     /workspace/chenxiaotao03/rv11091126/repositories/mmdeploy
mmdet                    2.25.1     /workspace/chenxiaotao03/rv11091126/repositories/mmdetection
mmengine                 0.5.0
```
### onnx envs
```shell
onnx                     1.11.0
onnxruntime              1.8.1
```

### test script
the pth model download from: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
```shell
 python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py \
    mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    ~/model/torch/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    mmdetection/demo/demo.jpg \
    --work-dir mmdeploy_model/faster-rcnn \
    --device cpu \
    --dump-info
```

### Environment

```Shell
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
2023-02-15 17:08:32,128 - mmdeploy - INFO -

2023-02-15 17:08:32,128 - mmdeploy - INFO - **********Environmental information**********
2023-02-15 17:08:32,335 - mmdeploy - INFO - sys.platform: linux
2023-02-15 17:08:32,335 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
2023-02-15 17:08:32,335 - mmdeploy - INFO - CUDA available: False
2023-02-15 17:08:32,335 - mmdeploy - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
2023-02-15 17:08:32,335 - mmdeploy - INFO - PyTorch: 1.13.1+cu117
2023-02-15 17:08:32,335 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

2023-02-15 17:08:32,335 - mmdeploy - INFO - TorchVision: 0.14.1+cu117
2023-02-15 17:08:32,335 - mmdeploy - INFO - OpenCV: 4.7.0
2023-02-15 17:08:32,335 - mmdeploy - INFO - MMCV: 1.6.0
2023-02-15 17:08:32,335 - mmdeploy - INFO - MMCV Compiler: GCC 7.5
2023-02-15 17:08:32,335 - mmdeploy - INFO - MMCV CUDA Compiler: not available
2023-02-15 17:08:32,335 - mmdeploy - INFO - MMDeploy: 0.10.0+4c34ad7
2023-02-15 17:08:32,335 - mmdeploy - INFO -

2023-02-15 17:08:32,335 - mmdeploy - INFO - **********Backend information**********
2023-02-15 17:08:32,583 - mmdeploy - INFO - onnxruntime: 1.8.1	ops_is_avaliable : True
2023-02-15 17:08:32,584 - mmdeploy - INFO - tensorrt: None	ops_is_avaliable : False
2023-02-15 17:08:32,594 - mmdeploy - INFO - ncnn: None	ops_is_avaliable : False
2023-02-15 17:08:32,594 - mmdeploy - INFO - pplnn_is_avaliable: False
2023-02-15 17:08:32,595 - mmdeploy - INFO - openvino_is_avaliable: False
2023-02-15 17:08:32,606 - mmdeploy - INFO - snpe_is_available: False
2023-02-15 17:08:32,607 - mmdeploy - INFO - ascend_is_available: False
2023-02-15 17:08:32,607 - mmdeploy - INFO - coreml_is_available: False
2023-02-15 17:08:32,607 - mmdeploy - INFO -

2023-02-15 17:08:32,607 - mmdeploy - INFO - **********Codebase information**********
2023-02-15 17:08:32,608 - mmdeploy - INFO - mmdet:	2.25.1
2023-02-15 17:08:32,608 - mmdeploy - INFO - mmseg:	None
2023-02-15 17:08:32,608 - mmdeploy - INFO - mmcls:	None
2023-02-15 17:08:32,608 - mmdeploy - INFO - mmocr:	None
2023-02-15 17:08:32,608 - mmdeploy - INFO - mmedit:	None
2023-02-15 17:08:32,608 - mmdeploy - INFO - mmdet3d:	None
2023-02-15 17:08:32,608 - mmdeploy - INFO - mmpose:	None
2023-02-15 17:08:32,608 - mmdeploy - INFO - mmrotate:	None
```

### Error traceback

```Shell
### error log

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
[2023-02-15 17:07:09.803] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
[2023-02-15 17:07:10.844] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
/workspace/chenxiaotao03/rv11091126/repositories/mmdetection/mmdet/datasets/utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
[2023-02-15 17:07:12.366] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
2023-02-15 17:07:12,369 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
load checkpoint from local path: /home/chenxiaotao03/model/torch/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
/workspace/chenxiaotao03/rv11091126/repositories/mmdetection/mmdet/datasets/utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
2023-02-15 17:07:13,129 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
2023-02-15 17:07:13,129 - mmdeploy - INFO - Export PyTorch model to ONNX: mmdeploy_model/faster-rcnn/end2end.onnx.
/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/workspace/chenxiaotao03/rv11091126/repositories/mmdetection/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
/workspace/chenxiaotao03/rv11091126/repositories/mmdetection/mmdet/core/anchor/anchor_generator.py:333: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors``
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/workspace/chenxiaotao03/rv11091126/repositories/mmdetection/mmdet/core/anchor/anchor_generator.py:369: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors``
  warnings.warn(
/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py:79: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/pytorch/functions/topk.py:28: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  k = torch.tensor(k, device=input.device, dtype=torch.long)
/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/codebase/mmdet/deploy/utils.py:47: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(max_shape) == 2, '`max_shape` should be [h, w]'
/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:92: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  iou_threshold = torch.tensor([iou_threshold], dtype=torch.float32)
/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:93: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  score_threshold = torch.tensor([score_threshold], dtype=torch.float32)
/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/mmcv/ops/nms.py:40: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  score_threshold = float(score_threshold)
/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/mmcv/ops/nms.py:41: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  iou_threshold = float(iou_threshold)
/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmcv/ops/nms.py:171: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmcv/ops/nms.py:172: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmcv/ops/nms.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if max_num > 0:
Process Process-2:
Traceback (most recent call last):
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 96, in torch2onnx
    export(
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/apis/onnx/export.py", line 122, in export
    torch.onnx.export(
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/apis/onnx/optimizer.py", line 10, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/base.py", line 70, in base_detector__forward
    return __forward_impl(ctx, self, img, img_metas=img_metas, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/core/optimizers/function_marker.py", line 261, in g
    rets = f(*args, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/base.py", line 26, in __forward_impl
    return self.simple_test(img, img_metas, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/two_stage.py", line 58, in two_stage_detector__simple_test
    proposals, _ = self.rpn_head.simple_test_rpn(x, img_metas)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdetection/mmdet/models/dense_heads/dense_test_mixins.py", line 130, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas=img_metas)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py", line 143, in rpn_head__get_bboxes
    return multiclass_nms(
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/core/optimizers/function_marker.py", line 261, in g
    rets = f(*args, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py", line 278, in multiclass_nms
    return _multiclass_nms(*args, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py", line 215, in multiclass_nms__default
    return ctx.origin_func(
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py", line 104, in _multiclass_nms
    selected_indices = ONNXNMSop.apply(boxes, scores,
  File "/workspace/chenxiaotao03/rv11091126/repositories/mmdeploy/mmdeploy/mmcv/ops/nms.py", line 48, in forward
    _, box_inds = nms(
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmcv/utils/misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "/home/chenxiaotao03/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmcv/ops/nms.py", line 175, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset, score_threshold,
RuntimeError: _Map_base::at
2023-02-15 17:07:14,466 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by XiaotaoChen** [comment]
将torch降级到1.10.0，torchvision改成0.11.1，mmcv使用mim安装就好了。
