### ISSUE TITLE
[Bug] fcos3d模型转tensorRT模型报错

### ISSUE THREAD

**Issue by happyday-lkj** [open-mmlab/mmdeploy#1770]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

fcos3d模型转tensorRT模型报错
`02/15 17:43:43 - mmengine - WARNING - Failed to search registry with scope "mmdet3d" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet3d" is a correct scope, or whether the registry is initialized.`

`mmengine - ERROR - /data/mono3d/mmdeploy-1.0.0rc1/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 81 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.`

一开始报和[这里](https://github.com/open-mmlab/mmdeploy/issues/1656#issue-1532532179)一样的错误，然后按照[建议](https://github.com/open-mmlab/mmdeploy/issues/1656#issuecomment-1383644716)进行修改，升级mmdeploy的版本，然后就报了上面的错误；

### Reproduction

在deploy目录：
python ./tools/deploy.py configs/mmdet3d/monocular-detection/monocular-detection_tensorrt_static-928x1600.py \
           ../mmdetection3d/configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune.py \
           /data/lmodels/mono_3d/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune.pth \
           ../mmdetection3d/demo/data/kitti/kitti_000008.png \
           --work-dir work_dir \
           --device cuda:1

### Environment

```Shell
02/15 17:49:20 - mmengine - INFO - 

02/15 17:49:20 - mmengine - INFO - **********Environmental information**********
02/15 17:49:21 - mmengine - INFO - sys.platform: linux
02/15 17:49:21 - mmengine - INFO - Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
02/15 17:49:21 - mmengine - INFO - CUDA available: True
02/15 17:49:21 - mmengine - INFO - numpy_random_seed: 2147483648
02/15 17:49:21 - mmengine - INFO - GPU 0,1,2,3: NVIDIA A40
02/15 17:49:21 - mmengine - INFO - CUDA_HOME: /opt/cuda-11.3
02/15 17:49:21 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.58
02/15 17:49:21 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
02/15 17:49:21 - mmengine - INFO - PyTorch: 1.10.0
02/15 17:49:21 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

02/15 17:49:21 - mmengine - INFO - TorchVision: 0.11.0
02/15 17:49:21 - mmengine - INFO - OpenCV: 4.5.4
02/15 17:49:21 - mmengine - INFO - MMEngine: 0.5.0
02/15 17:49:21 - mmengine - INFO - MMCV: 2.0.0rc1
02/15 17:49:21 - mmengine - INFO - MMCV Compiler: GCC 7.5
02/15 17:49:21 - mmengine - INFO - MMCV CUDA Compiler: 11.3
02/15 17:49:21 - mmengine - INFO - MMDeploy: 1.0.0rc1+
02/15 17:49:21 - mmengine - INFO - 

02/15 17:49:21 - mmengine - INFO - **********Backend information**********
02/15 17:49:21 - mmengine - INFO - tensorrt:	8.2.1.8
02/15 17:49:21 - mmengine - INFO - tensorrt custom ops:	Available
02/15 17:49:21 - mmengine - INFO - ONNXRuntime:	1.14.0
02/15 17:49:21 - mmengine - INFO - ONNXRuntime-gpu:	None
02/15 17:49:21 - mmengine - INFO - ONNXRuntime custom ops:	Available
02/15 17:49:21 - mmengine - INFO - pplnn:	None
02/15 17:49:21 - mmengine - INFO - ncnn:	None
02/15 17:49:21 - mmengine - INFO - snpe:	None
02/15 17:49:21 - mmengine - INFO - openvino:	2022.3.0
02/15 17:49:21 - mmengine - INFO - torchscript:	1.10.0
02/15 17:49:21 - mmengine - INFO - torchscript custom ops:	NotAvailable
02/15 17:49:21 - mmengine - INFO - rknn-toolkit:	None
02/15 17:49:21 - mmengine - INFO - rknn2-toolkit:	None
02/15 17:49:21 - mmengine - INFO - ascend:	None
02/15 17:49:21 - mmengine - INFO - coreml:	None
02/15 17:49:21 - mmengine - INFO - tvm:	None
02/15 17:49:21 - mmengine - INFO - 

02/15 17:49:21 - mmengine - INFO - **********Codebase information**********
02/15 17:49:21 - mmengine - INFO - mmdet:	3.0.0rc4
02/15 17:49:21 - mmengine - INFO - mmseg:	1.0.0rc0
02/15 17:49:21 - mmengine - INFO - mmcls:	1.0.0rc2
02/15 17:49:21 - mmengine - INFO - mmocr:	1.0.0rc4
02/15 17:49:21 - mmengine - INFO - mmedit:	1.0.0rc2
02/15 17:49:21 - mmengine - INFO - mmdet3d:	1.1.0rc2
02/15 17:49:21 - mmengine - INFO - mmpose:	1.0.0rc0
02/15 17:49:21 - mmengine - INFO - mmrotate:	None
02/15 17:49:21 - mmengine - INFO - mmaction:	None
```

**Comment by happyday-lkj** [comment]
Error trackback
`02/15 17:43:30 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
02/15 17:43:43 - mmengine - WARNING - Failed to search registry with scope "mmdet3d" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet3d" is a correct scope, or whether the registry is initialized.
Process Process-2:
Traceback (most recent call last):
  File "/data/softwares/anaconda3/envs/openmmlab/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/data/softwares/anaconda3/envs/openmmlab/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/data/companyPro/mono3d/mmdeploy-1.0.0rc1/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/data/companyPro/mono3d/mmdeploy-1.0.0rc1/mmdeploy/apis/pytorch2onnx.py", line 61, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/data/companyPro/mono3d/mmdeploy-1.0.0rc1/mmdeploy/apis/utils/utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "/data/companyPro/mono3d/mmdeploy-1.0.0rc1/mmdeploy/codebase/base/mmcodebase.py", line 44, in build_task_processor
    task = get_task_type(deploy_cfg)
  File "/data/companyPro/mono3d/mmdeploy-1.0.0rc1/mmdeploy/utils/config_utils.py", line 62, in get_task_type
    return Task.get(task)
  File "/data/companyPro/mono3d/mmdeploy-1.0.0rc1/mmdeploy/utils/constants.py", line 15, in get
    raise KeyError(f'Cannot get key by value "{value}" of {cls}')
KeyError: 'Cannot get key by value "MonocularDetection" of <enum \'Task\'>'
02/15 17:43:44 - mmengine - ERROR - /data/companyPro/mono3d/mmdeploy-1.0.0rc1/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 81 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.`

**Comment by Yutong-gannis** [comment]
@happyday-lkj mmdeploy1.x不支持单目3D了

**Comment by infatuation0215** [comment]
I met the same issue. Have you solved this problem? If so, could you please show me some details?
