### ISSUE TITLE
[Bug] ImportError: DLL load failed while importing mmdeploy_python

### ISSUE THREAD

**Issue by HwanWoongLee** [open-mmlab/mmdeploy#1809]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

hello.
I am running the example below in the MMdeploy Windows environment.

![image](https://user-images.githubusercontent.com/20108771/221095727-ad83c96f-0bbe-4bb0-b38f-762884fa99b3.png)

Executing the code results in the following error

` python .\mmdeploy\demo\python\image_classification.py cuda .\work_dir\trt\resnet\ .\mmclassification\demo\demo.JPEG`

**Error Message**
> Traceback (most recent call last):
  File "D:/openmmlab/mmdeploy/demo/python/image_classification.py", line 7, in <module>
    from mmdeploy_python import Classifier
  File "C:\ProgramData\miniconda3\envs\openmmlab\lib\site-packages\mmdeploy_python\__init__.py", line 21, in <module>
    from .mmdeploy_python import *  # noqa
ImportError: DLL load failed while importing mmdeploy_python: 지정된 모듈을 찾을 수 없습니다.

I am only using TensorRT. (onnx not installed)

Attaching the result of os.environ['PATH'].

> _C:\ProgramData\miniconda3\envs\openmmlab\python.exe 
> D:/openmmlab/mmdeploy/demo/python/image_classification.py
> C:\ProgramData\miniconda3\envs\openmmlab\Lib\site-packages\cv2\../../x64/vc14/bin;C:\ProgramData\miniconda3\envs\openmmlab;
> C:\ProgramData\miniconda3\envs\openmmlab\Library\mingw-w64\bin;
> C:\ProgramData\miniconda3\envs\openmmlab\Library\usr\bin;
> C:\ProgramData\miniconda3\envs\openmmlab\Library\bin;
> C:\ProgramData\miniconda3\envs\openmmlab\Scripts;
> C:\ProgramData\miniconda3\envs\openmmlab\bin;
> C:\ProgramData\miniconda3\condabin;
> C:\Python\Scripts;C:\Python;
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin;
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\libnvvp;
> C:\Windows\system32;
> C:\Windows;
> C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;
> C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
> C:\OpenCV\bin;C:\OpenCV\build\bin;
> C:\opencv\x64\vc15\bin;C:\Program Files (x86)\InstallAware X14;
> c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn;
> c:\Program Files\Microsoft SQL Server\100\Tools\Binn;
> c:\Program Files\Microsoft SQL Server\100\DTS\Binn;
> C:\Program Files\dotnet;
> C:\Program Files\Microsoft SQL Server\130\Tools\Binn;
> C:\Program Files\PuTTY;C:\vcpkg;
> C:\Program Files\OpenNI2\Samples\Bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;
> C:\Program Files\Git\cmd;
> C:\Program Files\CMake\bin;
> C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;
> C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.1;
> C:\Python\Scripts;
> C:\Python;C:\Users\lhu\AppData\Local\Microsoft\WindowsApps;
> C:\Users\lhu\.dotnet\tools;
> C:\TensorRT-8.5.1.7\lib;
> C:\TensorRT-8.5.1.7\bin;
> C:\ProgramData\miniconda3\Scripts;
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin;_

Any solution?

### Reproduction

` python .\mmdeploy\demo\python\image_classification.py cuda .\work_dir\trt\resnet\ .\mmclassification\demo\demo.JPEG`

### Environment

```Shell
02/24 14:10:42 - mmengine - INFO -

02/24 14:10:42 - mmengine - INFO - **********Environmental information**********
02/24 14:10:46 - mmengine - INFO - sys.platform: win32
02/24 14:10:46 - mmengine - INFO - Python: 3.8.16 (default, Jan 17 2023, 22:25:28) [MSC v.1916 64 bit (AMD64)]
02/24 14:10:46 - mmengine - INFO - CUDA available: True
02/24 14:10:46 - mmengine - INFO - numpy_random_seed: 2147483648
02/24 14:10:46 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3080 Ti
02/24 14:10:46 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
02/24 14:10:46 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.58
02/24 14:10:46 - mmengine - INFO - MSVC: Microsoft (R) C/C++ 최적화 컴파일러 버전 19.34.31937(x64)
02/24 14:10:46 - mmengine - INFO - GCC: n/a
02/24 14:10:46 - mmengine - INFO - PyTorch: 1.12.1
02/24 14:10:46 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

02/24 14:10:46 - mmengine - INFO - TorchVision: 0.13.1
02/24 14:10:46 - mmengine - INFO - OpenCV: 4.7.0
02/24 14:10:46 - mmengine - INFO - MMEngine: 0.5.0
02/24 14:10:46 - mmengine - INFO - MMCV: 2.0.0rc4
02/24 14:10:46 - mmengine - INFO - MMCV Compiler: MSVC 192829924
02/24 14:10:46 - mmengine - INFO - MMCV CUDA Compiler: 11.3
02/24 14:10:46 - mmengine - INFO - MMDeploy: 1.0.0rc0+b5fef48
02/24 14:10:46 - mmengine - INFO -

02/24 14:10:46 - mmengine - INFO - **********Backend information**********
Traceback (most recent call last):
  File "tools/check_env.py", line 45, in <module>
    check_backend()
  File "tools/check_env.py", line 19, in check_backend
    from mmdeploy.backend.base import get_backend_manager
ImportError: cannot import name 'get_backend_manager' from 'mmdeploy.backend.base' (C:\ProgramData\miniconda3\envs\openmmlab\lib\site-packages\mmdeploy\backend\base\__init__.py)
```

**Comment by xin-li-67** [comment]
Hi, have you tried to export PYTHONPATH after you ran `pip install -e .`?

**Comment by irexyc** [comment]
Hi, @HwanWoongLee  sorry for late reply. 

Have you installed `mmdeploy_python` wheel in `mmdeploy-xxx-windows-amd64-onnxruntime1.8.1.zip` previously ?

If so, you have to remove it first, or install wheel in `mmdeploy-xxx-windows-amd64-cuda11.1-tensorrt8.2.3.0.zip` through `pip install xx --force-reinstall`. If you only need tensorrt backend, you don't have to install wheel ``mmdeploy-xxx-windows-amd64-onnxruntime1.8.1.zip`

if not, you could use [this](https://github.com/lucasg/Dependencies/releases) tools to check dll dependencies of `mmdeploy_python.cpxx-win_amd64.pyd` located in `C:\ProgramData\miniconda3\envs\openmmlab\lib\site-packages\`

**Comment by HwanWoongLee** [comment]
> 
@irexyc 

Thank you for answer.
I did not install onnx related installation, only tensorrt related installation.

The `mmdeploy_python.cp38-win_amd64.pyd` file is located in the path` C:\ProgramData\miniconda3\envs\mmdeploy\Lib\site-packages\mmdeploy_python`.

Dependencies of the `mmdeploy_python.cp38-win_amd64.pyd` file do not seem to have any abnormalities.


![image](https://user-images.githubusercontent.com/20108771/224591292-6e33eb99-a0f0-45e4-8909-c256cec2ad4a.png)

----------------------------------------------------------------------------------------------------------------------

This is the result of mmdeploy_python importing.

> (mmdeploy) PS D:\openmmlab> python
Python 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
 import mmdeploy
 import mmdeploy_python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\miniconda3\envs\mmdeploy\lib\site-packages\mmdeploy_python\__init__.py", line 21, in <module>
    from .mmdeploy_python import *  # noqa
ImportError: DLL load failed while importing mmdeploy_python: 지정된 모듈을 찾을 수 없습니다.


Are there any other workarounds?
Thanks.

**Comment by irexyc** [comment]
Hi @HwanWoongLee

I test on my machine, it seems the pyd file depends on a specific python38.dll, I haven't found the reason yet.

For now, you could downgrade you python version to 3.8.13(We build mmdeploy_python on windows with this python version) or you could try this one(build with python 3.8.16)
https://drive.google.com/file/d/1R0C6KYcm6qG5fqK1OrVPkYuSxdAlXBCt/view?usp=sharing

**Comment by irexyc** [comment]
Hi @HwanWoongLee 

I figured out the problem, it's due to https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew

You may add dll path of cuda and tensort by `os.add_dll_directory` in `__init__.py` of mmdeploy_python.

We will update the file soon.

**Comment by irexyc** [comment]
Closed as new release is published and the error should be fixed
