### ISSUE TITLE
转engine模型报错

### ISSUE THREAD

**Issue by kc-w** [open-mmlab/mmdeploy#1815]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

onnx转engine报错

### Reproduction

    parser = argparse.ArgumentParser(description='Export model to backends.')
    parser.add_argument('--deploy_cfg',
                        default='E:/projectTest/mmdeploy1/configs/mmseg/segmentation_tensorrt-fp16_static-1024x1024.py',
                        help='deploy config path')
    parser.add_argument('--model_cfg',
                        default='C:/Users/wkc/Desktop/temp/MyBisentV1.py',
                        help='model config path')
    parser.add_argument('--checkpoint',
                        default='C:/Users/wkc/Desktop/temp/latest.pth',
                        help='model checkpoint path')
    parser.add_argument('--img',
                        default="D:/images/hanfeng/2022_11_28_16_16_18_893.bmp",
                        help='image used to convert model model')

### Environment

```Shell
D:\Python\Python39\python.exe E:/projectTest/mmdeploy-1.0.0rc1/tools/check_env.py
02/25 22:42:32 - mmengine - INFO - 

02/25 22:42:32 - mmengine - INFO - **********Environmental information**********
02/25 22:42:41 - mmengine - INFO - sys.platform: win32
02/25 22:42:41 - mmengine - INFO - Python: 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]
02/25 22:42:41 - mmengine - INFO - CUDA available: True
02/25 22:42:41 - mmengine - INFO - numpy_random_seed: 2147483648
02/25 22:42:41 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 1060
02/25 22:42:41 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
02/25 22:42:41 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.109
02/25 22:42:41 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30147 版
02/25 22:42:41 - mmengine - INFO - GCC: n/a
02/25 22:42:41 - mmengine - INFO - PyTorch: 1.11.0+cu113
02/25 22:42:41 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

02/25 22:42:41 - mmengine - INFO - TorchVision: 0.12.0+cu113
02/25 22:42:41 - mmengine - INFO - OpenCV: 4.5.3
02/25 22:42:41 - mmengine - INFO - MMEngine: 0.5.0
02/25 22:42:41 - mmengine - INFO - MMCV: 2.0.0rc4
02/25 22:42:41 - mmengine - INFO - MMCV Compiler: MSVC 192930147
02/25 22:42:41 - mmengine - INFO - MMCV CUDA Compiler: 11.3
02/25 22:42:41 - mmengine - INFO - MMDeploy: 1.0.0rc1+
02/25 22:42:41 - mmengine - INFO - 

02/25 22:42:41 - mmengine - INFO - **********Backend information**********
02/25 22:42:42 - mmengine - INFO - tensorrt:	8.4.1.5
02/25 22:42:42 - mmengine - INFO - tensorrt custom ops:	Available
02/25 22:42:43 - mmengine - INFO - ONNXRuntime:	1.13.1
02/25 22:42:43 - mmengine - INFO - ONNXRuntime-gpu:	None
02/25 22:42:43 - mmengine - INFO - ONNXRuntime custom ops:	NotAvailable
02/25 22:42:43 - mmengine - INFO - pplnn:	None
02/25 22:42:43 - mmengine - INFO - ncnn:	None
02/25 22:42:43 - mmengine - INFO - snpe:	None
02/25 22:42:43 - mmengine - INFO - openvino:	2022.1.0
02/25 22:42:43 - mmengine - INFO - torchscript:	1.11.0+cu113
02/25 22:42:43 - mmengine - INFO - torchscript custom ops:	NotAvailable
02/25 22:42:44 - mmengine - INFO - rknn-toolkit:	None
02/25 22:42:44 - mmengine - INFO - rknn2-toolkit:	None
02/25 22:42:44 - mmengine - INFO - ascend:	None
02/25 22:42:44 - mmengine - INFO - coreml:	None
02/25 22:42:44 - mmengine - INFO - tvm:	None
02/25 22:42:44 - mmengine - INFO - 

02/25 22:42:44 - mmengine - INFO - **********Codebase information**********
02/25 22:42:45 - mmengine - INFO - mmdet:	3.0.0rc5
02/25 22:42:45 - mmengine - INFO - mmseg:	1.0.0rc5
02/25 22:42:45 - mmengine - INFO - mmcls:	1.0.0rc5
02/25 22:42:45 - mmengine - INFO - mmocr:	None
02/25 22:42:45 - mmengine - INFO - mmedit:	None
02/25 22:42:45 - mmengine - INFO - mmdet3d:	None
02/25 22:42:45 - mmengine - INFO - mmpose:	None
02/25 22:42:45 - mmengine - INFO - mmrotate:	1.0.0rc1
02/25 22:42:45 - mmengine - INFO - mmaction:	None

Process finished with exit code 0
```

### Error traceback

```Shell
[02/25/2023-22:32:48] [TRT] [I] Input filename:   D:\mmdeploy-0.13.0\tools/work\end2end.onnx
[02/25/2023-22:32:48] [TRT] [I] ONNX IR version:  0.0.6
[02/25/2023-22:32:48] [TRT] [I] Opset version:    11
[02/25/2023-22:32:48] [TRT] [I] Producer name:    pytorch
[02/25/2023-22:32:48] [TRT] [I] Producer version: 1.11.0
[02/25/2023-22:32:48] [TRT] [I] Domain:           
[02/25/2023-22:32:48] [TRT] [I] Model version:    0
[02/25/2023-22:32:48] [TRT] [I] Doc string:       
[02/25/2023-22:32:48] [TRT] [I] ----------------------------------------------------------------
[02/25/2023-22:32:48] [TRT] [W] onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[02/25/2023-22:32:48] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
Process Process-3:
Traceback (most recent call last):
  File "D:\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\mmdeploy-0.13.0\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "D:\mmdeploy-0.13.0\mmdeploy\apis\utils\utils.py", line 95, in to_backend
    return backend_mgr.to_backend(
  File "D:\mmdeploy-0.13.0\mmdeploy\backend\tensorrt\backend_manager.py", line 129, in to_backend
    onnx2tensorrt(
  File "D:\mmdeploy-0.13.0\mmdeploy\backend\tensorrt\onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "D:\mmdeploy-0.13.0\mmdeploy\backend\tensorrt\utils.py", line 212, in from_onnx
    logger.warning('Platform does not has fast native fp16.')
AttributeError: 'tensorrt.tensorrt.Logger' object has no attribute 'warning'
2023-02-25 22:32:49,061 - mmdeploy - ERROR - `mmdeploy.apis.utils.utils.to_backend` with Call id: 1 failed. exit.
```

**Comment by kc-w** [comment]
转换fp16精度模型是否不兼容10系显卡?

**Comment by xin-li-67** [comment]
> 转换fp16精度模型是否不兼容10系显卡?

Hi, I did some research on this `Platform does not have fast native fp16` warning. According to this [link](https://forums.developer.nvidia.com/t/fp16-support-on-gtx-1060-and-1080/53256/2?u=xin.likfxeq), the 10th series does support FP16 but at a low rate. BTW, this warning should not be your main issue. The log right below this warning is the key. Maybe you need to consider reinstalling your trt to fix this problem.

**Comment by lvhan028** [comment]
10 series GPU (i.e. pascal architecture) doesn't support FP16 precision. 
As for the error "logger.warning('Platform does not has fast native fp16.')", it is because mmdeploy didn't use trt logger properly. 
A similar PR https://github.com/open-mmlab/mmdeploy/pull/1755 has resolved this issue on the master branch.
Could you please open another PR to fix it on dev-1.x branch?

**Comment by Joyphy** [comment]
> 10 series GPU (i.e. pascal architecture) doesn't support FP16 precision. As for the error "logger.warning('Platform does not has fast native fp16.')", it is because mmdeploy didn't use trt logger properly. A similar PR #1755 has resolved this issue on the master branch. Could you please open another PR to fix it on dev-1.x branch?

I also encountered the same issue. I used "log" instead of "warning" method to solve this problem. At the same time, I submitted a PR #1850  to dev-1.x branch.
