### ISSUE TITLE
[Bug] Inference onnx model using stand-alone onnxruntime library

### ISSUE THREAD

**Issue by dungng27** [open-mmlab/mmdeploy#1832]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I could not inference onnx model using stand-alone onnxruntime library after converting it by mmdeploy. This model is Rotated FCOS and was trained using mmrotate library. It has NMSRotated function in it.
It might be because NMSRotated has not been registered into onnxruntime library. How can i fix this issue? Or if i have to add this op into onnxruntime could you give me some document and tutorial?

### Reproduction

I run a script which has a part of code like this:
```
session = onnxruntime.InferenceSession(ckpt, providers=['CUDAExecutionProvider' if 'cuda' in device else 'CPUExecutionProvider'])

input_name = session.get_inputs()[0].name  
try:
    result = session.run(None, {input_name: img_pr})
except Exception as e:
        image = cv2.imread(image_path)
        image = cv2.resize(image, (256, 256))
        pred_image_path = osp.join('test_code/test_images', image_name)
        cv2.imwrite(pred_image_path, image)
        continue

session.register_custom_ops_library(ort_custom_op_path)
```
in which i load the onnx checkpoint after converting the model to onnx using mmdeploy. So i tried to inference the pretrained model using stand-alone onnxruntime library.

### Environment

```Shell
2023-03-06 02:53:07,598 - mmdeploy - INFO - 

2023-03-06 02:53:07,598 - mmdeploy - INFO - **********Environmental information**********
2023-03-06 02:53:07,764 - mmdeploy - INFO - sys.platform: linux
2023-03-06 02:53:07,764 - mmdeploy - INFO - Python: 3.8.13 (default, Oct 21 2022, 23:50:54) [GCC 11.2.0]
2023-03-06 02:53:07,764 - mmdeploy - INFO - CUDA available: True
2023-03-06 02:53:07,764 - mmdeploy - INFO - GPU 0: NVIDIA GeForce GTX 1660 SUPER
2023-03-06 02:53:07,764 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2023-03-06 02:53:07,764 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.124
2023-03-06 02:53:07,764 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2023-03-06 02:53:07,764 - mmdeploy - INFO - PyTorch: 1.11.0
2023-03-06 02:53:07,764 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

2023-03-06 02:53:07,764 - mmdeploy - INFO - TorchVision: 0.12.0
2023-03-06 02:53:07,764 - mmdeploy - INFO - OpenCV: 4.7.0
2023-03-06 02:53:07,764 - mmdeploy - INFO - MMCV: 1.7.0
2023-03-06 02:53:07,764 - mmdeploy - INFO - MMCV Compiler: GCC 9.3
2023-03-06 02:53:07,764 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2023-03-06 02:53:07,764 - mmdeploy - INFO - MMDeploy: 0.12.0+e8f222c
2023-03-06 02:53:07,764 - mmdeploy - INFO - 

2023-03-06 02:53:07,764 - mmdeploy - INFO - **********Backend information**********
2023-03-06 02:53:07,806 - mmdeploy - INFO - tensorrt:   8.2.4.2
2023-03-06 02:53:07,807 - mmdeploy - INFO - tensorrt custom ops:        NotAvailable
2023-03-06 02:53:07,835 - mmdeploy - INFO - ONNXRuntime:        1.8.1
2023-03-06 02:53:07,835 - mmdeploy - INFO - ONNXRuntime-gpu:    None
2023-03-06 02:53:07,835 - mmdeploy - INFO - ONNXRuntime custom ops:     Available
2023-03-06 02:53:07,837 - mmdeploy - INFO - pplnn:      None
2023-03-06 02:53:07,839 - mmdeploy - INFO - ncnn:       None
2023-03-06 02:53:07,842 - mmdeploy - INFO - snpe:       None
2023-03-06 02:53:07,843 - mmdeploy - INFO - openvino:   None
2023-03-06 02:53:07,844 - mmdeploy - INFO - torchscript:        1.11.0
2023-03-06 02:53:07,844 - mmdeploy - INFO - torchscript custom ops:     NotAvailable
2023-03-06 02:53:07,884 - mmdeploy - INFO - rknn-toolkit:       None
2023-03-06 02:53:07,884 - mmdeploy - INFO - rknn2-toolkit:      None
2023-03-06 02:53:07,886 - mmdeploy - INFO - ascend:     None
2023-03-06 02:53:07,887 - mmdeploy - INFO - coreml:     None
2023-03-06 02:53:07,888 - mmdeploy - INFO - tvm:        None
2023-03-06 02:53:07,888 - mmdeploy - INFO - 

2023-03-06 02:53:07,888 - mmdeploy - INFO - **********Codebase information**********
2023-03-06 02:53:08,747 - mmdeploy - INFO - mmdet:      2.28.1
2023-03-06 02:53:08,747 - mmdeploy - INFO - mmseg:      0.30.0
2023-03-06 02:53:08,747 - mmdeploy - INFO - mmcls:      0.25.0
2023-03-06 02:53:08,747 - mmdeploy - INFO - mmocr:      None
2023-03-06 02:53:08,747 - mmdeploy - INFO - mmedit:     None
2023-03-06 02:53:08,747 - mmdeploy - INFO - mmdet3d:    None
2023-03-06 02:53:08,747 - mmdeploy - INFO - mmpose:     None
2023-03-06 02:53:08,747 - mmdeploy - INFO - mmrotate:   0.3.3
2023-03-06 02:53:08,747 - mmdeploy - INFO - mmaction:   None
```

### Error traceback

```Shell
/opt/conda/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "test_code/inference_onnx.py", line 78, in <module>
    session = onnxruntime.InferenceSession(ckpt, providers=['CUDAExecutionProvider' if 'cuda' in device else 'CPUExecutionProvider'])
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 310, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /workspaces/PheNet_SLD/onnx_model/dethead/end2end.onnx failed:Fatal error: NMSRotated is not a registered function/op
```

**Comment by irexyc** [comment]
You have to register the custom ops before creating inference session

```
session_options = ort.SessionOptions()
session_options.register_custom_ops_library(ort_custom_op_path)
sess = ort.InferenceSession(
            onnx_file, session_options, providers=providers)
```

**Comment by dungng27** [comment]
> 

Thanks for your reply. But could i ask if i want to inference the model using C++ and onnxruntime library how could i do it without calling custom op library from mmdeploy onnxruntime?

**Comment by dungng27** [comment]
> You have to register the custom ops before creating inference session
> 
> ```
> session_options = ort.SessionOptions()
> session_options.register_custom_ops_library(ort_custom_op_path)
> sess = ort.InferenceSession(
>             onnx_file, session_options, providers=providers)
> ```
Thanks for your reply. But could i ask if i want to inference the model using C++ and onnxruntime library how could i do it without calling custom op library from mmdeploy onnxruntime?

**Comment by irexyc** [comment]
The official onnxruntime library doesn't provide `NMSRotated` op. Therefore, you have to register it.

**Comment by dungng27** [comment]
> The official onnxruntime library doesn't provide `NMSRotated` op. Therefore, you have to register it.

Thanks a lot.

**Comment by dungnq271** [comment]
> > The official onnxruntime library doesn't provide `NMSRotated` op. Therefore, you have to register it.
> 
> Thanks a lot.

Could you show me some links or docs to implement this op into the onnxruntime library?

**Comment by dungnq271** [comment]
> The official onnxruntime library doesn't provide `NMSRotated` op. Therefore, you have to register it.

Could you show me some links or docs to register this op into the onnxruntime library? Thanks.
