### ISSUE TITLE
[Bug] ImportError: so load failed while importing mmdeploy_python

### ISSUE THREAD

**Issue by wsxwd** [open-mmlab/mmdeploy#1834]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

successfully export *.engine file
```shell
python ./tools/deploy.py \
    configs/mmcls/classification_tensorrt_static-224x224.py \
    ../mmclassification/configs/resnet/resnet18_in1k-pre_8xb32-oursDA-ls_whitebaseimg.py \
    ../mmclassification/work_dirs/resnet18_in1k-pre_8xb32-oursDA-ls_whitebaseimg/epoch_13.pth \
    ../mmclassification/demo/dog.jpg \
    --test-img ../mmclassification/demo/dog.jpg \
    --work-dir mmcls_workdir \
    --device cuda:0 \
    --log-level INFO \
    --dump-info
```

i successfully infer *.engine by using by Model Converter, which is followed:
```python
from mmdeploy.apis import inference_model

result = inference_model(
    deploy_cfg='configs/mmcls/classification_tensorrt_static-224x224.py',
    model_cfg='../mmclassification/configs/resnet/resnet18_in1k-pre_8xb32-oursDA-ls_whitebaseimg.py',
    backend_files=['mmcls_workdir/end2end.engine'],
    img='../mmclassification/demo/demo.JPEG',
    device='cuda:0'
)
print(result)
```

but fail to inference using Python API

```python
# Copyright (c) OpenMMLab. All rights reserved.
import argparse

import cv2
from mmdeploy_python import Classifier


def parse_args():
    parser = argparse.ArgumentParser(
        description='show how to use sdk python api')
    parser.add_argument('device_name', help='name of device, cuda or cpu', default="cuda")
    parser.add_argument(
        'model_path',
        help='path of mmdeploy SDK model dumped by model converter', default="mmcls_workdir")
    parser.add_argument('image_path', help='path of an image', default="../mmclassification/demo/demo.JPEG")
    args = parser.parse_args()
    return args


def main():
    args = parse_args()

    img = cv2.imread(args.image_path)
    classifier = Classifier(
        model_path=args.model_path, device_name=args.device_name, device_id=0)
    result = classifier(img)
    for label_id, score in result:
        print(label_id, score)


if __name__ == '__main__':
    main()
```

### Reproduction

```python
# Copyright (c) OpenMMLab. All rights reserved.
import argparse

import cv2
from mmdeploy_python import Classifier


def parse_args():
    parser = argparse.ArgumentParser(
        description='show how to use sdk python api')
    parser.add_argument('device_name', help='name of device, cuda or cpu', default="cuda")
    parser.add_argument(
        'model_path',
        help='path of mmdeploy SDK model dumped by model converter', default="mmcls_workdir")
    parser.add_argument('image_path', help='path of an image', default="../mmclassification/demo/demo.JPEG")
    args = parser.parse_args()
    return args


def main():
    args = parse_args()

    img = cv2.imread(args.image_path)
    classifier = Classifier(
        model_path=args.model_path, device_name=args.device_name, device_id=0)
    result = classifier(img)
    for label_id, score in result:
        print(label_id, score)


if __name__ == '__main__':
    main()
```

### Environment

```Shell
2023-03-06 16:48:02,768 - mmdeploy - INFO -

2023-03-06 16:48:02,769 - mmdeploy - INFO - **********Environmental information**********
2023-03-06 16:48:03,796 - mmdeploy - INFO - sys.platform: linux
2023-03-06 16:48:03,796 - mmdeploy - INFO - Python: 3.8.15 (default, Nov 24 2022, 15:19:38) [GCC 11.2.0]
2023-03-06 16:48:03,797 - mmdeploy - INFO - CUDA available: True
2023-03-06 16:48:03,797 - mmdeploy - INFO - GPU 0,1,2,3,4,5,6,7: A100-SXM4-40GB
2023-03-06 16:48:03,797 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda-11
2023-03-06 16:48:03,797 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.2, V11.2.152
2023-03-06 16:48:03,797 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2023-03-06 16:48:03,797 - mmdeploy - INFO - PyTorch: 1.12.1+cu113
2023-03-06 16:48:03,797 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2.1
    - Built with CuDNN 8.3.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

2023-03-06 16:48:03,797 - mmdeploy - INFO - TorchVision: 0.13.1+cu113
2023-03-06 16:48:03,797 - mmdeploy - INFO - OpenCV: 4.4.0
2023-03-06 16:48:03,797 - mmdeploy - INFO - MMCV: 1.5.0
2023-03-06 16:48:03,797 - mmdeploy - INFO - MMCV Compiler: GCC 9.4
2023-03-06 16:48:03,797 - mmdeploy - INFO - MMCV CUDA Compiler: 11.2
2023-03-06 16:48:03,797 - mmdeploy - INFO - MMDeploy: 0.13.0+02d5a09
2023-03-06 16:48:03,798 - mmdeploy - INFO -

2023-03-06 16:48:03,798 - mmdeploy - INFO - **********Backend information**********
2023-03-06 16:48:04,004 - mmdeploy - INFO - tensorrt:	8.2.3.0
2023-03-06 16:48:04,005 - mmdeploy - INFO - tensorrt custom ops:	Available
2023-03-06 16:48:04,333 - mmdeploy - INFO - ONNXRuntime:	1.8.1
2023-03-06 16:48:04,333 - mmdeploy - INFO - ONNXRuntime-gpu:	None
2023-03-06 16:48:04,333 - mmdeploy - INFO - ONNXRuntime custom ops:	NotAvailable
2023-03-06 16:48:04,337 - mmdeploy - INFO - pplnn:	None
2023-03-06 16:48:04,346 - mmdeploy - INFO - ncnn:	None
2023-03-06 16:48:04,353 - mmdeploy - INFO - snpe:	None
2023-03-06 16:48:04,358 - mmdeploy - INFO - openvino:	None
2023-03-06 16:48:04,367 - mmdeploy - INFO - torchscript:	1.12.1+cu113
2023-03-06 16:48:04,368 - mmdeploy - INFO - torchscript custom ops:	NotAvailable
2023-03-06 16:48:04,618 - mmdeploy - INFO - rknn-toolkit:	None
2023-03-06 16:48:04,618 - mmdeploy - INFO - rknn2-toolkit:	None
2023-03-06 16:48:04,624 - mmdeploy - INFO - ascend:	None
2023-03-06 16:48:04,629 - mmdeploy - INFO - coreml:	None
2023-03-06 16:48:04,634 - mmdeploy - INFO - tvm:	None
2023-03-06 16:48:04,634 - mmdeploy - INFO -

2023-03-06 16:48:04,634 - mmdeploy - INFO - **********Codebase information**********
2023-03-06 16:48:04,673 - mmdeploy - INFO - mmdet:	2.24.1
2023-03-06 16:48:04,674 - mmdeploy - INFO - mmseg:	None
2023-03-06 16:48:04,674 - mmdeploy - INFO - mmcls:	0.25.0
2023-03-06 16:48:04,675 - mmdeploy - INFO - mmocr:	None
2023-03-06 16:48:04,675 - mmdeploy - INFO - mmedit:	None
2023-03-06 16:48:04,675 - mmdeploy - INFO - mmdet3d:	None
2023-03-06 16:48:04,675 - mmdeploy - INFO - mmpose:	0.25.1
2023-03-06 16:48:04,675 - mmdeploy - INFO - mmrotate:	None
2023-03-06 16:48:04,675 - mmdeploy - INFO - mmaction:	None
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "inference.py", line 17, in <module>
    from mmdeploy_python import Classifier
  File "/nfs/miniconda3/envs/data_cleaner/lib/python3.8/site-packages/mmdeploy_python/__init__.py", line 21, in <module>
    from .mmdeploy_python import *  # noqa
ImportError: libopencv_video.so.4.2: cannot open shared object file: No such file or directory
```

**Comment by irexyc** [comment]
Hi @wsxwd , are you using the prebuilt package from https://github.com/open-mmlab/mmdeploy/releases or you build mmdeploy_python yourself?

**Comment by wsxwd** [comment]
> Hi @wsxwd , are you using the prebuilt package from https://github.com/open-mmlab/mmdeploy/releases or you build mmdeploy_python yourself?

I am using the prebuilt package from https://github.com/open-mmlab/mmdeploy/releases

**Comment by irexyc** [comment]
The version you used seems built with dynamic opencv library which is inappropriate. 

You could use the the newest one https://github.com/open-mmlab/mmdeploy/releases/tag/v1.0.0rc3 which won't have opencv dependencies。

**Comment by wsxwd** [comment]
> The version you used seems built with dynamic opencv library which is inappropriate.
> 
> You could use the the newest one https://github.com/open-mmlab/mmdeploy/releases/tag/v1.0.0rc3 which won't have opencv dependencies。

Thanks, I'll try it

**Comment by wsxwd** [comment]
> The version you used seems built with dynamic opencv library which is inappropriate.
> 
> You could use the the newest one https://github.com/open-mmlab/mmdeploy/releases/tag/v1.0.0rc3 which won't have opencv dependencies。

```python
from mmdeploy.apis import inference_model

result = inference_model(
    deploy_cfg='configs/mmcls/classification_tensorrt_static-224x224.py',
    model_cfg='../mmclassification/configs/resnet/resnet18_in1k-pre_8xb32-oursDA-ls_whitebaseimg.py',
    backend_files=['mmcls_workdir/end2end.engine'],
    img='../mmclassification/demo/demo.JPEG',
    device='cuda:0'
)
print(result)


# Copyright (c) OpenMMLab. All rights reserved.
import argparse

import cv2
from mmdeploy_python import Classifier


def parse_args():
    parser = argparse.ArgumentParser(
        description='show how to use sdk python api')
    parser.add_argument('--device_name', help='name of device, cuda or cpu', default="cuda")
    parser.add_argument(
        '--model_path',
        help='path of mmdeploy SDK model dumped by model converter', default="mmcls_workdir")
    parser.add_argument('--image_path', help='path of an image', default="../mmclassification/demo/demo.JPEG")
    args = parser.parse_args()
    return args


def main():
    args = parse_args()

    img = cv2.imread(args.image_path)
    classifier = Classifier(
        model_path=args.model_path, device_name=args.device_name, device_id=0)
    result = classifier(img)
    for label_id, score in result:
        print(label_id, score)


if __name__ == '__main__':
    main()
```

Model Converter result is different from Python API result

Model Converter result
[array([[0.0753378 , 0.92466223]], dtype=float32)]

Python API result
1 0.8676138520240784
0 0.13238611817359924

**Comment by irexyc** [comment]
Could you provide your `model_cfg` and `pipeline.json` in `mmcls_workdir`

**Comment by irexyc** [comment]
Hi, @wsxwd 

I think the problem is due to the wrong `normalize` op in sdk. This [pr](https://github.com/open-mmlab/mmdeploy/commit/c94104515601ff20afc2cbbe70cb0ccb241bc5cc) fixed it.

If you build mmdeploy yourself, you could build the master branch, or if you use the prebuild package, you could use mmdeploy_python in [this one](https://github.com/open-mmlab/mmdeploy/releases/tag/v1.0.0rc3) the python apis are the same.
