### ISSUE TITLE
[Bug] RTMdet onnxruntime deploy bug

### ISSUE THREAD

**Issue by Youcunl** [open-mmlab/mmdeploy#1886]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

[https://github.com/open-mmlab/mmdeploy/blob/637958a910ed99640009a82631d35d759c54050f/mmdeploy/codebase/mmdet/models/dense_heads/rtmdet_ins_head.py#L170](url)

pad dets and labels cause the IndexError

### Reproduction

python tools/deploy.py configs/mmdet/instance-seg/instance-seg_rtmdet-ins_onnxruntime_static-640x640.py  ../rtmdet/configs/rtmdet/rtmdet-ins_tiny_8xb32-300e_fashionpedia_plus.py ../rtmdet/work_dirs/rtmdet-ins_tiny_8xb32-300e_fashionpedia_plus/epoch_90.pth /mnt/workspace/lyc/data/aws_shoes/img/000167f36019487bb7399ae83b437e61.jpg 

### Environment

```Shell
03/17 03:38:19 - mmengine - INFO - 

03/17 03:38:19 - mmengine - INFO - **********Environmental information**********
03/17 03:38:20 - mmengine - INFO - sys.platform: linux
03/17 03:38:20 - mmengine - INFO - Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
03/17 03:38:20 - mmengine - INFO - CUDA available: True
03/17 03:38:20 - mmengine - INFO - numpy_random_seed: 2147483648
03/17 03:38:20 - mmengine - INFO - GPU 0: Tesla V100-SXM2-32GB
03/17 03:38:20 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
03/17 03:38:20 - mmengine - INFO - NVCC: Cuda compilation tools, release 10.1, V10.1.24
03/17 03:38:20 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
03/17 03:38:20 - mmengine - INFO - PyTorch: 1.13.1+cu117
03/17 03:38:20 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

03/17 03:38:20 - mmengine - INFO - OpenCV: 4.7.0
03/17 03:38:20 - mmengine - INFO - MMEngine: 0.6.0
03/17 03:38:20 - mmengine - INFO - MMCV: 2.0.0rc4
03/17 03:38:20 - mmengine - INFO - MMCV Compiler: GCC 9.3
03/17 03:38:20 - mmengine - INFO - MMCV CUDA Compiler: 11.7
03/17 03:38:20 - mmengine - INFO - MMDeploy: 1.0.0rc3+637958a
03/17 03:38:20 - mmengine - INFO - 

03/17 03:38:20 - mmengine - INFO - **********Backend information**********
03/17 03:38:20 - mmengine - INFO - tensorrt:    8.2.3.0
03/17 03:38:20 - mmengine - INFO - tensorrt custom ops: NotAvailable
03/17 03:38:20 - mmengine - INFO - ONNXRuntime: None
03/17 03:38:20 - mmengine - INFO - ONNXRuntime-gpu:     1.14.1
03/17 03:38:20 - mmengine - INFO - ONNXRuntime custom ops:      Available
03/17 03:38:20 - mmengine - INFO - pplnn:       None
03/17 03:38:20 - mmengine - INFO - ncnn:        None
03/17 03:38:20 - mmengine - INFO - snpe:        None
03/17 03:38:20 - mmengine - INFO - openvino:    None
03/17 03:38:20 - mmengine - INFO - torchscript: 1.13.1
03/17 03:38:20 - mmengine - INFO - torchscript custom ops:      NotAvailable
03/17 03:38:20 - mmengine - INFO - rknn-toolkit:        None
03/17 03:38:20 - mmengine - INFO - rknn-toolkit2:       None
03/17 03:38:20 - mmengine - INFO - ascend:      None
03/17 03:38:20 - mmengine - INFO - coreml:      None
03/17 03:38:20 - mmengine - INFO - tvm: None
03/17 03:38:20 - mmengine - INFO - 

03/17 03:38:20 - mmengine - INFO - **********Codebase information**********
03/17 03:38:20 - mmengine - INFO - mmdet:       3.0.0rc6
03/17 03:38:20 - mmengine - INFO - mmseg:       None
03/17 03:38:20 - mmengine - INFO - mmcls:       None
03/17 03:38:20 - mmengine - INFO - mmocr:       None
03/17 03:38:20 - mmengine - INFO - mmedit:      None
03/17 03:38:20 - mmengine - INFO - mmdet3d:     None
03/17 03:38:20 - mmengine - INFO - mmpose:      None
03/17 03:38:20 - mmengine - INFO - mmrotate:    None
03/17 03:38:20 - mmengine - INFO - mmaction:    None
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/home/pai/envs/rtmdet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/pai/envs/rtmdet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/apis/onnx/export.py", line 131, in export
    torch.onnx.export(
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/apis/onnx/optimizer.py", line 11, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/apis/onnx/export.py", line 123, in wrapper
    return forward(*arg, **kwargs)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/models/detectors/single_stage.py", line 89, in single_stage_detector__forward
    return __forward_impl(self, batch_inputs, data_samples=data_samples)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/core/optimizers/function_marker.py", line 266, in g
    rets = f(*args, **kwargs)
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/models/detectors/single_stage.py", line 24, in __forward_impl
    output = self.bbox_head.predict(x, data_samples, rescale=False)
  File "/mnt/workspace/lyc/rtmdet/mmdet/models/dense_heads/base_dense_head.py", line 197, in predict
    predictions = self.predict_by_feat(
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/models/dense_heads/rtmdet_ins_head.py", line 102, in rtmdet_ins_head__predict_by_feat
    return _nms_with_mask_static(self, priors, bboxes, scores,
  File "/home/pai/envs/rtmdet/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/models/dense_heads/rtmdet_ins_head.py", line 202, in _nms_with_mask_static
    kernels = kernels[:, topk_inds, ...]
IndexError: index 4 is out of bounds for dimension 0 with size 4
```

**Comment by hanrui1sensetime** [comment]
Try #1884 please.
