### ISSUE TITLE
[Bug] convert cascade_mask_rcnn_convnext to tensorrt failed

### ISSUE THREAD

**Issue by Weiyun1025** [open-mmlab/mmdeploy#1896]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

An error is reported when trying to convert `cascade_mask_rcnn_convnext` to a tensorrt model:
> File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/codebase/mmdet/models/roi_heads/cascade_roi_head.py", line 167, in cascade_roi_head__simple_test
    bbox_pred = bbox_pred.reshape(batch_size, num_proposals_per_img, 4)
RuntimeError: shape '[1, 1000, 4]' is invalid for input of size 320000

The reason for this issue should be that the`cascade_roi_head__simple_test` function in `mmdeploy.codebase.mmdet.models.roi_heads.cascade_roi_head` assumes `reg_class_agnostic=True`, while `reg_class_agnostic=False` for `cascade_mask_rcnn_convnext`.

How should I solve this issue?

### Reproduction

```shell
MODEL="cascade_mask_rcnn_convnext-t_p4_w7_fpn_giou_4conv1f_fp16_ms-crop_3x_coco"

python deploy.py \
    "./deploy_configs/mmdet/instance-seg/instance-seg_tensorrt_dynamic-320x320-1344x1344.py" \
    "./det_configs/coco/${MODEL}.py" \
    "./ckpt/internimage/det/${MODEL}.pth" \
    "./demo.jpg" \
    --work-dir "./work_dirs/mmdet/instance-seg/${MODEL}" \
    --device cuda \
    --dump-info
```

### Environment

```Shell
2023-03-20 17:45:52,850 - mmdeploy - INFO - 

2023-03-20 17:45:52,850 - mmdeploy - INFO - **********Environmental information**********
2023-03-20 17:45:54,153 - mmdeploy - INFO - sys.platform: linux
2023-03-20 17:45:54,153 - mmdeploy - INFO - Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
2023-03-20 17:45:54,153 - mmdeploy - INFO - CUDA available: False
2023-03-20 17:45:54,153 - mmdeploy - INFO - GCC: gcc (GCC) 9.4.0
2023-03-20 17:45:54,153 - mmdeploy - INFO - PyTorch: 1.11.0+cu113
2023-03-20 17:45:54,153 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

2023-03-20 17:45:54,154 - mmdeploy - INFO - TorchVision: 0.12.0+cu113
2023-03-20 17:45:54,154 - mmdeploy - INFO - OpenCV: 4.7.0
2023-03-20 17:45:54,154 - mmdeploy - INFO - MMCV: 1.5.0
2023-03-20 17:45:54,154 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2023-03-20 17:45:54,154 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2023-03-20 17:45:54,154 - mmdeploy - INFO - MMDeploy: 0.13.0+34c6866
2023-03-20 17:45:54,154 - mmdeploy - INFO - 

2023-03-20 17:45:54,154 - mmdeploy - INFO - **********Backend information**********
2023-03-20 17:45:54,459 - mmdeploy - INFO - tensorrt:   8.2.4.2
2023-03-20 17:45:54,460 - mmdeploy - INFO - tensorrt custom ops:        Available
2023-03-20 17:45:54,552 - mmdeploy - INFO - ONNXRuntime:        1.8.1
2023-03-20 17:45:54,552 - mmdeploy - INFO - ONNXRuntime-gpu:    None
2023-03-20 17:45:54,552 - mmdeploy - INFO - ONNXRuntime custom ops:     NotAvailable
2023-03-20 17:45:54,562 - mmdeploy - INFO - pplnn:      None
2023-03-20 17:45:54,581 - mmdeploy - INFO - ncnn:       None
2023-03-20 17:45:54,602 - mmdeploy - INFO - snpe:       None
2023-03-20 17:45:54,610 - mmdeploy - INFO - openvino:   None
2023-03-20 17:45:54,617 - mmdeploy - INFO - torchscript:        1.11.0+cu113
2023-03-20 17:45:54,619 - mmdeploy - INFO - torchscript custom ops:     NotAvailable
2023-03-20 17:45:54,691 - mmdeploy - INFO - rknn-toolkit:       None
2023-03-20 17:45:54,691 - mmdeploy - INFO - rknn2-toolkit:      None
2023-03-20 17:45:54,702 - mmdeploy - INFO - ascend:     None
2023-03-20 17:45:54,711 - mmdeploy - INFO - coreml:     None
2023-03-20 17:45:54,720 - mmdeploy - INFO - tvm:        None
2023-03-20 17:45:54,720 - mmdeploy - INFO - 

2023-03-20 17:45:54,720 - mmdeploy - INFO - **********Codebase information**********
2023-03-20 17:45:54,732 - mmdeploy - INFO - mmdet:      2.28.1
2023-03-20 17:45:54,732 - mmdeploy - INFO - mmseg:      0.30.0
2023-03-20 17:45:54,732 - mmdeploy - INFO - mmcls:      0.25.0
2023-03-20 17:45:54,732 - mmdeploy - INFO - mmocr:      None
2023-03-20 17:45:54,732 - mmdeploy - INFO - mmedit:     None
2023-03-20 17:45:54,732 - mmdeploy - INFO - mmdet3d:    None
2023-03-20 17:45:54,732 - mmdeploy - INFO - mmpose:     None
2023-03-20 17:45:54,732 - mmdeploy - INFO - mmrotate:   None
2023-03-20 17:45:54,732 - mmdeploy - INFO - mmaction:   None
```

### Error traceback

```Shell
/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
2023-03-20 17:51:25,371 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/mmdet/apis/inference.py:51: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
2023-03-20 17:51:34,280 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2023-03-20 17:51:34,280 - mmdeploy - INFO - Export PyTorch model to ONNX: ./work_dirs/mmdet/instance-seg/cascade_mask_rcnn_convnext-t_p4_w7_fpn_giou_4conv1f_fp16_ms-crop_3x_coco/end2end.onnx.
2023-03-20 17:51:34,543 - mmdeploy - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
2023-03-20 17:51:34,547 - mmdeploy - WARNING - Can not find torch._C._jit_pass_onnx_deduplicate_initializers, function rewrite will not be applied
/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/mmdet/core/anchor/anchor_generator.py:333: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/mmdet/core/anchor/anchor_generator.py:370: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '
/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py:79: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/pytorch/functions/topk.py:58: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k > size:
/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/codebase/mmdet/deploy/utils.py:93: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(max_shape) == 2, '`max_shape` should be [h, w]'
/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:268: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  dets, labels = TRTBatchedNMSop.apply(boxes, scores, int(scores.shape[-1]),
/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/mmcv/ops/nms.py:143: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out_boxes = min(num_boxes, after_topk)
/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/mmcv/ops/nms.py:146: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  (batch_size, out_boxes)).to(scores.device))
/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/codebase/mmdet/models/roi_heads/cascade_roi_head.py:142: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert proposals.shape[0] == 1, 'Only support one input image ' \
Process Process-2:
Traceback (most recent call last):
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 111, in torch2onnx
    optimize=optimize)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/apis/onnx/export.py", line 132, in export
    verbose=verbose)
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/onnx/__init__.py", line 309, in export
    export_modules_as_functions)
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/onnx/utils.py", line 122, in export
    custom_opsets=custom_opsets, export_modules_as_functions=export_modules_as_functions)
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/onnx/utils.py", line 724, in _export
    dynamic_axes=dynamic_axes)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 402, in wrapper
    return self.func(self, *args, **kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/apis/onnx/optimizer.py", line 10, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/onnx/utils.py", line 499, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/onnx/utils.py", line 440, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/onnx/utils.py", line 391, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/jit/_trace.py", line 132, in forward
    self._force_outplace,
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/petrelfs/wangweiyun/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 402, in wrapper
    return self.func(self, *args, **kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/base.py", line 70, in base_detector__forward
    return __forward_impl(ctx, self, img, img_metas=img_metas, **kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/core/optimizers/function_marker.py", line 261, in g
    rets = f(*args, **kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/base.py", line 26, in __forward_impl
    return self.simple_test(img, img_metas, **kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 402, in wrapper
    return self.func(self, *args, **kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/two_stage.py", line 59, in two_stage_detector__simple_test
    return self.roi_head.simple_test(x, proposals, img_metas, rescale=False)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 402, in wrapper
    return self.func(self, *args, **kwargs)
  File "/mnt/petrelfs/wangweiyun/pkgs/mmdeploy/mmdeploy/codebase/mmdet/models/roi_heads/cascade_roi_head.py", line 167, in cascade_roi_head__simple_test
    bbox_pred = bbox_pred.reshape(batch_size, num_proposals_per_img, 4)
RuntimeError: shape '[1, 1000, 4]' is invalid for input of size 320000
2023-03-20 17:51:36,578 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
srun: error: SH-IDC1-10-140-37-6: task 0: Exited with exit code 1
```

**Comment by Weiyun1025** [comment]
Thanks for the pull request of @irexyc, which successfully solves this issue.
