### ISSUE TITLE
[Bug] scope_name should be a string, but got None

### ISSUE THREAD

**Issue by happybear1015** [open-mmlab/mmdeploy#1971]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

AssertionError: class `ObjectDetection` in mmdeploy/codebase/mmdet/deploy/object_detection.py: scope_name should be a string, but got None
04/08 14:47:33 - mmengine - ERROR - D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

### Reproduction

python tools/deploy.py configs/mmdet/instance-seg/instance-seg_openvino_dynamic-800x1344.py ./test_dir/mask_rcnn_r101_fpn_2x_coco.py ./test_dir/epoch_4.pth ./test_dir/2ban_34500.jpg --work-dir work_dir --device cpu --log-level INFO --show

### Environment

```Shell
04/08 14:50:37 - mmengine - INFO - **********Environmental information**********
D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\torch\cuda\__init__.py:143: UserWarning: 
NVIDIA GeForce RTX 3050 Ti Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3050 Ti Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: Could not find module 'D:\anaconda\envs\openvino_torch_gpu\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")
04/08 14:50:41 - mmengine - INFO - sys.platform: win32
04/08 14:50:41 - mmengine - INFO - Python: 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)]
04/08 14:50:41 - mmengine - INFO - CUDA available: True
04/08 14:50:41 - mmengine - INFO - numpy_random_seed: 2147483648
04/08 14:50:41 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3050 Ti Laptop GPU
04/08 14:50:41 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
04/08 14:50:41 - mmengine - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.8
04/08 14:50:41 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.35.32215 版
04/08 14:50:41 - mmengine - INFO - GCC: n/a
04/08 14:50:41 - mmengine - INFO - PyTorch: 1.10.1
04/08 14:50:41 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX512
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 

04/08 14:50:41 - mmengine - INFO - TorchVision: 0.11.2
04/08 14:50:41 - mmengine - INFO - OpenCV: 4.7.0
04/08 14:50:41 - mmengine - INFO - MMEngine: 0.7.2
04/08 14:50:41 - mmengine - INFO - MMCV: 2.0.0rc4
04/08 14:50:41 - mmengine - INFO - MMCV Compiler: MSVC 192829924
04/08 14:50:41 - mmengine - INFO - MMCV CUDA Compiler: 10.2
04/08 14:50:41 - mmengine - INFO - MMDeploy: 1.0.0+4bb9bc7
04/08 14:50:41 - mmengine - INFO - 

04/08 14:50:41 - mmengine - INFO - **********Backend information**********
04/08 14:50:41 - mmengine - INFO - tensorrt:	None
04/08 14:50:41 - mmengine - INFO - ONNXRuntime:	1.8.1
04/08 14:50:41 - mmengine - INFO - ONNXRuntime-gpu:	None
04/08 14:50:41 - mmengine - INFO - ONNXRuntime custom ops:	NotAvailable
04/08 14:50:41 - mmengine - INFO - pplnn:	None
04/08 14:50:41 - mmengine - INFO - ncnn:	None
04/08 14:50:41 - mmengine - INFO - snpe:	None
04/08 14:50:41 - mmengine - INFO - openvino:	2022.3.0
04/08 14:50:41 - mmengine - INFO - torchscript:	1.10.1
04/08 14:50:41 - mmengine - INFO - torchscript custom ops:	NotAvailable
04/08 14:50:41 - mmengine - INFO - rknn-toolkit:	None
04/08 14:50:41 - mmengine - INFO - rknn-toolkit2:	None
04/08 14:50:41 - mmengine - INFO - ascend:	None
04/08 14:50:41 - mmengine - INFO - coreml:	None
04/08 14:50:41 - mmengine - INFO - tvm:	None
04/08 14:50:41 - mmengine - INFO - vacc:	None
04/08 14:50:41 - mmengine - INFO - 

04/08 14:50:41 - mmengine - INFO - **********Codebase information**********
04/08 14:50:41 - mmengine - INFO - mmdet:	3.0.0
04/08 14:50:41 - mmengine - INFO - mmseg:	None
04/08 14:50:41 - mmengine - INFO - mmcls:	None
04/08 14:50:41 - mmengine - INFO - mmocr:	None
04/08 14:50:41 - mmengine - INFO - mmedit:	None
04/08 14:50:41 - mmengine - INFO - mmdet3d:	None
04/08 14:50:41 - mmengine - INFO - mmpose:	None
04/08 14:50:41 - mmengine - INFO - mmrotate:	None
04/08 14:50:41 - mmengine - INFO - mmaction:	None
04/08 14:50:41 - mmengine - INFO - mmrazor:	None

Process finished with exit code 0
```

### Error traceback

```Shell
(openvino_torch_gpu) C:\Users\15135\Desktop\deal_2\new\mmdeploy>python tools/deploy.py configs/mmdet/detection/detection_openvino_dynamic-300x300.py ./test_dir/mask_rcnn_r101_fpn_2x_coco.py ./test_dir/epoch_4.pth ./test_dir/2ban_34500.jpg --work-dir work_dir --device cpu --log-level INFO --show
04/08 14:46:16 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
obj==: <mmdeploy.codebase.mmdet.deploy.object_detection.MMDetection object at 0x0000023C791211F0>
04/08 14:46:17 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.      
obj==: <mmdeploy.codebase.mmdet.deploy.object_detection.MMDetection object at 0x0000023C791211F0>
04/08 14:46:17 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.  
obj==: <mmdeploy.codebase.mmdet.deploy.object_detection.MMDetection object at 0x0000023C7FFB1760>
Process Process-2:
Traceback (most recent call last):
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmdeploy\codebase\mmdet\deploy\object_detection.py", line 132, in __init__
    super().__init__(model_cfg, deploy_cfg, device)
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmdeploy\codebase\base\task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmengine\utils\manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmengine\registry\default_scope.py", line 35, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\openvino_torch_gpu\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\anaconda\envs\openvino_torch_gpu\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmdeploy\codebase\base\mmcodebase.py", line 45, in build_task_processor
    return cls.task_registry.build(
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmengine\registry\registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmengine\registry\build_functions.py", line 136, in build_from_cfg
    raise type(e)(
AssertionError: class `ObjectDetection` in mmdeploy/codebase/mmdet/deploy/object_detection.py: scope_name should be a string, but got None
04/08 14:46:17 - mmengine - ERROR - D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

(openvino_torch_gpu) C:\Users\15135\Desktop\deal_2\new\mmdeploy>python tools/deploy.py configs/mmdet/instance-seg/instance-seg_openvino_dynamic-800x1344.py ./test_dir/mask_rcnn_r101_fpn_2x_coco.py ./test_dir/epoch_4.pth ./test_dir/2ban_34500.jpg --work-dir work_dir --device cpu --log-level INFO --show
04/08 14:47:32 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
obj==: <mmdeploy.codebase.mmdet.deploy.object_detection.MMDetection object at 0x000001A848732340>
04/08 14:47:32 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
obj==: <mmdeploy.codebase.mmdet.deploy.object_detection.MMDetection object at 0x000001A848732340>
04/08 14:47:32 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.  
obj==: <mmdeploy.codebase.mmdet.deploy.object_detection.MMDetection object at 0x000001A860590790>
Process Process-2:
Traceback (most recent call last):
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmdeploy\codebase\mmdet\deploy\object_detection.py", line 132, in __init__
    super().__init__(model_cfg, deploy_cfg, device)
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmdeploy\codebase\base\task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmengine\utils\manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmengine\registry\default_scope.py", line 35, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\openvino_torch_gpu\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\anaconda\envs\openvino_torch_gpu\lib\multiprocessing\process.py", line 108, in run
    raise type(e)(
AssertionError: class `ObjectDetection` in mmdeploy/codebase/mmdet/deploy/object_detection.py: scope_name should be a string, but got None
04/08 14:47:33 - mmengine - ERROR - D:\anaconda\envs\openvino_torch_gpu\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by irexyc** [comment]
Please provide the content of `./test_dir/mask_rcnn_r101_fpn_2x_coco.py`,  it shoud contains `default_scope = 'mmdet'`
