### ISSUE TITLE
How to invoke inference_model(model_cfg, deploy_cfg, backend_models, img=frame, device=device)?

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [open-mmlab/mmdeploy#200]
I converted the ssd_mobilenet model with following command and got some files within a folder

` python "$MMDEPLOY_DIR"/tools/deploy.py    "$MMDEPLOY_DIR"/configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py     "$MMPose_Det"/configs/ssd/ssdlite_mobilenetv2_scratch_600e_coco.py     "$CHECKPOINT_DIR"/ssdlite_mobilenetv2_scratch_600e_coco_20210629_110627-974d9307.pth     demo.jpg     --work-dir ./tensorrt     --device cuda:0     --dump-info
`

Then  I tried to do the inference with `inference_model` within a python file. The code is following.

```
import mmcv
from mmdeploy.apis import inference_model

video_path='resources/test.mp4'

video = mmcv.VideoReader(video_path)
assert video.opened, f'Failed to load video file {video_path}'


det_checkpoint='checkpoints/ssdlite_mobilenetv2_scratch_600e_coco_20210629_110627-974d9307.pth'
model_cfg='configs/ssd/ssdlite_mobilenetv2_scratch_600e_coco.py'
deploy_cfg='configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py'
backend_models='checkpoints/tensorrt/end2end.engine'
device='cuda:0'

for frame in video:
    result = inference_model(model_cfg, deploy_cfg, backend_models, img=frame, device=device)
    print(result)
```

I got following error.
```
2022-03-02 04:18:04,221 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /media/luhee/MY FILES/FYP/MMDeploy/build/lib/libmmdeploy_tensorrt_ops.so
2022-03-02 04:18:04,221 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /media/luhee/MY FILES/FYP/MMDeploy/build/lib/libmmdeploy_tensorrt_ops.so
Traceback (most recent call last):
  File "deploy_test.py", line 17, in <module>
    result = inference_model(model_cfg, deploy_cfg, backend_models, img=frame, device=device)
  File "/media/luhee/MY FILES/FYP/MMDeploy/mmdeploy/apis/inference.py", line 33, in inference_model
    model = task_processor.init_backend_model(backend_files)
  File "/media/luhee/MY FILES/FYP/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 74, in init_backend_model
    model_files, self.model_cfg, self.deploy_cfg, device=self.device)
  File "/media/luhee/MY FILES/FYP/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 737, in build_object_detection_model
    **kwargs)
  File "/home/luhee/anaconda3/envs/fyp3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/media/luhee/MY FILES/FYP/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 34, in __build_backend_model
    **kwargs)
  File "/media/luhee/MY FILES/FYP/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 64, in __init__
    backend=backend, backend_files=backend_files, device=device)
  File "/media/luhee/MY FILES/FYP/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 82, in _init_wrapper
    deploy_cfg=self.deploy_cfg)
  File "/media/luhee/MY FILES/FYP/MMDeploy/mmdeploy/codebase/base/backend_model.py", line 61, in _build_wrapper
    engine=backend_files[0], output_names=output_names)
  File "/media/luhee/MY FILES/FYP/MMDeploy/mmdeploy/backend/tensorrt/wrapper.py", line 44, in __init__
    self.engine = load_trt_engine(engine)
  File "/media/luhee/MY FILES/FYP/MMDeploy/mmdeploy/backend/tensorrt/utils.py", line 142, in load_trt_engine
    with open(path, mode='rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'c'
```
**Please clarify me where I got wrong.**

**Comment by AllentDan** [comment]
Hi, @Thevakumar-Luheerathan. As is described in the docstring of the function `inference_model`, `backend_models` is supposed to be a variable of `Sequence[str]`.

**Comment by Thevakumar-Luheerathan** [comment]
> Hi, @Thevakumar-Luheerathan. As is described in the docstring of the function `inference_model`, `backend_models` is supposed to be a variable of `Sequence[str]`.

I tried the following code with the above correction.
```
import mmcv
from mmdeploy.apis import inference_model

video_path='resources/test.mp4'

video = mmcv.VideoReader(video_path)
assert video.opened, f'Failed to load video file {video_path}'


det_checkpoint='checkpoints/ssdlite_mobilenetv2_scratch_600e_coco_20210629_110627-974d9307.pth'
model_cfg='configs/ssd/ssdlite_mobilenetv2_scratch_600e_coco.py'
deploy_cfg='configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py'
backend_models=['checkpoints/tensorrt/end2end.engine']
device='cuda:0'

for frame in video:
    result = inference_model(model_cfg, deploy_cfg, backend_models, img=frame, device=device)
    print(result)
```
I got a `Aborted (core dumped)`. The log is as follows.



```
2022-03-02 16:20:39,547 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /media/luhee/MY FILES/FYP/MMDeploy/build/lib/libmmdeploy_tensorrt_ops.so
2022-03-02 16:20:39,549 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /media/luhee/MY FILES/FYP/MMDeploy/build/lib/libmmdeploy_tensorrt_ops.so
[03/02/2022-16:20:47] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 10.2.3 but loaded cuBLAS/cuBLAS LT 10.2.2
[03/02/2022-16:20:50] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 10.2.3 but loaded cuBLAS/cuBLAS LT 10.2.2
/home/luhee/anaconda3/envs/fyp3/lib/python3.7/site-packages/mmdet/datasets/utils.py:69: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
#assertion/media/luhee/MY FILES/FYP/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/trt_batched_nms.cpp,98
Aborted (core dumped)
```
```

```

**what should I do?**

**Comment by AllentDan** [comment]
Hi, @Thevakumar-Luheerathan. Check [this](https://github.com/open-mmlab/mmdeploy/issues/134) out that it could be the device of your platform does not support the TensorRT operation of the *engine* file. What device or devices did you use to convert the model and inference the model?

**Comment by Thevakumar-Luheerathan** [comment]
> Hi, @Thevakumar-Luheerathan. Check [this](https://github.com/open-mmlab/mmdeploy/issues/134) out that it could be the device of your platform does not support the TensorRT operation of the _engine_ file. What device or devices did you use to convert the model and inference the model?

I checked it. That issue is exactly similar to mine. Tensorrt needs at least 5.0 compute capability. My device(930MX) have the support to Tensorrt.

**Comment by AllentDan** [comment]
Hi, @Thevakumar-Luheerathan. We did not test the devices with 5.0 compute capability actually by now. However, here are some  suggestions that may make it a workaround:
1. modify the [_NVCC_FLAGS](https://github.com/open-mmlab/mmdeploy/blob/34879e638cc2db511e798a376b9a4b9932660fe1/cmake/cuda.cmake#L36) 
2. reduce the number of [max_output_boxes_per_class](https://github.com/open-mmlab/mmdeploy/blob/34879e638cc2db511e798a376b9a4b9932660fe1/configs/mmdet/_base_/base_static.py#L12) reduce the number of proposals.

**Comment by Thevakumar-Luheerathan** [comment]
@AllentDan is it possible to give some clarfications on what I am going to modify? And what would be the impact of these?..

**Comment by AllentDan** [comment]
1. `set(_NVCC_FLAGS "${_NVCC_FLAGS} -gencode arch=compute_50,code=sm_50")`
2. `pre_top_k=500,`

**Comment by lvhan028** [comment]
Close it since no activity for quite a long time
