### ISSUE TITLE
双阶段模型部署成onnx的使用报错[Bug] 

### ISSUE THREAD

**Issue by sherleyjj** [open-mmlab/mmdeploy#2014]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

当我按照mmdeploy中对mmdet和mmpose中的模型转换成onnx，然后分别使用build_task_processor和build_backend_model构建模型，会出现错误：KeyError: 'PackDetInputs is not in the transform registry. Please check whether the value of `PackDetInputs` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

### Reproduction

no

### Environment

```Shell
04/21 12:32:27 - mmengine - INFO - **********Environmental information**********
04/21 12:32:29 - mmengine - INFO - sys.platform: linux
04/21 12:32:29 - mmengine - INFO - Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
04/21 12:32:29 - mmengine - INFO - CUDA available: True
04/21 12:32:29 - mmengine - INFO - numpy_random_seed: 2147483648
04/21 12:32:29 - mmengine - INFO - GPU 0,1,2,3: NVIDIA GeForce RTX 2080 Ti
04/21 12:32:29 - mmengine - INFO - CUDA_HOME: /usr
04/21 12:32:29 - mmengine - INFO - NVCC: Cuda compilation tools, release 10.1, V10.1.24
04/21 12:32:29 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
04/21 12:32:29 - mmengine - INFO - PyTorch: 1.12.1+cu113
04/21 12:32:29 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

04/21 12:32:29 - mmengine - INFO - TorchVision: 0.13.1+cu113
04/21 12:32:29 - mmengine - INFO - OpenCV: 4.7.0
04/21 12:32:29 - mmengine - INFO - MMEngine: 0.7.2
04/21 12:32:29 - mmengine - INFO - MMCV: 2.0.0
04/21 12:32:29 - mmengine - INFO - MMCV Compiler: GCC 9.3
04/21 12:32:29 - mmengine - INFO - MMCV CUDA Compiler: 11.3
04/21 12:32:29 - mmengine - INFO - MMDeploy: 1.0.0+6c26e88
04/21 12:32:29 - mmengine - INFO - 

04/21 12:32:29 - mmengine - INFO - **********Backend information**********
04/21 12:32:29 - mmengine - INFO - tensorrt:    None
04/21 12:32:29 - mmengine - INFO - ONNXRuntime: 1.8.1
04/21 12:32:29 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
04/21 12:32:29 - mmengine - INFO - ONNXRuntime custom ops:      Available
04/21 12:32:29 - mmengine - INFO - pplnn:       None
04/21 12:32:29 - mmengine - INFO - ncnn:        None
04/21 12:32:29 - mmengine - INFO - snpe:        None
04/21 12:32:29 - mmengine - INFO - openvino:    None
04/21 12:32:29 - mmengine - INFO - torchscript: 1.12.1+cu113
04/21 12:32:29 - mmengine - INFO - torchscript custom ops:      NotAvailable
04/21 12:32:29 - mmengine - INFO - rknn-toolkit:        None
04/21 12:32:29 - mmengine - INFO - rknn-toolkit2:       None
04/21 12:32:29 - mmengine - INFO - ascend:      None
04/21 12:32:29 - mmengine - INFO - coreml:      None
04/21 12:32:29 - mmengine - INFO - tvm: None
04/21 12:32:29 - mmengine - INFO - vacc:        None
04/21 12:32:29 - mmengine - INFO - 

04/21 12:32:29 - mmengine - INFO - **********Codebase information**********
04/21 12:32:29 - mmengine - INFO - mmdet:       3.0.0
04/21 12:32:29 - mmengine - INFO - mmseg:       None
04/21 12:32:29 - mmengine - INFO - mmcls:       None
04/21 12:32:29 - mmengine - INFO - mmocr:       None
04/21 12:32:29 - mmengine - INFO - mmedit:      None
04/21 12:32:29 - mmengine - INFO - mmdet3d:     None
04/21 12:32:29 - mmengine - INFO - mmpose:      1.0.0
04/21 12:32:29 - mmengine - INFO - mmrotate:    None
04/21 12:32:29 - mmengine - INFO - mmaction:    None
04/21 12:32:29 - mmengine - INFO - mmrazor:     None
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/home/jiangdehong/conda/mmdeploy/testonnx.py", line 163, in <module>
    model_det_inputs, _ = task_processor_det.create_input('demo/resources/6.png', input_det_shape)
  File "/home/jiangdehong/conda/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 204, in create_input
    test_pipeline = Compose(pipeline)
  File "/home/jiangdehong/anaconda3/envs/mmpose2/lib/python3.8/site-packages/mmcv/transforms/wrappers.py", line 66, in __init__
    transform = TRANSFORMS.build(transform)
  File "/home/jiangdehong/anaconda3/envs/mmpose2/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/jiangdehong/anaconda3/envs/mmpose2/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'PackDetInputs is not in the transform registry. Please check whether the value of `PackDetInputs` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```

**Comment by RunningLeon** [comment]
@sherleyjj Hi, pls. provide sample code to reproduce the issue.

**Comment by sherleyjj** [comment]
![image](https://user-images.githubusercontent.com/49601443/233600082-d5d04c82-86ea-4095-8c07-c9638bd27fff.png)
在162行会发生错误，或者155和156行调换也会发生同样的错误

**Comment by sherleyjj** [comment]
@RunningLeon 十分感谢

**Comment by RunningLeon** [comment]
@sherleyjj hi, you could register all modules before use it: 
```
        from mmpose.utils.setup_env import register_all_modules
        register_all_modules(True)
```
