### ISSUE TITLE
[Bug] ONNX deployment failure of YOLOX trained in previous version

### ISSUE THREAD

**Issue by wanbin-song** [open-mmlab/mmdeploy#2028]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I trained my yolox model using mmdetection and wants to export to ONNX format.
The mmcv/mmdet version I trained my model is as following, which is slightly different with the ones in mmdeploy docker.

Version of libraries I trained
- mmcv = 1.3.17
- mmdet = 2.25.1

Seems the error message is related with the library version, but can i get a workaround?

### Reproduction

python ./mmdeploy/tools/deploy.py ./mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py ./mmdeploy/configs/yolox_s_8x8_300e_c_fd6_rh_coco.py best_bbox_mAP_epoch_296.pth sample.jpg   

### Environment

```Shell
04/26 00:04:09 - mmengine - INFO - 

04/26 00:04:09 - mmengine - INFO - **********Environmental information**********
04/26 00:04:09 - mmengine - INFO - sys.platform: linux
04/26 00:04:09 - mmengine - INFO - Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
04/26 00:04:09 - mmengine - INFO - CUDA available: False
04/26 00:04:09 - mmengine - INFO - numpy_random_seed: 2147483648
04/26 00:04:09 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
04/26 00:04:09 - mmengine - INFO - PyTorch: 1.10.0+cpu
04/26 00:04:09 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, 

04/26 00:04:09 - mmengine - INFO - TorchVision: 0.11.0+cpu
04/26 00:04:09 - mmengine - INFO - OpenCV: 4.5.3-openvino
04/26 00:04:09 - mmengine - INFO - MMEngine: 0.7.2
04/26 00:04:09 - mmengine - INFO - MMCV: 2.0.0
04/26 00:04:09 - mmengine - INFO - MMCV Compiler: GCC 7.3
04/26 00:04:09 - mmengine - INFO - MMCV CUDA Compiler: not available
04/26 00:04:09 - mmengine - INFO - MMDeploy: 1.0.0+
04/26 00:04:09 - mmengine - INFO - 

04/26 00:04:09 - mmengine - INFO - **********Backend information**********
04/26 00:04:10 - mmengine - INFO - tensorrt:    None
04/26 00:04:10 - mmengine - INFO - ONNXRuntime: 1.8.1
04/26 00:04:10 - mmengine - INFO - ONNXRuntime-gpu:     None
04/26 00:04:10 - mmengine - INFO - ONNXRuntime custom ops:      Available
04/26 00:04:10 - mmengine - INFO - pplnn:       None
04/26 00:04:10 - mmengine - INFO - ncnn:        1.0.20230424
04/26 00:04:10 - mmengine - INFO - ncnn custom ops:     Available
04/26 00:04:10 - mmengine - INFO - snpe:        None
04/26 00:04:10 - mmengine - INFO - openvino:    2022.3.0
04/26 00:04:10 - mmengine - INFO - torchscript: 1.10.0+cpu
04/26 00:04:10 - mmengine - INFO - torchscript custom ops:      NotAvailable
04/26 00:04:10 - mmengine - INFO - rknn-toolkit:        None
04/26 00:04:10 - mmengine - INFO - rknn-toolkit2:       None
04/26 00:04:10 - mmengine - INFO - ascend:      None
04/26 00:04:10 - mmengine - INFO - coreml:      None
04/26 00:04:10 - mmengine - INFO - tvm: None
04/26 00:04:10 - mmengine - INFO - vacc:        None
04/26 00:04:10 - mmengine - INFO - 

04/26 00:04:10 - mmengine - INFO - **********Codebase information**********
04/26 00:04:10 - mmengine - INFO - mmdet:       3.0.0
04/26 00:04:10 - mmengine - INFO - mmseg:       None
04/26 00:04:10 - mmengine - INFO - mmcls:       None
04/26 00:04:10 - mmengine - INFO - mmocr:       1.0.0
04/26 00:04:10 - mmengine - INFO - mmedit:      None
04/26 00:04:10 - mmengine - INFO - mmdet3d:     None
04/26 00:04:10 - mmengine - INFO - mmpose:      None
04/26 00:04:10 - mmengine - INFO - mmrotate:    None
04/26 00:04:10 - mmengine - INFO - mmaction:    None
04/26 00:04:10 - mmengine - INFO - mmrazor:     None
```

### Error traceback

```Shell
04/26 00:04:48 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
04/26 00:04:49 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
04/26 00:04:49 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'input_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 63, in torch2onnx
    torch_model = task_processor.build_pytorch_model(model_checkpoint)
  File "/root/workspace/mmdeploy/mmdeploy/codebase/base/task.py", line 120, in build_pytorch_model
    model = MODELS.build(model)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 241, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
TypeError: class `YOLOX` in mmdet/models/detectors/yolox.py: __init__() got an unexpected keyword argument 'input_size'
04/26 00:04:49 - mmengine - ERROR - /root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by fedllanes** [comment]
Could you fix it?

**Comment by huayuan4396** [comment]
@wanbin-song Hi, I've tried to deploy the yolox(the model is downloaded from mmdet model zoo) and it works fine. I think this issue is probably related to the mmdet version you used to train your model, maybe you should try to train it on a newer version of mmdet.

Here is my env_info:

```Shell
05/10 15:34:00 - mmengine - INFO - 

05/10 15:34:00 - mmengine - INFO - **********Environmental information**********
05/10 15:34:00 - mmengine - INFO - sys.platform: linux
05/10 15:34:00 - mmengine - INFO - Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
05/10 15:34:00 - mmengine - INFO - CUDA available: True
05/10 15:34:00 - mmengine - INFO - numpy_random_seed: 2147483648
05/10 15:34:00 - mmengine - INFO - GPU 0: NVIDIA GeForce GTX 1660 Ti
05/10 15:34:00 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
05/10 15:34:00 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.1, V11.1.105
05/10 15:34:00 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
05/10 15:34:00 - mmengine - INFO - PyTorch: 1.8.1+cu111
05/10 15:34:00 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

05/10 15:34:00 - mmengine - INFO - TorchVision: 0.9.1+cu111
05/10 15:34:00 - mmengine - INFO - OpenCV: 4.7.0
05/10 15:34:00 - mmengine - INFO - MMEngine: 0.7.2
05/10 15:34:00 - mmengine - INFO - MMCV: 2.0.0
05/10 15:34:00 - mmengine - INFO - MMCV Compiler: GCC 7.3
05/10 15:34:00 - mmengine - INFO - MMCV CUDA Compiler: 11.1
05/10 15:34:00 - mmengine - INFO - MMDeploy: 1.0.0+376c511
05/10 15:34:00 - mmengine - INFO - 

05/10 15:34:00 - mmengine - INFO - **********Backend information**********
05/10 15:34:01 - mmengine - INFO - tensorrt:	8.4.3.1
05/10 15:34:01 - mmengine - INFO - tensorrt custom ops:	NotAvailable
05/10 15:34:01 - mmengine - INFO - ONNXRuntime:	1.8.1
05/10 15:34:01 - mmengine - INFO - ONNXRuntime-gpu:	None
05/10 15:34:01 - mmengine - INFO - ONNXRuntime custom ops:	NotAvailable
05/10 15:34:01 - mmengine - INFO - pplnn:	0.0.0
05/10 15:34:01 - mmengine - INFO - ncnn:	1.0.20230424
05/10 15:34:01 - mmengine - INFO - ncnn custom ops:	NotAvailable
05/10 15:34:01 - mmengine - INFO - snpe:	None
05/10 15:34:01 - mmengine - INFO - openvino:	None
05/10 15:34:01 - mmengine - INFO - torchscript:	1.8.1+cu111
05/10 15:34:01 - mmengine - INFO - torchscript custom ops:	NotAvailable
05/10 15:34:01 - mmengine - INFO - rknn-toolkit:	None
05/10 15:34:01 - mmengine - INFO - rknn-toolkit2:	None
05/10 15:34:01 - mmengine - INFO - ascend:	None
05/10 15:34:01 - mmengine - INFO - coreml:	None
05/10 15:34:01 - mmengine - INFO - tvm:	None
05/10 15:34:01 - mmengine - INFO - vacc:	None
05/10 15:34:01 - mmengine - INFO - 

05/10 15:34:01 - mmengine - INFO - **********Codebase information**********
05/10 15:34:01 - mmengine - INFO - mmdet:	3.0.0
05/10 15:34:01 - mmengine - INFO - mmseg:	None
05/10 15:34:01 - mmengine - INFO - mmpretrain:	1.0.0rc7
05/10 15:34:01 - mmengine - INFO - mmocr:	None
05/10 15:34:01 - mmengine - INFO - mmagic:	1.0.0
05/10 15:34:01 - mmengine - INFO - mmdet3d:	None
05/10 15:34:01 - mmengine - INFO - mmpose:	None
05/10 15:34:01 - mmengine - INFO - mmrotate:	None
05/10 15:34:01 - mmengine - INFO - mmaction:	None
05/10 15:34:01 - mmengine - INFO - mmrazor:	None

**Comment by oym050922021** [comment]
> 

 @huayuan4396  hello，I've tried to deploy the yolox with the latest version mmdet, but it failed。
our Environment is as follows。
05/22 17:38:02 - mmengine - INFO - TorchVision: 0.14.1+cu117
05/22 17:38:02 - mmengine - INFO - OpenCV: 4.7.0
05/22 17:38:02 - mmengine - INFO - MMEngine: 0.7.2
05/22 17:38:02 - mmengine - INFO - MMCV: 2.0.0rc4
05/22 17:38:02 - mmengine - INFO - MMCV Compiler: GCC 9.3
05/22 17:38:02 - mmengine - INFO - MMCV CUDA Compiler: 11.7
05/22 17:38:02 - mmengine - INFO - MMDeploy: 1.0.0+8670d83
05/22 17:38:02 - mmengine - INFO - 

05/22 17:38:02 - mmengine - INFO - **********Backend information**********
05/22 17:38:02 - mmengine - INFO - tensorrt:    None
05/22 17:38:02 - mmengine - INFO - ONNXRuntime: 1.8.1
05/22 17:38:02 - mmengine - INFO - ONNXRuntime-gpu:     None
05/22 17:38:02 - mmengine - INFO - ONNXRuntime custom ops:      Available
05/22 17:38:02 - mmengine - INFO - pplnn:       None
05/22 17:38:02 - mmengine - INFO - ncnn:        None
05/22 17:38:02 - mmengine - INFO - snpe:        None
05/22 17:38:02 - mmengine - INFO - openvino:    None
05/22 17:38:02 - mmengine - INFO - torchscript: 1.13.1
05/22 17:38:02 - mmengine - INFO - torchscript custom ops:      NotAvailable
05/22 17:38:02 - mmengine - INFO - rknn-toolkit:        None
05/22 17:38:02 - mmengine - INFO - rknn-toolkit2:       None
05/22 17:38:02 - mmengine - INFO - ascend:      None
05/22 17:38:02 - mmengine - INFO - coreml:      None
05/22 17:38:02 - mmengine - INFO - tvm: None
05/22 17:38:02 - mmengine - INFO - vacc:        None
05/22 17:38:02 - mmengine - INFO - 

05/22 17:38:02 - mmengine - INFO - **********Codebase information**********
05/22 17:38:02 - mmengine - INFO - mmdet:       3.0.0
05/22 17:38:02 - mmengine - INFO - mmseg:       None
05/22 17:38:02 - mmengine - INFO - mmpretrain:  None
05/22 17:38:02 - mmengine - INFO - mmocr:       None
05/22 17:38:02 - mmengine - INFO - mmagic:      None
05/22 17:38:02 - mmengine - INFO - mmdet3d:     None
05/22 17:38:02 - mmengine - INFO - mmpose:      None
05/22 17:38:02 - mmengine - INFO - mmrotate:    None
05/22 17:38:02 - mmengine - INFO - mmaction:    None
05/22 17:38:02 - mmengine - INFO - mmrazor:     None


what is the problem, please？Thank you!
