### ISSUE TITLE
[Bug] dbnet convert to tensorrt

### ISSUE THREAD

**Issue by XinDing5** [open-mmlab/mmdeploy#2032]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I tried to convert dbnet model to tensorrt but it failed. Could you please help to have a look? Thanks.

### Reproduction

Here is the command I used:
python tools/deploy.py \
    configs/mmocr/text-detection/text-detection_tensorrt_static-512x512.py \
    pthmodels/detect/dbnet_resnet18_fpnc_1200e_rects_icdar2015.py \
    pthmodels/detect/epoch_80.pth \
    demo/resources/text_det.jpg \
    --work-dir mmdeploy_models/detect/tensorrt \
    --device cuda \
    --show \
    --dump-info

### Environment

```Shell
04/26 14:01:08 - mmengine - INFO - **********Environmental information**********
04/26 14:01:10 - mmengine - INFO - sys.platform: linux
04/26 14:01:10 - mmengine - INFO - Python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) [GCC 10.3.0]
04/26 14:01:10 - mmengine - INFO - CUDA available: True
04/26 14:01:10 - mmengine - INFO - numpy_random_seed: 2147483648
04/26 14:01:10 - mmengine - INFO - GPU 0,1: Tesla V100-PCIE-32GB
04/26 14:01:10 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
04/26 14:01:10 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.99
04/26 14:01:10 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
04/26 14:01:10 - mmengine - INFO - PyTorch: 1.13.0a0+340c412
04/26 14:01:10 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.4
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.4 Product Build 20200917 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash N/A)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
  - CuDNN 8.4.1  (built against CUDA 11.6)
  - Magma 2.6.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.4.1, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS=-fno-gnu-unique -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

04/26 14:01:10 - mmengine - INFO - TorchVision: 0.13.0a0
04/26 14:01:10 - mmengine - INFO - OpenCV: 4.2.0
04/26 14:01:10 - mmengine - INFO - MMEngine: 0.7.2
04/26 14:01:10 - mmengine - INFO - MMCV: 2.0.0
04/26 14:01:10 - mmengine - INFO - MMCV Compiler: GCC 9.4
04/26 14:01:10 - mmengine - INFO - MMCV CUDA Compiler: 11.7
04/26 14:01:10 - mmengine - INFO - MMDeploy: 1.0.0+2c7e91b
04/26 14:01:10 - mmengine - INFO - 

04/26 14:01:10 - mmengine - INFO - **********Backend information**********
04/26 14:01:11 - mmengine - INFO - tensorrt:    8.2.5.1
04/26 14:01:11 - mmengine - INFO - tensorrt custom ops: Available
04/26 14:01:11 - mmengine - INFO - ONNXRuntime: None
04/26 14:01:11 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
04/26 14:01:11 - mmengine - INFO - ONNXRuntime custom ops:      Available
04/26 14:01:11 - mmengine - INFO - pplnn:       None
04/26 14:01:11 - mmengine - INFO - ncnn:        None
04/26 14:01:11 - mmengine - INFO - snpe:        None
04/26 14:01:11 - mmengine - INFO - openvino:    None
04/26 14:01:11 - mmengine - INFO - torchscript: 1.13.0a0+340c412
04/26 14:01:11 - mmengine - INFO - torchscript custom ops:      NotAvailable
04/26 14:01:11 - mmengine - INFO - rknn-toolkit:        None
04/26 14:01:11 - mmengine - INFO - rknn-toolkit2:       None
04/26 14:01:11 - mmengine - INFO - ascend:      None
04/26 14:01:11 - mmengine - INFO - coreml:      None
04/26 14:01:11 - mmengine - INFO - tvm: None
04/26 14:01:11 - mmengine - INFO - vacc:        None
04/26 14:01:11 - mmengine - INFO - 

04/26 14:01:11 - mmengine - INFO - **********Codebase information**********
04/26 14:01:11 - mmengine - INFO - mmdet:       3.0.0
04/26 14:01:11 - mmengine - INFO - mmseg:       None
04/26 14:01:11 - mmengine - INFO - mmcls:       None
04/26 14:01:11 - mmengine - INFO - mmocr:       1.0.0
04/26 14:01:11 - mmengine - INFO - mmedit:      None
04/26 14:01:11 - mmengine - INFO - mmdet3d:     None
04/26 14:01:11 - mmengine - INFO - mmpose:      None
04/26 14:01:11 - mmengine - INFO - mmrotate:    None
04/26 14:01:11 - mmengine - INFO - mmaction:    None
04/26 14:01:11 - mmengine - INFO - mmrazor:     None
```

### Error traceback

```Shell
04/26 13:50:55 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
04/26 13:50:55 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "mmocr_tasks" registry tree. As a workaround, the current "mmocr_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
04/26 13:50:57 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
NOTE! Installing ujson may make loading annotations faster.
04/26 13:50:59 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
04/26 13:50:59 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "mmocr_tasks" registry tree. As a workaround, the current "mmocr_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: pthmodels/detect/epoch_80.pth
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 64, in torch2onnx
    data, model_inputs = task_processor.create_input(
  File "/opt/conda/lib/python3.8/site-packages/mmdeploy/codebase/mmocr/deploy/text_detection.py", line 201, in create_input
    data_ = test_pipeline(data_)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/transforms/wrappers.py", line 88, in transform
    results = t(results)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/dfs/data/mmocr/mmocr/datasets/transforms/ocr_transforms.py", line 605, in transform
    results = super().transform(results)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/transforms/processing.py", line 257, in transform
    self._resize_img(results)
  File "/dfs/data/mmocr/mmocr/datasets/transforms/ocr_transforms.py", line 554, in _resize_img
    return super()._resize_img(results)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/transforms/processing.py", line 185, in _resize_img
    img, w_scale, h_scale = mmcv.imresize(
  File "/opt/conda/lib/python3.8/site-packages/mmcv/image/geometric.py", line 116, in imresize
    resized_img = cv2.resize(
SystemError: new style getargs format but argument is not a tuple
04/26 13:51:02 - mmengine - ERROR - /opt/conda/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
root@workspace:/dfs/data/mmdeploy# sh convert_textdet.sh
NOTE! Installing ujson may make loading annotations faster.
04/26 13:53:23 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
04/26 13:53:23 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "mmocr_tasks" registry tree. As a workaround, the current "mmocr_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
04/26 13:53:25 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
NOTE! Installing ujson may make loading annotations faster.
04/26 13:53:27 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
04/26 13:53:27 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "mmocr_tasks" registry tree. As a workaround, the current "mmocr_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: pthmodels/detect/epoch_80.pth
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 64, in torch2onnx
    data, model_inputs = task_processor.create_input(
  File "/opt/conda/lib/python3.8/site-packages/mmdeploy/codebase/mmocr/deploy/text_detection.py", line 201, in create_input
    data_ = test_pipeline(data_)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/transforms/wrappers.py", line 88, in transform
    results = t(results)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/dfs/data/mmocr/mmocr/datasets/transforms/ocr_transforms.py", line 605, in transform
    results = super().transform(results)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/transforms/processing.py", line 257, in transform
    self._resize_img(results)
  File "/dfs/data/mmocr/mmocr/datasets/transforms/ocr_transforms.py", line 554, in _resize_img
    return super()._resize_img(results)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/transforms/processing.py", line 185, in _resize_img
    img, w_scale, h_scale = mmcv.imresize(
  File "/opt/conda/lib/python3.8/site-packages/mmcv/image/geometric.py", line 116, in imresize
    resized_img = cv2.resize(
SystemError: new style getargs format but argument is not a tuple
04/26 13:53:30 - mmengine - ERROR - /opt/conda/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by RunningLeon** [comment]
@XinDing5 hi, could you try with `pip install opencv-python==4.5.4.60`?
