### ISSUE TITLE
[Bug] error when convert SATRN to tensorrt

### ISSUE THREAD

**Issue by Daisy5296** [open-mmlab/mmdeploy#2034]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I tried to convert the provided SATRN model to tensorrt, but it failed. Could you please help to have a look? Thanks!

### Reproduction

Here is my command:

python tools/deploy.py \
    configs/mmocr/text-recognition/text-recognition_tensorrt-fp16_static-32x32.py \
    pthmodels/satrn_shallow_5e_st_mj.py \
    pthmodels/satrn_shallow_5e_st_mj_20220915_152443-5fd04a4c.pth \
    demo/resources/text_recog.jpg \
    --work-dir mmdeploy_models/recog/tensorrt \
    --device cuda \
    --show \
    --dump-info

### Environment

```Shell
04/26 14:01:08 - mmengine - INFO - **********Environmental information**********
04/26 14:01:10 - mmengine - INFO - sys.platform: linux
04/26 14:01:10 - mmengine - INFO - Python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) [GCC 10.3.0]
04/26 14:01:10 - mmengine - INFO - CUDA available: True
04/26 14:01:10 - mmengine - INFO - numpy_random_seed: 2147483648
04/26 14:01:10 - mmengine - INFO - GPU 0,1: Tesla V100-PCIE-32GB
04/26 14:01:10 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
04/26 14:01:10 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.99
04/26 14:01:10 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
04/26 14:01:10 - mmengine - INFO - PyTorch: 1.13.0a0+340c412
04/26 14:01:10 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.4
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.4 Product Build 20200917 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash N/A)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
  - CuDNN 8.4.1  (built against CUDA 11.6)
  - Magma 2.6.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.4.1, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS=-fno-gnu-unique -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

04/26 14:01:10 - mmengine - INFO - TorchVision: 0.13.0a0
04/26 14:01:10 - mmengine - INFO - OpenCV: 4.2.0
04/26 14:01:10 - mmengine - INFO - MMEngine: 0.7.2
04/26 14:01:10 - mmengine - INFO - MMCV: 2.0.0
04/26 14:01:10 - mmengine - INFO - MMCV Compiler: GCC 9.4
04/26 14:01:10 - mmengine - INFO - MMCV CUDA Compiler: 11.7
04/26 14:01:10 - mmengine - INFO - MMDeploy: 1.0.0+2c7e91b
04/26 14:01:10 - mmengine - INFO - 

04/26 14:01:10 - mmengine - INFO - **********Backend information**********
04/26 14:01:11 - mmengine - INFO - tensorrt:    8.2.5.1
04/26 14:01:11 - mmengine - INFO - tensorrt custom ops: Available
04/26 14:01:11 - mmengine - INFO - ONNXRuntime: None
04/26 14:01:11 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
04/26 14:01:11 - mmengine - INFO - ONNXRuntime custom ops:      Available
04/26 14:01:11 - mmengine - INFO - pplnn:       None
04/26 14:01:11 - mmengine - INFO - ncnn:        None
04/26 14:01:11 - mmengine - INFO - snpe:        None
04/26 14:01:11 - mmengine - INFO - openvino:    None
04/26 14:01:11 - mmengine - INFO - torchscript: 1.13.0a0+340c412
04/26 14:01:11 - mmengine - INFO - torchscript custom ops:      NotAvailable
04/26 14:01:11 - mmengine - INFO - rknn-toolkit:        None
04/26 14:01:11 - mmengine - INFO - rknn-toolkit2:       None
04/26 14:01:11 - mmengine - INFO - ascend:      None
04/26 14:01:11 - mmengine - INFO - coreml:      None
04/26 14:01:11 - mmengine - INFO - tvm: None
04/26 14:01:11 - mmengine - INFO - vacc:        None
04/26 14:01:11 - mmengine - INFO - 

04/26 14:01:11 - mmengine - INFO - **********Codebase information**********
04/26 14:01:11 - mmengine - INFO - mmdet:       3.0.0
04/26 14:01:11 - mmengine - INFO - mmseg:       None
04/26 14:01:11 - mmengine - INFO - mmcls:       None
04/26 14:01:11 - mmengine - INFO - mmocr:       1.0.0
04/26 14:01:11 - mmengine - INFO - mmedit:      None
04/26 14:01:11 - mmengine - INFO - mmdet3d:     None
04/26 14:01:11 - mmengine - INFO - mmpose:      None
04/26 14:01:11 - mmengine - INFO - mmrotate:    None
04/26 14:01:11 - mmengine - INFO - mmaction:    None
04/26 14:01:11 - mmengine - INFO - mmrazor:     None
```

### Error traceback

```Shell
04/26 16:42:11 - mmengine - INFO - Execute onnx optimize passes.
04/26 16:42:11 - mmengine - WARNING - Can not optimize model, please build torchscipt extension.
More details: https://github.com/open-mmlab/mmdeploy/tree/1.x/docs/en/experimental/onnx_optimizer.md
04/26 16:42:27 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
04/26 16:42:32 - mmengine - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in subprocess
04/26 16:42:32 - mmengine - INFO - Successfully loaded tensorrt plugins from /opt/conda/lib/python3.8/site-packages/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
[04/26/2023-16:42:33] [TRT] [I] [MemUsageChange] Init CUDA: CPU +277, GPU +0, now: CPU 349, GPU 1172 (MiB)
[04/26/2023-16:42:33] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 349 MiB, GPU 1172 MiB
[04/26/2023-16:42:33] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 461 MiB, GPU 1196 MiB
[04/26/2023-16:42:34] [TRT] [I] ----------------------------------------------------------------
[04/26/2023-16:42:34] [TRT] [I] Input filename:   mmdeploy_models/recog/tensorrt/end2end.onnx
[04/26/2023-16:42:34] [TRT] [I] ONNX IR version:  0.0.6
[04/26/2023-16:42:34] [TRT] [I] Opset version:    11
[04/26/2023-16:42:34] [TRT] [I] Producer name:    pytorch
[04/26/2023-16:42:34] [TRT] [I] Producer version: 1.13.0
[04/26/2023-16:42:34] [TRT] [I] Domain:           
[04/26/2023-16:42:34] [TRT] [I] Model version:    0
[04/26/2023-16:42:34] [TRT] [I] Doc string:       
[04/26/2023-16:42:34] [TRT] [I] ----------------------------------------------------------------
[04/26/2023-16:42:34] [TRT] [W] parsers/onnx/onnx2trt_utils.cpp:368: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[04/26/2023-16:42:43] [TRT] [W] parsers/onnx/onnx2trt_utils.cpp:396: One or more weights outside the range of INT32 was clamped
[04/26/2023-16:42:43] [TRT] [W] parsers/onnx/onnx2trt_utils.cpp:396: One or more weights outside the range of INT32 was clamped
[04/26/2023-16:42:43] [TRT] [W] parsers/onnx/onnx2trt_utils.cpp:396: One or more weights outside the range of INT32 was clamped
[04/26/2023-16:42:43] [TRT] [E] [graphShapeAnalyzer.cpp::computeOutputExtents::1026] Error Code 4: Miscellaneous (Concat_845: error while computing output extent)
[04/26/2023-16:42:43] [TRT] [E] parsers/onnx/ModelImporter.cpp:791: While parsing node number 845 [Concat -> "onnx::Reshape_1947"]:
[04/26/2023-16:42:43] [TRT] [E] parsers/onnx/ModelImporter.cpp:792: --- Begin node ---
[04/26/2023-16:42:43] [TRT] [E] parsers/onnx/ModelImporter.cpp:793: input: "onnx::Shape_1924"
input: "onnx::Concat_31050"
output: "onnx::Reshape_1947"
name: "Concat_845"
op_type: "Concat"
attribute {
  name: "axis"
  i: 0
  type: INT
}

[04/26/2023-16:42:43] [TRT] [E] parsers/onnx/ModelImporter.cpp:794: --- End node ---
[04/26/2023-16:42:43] [TRT] [E] parsers/onnx/ModelImporter.cpp:796: ERROR: parsers/onnx/ModelImporter.cpp:179 In function parseGraph:
[6] Invalid Node - Concat_845
[graphShapeAnalyzer.cpp::computeOutputExtents::1026] Error Code 4: Miscellaneous (Concat_845: error while computing output extent)
Process Process-3:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmdeploy/apis/utils/utils.py", line 98, in to_backend
    return backend_mgr.to_backend(
  File "/opt/conda/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/backend_manager.py", line 127, in to_backend
    onnx2tensorrt(
  File "/opt/conda/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "/opt/conda/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/utils.py", line 185, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 845 (parseGraph): INVALID_NODE: Invalid Node - Concat_845
[graphShapeAnalyzer.cpp::computeOutputExtents::1026] Error Code 4: Miscellaneous (Concat_845: error while computing output extent)

04/26 16:42:44 - mmengine - ERROR - /opt/conda/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.utils.utils.to_backend` with Call id: 1 failed. exit.
```

**Comment by AllentDan** [comment]
Please use TensorRT 8.5+.

**Comment by XinDing5** [comment]
> Please use TensorRT 8.5+.

Hi thanks for reply. I am afraid I cannot upgrade to TensorRT 8.5+ due to the limitation of the deployment environment... Is it true that SATRN is not supported in tensorRT 8.2? I think it is not related, because that the model cannot even pass onnx parser or onnxsim. It seems to be something wrong with the onnx model. Could you please help to check this? Thanks!

**Comment by AllentDan** [comment]
I tried TensorRT 8.4.1.5+PyTorch 1.10 and it succeeded. Maybe you can try the config `configs/mmocr/text-recognition/text-recognition_tensorrt_dynamic-32x32-32x640.py`

**Comment by XinDing5** [comment]
> I tried TensorRT 8.4.1.5+PyTorch 1.10 and it succeeded. Maybe you can try the config `configs/mmocr/text-recognition/text-recognition_tensorrt_dynamic-32x32-32x640.py`

Tried this and the same error occurs. But it can be onnxsim successfully. I then used the simplified onnx model and did a trt conversion using trtexec without mmdeploy. It got the following error. Is there any clue from this?

[04/27/2023-07:36:46] [I] Finish parsing network model
[04/27/2023-07:59:14] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +518, GPU +226, now: CPU 1401, GPU 2993 (MiB)
[04/27/2023-07:59:14] [I] [TRT] [MemUsageChange] Init cuDNN: CPU +115, GPU +52, now: CPU 1516, GPU 3045 (MiB)
[04/27/2023-07:59:14] [I] [TRT] Local timing cache in use. Profiling results in this builder pass will not be stored.
[04/27/2023-08:00:30] [W] [TRT] Skipping tactic 0 due to Myelin error: No results returned from cublas heuristic search
[04/27/2023-08:00:30] [W] [TRT] Weights [name=onnx::Where_664 + (Unnamed Layer* 280) [Shuffle]]: Converted FP32 value in weights (either FP32 infinity or FP32 value outside FP16 range) to corresponding FP16 infinity. If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.
[04/27/2023-08:00:35] [W] [TRT] Skipping tactic 0 due to Myelin error: No results returned from cublas heuristic search
[04/27/2023-08:00:35] [W] [TRT] Weights [name=onnx::Where_664 + (Unnamed Layer* 280) [Shuffle]]: Converted FP32 value in weights (either FP32 infinity or FP32 value outside FP16 range) to corresponding FP16 infinity. If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.
[04/27/2023-08:00:41] [W] [TRT] Skipping tactic 0 due to Myelin error: No results returned from cublas heuristic search
[04/27/2023-08:00:41] [E] Error[10]: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[onnx::Equal_661 + (Unnamed Layer* 277) [Shuffle]...Where_3885]}.)
[04/27/2023-08:00:41] [E] Error[2]: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
[04/27/2023-08:00:41] [E] Engine could not be created from network
[04/27/2023-08:00:41] [E] Building engine failed
[04/27/2023-08:00:41] [E] Failed to create engine from model.
[04/27/2023-08:00:41] [E] Engine set up failed

**Comment by AllentDan** [comment]
Did not reproduce your error. I used the following commands:
```bash
python tools/deploy.py configs/mmocr/text-recognition/text-recognition_tensorrt_dynamic-32x32-32x640.py ../mmocr/configs/textrecog/satrn/satrn_shallow_5e_st_mj.py https://download.openmmlab.com/mmocr/textrecog/satrn/satrn_shallow_5e_st_mj/satrn_shallow_5e_st_mj_20220915_152443-5fd04a4c.pth ../mmocr/demo/demo_text_recog.jpg --work-dir work_dirs/tensorrt/ocr/satrn --device cuda --show
```
Maybe you can share your ONNX file.
