### ISSUE TITLE
deploy BasicVSR error

### ISSUE THREAD

**Issue by zxd-cqu** [open-mmlab/mmdeploy#2040]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I am trying to deploy BasicVSR using mmdeploy:

but it gives me the following error
```
Traceback (most recent call last):
  File "tools/deploy.py", line 335, in <module>
    main()
  File "tools/deploy.py", line 129, in main
    export2SDK(
  File "/home/orin/ssd/Downloads/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 348, in export2SDK
    pipeline_info = get_pipeline(deploy_cfg, model_cfg, work_dir, device)
  File "/home/orin/ssd/Downloads/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 281, in get_pipeline
    preprocess = get_preprocess(deploy_cfg, model_cfg, device=device)
  File "/home/orin/ssd/Downloads/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 207, in get_preprocess
    assert transforms[0]['type'] == 'LoadImageFromFile', \
AssertionError: The first item type of pipeline should be LoadImageFromFile

```
I don't think this is an environment issue because I was able to deploy SRCNN and EDSR successfully. I think it's because mmdeploy doesn't currently support video super-resolution, right?

### Reproduction

The cmd is:
```
python3 tools/deploy.py \
  configs/mmedit/super-resolution/super-resolution_onnxruntime_static.py \
  /home/orin/ssd/mmedit_dev1x-deploy/configs/basicvsr/basicvsr_2xb4_reds4.py \
  https://download.openmmlab.com/mmediting/restorers/basicvsr/basicvsr_reds4_20120409-0e599677.pth \
  demo/resources/face.png \
  --work-dir mmdeploy_models/mmedit/basicvsr \
  --device cuda \
  --show \
  --dump-info
```

### Environment

```Shell
root@ubuntu:/home/orin/ssd/Downloads/mmdeploy# python3 tools/check_env.py
04/27 14:59:22 - mmengine - INFO -

04/27 14:59:22 - mmengine - INFO - **********Environmental information**********
04/27 14:59:24 - mmengine - INFO - sys.platform: linux
04/27 14:59:24 - mmengine - INFO - Python: 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
04/27 14:59:24 - mmengine - INFO - CUDA available: True
04/27 14:59:24 - mmengine - INFO - numpy_random_seed: 2147483648
04/27 14:59:24 - mmengine - INFO - GPU 0: Orin
04/27 14:59:24 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
04/27 14:59:24 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.4, V11.4.166
04/27 14:59:24 - mmengine - INFO - GCC: aarch64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
04/27 14:59:24 - mmengine - INFO - PyTorch: 1.11.0
04/27 14:59:24 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.4
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 11.4
  - NVCC architecture flags: -gencode;arch=compute_72,code=sm_72;-gencode;arch=compute_87,code=sm_87
  - CuDNN 8.3.2
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=11.4, CUDNN_VERSION=8.3.2, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=open, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

04/27 14:59:24 - mmengine - INFO - TorchVision: 0.12.0a0+9b5a3fe
04/27 14:59:24 - mmengine - INFO - OpenCV: 4.5.5
04/27 14:59:24 - mmengine - INFO - MMEngine: 0.7.2
04/27 14:59:24 - mmengine - INFO - MMCV: 2.0.0
04/27 14:59:24 - mmengine - INFO - MMCV Compiler: GCC 9.4
04/27 14:59:24 - mmengine - INFO - MMCV CUDA Compiler: 11.4
04/27 14:59:24 - mmengine - INFO - MMDeploy: 1.0.0rc3+0196cd0
04/27 14:59:24 - mmengine - INFO -

04/27 14:59:24 - mmengine - INFO - **********Backend information**********
04/27 14:59:24 - mmengine - INFO - tensorrt:    8.4.0.11
04/27 14:59:24 - mmengine - INFO - tensorrt custom ops: Available
04/27 14:59:24 - mmengine - INFO - ONNXRuntime: None
04/27 14:59:24 - mmengine - INFO - ONNXRuntime-gpu:     1.12.1
04/27 14:59:24 - mmengine - INFO - ONNXRuntime custom ops:      NotAvailable
04/27 14:59:24 - mmengine - INFO - pplnn:       None
04/27 14:59:24 - mmengine - INFO - ncnn:        None
04/27 14:59:24 - mmengine - INFO - snpe:        None
04/27 14:59:24 - mmengine - INFO - openvino:    None
04/27 14:59:24 - mmengine - INFO - torchscript: 1.11.0
04/27 14:59:24 - mmengine - INFO - torchscript custom ops:      NotAvailable
04/27 14:59:24 - mmengine - INFO - rknn-toolkit:        None
04/27 14:59:24 - mmengine - INFO - rknn-toolkit2:       None
04/27 14:59:24 - mmengine - INFO - ascend:      None
04/27 14:59:24 - mmengine - INFO - coreml:      None
04/27 14:59:24 - mmengine - INFO - tvm: None
04/27 14:59:24 - mmengine - INFO - vacc:        None
04/27 14:59:24 - mmengine - INFO -

04/27 14:59:24 - mmengine - INFO - **********Codebase information**********
04/27 14:59:24 - mmengine - INFO - mmdet:       3.0.0
04/27 14:59:24 - mmengine - INFO - mmseg:       None
04/27 14:59:24 - mmengine - INFO - mmcls:       None
04/27 14:59:24 - mmengine - INFO - mmocr:       None
04/27 14:59:24 - mmengine - INFO - mmedit:      1.0.0rc6
04/27 14:59:24 - mmengine - INFO - mmdet3d:     None
04/27 14:59:24 - mmengine - INFO - mmpose:      None
04/27 14:59:24 - mmengine - INFO - mmrotate:    None
04/27 14:59:24 - mmengine - INFO - mmaction:    None
04/27 14:59:24 - mmengine - INFO - mmrazor:     None
```

**Comment by zxd-cqu** [comment]
why no answer?

**Comment by huayuan4396** [comment]
Hi, @zxd-cqu , sorry for the late response, MMDeploy is currently not supporting video-super-resolution network, so BasicVSR cannot be deployed  at present. I think we will support it in the future.
Feel  free to reopen this issue when getting any problem.
