### ISSUE TITLE
[Bug] Error when converting yolov8 model to onnx

### ISSUE THREAD

**Issue by WeitaoVan** [open-mmlab/mmdeploy#2051]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hi. I tried to convert yolov8_s to onnx but got the error
```
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: InstanceData
05/05 19:41:34 - mmengine - ERROR - /home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

### Reproduction

```
python tools/deploy.py     configs/mmdet/detection/detection_onnxruntime_static.py     ../mmyolo/configs/yolov8/yolov8_s_syncbn_fast_8xb16-500e_coco.py     ../mmyolo/weights/best_coco_bbox_mAP_epoch_277.pth     ../mmyolo/demo/demo.jpg     --work-dir mmdeploy_model/mmyolo     --device cpu     --dump-info
```

### Environment

```Shell
05/05 20:00:41 - mmengine - INFO - 

05/05 20:00:41 - mmengine - INFO - **********Environmental information**********
05/05 20:00:41 - mmengine - INFO - sys.platform: linux
05/05 20:00:41 - mmengine - INFO - Python: 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:57:39) [GCC 9.3.0]
05/05 20:00:41 - mmengine - INFO - CUDA available: True
05/05 20:00:41 - mmengine - INFO - numpy_random_seed: 2147483648
05/05 20:00:41 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3080
05/05 20:00:41 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.7
05/05 20:00:41 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.64
05/05 20:00:41 - mmengine - INFO - GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
05/05 20:00:41 - mmengine - INFO - PyTorch: 1.13.0
05/05 20:00:41 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

05/05 20:00:41 - mmengine - INFO - TorchVision: 0.14.0
05/05 20:00:41 - mmengine - INFO - OpenCV: 4.7.0
05/05 20:00:41 - mmengine - INFO - MMEngine: 0.7.2
05/05 20:00:41 - mmengine - INFO - MMCV: 2.0.0
05/05 20:00:41 - mmengine - INFO - MMCV Compiler: GCC 9.3
05/05 20:00:41 - mmengine - INFO - MMCV CUDA Compiler: 11.7
05/05 20:00:41 - mmengine - INFO - MMDeploy: 1.0.0+840adcf
05/05 20:00:41 - mmengine - INFO - 

05/05 20:00:41 - mmengine - INFO - **********Backend information**********
05/05 20:00:41 - mmengine - INFO - tensorrt:	None
05/05 20:00:41 - mmengine - INFO - ONNXRuntime:	1.14.1
05/05 20:00:41 - mmengine - INFO - ONNXRuntime-gpu:	None
05/05 20:00:41 - mmengine - INFO - ONNXRuntime custom ops:	Available
05/05 20:00:41 - mmengine - INFO - pplnn:	None
05/05 20:00:41 - mmengine - INFO - ncnn:	None
05/05 20:00:41 - mmengine - INFO - snpe:	None
05/05 20:00:41 - mmengine - INFO - openvino:	None
05/05 20:00:41 - mmengine - INFO - torchscript:	1.13.0
05/05 20:00:41 - mmengine - INFO - torchscript custom ops:	NotAvailable
05/05 20:00:41 - mmengine - INFO - rknn-toolkit:	None
05/05 20:00:41 - mmengine - INFO - rknn-toolkit2:	None
05/05 20:00:41 - mmengine - INFO - ascend:	None
05/05 20:00:41 - mmengine - INFO - coreml:	None
05/05 20:00:41 - mmengine - INFO - tvm:	None
05/05 20:00:41 - mmengine - INFO - vacc:	None
05/05 20:00:41 - mmengine - INFO - 

05/05 20:00:41 - mmengine - INFO - **********Codebase information**********
05/05 20:00:41 - mmengine - INFO - mmdet:	3.0.0
05/05 20:00:41 - mmengine - INFO - mmseg:	None
05/05 20:00:41 - mmengine - INFO - mmcls:	None
05/05 20:00:41 - mmengine - INFO - mmocr:	None
05/05 20:00:41 - mmengine - INFO - mmedit:	None
05/05 20:00:41 - mmengine - INFO - mmdet3d:	None
05/05 20:00:41 - mmengine - INFO - mmpose:	None
05/05 20:00:41 - mmengine - INFO - mmrotate:	None
05/05 20:00:41 - mmengine - INFO - mmaction:	None
05/05 20:00:41 - mmengine - INFO - mmrazor:	1.0.0
```

### Error traceback

```Shell
Process Process-2:
Traceback (most recent call last):
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/onnx/export.py", line 131, in export
    torch.onnx.export(
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/onnx/optimizer.py", line 11, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/torch/jit/_trace.py", line 121, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: InstanceData
05/05 19:41:34 - mmengine - ERROR - /home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by AllentDan** [comment]
Please use configs in [mmyolo](https://github.com/open-mmlab/mmyolo/tree/main/configs/deploy) to do the conversion.

**Comment by WeitaoVan** [comment]
Thanks. Problem solved.

**Comment by 459737087** [comment]
great question!!!! sloved my problem

**Comment by bnddwwj** [comment]
> 谢谢。问题解决了。
Hello, what method was used to solve this problem?

**Comment by bnddwwj** [comment]
> 谢谢。问题解决了。

您好，请问使用了什么方法解决的这个问题呢？
