### ISSUE TITLE
[Bug]  Can't export GFL with R101 backbone from my own checkpoint

### ISSUE THREAD

**Issue by GeorgePearse** [open-mmlab/mmdeploy#2066]
### Checklist

- [x] I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [x] 3. The bug has not been fixed in the latest version.

### Describe the bug

Problem when I try to convert my GFL r101 checkpoint to ONNX, but not the COCO checkpoint (e.g. gfl_r101_fpn_mstrain_2x_coco_20200629_200126-dd12f847.pth) 

```
05/09 19:31:33 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/09 19:31:33 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/09 19:31:36 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
05/09 19:31:37 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/09 19:31:37 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: iter=15000_map50=0.406.pth
/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:108: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 63, in torch2onnx
    torch_model = task_processor.build_pytorch_model(model_checkpoint)
  File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmdeploy/codebase/base/task.py", line 123, in build_pytorch_model
    load_checkpoint(model, model_checkpoint, map_location=self.device)
  File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 636, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 548, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 330, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 347, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 881, in __setstate__
    self.process_group = _get_default_group()
  File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 697, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

### Reproduction

```
python mmdeploy/tools/deploy.py mmdeploy/configs/mmdet/detection/detection_onnxruntime_static.py mmdetection/models/gfl_r101.py iter=15000_map50=0.406.pth <image-path>.png --test-img <image-name> --work-dir exports/onnx_static --device cpu --log-level INFO --show --dump-info
```

**Comment by RunningLeon** [comment]
@GeorgePearse hi, pls. try if your ckpt can be loaded successfully.
```
            from mmengine.runner.checkpoint import load_checkpoint
            load_checkpoint(model, model_checkpoint, map_location='cpu')
```
