### ISSUE TITLE
Is it possible to add batch inference for a deployed RTMDet model? [Feature] 

### ISSUE THREAD

**Issue by cozeybozey** [open-mmlab/mmdeploy#2075]
### Motivation

In this issue (https://github.com/open-mmlab/mmdeploy/pull/1662) I saw a note that said that currently only single batch inference is supported. I was wondering whether that is still the case and if so whether it is possible to add multiple batch inference. This would make RTMDet inference significantly faster in practice, so I think this would be useful for anyone who wants to use this model.

**Comment by cozeybozey** [comment]
I just realized that I may have confused myself. I thought single batch inference meant that you can only use a batch size of 1 during inference, meaning you can only feed one image at a time. However, that may not have been what the note in https://github.com/open-mmlab/mmdeploy/pull/1662 was referring to. So let me just ask, is it possible to deploy an RTMDet model and then run inference on it with a batch of images? 

I am asking this, because I am currently trying to run a deployed RTMDet model with a batch of images, but I get an error when I do so. I do not get an error when I use a batch size of 1. Thanks for the help in advance!

**Comment by huayuan4396** [comment]
Hi, @cozeybozey , would you please provide some more details about the error you got? (the config file, the command you used, and the error message).

**Comment by cozeybozey** [comment]
I deploy an RTMDet model with the instance-seg_onnxruntime_dynamic.py and rtmdet-ins_s_8xb32-300e_coco.py config files. These are just standard config files from the repository. I then use the rtmdet-ins_s_8xb32-300e_coco_20221121_212604-fdc5d7ec.pth checkpoint along with the image of a bench. These are all files from the repo itself. Afterwards I run an onnxruntime inference session and then I get the following error:
```
2023-05-15 08:53:18.418915241 [E:onnxruntime:, sequential_executor.cc:494 ExecuteKernel] Non-zero status code returned while running Where node. Name:'/Where' Status Message: /Where: condition operand cannot broadcast on dim 0 Condition Shape: {2,80}, X Shape: {1}, Y Shape: {2,8400,80}
Traceback (most recent call last):
  File "onnx_run.py", line 561, in <module>
    onnx_inference.run_inference(use_yolo_nms)
  File "onnx_run.py", line 119, in run_inference
    outputs = session.run(None, {"images": input_tensor}) if "yolo" in self.onnx_path else session.run(None, {"input": input_tensor})
  File "/home/user/miniconda3/envs/onnx_inference/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Where node. Name:'/Where' Status Message: /Where: condition operand cannot broadcast on dim 0 Condition Shape: {2,80}, X Shape: {1}, Y Shape: {2,8400,80}
```

**Comment by zenjieli** [comment]
I got the same problem with YOLOx.

**Comment by cozeybozey** [comment]
Hi I don't mean to be obnoxious, but I was wondering whether there is any follow up to this. I would especially like to know whether I am doing something wrong or whether it is a missing feature or a bug. Apparently @zenjieli also ran into the same problem with YOLOx, so it might be a bug? Thanks for the help in advance!

**Comment by zenjieli** [comment]
> I see this issue has been marked as stale, but I still have this issue. Does anyone know whether there indeed is a bug in RTMDet when it comes to batch inference on an ONNX model?

It is a bug as I said early and the fix is straightforward. We just need one to send a pull request.

**Comment by zenjieli** [comment]
> Ow sorry, I didn't really understand the issue (#2006) exactly so I didn't know the fix for YOLOx would also fix the issue with RTMDet. So now we are just waiting for the pull request that fixes that issue, which should then also fix the RTMDet issue?

I just checked the code in mmdeploy/codebase/mmdet/models/dense_heads/yolox_head.py. The bug seems fixed in commit 8c45ea4. Did you try it?

**Comment by cozeybozey** [comment]
After pulling main, I still get the same issue with the Where operator not working unfortunately. According to ONNX this is what it says the shapes are:
![image](https://github.com/open-mmlab/mmdeploy/assets/71214958/910c74c2-b4fb-4cac-bf99-7716b33a157f)
This also seems wrong right? It would seem to me that the X Shape should be {32} (which is the batch size in my case).

**Comment by zenjieli** [comment]
> After pulling main, I still get the same issue with the Where operator not working unfortunately. According to ONNX this is what it says the shapes are: ![image](https://user-images.githubusercontent.com/71214958/245706204-910c74c2-b4fb-4cac-bf99-7716b33a157f.png) This also seems wrong right? It would seem to me that the X Shape should be {32} (which is the batch size in my case).

Yes. X shape should be {32}, but I don't see this error with RTMDet. Which config file and model pth file do you use? Can you share them?

**Comment by cozeybozey** [comment]
Yes of course. For mmdeploy I am using this config: mmdeploy/configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py. 
And for mmdetection I am using this config: mmdetection/configs/rtmdet/rtmdet-ins_s_8xb32-300e_coco.py.
And then for the model I am using this model: mmdetection/checkpoints/rtmdet-ins_s_8xb32-300e_coco_20221121_212604-fdc5d7ec.pth. 

So these should all be models and checkpoints from mmdeploy or mmdetection.

**Comment by zenjieli** [comment]
> Yes of course. For mmdeploy I am using this config: mmdeploy/configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py. And for mmdetection I am using this config: mmdetection/configs/rtmdet/rtmdet-ins_s_8xb32-300e_coco.py. And then for the model I am using this model: mmdetection/checkpoints/rtmdet-ins_s_8xb32-300e_coco_20221121_212604-fdc5d7ec.pth.
> 
> So these should all be models and checkpoints from mmdeploy or mmdetection.

Score filtering and NMS for batch inference are supported in mmdeploy/codebase/mmdet/models/dense_heads/rtmdet_head.py but not in rtmdet_ins_head.py. So rtmdet_s_8xb32-300e_coco_20220905_161602-387a891e.pth (for object detection) works for batch inference deployment but rtmdet-ins_s_8xb32-300e_coco_20221121_212604-fdc5d7ec.pth (for instant segmentation) doesn't. The bug in rtmdet_ins_head.py need to be fixed.

**Comment by cozeybozey** [comment]
Great, thanks for figuring that out! Do you think it can be fixed soon or is it a difficult bug to solve?

**Comment by cozeybozey** [comment]
Hi, I was wondering if there are any updates on the bug fix?

**Comment by RunningLeon** [comment]
@zenjieli @cozeybozey hi, guys. Could you try this pr https://github.com/open-mmlab/mmdeploy/pull/2343? batch inference should be fixed for ort.
