### ISSUE TITLE
[Bug] AttributeError: MMYOLO when deploying pruned model

### ISSUE THREAD

**Issue by WeitaoVan** [open-mmlab/mmdeploy#2076]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hi,
I'm using the [MMrazor GroupFisher](https://github.com/open-mmlab/mmrazor/blob/main/configs/pruning/mmdet/group_fisher/retinanet/script.sh) method to prune yolo model. When I export the pruned model to onnx, an error occurred.

More information: 
I can successfully use mmdeploy to convert a normal yolo model like the following scripts. This error only occurred when I tried to convert the pruned model using the mmrazor configs.
```bash
python tools/deploy.py     ../mmyolo/configs/deploy/detection_onnxruntime_static.py     ../mmyolo/configs/yolov8/yolov8_s_syncbn_fast_8xb16-500e_coco.py     ../mmyolo/weights/best_coco_bbox_mAP_epoch_277.pth     ../mmyolo/demo/demo.jpg     --work-dir mmdeploy_model/mmyolo     --device cpu     --dump-info
```

### Reproduction

razor_config=configs/pruning/mmyolo/group_fisher/yolov8/group_fisher_flops_deploy_yolov8_mobile.py
deploy_config=$MMYOLO_ROOT"configs/deploy/detection_onnxruntime_static.py"

python $MMDEPLOY_ROOT"tools/deploy.py" $deploy_config \
    $razor_config \
    $finetune_model_path \
    $MMYOLO_ROOT"/demo/dog.jpg" \
    --work-dir ./work_dirs/mmdeploy

### Environment

```Shell
05/05 20:00:41 - mmengine - INFO - 

05/05 20:00:41 - mmengine - INFO - **********Environmental information**********
05/05 20:00:41 - mmengine - INFO - sys.platform: linux
05/05 20:00:41 - mmengine - INFO - Python: 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:57:39) [GCC 9.3.0]
05/05 20:00:41 - mmengine - INFO - CUDA available: True
05/05 20:00:41 - mmengine - INFO - numpy_random_seed: 2147483648
05/05 20:00:41 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3080
05/05 20:00:41 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.7
05/05 20:00:41 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.64
05/05 20:00:41 - mmengine - INFO - GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
05/05 20:00:41 - mmengine - INFO - PyTorch: 1.13.0
05/05 20:00:41 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

05/05 20:00:41 - mmengine - INFO - TorchVision: 0.14.0
05/05 20:00:41 - mmengine - INFO - OpenCV: 4.7.0
05/05 20:00:41 - mmengine - INFO - MMEngine: 0.7.2
05/05 20:00:41 - mmengine - INFO - MMCV: 2.0.0
05/05 20:00:41 - mmengine - INFO - MMCV Compiler: GCC 9.3
05/05 20:00:41 - mmengine - INFO - MMCV CUDA Compiler: 11.7
05/05 20:00:41 - mmengine - INFO - MMDeploy: 1.0.0+840adcf
05/05 20:00:41 - mmengine - INFO - 

05/05 20:00:41 - mmengine - INFO - **********Backend information**********
05/05 20:00:41 - mmengine - INFO - tensorrt:	None
05/05 20:00:41 - mmengine - INFO - ONNXRuntime:	1.14.1
05/05 20:00:41 - mmengine - INFO - ONNXRuntime-gpu:	None
05/05 20:00:41 - mmengine - INFO - ONNXRuntime custom ops:	Available
05/05 20:00:41 - mmengine - INFO - pplnn:	None
05/05 20:00:41 - mmengine - INFO - ncnn:	None
05/05 20:00:41 - mmengine - INFO - snpe:	None
05/05 20:00:41 - mmengine - INFO - openvino:	None
05/05 20:00:41 - mmengine - INFO - torchscript:	1.13.0
05/05 20:00:41 - mmengine - INFO - torchscript custom ops:	NotAvailable
05/05 20:00:41 - mmengine - INFO - rknn-toolkit:	None
05/05 20:00:41 - mmengine - INFO - rknn-toolkit2:	None
05/05 20:00:41 - mmengine - INFO - ascend:	None
05/05 20:00:41 - mmengine - INFO - coreml:	None
05/05 20:00:41 - mmengine - INFO - tvm:	None
05/05 20:00:41 - mmengine - INFO - vacc:	None
05/05 20:00:41 - mmengine - INFO - 

05/05 20:00:41 - mmengine - INFO - **********Codebase information**********
05/05 20:00:41 - mmengine - INFO - mmdet:	3.0.0
05/05 20:00:41 - mmengine - INFO - mmseg:	None
05/05 20:00:41 - mmengine - INFO - mmcls:	None
05/05 20:00:41 - mmengine - INFO - mmocr:	None
05/05 20:00:41 - mmengine - INFO - mmedit:	None
05/05 20:00:41 - mmengine - INFO - mmdet3d:	None
05/05 20:00:41 - mmengine - INFO - mmpose:	None
05/05 20:00:41 - mmengine - INFO - mmrotate:	None
05/05 20:00:41 - mmengine - INFO - mmaction:	None
05/05 20:00:41 - mmengine - INFO - mmrazor:	1.0.0
```

### Error traceback

```Shell
05/12 20:30:13 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
Process Process-2:
Traceback (most recent call last):
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/pytorch2onnx.py", line 61, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/utils/utils.py", line 46, in build_task_processor
    import_codebase(codebase_type, custom_module_list)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/codebase/__init__.py", line 34, in import_codebase
    importlib.import_module(f'{custom_module}')
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/wwt/project/mmyolo/mmyolo/deploy/__init__.py", line 5, in <module>
    from .object_detection import MMYOLO, YOLOObjectDetection
  File "/home/wwt/project/mmyolo/mmyolo/deploy/object_detection.py", line 14, in <module>
    @CODEBASE.register_module(Codebase.MMYOLO.value)
  File "/home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/enum.py", line 352, in __getattr__
    raise AttributeError(name) from None
AttributeError: MMYOLO
05/12 20:30:13 - mmengine - ERROR - /home/wwt/anaconda3/envs/mmcv2_torch113/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by WeitaoVan** [comment]
Problem solved.
Solution:
One needs to add `MMYOLO` into the enum class `Codebase` in mmdeploy/utils/constants.py
