### ISSUE TITLE
[Bug]  -dump-info convert .pth to .onnx failed!

### ISSUE THREAD

**Issue by blaoke** [open-mmlab/mmdeploy#2085]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

when I convert .pth to onnx , if I add `--dump-info` in the last , got this error. If I remove `--dump-info`,  result onnx file is fine.
I want to use  `python demo/python/object_detection.py cpu out_file pic_filename`, cause SDK file pipeline.json not got, I'm stucked. help me!! @irexyc

### Reproduction

python ./tools/deploy.py configs/mmdet/detection/detection_onnxruntime_dynamic.py /home/lb/wendang/znjs/small_obj/GFocalV2/configs/gfocal/gfocal_r50_fpn_ms2x.py /home/lb/wendang/znjs/small_obj/GFocalV2/gfocal_r50_fpn_ms2x.pth /home/lb/wendang/znjs/small_obj/GFocalV2/demo/demo.jpg --work-dir ./out --device cuda:0 --show

### Environment

```Shell
2023-05-17 18:08:36,429 - mmdeploy - INFO - 

2023-05-17 18:08:36,429 - mmdeploy - INFO - **********Environmental information**********
2023-05-17 18:08:37,437 - mmdeploy - INFO - sys.platform: linux
2023-05-17 18:08:37,437 - mmdeploy - INFO - Python: 3.8.10 (default, Jun  4 2021, 15:09:15) [GCC 7.5.0]
2023-05-17 18:08:37,437 - mmdeploy - INFO - CUDA available: True
2023-05-17 18:08:37,437 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
2023-05-17 18:08:37,437 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda-11.3
2023-05-17 18:08:37,437 - mmdeploy - INFO - NVCC: Build cuda_11.3.r11.3/compiler.29920130_0
2023-05-17 18:08:37,437 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2023-05-17 18:08:37,437 - mmdeploy - INFO - PyTorch: 1.10.1+cu113
2023-05-17 18:08:37,437 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

2023-05-17 18:08:37,437 - mmdeploy - INFO - TorchVision: 0.11.2+cu113
2023-05-17 18:08:37,437 - mmdeploy - INFO - OpenCV: 4.7.0
2023-05-17 18:08:37,437 - mmdeploy - INFO - MMCV: 1.4.0
2023-05-17 18:08:37,437 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2023-05-17 18:08:37,437 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2023-05-17 18:08:37,437 - mmdeploy - INFO - MMDeploy: 0.14.0+c737563
2023-05-17 18:08:37,437 - mmdeploy - INFO - 

2023-05-17 18:08:37,437 - mmdeploy - INFO - **********Backend information**********
2023-05-17 18:08:37,458 - mmdeploy - INFO - tensorrt:	None
2023-05-17 18:08:37,492 - mmdeploy - INFO - ONNXRuntime:	1.9.0
2023-05-17 18:08:37,492 - mmdeploy - INFO - ONNXRuntime-gpu:	1.9.0
2023-05-17 18:08:37,492 - mmdeploy - INFO - ONNXRuntime custom ops:	Available
2023-05-17 18:08:37,493 - mmdeploy - INFO - pplnn:	None
2023-05-17 18:08:37,496 - mmdeploy - INFO - ncnn:	None
2023-05-17 18:08:37,497 - mmdeploy - INFO - snpe:	None
2023-05-17 18:08:37,498 - mmdeploy - INFO - openvino:	None
2023-05-17 18:08:37,500 - mmdeploy - INFO - torchscript:	1.10.1+cu113
2023-05-17 18:08:37,500 - mmdeploy - INFO - torchscript custom ops:	NotAvailable
2023-05-17 18:08:37,564 - mmdeploy - INFO - rknn-toolkit:	None
2023-05-17 18:08:37,564 - mmdeploy - INFO - rknn2-toolkit:	None
2023-05-17 18:08:37,566 - mmdeploy - INFO - ascend:	None
2023-05-17 18:08:37,567 - mmdeploy - INFO - coreml:	None
2023-05-17 18:08:37,569 - mmdeploy - INFO - tvm:	None
2023-05-17 18:08:37,569 - mmdeploy - INFO - 

2023-05-17 18:08:37,569 - mmdeploy - INFO - **********Codebase information**********
2023-05-17 18:08:37,570 - mmdeploy - INFO - mmdet:	2.18.1
2023-05-17 18:08:37,570 - mmdeploy - INFO - mmseg:	None
2023-05-17 18:08:37,570 - mmdeploy - INFO - mmcls:	None
2023-05-17 18:08:37,570 - mmdeploy - INFO - mmocr:	None
2023-05-17 18:08:37,570 - mmdeploy - INFO - mmedit:	None
2023-05-17 18:08:37,570 - mmdeploy - INFO - mmdet3d:	None
2023-05-17 18:08:37,570 - mmdeploy - INFO - mmpose:	None
2023-05-17 18:08:37,570 - mmdeploy - INFO - mmrotate:	None
2023-05-17 18:08:37,570 - mmdeploy - INFO - mmaction:	None
```

### Error traceback

```Shell
python ./tools/deploy.py configs/mmdet/detection/detection_onnxruntime_dynamic.py /home/lb/wendang/znjs/small_obj/GFocalV2/configs/gfocal/gfocal_r50_fpn_ms2x.py /home/lb/wendang/znjs/small_obj/GFocalV2/gfocal_r50_fpn_ms2x.pth /home/lb/wendang/znjs/small_obj/GFocalV2/demo/demo.jpg --work-dir ./out --device cuda:0 --show

 I got this error
```
Traceback (most recent call last):
  File "./tools/deploy.py", line 308, in <module>
    main()
  File "./tools/deploy.py", line 129, in main
    export2SDK(
  File "/home/lb/wendang/code-OpenSource/MMlab/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 457, in export2SDK
    pipeline_info = get_pipeline(deploy_cfg, model_cfg, work_dir, device)
  File "/home/lb/wendang/code-OpenSource/MMlab/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 395, in get_pipeline
    postprocess = get_postprocess(deploy_cfg, model_cfg, device)
  File "/home/lb/wendang/code-OpenSource/MMlab/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 327, in get_postprocess
    params = task_processor.get_postprocess()
  File "/home/lb/wendang/code-OpenSource/MMlab/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 306, in get_postprocess
    postprocess = self.model_cfg.model.test_cfg
  File "/home/lb/miniconda3/envs/gfocalv1_0/lib/python3.8/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'
```
```

**Comment by irexyc** [comment]
Some fields of your custom config may miss compared to official configs.

You can have a look as https://github.com/implus/GFocalV2/blob/bfcc2b9fbbcad714cff59dacc8fb1111ce381cda/configs/gfocal/gfocal_r50_fpn_1x.py#L53-L58


If that doesn't help, please provide the full model config by: 

```python
from mmcv import Config
model_config = Config.fromfile('/home/lb/wendang/znjs/small_obj/GFocalV2/configs/gfocal/gfocal_r50_fpn_ms2x.py')
model_config.dump('model_config.py')
```
