### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 6sz** [open-mmlab/mmdeploy#2101]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

An error occurred while using the script to install mmdeploy

### Reproduction

Install using the 'python3 tools/scripts/build_ubuntu_x64_ncnn. py' command
No modifications were made to the script，But there was an appeal error

### Environment

```Shell
addict                    2.4.0                    pypi_0    pypi
blas                      1.0                         mkl    defaults
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
certifi                   2023.5.7                 pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cudatoolkit               11.1.74              h6bb024c_0    nvidia
cycler                    0.11.0                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
fonttools                 4.39.4                   pypi_0    pypi
freetype                  2.12.1               hca18f0e_1    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.6.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    defaults
jpeg                      9e                   h0b41bf4_3    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.15                 hfd0df8a_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libdeflate                1.17                 h0b41bf4_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libuv                     1.44.2               h166bdaf_0    conda-forge
libwebp-base              1.3.0                h0b41bf4_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
markdown                  3.4.3                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0            py38h95df7f1_0    conda-forge
mkl_fft                   1.3.1            py38h8666266_1    conda-forge
mkl_random                1.2.2            py38h1abd341_0    conda-forge
mmcv-full                 1.5.1                    pypi_0    pypi
mmengine                  0.7.3                    pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
ncnn                      1.0.20230223             pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
numpy                     1.24.3           py38h14f4228_0    defaults
numpy-base                1.24.3           py38h31eccc5_0    defaults
opencv-python             4.7.0.72                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openmim                   0.3.7                    pypi_0    pypi
openssl                   1.1.1t               h0b41bf4_0    conda-forge
ordered-set               4.1.0                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.1                    pypi_0    pypi
pillow                    9.4.0            py38hde6dc18_1    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
portalocker               2.7.0                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pygments                  2.15.1                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.8.0                h357f687_5    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.10.0          py3.8_cuda11.1_cudnn8.0.5_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
requests                  2.30.0                   pypi_0    pypi
rich                      13.3.5                   pypi_0    pypi
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.42.0               h2c6b66d_0    conda-forge
tabulate                  0.9.0                    pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1                    pypi_0    pypi
torchaudio                0.10.0               py38_cu111    pytorch
torchvision               0.11.1               py38_cu111    pytorch
tqdm                      4.65.0                   pypi_0    pypi
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023.3                   pypi_0    pypi
urllib3                   2.0.2                    pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yapf                      0.33.0                   pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

### Error traceback

```Shell
----------build and install pyncnn----------
-- CMAKE_INSTALL_PREFIX = /home/lsz/Documents/code/mmdeploy-dep/ncnn/build/install
-- NCNN_VERSION_STRING = 1.0.20230522
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - broken
CMake Error at /home/lsz/Documents/software/cmake-3.20.0-linux-x86_64/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/lsz/Documents/code/mmdeploy-dep/ncnn/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_15465/fast && /usr/bin/make  -f CMakeFiles/cmTC_15465.dir/build.make CMakeFiles/cmTC_15465.dir/build
    make[1]: Entering directory '/home/lsz/Documents/code/mmdeploy-dep/ncnn/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_15465.dir/testCCompiler.c.o
    /usr/bin/cc    -o CMakeFiles/cmTC_15465.dir/testCCompiler.c.o -c /home/lsz/Documents/code/mmdeploy-dep/ncnn/build/CMakeFiles/CMakeTmp/testCCompiler.c
    cc1: error: /usr/local/include/x86_64-linux-gnu: Permission denied
    make[1]: *** [CMakeFiles/cmTC_15465.dir/build.make:78: CMakeFiles/cmTC_15465.dir/testCCompiler.c.o] Error 1
    make[1]: Leaving directory '/home/lsz/Documents/code/mmdeploy-dep/ncnn/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:127: cmTC_15465/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:48 (project)


-- Configuring incomplete, errors occurred!
See also "/home/lsz/Documents/code/mmdeploy-dep/ncnn/build/CMakeFiles/CMakeOutput.log".
See also "/home/lsz/Documents/code/mmdeploy-dep/ncnn/build/CMakeFiles/CMakeError.log".
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/lsz/Documents/code/mmdeploy-dep/ncnn/python
ERROR: file:///home/lsz/Documents/code/mmdeploy-dep/ncnn/python does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Traceback (most recent call last):
  File "tools/scripts/build_ubuntu_x64_ncnn.py", line 185, in <module>
    main()
  File "tools/scripts/build_ubuntu_x64_ncnn.py", line 174, in main
    ncnn_cmake_dir = install_pyncnn(dep_dir)
  File "tools/scripts/build_ubuntu_x64_ncnn.py", line 96, in install_pyncnn
    assert (os.path.exists(ncnn_cmake_dir))
AssertionError
```

**Comment by tpoisonooo** [comment]
Manually build and install ncnn and  pyncnn by this [doc](https://github.com/Tencent/ncnn/wiki/how-to-build)
And give these outputs:
```bash
$ gcc --version
$ g++ --version
$ cmake -- version
```

**Comment by 6sz** [comment]
> ```shell
> cmake -- version
> ```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
cmake version 3.20.0

Is my version of gcc too high？

**Comment by tpoisonooo** [comment]
`cmake` and `gcc` version is fine. 
There is a `cc1: error: /usr/local/include/x86_64-linux-gnu: Permission denied` in your log, please check dir permission and manually build pyncnn

**Comment by tpoisonooo** [comment]
cc @6sz
