### ISSUE TITLE
[Bug] Docker image is not buildable

### ISSUE THREAD

**Issue by Charlyo** [open-mmlab/mmdeploy#2117]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

As of today May the 25th 2023, the gpu docker image is not buildable.

### Reproduction

With the command
`docker build docker/GPU/ -t mmdeploy:inside --build-arg  USE_SRC_INSIDE=true
`

### Environment

```Shell
Ubuntu 22.04
Latest docker available
```

### Error traceback

```Shell
`#0 1485.0       Traceback (most recent call last):
#0 1485.0         File "<string>", line 2, in <module>
#0 1485.0         File "<pip-setuptools-caller>", line 34, in <module>
#0 1485.0         File "/tmp/pip-install-29vnhsu2/mmcv_22d241b9107144329235081e2c8206df/setup.py", line 314, in <module>
#0 1485.0           setup(
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
#0 1485.0           return distutils.core.setup(**attrs)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
#0 1485.0           return run_commands(dist)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#0 1485.0           dist.run_commands()
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
#0 1485.0           self.run_command(cmd)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
#0 1485.0           super().run_command(command)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 1485.0           cmd_obj.run()
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
#0 1485.0           return orig.install.run(self)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/command/install.py", line 698, in run
#0 1485.0           self.run_command('build')
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
#0 1485.0           self.distribution.run_command(command)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
#0 1485.0           super().run_command(command)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 1485.0           cmd_obj.run()
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
#0 1485.0           self.run_command(cmd_name)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
#0 1485.0           self.distribution.run_command(command)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
#0 1485.0           super().run_command(command)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 1485.0           cmd_obj.run()
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
#0 1485.0           _build_ext.run(self)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
#0 1485.0           _build_ext.build_ext.run(self)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
#0 1485.0           self.build_extensions()
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 735, in build_extensions
#0 1485.0           build_ext.build_extensions(self)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
#0 1485.0           _build_ext.build_ext.build_extensions(self)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
#0 1485.0           self._build_extensions_serial()
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
#0 1485.0           self.build_extension(ext)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
#0 1485.0           _build_ext.build_extension(self, ext)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
#0 1485.0           objects = self.compiler.compile(
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 599, in compile
#0 1485.0           self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 483, in unix_wrap_single_compile
#0 1485.0           cflags = unix_cuda_flags(cflags)
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 450, in unix_cuda_flags
#0 1485.0           cflags + _get_cuda_arch_flags(cflags))
#0 1485.0         File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1606, in _get_cuda_arch_flags
#0 1485.0           arch_list[-1] += '+PTX'
#0 1485.0       IndexError: list index out of range
#0 1485.0       [end of output]
#0 1485.0   
#0 1485.0   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 1485.0 error: legacy-install-failure
#0 1485.0 
#0 1485.0 × Encountered error while trying to install package.
#0 1485.0 ╰─> mmcv
`
```

**Comment by irexyc** [comment]
Have you modified the Dockerfile? 

Normally, there shouldn't be building process for mmcv as mmcv provide the prebuilt package. (https://github.com/open-mmlab/mmdeploy/blob/main/docker/GPU/Dockerfile#LL52C20-L52C23)

**Comment by Charlyo** [comment]
No, I have not modified it.

**Comment by irexyc** [comment]
You can you this image 
https://hub.docker.com/layers/openmmlab/mmdeploy/ubuntu20.04-cuda11.3-mmdeploy1.1.0/images/sha256-1637dadb3633bbdee9bfd2f57c3d29d8af967fc8b6d6470a186ec3df2b78bd36?context=explore

**Comment by qraleq** [comment]
I'm observing the same error when trying to build the image myself. Is there a fix for this?

**Comment by RunningLeon** [comment]
@qraleq hi, why not use the built image `openmmlab/mmdeploy:ubuntu20.04-cuda11.3-mmdeploy1.1.0`?

**Comment by RunningLeon** [comment]
Sorry for the confusion. Will update the document later.

**Comment by mchaniotakis** [comment]
This is still an issue.
