### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by clveryang** [open-mmlab/mmdeploy#2119]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I use following code to build a yolox in tensorrt engine ：

  python3 ./tools/deploy.py \
  mmdeploy-main/configs/mmdet/detection/detection_tensorrt-fp16_dynamic-64x64-800x800.py \
  mmdeploy-main/mmdetection/configs/yolox/yolox_s_8xb8-300e_coco.py \
  "mmdeploy_checkpoints/mmdet/yolox/yolox_s_8x8_300e_coco_20211121_095711-4592a793.pth" \
  "mmdetection/demo/demo.jpg"  \
  --work-dir "../mmdeploy_regression_working_dir/mmdet/yolox/tensorrt/dynamic/fp16/yolox_s_8x8_300e_coco_20211121_095711-4592a793"  \
  --device cuda:0  \
  --log-level INFO \
  --test-img ./tests/data/tiger.jpeg

I change code to let the engine in a dynamic shape :
_base_ = ['../_base_/base_dynamic.py', '../../_base_/backends/tensorrt.py']

backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 64, 64],
                    opt_shape=[1, 3, 800, 800],
                    max_shape=[64, 3, 800, 800])))
    ])

Then, I try to test this engine:

  python3 tools/test.py \
  configs/mmdet/detection/detection_tensorrt-fp16_dynamic-64x64-800x800.py \
  mmdeploy-main/mmdetection/configs/yolo/yolov3_d53_8xb8-320-273e_coco.py \
  --model ../mmdeploy_regression_working_dir/mmdet/yolov3/tensorrt/dynamic/fp16/yolov3_d53_320_273e_coco-421362b6/end2end.engine \
  --work-dir "mmdeploy_regression_working_dir/mmdet/yolov3/tensorrt/dynamic/fp16/yolov3_d53_320_273e_coco-421362b6/backend/test_logs" \
  --speed-test \
  --device cuda:0 \
  --batch-size N \
  --cfg-options test_dataloader.num_workers=0 test_dataloader.persistent_workers=False val_dataloader.num_workers=0 val_dataloader.persistent_workers=False 

I find that only N equal as 1 this engine can run. If i set the N > 1 , the engine inference is failure

### Reproduction

python3 ./tools/deploy.py \
  mmdeploy-main/configs/mmdet/detection/detection_tensorrt-fp16_dynamic-64x64-800x800.py \
  mmdeploy-main/mmdetection/configs/yolox/yolox_s_8xb8-300e_coco.py \
  "mmdeploy_checkpoints/mmdet/yolox/yolox_s_8x8_300e_coco_20211121_095711-4592a793.pth" \
  "mmdetection/demo/demo.jpg"  \
  --work-dir "../mmdeploy_regression_working_dir/mmdet/yolox/tensorrt/dynamic/fp16/yolox_s_8x8_300e_coco_20211121_095711-4592a793"  \
  --device cuda:0  \
  --log-level INFO \
  --test-img ./tests/data/tiger.jpeg

  python3 tools/test.py \
  configs/mmdet/detection/detection_tensorrt-fp16_dynamic-64x64-800x800.py \
  mmdeploy-main/mmdetection/configs/yolo/yolov3_d53_8xb8-320-273e_coco.py \
  --model ../mmdeploy_regression_working_dir/mmdet/yolov3/tensorrt/dynamic/fp16/yolov3_d53_320_273e_coco-421362b6/end2end.engine \
  --work-dir "mmdeploy_regression_working_dir/mmdet/yolov3/tensorrt/dynamic/fp16/yolov3_d53_320_273e_coco-421362b6/backend/test_logs" \
  --speed-test \
  --device cuda:0 \
  --batch-size N \
  --cfg-options test_dataloader.num_workers=0 test_dataloader.persistent_workers=False val_dataloader.num_workers=0 val_dataloader.persistent_workers=False 

### Environment

```Shell
torch 1.12.0
tensorrt  8.6.0
mmcls    1.0.0
mmcv     2.0.0
mmdeploy   1.1.0
mmdet      3.0.0    
mmengine   0.7.2
```

### Error traceback

```Shell
[05/26/2023-16:47:24] [TRT] [E] 7: [shapeMachine.cpp::executeContinuation::864] Error Code 7: Internal Error (Where_799: dimensions not compatible for select Broadcast has incompatible dimensions: 128 != 8400 && 128 != 1 && 8400 != 1. Instruction: CHECK_BROADCAST 128 8400.)
Traceback (most recent call last):
  File "tools/test.py", line 159, in <module>
    main()
  File "tools/test.py", line 150, in main
    runner.test()
  File "/home/zhichao.yang/miniconda3/envs/yang_kiwi/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1752, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/home/zhichao.yang/miniconda3/envs/yang_kiwi/lib/python3.8/site-packages/mmengine/runner/loops.py", line 438, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/home/zhichao.yang/miniconda3/envs/yang_kiwi/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/home/zhichao.yang/miniconda3/envs/yang_kiwi/lib/python3.8/site-packages/mmengine/evaluator/metric.py", line 115, in evaluate
    _metrics = self.compute_metrics(results)  # type: ignore
  File "/home/zhichao.yang/mmdeploy-main/mmdetection/mmdet/evaluation/metrics/coco_metric.py", line 419, in compute_metrics
    result_files = self.results2json(preds, outfile_prefix)
  File "/home/zhichao.yang/mmdeploy-main/mmdetection/mmdet/evaluation/metrics/coco_metric.py", line 262, in results2json
    dump(bbox_json_results, result_files['bbox'])
  File "/home/zhichao.yang/miniconda3/envs/yang_kiwi/lib/python3.8/site-packages/mmengine/fileio/io.py", line 931, in dump
    handler.dump_to_fileobj(obj, f, **kwargs)
  File "/home/zhichao.yang/miniconda3/envs/yang_kiwi/lib/python3.8/site-packages/mmengine/fileio/handlers/json_handler.py", line 32, in dump_to_fileobj
    json.dump(obj, file, **kwargs)
  File "/home/zhichao.yang/miniconda3/envs/yang_kiwi/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/zhichao.yang/miniconda3/envs/yang_kiwi/lib/python3.8/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/home/zhichao.yang/miniconda3/envs/yang_kiwi/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/zhichao.yang/miniconda3/envs/yang_kiwi/lib/python3.8/json/encoder.py", line 397, in _iterencode_dict
    yield _floatstr(value)
  File "/home/zhichao.yang/miniconda3/envs/yang_kiwi/lib/python3.8/json/encoder.py", line 236, in floatstr
    return _repr(o)
KeyboardInterrupt
```

**Comment by clveryang** [comment]
traceback  add:
shape = tuple(self.context.get_binding_shape(idx))
ValueError: __len__() should return >= 0

**Comment by northagain** [comment]
有进展吗兄弟 我也是batchsize改不成
