### ISSUE TITLE
[Bug] onnx2ncnn failed

### ISSUE THREAD

**Issue by dungng27** [open-mmlab/mmdeploy#2137]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

When I deploy my mmsegmentation model, which is this [model](https://github.com/open-mmlab/mmsegmentation/tree/main/configs/mobilenet_v3), to ncnn, it returned the error:
```
AssertionError: onnx2ncnn failed
```

### Reproduction

I run this command in my docker workspace to deploy the model using quantize mode and it returns the error:
```
python3 /workspaces/PheNet_Occupancy/mmdeploy/tools/deploy.py  \
        /workspaces/PheNet_Occupancy/my_src/deploy_cfg/ncnn/segmentation_ncnn_static-768x768.py  \
        /workspaces/PheNet_Occupancy/training_logs/2cls_40kiters_extaugs/mobilenet-v3-d8-s_lraspp_occupancy.py \
        /workspaces/PheNet_Occupancy/training_logs/2cls_40kiters_extaugs/iter_36000.pth \
        /workspaces/PheNet_Occupancy/data/bev_occupancy/test/images/12_59.png   \
        --work-dir /workspaces/PheNet_Occupancy/deployed_model \
        --device cpu \
        --quant \
        --quant-image-dir /workspaces/PheNet_Occupancy/data/bev_occupancy/test/images \
        --show
```

Before that, these are the commands I used to build ncnn:
```
$ apt install -y build-essential git cmake libprotobuf-dev protobuf-compiler libvulkan-dev vulkan-utils libopencv-dev

$ git clone https://github.com/Tencent/ncnn.git \
    && cd ncnn \
    && mkdir -p build \
    && cd build 
$ cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=ON \
    -DNCNN_SYSTEM_GLSLANG=ON -DNCNN_BUILD_EXAMPLES=ON \
    -DNCNN_PYTHON=ON -DNCNN_SHARED_LIB=ON ..
$ make \
    && make install 
$ cd .. \
    && export NCNN_DIR=$(pwd) \
    && export LD_LIBRARY_PATH=${NCNN_DIR}/build/install/lib/:$LD_LIBRARY_PATH
$ cd ${NCNN_DIR}/python \
    && pip install -e .

# Custom ops
$ cd ${MMDEPLOY_DIR} \
    && mkdir -p build && cd build \
    && cmake -DCMAKE_CXX_COMPILER=g++-7 -DMMDEPLOY_TARGET_BACKENDS=ncnn -Dncnn_DIR=${NCNN_DIR}/build/install/lib/cmake/ncnn .. \
    && make -j$(nproc) && make install
```

In `/workspaces/PheNet_Occupancy/my_src/deploy_cfg/ncnn/segmentation_ncnn_int8_static-768x768.py` file I modified a little bit:
```
_base_ = ['../segmentation_static.py', '../_base_/backends/ncnn-int8.py']

onnx_config = dict(input_shape=[768, 768])
```
where `[768, 768]` is my model's input shape

### Environment

```Shell
Here is my environment:
05/31 07:50:35 - mmengine - INFO - 

05/31 07:50:35 - mmengine - INFO - **********Environmental information**********
05/31 07:50:36 - mmengine - INFO - sys.platform: linux
05/31 07:50:36 - mmengine - INFO - Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
05/31 07:50:36 - mmengine - INFO - CUDA available: True
05/31 07:50:36 - mmengine - INFO - numpy_random_seed: 2147483648
05/31 07:50:36 - mmengine - INFO - GPU 0: NVIDIA GeForce GTX 1660 SUPER
05/31 07:50:36 - mmengine - INFO - CUDA_HOME: None
05/31 07:50:36 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
05/31 07:50:36 - mmengine - INFO - PyTorch: 1.10.0
05/31 07:50:36 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

05/31 07:50:36 - mmengine - INFO - TorchVision: 0.11.0
05/31 07:50:36 - mmengine - INFO - OpenCV: 4.6.0
05/31 07:50:36 - mmengine - INFO - MMEngine: 0.7.3
05/31 07:50:36 - mmengine - INFO - MMCV: 2.0.0
05/31 07:50:36 - mmengine - INFO - MMCV Compiler: GCC 9.3
05/31 07:50:36 - mmengine - INFO - MMCV CUDA Compiler: 11.3
05/31 07:50:36 - mmengine - INFO - MMDeploy: 1.0.0+36a1a7e
05/31 07:50:36 - mmengine - INFO - 

05/31 07:50:36 - mmengine - INFO - **********Backend information**********
05/31 07:50:36 - mmengine - INFO - tensorrt:    None
05/31 07:50:36 - mmengine - INFO - ONNXRuntime: 1.8.1
05/31 07:50:36 - mmengine - INFO - ONNXRuntime-gpu:     None
05/31 07:50:36 - mmengine - INFO - ONNXRuntime custom ops:      Available
05/31 07:50:36 - mmengine - INFO - pplnn:       None
05/31 07:50:36 - mmengine - INFO - ncnn:        1.0.20230531
05/31 07:50:36 - mmengine - INFO - ncnn custom ops:     Available
05/31 07:50:36 - mmengine - INFO - snpe:        None
05/31 07:50:36 - mmengine - INFO - openvino:    2022.3.0
05/31 07:50:36 - mmengine - INFO - torchscript: 1.10.0
05/31 07:50:36 - mmengine - INFO - torchscript custom ops:      NotAvailable
05/31 07:50:36 - mmengine - INFO - rknn-toolkit:        None
05/31 07:50:36 - mmengine - INFO - rknn-toolkit2:       None
05/31 07:50:36 - mmengine - INFO - ascend:      None
05/31 07:50:36 - mmengine - INFO - coreml:      None
05/31 07:50:36 - mmengine - INFO - tvm: None
05/31 07:50:36 - mmengine - INFO - vacc:        None
05/31 07:50:36 - mmengine - INFO - 

05/31 07:50:36 - mmengine - INFO - **********Codebase information**********
05/31 07:50:36 - mmengine - INFO - mmdet:       None
05/31 07:50:36 - mmengine - INFO - mmseg:       1.0.0
05/31 07:50:36 - mmengine - INFO - mmpretrain:  None
05/31 07:50:36 - mmengine - INFO - mmocr:       None
05/31 07:50:36 - mmengine - INFO - mmagic:      None
05/31 07:50:36 - mmengine - INFO - mmdet3d:     None
05/31 07:50:36 - mmengine - INFO - mmpose:      None
05/31 07:50:36 - mmengine - INFO - mmrotate:    None
05/31 07:50:36 - mmengine - INFO - mmaction:    None
05/31 07:50:36 - mmengine - INFO - mmrazor:     1.0.0
```

### Error traceback

```Shell
05/31 08:03:58 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
05/31 08:03:58 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
05/31 08:03:58 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "mmseg_tasks" registry tree. As a workaround, the current "mmseg_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/hsigmoid.py:35: UserWarning: In MMCV v1.4.4, we modified the default value of args to align with PyTorch official. Previous Implementation: Hsigmoid(x) = min(max((x + 1) / 2, 0), 1). Current Implementation: Hsigmoid(x) = min(max((x + 3) / 6, 0), 1).
  warnings.warn(
/workspaces/PheNet_Occupancy/mmsegmentation/mmseg/models/decode_heads/decode_head.py:120: UserWarning: For binary segmentation, we suggest using`out_channels = 1` to define the outputchannels of segmentor, and use `threshold`to convert `seg_logits` into a predictionapplying a threshold
  warnings.warn('For binary segmentation, we suggest using'
/workspaces/PheNet_Occupancy/mmsegmentation/mmseg/models/builder.py:36: UserWarning: ``build_loss`` would be deprecated soon, please use ``mmseg.registry.MODELS.build()`` 
  warnings.warn('``build_loss`` would be deprecated soon, please use '
/workspaces/PheNet_Occupancy/mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
Loads checkpoint by local backend from path: /workspaces/PheNet_Occupancy/training_logs/2cls_40kiters_extaugs/iter_36000.pth
05/31 08:03:58 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
05/31 08:03:58 - mmengine - INFO - Export PyTorch model to ONNX: /workspaces/PheNet_Occupancy/deployed_model/end2end.onnx.
05/31 08:03:58 - mmengine - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
/root/workspace/mmdeploy/mmdeploy/pytorch/functions/getattribute.py:19: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ret = torch.Size([int(s) for s in ret])
/root/workspace/mmdeploy/mmdeploy/pytorch/functions/size.py:23: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ret = [int(r) for r in ret]
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::AdaptiveAvgPool2d type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
05/31 08:04:13 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
05/31 08:04:13 - mmengine - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in main process
Unknown data type 0
Traceback (most recent call last):
  File "/workspaces/PheNet_Occupancy/mmdeploy/tools/deploy.py", line 335, in <module>
    main()
  File "/workspaces/PheNet_Occupancy/mmdeploy/tools/deploy.py", line 259, in main
    backend_files = to_backend(
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/utils/utils.py", line 98, in to_backend
    return backend_mgr.to_backend(
  File "/root/workspace/mmdeploy/mmdeploy/backend/ncnn/backend_manager.py", line 141, in to_backend
    from_onnx(onnx_path, osp.join(work_dir, onnx_name))
  File "/root/workspace/mmdeploy/mmdeploy/backend/ncnn/onnx2ncnn.py", line 72, in from_onnx
    assert ret_code == 0, 'onnx2ncnn failed'
AssertionError: onnx2ncnn failed
```

**Comment by oym050922021** [comment]
@dungng27 hi,  has this problem been solved? I have the same problem.
