### ISSUE TITLE
[Docs]  rtmpose  rk1126

### ISSUE THREAD

**Issue by JunGenius** [open-mmlab/mmdeploy#2152]
### 📚 The doc issue

Hello, author, I would like to ask a few questions.
   1. Does rtmpose support reasoning on rk1126 ?
   2. I can successfully convert the rknn model using pose-detection_simcc_rknn-fp16_static-256x256.py, but when initializing the model, the error is reported as follows.
        
 ```
 python mmdeploy-1.1.0/tools/deploy.py \
 mmdeploy-1.1.0/configs/mmpose/pose-detection_simcc_rknn-fp16_static-256x256.py \
 mmpose-1.0.0/configs/face_2d_keypoint/rtmpose/wflw/rtmpose-m_8xb64-60e_wflw-256x256.py \
 mmpose-1.0.0/checkpoints/rtmpose-m_simcc-wflw_pt-aic-coco_60e-256x256-dc1dcdcf_20230228.pth \
 imgs/face.jpg \
 --work-dir work-dirs/mmpose/rtmpose
     
 # ------------------ init model ------------------
  --> Init runtime environment
  librknn_runtime version 1.7.3 (5047ff8 build: 2022-08-13 12:11:22 base: 1131)
  E [op_setup:199]Error permute dims '3' vs '4'
  E [setup_node:448]Setup node[188] PERMUTE fail
  Create rknn graph fail!
  Create RKNN model fail, error=-6
  E Catch exception when init runtime!
  E Traceback (most recent call last):
  E   File "rknn/api/rknn_base.py", line 936, in rknn.api.rknn_base.RKNNBase.init_runtime
  E   File "rknn/api/rknn_runtime.py", line 341, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
  E Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID
  E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
  E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
  Init runtime environment failed
```

 3. I used pose-detection_simcc_rknn-int8_static-256x256.py, but failed to convert the rknn model, the error is as follows.

```
python mmdeploy-1.1.0/tools/deploy.py \
mmdeploy-1.1.0/configs/mmpose/pose-detection_simcc_rknn-int8_static-256x256.py \
mmpose-1.0.0/configs/face_2d_keypoint/rtmpose/wflw/rtmpose-m_8xb64-60e_wflw-256x256.py \
mmpose-1.0.0/checkpoints/rtmpose-m_simcc-wflw_pt-aic-coco_60e-256x256-dc1dcdcf_20230228.pth \
imgs/face.jpg \
--work-dir work-dirs/mmpose/rtmpose

# ------------------------------------------------

E Catch exception when building RKNN model!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 486, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build_layer
E   File "rknn/base/RKNNlib/layer/RKNNlayer.py", line 293, in rknn.base.RKNNlib.layer.RKNNlayer.RKNNLayer.compute_tensor
E   File "rknn/base/RKNNlib/layer/matmullayer.py", line 120, in rknn.base.RKNNlib.layer.matmullayer.MatmulLayer.compute_out_tensor
E   File "/home/qh/.conda/envs/mmdeploy38/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
E     raise e.with_traceback(filtered_tb) from None
E   File "/home/qh/.conda/envs/mmdeploy38/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2013, in _create_c_op
E     raise ValueError(e.message)
E ValueError: Dimensions must be equal, but are 128 and 1 for '{{node MatMul_MatMul_241_23/MatMul}} = BatchMatMulV2[T=DT_FLOAT, adj_x=false, adj_y=false](Squeeze_Squeeze_238_27/cond/Identity, MatMul_MatMul_241_23_reshape_for_in1_261/cond/Identity)' with input shapes: [1,98,128], [98,1,1,128].
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
06/05 16:22:32 - mmengine - ERROR - /home/qh/workspace/train/openmmlab_1.0.0/mmdeploy-1.1.0/mmdeploy/backend/rknn/onnx2rknn.py - onnx2rknn - 92 - Build model failed!

```

Can you provide some advice on how I can solve these problems ?  thank you very much.

**Comment by AllentDan** [comment]
Does other mmpose models such as hrnetv2 work fine? Besides, please paste the log info of `python tools/check_env.py`.

**Comment by JunGenius** [comment]
> Does other mmpose models such as hrnetv2 work fine? Besides, please paste the log info of `python tools/check_env.py`.

Yes, hrnetv2 works fine.

`python tools/check_env.py`
```
06/05 21:08:34 - mmengine - INFO - **********Environmental information**********
06/05 21:08:34 - mmengine - INFO - sys.platform: linux
06/05 21:08:34 - mmengine - INFO - Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
06/05 21:08:34 - mmengine - INFO - CUDA available: True
06/05 21:08:34 - mmengine - INFO - numpy_random_seed: 2147483648
06/05 21:08:34 - mmengine - INFO - GPU 0: GeForce RTX 2080 Ti
06/05 21:08:34 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-10.2
06/05 21:08:34 - mmengine - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.8
06/05 21:08:34 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
06/05 21:08:34 - mmengine - INFO - PyTorch: 1.8.0
06/05 21:08:34 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

06/05 21:08:34 - mmengine - INFO - TorchVision: 0.9.0
06/05 21:08:34 - mmengine - INFO - OpenCV: 4.7.0
06/05 21:08:34 - mmengine - INFO - MMEngine: 0.7.3
06/05 21:08:34 - mmengine - INFO - MMCV: 2.0.0
06/05 21:08:34 - mmengine - INFO - MMCV Compiler: GCC 7.3
06/05 21:08:34 - mmengine - INFO - MMCV CUDA Compiler: 10.2
06/05 21:08:34 - mmengine - INFO - MMDeploy: 1.1.0+
06/05 21:08:34 - mmengine - INFO -

06/05 21:08:34 - mmengine - INFO - **********Backend information**********
06/05 21:08:34 - mmengine - INFO - tensorrt:    None
06/05 21:08:35 - mmengine - INFO - ONNXRuntime: 1.13.1
06/05 21:08:35 - mmengine - INFO - ONNXRuntime-gpu:     None
06/05 21:08:35 - mmengine - INFO - ONNXRuntime custom ops:      NotAvailable
06/05 21:08:35 - mmengine - INFO - pplnn:       None
06/05 21:08:35 - mmengine - INFO - ncnn:        None
06/05 21:08:35 - mmengine - INFO - snpe:        None
06/05 21:08:35 - mmengine - INFO - openvino:    None
06/05 21:08:35 - mmengine - INFO - torchscript: 1.8.0
06/05 21:08:35 - mmengine - INFO - torchscript custom ops:      NotAvailable
/home/qh/.conda/envs/mmdeploy38/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
06/05 21:08:35 - mmengine - INFO - rknn-toolkit:        1.7.3
06/05 21:08:35 - mmengine - INFO - rknn-toolkit2:       None
06/05 21:08:35 - mmengine - INFO - ascend:      None
06/05 21:08:35 - mmengine - INFO - coreml:      None
06/05 21:08:35 - mmengine - INFO - tvm: None
06/05 21:08:35 - mmengine - INFO - vacc:        None
06/05 21:08:35 - mmengine - INFO -

06/05 21:08:35 - mmengine - INFO - **********Codebase information**********
06/05 21:08:35 - mmengine - INFO - mmdet:       3.0.0
06/05 21:08:35 - mmengine - INFO - mmseg:       None
06/05 21:08:35 - mmengine - INFO - mmpretrain:  None
06/05 21:08:35 - mmengine - INFO - mmocr:       None
06/05 21:08:35 - mmengine - INFO - mmagic:      None
06/05 21:08:35 - mmengine - INFO - mmdet3d:     None
06/05 21:08:35 - mmengine - INFO - mmpose:      1.0.0
06/05 21:08:35 - mmengine - INFO - mmrotate:    None
06/05 21:08:35 - mmengine - INFO - mmaction:    None
06/05 21:08:35 - mmengine - INFO - mmrazor:     None


```

**Comment by AllentDan** [comment]
Well, rtmpose configuration that you used contains both `RTMCCHead` and `CSPNeXt` while neither of them was tested on rv1126. I am afraid that you have to debug and find out what exactly causes the error through a binary search. Willing to provide advice when you working on that.

**Comment by JunGenius** [comment]
> Well, rtmpose configuration that you used contains both `RTMCCHead` and `CSPNeXt` while neither of them was tested on rv1126. I am afraid that you have to debug and find out what exactly causes the error through a binary search. Willing to provide advice when you working on that.

Ok, thanks for your reply. I will try to find the error.
