### ISSUE TITLE
[Bug]  convert mmocr‘s textrecog pth model to onnx error

### ISSUE THREAD

**Issue by leemayi** [open-mmlab/mmdeploy#2182]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I use mmdeploy convert mmocr model to tensortrt model geting some errors:

2023-06-14 14:37:38,637 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2023-06-14 14:37:38,637 - mmdeploy - INFO - Export PyTorch model to ONNX: D:\mmdep\mm\datas\ocr_mydata2\rec\trt\end2end.onnx.
2023-06-14 14:37:38,651 - mmdeploy - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
d:\mmdep\mm\mmdeploy\mmdeploy\codebase\mmocr\models\text_recognition\base.py:51: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  img_shape = [int(val) for val in img_shape]
d:\mmdep\mm\mmdeploy\mmdeploy\codebase\mmocr\models\text_recognition\base.py:51: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  img_shape = [int(val) for val in img_shape]
d:\mmdep\mm\mmdeploy\mmdeploy\pytorch\functions\multi_head_attention_forward.py:23: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  q = q / math.sqrt(E)
C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\mmcv\cnn\bricks\wrappers.py:170: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if x.numel() == 0 and obsolete_torch_version(TORCH_VERSION, (1, 5)):
d:\mmdep\mm\mmocr\mmocr\models\textrecog\decoders\abinet_language_decoder.py:147: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  out = torch.where(abn, out, out.new_tensor(logit.shape[1]))
Traceback (most recent call last):
  File ".\export_fast_2x_ocr_rec_mydata2.py", line 15, in <module>
    torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\onnx\export.py", line 122, in export
    torch.onnx.export(
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\__init__.py", line 350, in export
    return utils.export(
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 163, in export
    _export(
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "d:\mmdep\mm\mmdeploy\mmdeploy\core\rewriters\rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\onnx\optimizer.py", line 10, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 727, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 602, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 517, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\jit\_trace.py", line 1175, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\core\rewriters\rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\codebase\mmocr\models\text_recognition\base.py", line 53, in base_recognizer__forward
    return self.simple_test(img, img_metas, **kwargs)
  File "d:\mmdep\mm\mmocr\mmocr\models\textrecog\recognizer\abinet.py", line 163, in simple_test
    out_dec = self.decoder(
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "d:\mmdep\mm\mmocr\mmocr\models\textrecog\decoders\base_decoder.py", line 30, in forward
    return self.forward_test(feat, out_enc, img_metas)
  File "d:\mmdep\mm\mmocr\mmocr\models\textrecog\decoders\abinet_language_decoder.py", line 133, in forward_test
    return self.forward_train(feat, out_enc, None, img_metas)
  File "d:\mmdep\mm\mmocr\mmocr\models\textrecog\decoders\abinet_language_decoder.py", line 104, in forward_train
    lengths = self._get_length(logits)
  File "d:\mmdep\mm\mmocr\mmocr\models\textrecog\decoders\abinet_language_decoder.py", line 147, in _get_length
    out = torch.where(abn, out, out.new_tensor(logit.shape[1]))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Reproduction

this is my convert script :

from mmdeploy.apis import torch2onnx
from mmdeploy.apis.tensorrt import onnx2tensorrt
from mmdeploy.backend.sdk.export_info import export2SDK
import os

img = 'D:\\mmdep\\mm\\datas\\ocr_mydata2\\rec\\1.jpg'
work_dir = 'D:\\mmdep\\mm\\datas\\ocr_mydata2\\rec\\trt'
save_file = 'end2end.onnx'
deploy_cfg = 'mmdeploy/configs/mmocr/text-recognition/text-recognition_tensorrt_dynamic-32x32-32x640.py'
model_cfg = 'D:\\mmdep\\mm\\datas\\ocr_mydata2\\rec\\config.py'
model_checkpoint = 'D:\\mmdep\\mm\\datas\\ocr_mydata2\\rec\\latest.pth'
device = 'cuda'

# 1. convert model to IR(onnx)
torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  model_checkpoint, device)

# 2. convert IR to tensorrt
onnx_model = os.path.join(work_dir, save_file)
save_file = 'end2end.engine'
model_id = 0
device = 'cuda'
onnx2tensorrt(work_dir, save_file, model_id, deploy_cfg, onnx_model, device)

# 3. extract pipeline info for sdk use (dump-info)
export2SDK(deploy_cfg, model_cfg, work_dir, pth=model_checkpoint, device=device)

### Environment

```Shell
2023-06-14 14:44:43,896 - mmdeploy - INFO - sys.platform: win32
2023-06-14 14:44:43,897 - mmdeploy - INFO - Python: 3.8.15 (default, Nov 24 2022, 14:38:14) [MSC v.1916 64 bit (AMD64)]
2023-06-14 14:44:43,897 - mmdeploy - INFO - CUDA available: True
2023-06-14 14:44:43,897 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3060
2023-06-14 14:44:43,897 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
2023-06-14 14:44:43,897 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.112
2023-06-14 14:44:43,897 - mmdeploy - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.33.31629 版
2023-06-14 14:44:43,898 - mmdeploy - INFO - GCC: n/a
2023-06-14 14:44:43,898 - mmdeploy - INFO - PyTorch: 1.12.1+cu116
2023-06-14 14:44:43,898 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

2023-06-14 14:44:43,899 - mmdeploy - INFO - TorchVision: 0.13.1+cu116
2023-06-14 14:44:43,899 - mmdeploy - INFO - OpenCV: 4.5.4
2023-06-14 14:44:43,899 - mmdeploy - INFO - MMCV: 1.7.1
2023-06-14 14:44:43,899 - mmdeploy - INFO - MMCV Compiler: MSVC 192829924
2023-06-14 14:44:43,900 - mmdeploy - INFO - MMCV CUDA Compiler: 11.6
2023-06-14 14:44:43,900 - mmdeploy - INFO - MMDeploy: 0.11.0+
2023-06-14 14:44:43,900 - mmdeploy - INFO -

2023-06-14 14:44:43,900 - mmdeploy - INFO - **********Backend information**********
2023-06-14 14:44:43,984 - mmdeploy - INFO - tensorrt:   8.2.3.0
2023-06-14 14:44:43,984 - mmdeploy - INFO - tensorrt custom ops:        Available
2023-06-14 14:44:43,988 - mmdeploy - INFO - ONNXRuntime:        None
2023-06-14 14:44:43,990 - mmdeploy - INFO - pplnn:      None
2023-06-14 14:44:44,019 - mmdeploy - INFO - ncnn:       None
2023-06-14 14:44:44,078 - mmdeploy - INFO - snpe:       None
2023-06-14 14:44:44,082 - mmdeploy - INFO - openvino:   None
2023-06-14 14:44:44,085 - mmdeploy - INFO - torchscript:        1.12.1+cu116
2023-06-14 14:44:44,086 - mmdeploy - INFO - torchscript custom ops:     NotAvailable
2023-06-14 14:44:44,203 - mmdeploy - INFO - rknn-toolkit:       None
2023-06-14 14:44:44,204 - mmdeploy - INFO - rknn2-toolkit:      None
2023-06-14 14:44:44,207 - mmdeploy - INFO - ascend:     None
2023-06-14 14:44:44,210 - mmdeploy - INFO - coreml:     None
2023-06-14 14:44:44,213 - mmdeploy - INFO - tvm:        None
2023-06-14 14:44:44,214 - mmdeploy - INFO -

2023-06-14 14:44:44,214 - mmdeploy - INFO - **********Codebase information**********
2023-06-14 14:44:44,221 - mmdeploy - INFO - mmdet:      2.26.0
2023-06-14 14:44:44,221 - mmdeploy - INFO - mmseg:      None
2023-06-14 14:44:44,221 - mmdeploy - INFO - mmcls:      0.25.0
2023-06-14 14:44:44,221 - mmdeploy - INFO - mmocr:      0.6.3
2023-06-14 14:44:44,222 - mmdeploy - INFO - mmedit:     None
2023-06-14 14:44:44,222 - mmdeploy - INFO - mmdet3d:    None
2023-06-14 14:44:44,222 - mmdeploy - INFO - mmpose:     None
2023-06-14 14:44:44,222 - mmdeploy - INFO - mmrotate:   None
2023-06-14 14:44:44,222 - mmdeploy - INFO - mmaction:   None
```

### Error traceback

```Shell
2023-06-14 14:37:38,637 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2023-06-14 14:37:38,637 - mmdeploy - INFO - Export PyTorch model to ONNX: D:\mmdep\mm\datas\ocr_mydata2\rec\trt\end2end.onnx.
2023-06-14 14:37:38,651 - mmdeploy - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
d:\mmdep\mm\mmdeploy\mmdeploy\codebase\mmocr\models\text_recognition\base.py:51: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  img_shape = [int(val) for val in img_shape]
d:\mmdep\mm\mmdeploy\mmdeploy\codebase\mmocr\models\text_recognition\base.py:51: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  img_shape = [int(val) for val in img_shape]
d:\mmdep\mm\mmdeploy\mmdeploy\pytorch\functions\multi_head_attention_forward.py:23: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  q = q / math.sqrt(E)
C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\mmcv\cnn\bricks\wrappers.py:170: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if x.numel() == 0 and obsolete_torch_version(TORCH_VERSION, (1, 5)):
d:\mmdep\mm\mmocr\mmocr\models\textrecog\decoders\abinet_language_decoder.py:147: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  out = torch.where(abn, out, out.new_tensor(logit.shape[1]))
Traceback (most recent call last):
  File ".\export_fast_2x_ocr_rec_mydata2.py", line 15, in <module>
    torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\onnx\export.py", line 122, in export
    torch.onnx.export(
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\__init__.py", line 350, in export
    return utils.export(
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 163, in export
    _export(
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "d:\mmdep\mm\mmdeploy\mmdeploy\core\rewriters\rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\apis\onnx\optimizer.py", line 10, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 727, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 602, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 517, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\jit\_trace.py", line 1175, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\core\rewriters\rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "d:\mmdep\mm\mmdeploy\mmdeploy\codebase\mmocr\models\text_recognition\base.py", line 53, in base_recognizer__forward
    return self.simple_test(img, img_metas, **kwargs)
  File "d:\mmdep\mm\mmocr\mmocr\models\textrecog\recognizer\abinet.py", line 163, in simple_test
    out_dec = self.decoder(
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jushiPC\.conda\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "d:\mmdep\mm\mmocr\mmocr\models\textrecog\decoders\base_decoder.py", line 30, in forward
    return self.forward_test(feat, out_enc, img_metas)
  File "d:\mmdep\mm\mmocr\mmocr\models\textrecog\decoders\abinet_language_decoder.py", line 133, in forward_test
    return self.forward_train(feat, out_enc, None, img_metas)
  File "d:\mmdep\mm\mmocr\mmocr\models\textrecog\decoders\abinet_language_decoder.py", line 104, in forward_train
    lengths = self._get_length(logits)
  File "d:\mmdep\mm\mmocr\mmocr\models\textrecog\decoders\abinet_language_decoder.py", line 147, in _get_length
    out = torch.where(abn, out, out.new_tensor(logit.shape[1]))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by AllentDan** [comment]
Please try the latest mmdeploy.

**Comment by AllentDan** [comment]
I mean the error could be fixed in the latest MMDeploy. ABINet was not supported in the version of 0.11.
