### ISSUE TITLE
[Bug] when I use end2end.engine to predict image, It failed

### ISSUE THREAD

**Issue by 459737087** [open-mmlab/mmdeploy#2212]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

first 
```
python mmdeploy/tools/deploy.py     mmdeploy/configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py     mmdetection/configs/faster_rcnn/faster-rcnn_r50_fpn_1x_coco.py     checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth     mmdetection/demo/demo.jpg     --work-dir mmdeploy_model/faster-rcnn     --device cuda     --dump-info
```
I got end2end.engine 
then I use this engine to predict image

### Reproduction

```
import tensorrt as trt
import pycuda.autoinit
import pycuda.driver as cuda
import numpy as np
import cv2
import torch
# 加载TensorRT的engine文件，创建TensorRT的推理引擎
# engine_path = "/output/mmdeploy_model/yolov/end2end.engine"

 
import tensorrt as trt
import pycuda.driver as cuda
import pycuda.autoinit
from torchvision import transforms
import numpy as np
from PIL import Image
import time
import argparse

def loadEngine2TensorRT(filepath):
    G_LOGGER = trt.Logger(trt.Logger.WARNING)
    # 反序列化引擎
    with open(filepath, "rb") as f, trt.Runtime(G_LOGGER) as runtime:
        engine = runtime.deserialize_cuda_engine(f.read())
        return engine

def do_inference(engine, batch_size, input, output_shape):

    # 创建上下文
    context = engine.create_execution_context()
    output = np.empty(output_shape, dtype=np.float32)

    # 分配内存
    d_input = cuda.mem_alloc(1 * input.size * input.dtype.itemsize)
    d_output = cuda.mem_alloc(1 * output.size * output.dtype.itemsize)
    bindings = [int(d_input), int(d_output)]

    # pycuda操作缓冲区
    stream = cuda.Stream()
    # 将输入数据放入device
    cuda.memcpy_htod_async(d_input, input, stream)

    start = time.time()
    # 执行模型
    context.execute_async(batch_size, bindings, stream.handle, None)
    # 将预测结果从从缓冲区取出
    cuda.memcpy_dtoh_async(output, d_output, stream)
    end = time.time()

    # 线程同步
    stream.synchronize()

    print("\nTensorRT {} test:".format(engine_path.split('/')[-1].split('.')[0]))
    print("output:", output)
    print("time cost:", end - start)

def get_shape(engine):
    for binding in engine:
        if engine.binding_is_input(binding):
            input_shape = engine.get_binding_shape(binding)
        else:
            output_shape = engine.get_binding_shape(binding)
    return input_shape, output_shape

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description = "TensorRT do inference")
    parser.add_argument("--batch_size", type=int, default=1, help='batch_size')
    parser.add_argument("--img_path", type=str, default='test_image/1.jpg', help='cache_file')
    parser.add_argument("--engine_file_path", type=str, default='my_files/test.engine', help='engine_file_path')
    args = parser.parse_args()
    engine_path = "/output/mmdeploy_model/yolov/end2end.engine"
    args.img_path = "7117_00000.jpg"
    # engine_path = args.engine_file_path
    engine = loadEngine2TensorRT(engine_path)
    img = Image.open(args.img_path)
    print("----------------------engine", engine)
    input_shape, output_shape = get_shape(engine)
    transform = transforms.Compose([
        transforms.Resize([input_shape[1], input_shape[2]]),  # [h,w]
        transforms.ToTensor()
        ])
    img = transform(img).unsqueeze(0)
    img = img.numpy()

    do_inference(engine, args.batch_size, img, output_shape)
```

### Environment

```Shell
mmcv                 2.0.0
mmdeploy             1.1.0
mmdeploy-runtime     1.1.0
mmdeploy-runtime-gpu 1.1.0
mmdet                3.0.0
mmengine             0.7.4
mmyolo               0.5.0
torch                1.10.0
onnx                 1.14.0
onnxruntime-gpu      1.8.1
openmim              0.3.7
```

### Error traceback

```Shell
File "untitled.py", line 77, in <module>
    input_shape, output_shape = get_shape(engine)
  File "untitled.py", line 58, in get_shape
    for binding in engine:
TypeError: 'NoneType' object is not iterable
```

**Comment by Ji-Hu** [comment]
How about conversion on CPU? (--device CPU)
In my case, the onnx model converted on CPU and inferenced on cuda.
I'm not sure tensorrt case, but onnx model converted on cuda doesn't work well too.
I hope this might be help

**Comment by 459737087** [comment]
> How about conversion on CPU? (--device CPU) In my case, the onnx model converted on CPU and inferenced on cuda. I'm not sure tensorrt case, but onnx model converted on cuda doesn't work well too. I hope this might be help

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/output/.pylibs/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/output/.pylibs/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 63, in torch2onnx
    torch_model = task_processor.build_pytorch_model(model_checkpoint)
  File "/output/.pylibs/lib/python3.8/site-packages/mmdeploy/codebase/base/task.py", line 123, in build_pytorch_model
    load_checkpoint(model, model_checkpoint, map_location=self.device)
  File "/output/.pylibs/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 636, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/output/.pylibs/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 548, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/output/.pylibs/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 330, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/output/.pylibs/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 347, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 787, in _legacy_load
    result = unpickler.load()
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 743, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 824, in restore_location
    return default_restore_location(storage, map_location)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 178, in default_restore_location
    raise RuntimeError("don't know how to restore data location of "
RuntimeError: don't know how to restore data location of torch.FloatStorage (tagged with CPU)
```
it reported error

**Comment by RunningLeon** [comment]
@459737087 hi, did you check the saved drawn image in the `work-dir` after running `deploy.py`?  BTW, why not use `TRTWrapper` from mmdeploy?
https://github.com/open-mmlab/mmdeploy/blob/a5de11947891d6ef25a308785a55c700f88c8d74/mmdeploy/backend/tensorrt/wrapper.py#L56

**Comment by 459737087** [comment]
> @459737087 hi, did you check the saved drawn image in the `work-dir` after running `deploy.py`? BTW, why not use `TRTWrapper` from mmdeploy?
> 
> https://github.com/open-mmlab/mmdeploy/blob/a5de11947891d6ef25a308785a55c700f88c8d74/mmdeploy/backend/tensorrt/wrapper.py#L56-L76

Hi, I got the image in the work-dir after running deploy.py is correct.

**Comment by 459737087** [comment]
I try this way:
```
 >>> from mmdeploy.backend.tensorrt import TRTWrapper 
 >>> engine_file = 'resnet.engine' 
 >>> model = TRTWrapper(engine_file) 
 >>> inputs = dict(input=torch.randn(1, 3, 224, 224)) 
 >>> outputs = model(inputs) 
 >>> print(outputs) 
```

it works , but why?

**Comment by RunningLeon** [comment]
maybe you did no load trt custom ops in your code
https://github.com/open-mmlab/mmdeploy/blob/a5de11947891d6ef25a308785a55c700f88c8d74/mmdeploy/backend/tensorrt/wrapper.py#L83

**Comment by 459737087** [comment]
Thank you! you're right.  @RunningLeon

**Comment by RunningLeon** [comment]
@459737087 hi, good to know it is solved.
