### ISSUE TITLE
[Bug] Errors when converting rtmpose pth to onnx model

### ISSUE THREAD

**Issue by wanghlsara** [open-mmlab/mmdeploy#2225]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

```
### Describe the bug

root@ebf809ca6cd8:~/workspace/mmdeploy# python tools/deploy.py     configs/mmdet/detection/detection_onnxruntime_static.py     ../mmpose/projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py     https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_nano_8xb32-100e_coco-obj365-person-05d8511e.pth     demo/resources/human-pose.jpg     --work-dir rtmpose-ort/rtmdet-nano     --device cpu     --show     --dump-info 
Traceback (most recent call last):
  File "tools/deploy.py", line 335, in <module>
    main()
  File "tools/deploy.py", line 123, in main
    deploy_cfg, model_cfg = load_config(deploy_cfg_path, model_cfg_path)
  File "/root/workspace/mmdeploy/mmdeploy/utils/config_utils.py", line 29, in load_config
    configs = [_load_config(cfg) for cfg in args]
  File "/root/workspace/mmdeploy/mmdeploy/utils/config_utils.py", line 29, in <listcomp>
    configs = [_load_config(cfg) for cfg in args]
  File "/root/workspace/mmdeploy/mmdeploy/utils/config_utils.py", line 22, in _load_config
    cfg = mmengine.Config.fromfile(cfg)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/config/config.py", line 178, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/usr/local/lib/python3.8/dist-packages/mmengine/config/config.py", line 488, in _file2dict
    base_cfg_path, scope = Config._get_cfg_path(
  File "/usr/local/lib/python3.8/dist-packages/mmengine/config/config.py", line 692, in _get_cfg_path
    raise ModuleNotFoundError(
ModuleNotFoundError: mmdet is not installed, please install mmdet manually
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7fe89d9c2e50>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tempfile.py", line 579, in __del__
    self.close()
  File "/usr/lib/python3.8/tempfile.py", line 575, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpqtjr4r_i/tmpbfifebdi.py'
root@ebf809ca6cd8:~/workspace/mmdeploy# 
```

### Reproduction

1、download this  image from dockerhub ：
https://hub.docker.com/layers/openmmlab/mmdeploy/ubuntu20.04-cuda11.3-mmdeploy/images/sha256-307b6940638b7b9ff0af99362e0aa1eab56c57a878b3381ebed732d741b610a6?context=explore
2、git clone mmdeploy，mmpose, mmdetection, all of them are the latest versions.  I run pip install -r requirements.txt in all the three folders.
3、in mmdeploy folder，I run python tools/deploy.py  to convert pth to onnx model , and get errors.

### Environment

```Shell
root@ebf809ca6cd8:~/workspace/mmdeploy# python tools/check_env.py
06/29 06:43:22 - mmengine - INFO - 

06/29 06:43:22 - mmengine - INFO - **********Environmental information**********
06/29 06:43:23 - mmengine - INFO - sys.platform: linux
06/29 06:43:23 - mmengine - INFO - Python: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
06/29 06:43:23 - mmengine - INFO - CUDA available: True
06/29 06:43:23 - mmengine - INFO - numpy_random_seed: 2147483648
06/29 06:43:23 - mmengine - INFO - GPU 0,1: NVIDIA GeForce RTX 3080
06/29 06:43:23 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
06/29 06:43:23 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.109
06/29 06:43:23 - mmengine - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
06/29 06:43:23 - mmengine - INFO - PyTorch: 1.10.0+cu113
06/29 06:43:23 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

06/29 06:43:23 - mmengine - INFO - TorchVision: 0.11.0+cu113
06/29 06:43:23 - mmengine - INFO - OpenCV: 4.5.4
06/29 06:43:23 - mmengine - INFO - MMEngine: 0.7.4
06/29 06:43:23 - mmengine - INFO - MMCV: 2.0.0
06/29 06:43:23 - mmengine - INFO - MMCV Compiler: GCC 9.3
06/29 06:43:23 - mmengine - INFO - MMCV CUDA Compiler: 11.3
06/29 06:43:23 - mmengine - INFO - MMDeploy: 1.1.0+e19f6fa
06/29 06:43:23 - mmengine - INFO - 

06/29 06:43:23 - mmengine - INFO - **********Backend information**********
06/29 06:43:23 - mmengine - INFO - tensorrt:    8.2.3.0
06/29 06:43:23 - mmengine - INFO - tensorrt custom ops: NotAvailable
06/29 06:43:23 - mmengine - INFO - ONNXRuntime: None
06/29 06:43:23 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
06/29 06:43:23 - mmengine - INFO - ONNXRuntime custom ops:      NotAvailable
06/29 06:43:23 - mmengine - INFO - pplnn:       0.8.1
06/29 06:43:23 - mmengine - INFO - ncnn:        1.0.20230224
06/29 06:43:23 - mmengine - INFO - ncnn custom ops:     NotAvailable
06/29 06:43:23 - mmengine - INFO - snpe:        None
06/29 06:43:23 - mmengine - INFO - openvino:    2022.3.0
06/29 06:43:23 - mmengine - INFO - torchscript: 1.10.0+cu113
06/29 06:43:23 - mmengine - INFO - torchscript custom ops:      NotAvailable
06/29 06:43:23 - mmengine - INFO - rknn-toolkit:        None
06/29 06:43:23 - mmengine - INFO - rknn-toolkit2:       None
06/29 06:43:23 - mmengine - INFO - ascend:      None
06/29 06:43:23 - mmengine - INFO - coreml:      None
06/29 06:43:23 - mmengine - INFO - tvm: None
06/29 06:43:23 - mmengine - INFO - vacc:        None
06/29 06:43:23 - mmengine - INFO - 

06/29 06:43:23 - mmengine - INFO - **********Codebase information**********
06/29 06:43:23 - mmengine - INFO - mmdet:       None
06/29 06:43:23 - mmengine - INFO - mmseg:       None
06/29 06:43:23 - mmengine - INFO - mmpretrain:  None
06/29 06:43:23 - mmengine - INFO - mmocr:       None
06/29 06:43:23 - mmengine - INFO - mmagic:      None
06/29 06:43:23 - mmengine - INFO - mmdet3d:     None
06/29 06:43:23 - mmengine - INFO - mmpose:      None
06/29 06:43:23 - mmengine - INFO - mmrotate:    None
06/29 06:43:23 - mmengine - INFO - mmaction:    None
06/29 06:43:23 - mmengine - INFO - mmrazor:     None
06/29 06:43:23 - mmengine - INFO - mmyolo:      None
root@ebf809ca6cd8:~/workspace/mmdeploy#
```

**Comment by RunningLeon** [comment]
@wanghlsara hi, you should install mmpose(git clone and from source) and mmdet in the docker container if you want to deploy rtmpose.
```
git clone --depth=1 https://github.com/open-mmlab/mmpose.git
python3 -m pip install -e ./mmpose
python3 -m mim install -r ./mmpose/requirements/mminstall.txt
```

**Comment by yuhanqing1996** [comment]
@wanghlsara  hi guys, I met the same error. I found my config file is not correct. when I fix my config file, I it run correct.

**Comment by wanghlsara** [comment]
@RunningLeon 
Thanks.
Unfortunately, it doesn't work for me.
This error can disappear by installing mmdet and mmpose from pypi, but those pacakages are not suitable for development.
> git clone --depth=1 https://github.com/open-mmlab/mmpose.git
> python3 -m pip install -e ./mmpose
> python3 -m mim install -r ./mmpose/requirements/mminstall.txt


@yuhanqing1996 
Can you tell me how to fix the config file ?
