### ISSUE TITLE
mask rcnn with swin-t backbone engine issues

### ISSUE THREAD

**Issue by runzeer** [open-mmlab/mmdeploy#2232]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I run mask rcnn model with swin-t backbone but with the following issues:
the onnx file has been generated but the engine file can not be generated

Failed to parse onnx, In node 97 (importSlice): UNSUPPORTED_NODE: Assertion failed: (axes.allValuesKnown()) && "This version of TensorRT does not support dynamic axes.

My tensorRT version is 8.6.0 and is the newest. So could the issue can be solved?

### Reproduction

python tools/deploy.py configs/mmdet/instance-seg/instance-seg_tensorrt_static-800x1344.py ../mmdetection_3.0/configs/swin/mask-rcnn_swin-t-p4-w7_fpn_ms-crop-3x_coco.py ../mmdetection_3.0/mask_rcnn_swin-t-p4-w7_fpn_ms-crop-3x_coco_20210906_131725-bacf6f7b.pth ../mmdetection_3.0/demo/demo.jpg --work-dir mmdeploy_model/mask_rcnn_swin_t --device cuda --dump-info

### Environment

```Shell
07/02 05:28:25 - mmengine - INFO - TorchVision: 0.12.0+cu115
07/02 05:28:25 - mmengine - INFO - OpenCV: 4.5.5
07/02 05:28:25 - mmengine - INFO - MMEngine: 0.7.3
07/02 05:28:25 - mmengine - INFO - MMCV: 2.0.1
07/02 05:28:25 - mmengine - INFO - MMCV Compiler: GCC 7.3
07/02 05:28:25 - mmengine - INFO - MMCV CUDA Compiler: 11.5
07/02 05:28:25 - mmengine - INFO - MMDeploy: 1.1.0+
07/02 05:28:25 - mmengine - INFO - 

07/02 05:28:25 - mmengine - INFO - **********Backend information**********
07/02 05:28:25 - mmengine - INFO - tensorrt:	8.6.0
07/02 05:28:25 - mmengine - INFO - tensorrt custom ops:	Available
07/02 05:28:25 - mmengine - INFO - ONNXRuntime:	1.5.1
07/02 05:28:25 - mmengine - INFO - ONNXRuntime-gpu:	1.8.1
07/02 05:28:25 - mmengine - INFO - ONNXRuntime custom ops:	Available
07/02 05:28:25 - mmengine - INFO - pplnn:	None
07/02 05:28:25 - mmengine - INFO - ncnn:	None
07/02 05:28:25 - mmengine - INFO - snpe:	None
07/02 05:28:25 - mmengine - INFO - openvino:	None
07/02 05:28:25 - mmengine - INFO - torchscript:	1.11.0+cu115
07/02 05:28:25 - mmengine - INFO - torchscript custom ops:	NotAvailable
07/02 05:28:25 - mmengine - INFO - rknn-toolkit:	None
07/02 05:28:25 - mmengine - INFO - rknn-toolkit2:	None
07/02 05:28:25 - mmengine - INFO - ascend:	None
07/02 05:28:25 - mmengine - INFO - coreml:	None
07/02 05:28:25 - mmengine - INFO - tvm:	None
07/02 05:28:25 - mmengine - INFO - vacc:	None
07/02 05:28:25 - mmengine - INFO - 

07/02 05:28:25 - mmengine - INFO - **********Codebase information**********
07/02 05:28:25 - mmengine - INFO - mmdet:	3.1.0
07/02 05:28:25 - mmengine - INFO - mmseg:	None
07/02 05:28:25 - mmengine - INFO - mmpretrain:	None
07/02 05:28:25 - mmengine - INFO - mmocr:	None
07/02 05:28:25 - mmengine - INFO - mmagic:	None
07/02 05:28:25 - mmengine - INFO - mmdet3d:	None
07/02 05:28:25 - mmengine - INFO - mmpose:	None
07/02 05:28:25 - mmengine - INFO - mmrotate:	None
07/02 05:28:25 - mmengine - INFO - mmaction:	None
07/02 05:28:25 - mmengine - INFO - mmrazor:	None
```

### Error traceback

```Shell
re details: https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/experimental/onnx_optimizer.md
07/02 05:17:05 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
07/02 05:17:15 - mmengine - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in subprocess
07/02 05:17:15 - mmengine - INFO - Successfully loaded tensorrt plugins from /home/zrz/miniconda3/envs/mmpose/lib/python3.8/site-packages/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
[07/02/2023-05:17:16] [TRT] [I] [MemUsageChange] Init CUDA: CPU +386, GPU +0, now: CPU 444, GPU 2068 (MiB)
[07/02/2023-05:17:22] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1620, GPU +302, now: CPU 2138, GPU 2370 (MiB)
[07/02/2023-05:17:22] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
[07/02/2023-05:17:22] [TRT] [I] ----------------------------------------------------------------
[07/02/2023-05:17:22] [TRT] [I] Input filename:   mmdeploy_model/mask_rcnn_swin_t/end2end.onnx
[07/02/2023-05:17:22] [TRT] [I] ONNX IR version:  0.0.6
[07/02/2023-05:17:22] [TRT] [I] Opset version:    11
[07/02/2023-05:17:22] [TRT] [I] Producer name:    pytorch
[07/02/2023-05:17:22] [TRT] [I] Producer version: 1.11.0
[07/02/2023-05:17:22] [TRT] [I] Domain:           
[07/02/2023-05:17:22] [TRT] [I] Model version:    0
[07/02/2023-05:17:22] [TRT] [I] Doc string:       
[07/02/2023-05:17:22] [TRT] [I] ----------------------------------------------------------------
[07/02/2023-05:17:22] [TRT] [W] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[07/02/2023-05:17:22] [TRT] [E] ModelImporter.cpp:768: While parsing node number 97 [Slice -> "onnx::Slice_329"]:
[07/02/2023-05:17:22] [TRT] [E] ModelImporter.cpp:769: --- Begin node ---
[07/02/2023-05:17:22] [TRT] [E] ModelImporter.cpp:770: input: "onnx::Slice_278"
input: "onnx::Slice_325"
input: "onnx::Slice_326"
input: "onnx::Slice_327"
input: "onnx::Slice_328"
output: "onnx::Slice_329"
name: "Slice_97"
op_type: "Slice"

[07/02/2023-05:17:22] [TRT] [E] ModelImporter.cpp:771: --- End node ---
[07/02/2023-05:17:22] [TRT] [E] ModelImporter.cpp:774: ERROR: builtin_op_importers.cpp:4491 In function importSlice:
[8] Assertion failed: (axes.allValuesKnown()) && "This version of TensorRT does not support dynamic axes."
Process Process-3:
Traceback (most recent call last):
  File "/home/zrz/miniconda3/envs/mmpose/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zrz/miniconda3/envs/mmpose/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zrz/miniconda3/envs/mmpose/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/zrz/miniconda3/envs/mmpose/lib/python3.8/site-packages/mmdeploy/apis/utils/utils.py", line 98, in to_backend
    return backend_mgr.to_backend(
  File "/home/zrz/miniconda3/envs/mmpose/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/backend_manager.py", line 127, in to_backend
    onnx2tensorrt(
  File "/home/zrz/miniconda3/envs/mmpose/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "/home/zrz/miniconda3/envs/mmpose/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/utils.py", line 185, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 97 (importSlice): UNSUPPORTED_NODE: Assertion failed: (axes.allValuesKnown()) && "This version of TensorRT does not support dynamic axes."

07/02 05:17:24 - mmengine - ERROR - /home/zrz/miniconda3/envs/mmpose/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.utils.utils.to_backend` with Call id: 1 failed. exit.
```

**Comment by RunningLeon** [comment]
@runzeer hi, not tested on trt8.6. maybe you could go for [onnx-simplifier](https://github.com/daquexian/onnx-simplifier) to simplify and static the onnx file.
