### ISSUE TITLE
[Bug] AttributeError: 'dict' object has no attribute 'detach'

### ISSUE THREAD

**Issue by Hevislee** [open-mmlab/mmdeploy#2242]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I want to get an int8 model. But when i run: python3 tools/deploy.py configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-nus-64x4.py /home/mmdetection3d/configs/pointpillars/pointpillars_hv_fpn_sbn-all_8xb4-2x_nus-3d.py /home/mmdetection3d/configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d_20210826_104936-fca299c1.pth /home/data/nuscenes/n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951.pcd.bin --device cuda:0 --quant
The error occured：AttributeError: 'dict' object has no attribute 'detach'

### Reproduction

 python3 tools/deploy.py configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-nus-64x4.py /home/mmdetection3d/configs/pointpillars/pointpillars_hv_fpn_sbn-all_8xb4-2x_nus-3d.py /home/mmdetection3d/configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d_20210826_104936-fca299c1.pth /home/data/nuscenes/n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951.pcd.bin --device cuda:0 --quant

I modified the config of: "pointpillars_hv_fpn_sbn-all_8xb4-2x_nus-3d.py"
replace the "_base_ = ['./voxel-detection_dynamic.py', '../../_base_/backends/tensorrt.py']" as "_base_ = ['./voxel-detection_dynamic.py', '../../_base_/backends/tensorrt-int8.py']" to get int8 model 

### Environment

```Shell
07/05 10:54:10 - mmengine - INFO - 07/05 10:54:10 - mmengine - INFO - **********Environmental information**********07/05 10:54:11 - mmengine - INFO - sys.platform: linux07/05 10:54:11 - mmengine - INFO - Python: 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) [GCC 11.3.0]07/05 10:54:11 - mmengine - INFO - CUDA available: True07/05 10:54:11 - mmengine - INFO - numpy_random_seed: 214748364807/05 10:54:11 - mmengine - INFO - GPU 0,1,2,3: NVIDIA GeForce RTX 309007/05 10:54:11 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.107/05 10:54:11 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.1, V11.1.10507/05 10:54:11 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.007/05 10:54:11 - mmengine - INFO - PyTorch: 1.10.0+cu11107/05 10:54:11 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

07/05 10:54:11 - mmengine - INFO - TorchVision: 0.11.0+cu111
07/05 10:54:11 - mmengine - INFO - OpenCV: 4.7.0
07/05 10:54:11 - mmengine - INFO - MMEngine: 0.7.3
07/05 10:54:11 - mmengine - INFO - MMCV: 2.0.0
07/05 10:54:11 - mmengine - INFO - MMCV Compiler: GCC 7.3
07/05 10:54:11 - mmengine - INFO - MMCV CUDA Compiler: 11.1
07/05 10:54:11 - mmengine - INFO - MMDeploy: 1.1.0+439f88b
07/05 10:54:11 - mmengine - INFO - 

07/05 10:54:11 - mmengine - INFO - **********Backend information**********
07/05 10:54:11 - mmengine - INFO - tensorrt:    8.4.2.4
07/05 10:54:11 - mmengine - INFO - tensorrt custom ops: Available
07/05 10:54:11 - mmengine - INFO - ONNXRuntime: None
07/05 10:54:11 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
07/05 10:54:11 - mmengine - INFO - ONNXRuntime custom ops:      NotAvailable
07/05 10:54:11 - mmengine - INFO - pplnn:       None
07/05 10:54:11 - mmengine - INFO - ncnn:        None
07/05 10:54:11 - mmengine - INFO - snpe:        None
07/05 10:54:11 - mmengine - INFO - openvino:    None
07/05 10:54:11 - mmengine - INFO - torchscript: 1.10.0+cu111
07/05 10:54:11 - mmengine - INFO - torchscript custom ops:      NotAvailable
07/05 10:54:11 - mmengine - INFO - rknn-toolkit:        None
07/05 10:54:11 - mmengine - INFO - rknn-toolkit2:       None
07/05 10:54:11 - mmengine - INFO - ascend:      None
07/05 10:54:12 - mmengine - INFO - coreml:      None
07/05 10:54:12 - mmengine - INFO - tvm: None
07/05 10:54:12 - mmengine - INFO - vacc:        None
07/05 10:54:12 - mmengine - INFO - 

07/05 10:54:12 - mmengine - INFO - **********Codebase information**********
07/05 10:54:12 - mmengine - INFO - mmdet:       3.0.0
07/05 10:54:12 - mmengine - INFO - mmseg:       None
07/05 10:54:12 - mmengine - INFO - mmpretrain:  None
07/05 10:54:12 - mmengine - INFO - mmocr:       None
07/05 10:54:12 - mmengine - INFO - mmagic:      None
07/05 10:54:12 - mmengine - INFO - mmdet3d:     1.1.0
07/05 10:54:12 - mmengine - INFO - mmpose:      None
07/05 10:54:12 - mmengine - INFO - mmrotate:    None
07/05 10:54:12 - mmengine - INFO - mmaction:    None
07/05 10:54:12 - mmengine - INFO - mmrazor:     None
```

### Error traceback

```Shell
0%|                                                   | 0/6019 [00:00<?, ?it/s]<class 'dict'>
Process Process-3:
Traceback (most recent call last):
  File "/home/anaconda3/envs/mmdet3d/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/anaconda3/envs/mmdet3d/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/mmdeploy/mmdeploy/apis/calibration.py", line 73, in create_calib_input_data
    create_calib_input_data_impl(
  File "/home/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/mmdeploy/mmdeploy/apis/utils/calibration.py", line 69, in create_calib_input_data
    input_ndarray = input_tensor.detach().cpu().numpy()
```

**Comment by RunningLeon** [comment]
hi, sorry for the trouble. Creating the calib dataset of multi-nputs is not supported by now.
