### ISSUE TITLE
[Bug] KeyError: <Task.VOXEL_DETECTION: 'VoxelDetection'>

### ISSUE THREAD

**Issue by AndrewJSong** [open-mmlab/mmdeploy#2262]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

全部拉取的最新版本代码。
1. mmdeploy无法转换mmdetection的faster_rcnn到tensorrt，可以转onnxruntime。
2. mmdeploy无法转换mmdetection3d的pointpillar和centerpoint到onnxruntime。

### Reproduction

mmdetection模型：
07/09 07:29:01 - mmengine - INFO - Execute onnx optimize passes.
07/09 07:29:02 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
07/09 07:29:03 - mmengine - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in subprocess
07/09 07:29:03 - mmengine - WARNING - Could not load the library of tensorrt plugins.             Because the file does not exist: 
[07/09/2023-07:29:03] [TRT] [I] [MemUsageChange] Init CUDA: CPU +570, GPU +0, now: CPU 643, GPU 857 (MiB)
[07/09/2023-07:29:04] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +542, GPU +116, now: CPU 1237, GPU 973 (MiB)
[07/09/2023-07:29:04] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
[07/09/2023-07:29:04] [TRT] [I] ----------------------------------------------------------------
[07/09/2023-07:29:04] [TRT] [I] Input filename:   mmdeploy_model/faster_rcnn/end2end.onnx
[07/09/2023-07:29:04] [TRT] [I] ONNX IR version:  0.0.6
[07/09/2023-07:29:04] [TRT] [I] Opset version:    11
[07/09/2023-07:29:04] [TRT] [I] Producer name:    pytorch
[07/09/2023-07:29:04] [TRT] [I] Producer version: 1.12.1
[07/09/2023-07:29:04] [TRT] [I] Domain:           
[07/09/2023-07:29:04] [TRT] [I] Model version:    0
[07/09/2023-07:29:04] [TRT] [I] Doc string:       
[07/09/2023-07:29:04] [TRT] [I] ----------------------------------------------------------------
[07/09/2023-07:29:05] [TRT] [W] onnx2trt_utils.cpp:377: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[07/09/2023-07:29:05] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[07/09/2023-07:29:05] [TRT] [I] No importer registered for op: GatherTopk. Attempting to import as plugin.
[07/09/2023-07:29:05] [TRT] [I] Searching for plugin: GatherTopk, plugin_version: 1, plugin_namespace: 
[07/09/2023-07:29:05] [TRT] [E] ModelImporter.cpp:726: While parsing node number 421 [GatherTopk -> "onnx::Cast_1030"]:
[07/09/2023-07:29:05] [TRT] [E] ModelImporter.cpp:727: --- Begin node ---
[07/09/2023-07:29:05] [TRT] [E] ModelImporter.cpp:728: input: "x.55"
input: "inds"
output: "onnx::Cast_1030"
name: "GatherTopk_421"
op_type: "GatherTopk"
domain: "mmdeploy"

[07/09/2023-07:29:05] [TRT] [E] ModelImporter.cpp:729: --- End node ---
[07/09/2023-07:29:05] [TRT] [E] ModelImporter.cpp:732: ERROR: builtin_op_importers.cpp:5428 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
Process Process-3:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/share/Container_Workspace/study_mmdeploy/mmdeploy_1_2_0/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/share/Container_Workspace/study_mmdeploy/mmdeploy_1_2_0/mmdeploy/apis/utils/utils.py", line 104, in to_backend
    **kwargs)
  File "/share/Container_Workspace/study_mmdeploy/mmdeploy_1_2_0/mmdeploy/backend/tensorrt/backend_manager.py", line 134, in to_backend
    partition_type=partition_type)
  File "/share/Container_Workspace/study_mmdeploy/mmdeploy_1_2_0/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 88, in onnx2tensorrt
    device_id=device_id)
  File "/share/Container_Workspace/study_mmdeploy/mmdeploy_1_2_0/mmdeploy/backend/tensorrt/utils.py", line 185, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 421 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

07/09 07:29:05 - mmengine - ERROR - /share/Container_Workspace/study_mmdeploy/mmdeploy_1_2_0/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 81 - `mmdeploy.apis.utils.utils.to_backend` with Call id: 1 failed. exit.

mmdetection3d模型：
python tools/deploy.py configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime_dynamic.py ../mmdetection3d_1_2_0/configs/centerpoint/centerpoint_pillar02_second_secfpn_head-circlenms_8xb4-cyclic-20e_nus-3d.py checkpoints/centerpoint_02pillar_second_secfpn_circlenms_4x8_cyclic_20e_nus_20210816_064624-0f3299c0.pth ../mmdetection3d_1_2_0/demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951.pcd.bin --work-dir mmdeploy_model/centerpoints --device cuda --dump-info

Traceback (most recent call last):
  File "tools/deploy.py", line 335, in <module>
    main()
  File "tools/deploy.py", line 134, in main
    device=args.device)
  File "/share/Container_Workspace/study_mmdeploy/mmdeploy_1_2_0/mmdeploy/backend/sdk/export_info.py", line 352, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/share/Container_Workspace/study_mmdeploy/mmdeploy_1_2_0/mmdeploy/backend/sdk/export_info.py", line 266, in get_deploy
    cls_name = task_map[task]['cls_name']
KeyError: <Task.VOXEL_DETECTION: 'VoxelDetection'>

### Environment

```Shell
python tools/check_env.py 
07/09 07:26:34 - mmengine - INFO - 

07/09 07:26:34 - mmengine - INFO - **********Environmental information**********
07/09 07:26:35 - mmengine - INFO - sys.platform: linux
07/09 07:26:35 - mmengine - INFO - Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
07/09 07:26:35 - mmengine - INFO - CUDA available: True
07/09 07:26:35 - mmengine - INFO - numpy_random_seed: 2147483648
07/09 07:26:35 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3070
07/09 07:26:35 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
07/09 07:26:35 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.109
07/09 07:26:35 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
07/09 07:26:35 - mmengine - INFO - PyTorch: 1.12.1
07/09 07:26:35 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

07/09 07:26:35 - mmengine - INFO - TorchVision: 0.13.1
07/09 07:26:35 - mmengine - INFO - OpenCV: 4.8.0
07/09 07:26:35 - mmengine - INFO - MMEngine: 0.8.1
07/09 07:26:35 - mmengine - INFO - MMCV: 2.0.1
07/09 07:26:35 - mmengine - INFO - MMCV Compiler: GCC 7.5
07/09 07:26:35 - mmengine - INFO - MMCV CUDA Compiler: 11.3
07/09 07:26:35 - mmengine - INFO - MMDeploy: 1.2.0+0a8cbe2
07/09 07:26:35 - mmengine - INFO - 

07/09 07:26:35 - mmengine - INFO - **********Backend information**********
07/09 07:26:35 - mmengine - INFO - tensorrt:	8.5.3.1
07/09 07:26:35 - mmengine - INFO - tensorrt custom ops:	NotAvailable
07/09 07:26:35 - mmengine - INFO - ONNXRuntime:	None
07/09 07:26:35 - mmengine - INFO - ONNXRuntime-gpu:	1.14.1
07/09 07:26:35 - mmengine - INFO - ONNXRuntime custom ops:	NotAvailable
07/09 07:26:35 - mmengine - INFO - pplnn:	None
07/09 07:26:35 - mmengine - INFO - ncnn:	None
07/09 07:26:35 - mmengine - INFO - snpe:	None
07/09 07:26:35 - mmengine - INFO - openvino:	None
07/09 07:26:35 - mmengine - INFO - torchscript:	1.12.1
07/09 07:26:35 - mmengine - INFO - torchscript custom ops:	NotAvailable
07/09 07:26:35 - mmengine - INFO - rknn-toolkit:	None
07/09 07:26:35 - mmengine - INFO - rknn-toolkit2:	None
07/09 07:26:35 - mmengine - INFO - ascend:	None
07/09 07:26:35 - mmengine - INFO - coreml:	None
07/09 07:26:35 - mmengine - INFO - tvm:	None
07/09 07:26:35 - mmengine - INFO - vacc:	None
07/09 07:26:35 - mmengine - INFO - 

07/09 07:26:35 - mmengine - INFO - **********Codebase information**********
07/09 07:26:35 - mmengine - INFO - mmdet:	3.1.0
07/09 07:26:35 - mmengine - INFO - mmseg:	1.1.0
07/09 07:26:35 - mmengine - INFO - mmpretrain:	None
07/09 07:26:35 - mmengine - INFO - mmocr:	None
07/09 07:26:35 - mmengine - INFO - mmagic:	None
07/09 07:26:35 - mmengine - INFO - mmdet3d:	1.2.0
07/09 07:26:35 - mmengine - INFO - mmpose:	None
07/09 07:26:35 - mmengine - INFO - mmrotate:	None
07/09 07:26:35 - mmengine - INFO - mmaction:	None
07/09 07:26:35 - mmengine - INFO - mmrazor:	None
07/09 07:26:35 - mmengine - INFO - mmyolo:	None
```

**Comment by irexyc** [comment]
The sdk don't support mmdetection3d inference, so please remove `--dump-info` when you export the model.

**Comment by RunningLeon** [comment]
hi
1. tensorrt custom ops is not built. Pls. install mmdeploy correctly.
2. pls. provide sample code to reproduce mmdet3d issue
