### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zkccpro** [open-mmlab/mmdeploy#2264]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

**THIS MAY BE A COMMON PROBLEM!!!!**

使用CUDA11.8和torch2.0.1，最新版本的mm组件。系统是windows（但我在linux上试了，一样的结果）转换cascade rcnn到tensorrt出错，报错信息：
```
(base) PS D:\mmdeploy> python .\tools\deploy.py ..\pth2trt\conf\mmdeploy_det.py ..\pth2trt\conf\cascoco_randomclipv3.py  ..\pth2trt\best_bbox_mAP_epoch_4.pth ..\pth2trt\xxx.bmp --work-dir work_dir/ --device cuda
07/10 15:42:41 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
07/10 15:42:42 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
07/10 15:42:42 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
07/10 15:42:42 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
```
我看了好几个issues都有类似的问题，似乎和第三方依赖版本无关？？？
我还使用了mmdeploy0.x（不适用mmengine）则不出现这个问题。
似乎是deploy config写的不对？但我的config文件可以在低版本的mmdeploy上跑通，以下是我的deploy config：
```
onnx_config = dict(
    type='onnx',
    export_params=True,
    keep_initializers_as_inputs=False,
    opset_version=11,
    save_file='end2end.onnx',
    input_names=['input'],
    output_names=['boxes', 'classes'],
    input_shape=[1504, 1504],
    optimize=True,
    dynamic_axes={
        'input': {
            0: 'batch'
            # 2: 'height',
            # 3: 'width'
        },
        'boxes': {
            0: 'batch'
            # 1: 'num_dets',
        },
        'classes': {
            0: 'batch'
            # 1: 'num_dets',
        },
    }
)

codebase_config = dict(
    type='mmdet',
    task='ObjectDetection',
    model_type='end2end',
    post_processing=dict(
        score_threshold=0.05,
        confidence_threshold=0.005,  # for YOLOv3
        iou_threshold=0.5,
        max_output_boxes_per_class=200,
        pre_top_k=5000,
        keep_top_k=100,
        background_label_id=-1,
    ))

backend_config = dict(
    type='tensorrt',
    common_config=dict(fp16_mode=False, max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 2016, 2016],
                    opt_shape=[8, 3, 2016, 2016],
                    max_shape=[8, 3, 2016, 2016])))
    ])
```
model config：
```
classes = ('bengbianjiao','dimo','laxian','youpao','quemo','liewen','jihao','baidian','bengyou','luozang','diyou','paobai','queyou','shuizhu','sehen','pentouyin','qipao','aokeng')   #模型的分类名(第三版)
classnum = 18
data_root = './'
pic_root = '/pics'
dataset_type = 'CocoDataset'
norm_cfg = dict(type='BN', requires_grad=True)
# model settings
model = dict(
    type='CascadeRCNN',
        backbone=dict(
            type='ResNeSt',
            stem_channels=64,
            depth=50,
            radix=2,
            reduction_factor=4,
            avg_down_stride=True,
            num_stages=4,
            out_indices=(0, 1, 2, 3),
            frozen_stages=1,
            norm_cfg=norm_cfg,
            dcn=dict(type='DCNv2', deform_groups=1, fallback_on_stride=False),
            stage_with_dcn=(False, True, True, True),
            norm_eval=True,
            style='pytorch' ,
            init_cfg=dict(type='Pretrained', checkpoint='open-mmlab://resnest50'
            )),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            # scals为anchor缩放比例，strides初始大小*scales生成base_anchor
            # ratios为anchor高宽比，定义anchor形状，每一处生成ratios*scales个anchor
            # base_anchor*anchor_strides生成各个feature_map上使用的anchor。
            type='AnchorGenerator',
            scales=[6],     
            ratios=[0.1,  0.5, 1.0, 2.0, 10.0], 
            strides=[4, 8, 16, 32, 64]),          
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
    roi_head=dict(
        type='CascadeRoIHead',
        num_stages=3,
        stage_loss_weights=[1, 0.5, 0.25],
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=[
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=classnum,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.1, 0.1, 0.2, 0.2]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=classnum,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.05, 0.05, 0.1, 0.1]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=classnum,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.033, 0.033, 0.067, 0.067]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
        ]),
    # model training and testing settings
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.6,
                neg_iou_thr=0.2,
                min_pos_iou=0.2,
                gpu_assign_thr=10,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=0,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=[
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.3,
                    neg_iou_thr=0.3,
                    
                    min_pos_iou=0.3,
                    gpu_assign_thr=10,
                    match_low_quality=False,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                pos_weight=-1,
                debug=False),
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.4,
                    neg_iou_thr=0.4,
                    min_pos_iou=0.4,
                    match_low_quality=False,
                    gpu_assign_thr=10,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                pos_weight=-1,
                debug=False),
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.5,
                    neg_iou_thr=0.5,
                    min_pos_iou=0.5,
                    match_low_quality=False,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                pos_weight=-1,
                debug=False)
        ]),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.1),
            max_per_img=100)))

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True) #  ImageNet 预训练的模型权重
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),   
    dict(type='Resize', img_scale=[(1504,1504)], keep_ratio=True),
    dict(
        type='RandomFlip',  
        direction=['horizontal'],
        flip_ratio=[0.5]
        ),  
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1504,1504),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=False),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'test.json',
        img_prefix=pic_root,
        classes=classes,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'test.json',
        img_prefix=pic_root,
        classes=classes,
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'test.json',
        img_prefix=pic_root,
        classes=classes,
        pipeline=test_pipeline))
evaluation = dict(interval=1, 
            metric='bbox',
            save_best='auto', 
            iou_thrs=[0.1,0.3,0.5],
            classwise=True,  # 显示每个类别的评估结果
            metric_items=['mAP', 'mAP_s', 'mAP_m', 'mAP_l'])
# optimizer
optimizer = dict(type='Adam', lr=7.000e-06)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=20, # warmup的迭代次数
    warmup_ratio=0.001, # warmup的起始学习比率
    step=[5, 35, 50])  
    # step=[20, 40, 70, 100, 150])
runner = dict(type='EpochBasedRunner', max_epochs=100)

checkpoint_config = dict(interval=10)
# yapf:disable
log_config = dict(
    interval=500,
    hooks=[ 
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
custom_hooks = [dict(type='NumClassCheckHook')]

dist_params = dict(backend='nccl')
log_level = 'INFO'
#load_from ='/home/xxx/ceramicTile/high_precision/work_dirs/cascoco_randomclipv3_ccd/best_bbox_mAP_epoch_4.pth'
load_from = '/home/xxx/ceramicTile/high_precision/cis/work_dirs/cascoco_randomclipv3/best_bbox_mAP_epoch_6_20230524.pth'
resume_from = None #'/home/xxx/mmdetection/work_dirs/cascoco_randomclipv3/best_bbox_mAP_epoch_17.pth'     
workflow = [('train',1)] 
```

### Reproduction

python .\tools\deploy.py ..\pth2trt\conf\mmdeploy_det.py ..\pth2trt\conf\cascoco_randomclipv3.py  ..\pth2trt\best_bbox_mAP_epoch_4.pth ..\pth2trt\xxx.bmp --work-dir work_dir/ --device cuda

NEVER modify.

### Environment

```Shell
(base) PS D:\mmdeploy>  python .\tools\check_env.py
07/10 16:07:35 - mmengine - INFO -

07/10 16:07:35 - mmengine - INFO - **********Environmental information**********
07/10 16:07:40 - mmengine - INFO - sys.platform: win32
07/10 16:07:40 - mmengine - INFO - Python: 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
07/10 16:07:40 - mmengine - INFO - CUDA available: True
07/10 16:07:40 - mmengine - INFO - numpy_random_seed: 2147483648
07/10 16:07:40 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 4090
07/10 16:07:40 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
07/10 16:07:40 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.8, V11.8.89
07/10 16:07:40 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30148 版
07/10 16:07:40 - mmengine - INFO - GCC: n/a
07/10 16:07:40 - mmengine - INFO - PyTorch: 2.0.0+cu118
07/10 16:07:40 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 193431937
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.7
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

07/10 16:07:40 - mmengine - INFO - TorchVision: 0.15.1+cu118
07/10 16:07:40 - mmengine - INFO - OpenCV: 4.8.0
07/10 16:07:40 - mmengine - INFO - MMEngine: 0.6.0
07/10 16:07:40 - mmengine - INFO - MMCV: 2.0.1
07/10 16:07:40 - mmengine - INFO - MMCV Compiler: MSVC 192930148
07/10 16:07:40 - mmengine - INFO - MMCV CUDA Compiler: 11.8
07/10 16:07:40 - mmengine - INFO - MMDeploy: 1.2.0+unknown
07/10 16:07:40 - mmengine - INFO -

07/10 16:07:40 - mmengine - INFO - **********Backend information**********
07/10 16:07:40 - mmengine - INFO - tensorrt:    8.4.3.1
07/10 16:07:40 - mmengine - INFO - tensorrt custom ops: Available
07/10 16:07:40 - mmengine - INFO - ONNXRuntime: None
07/10 16:07:40 - mmengine - INFO - pplnn:       None
07/10 16:07:40 - mmengine - INFO - ncnn:        None
07/10 16:07:40 - mmengine - INFO - snpe:        None
07/10 16:07:40 - mmengine - INFO - openvino:    None
07/10 16:07:40 - mmengine - INFO - torchscript: 2.0.0+cu118
07/10 16:07:40 - mmengine - INFO - torchscript custom ops:      NotAvailable
07/10 16:07:40 - mmengine - INFO - rknn-toolkit:        None
07/10 16:07:40 - mmengine - INFO - rknn-toolkit2:       None
07/10 16:07:40 - mmengine - INFO - ascend:      None
07/10 16:07:40 - mmengine - INFO - coreml:      None
07/10 16:07:40 - mmengine - INFO - tvm: None
07/10 16:07:40 - mmengine - INFO - vacc:        None
07/10 16:07:40 - mmengine - INFO -

07/10 16:07:40 - mmengine - INFO - **********Codebase information**********
07/10 16:07:40 - mmengine - INFO - mmdet:       3.0.0rc5
07/10 16:07:40 - mmengine - INFO - mmseg:       None
07/10 16:07:40 - mmengine - INFO - mmpretrain:  None
07/10 16:07:40 - mmengine - INFO - mmocr:       None
07/10 16:07:40 - mmengine - INFO - mmagic:      None
07/10 16:07:40 - mmengine - INFO - mmdet3d:     None
07/10 16:07:40 - mmengine - INFO - mmpose:      None
07/10 16:07:40 - mmengine - INFO - mmrotate:    None
07/10 16:07:40 - mmengine - INFO - mmaction:    None
07/10 16:07:40 - mmengine - INFO - mmrazor:     None
07/10 16:07:40 - mmengine - INFO - mmyolo:      None
```
```


### Error traceback

```Shell
(base) PS D:\mmdeploy> python .\tools\deploy.py ..\pth2trt\conf\mmdeploy_det.py ..\pth2trt\conf\cascoco_randomclipv3.py  ..\pth2trt\best_bbox_mAP_epoch_4.pth ..\pth2trt\xxx.bmp --work-dir work_dir/ --device cuda
07/10 16:08:57 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
07/10 16:08:58 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
07/10 16:08:58 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
07/10 16:08:58 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
Process Process-2:
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "d:\mmdeploy\mmdeploy\codebase\mmdet\deploy\object_detection.py", line 132, in __init__
    super().__init__(model_cfg, deploy_cfg, device)
  File "d:\mmdeploy\mmdeploy\codebase\base\task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "D:\anaconda\lib\site-packages\mmengine\utils\manager.py", line 109, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "D:\anaconda\lib\site-packages\mmengine\registry\default_scope.py", line 35, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\anaconda\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "d:\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "d:\mmdeploy\mmdeploy\apis\pytorch2onnx.py", line 61, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "d:\mmdeploy\mmdeploy\apis\utils\utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "d:\mmdeploy\mmdeploy\codebase\base\mmcodebase.py", line 45, in build_task_processor
    return cls.task_registry.build(
  File "D:\anaconda\lib\site-packages\mmengine\registry\registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\anaconda\lib\site-packages\mmengine\registry\build_functions.py", line 135, in build_from_cfg
    raise type(e)(
AssertionError: class `ObjectDetection` in mmdeploy/codebase/mmdet/deploy/object_detection.py: scope_name should be a string, but got None
07/10 16:08:59 - mmengine - ERROR - d:\mmdeploy\mmdeploy\apis\core\pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```
```

**Comment by RunningLeon** [comment]
hi, pls. try upgrade mmengine.

**Comment by zkccpro** [comment]
@RunningLeon  I try mmengine0.8.0, not work. Do mmengine0.8.1 may make different???

**Comment by zkccpro** [comment]
@RunningLeon I just try mmengine0.8.1 newest, not work. I saw another one uses mmengine0.6.0 and works, I dont think it is about mmengine version...

**Comment by zkccpro** [comment]
@RunningLeon  @ALL 
Hi, I think I find out why for this! Probably because I used mmdet1.x to train model. When I use latest pretrained model provided on mmdet repo, mmdeploy1.x can deploy this model to onnx and trt, and never occur this.
Besides, I trained model myself using mmdet3.x, and deploy by mmdeploy1.x, it also gets correct onnx and trt plan file after my validations.

**Comment by RunningLeon** [comment]
@zkccpro hi, good to know it is solved. The version matching is quite problematic.
