### ISSUE TITLE
[Bug] ValueError: The len of mean_values ([123.675, 116.28, 103.53]) for input 0 is wrong, expect 224!

### ISSUE THREAD

**Issue by zhanghui-china** [open-mmlab/mmdeploy#2271]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

cannot model convert

### Reproduction

python tools/deploy.py \
        configs/mmpretrain/classification_rknn-int8_static-224x224.py \
        ~/mmpretrain/configs/resnet/resnet50_8xb32_in1k.py \
        ./resnet50_batch256_imagenet_20200708-cfb998bf.pth \
        ~/mmpretrain/demo/demo.JPEG \
        --work-dir mmdeploy_models/mmpretrain/resnet50 \
        --device cpu \
        --dump-info

when i execute the command above, It shows:

```shell

(mmdeploy) zhanghui@zhanghui-ubuntu2204:~/MMDeploy$ sh ./rknn_resnet50.sh
07/12 16:19:53 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
07/12 16:19:53 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "mmpretrain_tasks" registry tree. As a workaround, the current "mmpretrain_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
07/12 16:19:54 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
07/12 16:19:55 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
07/12 16:19:55 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "mmpretrain_tasks" registry tree. As a workaround, the current "mmpretrain_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: ./resnet50_batch256_imagenet_20200708-cfb998bf.pth
07/12 16:19:55 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
07/12 16:19:55 - mmengine - INFO - Export PyTorch model to ONNX: mmdeploy_models/mmpretrain/resnet50/end2end.onnx.
07/12 16:19:55 - mmengine - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
07/12 16:19:57 - mmengine - INFO - Execute onnx optimize passes.
07/12 16:19:58 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
07/12 16:19:59 - mmengine - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in main process
07/12 16:19:59 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
W __init__: rknn-toolkit2 version: 1.5.0+1fa95b5c
W load_onnx: If you don't need to crop the model, don't set 'inputs'/'input_size_list'/'outputs'!
W load_onnx: It is recommended onnx opset 12, but your onnx model opset is 11!
W load_onnx: Model converted from pytorch, 'opset_version' should be set 12 in torch.onnx.export for successful convert!
             More details can be found in examples/pytorch/resnet18_export_onnx
Loading : 100%|█████████████████████████████████████████████████| 108/108 [00:00<00:00, 3522.76it/s]
E load_onnx: The len of mean_values ([123.675, 116.28, 103.53]) for input 0 is wrong, expect 224!
W load_onnx: ===================== WARN(4) =====================
E rknn-toolkit2 version: 1.5.0+1fa95b5c
E load_onnx: Catch exception when loading onnx model: /home/zhanghui/MMDeploy/mmdeploy_models/mmpretrain/resnet50/end2end.onnx!
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1382, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx:   File "rknn/api/rknn_base.py", line 726, in rknn.api.rknn_base.RKNNBase._create_ir_and_inputs_meta
E load_onnx:   File "rknn/api/rknn_log.py", line 112, in rknn.api.rknn_log.RKNNLog.e
E load_onnx: ValueError: The len of mean_values ([123.675, 116.28, 103.53]) for input 0 is wrong, expect 224!
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
  https://eyun.baidu.com/s/3eTDMk6Y (Pwd: rknn)  Path: RK_NPU_SDK / RK_NPU_SDK_1.X.0 / develop /
  If the error still exists in the latest version, please collect the corresponding error logs and the model,
  convert script, and input data that can reproduce the problem, and then submit an issue on:
  https://redmine.rock-chips.com (Please consult our sales or FAE for the redmine account)
07/12 16:19:59 - mmengine - ERROR - /home/zhanghui/MMDeploy/mmdeploy/backend/rknn/onnx2rknn.py - onnx2rknn - 80 - Load model failed!
(mmdeploy) zhanghui@zhanghui-ubuntu2204:~/MMDeploy$
```

resnet50_batch256_imagenet_20200708-cfb998bf.pth downloaded from 
https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_batch256_imagenet_20200708-cfb998bf.pth

### Environment

```Shell
ubuntu 22.04 x86
conda python3.8.17
```

**Comment by AllentDan** [comment]
As answered in WeChat, maybe you can try the official [demo](https://github.com/rockchip-linux/rknn-toolkit2/blob/master/examples/onnx/resnet50v2/test.py) to check if you are preparing environment right.
