### ISSUE TITLE
[Bug] pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.4.0-22dcfef4'

### ISSUE THREAD

**Issue by zhanghui-china** [open-mmlab/mmdeploy#2276]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

my board is Rock5a , RK3588

python tools/deploy.py
configs/mmpretrain/classification_rknn-int8_static-224x224.py
~/mmpretrain/configs/resnet/resnet50_8xb32_in1k.py
/resnet50_batch256_imagenet_20200708-cfb998bf.pth
~/mmpretrain/demo/demo.JPEG
--work-dir mmdeploy_models/mmpretrain/resnet50
--device cpu
--dump-info

when i execute model convert from onnx to rknn:

pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.4.0-22dcfef4'

### Reproduction

```Shell
(rock38) rock@ubuntu:~/mmdeploy$ sh ./rknn_resnet50.sh
07/13 16:00:24 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
07/13 16:00:24 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "mmpretrain_tasks" registry tree. As a workaround, the current "mmpretrain_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
07/13 16:00:25 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
07/13 16:00:25 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
07/13 16:00:25 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "mmpretrain_tasks" registry tree. As a workaround, the current "mmpretrain_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: /home/rock/resnet50_batch256_imagenet_20200708-cfb998bf.pth
07/13 16:00:26 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
07/13 16:00:26 - mmengine - INFO - Export PyTorch model to ONNX: mmdeploy_models/mmpretrain/resnet50/end2end.onnx.
07/13 16:00:26 - mmengine - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
07/13 16:00:28 - mmengine - INFO - Execute onnx optimize passes.
07/13 16:00:28 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
07/13 16:00:28 - mmengine - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in main process
07/13 16:00:29 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
Traceback (most recent call last):
  File "tools/deploy.py", line 335, in <module>
    main()
  File "tools/deploy.py", line 259, in main
    backend_files = to_backend(
  File "/home/rock/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/rock/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/rock/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/rock/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/rock/mmdeploy/mmdeploy/apis/utils/utils.py", line 98, in to_backend
    return backend_mgr.to_backend(
  File "/home/rock/mmdeploy/mmdeploy/backend/rknn/backend_manager.py", line 147, in to_backend
    onnx2rknn(onnx_path, output_path, deploy_cfg)
  File "/home/rock/mmdeploy/mmdeploy/backend/rknn/onnx2rknn.py", line 71, in onnx2rknn
    rknn = RKNN(verbose=True)
  File "/home/rock/anaconda3/envs/rock38/lib/python3.8/site-packages/rknn/api/rknn.py", line 56, in __init__
    self.rknn_base = RKNNBase(cur_path, verbose)
  File "rknn/api/rknn_base.py", line 75, in rknn.api.rknn_base.RKNNBase.__init__
  File "/home/rock/anaconda3/envs/rock38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 526, in get_distribution
    dist = get_provider(dist)
  File "/home/rock/anaconda3/envs/rock38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 398, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/rock/anaconda3/envs/rock38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 695, in find
    if dist is not None and dist not in req:
  File "/home/rock/anaconda3/envs/rock38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3204, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/home/rock/anaconda3/envs/rock38/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 902, in contains
    item = Version(item)
  File "/home/rock/anaconda3/envs/rock38/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.4.0-22dcfef4'
(rock38) rock@ubuntu:~/mmdeploy$
```

### Environment

```Shell
Ubuntu 18.04 LTS X86
gcc 7.5.0
conda python 3.8
MMDEPLOY_DIR=~/mmdeploy
ONNXRUNTIME_DIR=onnxruntime-linux-x64-1.8.1
LD_LIBRARY_PATH=$ONNXRUNTIME_DIR/lib:$LD_LIBRARY_PATH
pytorch 1.8.1
mmcv>=2.0.0rc2
rknn_toolkit2-1.4.0_22dcfef4-cp38-cp38-linux_x86_64.whl
numpy 1.20.3
```

```

**Comment by AllentDan** [comment]
This is my env:
```
07/14 09:29:49 - mmengine - INFO - **********Environmental information**********
07/14 09:29:49 - mmengine - INFO - sys.platform: linux
07/14 09:29:49 - mmengine - INFO - Python: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) [GCC 7.5.0]
07/14 09:29:49 - mmengine - INFO - CUDA available: True
07/14 09:29:49 - mmengine - INFO - numpy_random_seed: 2147483648
07/14 09:29:49 - mmengine - INFO - GPU 0: NVIDIA GeForce GTX 1660 SUPER
07/14 09:29:49 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
07/14 09:29:49 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.4, V11.4.48
07/14 09:29:49 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
07/14 09:29:49 - mmengine - INFO - PyTorch: 1.8.0
07/14 09:29:49 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

07/14 09:29:49 - mmengine - INFO - TorchVision: 0.9.0
07/14 09:29:49 - mmengine - INFO - OpenCV: 4.4.0
07/14 09:29:49 - mmengine - INFO - MMEngine: 0.8.2
07/14 09:29:49 - mmengine - INFO - MMCV: 2.0.0
07/14 09:29:49 - mmengine - INFO - MMCV Compiler: GCC 7.5
07/14 09:29:49 - mmengine - INFO - MMCV CUDA Compiler: 11.4
07/14 09:29:49 - mmengine - INFO - MMDeploy: 1.1.0+b1b9b4b
07/14 09:29:49 - mmengine - INFO - 

07/14 09:29:49 - mmengine - INFO - **********Backend information**********
07/14 09:29:49 - mmengine - INFO - tensorrt:    None
07/14 09:29:49 - mmengine - INFO - ONNXRuntime: 1.10.0
07/14 09:29:49 - mmengine - INFO - ONNXRuntime-gpu:     None
07/14 09:29:49 - mmengine - INFO - ONNXRuntime custom ops:      Available
07/14 09:29:49 - mmengine - INFO - pplnn:       None
07/14 09:29:49 - mmengine - INFO - ncnn:        None
07/14 09:29:49 - mmengine - INFO - snpe:        None
07/14 09:29:49 - mmengine - INFO - openvino:    None
07/14 09:29:49 - mmengine - INFO - torchscript: 1.8.0
07/14 09:29:49 - mmengine - INFO - torchscript custom ops:      Available
07/14 09:29:50 - mmengine - INFO - rknn-toolkit:        None
07/14 09:29:50 - mmengine - INFO - rknn-toolkit2:       1.4.0-22dcfef4
07/14 09:29:50 - mmengine - INFO - ascend:      None
07/14 09:29:50 - mmengine - INFO - coreml:      None
07/14 09:29:50 - mmengine - INFO - tvm: None
07/14 09:29:50 - mmengine - INFO - vacc:        None
07/14 09:29:50 - mmengine - INFO - 

07/14 09:29:50 - mmengine - INFO - **********Codebase information**********
07/14 09:29:50 - mmengine - INFO - mmdet:       3.0.0
07/14 09:29:50 - mmengine - INFO - mmseg:       1.0.0rc0
07/14 09:29:50 - mmengine - INFO - mmpretrain:  1.0.0
07/14 09:29:50 - mmengine - INFO - mmocr:       None
07/14 09:29:50 - mmengine - INFO - mmagic:      None
07/14 09:29:50 - mmengine - INFO - mmdet3d:     None
07/14 09:29:50 - mmengine - INFO - mmpose:      1.0.0
07/14 09:29:50 - mmengine - INFO - mmrotate:    None
07/14 09:29:50 - mmengine - INFO - mmaction:    None
07/14 09:29:50 - mmengine - INFO - mmrazor:     None
```

**Comment by zhanghui-china** [comment]
(rock38) rock@ubuntu:~$ pip list
Package             Version         Editable project location
------------------- --------------- -------------------------
addict              2.4.0
aenum               3.1.15
certifi             2023.5.7
charset-normalizer  3.2.0
click               8.1.5
colorama            0.4.6
contourpy           1.1.0
cycler              0.11.0
dill                0.3.6
einops              0.6.1
flatbuffers         23.5.26
fonttools           4.41.0
grpcio              1.56.0
idna                3.4
importlib-metadata  6.8.0
importlib-resources 6.0.0
kiwisolver          1.4.4
Markdown            3.4.3
markdown-it-py      3.0.0
mat4py              0.5.0
matplotlib          3.7.2
mdurl               0.1.2
mkl-fft             1.3.6
mkl-random          1.2.2
mkl-service         2.4.0
mmcv                2.0.1
mmdeploy            1.2.0           /home/rock/mmdeploy
mmengine            0.8.2
mmpretrain          1.0.0
model-index         0.1.11
modelindex          0.0.2
multiprocess        0.70.14
numpy               1.20.3
onnx                1.8.1
onnxoptimizer       0.3.13
onnxruntime         1.8.1
opencv-python       4.8.0.74
opendatalab         0.0.9
openmim             0.3.9
ordered-set         4.1.0
packaging           23.1
pandas              2.0.3
Pillow              9.3.0
pip                 23.1.2
platformdirs        3.8.1
prettytable         3.8.0
protobuf            3.20.2
pycryptodome        3.18.0
Pygments            2.15.1
pyparsing           3.0.9
python-dateutil     2.8.2
pytz                2023.3
PyYAML              6.0
requests            2.31.0
rich                13.4.2
rknn-toolkit2       1.4.0-22dcfef4
scipy               1.10.1
setuptools          67.8.0
six                 1.16.0
tabulate            0.9.0
termcolor           2.3.0
terminaltables      3.1.10
tomli               2.0.1
torch               1.8.1
torchaudio          0.8.0a0+e4e171a
torchvision         0.9.1
tqdm                4.65.0
typing_extensions   4.6.3
tzdata              2023.3
urllib3             2.0.3
wcwidth             0.2.6
wheel               0.38.4
yapf                0.40.1
zipp                3.16.1
(rock38) rock@ubuntu:~$

**Comment by AllentDan** [comment]
I got a workaround for rknn-toolkit2-1.5+. It turns out [load_onnx](https://github.com/open-mmlab/mmdeploy/blob/0a8cbe2286dcb226f3140d0bae8700cdfaf37a47/mmdeploy/backend/rknn/onnx2rknn.py#L73) function of rknn-toolkit2 throw the weird error. I will fix it and update the documents ASAP.
