### ISSUE TITLE
[Bug]  Failed to create TensorRT engine when tried to deploy ViTPose 

### ISSUE THREAD

**Issue by wanghlsara** [open-mmlab/mmdeploy#2289]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I used mmdeploy to convert pth to tensorrt model file but failed.  I only got an intermediate  onnx  file without the engine one. Since mmpose has supported vitpose, I am eagerly looking forward  to  export the onnx/trt model using mmdeploy. What should I do to fix the error? 

### Reproduction

```
> mim download mmpose --config td-hm_ViTPose-huge_8xb64-210e_coco-256x192 --dest .


> python tools/deploy.py \
>     configs/mmpose/pose-detection_tensorrt_dynamic-256x192.py \
>     td-hm_ViTPose-huge_8xb64-210e_coco-256x192.py \
>     td-hm_ViTPose-huge_8xb64-210e_coco-256x192-e32adcd4_20230314.pth  \
>     demo/resources/human-pose.jpg \
>     --work-dir vitpose-trt/vitpose-h \
>     --device cuda:0 \
>     --show \
>     --dump-info
```

### Environment

```Shell
root@ebf809ca6cd8:~/workspace/mmdeploy# pip list
Package                Version
---------------------- ------------
addict                 2.4.0
aenum                  3.1.15
alembic                1.11.1
appdirs                1.4.4
asynctest              0.13.0
attrs                  23.1.0
blinker                1.6.2
certifi                2022.12.7
charset-normalizer     3.0.1
chumpy                 0.70
cityscapesScripts      2.2.2
clearml                1.11.0
click                  8.1.3
cloudpickle            2.2.1
colorama               0.4.6
coloredlogs            15.0.1
contourpy              1.1.0
coverage               7.2.7
cycler                 0.11.0
Cython                 0.29.35
dadaptation            3.1
databricks-cli         0.17.7
defusedxml             0.7.1
dill                   0.3.6
docker                 6.1.2
entrypoints            0.4
et-xmlfile             1.1.0
exceptiongroup         1.1.1
fastjsonschema         2.15.3
flake8                 6.0.0
Flask                  2.3.2
flatbuffers            23.1.21
fonttools              4.40.0
furl                   2.1.3
gitdb                  4.0.10
GitPython              3.1.31
greenlet               2.0.2
grpcio                 1.56.0
gunicorn               20.1.0
h5py                   3.9.0
humanfriendly          10.0
idna                   3.4
imagecorruptions       1.1.2
imageio                2.31.1
importlib-metadata     6.7.0
importlib-resources    5.12.0
iniconfig              2.0.0
interrogate            1.5.0
isort                  4.3.21
itsdangerous           2.1.2
Jinja2                 3.1.2
joblib                 1.2.0
json-tricks            3.17.1
jsonschema             4.17.3
jstyleson              0.0.2
kiwisolver             1.4.4
lazy_loader            0.2
lion-pytorch           0.1.2
lmdb                   1.4.1
loguru                 0.7.0
Mako                   1.2.4
Markdown               3.4.3
markdown-it-py         3.0.0
MarkupSafe             2.1.3
matplotlib             3.6.2
mccabe                 0.7.0
mdurl                  0.1.2
mlflow                 2.4.1
mmcls                  1.0.0rc6
mmcv                   2.0.0
mmdeploy-runtime       1.1.0
mmdet                  3.0.0
mmengine               0.8.2
mmpose                 1.0.0
model-index            0.1.11
modelindex             0.0.2
mpmath                 1.3.0
multiprocess           0.70.14
munkres                1.1.4
ncnn                   1.0.20230224
networkx               2.8.8
numpy                  1.23.4
oauthlib               3.2.2
onnx                   1.14.0
onnxruntime-gpu        1.13.1
opencv-contrib-python  4.5.4.60
opencv-python          4.7.0.68
opencv-python-headless 4.5.4.60
opendatalab            0.0.9
openmim                0.3.9
openpyxl               3.0.9
openvino               2022.3.0
openvino-dev           2022.3.0
openvino-telemetry     2022.3.0
ordered-set            4.1.0
orderedmultidict       1.0.1
packaging              23.1
pandas                 1.3.5
parameterized          0.9.0
pathlib2               2.3.7.post1
Pillow                 9.4.0
pip                    23.2
pkgutil_resolve_name   1.3.10
platformdirs           3.8.0
pluggy                 1.2.0
portalocker            2.7.0
prettytable            3.8.0
protobuf               3.20.2
psutil                 5.9.5
py                     1.11.0
pyarrow                12.0.0
pybind11               2.10.3
pycocotools            2.0.6
pycodestyle            2.10.0
pycryptodome           3.18.0
pycuda                 2022.2.2
pyflakes               3.0.1
Pygments               2.15.1
PyJWT                  2.4.0
pyparsing              3.1.0
pyppl                  0.8.1
pyquaternion           0.9.9
pyrsistent             0.19.3
pytest                 7.4.0
pytest-runner          6.0.0
python-dateutil        2.8.2
pytools                2023.1
pytz                   2022.7.1
PyWavelets             1.4.1
PyYAML                 6.0
querystring-parser     1.2.4
requests               2.28.2
rich                   13.4.2
scikit-image           0.21.0
scikit-learn           1.2.2
scipy                  1.10.1
setuptools             67.4.0
shapely                2.0.1
six                    1.16.0
smmap                  5.0.0
some-package           0.1
SQLAlchemy             2.0.16
sqlparse               0.4.4
sympy                  1.12
tabulate               0.9.0
tensorrt               8.2.3.0
termcolor              2.3.0
terminaltables         3.1.10
texttable              1.6.7
threadpoolctl          3.1.0
tifffile               2023.4.12
toml                   0.10.2
tomli                  2.0.1
torch                  1.10.0+cu113
torchvision            0.11.0+cu113
tqdm                   4.64.1
typing                 3.7.4.3
typing_extensions      4.5.0
urllib3                1.26.14
wcwidth                0.2.6
websocket-client       1.5.3
Werkzeug               2.3.4
wheel                  0.38.4
xdoctest               1.1.1
xlrd                   1.2.0
xtcocotools            1.13
yacs                   0.1.8
yapf                   0.40.1
zipp                   3.15.0
```

### Error traceback

```Shell
07/18 06:51:52 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
07/18 06:51:52 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
07/18 06:51:54 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
07/18 06:51:55 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
07/18 06:51:55 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: td-hm_ViTPose-huge_8xb64-210e_coco-256x192-e32adcd4_20230314.pth
/usr/local/lib/python3.8/dist-packages/mmpose/datasets/datasets/utils.py:102: UserWarning: The metainfo config file "configs/_base_/datasets/coco.py" does not exist. A matched config file "/usr/local/lib/python3.8/dist-packages/mmpose/.mim/configs/_base_/datasets/coco.py" will be used instead.
  warnings.warn(
07/18 06:52:05 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
07/18 06:52:05 - mmengine - INFO - Export PyTorch model to ONNX: vitpose-trt/vitpose-h/end2end.onnx.
07/18 06:52:06 - mmengine - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
07/18 06:52:06 - mmengine - WARNING - Can not find models.yolox_pose_head.YOLOXPoseHead.predict, function rewrite will not be applied
07/18 06:52:06 - mmengine - WARNING - Can not find models.yolox_pose_head.YOLOXPoseHead.predict_by_feat, function rewrite will not be applied
07/18 06:52:06 - mmengine - WARNING - Can not find torch._C._jit_pass_onnx_deduplicate_initializers, function rewrite will not be applied
07/18 06:52:06 - mmengine - WARNING - Can not find mmdet.models.utils.transformer.PatchMerging.forward, function rewrite will not be applied
/usr/local/lib/python3.8/dist-packages/mmcls/models/utils/embed.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if src_shape[0] == dst_shape[0] and src_shape[1] == dst_shape[1]:
07/18 06:52:15 - mmengine - INFO - Execute onnx optimize passes.
07/18 06:52:15 - mmengine - WARNING - Can not optimize model, please build torchscipt extension.
More details: https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/experimental/onnx_optimizer.md
07/18 06:52:19 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
07/18 06:52:22 - mmengine - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in subprocess
07/18 06:52:22 - mmengine - INFO - Successfully loaded tensorrt plugins from /root/workspace/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
[07/18/2023-06:52:23] [TRT] [I] [MemUsageChange] Init CUDA: CPU +457, GPU +0, now: CPU 543, GPU 446 (MiB)
[07/18/2023-06:52:23] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 543 MiB, GPU 446 MiB
[07/18/2023-06:52:23] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 697 MiB, GPU 490 MiB
[07/18/2023-06:52:23] [TRT] [I] ----------------------------------------------------------------
[07/18/2023-06:52:23] [TRT] [I] Input filename:   vitpose-trt/vitpose-h/end2end.onnx
[07/18/2023-06:52:23] [TRT] [I] ONNX IR version:  0.0.7
[07/18/2023-06:52:23] [TRT] [I] Opset version:    11
[07/18/2023-06:52:23] [TRT] [I] Producer name:    pytorch
[07/18/2023-06:52:23] [TRT] [I] Producer version: 1.10
[07/18/2023-06:52:23] [TRT] [I] Domain:           
[07/18/2023-06:52:23] [TRT] [I] Model version:    0
[07/18/2023-06:52:23] [TRT] [I] Doc string:       
[07/18/2023-06:52:23] [TRT] [I] ----------------------------------------------------------------
[07/18/2023-06:52:23] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[07/18/2023-06:52:25] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[07/18/2023-06:52:32] [TRT] [W] Output type must be INT32 for shape outputs
[07/18/2023-06:52:36] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.4.2
[07/18/2023-06:52:36] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +647, GPU +272, now: CPU 3809, GPU 762 (MiB)
[07/18/2023-06:52:37] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +172, GPU +266, now: CPU 3981, GPU 1028 (MiB)
[07/18/2023-06:52:37] [TRT] [W] TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.2.0
[07/18/2023-06:52:37] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[07/18/2023-06:52:37] [TRT] [E] 4: [shapeCompiler.cpp::evaluateShapeChecks::832] Error Code 4: Internal Error (kOPT values for profile 0 violate shape constraints: reshape would change volume. IShuffleLayer Reshape_50: reshaping failed for tensor: 461)
[07/18/2023-06:52:37] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/utils/utils.py", line 98, in to_backend
    return backend_mgr.to_backend(
  File "/root/workspace/mmdeploy/mmdeploy/backend/tensorrt/backend_manager.py", line 127, in to_backend
    onnx2tensorrt(
  File "/root/workspace/mmdeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "/root/workspace/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 248, in from_onnx
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine
07/18 06:52:37 - mmengine - ERROR - /root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.utils.utils.to_backend` with Call id: 1 failed. exit.
```
```

**Comment by wanghlsara** [comment]
update:
I finally got the engine file by changing pose-detection_tensorrt_dynamic-256x192.py to pose-detection_tensorrt_static-256x192.py.

**Comment by RunningLeon** [comment]
@wanghlsara hi, ViTPose is not on the [model support list](https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmpose.html#supported-models). You could debug the outputs in the visualization status at first.
