### ISSUE TITLE
[Bug] torch.onnx.errors.UnsupportedOperatorError when convert mask2former to onnx

### ISSUE THREAD

**Issue by rpl-alan-shangguan** [open-mmlab/mmdeploy#2323]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I ENCOUNTERED THIS ERROR when I tried to convert the mask2former_swin-t model from mmsegmentation to tensorrt.

`Traceback (most recent call last):
  File "../mmdeploy/tools/deploy.py", line 335, in <module>
    main()
  File "../mmdeploy/tools/deploy.py", line 142, in main
    torch2ir(ir_type)(
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/onnx/export.py", line 132, in export
    torch.onnx.export(
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/onnx/optimizer.py", line 27, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py", line 663, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py", line 1909, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::einsum' to ONNX opset version 11 is not supported. Support for this operator was added in version 12, try exporting with this version.`

### Reproduction

python ../mmdeploy/tools/deploy.py \
    ../mmdeploy/configs/mmseg/segmentation_tensorrt-fp16_static-1024x1224.py \
    ../mmsegmentation/work_dirs/mask2former_swin-t_8xb2-90k_cityscapes-512x1024/mask2former_swin-t_8xb2-90k_cityscapes-512x1024.py \
    ../mmsegmentation/work_dirs/mask2former_swin-t_8xb2-90k_cityscapes-512x1024/best_mIoU_iter_230727_5000.pth \
    ../test_data/segmentation_labeled_dataset/leftImg8bit/default/20221027_143549_759347.jpg \
    --test-img ../test_data/segmentation_labeled_dataset/leftImg8bit/default/20221027_143549_759347.jpg \
    --work-dir ./mask2former_with_argmax/ \
    --device cuda:0 \
    --log-level INFO \
    --dump-info

### Environment

```Shell
08/03 08:37:23 - mmengine - INFO - 

08/03 08:37:23 - mmengine - INFO - **********Environmental information**********
08/03 08:37:24 - mmengine - INFO - sys.platform: linux
08/03 08:37:24 - mmengine - INFO - Python: 3.8.0 (default, Nov  6 2019, 21:49:08) [GCC 7.3.0]
08/03 08:37:24 - mmengine - INFO - CUDA available: True
08/03 08:37:24 - mmengine - INFO - numpy_random_seed: 2147483648
08/03 08:37:24 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3080 Ti
08/03 08:37:24 - mmengine - INFO - GPU 1: Quadro P3200
08/03 08:37:24 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.7
08/03 08:37:24 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.99
08/03 08:37:24 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
08/03 08:37:24 - mmengine - INFO - PyTorch: 1.13.1+cu117
08/03 08:37:24 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.4.1  (built against CUDA 11.6)
    - Built with CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

08/03 08:37:24 - mmengine - INFO - TorchVision: 0.14.1+cu117
08/03 08:37:24 - mmengine - INFO - OpenCV: 4.8.0
08/03 08:37:24 - mmengine - INFO - MMEngine: 0.8.2
08/03 08:37:24 - mmengine - INFO - MMCV: 2.0.1
08/03 08:37:24 - mmengine - INFO - MMCV Compiler: GCC 9.3
08/03 08:37:24 - mmengine - INFO - MMCV CUDA Compiler: 11.7
08/03 08:37:24 - mmengine - INFO - MMDeploy: 1.2.0+50df685
08/03 08:37:24 - mmengine - INFO - 

08/03 08:37:24 - mmengine - INFO - **********Backend information**********
08/03 08:37:24 - mmengine - INFO - tensorrt:    8.6.1
08/03 08:37:24 - mmengine - INFO - tensorrt custom ops: Available
08/03 08:37:24 - mmengine - INFO - ONNXRuntime: 1.15.1
08/03 08:37:24 - mmengine - INFO - ONNXRuntime-gpu:     None
08/03 08:37:24 - mmengine - INFO - ONNXRuntime custom ops:      NotAvailable
08/03 08:37:24 - mmengine - INFO - pplnn:       None
08/03 08:37:24 - mmengine - INFO - ncnn:        None
08/03 08:37:24 - mmengine - INFO - snpe:        None
08/03 08:37:24 - mmengine - INFO - openvino:    2023.0.1
08/03 08:37:24 - mmengine - INFO - torchscript: 1.13.1+cu117
08/03 08:37:24 - mmengine - INFO - torchscript custom ops:      NotAvailable
08/03 08:37:24 - mmengine - INFO - rknn-toolkit:        None
08/03 08:37:24 - mmengine - INFO - rknn-toolkit2:       None
08/03 08:37:24 - mmengine - INFO - ascend:      None
08/03 08:37:24 - mmengine - INFO - coreml:      None
08/03 08:37:24 - mmengine - INFO - tvm: None
08/03 08:37:24 - mmengine - INFO - vacc:        None
08/03 08:37:24 - mmengine - INFO - 

08/03 08:37:24 - mmengine - INFO - **********Codebase information**********
08/03 08:37:24 - mmengine - INFO - mmdet:       3.1.0
08/03 08:37:24 - mmengine - INFO - mmseg:       1.1.1
08/03 08:37:24 - mmengine - INFO - mmpretrain:  None
08/03 08:37:24 - mmengine - INFO - mmocr:       None
08/03 08:37:24 - mmengine - INFO - mmagic:      None
08/03 08:37:24 - mmengine - INFO - mmdet3d:     None
08/03 08:37:24 - mmengine - INFO - mmpose:      None
08/03 08:37:24 - mmengine - INFO - mmrotate:    None
08/03 08:37:24 - mmengine - INFO - mmaction:    None
08/03 08:37:24 - mmengine - INFO - mmrazor:     None
08/03 08:37:24 - mmengine - INFO - mmyolo:      None
```

**Comment by RunningLeon** [comment]
hi
1. mask2former is not supported
2. as the error, pls. try change the opset_version to 12  https://github.com/open-mmlab/mmdeploy/blob/c1bfccd617141f9f1eea8d1ceb5f3a7df40e6b35/configs/_base_/onnx_config.py#L5
>torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::einsum' to ONNX opset version 11 is not supported. Support for this operator was added in version 12, try exporting with this version.

**Comment by rpl-alan-shangguan** [comment]
I changed it to 12, then I got another error

Traceback (most recent call last):
  File "../mmdeploy/tools/deploy.py", line 335, in <module>
    main()
  File "../mmdeploy/tools/deploy.py", line 142, in main
    torch2ir(ir_type)(
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/onnx/export.py", line 132, in export
    torch.onnx.export(
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/onnx/optimizer.py", line 27, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py", line 1172, in _model_to_graph
    params_dict = _C._jit_pass_onnx_constant_fold(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)

**Comment by rpl-alan-shangguan** [comment]
python ../mmdeploy/tools/deploy.py \
    ../mmdeploy/configs/mmseg/segmentation_onnxruntime_dynamic.py \
    ../mmsegmentation/work_dirs/mask2former_swin-t_8xb2-90k_cityscapes-512x1024/mask2former_swin-t_8xb2-90k_cityscapes-512x1024.py \
    ../mmsegmentation/work_dirs/mask2former_swin-t_8xb2-90k_cityscapes-512x1024/best_mIoU_iter_230727_5000.pth \
    ../test_data/segmentation_labeled_dataset/leftImg8bit/default/20221027_143549_759347.jpg \
    --test-img ../test_data/segmentation_labeled_dataset/leftImg8bit/default/20221027_143549_759347.jpg \
    --work-dir ./mask2former_with_argmax/ \
    --device cpu \
    --log-level INFO \
    --dump-info

Try only convert it to onnx using CPU, and I got another error

Traceback (most recent call last):
  File "../mmdeploy/tools/deploy.py", line 335, in <module>
    main()
  File "../mmdeploy/tools/deploy.py", line 142, in main
    torch2ir(ir_type)(
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/onnx/export.py", line 132, in export
    torch.onnx.export(
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/onnx/optimizer.py", line 27, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/apis/onnx/export.py", line 125, in wrapper
    return forward(*arg, **kwargs)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/codebase/mmseg/models/segmentors/base.py", line 51, in base_segmentor__forward
    seg_logit = self.predict(inputs, data_samples)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py", line 26, in encoder_decoder__predict
    seg_logit = self.decode_head.predict(x, batch_img_metas, self.test_cfg)
  File "/home/alan/Downloads/mmsegmentation/mmseg/models/decode_heads/mask2former_head.py", line 146, in predict
    batch_data_samples = [
  File "/home/alan/Downloads/mmsegmentation/mmseg/models/decode_heads/mask2former_head.py", line 147, in <listcomp>
    SegDataSample(metainfo=metainfo) for metainfo in batch_img_metas
  File "/home/alan/Downloads/mmengine/mmengine/structures/base_data_element.py", line 216, in __init__
    self.set_metainfo(metainfo=metainfo)
  File "/home/alan/Downloads/mmengine/mmengine/structures/base_data_element.py", line 231, in set_metainfo
    meta = copy.deepcopy(metainfo)
  File "/home/alan/Downloads/mmdeploy/mmdeploy/pytorch/functions/copy.py", line 17, in copy__default
    return ctx.origin_func(tensor, *args, **kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/copy.py", line 229, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/copy.py", line 263, in _reconstruct
    y = func(*args)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/copy.py", line 262, in <genexpr>
    args = (deepcopy(arg, memo) for arg in args)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/copy.py", line 209, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/copy.py", line 209, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/_tensor.py", line 135, in __deepcopy__
    new_storage = self.storage().__deepcopy__(memo)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/storage.py", line 597, in __deepcopy__
    return self._new_wrapped_storage(copy.deepcopy(self._storage, memo))
  File "/home/alan/Downloads/mmdeploy/mmdeploy/pytorch/functions/copy.py", line 17, in copy__default
    return ctx.origin_func(tensor, *args, **kwargs)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/storage.py", line 97, in __deepcopy__
    new_storage = self.clone()
  File "/home/alan/miniconda3/envs/mm/lib/python3.8/site-packages/torch/storage.py", line 111, in clone
    return type(self)(self.nbytes(), device=self.device).copy_(self)
RuntimeError: NYI: Named tensors are not supported with the tracer

**Comment by RunningLeon** [comment]
@rpl-alan-shangguan hi, this has been fixed in this PR https://github.com/open-mmlab/mmdeploy/pull/2319. Could sync with the latest mmdeploy main branch and try again?

**Comment by nuistAImaster** [comment]
I meet a same question

**Comment by RunningLeon** [comment]
hi, for mask2former from mmseg, pls. try with static shape deploy config with opset_version>=12

> I meet a same question
