### ISSUE TITLE
[Bug] `engine` should be str or trt.ICudaEngine, but given: <class 'NoneType'>

### ISSUE THREAD

**Issue by da13132** [open-mmlab/mmdeploy#2325]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I have successfully built mmdeploy in the jetson environment. I use mmdeploy to export the tensorrt format of RTMPose in the server environment and run it successfully in the server environment. I hope to test tensorrt in the jetson environment, but when I copy the corresponding files to jetson , running an error, prompting 'TypeError: class `End2EndModel` in mmdeploy/codebase/mmpose/deploy/pose_detection_model.py: `engine` should be str or trt.ICudaEngine, but given: <class 'NoneType'>'. Hope to get your help!

### Reproduction

python tools/profiler.py /home/zhanglei/Desktop/zhanglei/mmdeploy/configs/mmpose/pose-detection_simcc_tensorrt_dynamic-256x192.py /home/zhanglei/Desktop/zhanglei/mmpose/configs/body_2d_keypoint/rtmpose/coco/rtmpose-t_8xb256-420e_coco-256x192.py /home/zhanglei/Desktop/zhanglei/mmdeploy/photos --model /home/zhanglei/Desktop/zhanglei/mmdeploy/rtmpose-tensorrt/end2end.engine --device cuda:0

### Environment

```Shell
08/03 15:11:00 - mmengine - INFO -

08/03 15:11:00 - mmengine - INFO - **********Environmental information**********
08/03 15:11:04 - mmengine - INFO - sys.platform: linux
08/03 15:11:04 - mmengine - INFO - Python: 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 07:33:48) [GCC 7.3.0]
08/03 15:11:04 - mmengine - INFO - CUDA available: True
08/03 15:11:04 - mmengine - INFO - numpy_random_seed: 2147483648
08/03 15:11:04 - mmengine - INFO - GPU 0: Xavier
08/03 15:11:04 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
08/03 15:11:04 - mmengine - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.300
08/03 15:11:04 - mmengine - INFO - GCC: x86_64-conda_cos6-linux-gnu-gcc (conda-forge gcc 12.2.0-19) 12.2.0
08/03 15:11:04 - mmengine - INFO - PyTorch: 1.10.0
08/03 15:11:04 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_53,code=sm_53;-gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72
  - CuDNN 8.2.1
    - Built with CuDNN 8.0
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=8.0.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -DMISSING_ARM_VST1 -DMISSING_ARM_VLD1 -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=open, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON,

08/03 15:11:04 - mmengine - INFO - TorchVision: 0.11.1
08/03 15:11:04 - mmengine - INFO - OpenCV: 4.8.0
08/03 15:11:04 - mmengine - INFO - MMEngine: 0.8.2
08/03 15:11:04 - mmengine - INFO - MMCV: 2.0.0
08/03 15:11:04 - mmengine - INFO - MMCV Compiler: GCC 7.5
08/03 15:11:04 - mmengine - INFO - MMCV CUDA Compiler: 10.2
08/03 15:11:04 - mmengine - INFO - MMDeploy: 1.2.0+553f9b8
08/03 15:11:04 - mmengine - INFO -

08/03 15:11:04 - mmengine - INFO - **********Backend information**********
08/03 15:11:04 - mmengine - INFO - tensorrt:    8.0.1.6
08/03 15:11:04 - mmengine - INFO - tensorrt custom ops: Available
08/03 15:11:04 - mmengine - INFO - ONNXRuntime: None
08/03 15:11:04 - mmengine - INFO - ONNXRuntime-gpu:     1.10.0
08/03 15:11:04 - mmengine - INFO - ONNXRuntime custom ops:      NotAvailable
08/03 15:11:04 - mmengine - INFO - pplnn:       None
08/03 15:11:04 - mmengine - INFO - ncnn:        None
08/03 15:11:04 - mmengine - INFO - snpe:        None
08/03 15:11:04 - mmengine - INFO - openvino:    None
08/03 15:11:04 - mmengine - INFO - torchscript: 1.10.0
08/03 15:11:04 - mmengine - INFO - torchscript custom ops:      NotAvailable
08/03 15:11:05 - mmengine - INFO - rknn-toolkit:        None
08/03 15:11:05 - mmengine - INFO - rknn-toolkit2:       None
08/03 15:11:05 - mmengine - INFO - ascend:      None
08/03 15:11:05 - mmengine - INFO - coreml:      None
08/03 15:11:05 - mmengine - INFO - tvm: None
08/03 15:11:05 - mmengine - INFO - vacc:        None
08/03 15:11:05 - mmengine - INFO -

08/03 15:11:05 - mmengine - INFO - **********Codebase information**********
08/03 15:11:05 - mmengine - INFO - mmdet:       3.0.0
08/03 15:11:05 - mmengine - INFO - mmseg:       None
08/03 15:11:05 - mmengine - INFO - mmpretrain:  None
08/03 15:11:05 - mmengine - INFO - mmocr:       None
08/03 15:11:05 - mmengine - INFO - mmagic:      None
08/03 15:11:05 - mmengine - INFO - mmdet3d:     None
08/03 15:11:05 - mmengine - INFO - mmpose:      1.1.0
08/03 15:11:05 - mmengine - INFO - mmrotate:    None
08/03 15:11:05 - mmengine - INFO - mmaction:    None
08/03 15:11:05 - mmengine - INFO - mmrazor:     None
08/03 15:11:05 - mmengine - INFO - mmyolo:      None
```

### Error traceback

```Shell
08/03 15:37:29 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
08/03 15:37:29 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
08/03 15:37:29 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "backend_segmentors" registry tree. As a workaround, the current "backend_segmentors" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
08/03 15:37:29 - mmengine - INFO - Successfully loaded tensorrt plugins from /home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
08/03 15:37:29 - mmengine - INFO - Successfully loaded tensorrt plugins from /home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
[TensorRT] ERROR: 1: [stdArchiveReader.cpp::StdArchiveReader::34] Error Code 1: Serialization (Serialization assertion safeVersionRead == safeSerializationVersion failed.Version tag does not match. Note: Current Version: 43, Serialized Engine Version: 0)
[TensorRT] ERROR: 4: [runtime.cpp::deserializeCudaEngine::76] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "/home/zhanglei/Desktop/zhanglei/mmengine/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/codebase/mmpose/deploy/pose_detection_model.py", line 55, in __init__
    **kwargs)
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/codebase/mmpose/deploy/pose_detection_model.py", line 78, in _init_wrapper
    **kwargs)
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/codebase/base/backend_model.py", line 66, in _build_wrapper
    output_names, deploy_cfg, **kwargs)
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/backend/tensorrt/backend_manager.py", line 34, in build_wrapper
    return TRTWrapper(engine=backend_files[0], output_names=output_names)
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/backend/tensorrt/wrapper.py", line 91, in __init__
    but given: {type(self.engine)}')
TypeError: `engine` should be str or trt.ICudaEngine,                 but given: <class 'NoneType'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/profiler.py", line 168, in <module>
    main()
  File "tools/profiler.py", line 120, in main
    model = task_processor.build_backend_model(args.model)
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/codebase/mmpose/deploy/pose_detection.py", line 178, in build_backend_model
    **kwargs)
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/codebase/mmpose/deploy/pose_detection_model.py", line 301, in build_pose_detection_model
    **kwargs))
  File "/home/zhanglei/Desktop/zhanglei/mmengine/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/zhanglei/Desktop/zhanglei/mmengine/mmengine/registry/build_functions.py", line 145, in build_from_cfg
    f'class `{obj_cls.__name__}` in '  # type: ignore
TypeError: class `End2EndModel` in mmdeploy/codebase/mmpose/deploy/pose_detection_model.py: `engine` should be str or trt.ICudaEngine,                 but given: <class 'NoneType'>
```

**Comment by RunningLeon** [comment]
@da13132 hi, you have to copy the `end2end.onnx` to jetson device and run `tools/onnx2tensorrt.py` to get the new `end2end.engine`

**Comment by da13132** [comment]
Thanks for your help, it worked！

**Comment by RunningLeon** [comment]
Glad to know it is solved. Feel free to reopen or create a new issue.

**Comment by GGGGGxun** [comment]
@RunningLeon  what is jetson device？
