### ISSUE TITLE
[Bug] Only tuples, lists and Variables are supported as JIT inputs/outputs.

### ISSUE THREAD

**Issue by yfnn** [open-mmlab/mmdeploy#2342]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I want to convert chinese-clip from pytorch to onnx.
Model_path I used is xxx/clip_cn_rn50.pt. Actually, this issue occured whenerve I used clip_cn_rn50.pt or clip_cn_vit-h-14.pt.
Model_cfg I used is mmpretrain/configs/chinese_clip/cn-clip_resnet50_zeroshot-cls_cifar100.py
Deploy_cfg I used is configs/mmpretrain/classification_onnxruntime_dynamic.py

RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: DataSample

In the file of 'mmdeploy/codebase/mmpretrain/deploy/classification.py', there is a variable 'data' on the line 220. The structure of this data is that:
{'images': tensor([[[[ 1.2880,  1.3026,  1.3318,  ..., -1.7047, -1.7339, -1.7339],
          [ 1.4340,  1.4340,  1.4340,  ..., -1.7923, -1.7631, -1.7777],
          [ 1.3464,  1.4340,  1.5070,  ..., -1.7923, -1.7923, -1.7923],
          ...,
          [ 1.0106,  0.9668,  0.9376,  ..., -1.7777, -1.7777, -1.7923],
          [-1.6463, -1.6755, -1.6901,  ..., -1.7777, -1.7631, -1.7923],
          [-1.7923, -1.7923, -1.7923,  ..., -1.7923, -1.7923, -1.7923]]],

        [[[ 1.4446,  1.4596,  1.4896,  ..., -1.5420, -1.5420, -1.5420],
          [ 1.5496,  1.5496,  1.5496,  ..., -1.6921, -1.6470, -1.6170],
          [ 1.3245,  1.4145,  1.4896,  ..., -1.7221, -1.7521, -1.7521],
          ...,
          [ 1.1444,  1.1294,  1.0994,  ..., -1.5270, -1.5570, -1.5720],
          [-1.4970, -1.4970, -1.5270,  ..., -1.5420, -1.5570, -1.5720],
          [-1.6170, -1.6020, -1.6170,  ..., -1.6470, -1.6621, -1.6621]]],

        [[[ 1.3780,  1.3922,  1.4207,  ..., -1.2811, -1.2811, -1.2811],
          [ 1.4491,  1.4491,  1.4491,  ..., -1.4091, -1.3665, -1.3522],
          [ 1.1932,  1.2785,  1.3496,  ..., -1.4376, -1.4660, -1.4660],
          ...,
          [ 1.2358,  1.2216,  1.1932,  ..., -1.2811, -1.2954, -1.3238],
          [-1.2811, -1.2811, -1.2811,  ..., -1.3096, -1.3238, -1.3380],
          [-1.3949, -1.3807, -1.3522,  ..., -1.4091, -1.4233, -1.4233]]]]), 'data_samples': [<DataSample(
META INFORMATION
    scale_factor: (1.0, 1.0)
) at 0x7fcdd4ca3850>]}

I think the bug is pointed to this data. But I don't know how to fix it.  I'm a novice in this field.

### Reproduction

Commad:
python3 tools/deploy.py configs/mmpretrain/classification_onnxruntime_dynamic.py /data/mmpretrain/configs/chinese_clip/cn-clip_resnet50_zeroshot-cls_cifar100.py /data/clip_data/pretrained_weights/clip_cn_rn50.pt /data/test.jpg --work-dir ./workdir1 --quant --quant-image-dir /data/imagenet-sample-images/

I did some modifications on the code.
1. MMDeploy/mmdeploy/codebase/mmpretrain/deploy/classification.py, line 220.
I modified from 'return data, data['inputs']' to 'return data, data['images'].permute(1,0,2,3)'. 
If not, there will errors , including 'key error: inputs' and 'need 3 channel image but give 1'.

Debug: data.shape is [3,1,224,224], which should be permuted to [1,3,224,224]

I think these modifications are right.

### Environment

```Shell
OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
08/10 13:35:00 - mmengine - INFO - 

08/10 13:35:00 - mmengine - INFO - **********Environmental information**********
08/10 13:35:01 - mmengine - INFO - sys.platform: linux
08/10 13:35:01 - mmengine - INFO - Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
08/10 13:35:01 - mmengine - INFO - CUDA available: False
08/10 13:35:01 - mmengine - INFO - numpy_random_seed: 2147483648
08/10 13:35:01 - mmengine - INFO - GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
08/10 13:35:01 - mmengine - INFO - PyTorch: 1.8.0
08/10 13:35:01 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

08/10 13:35:01 - mmengine - INFO - TorchVision: 0.9.0
08/10 13:35:01 - mmengine - INFO - OpenCV: 4.8.0
08/10 13:35:01 - mmengine - INFO - MMEngine: 0.8.4
08/10 13:35:01 - mmengine - INFO - MMCV: 2.0.1
08/10 13:35:01 - mmengine - INFO - MMCV Compiler: GCC 7.3
08/10 13:35:01 - mmengine - INFO - MMCV CUDA Compiler: 10.2
08/10 13:35:01 - mmengine - INFO - MMDeploy: 1.2.0+8a59bae
08/10 13:35:01 - mmengine - INFO - 

08/10 13:35:01 - mmengine - INFO - **********Backend information**********
08/10 13:35:01 - mmengine - INFO - tensorrt:    None
08/10 13:35:01 - mmengine - INFO - ONNXRuntime: 1.8.1
08/10 13:35:01 - mmengine - INFO - ONNXRuntime-gpu:     None
08/10 13:35:01 - mmengine - INFO - ONNXRuntime custom ops:      Available
08/10 13:35:01 - mmengine - INFO - pplnn:       None
08/10 13:35:01 - mmengine - INFO - ncnn:        None
08/10 13:35:01 - mmengine - INFO - snpe:        None
08/10 13:35:01 - mmengine - INFO - openvino:    None
08/10 13:35:01 - mmengine - INFO - torchscript: 1.8.0
08/10 13:35:01 - mmengine - INFO - torchscript custom ops:      NotAvailable
08/10 13:35:01 - mmengine - INFO - rknn-toolkit:        None
08/10 13:35:01 - mmengine - INFO - rknn-toolkit2:       None
08/10 13:35:01 - mmengine - INFO - ascend:      None
08/10 13:35:01 - mmengine - INFO - coreml:      None
08/10 13:35:01 - mmengine - INFO - tvm: None
08/10 13:35:01 - mmengine - INFO - vacc:        None
08/10 13:35:01 - mmengine - INFO - 

08/10 13:35:01 - mmengine - INFO - **********Codebase information**********
08/10 13:35:01 - mmengine - INFO - mmdet:       None
08/10 13:35:01 - mmengine - INFO - mmseg:       None
08/10 13:35:01 - mmengine - INFO - mmpretrain:  1.0.1
08/10 13:35:01 - mmengine - INFO - mmocr:       None
08/10 13:35:01 - mmengine - INFO - mmagic:      None
08/10 13:35:01 - mmengine - INFO - mmdet3d:     None
08/10 13:35:01 - mmengine - INFO - mmpose:      None
08/10 13:35:01 - mmengine - INFO - mmrotate:    None
08/10 13:35:01 - mmengine - INFO - mmaction:    None
08/10 13:35:01 - mmengine - INFO - mmrazor:     None
08/10 13:35:01 - mmengine - INFO - mmyolo:      None

I installed PyTorch by conda.
$PATH:bash: /home/yangfan04/anaconda3/envs/mmdeploy1/bin:/home/yangfan04/.vscode-server/bin/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/bin/remote-cli:/home/yangfan04/.local/bin:/home/yangfan04/anaconda3/condabin:/opt/conda/bin:/kubebrain:/usr/local/nvidia/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

$LD_LIBRARY_PATH:bash: /data/onnxruntime-linux-x64-1.8.1/lib:/data/onnxruntime-linux-x64-1.8.1/lib:/usr/local/nvidia/lib64
```

### Error traceback

```Shell
Traceback:
Traceback (most recent call last):
  File "/home/yangfan04/anaconda3/envs/mmdeploy1/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/yangfan04/anaconda3/envs/mmdeploy1/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/data/MMDeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/data/MMDeploy/mmdeploy/apis/pytorch2onnx.py", line 112, in torch2onnx
    optimize=optimize)
  File "/data/MMDeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/data/MMDeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/data/MMDeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/data/MMDeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/data/MMDeploy/mmdeploy/apis/onnx/export.py", line 142, in export
    verbose=verbose)
  File "/home/yangfan04/anaconda3/envs/mmdeploy1/lib/python3.7/site-packages/torch/onnx/__init__.py", line 276, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/yangfan04/anaconda3/envs/mmdeploy1/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/yangfan04/anaconda3/envs/mmdeploy1/lib/python3.7/site-packages/torch/onnx/utils.py", line 698, in _export
    dynamic_axes=dynamic_axes)
  File "/data/MMDeploy/mmdeploy/apis/onnx/optimizer.py", line 27, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/home/yangfan04/anaconda3/envs/mmdeploy1/lib/python3.7/site-packages/torch/onnx/utils.py", line 456, in _model_to_graph
    use_new_jit_passes)
  File "/home/yangfan04/anaconda3/envs/mmdeploy1/lib/python3.7/site-packages/torch/onnx/utils.py", line 417, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
File "/home/yangfan04/anaconda3/envs/mmdeploy1/lib/python3.7/site-packages/torch/onnx/utils.py", line 377, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/yangfan04/anaconda3/envs/mmdeploy1/lib/python3.7/site-packages/torch/jit/_trace.py", line 1139, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/yangfan04/anaconda3/envs/mmdeploy1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yangfan04/anaconda3/envs/mmdeploy1/lib/python3.7/site-packages/torch/jit/_trace.py", line 130, in forward
    self._force_outplace,
  File "/home/yangfan04/anaconda3/envs/mmdeploy1/lib/python3.7/site-packages/torch/jit/_trace.py", line 119, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: DataSample
08/10 11:46:29 - mmengine - ERROR - /data/MMDeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 81 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.


Thanks.
```

**Comment by RunningLeon** [comment]
hi, the model is not supported by https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmpretrain.html#supported-models.
