### ISSUE TITLE
[Bug] AssertionError: Input shape should be between (1, 3, 512, 1024) and (1, 3, 512, 1024) but get (1, 3, 1024, 1911).

### ISSUE THREAD

**Issue by gitleej** [open-mmlab/mmdeploy#2366]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

# Run Message
```shell
D:\ProgramData\.conda\envs\openmmlab\python.exe "D:/Program Files/JetBrains/PyCharm 2023.1.2/plugins/python/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 54709 --file E:\00-Truking\02-Code\mmdeploy\tools\test.py .\mmdeploy\configs\mmseg\segmentation_tensorrt_static-512x1024.py .\mmsegmentation\configs\stdc\stdc2_in1k-pre_4xb12-80k_medicine_board_with_ok-512x1024.py --model .\mmdeploy_model_convert\trt\stdc2_in1k-pre_4xb12-80k_medicine_board_with_ok-512x1024\end2end.engine --device cuda:0 
Connected to pydev debugger (build 231.9011.38)
08/22 10:41:33 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
08/22 10:41:33 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "mmseg_tasks" registry tree. As a workaround, the current "mmseg_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
08/22 10:41:39 - mmengine - WARNING - Attribute `_fully_initialized` is not defined in <class 'mmseg.datasets.cityscapes.CityscapesDataset'> or `type(obj)._fully_initialized is False, `full_init` will be called and <class 'mmseg.datasets.cityscapes.CityscapesDataset'>._fully_initialized will be set to True
08/22 10:43:20 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "backend_segmentors" registry tree. As a workaround, the current "backend_segmentors" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
08/22 10:43:20 - mmengine - INFO - Successfully loaded tensorrt plugins from E:\00-Truking\02-Code\mmdeploy\mmdeploy\lib\mmdeploy_tensorrt_ops.dll
08/22 10:43:20 - mmengine - INFO - Successfully loaded tensorrt plugins from E:\00-Truking\02-Code\mmdeploy\mmdeploy\lib\mmdeploy_tensorrt_ops.dll
[08/22/2023-10:43:21] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.8.0 but loaded cuBLAS/cuBLAS LT 11.5.1
[08/22/2023-10:43:21] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.8.0 but loaded cuBLAS/cuBLAS LT 11.5.1
08/22 10:43:58 - mmengine - INFO - 
------------------------------------------------------------
System environment:
    sys.platform: win32
    Python: 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
    CUDA available: True
    numpy_random_seed: 794147490
    GPU 0: NVIDIA GeForce RTX 3050 Laptop GPU
    CUDA_HOME: D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
    NVCC: Cuda compilation tools, release 11.2, V11.2.67
    MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30151 for x64
    GCC: n/a
    PyTorch: 1.12.0
    PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

    TorchVision: 0.13.0
    OpenCV: 4.8.0
    MMEngine: 0.8.4

Runtime environment:
    dist_cfg: {'backend': 'nccl'}
    seed: 794147490
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------

08/22 10:43:58 - mmengine - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) RuntimeInfoHook                    
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
before_train:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(NORMAL      ) DistSamplerSeedHook                
 -------------------- 
before_train_iter:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_train_iter:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(NORMAL      ) SegVisualizationHook               
(BELOW_NORMAL) LoggerHook                         
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) IterTimerHook                      
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_val:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
before_val_epoch:
(NORMAL      ) IterTimerHook                      
 -------------------- 
before_val_iter:
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_val_iter:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) SegVisualizationHook               
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_val_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
after_val:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
after_train:
(VERY_HIGH   ) RuntimeInfoHook                    
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_test:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
before_test_epoch:
(NORMAL      ) IterTimerHook                      
 -------------------- 
before_test_iter:
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_test_iter:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) SegVisualizationHook               
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_test_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_test:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
after_run:
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
E:\00-Truking\02-Code\mmsegmentation\mmseg\engine\hooks\visualization_hook.py:61: UserWarning: The draw is False, it means that the hook for visualization will not take effect. The results will NOT be visualized or stored.
  warnings.warn('The draw is False, it means that the '
08/22 10:44:12 - mmengine - WARNING - The prefix is not set in metric class IoUMetric.
Traceback (most recent call last):
  File "D:\ProgramData\.conda\envs\openmmlab\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\ProgramData\.conda\envs\openmmlab\lib\site-packages\mmengine\runner\loops.py", line 454, in run_iter
    outputs = self.runner.model.test_step(data_batch)
  File "D:\ProgramData\.conda\envs\openmmlab\lib\site-packages\mmengine\model\base_model\base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "D:\ProgramData\.conda\envs\openmmlab\lib\site-packages\mmengine\model\base_model\base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "D:\ProgramData\.conda\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\00-Truking\02-Code\mmdeploy\mmdeploy\codebase\mmseg\deploy\segmentation_model.py", line 86, in forward
    batch_outputs = self.wrapper({self.input_name:
  File "D:\ProgramData\.conda\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\00-Truking\02-Code\mmdeploy\mmdeploy\backend\tensorrt\wrapper.py", line 148, in forward
    assert s_min <= s_input <= s_max, \
AssertionError: Input shape should be between (1, 3, 512, 1024) and (1, 3, 512, 1024) but get (1, 3, 1024, 1911).
python-BaseException

Process finished with exit code 1

```

### Reproduction

# cmd
```shell
python .\mmdeploy\tools\test.py .\mmdeploy\configs\mmseg\segmentation_tensorrt_static-512x1024.py .\mmsegmentation\configs\stdc\stdc2_in1k-pre_4xb12-80k_medicine_board_with_ok-512x1024.py --model .\mmdeploy_model_convert\trt\stdc2_in1k-pre_4xb12-80k_medicine_board_with_ok-512x1024\end2end.engine --device cuda:0 
```
.\mmsegmentation\configs\stdc\stdc2_in1k-pre_4xb12-80k_medicine_board_with_ok-512x1024.py **only change the dataset path.** Based on ".\mmsegmentation\configs\stdc\stdc2_in1k-pre_4xb12-80k_cityscapes-512x1024.py"

### Environment

```Shell
08/22 11:00:48 - mmengine - INFO - **********Environmental information**********
08/22 11:01:00 - mmengine - INFO - sys.platform: win32
08/22 11:01:00 - mmengine - INFO - Python: 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
08/22 11:01:00 - mmengine - INFO - CUDA available: True
08/22 11:01:00 - mmengine - INFO - numpy_random_seed: 2147483648
08/22 11:01:00 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3050 Laptop GPU
08/22 11:01:00 - mmengine - INFO - CUDA_HOME: D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
08/22 11:01:00 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.2, V11.2.67
08/22 11:01:00 - mmengine - INFO - MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30151 for x64
08/22 11:01:00 - mmengine - INFO - GCC: n/a
08/22 11:01:00 - mmengine - INFO - PyTorch: 1.12.0
08/22 11:01:00 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

08/22 11:01:00 - mmengine - INFO - TorchVision: 0.13.0
08/22 11:01:00 - mmengine - INFO - OpenCV: 4.8.0
08/22 11:01:00 - mmengine - INFO - MMEngine: 0.8.4
08/22 11:01:00 - mmengine - INFO - MMCV: 2.0.1
08/22 11:01:00 - mmengine - INFO - MMCV Compiler: MSVC 192930148
08/22 11:01:00 - mmengine - INFO - MMCV CUDA Compiler: 11.3
08/22 11:01:00 - mmengine - INFO - MMDeploy: 1.2.0+a7e9be2
08/22 11:01:00 - mmengine - INFO -

08/22 11:01:00 - mmengine - INFO - **********Backend information**********
08/22 11:01:01 - mmengine - INFO - tensorrt:    8.4.0.6
08/22 11:01:01 - mmengine - INFO - tensorrt custom ops: Available
08/22 11:01:01 - mmengine - INFO - ONNXRuntime: 1.8.1
08/22 11:01:01 - mmengine - INFO - ONNXRuntime-gpu:     None
08/22 11:01:01 - mmengine - INFO - ONNXRuntime custom ops:      NotAvailable
08/22 11:01:01 - mmengine - INFO - pplnn:       None
08/22 11:01:01 - mmengine - INFO - ncnn:        None
08/22 11:01:01 - mmengine - INFO - snpe:        None
08/22 11:01:01 - mmengine - INFO - openvino:    None
08/22 11:01:01 - mmengine - INFO - torchscript: 1.12.0
08/22 11:01:01 - mmengine - INFO - torchscript custom ops:      NotAvailable
08/22 11:01:01 - mmengine - INFO - rknn-toolkit:        None
08/22 11:01:01 - mmengine - INFO - rknn-toolkit2:       None
08/22 11:01:01 - mmengine - INFO - ascend:      None
08/22 11:01:01 - mmengine - INFO - coreml:      None
08/22 11:01:01 - mmengine - INFO - tvm: None
08/22 11:01:01 - mmengine - INFO - vacc:        None
08/22 11:01:01 - mmengine - INFO -

08/22 11:01:01 - mmengine - INFO - **********Codebase information**********
08/22 11:01:02 - mmengine - INFO - mmdet:       None
08/22 11:01:02 - mmengine - INFO - mmseg:       1.1.1
08/22 11:01:02 - mmengine - INFO - mmpretrain:  1.0.2
08/22 11:01:02 - mmengine - INFO - mmocr:       None
08/22 11:01:02 - mmengine - INFO - mmagic:      None
08/22 11:01:02 - mmengine - INFO - mmdet3d:     None
08/22 11:01:02 - mmengine - INFO - mmpose:      None
08/22 11:01:02 - mmengine - INFO - mmrotate:    None
08/22 11:01:02 - mmengine - INFO - mmaction:    None
08/22 11:01:02 - mmengine - INFO - mmrazor:     None
08/22 11:01:02 - mmengine - INFO - mmyolo:      None
```

### Error traceback

```Shell
E:\00-Truking\02-Code\mmsegmentation\mmseg\engine\hooks\visualization_hook.py:61: UserWarning: The draw is False, it means that the hook for visualization will not take effect. The results will NOT be visualized or stored.
  warnings.warn('The draw is False, it means that the '
08/22 10:44:12 - mmengine - WARNING - The prefix is not set in metric class IoUMetric.
Traceback (most recent call last):
  File "D:\ProgramData\.conda\envs\openmmlab\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\ProgramData\.conda\envs\openmmlab\lib\site-packages\mmengine\runner\loops.py", line 454, in run_iter
    outputs = self.runner.model.test_step(data_batch)
  File "D:\ProgramData\.conda\envs\openmmlab\lib\site-packages\mmengine\model\base_model\base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "D:\ProgramData\.conda\envs\openmmlab\lib\site-packages\mmengine\model\base_model\base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "D:\ProgramData\.conda\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\00-Truking\02-Code\mmdeploy\mmdeploy\codebase\mmseg\deploy\segmentation_model.py", line 86, in forward
    batch_outputs = self.wrapper({self.input_name:
  File "D:\ProgramData\.conda\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\00-Truking\02-Code\mmdeploy\mmdeploy\backend\tensorrt\wrapper.py", line 148, in forward
    assert s_min <= s_input <= s_max, \
AssertionError: Input shape should be between (1, 3, 512, 1024) and (1, 3, 512, 1024) but get (1, 3, 1024, 1911).
```

**Comment by gitleej** [comment]
When i try to test the export model with trt backend in python, i meet this error, the input image size is 450*840, but the dataload output is 1024*1911 with the scale_factor(2.275, 2.275). I can't find where to set scale_factor.
