### ISSUE TITLE
deploy.py crashes on headless installation

### ISSUE THREAD

**Issue by tehkillerbee** [open-mmlab/mmdeploy#238]
Hello everyone,

I noticed a small bug when deploying on a headless installation.

The deployment process will terminate, before generating test output. It does appear that the correct engine output is generated, just not the validation image output.

A simple workaround is to run the deploy.py with xforwarding enabled.
```
2022-03-15:06:29:28,root ERROR    [utils.py:41] no display name and no $DISPLAY environment variable
Traceback (most recent call last):
  File "/home/nvidia/git/work/MMDeploy/mmdeploy/utils/utils.py", line 36, in target_wrapper
    result = target(*args, **kwargs)
  File "/home/nvidia/git/work/MMDeploy/mmdeploy/apis/visualize.py", line 68, in visualize_model
    show_result=show_result)
  File "/home/nvidia/git/work/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 184, in visualize
    score_thr=score_thr)
  File "/home/nvidia/git/work/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 286, in show_result
    out_file=out_file)
  File "/home/nvidia/git/work/mmdetection/mmdet/models/detectors/base.py", line 353, in show_result
    out_file=out_file)
  File "/home/nvidia/git/work/mmdetection/mmdet/core/visualization/image.py", line 119, in imshow_det_bboxes
    fig = plt.figure(win_name, frameon=False)
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 539, in figure
    **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 171, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py", line 1049, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
2022-03-15 06:29:30,000 - mmdeploy - ERROR - visualize tensorrt model failed.
```

**Comment by hanrui1sensetime** [comment]
Hi, @tehkillerbee, I will fix the bug by skipping show_results when you on headless installation.

**Comment by tehkillerbee** [comment]
@hanrui1sensetime Great! I'll close this issue since it has been merged already.

**Comment by AllentDan** [comment]
Hi, @tehkillerbee. Could you not use `--show` argument for deploy.py and check if it works? Just like the PR #293. Or if it still does not work. Could you try [this](https://stackoverflow.com/questions/37604289/tkinter-tclerror-no-display-name-and-no-display-environment-variable) out? 

As there are many situations that we want to save the drawed image to the remote headless machine.

**Comment by tehkillerbee** [comment]
@AllentDan Yes, I will test it ASAP when I have a Xavier AGX on hand.

**Comment by tehkillerbee** [comment]
@AllentDan I noticed that the error still occurs when --show is not set. I.e., the default state for show is 'true'. I actually never set --show in the first place.

So it looks like I cannot disable it on a headless system.
