### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by woshinangua** [open-mmlab/mmdeploy#2386]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

TypeError: build_backend_model() takes from 1 to 2 positional arguments but 3 were given

### Reproduction

from mmdeploy.apis import inference_model
result = inference_model(
  model_cfg='./mmocr/configs/textdet/dbnet/dbnet_resnet18_fpnc_1200e_totaltext.py',
  deploy_cfg='./mmdeploy/configs/mmocr/text-detection/text-detection_onnxruntime_dynamic.py',
  backend_files=['./mmdeploy_model/end2end.onnx'],
  img='./mmocr/demo/demo_text_det.jpg',
  device='cpu')
# 控制台打印得到的results结果
print("result: {}".format(result))

### Environment

```Shell
08/29 12:55:37 - mmengine - INFO - **********Environmental information**********
08/29 12:55:39 - mmengine - INFO - sys.platform: linux
08/29 12:55:39 - mmengine - INFO - Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
08/29 12:55:39 - mmengine - INFO - CUDA available: True
08/29 12:55:39 - mmengine - INFO - numpy_random_seed: 2147483648
08/29 12:55:39 - mmengine - INFO - GPU 0,1: GeForce RTX 3090
08/29 12:55:39 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.1
08/29 12:55:39 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.1, V11.1.105
08/29 12:55:39 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
08/29 12:55:39 - mmengine - INFO - PyTorch: 1.8.0
08/29 12:55:39 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

08/29 12:55:39 - mmengine - INFO - TorchVision: 0.9.0
08/29 12:55:39 - mmengine - INFO - OpenCV: 4.8.0
08/29 12:55:39 - mmengine - INFO - MMEngine: 0.8.4
08/29 12:55:39 - mmengine - INFO - MMCV: 2.0.1
08/29 12:55:39 - mmengine - INFO - MMCV Compiler: GCC 7.3
08/29 12:55:39 - mmengine - INFO - MMCV CUDA Compiler: 11.1
08/29 12:55:39 - mmengine - INFO - MMDeploy: 1.2.0+7c7e43b
08/29 12:55:39 - mmengine - INFO -

08/29 12:55:39 - mmengine - INFO - **********Backend information**********
08/29 12:55:39 - mmengine - INFO - tensorrt:    8.2.3.0
08/29 12:55:39 - mmengine - INFO - tensorrt custom ops: Available
08/29 12:55:39 - mmengine - INFO - ONNXRuntime: 1.8.1
08/29 12:55:39 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
08/29 12:55:39 - mmengine - INFO - ONNXRuntime custom ops:      Available
08/29 12:55:39 - mmengine - INFO - pplnn:       None
08/29 12:55:39 - mmengine - INFO - ncnn:        None
08/29 12:55:39 - mmengine - INFO - snpe:        None
08/29 12:55:39 - mmengine - INFO - openvino:    None
08/29 12:55:39 - mmengine - INFO - torchscript: 1.8.0
08/29 12:55:39 - mmengine - INFO - torchscript custom ops:      NotAvailable
08/29 12:55:39 - mmengine - INFO - rknn-toolkit:        None
08/29 12:55:39 - mmengine - INFO - rknn-toolkit2:       None
08/29 12:55:39 - mmengine - INFO - ascend:      None
08/29 12:55:39 - mmengine - INFO - coreml:      None
08/29 12:55:39 - mmengine - INFO - tvm: None
08/29 12:55:39 - mmengine - INFO - vacc:        None
08/29 12:55:39 - mmengine - INFO -

08/29 12:55:39 - mmengine - INFO - **********Codebase information**********
08/29 12:55:39 - mmengine - INFO - mmdet:       3.1.0
08/29 12:55:39 - mmengine - INFO - mmseg:       None
08/29 12:55:39 - mmengine - INFO - mmpretrain:  None
08/29 12:55:39 - mmengine - INFO - mmocr:       1.0.1
08/29 12:55:39 - mmengine - INFO - mmagic:      None
08/29 12:55:39 - mmengine - INFO - mmdet3d:     None
08/29 12:55:39 - mmengine - INFO - mmpose:      None
08/29 12:55:39 - mmengine - INFO - mmrotate:    None
08/29 12:55:39 - mmengine - INFO - mmaction:    None
08/29 12:55:39 - mmengine - INFO - mmrazor:     None
08/29 12:55:39 - mmengine - INFO - mmyolo:      None
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    device='cpu')
  File "/home/yejian/lh/MMDeploy/mmdeploy/apis/inference.py", line 46, in inference_model
    backend_files, task_processor.update_data_preprocessor)
TypeError: build_backend_model() takes from 1 to 2 positional arguments but 3 were given
(mmdeploy) root@2084a876b2bd:/home/yejian/lh# vim +46 /home/yejian/lh/MMDeploy/mmdeploy/apis/inference.py
(mmdeploy) root@2084a876b2bd:/home/yejian/lh# python /mmdeploy/tools/check_env.py
python: can't open file '/mmdeploy/tools/check_env.py': [Errno 2] No such file or directory
```

**Comment by woshinangua** [comment]
我把model = task_processor.build_backend_model(backend_files, task_processor.update_data_preprocessor)中的ask_processor.update_data_preprocessor这个参数删除掉，改为model = task_processor.build_backend_model(backend_files)后，倒是输出了结果：result: [<TextRecogDataSample(

    META INFORMATION
    img_path: './mmocr/demo/demo_text_recog.jpg'
    ori_shape: (182, 206)
    batch_input_shape: (32, 128)
    img_shape: (32, 128)
    valid_ratio: 1.0

    DATA FIELDS
    pred_text: <LabelData(

            META INFORMATION

            DATA FIELDS
            item: 'star'
            score: [0.9999845027923584, 0.9999897480010986, 0.9999806880950928, 0.9998551607131958]
        ) at 0x7f91da5b3a10>
    gt_text: <LabelData(

            META INFORMATION

            DATA FIELDS
        ) at 0x7f91d92cf110>
) at 0x7f91d92cf0d0>]

**Comment by RunningLeon** [comment]
@woshinangua hi, thanks for your feedback, could you try to change the argument as kargs, eg. ` data_preprocessor_updater=task_processor.update_data_preprocessor)` ?
https://github.com/open-mmlab/mmdeploy/blob/b7024ddfe5b435a7aa481f81a9449dc485fd71b4/mmdeploy/apis/inference.py#L46
