### ISSUE TITLE
[Bug] Here, received an input of unsupported type: InstanceData

### ISSUE THREAD

**Issue by facias914** [open-mmlab/mmdeploy#2390]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I have searched the other same Bug report,but can not solve the question.

I wanted to convert the RTMDet-rotated model to onnx and tensorrt. My trained model is in the mmyolo folder, and in mmyolo I compiled mmdeploy from source, and then used tools/deploy.py in mmdeploy floder to convert model.

### Reproduction

python mmdeploy/tools/deploy.py mmdeploy/configs/mmrotate/rotated-detection_onnxruntime_static.py   configs/rtmdet/rotated/rtmdet_rgb-ir_ms.py work_dir/best_dota_mAP_epoch_14.pth /data/img.png --work-dir work_dirs --device cuda --dump-info

python mmdeploy/tools/deploy.py configs/deploy/detection_onnxruntime_static.py   configs/rtmdet/rotated/rtmdet_rgb-ir_ms.py work_dir/best_dota_mAP_epoch_14.pth /data/img.png --work-dir work_dirs --device cuda --dump-info

### Environment

```Shell
mmcv                      2.0.0rc4                 pypi_0    pypi
mmdeploy                  1.2.0                     dev_0    <develop>
mmdet                     3.0.0                    pypi_0    pypi
mmengine                  0.8.4                    pypi_0    pypi
mmrotate                  1.0.0rc1                 pypi_0    pypi
mmyolo                    0.6.0                     dev_0    <develop>
```

### Error traceback

```Shell
08/31 11:13:04 - mmengine - WARNING - Failed to search registry with scope "mmrotate" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmrotate" is a correct scope, or whether the registry is initialized.
08/31 11:13:04 - mmengine - WARNING - Failed to search registry with scope "mmrotate" in the "mmrotate_tasks" registry tree. As a workaround, the current "mmrotate_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmrotate" is a correct scope, or whether the registry is initialized.
08/31 11:13:04 - mmengine - WARNING - Failed to search registry with scope "mmyolo" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmyolo" is a correct scope, or whether the registry is initialized.
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/mmrotate/utils/setup_env.py:32: UserWarning: The current default scope "mmyolo" is not "mmrotate", `register_all_modules` will force the currentdefault scope to be "mmrotate". If this is not expected, please set `init_default_scope=False`.
  warnings.warn('The current default scope '
08/31 11:13:05 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
08/31 11:13:06 - mmengine - WARNING - Failed to search registry with scope "mmrotate" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmrotate" is a correct scope, or whether the registry is initialized.
08/31 11:13:06 - mmengine - WARNING - Failed to search registry with scope "mmrotate" in the "mmrotate_tasks" registry tree. As a workaround, the current "mmrotate_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmrotate" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: work_dir/best_dota_mAP_epoch_14.pth
08/31 11:13:07 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
08/31 11:13:07 - mmengine - INFO - Export PyTorch model to ONNX: work_dirs/end2end.onnx.
/data/facias/mmyolo/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/single_stage.py:80: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  img_shape = [int(val) for val in img_shape]
/data/facias/mmyolo/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/single_stage.py:80: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  img_shape = [int(val) for val in img_shape]
/data/facias/mmyolo/mmdeploy/mmdeploy/core/optimizers/function_marker.py:160: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/data/facias/mmyolo/mmyolo/models/task_modules/coders/distance_angle_point_coder.py:58: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert points.size(-2) == pred_bboxes.size(-2)
/data/facias/mmyolo/mmyolo/models/task_modules/coders/distance_angle_point_coder.py:59: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert points.size(-1) == 2
/data/facias/mmyolo/mmyolo/models/task_modules/coders/distance_angle_point_coder.py:60: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(-1) == 5
/data/facias/mmyolo/mmyolo/models/dense_heads/rtmdet_rotated_head.py:439: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  img_meta) in zip(flatten_decoded_bboxes, flatten_cls_scores,
/data/facias/mmyolo/mmyolo/models/dense_heads/rtmdet_rotated_head.py:460: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if scores.shape[0] == 0:       #不需要
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/mmdet/models/utils/misc.py:336: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  num_topk = min(topk, valid_idxs.size(0))
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/mmdet/structures/bbox/base_boxes.py:62: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  data = torch.as_tensor(data)
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/mmdet/structures/bbox/base_boxes.py:73: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if data.numel() == 0:
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/mmdet/structures/bbox/base_boxes.py:76: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert data.dim() >= 2 and data.size(-1) == self.box_dim, \
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/mmengine/structures/instance_data.py:306: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  return len(self.values()[0])
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/mmengine/structures/instance_data.py:152: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(value) == len(self), 'The length of ' \
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/mmdet/models/dense_heads/base_dense_head.py:477: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if with_nms and results.bboxes.numel() > 0:
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/mmcv/ops/nms.py:533: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if boxes.size(-1) == 5:
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/mmcv/ops/nms.py:543: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  max_coordinate + torch.tensor(1).to(boxes))
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/mmcv/ops/nms.py:558: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if boxes_for_nms.shape[0] < split_thr:
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/mmcv/ops/nms.py:400: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if dets.shape[0] == 0:
/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/mmengine/structures/instance_data.py:220: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  indexes = item.cpu().numpy().tolist()
Process Process-2:
Traceback (most recent call last):
  File "/home/facias/.conda/envs/rtmdet/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/facias/.conda/envs/rtmdet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/facias/mmyolo/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/data/facias/mmyolo/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "/data/facias/mmyolo/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/data/facias/mmyolo/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/data/facias/mmyolo/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/data/facias/mmyolo/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/data/facias/mmyolo/mmdeploy/mmdeploy/apis/onnx/export.py", line 138, in export
    torch.onnx.export(
  File "/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/data/facias/mmyolo/mmdeploy/mmdeploy/apis/onnx/optimizer.py", line 27, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/facias/.conda/envs/rtmdet/lib/python3.8/site-packages/torch/jit/_trace.py", line 121, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: InstanceData
```

**Comment by RunningLeon** [comment]
hi, isn't rtmdet-rotate from [mmrotate](https://github.com/open-mmlab/mmrotate/tree/dev-1.x/configs/rotated_rtmdet), which you should use `configs/mmrotate/rotated-detection_onnxruntime_static.py` as deploy_config?

**Comment by facias914** [comment]
> hi, isn't rtmdet-rotate from [mmrotate](https://github.com/open-mmlab/mmrotate/tree/dev-1.x/configs/rotated_rtmdet), which you should use `configs/mmrotate/rotated-detection_onnxruntime_static.py` as deploy_config?

Thanks! I also noticed this problem. But should I retrain the rtmdet model using the mmrotate

**Comment by RunningLeon** [comment]
hi, maybe you can ask it in mmroate repo how you can convert the model config and ckpt to mmrotate style

**Comment by hehaodong530** [comment]
hi, have you solved the problem?

**Comment by sharanms88** [comment]
I am also having the same issue. But it is with Yoloact from mmdet.  Any solution that you found works?
