### ISSUE TITLE
[Bug] RuntimeError: Failed to parse onnx, In node 972 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

### ISSUE THREAD

**Issue by 564192234** [open-mmlab/mmdeploy#2398]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

我将训练完成的mmrotate.pth模型转换为trt模型的过程中出现了错误。work-dir内生成了三个json文件和end2end文件，后就无法继续生成了。安装mmdeploy是按照0.x的版本linux_x86进行源码安装，因为我只是要将pth转为trt，所以并没有安装pplcv。

### Reproduction

python mmdeploy/tools/deploy.py /home/superdisk/cu102/mmdeploy/mmdeploy/configs/mmrotate/rotated-detection_tensorrt_dynamic-320x320-1024x1024.py /home/superdisk/cu102/mmdeploy/mmdeploy/mmrotate_config_pth/rotated_retinanet_obb_csl_gaussian_r50_fpn_fp16_1x_dota_le90.py /home/superdisk/cu102/mmdeploy/mmdeploy/mmrotate_config_pth/epoch_20.pth /home/superdisk/cu102/mmdeploy/mmdeploy/mmrotate_config_pth/output_image2126.jpg --work-dir mmdeploy_model/test_retinanet --device cuda --dump-info

### Environment

```Shell
2023-09-04 08:36:21,628 - mmdeploy - INFO - 

2023-09-04 08:36:21,628 - mmdeploy - INFO - **********Environmental information**********
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2023-09-04 08:36:21,775 - mmdeploy - INFO - sys.platform: linux
2023-09-04 08:36:21,775 - mmdeploy - INFO - Python: 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00) [GCC 11.4.0]
2023-09-04 08:36:21,775 - mmdeploy - INFO - CUDA available: True
2023-09-04 08:36:21,775 - mmdeploy - INFO - GPU 0: Quadro RTX 8000
2023-09-04 08:36:21,775 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2023-09-04 08:36:21,775 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.8
2023-09-04 08:36:21,775 - mmdeploy - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
2023-09-04 08:36:21,775 - mmdeploy - INFO - PyTorch: 1.8.0
2023-09-04 08:36:21,775 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

2023-09-04 08:36:21,775 - mmdeploy - INFO - TorchVision: 0.9.0
2023-09-04 08:36:21,775 - mmdeploy - INFO - OpenCV: 4.8.0
2023-09-04 08:36:21,775 - mmdeploy - INFO - MMCV: 1.7.1
2023-09-04 08:36:21,775 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2023-09-04 08:36:21,776 - mmdeploy - INFO - MMCV CUDA Compiler: 10.2
2023-09-04 08:36:21,776 - mmdeploy - INFO - MMDeploy: 0.14.0+
2023-09-04 08:36:21,776 - mmdeploy - INFO - 

2023-09-04 08:36:21,776 - mmdeploy - INFO - **********Backend information**********
2023-09-04 08:36:21,800 - mmdeploy - INFO - tensorrt:   8.2.3.0
2023-09-04 08:36:21,800 - mmdeploy - INFO - tensorrt custom ops:        Available
2023-09-04 08:36:21,817 - mmdeploy - INFO - ONNXRuntime:        1.8.1
2023-09-04 08:36:21,817 - mmdeploy - INFO - ONNXRuntime-gpu:    None
2023-09-04 08:36:21,817 - mmdeploy - INFO - ONNXRuntime custom ops:     Available
2023-09-04 08:36:21,818 - mmdeploy - INFO - pplnn:      None
2023-09-04 08:36:21,819 - mmdeploy - INFO - ncnn:       None
2023-09-04 08:36:21,821 - mmdeploy - INFO - snpe:       None
2023-09-04 08:36:21,822 - mmdeploy - INFO - openvino:   None
2023-09-04 08:36:21,822 - mmdeploy - INFO - torchscript:        1.8.0
2023-09-04 08:36:21,823 - mmdeploy - INFO - torchscript custom ops:     NotAvailable
2023-09-04 08:36:21,837 - mmdeploy - INFO - rknn-toolkit:       None
2023-09-04 08:36:21,837 - mmdeploy - INFO - rknn2-toolkit:      None
2023-09-04 08:36:21,838 - mmdeploy - INFO - ascend:     None
2023-09-04 08:36:21,839 - mmdeploy - INFO - coreml:     None
2023-09-04 08:36:21,840 - mmdeploy - INFO - tvm:        None
2023-09-04 08:36:21,840 - mmdeploy - INFO - 

2023-09-04 08:36:21,840 - mmdeploy - INFO - **********Codebase information**********
2023-09-04 08:36:22,509 - mmdeploy - INFO - mmdet:      2.28.2
2023-09-04 08:36:22,509 - mmdeploy - INFO - mmseg:      None
2023-09-04 08:36:22,509 - mmdeploy - INFO - mmcls:      None
2023-09-04 08:36:22,509 - mmdeploy - INFO - mmocr:      None
2023-09-04 08:36:22,509 - mmdeploy - INFO - mmedit:     None
2023-09-04 08:36:22,509 - mmdeploy - INFO - mmdet3d:    None
2023-09-04 08:36:22,509 - mmdeploy - INFO - mmpose:     None
2023-09-04 08:36:22,509 - mmdeploy - INFO - mmrotate:   0.3.4
2023-09-04 08:36:22,509 - mmdeploy - INFO - mmaction:   None
```

### Error traceback

```Shell
/root/anaconda3/envs/mmrotate/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/root/anaconda3/envs/mmrotate/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/root/anaconda3/envs/mmrotate/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
2023-09-04 09:08:42,738 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
load checkpoint from local path: /home/superdisk/cu102/mmdeploy/mmdeploy/mmrotate_config_pth/epoch_20.pth
2023-09-04 09:08:45,296 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2023-09-04 09:08:45,296 - mmdeploy - INFO - Export PyTorch model to ONNX: mmdeploy_model/test_retinanet/end2end.onnx.
2023-09-04 09:08:45,322 - mmdeploy - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
2023-09-04 09:08:45,326 - mmdeploy - WARNING - Can not find torch.nn.functional._scaled_dot_product_attention, function rewrite will not be applied
2023-09-04 09:08:45,326 - mmdeploy - WARNING - Can not find torch._C._jit_pass_onnx_deduplicate_initializers, function rewrite will not be applied
/home/superdisk/cu102/mmdeploy/mmdeploy/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/home/superdisk/rotate/rotate/mmrotate/mmrotate/models/dense_heads/csl_rotated_retina_head.py:427: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/home/superdisk/rotate/rotate/mmrotate/mmrotate/models/dense_heads/csl_rotated_retina_head.py:440: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if scores.shape[0] > nms_pre > 0:
/home/superdisk/cu102/mmdeploy/mmdeploy/mmdeploy/pytorch/functions/topk.py:58: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k > size:
/home/superdisk/rotate/rotate/mmrotate/mmrotate/core/bbox/coder/delta_xywha_rbbox_coder.py:101: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/home/superdisk/rotate/rotate/mmrotate/mmrotate/core/post_processing/bbox_nms_rotated.py:35: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if multi_bboxes.shape[1] > 5:
/home/superdisk/rotate/rotate/mmrotate/mmrotate/core/post_processing/bbox_nms_rotated.py:75: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if bboxes.size(-1) == 5:
/root/anaconda3/envs/mmrotate/lib/python3.8/site-packages/mmcv/ops/nms.py:448: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if dets.shape[0] == 0:
2023-09-04 09:08:53,542 - mmdeploy - INFO - Execute onnx optimize passes.
2023-09-04 09:08:55,838 - mmdeploy - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
/root/anaconda3/envs/mmrotate/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
2023-09-04 09:08:56,824 - mmdeploy - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in subprocess
2023-09-04 09:08:56,842 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /home/superdisk/cu102/mmdeploy/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
[09/04/2023-09:08:57] [TRT] [I] [MemUsageChange] Init CUDA: CPU +294, GPU +0, now: CPU 348, GPU 341 (MiB)
[09/04/2023-09:08:57] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 348 MiB, GPU 341 MiB
[09/04/2023-09:08:57] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 441 MiB, GPU 375 MiB
[09/04/2023-09:08:57] [TRT] [I] ----------------------------------------------------------------
[09/04/2023-09:08:57] [TRT] [I] Input filename:   mmdeploy_model/test_retinanet/end2end.onnx
[09/04/2023-09:08:57] [TRT] [I] ONNX IR version:  0.0.6
[09/04/2023-09:08:57] [TRT] [I] Opset version:    11
[09/04/2023-09:08:57] [TRT] [I] Producer name:    pytorch
[09/04/2023-09:08:57] [TRT] [I] Producer version: 1.8
[09/04/2023-09:08:57] [TRT] [I] Domain:           
[09/04/2023-09:08:57] [TRT] [I] Model version:    0
[09/04/2023-09:08:57] [TRT] [I] Doc string:       
[09/04/2023-09:08:57] [TRT] [I] ----------------------------------------------------------------
[09/04/2023-09:08:57] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[09/04/2023-09:08:57] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[09/04/2023-09:08:57] [TRT] [I] No importer registered for op: GridPriorsTRT. Attempting to import as plugin.
[09/04/2023-09:08:57] [TRT] [I] Searching for plugin: GridPriorsTRT, plugin_version: 1, plugin_namespace: 
[09/04/2023-09:08:57] [TRT] [I] Successfully created plugin: GridPriorsTRT
[09/04/2023-09:08:57] [TRT] [I] No importer registered for op: GridPriorsTRT. Attempting to import as plugin.
[09/04/2023-09:08:57] [TRT] [I] Searching for plugin: GridPriorsTRT, plugin_version: 1, plugin_namespace: 
[09/04/2023-09:08:57] [TRT] [I] Successfully created plugin: GridPriorsTRT
[09/04/2023-09:08:57] [TRT] [I] No importer registered for op: GridPriorsTRT. Attempting to import as plugin.
[09/04/2023-09:08:57] [TRT] [I] Searching for plugin: GridPriorsTRT, plugin_version: 1, plugin_namespace: 
[09/04/2023-09:08:57] [TRT] [I] Successfully created plugin: GridPriorsTRT
[09/04/2023-09:08:57] [TRT] [I] No importer registered for op: GridPriorsTRT. Attempting to import as plugin.
[09/04/2023-09:08:57] [TRT] [I] Searching for plugin: GridPriorsTRT, plugin_version: 1, plugin_namespace: 
[09/04/2023-09:08:57] [TRT] [I] Successfully created plugin: GridPriorsTRT
[09/04/2023-09:08:57] [TRT] [I] No importer registered for op: GridPriorsTRT. Attempting to import as plugin.
[09/04/2023-09:08:57] [TRT] [I] Searching for plugin: GridPriorsTRT, plugin_version: 1, plugin_namespace: 
[09/04/2023-09:08:57] [TRT] [I] Successfully created plugin: GridPriorsTRT
[09/04/2023-09:08:57] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
[09/04/2023-09:08:58] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
[09/04/2023-09:08:58] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
[09/04/2023-09:08:58] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
[09/04/2023-09:08:58] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
[09/04/2023-09:08:59] [TRT] [I] No importer registered for op: NonZero. Attempting to import as plugin.
[09/04/2023-09:08:59] [TRT] [I] Searching for plugin: NonZero, plugin_version: 1, plugin_namespace: 
[09/04/2023-09:08:59] [TRT] [E] ModelImporter.cpp:773: While parsing node number 972 [NonZero -> "1995"]:
[09/04/2023-09:08:59] [TRT] [E] ModelImporter.cpp:774: --- Begin node ---
[09/04/2023-09:08:59] [TRT] [E] ModelImporter.cpp:775: input: "1994"
output: "1995"
name: "NonZero_972"
op_type: "NonZero"

[09/04/2023-09:08:59] [TRT] [E] ModelImporter.cpp:776: --- End node ---
[09/04/2023-09:08:59] [TRT] [E] ModelImporter.cpp:779: ERROR: builtin_op_importers.cpp:4870 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
Process Process-3:
Traceback (most recent call last):
  File "/root/anaconda3/envs/mmrotate/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/mmrotate/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/superdisk/cu102/mmdeploy/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/superdisk/cu102/mmdeploy/mmdeploy/mmdeploy/apis/utils/utils.py", line 95, in to_backend
    return backend_mgr.to_backend(
  File "/home/superdisk/cu102/mmdeploy/mmdeploy/mmdeploy/backend/tensorrt/backend_manager.py", line 129, in to_backend
    onnx2tensorrt(
  File "/home/superdisk/cu102/mmdeploy/mmdeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "/home/superdisk/cu102/mmdeploy/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 181, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 972 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
```

**Comment by RunningLeon** [comment]
hi, first of all, make sure the model is supported by this [doc](https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmrotate.html#supported-models). Secondly, as the error log suggtests, the model has `NonZero`, which is not support by  TensorRT.
> [09/04/2023-09:08:59] [TRT] [E] ModelImporter.cpp:773: While parsing node number 972 [NonZero -> "1995"]:
[09/04/2023-09:08:59] [TRT] [E] ModelImporter.cpp:774: --- Begin node ---
[09/04/2023-09:08:59] [TRT] [E] ModelImporter.cpp:775: input: "1994"
output: "1995"
name: "NonZero_972"
op_type: "NonZero"

**Comment by 564192234** [comment]
请问是什么意思呢，看到文档是RotatedRetinaNet支持onnx和tensorrt，我用rotated_retinanet_obb_csl_gaussian_r50_fpn_fp16_1x_dota_le90.py训练自己的数据集，其他暂时都没有更改，训练出来的模型也不支持转换吗。请问哪些mmrotate是支持的转换成trt的。谢谢

**Comment by 564192234** [comment]
我换了成了rotated_retinanet_obb_r50_fpn_1x_dota_ms_rr_le90.py，解决了整个问题。谢谢您。
