### ISSUE TITLE
[Bug] Conversion of Rotated-RCNN model into ONNX fails

### ISSUE THREAD

**Issue by prashant-dn** [open-mmlab/mmdeploy#2421]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I have used mmrotate to train a Rotated-RCNN model using the sample notebook. Now I wish to export it as onnx. So I use the dockerfile provided in the mmdeploy repo and create an image. Then I follow the official instructions to export the model `faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth`. For this, my environment is:

> mmdet-v3.0 + mmdeploy-v1.2 + mmcv-v2.0.0 + mmrotateANY-> works

On running
```console
python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py \
    mmdetection/configs/faster_rcnn/faster-rcnn_r50_fpn_1x_coco.py \
    checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    mmdetection/demo/demo.jpg \
    --work-dir mmdeploy_model/faster-rcnn \
    --device cuda \
    --dump-info
```

I can successfully export the engine as well as the onnx. 

Now I use the same environment to convert my custom (rotated-rcnn) model, using
```
python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmrotate/rotated-detection_tensorrt_dynamic-320x320-1024x1024.py \
    /mmrotate/demo/custom-config.py \
    /mmrotate/popo_exps/9sep-1230/epoch_30.pth \
    /mmrotate/demo/demo.jpg \
    --work-dir mmdeploy_model/custom-rotated-rcnn \
    --device cuda \
    --dump-info
```

I get the error that `mmcv` and `mmdet` versions were incompatible. So as per the instructions, I downgraded them. My environment then,
> mmdet-v2.28.2 + mmdeploy-v1.2 + mmrotate-v0.3.4 + mmcv-v1.3.17/v1.7.1

Now the `deploy.py` throws error:
```console
Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 335, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 129, in main
    export2SDK(
  File "/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 352, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 267, in get_deploy
    _, customs = get_model_name_customs(
  File "/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 61, in get_model_name_customs
    task_processor = build_task_processor(
  File "/mmdeploy/mmdeploy/apis/utils/utils.py", line 46, in build_task_processor
    import_codebase(codebase_type, custom_module_list)
  File "/mmdeploy/mmdeploy/codebase/__init__.py", line 37, in import_codebase
    codebase.register_all_modules()
  File "/mmdeploy/mmdeploy/codebase/mmrotate/deploy/rotated_detection.py", line 34, in register_all_modules
    from mmdet.utils.setup_env import \
ImportError: cannot import name 'register_all_modules' from 'mmdet.utils.setup_env' (/opt/conda/lib/python3.8/site-packages/mmdet/utils/setup_env.py)
```

Note that I am using `main` branches for all the repos here. 
-------
In a [similar issue](https://github.com/open-mmlab/mmdeploy/issues/1480), switching to the `dev-1.x` branch helped but when I switch to `dev-1.x` branch, and upgrade mmdet, mmcv to latest versions, I get a new error
```console
root@807b7f5c7232:/# python3 mmdeploy/tools/deploy.py     mmdeploy/configs/mmrotate/rotated-detection_tensorrt_dynamic-320x320-1024x1024.py     /mmrotate/demo/custom-popo-config.py     /mmrotate/popo_exps/9sep-1230/epoch_30.pth     /mmrotate/demo/demo.jpg     --work-dir mmdeploy_model/custom-rotated-rcnn     --device cuda     --dump-info
09/11 10:44:18 - mmengine - WARNING - Failed to search registry with scope "mmrotate" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmrotate" is a correct scope, or whether the registry is initialized.
09/11 10:44:18 - mmengine - WARNING - Failed to search registry with scope "mmrotate" in the "mmrotate_tasks" registry tree. As a workaround, the current "mmrotate_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmrotate" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 335, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 129, in main
    export2SDK(
  File "/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 352, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 267, in get_deploy
    _, customs = get_model_name_customs(
  File "/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 61, in get_model_name_customs
    task_processor = build_task_processor(
  File "/mmdeploy/mmdeploy/apis/utils/utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "/mmdeploy/mmdeploy/codebase/base/mmcodebase.py", line 45, in build_task_processor
    return cls.task_registry.build(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mmdeploy/mmdeploy/codebase/mmrotate/deploy/rotated_detection.py", line 156, in __init__
    super().__init__(model_cfg, deploy_cfg, device, experiment_name)
  File "/mmdeploy/mmdeploy/codebase/base/task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/utils/manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/default_scope.py", line 35, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None
```

### Reproduction

Simply follow the official instructions given in the mmdeploy repo: https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/02-how-to-run/convert_model.md

### Environment

```Shell
root@807b7f5c7232:/# python3 mmdeploy/tools/check_env.py 
09/11 13:34:26 - mmengine - INFO - 

09/11 13:34:26 - mmengine - INFO - **********Environmental information**********
09/11 13:34:27 - mmengine - INFO - sys.platform: linux
09/11 13:34:27 - mmengine - INFO - Python: 3.8.17 (default, Jul  5 2023, 21:04:15) [GCC 11.2.0]
09/11 13:34:27 - mmengine - INFO - CUDA available: True
09/11 13:34:27 - mmengine - INFO - numpy_random_seed: 2147483648
09/11 13:34:27 - mmengine - INFO - GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 2080 Ti
09/11 13:34:27 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
09/11 13:34:27 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.124
09/11 13:34:27 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
09/11 13:34:27 - mmengine - INFO - PyTorch: 1.10.0
09/11 13:34:27 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

09/11 13:34:27 - mmengine - INFO - TorchVision: 0.11.0
09/11 13:34:27 - mmengine - INFO - OpenCV: 4.8.0
09/11 13:34:27 - mmengine - INFO - MMEngine: 0.8.4
09/11 13:34:27 - mmengine - INFO - MMCV: 2.0.1
09/11 13:34:27 - mmengine - INFO - MMCV Compiler: GCC 9.3
09/11 13:34:27 - mmengine - INFO - MMCV CUDA Compiler: 11.3
09/11 13:34:27 - mmengine - INFO - MMDeploy: 1.2.0+
09/11 13:34:27 - mmengine - INFO - 

09/11 13:34:27 - mmengine - INFO - **********Backend information**********
09/11 13:34:27 - mmengine - INFO - tensorrt:    8.2.4.2
09/11 13:34:27 - mmengine - INFO - tensorrt custom ops: NotAvailable
09/11 13:34:27 - mmengine - INFO - ONNXRuntime: None
09/11 13:34:27 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
09/11 13:34:27 - mmengine - INFO - ONNXRuntime custom ops:      NotAvailable
09/11 13:34:27 - mmengine - INFO - pplnn:       None
09/11 13:34:27 - mmengine - INFO - ncnn:        None
09/11 13:34:27 - mmengine - INFO - snpe:        None
09/11 13:34:27 - mmengine - INFO - openvino:    None
09/11 13:34:27 - mmengine - INFO - torchscript: 1.10.0
09/11 13:34:27 - mmengine - INFO - torchscript custom ops:      NotAvailable
09/11 13:34:28 - mmengine - INFO - rknn-toolkit:        None
09/11 13:34:28 - mmengine - INFO - rknn-toolkit2:       None
09/11 13:34:28 - mmengine - INFO - ascend:      None
09/11 13:34:28 - mmengine - INFO - coreml:      None
09/11 13:34:28 - mmengine - INFO - tvm: None
09/11 13:34:28 - mmengine - INFO - vacc:        None
09/11 13:34:28 - mmengine - INFO - 

09/11 13:34:28 - mmengine - INFO - **********Codebase information**********
09/11 13:34:28 - mmengine - INFO - mmdet:       3.0.0
09/11 13:34:28 - mmengine - INFO - mmseg:       None
09/11 13:34:28 - mmengine - INFO - mmpretrain:  None
09/11 13:34:28 - mmengine - INFO - mmocr:       None
09/11 13:34:28 - mmengine - INFO - mmagic:      None
09/11 13:34:28 - mmengine - INFO - mmdet3d:     None
09/11 13:34:28 - mmengine - INFO - mmpose:      None
09/11 13:34:28 - mmengine - INFO - mmrotate:    1.0.0rc1
09/11 13:34:28 - mmengine - INFO - mmaction:    None
09/11 13:34:28 - mmengine - INFO - mmrazor:     None
09/11 13:34:28 - mmengine - INFO - mmyolo:      None
root@807b7f5c7232:/#
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 335, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 129, in main
    export2SDK(
  File "/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 352, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 267, in get_deploy
    _, customs = get_model_name_customs(
  File "/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 61, in get_model_name_customs
    task_processor = build_task_processor(
  File "/mmdeploy/mmdeploy/apis/utils/utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "/mmdeploy/mmdeploy/codebase/base/mmcodebase.py", line 45, in build_task_processor
    return cls.task_registry.build(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mmdeploy/mmdeploy/codebase/mmrotate/deploy/rotated_detection.py", line 156, in __init__
    super().__init__(model_cfg, deploy_cfg, device, experiment_name)
  File "/mmdeploy/mmdeploy/codebase/base/task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/utils/manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/default_scope.py", line 35, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None
```

**Comment by RunningLeon** [comment]
@prashant-dn hi, for mmrotate, pls. use dev-1.x. for other codebases, pls. use main branch.

**Comment by prashant-dn** [comment]
I tried the same env
```console

10/03 12:54:50 - mmengine - INFO - TorchVision: 0.11.0
10/03 12:54:50 - mmengine - INFO - OpenCV: 4.8.0
10/03 12:54:50 - mmengine - INFO - MMEngine: 0.8.4
10/03 12:54:50 - mmengine - INFO - MMCV: 2.0.0rc4
10/03 12:54:50 - mmengine - INFO - MMCV Compiler: GCC 9.3
10/03 12:54:50 - mmengine - INFO - MMCV CUDA Compiler: 11.3
10/03 12:54:50 - mmengine - INFO - MMDeploy: 1.2.0+
10/03 12:54:50 - mmengine - INFO - 

10/03 12:54:50 - mmengine - INFO - **********Backend information**********
10/03 12:54:51 - mmengine - INFO - tensorrt:    8.2.4.2
10/03 12:54:51 - mmengine - INFO - tensorrt custom ops: Available
10/03 12:54:51 - mmengine - INFO - ONNXRuntime: None
10/03 12:54:51 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
10/03 12:54:51 - mmengine - INFO - ONNXRuntime custom ops:      Available
10/03 12:54:51 - mmengine - INFO - pplnn:       None
10/03 12:54:51 - mmengine - INFO - ncnn:        None
10/03 12:54:51 - mmengine - INFO - snpe:        None
10/03 12:54:51 - mmengine - INFO - openvino:    None
10/03 12:54:51 - mmengine - INFO - torchscript: 1.10.0
10/03 12:54:51 - mmengine - INFO - torchscript custom ops:      NotAvailable
10/03 12:54:51 - mmengine - INFO - rknn-toolkit:        None
10/03 12:54:51 - mmengine - INFO - rknn-toolkit2:       None
10/03 12:54:51 - mmengine - INFO - ascend:      None
10/03 12:54:51 - mmengine - INFO - coreml:      None
10/03 12:54:51 - mmengine - INFO - tvm: None
10/03 12:54:51 - mmengine - INFO - vacc:        None
10/03 12:54:51 - mmengine - INFO - 

10/03 12:54:51 - mmengine - INFO - **********Codebase information**********
10/03 12:54:51 - mmengine - INFO - mmdet:       3.1.0
10/03 12:54:51 - mmengine - INFO - mmseg:       None
10/03 12:54:51 - mmengine - INFO - mmpretrain:  None
10/03 12:54:51 - mmengine - INFO - mmocr:       None
10/03 12:54:51 - mmengine - INFO - mmagic:      None
10/03 12:54:51 - mmengine - INFO - mmdet3d:     None
10/03 12:54:51 - mmengine - INFO - mmpose:      None
10/03 12:54:51 - mmengine - INFO - mmrotate:    1.0.0rc1
10/03 12:54:51 - mmengine - INFO - mmaction:    None
10/03 12:54:51 - mmengine - INFO - mmrazor:     None
10/03 12:54:51 - mmengine - INFO - mmyolo:      None

```
Still got the error
```console
root@322e5bd9080a:/# python3 mmdeploy/tools/deploy.py     mmdeploy/configs/mmrotate/rotated-detection_tens
orrt_dynamic-320x320-1024x1024.py     /mmrotate/demo/custom-popo-config.py     /mmrotate/popo_exps/9sep-12
30/epoch_30.pth     /mmrotate/demo/demo.jpg     --work-dir mmdeploy_model/custom-rotated-rcnn     --device
 cuda     --dump-info
10/03 12:56:28 - mmengine - WARNING - Failed to search registry with scope "mmrotate" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmrotate" is a correct scope, or whether the registry is initialized.
10/03 12:56:28 - mmengine - WARNING - Failed to search registry with scope "mmrotate" in the "mmrotate_tasks" registry tree. As a workaround, the current "mmrotate_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmrotate" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 335, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 129, in main
    export2SDK(
  File "/root/workspace/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 352, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/root/workspace/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 267, in get_deploy
    _, customs = get_model_name_customs(
  File "/root/workspace/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 61, in get_model_name_customs
    task_processor = build_task_processor(
  File "/root/workspace/mmdeploy/mmdeploy/apis/utils/utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "/root/workspace/mmdeploy/mmdeploy/codebase/base/mmcodebase.py", line 45, in build_task_processor
    return cls.task_registry.build(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmrotate/deploy/rotated_detection.py", line 156, in __init__
    super().__init__(model_cfg, deploy_cfg, device, experiment_name)
  File "/root/workspace/mmdeploy/mmdeploy/codebase/base/task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/utils/manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/default_scope.py", line 35, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None
```
