### ISSUE TITLE
[Bug] RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage (tagged with gpu)

### ISSUE THREAD

**Issue by volkov-maxim** [open-mmlab/mmdeploy#2454]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hi!

When I try to convert PyTorch mmpose model `td-hm_hrnet-w48_dark-8xb32-210e_coco-wholebody-384x288` to TensorRT, I get a `RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage (tagged with gpu)`.

### Reproduction

1. Download configs and weights 
`mim download mmpose --config td-hm_hrnet-w48_dark-8xb32-210e_coco-wholebody-384x288 --dest .`
2. Run command for convert the model
`py tools/deploy.py configs/mmpose/pose-detection_tensorrt_dynamic-256x192.py td-hm_hrnet-w48_dark-8xb32-210e_coco-wholebody-384x288.py hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth demo/resources/human-pose.jpg --work-dir mmdeploy_models/mmpose/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918 --device gpu --show`

### Environment

```Shell
09/21 15:26:01 - mmengine - INFO - 

09/21 15:26:01 - mmengine - INFO - **********Environmental information**********
09/21 15:26:02 - mmengine - INFO - sys.platform: linux
09/21 15:26:02 - mmengine - INFO - Python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
09/21 15:26:02 - mmengine - INFO - CUDA available: True
09/21 15:26:02 - mmengine - INFO - numpy_random_seed: 2147483648
09/21 15:26:02 - mmengine - INFO - GPU 0,1: NVIDIA GeForce RTX 3080 Ti
09/21 15:26:02 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-12.2
09/21 15:26:02 - mmengine - INFO - NVCC: Cuda compilation tools, release 12.2, V12.2.140
09/21 15:26:02 - mmengine - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
09/21 15:26:02 - mmengine - INFO - PyTorch: 2.0.0+cu117
09/21 15:26:02 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.9.4  (built against CUDA 12.2)
    - Built with CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

09/21 15:26:02 - mmengine - INFO - TorchVision: 0.15.1+cu117
09/21 15:26:02 - mmengine - INFO - OpenCV: 4.7.0
09/21 15:26:02 - mmengine - INFO - MMEngine: 0.8.4
09/21 15:26:02 - mmengine - INFO - MMCV: 2.0.1
09/21 15:26:02 - mmengine - INFO - MMCV Compiler: GCC 9.3
09/21 15:26:02 - mmengine - INFO - MMCV CUDA Compiler: 11.7
09/21 15:26:02 - mmengine - INFO - MMDeploy: 1.2.0+71a1e6c
09/21 15:26:02 - mmengine - INFO - 

09/21 15:26:02 - mmengine - INFO - **********Backend information**********
09/21 15:26:02 - mmengine - INFO - tensorrt:	8.6.1
09/21 15:26:02 - mmengine - INFO - tensorrt custom ops:	Available
09/21 15:26:02 - mmengine - INFO - ONNXRuntime:	None
09/21 15:26:02 - mmengine - INFO - pplnn:	None
09/21 15:26:02 - mmengine - INFO - ncnn:	None
09/21 15:26:02 - mmengine - INFO - snpe:	None
09/21 15:26:02 - mmengine - INFO - openvino:	None
09/21 15:26:02 - mmengine - INFO - torchscript:	2.0.0
09/21 15:26:02 - mmengine - INFO - torchscript custom ops:	NotAvailable
09/21 15:26:02 - mmengine - INFO - rknn-toolkit:	None
09/21 15:26:02 - mmengine - INFO - rknn-toolkit2:	None
09/21 15:26:02 - mmengine - INFO - ascend:	None
09/21 15:26:02 - mmengine - INFO - coreml:	None
09/21 15:26:02 - mmengine - INFO - tvm:	None
09/21 15:26:02 - mmengine - INFO - vacc:	None
09/21 15:26:02 - mmengine - INFO - 

09/21 15:26:02 - mmengine - INFO - **********Codebase information**********
09/21 15:26:02 - mmengine - INFO - mmdet:	3.1.0
09/21 15:26:02 - mmengine - INFO - mmseg:	None
09/21 15:26:02 - mmengine - INFO - mmpretrain:	None
09/21 15:26:02 - mmengine - INFO - mmocr:	None
09/21 15:26:02 - mmengine - INFO - mmagic:	None
09/21 15:26:02 - mmengine - INFO - mmdet3d:	None
09/21 15:26:02 - mmengine - INFO - mmpose:	1.1.0
09/21 15:26:02 - mmengine - INFO - mmrotate:	None
09/21 15:26:02 - mmengine - INFO - mmaction:	None
09/21 15:26:02 - mmengine - INFO - mmrazor:	None
09/21 15:26:02 - mmengine - INFO - mmyolo:	None



$ echo $PATH
/home/test/bin:/home/test/.rbenv/shims:/home/test/.rbenv/bin:/usr/local/cuda-12.2/bin:/home/test/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin


$ echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64:/home/test/TensorRT-8.6.1.6/lib:/usr/local/cuda-12.2/lib64

$ echo $PYTHONPATH
(empty, I use venv)
```

### Error traceback

```Shell
09/21 15:05:24 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
09/21 15:05:25 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
09/21 15:05:25 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/test/lib/python3.10/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/test/lib/python3.10/site-packages/mmdeploy/apis/pytorch2onnx.py", line 63, in torch2onnx
    torch_model = task_processor.build_pytorch_model(model_checkpoint)
  File "/home/test/lib/python3.10/site-packages/mmdeploy/codebase/base/task.py", line 123, in build_pytorch_model
    load_checkpoint(model, model_checkpoint, map_location=self.device)
  File "/home/test/lib/python3.10/site-packages/mmengine/runner/checkpoint.py", line 636, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/test/lib/python3.10/site-packages/mmengine/runner/checkpoint.py", line 548, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/test/lib/python3.10/site-packages/mmengine/runner/checkpoint.py", line 330, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/test/lib/python3.10/site-packages/mmengine/runner/checkpoint.py", line 347, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/test/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/test/lib/python3.10/site-packages/torch/serialization.py", line 1043, in _legacy_load
    result = unpickler.load()
  File "/home/test/lib/python3.10/site-packages/torch/serialization.py", line 980, in persistent_load
    wrap_storage=restore_location(obj, location),
  File "/home/test/lib/python3.10/site-packages/torch/serialization.py", line 1083, in restore_location
    return default_restore_location(storage, map_location)
  File "/home/test/lib/python3.10/site-packages/torch/serialization.py", line 220, in default_restore_location
    raise RuntimeError("don't know how to restore data location of "
RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage (tagged with gpu)
09/21 15:05:25 - mmengine - ERROR - /home/test/lib/python3.10/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by RunningLeon** [comment]
hi, you should run with `tools/deploy.py xx --device cuda`, not `--device gpu`

**Comment by volkov-maxim** [comment]
> hi, you should run with `tools/deploy.py xx --device cuda`, not `--device gpu`

@RunningLeon  Thank you very much for your help!
