### ISSUE TITLE
[Bug] TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by korneliaWatson** [open-mmlab/mmdeploy#2474]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hi. 

I see there was another user experiencing this behaviour but its cause or a solution haven't been specified. 

I have two custom MMPose models trained using the same script.

When I try to convert them to onnx models, one converts fine, one fails with 
```
File "/home/project/mmdeploy/mmdeploy/codebase/mmpose/deploy/pose_detection.py", line 261, in create_input
    data.update(meta_data)
TypeError: 'NoneType' object is not iterable
```

Would someone be able to tell me when that `meta_data` is being created? How come the behaviour is not consistent, it works for some models and fails for others. Any helps getting this error resolved would be appreciated.

### Reproduction

python /home/project/mmdeploy/tools/deploy.py /home/project/mmdeploy/configs/mmpose/pose-detection_onnxruntime_static.py /home/project/artifacts/config.py /home/project/artifacts/checkpoint.pth /home/project/artifacts/demo_image.jpg --work-dir /home/project/ort/ --device cpu

### Environment

```Shell
09/29 11:15:07 - mmengine - INFO - **********Environmental information**********
09/29 11:15:08 - mmengine - INFO - sys.platform: linux
09/29 11:15:08 - mmengine - INFO - Python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
09/29 11:15:08 - mmengine - INFO - CUDA available: False
09/29 11:15:08 - mmengine - INFO - numpy_random_seed: 2147483648
09/29 11:15:08 - mmengine - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
09/29 11:15:08 - mmengine - INFO - PyTorch: 2.0.1+cpu
09/29 11:15:08 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

09/29 11:15:08 - mmengine - INFO - TorchVision: 0.15.2+cpu
09/29 11:15:08 - mmengine - INFO - OpenCV: 4.8.0
09/29 11:15:08 - mmengine - INFO - MMEngine: 0.8.4
09/29 11:15:08 - mmengine - INFO - MMCV: 2.0.1
09/29 11:15:08 - mmengine - INFO - MMCV Compiler: GCC 7.3
09/29 11:15:08 - mmengine - INFO - MMCV CUDA Compiler: not available
09/29 11:15:08 - mmengine - INFO - MMDeploy: 1.2.0+6e60cae
09/29 11:15:08 - mmengine - INFO - 

09/29 11:15:08 - mmengine - INFO - **********Backend information**********
09/29 11:15:08 - mmengine - INFO - tensorrt:    None
09/29 11:15:08 - mmengine - INFO - ONNXRuntime: 1.15.1
09/29 11:15:08 - mmengine - INFO - ONNXRuntime-gpu:     None
09/29 11:15:08 - mmengine - INFO - ONNXRuntime custom ops:      Available
09/29 11:15:08 - mmengine - INFO - pplnn:       None
09/29 11:15:08 - mmengine - INFO - ncnn:        None
09/29 11:15:08 - mmengine - INFO - snpe:        None
09/29 11:15:08 - mmengine - INFO - openvino:    None
09/29 11:15:08 - mmengine - INFO - torchscript: 2.0.1+cpu
09/29 11:15:08 - mmengine - INFO - torchscript custom ops:      NotAvailable
09/29 11:15:08 - mmengine - INFO - rknn-toolkit:        None
09/29 11:15:08 - mmengine - INFO - rknn-toolkit2:       None
09/29 11:15:08 - mmengine - INFO - ascend:      None
09/29 11:15:08 - mmengine - INFO - coreml:      None
09/29 11:15:08 - mmengine - INFO - tvm: None
09/29 11:15:08 - mmengine - INFO - vacc:        None
09/29 11:15:08 - mmengine - INFO - 

09/29 11:15:08 - mmengine - INFO - **********Codebase information**********
09/29 11:15:08 - mmengine - INFO - mmdet:       3.1.0
09/29 11:15:08 - mmengine - INFO - mmseg:       None
09/29 11:15:08 - mmengine - INFO - mmpretrain:  None
09/29 11:15:08 - mmengine - INFO - mmocr:       None
09/29 11:15:08 - mmengine - INFO - mmagic:      None
09/29 11:15:08 - mmengine - INFO - mmdet3d:     None
09/29 11:15:08 - mmengine - INFO - mmpose:      1.1.0
09/29 11:15:08 - mmengine - INFO - mmrotate:    None
09/29 11:15:08 - mmengine - INFO - mmaction:    None
09/29 11:15:08 - mmengine - INFO - mmrazor:     None
09/29 11:15:08 - mmengine - INFO - mmyolo:      None
```

### Error traceback

```Shell
09/29 11:15:45 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: /home/project/artifacts/checkpoint.pth
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/project/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/project/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 64, in torch2onnx
    data, model_inputs = task_processor.create_input(
  File "/home/project/mmdeploy/mmdeploy/codebase/mmpose/deploy/pose_detection.py", line 261, in create_input
    data.update(meta_data)
TypeError: 'NoneType' object is not iterable
09/29 11:15:46 - mmengine - ERROR - /home/project/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by RunningLeon** [comment]
@korneliaWatson hi, pls. make sure your `test_pipeline` in model config is consistent with official configs provided by mmpose: https://github.com/open-mmlab/mmpose/blob/537bd8e543ab463fb55120d5caaa1ae22d6aaf06/configs/body_2d_keypoint/simcc/coco/simcc_mobilenetv2_wo-deconv-8xb64-210e_coco-256x192.py#L77

**Comment by timsainb** [comment]
@korneliaWatson I'm running into the same error can you tell me what you did to fix it?
