### ISSUE TITLE
[Bug] Convert CO-DETR error

### ISSUE THREAD

**Issue by monsterlyg** [open-mmlab/mmdeploy#2484]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [x] 3. The bug has not been fixed in the latest version.

### Describe the bug

Try to export co-detr with mmdeploy, but returned traceback.

### Reproduction

from mmdeploy.apis import torch2onnx
from mmdeploy.backend.sdk.export_info import export2SDK

img = 'demo/demo.jpg'
work_dir = 'mmdeploy_models/mmdet/onnx'
save_file = 'end2end.onnx'
deploy_cfg = '../mmdeploy/configs/mmdet/detection/detection_onnxruntime_static.py'
model_cfg = 'projects/CO-DETR/configs/codino/co_dino_5scale_r50_lsj_8xb2_1x_coco.py'
model_checkpoint = 'checkpoints/co_dino_5scale_r50_lsj_8xb2_1x_coco-69a72d67.pth'
device = 'cpu'
torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
           model_checkpoint, device)

### Environment

```Shell
mmdetection-dev-3.x   PyTorch: 1.13.1  10/09 19:41:30 - mmengine - INFO - TorchVision: 0.14.1
10/09 19:41:30 - mmengine - INFO - OpenCV: 4.8.1
10/09 19:41:30 - mmengine - INFO - MMEngine: 0.8.5
10/09 19:41:30 - mmengine - INFO - MMCV: 2.0.1
10/09 19:41:30 - mmengine - INFO - MMCV Compiler: GCC 9.3
10/09 19:41:30 - mmengine - INFO - MMCV CUDA Compiler: 11.6
10/09 19:41:30 - mmengine - INFO - MMDeploy: 1.3.0+59449cc
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/root/mnt2/lyg/Projects/mmdetection/convert.py", line 13, in <module>
    torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/onnx/export.py", line 138, in export
    torch.onnx.export(
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/onnx/optimizer.py", line 27, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/jit/_trace.py", line 121, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: DetDataSample
```

**Comment by RunningLeon** [comment]
hi, CO-DETR is not supported by far: https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmdet.html#supported-models

**Comment by YOODS-Xu** [comment]
@monsterlyg 
您好
这个问题您解决了吗？
我查资料有说co-detr的执行就是dino。mmdeploy是可以转换dino的，所以也可以转换co-detr。
如果您解决了，还请教一下怎么解决的。

**Comment by YOODS-Xu** [comment]
@RunningLeon 
多谢您的贡献。
我在用mmdeploy转换co-detr到onnx时，也遇到了以下的报错。
如果您知道如何解决，敬请赐教。

RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: DetDataSample

我的config如下
from mmdeploy.apis import torch2onnx
from mmdeploy.backend.sdk.export_info import export2SDK

img = 'demo/00000003_00000000675A0D0C_06.jpg'
work_dir = 'mmdeploy_models/onnx'
save_file = 'co-detr-wiener-r50-lsj.onnx'
deploy_cfg = '/home2/ros/miniconda3/envs/openmmlab/mmdeploy/configs/mmdet/detection/detection_onnxruntime_static.py'
model_cfg = './work_dir/co-detr-wiener.py'
model_checkpoint = './work_dir/epoch_12.pth'
device = 'cpu'

# 1. convert model to onnx
torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
           model_checkpoint, device)

# 2. extract pipeline info for inference by MMDeploy SDK
export2SDK(deploy_cfg, model_cfg, work_dir, pth=model_checkpoint,
           device=device)

**Comment by monsterlyg** [comment]
听说新版本代码官方已经修复了



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 29, 2024 16:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmdeploy] [Bug] Convert CO-DETR error (Issue #2484)




 
@RunningLeon
 多谢您的贡献。
 我在用mmdeploy转换co-detr到onnx时，也遇到了以下的报错。
 如果您知道如何解决，敬请赐教。
 
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: DetDataSample
 
我的config如下
 from mmdeploy.apis import torch2onnx
 from mmdeploy.backend.sdk.export_info import export2SDK
 
img = 'demo/00000003_00000000675A0D0C_06.jpg'
 work_dir = 'mmdeploy_models/onnx'
 save_file = 'co-detr-wiener-r50-lsj.onnx'
 deploy_cfg = '/home2/ros/miniconda3/envs/openmmlab/mmdeploy/configs/mmdet/detection/detection_onnxruntime_static.py'
 model_cfg = './work_dir/co-detr-wiener.py'
 model_checkpoint = './work_dir/epoch_12.pth'
 device = 'cpu'
 
1. convert model to onnx
 
torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
 model_checkpoint, device)
 
2. extract pipeline info for inference by MMDeploy SDK
 
export2SDK(deploy_cfg, model_cfg, work_dir, pth=model_checkpoint,
 device=device)

**Comment by YOODS-Xu** [comment]
@monsterlyg 
多谢您的赐教。
我按照下面的方法，
https://github.com/Sense-X/Co-DETR/issues/26#issuecomment-1707752118
修改了库文件，
lib/python3.8/site-packages/torch/jit/_trace.py
可以生成onnx了，不过还是报错
The bbox is out of bounds, the drawn bbox may not be in the image
The polygon is out of bounds, the drawn polygon may not be in the image
用的图像尺寸和训练的尺寸是一样的。

**Comment by monsterlyg** [comment]
> @monsterlyg 多谢您的赐教。 我按照下面的方法， [Sense-X/Co-DETR#26 (comment)](https://github.com/Sense-X/Co-DETR/issues/26#issuecomment-1707752118) 修改了库文件， lib/python3.8/site-packages/torch/jit/_trace.py 可以生成onnx了，不过还是报错 The bbox is out of bounds, the drawn bbox may not be in the image The polygon is out of bounds, the drawn polygon may not be in the image 用的图像尺寸和训练的尺寸是一样的。

那你可以考虑对图像的box输出做个clip了，

**Comment by YOODS-Xu** [comment]
@monsterlyg 非常感谢您的赐教。
