### ISSUE TITLE
[Bug] AssertionError: scope_name should be a string, but got None

### ISSUE THREAD

**Issue by AndreaMacri-sys** [open-mmlab/mmdeploy#2490]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hello,
I'm trying to convert a mmpretrain model (specifically a MobileNet V3) into a ONNX model, but this error occurs.
I had also tried to convert a mmdet model and the process was successful

### Reproduction

python3 tools/deploy.py configs/mmpretrain/classification_onnxruntime_static.py sys_config/mobilenet_v3/sys_mobilenet-v3-large_8xb128_in1k.py checkpoints/22PM01_mbv3.pth images/pmi.png

### Environment

```Shell
10/11 17:13:41 - mmengine - INFO - 

10/11 17:13:41 - mmengine - INFO - **********Environmental information**********
10/11 17:13:42 - mmengine - INFO - sys.platform: linux
10/11 17:13:42 - mmengine - INFO - Python: 3.8.10 (default, May 26 2023, 14:05:08) [GCC 9.4.0]
10/11 17:13:42 - mmengine - INFO - CUDA available: True
10/11 17:13:42 - mmengine - INFO - numpy_random_seed: 2147483648
10/11 17:13:42 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3050 Laptop GPU
10/11 17:13:42 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
10/11 17:13:42 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.124
10/11 17:13:42 - mmengine - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
10/11 17:13:42 - mmengine - INFO - PyTorch: 2.0.1+cu117
10/11 17:13:42 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.9.5  (built against CUDA 11.8)
    - Built with CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

10/11 17:13:42 - mmengine - INFO - TorchVision: 0.15.2+cu117
10/11 17:13:42 - mmengine - INFO - OpenCV: 4.6.0
10/11 17:13:42 - mmengine - INFO - MMEngine: 0.8.5
10/11 17:13:42 - mmengine - INFO - MMCV: 2.0.1
10/11 17:13:42 - mmengine - INFO - MMCV Compiler: GCC 9.4
10/11 17:13:42 - mmengine - INFO - MMCV CUDA Compiler: 11.6
10/11 17:13:42 - mmengine - INFO - MMDeploy: 1.3.0+1132e82
10/11 17:13:42 - mmengine - INFO - 

10/11 17:13:42 - mmengine - INFO - **********Backend information**********
10/11 17:13:42 - mmengine - INFO - tensorrt:	None
10/11 17:13:42 - mmengine - INFO - ONNXRuntime:	1.16.0
10/11 17:13:42 - mmengine - INFO - ONNXRuntime-gpu:	1.8.1
10/11 17:13:42 - mmengine - INFO - ONNXRuntime custom ops:	Available
10/11 17:13:42 - mmengine - INFO - pplnn:	None
10/11 17:13:42 - mmengine - INFO - ncnn:	None
10/11 17:13:42 - mmengine - INFO - snpe:	None
10/11 17:13:42 - mmengine - INFO - openvino:	None
10/11 17:13:42 - mmengine - INFO - torchscript:	2.0.1
10/11 17:13:42 - mmengine - INFO - torchscript custom ops:	NotAvailable
10/11 17:13:42 - mmengine - INFO - rknn-toolkit:	None
10/11 17:13:42 - mmengine - INFO - rknn-toolkit2:	None
10/11 17:13:42 - mmengine - INFO - ascend:	None
10/11 17:13:42 - mmengine - INFO - coreml:	None
10/11 17:13:42 - mmengine - INFO - tvm:	None
10/11 17:13:42 - mmengine - INFO - vacc:	None
10/11 17:13:42 - mmengine - INFO - 

10/11 17:13:42 - mmengine - INFO - **********Codebase information**********
10/11 17:13:42 - mmengine - INFO - mmdet:	None
10/11 17:13:42 - mmengine - INFO - mmseg:	None
10/11 17:13:42 - mmengine - INFO - mmpretrain:	1.0.2
10/11 17:13:42 - mmengine - INFO - mmocr:	None
10/11 17:13:42 - mmengine - INFO - mmagic:	None
10/11 17:13:42 - mmengine - INFO - mmdet3d:	None
10/11 17:13:42 - mmengine - INFO - mmpose:	None
10/11 17:13:42 - mmengine - INFO - mmrotate:	None
10/11 17:13:42 - mmengine - INFO - mmaction:	None
10/11 17:13:42 - mmengine - INFO - mmrazor:	None
10/11 17:13:42 - mmengine - INFO - mmyolo:	None
```

### Error traceback

```Shell
10/11 16:47:54 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
10/11 16:47:55 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
10/11 16:47:55 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "mmpretrain_tasks" registry tree. As a workaround, the current "mmpretrain_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/andrea/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/andrea/.local/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 61, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/home/andrea/.local/lib/python3.8/site-packages/mmdeploy/apis/utils/utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "/home/andrea/.local/lib/python3.8/site-packages/mmdeploy/codebase/base/mmcodebase.py", line 45, in build_task_processor
    return cls.task_registry.build(
  File "/home/andrea/.local/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/andrea/.local/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/andrea/.local/lib/python3.8/site-packages/mmdeploy/codebase/mmpretrain/deploy/classification.py", line 126, in __init__
    super(Classification, self).__init__(model_cfg, deploy_cfg, device)
  File "/home/andrea/.local/lib/python3.8/site-packages/mmdeploy/codebase/base/task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "/home/andrea/.local/lib/python3.8/site-packages/mmengine/utils/manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "/home/andrea/.local/lib/python3.8/site-packages/mmengine/registry/default_scope.py", line 35, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None
10/11 16:47:55 - mmengine - ERROR - /home/andrea/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by irexyc** [comment]
`sys_mobilenet-v3-large_8xb128_in1k.py` 里面及一行 `default_scope = 'mmpretrain'`试试？

**Comment by AndreaMacri-sys** [comment]
> `sys_mobilenet-v3-large_8xb128_in1k.py` 里面及一行 `default_scope = 'mmpretrain'`试试？

This solved my problem, thank you!
