### ISSUE TITLE
关于pointpillar 模型测试问题[Feature] 

### ISSUE THREAD

**Issue by fpeanut** [open-mmlab/mmdeploy#2496]
### Motivation

我利用tools/deploy顺利生成了engine和onnx模型，但是在运行python3 tools/test.py configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime_dynamic.py ../mmdetection3d/configs/pointpillars/pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py --model ./end2end.onnx --speed-test --device cuda:0时，报出如下错误：
/usr/local/lib/python3.8/dist-packages/mmdet3d/evaluation/functional/kitti_utils/eval.py:10: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def get_thresholds(scores: np.ndarray, num_gt, num_sample_pts=41):
10/17 06:32:54 - mmengine - WARNING - Failed to search registry with scope "mmdet3d" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet3d" is a correct scope, or whether the registry is initialized.
10/17 06:32:54 - mmengine - WARNING - Failed to search registry with scope "mmdet3d" in the "mmdet3d_tasks" registry tree. As a workaround, the current "mmdet3d_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet3d" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "tools/test.py", line 159, in <module>
    main()
  File "tools/test.py", line 120, in main
    dataset = task_processor.build_dataset(test_dataloader['dataset'])
  File "/workspace/mmdeploy/mmdeploy/codebase/base/task.py", line 156, in build_dataset
    dataset = DATASETS.build(dataset_cfg)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmdet3d/datasets/kitti_dataset.py", line 79, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/mmdet3d/datasets/det3d_dataset.py", line 129, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/mmengine/dataset/base_dataset.py", line 245, in __init__
    self.full_init()
  File "/usr/local/lib/python3.8/dist-packages/mmengine/dataset/base_dataset.py", line 296, in full_init
    self.data_list = self.load_data_list()
  File "/usr/local/lib/python3.8/dist-packages/mmengine/dataset/base_dataset.py", line 433, in load_data_list
    annotations = load(self.ann_file)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/fileio/io.py", line 855, in load
    with BytesIO(file_backend.get(file)) as f:
  File "/usr/local/lib/python3.8/dist-packages/mmengine/fileio/backends/local_backend.py", line 33, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/kitti/kitti_infos_val.pkl'

**Comment by RunningLeon** [comment]
You have to prepare datasets before running `test.py`. Same like you train a model.
