### ISSUE TITLE
yolox-pose onnx conver error

### ISSUE THREAD

**Issue by zgq91** [open-mmlab/mmdeploy#2507]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Traceback (most recent call last):
  File "d:\Anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "d:\Anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "e:\python_workspace\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "e:\python_workspace\mmdeploy\mmdeploy\apis\pytorch2onnx.py", line 64, in torch2onnx
    data, model_inputs = task_processor.create_input(
  File "e:\python_workspace\mmdeploy\mmdeploy\codebase\mmpose\deploy\pose_detection.py", line 268, in create_input
    data.update(meta_data)
TypeError: 'NoneType' object is not iterable
10/19 23:09:02 - mmengine - ERROR - e:\python_workspace\mmdeploy\mmdeploy\apis\core\pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

### Reproduction

python tools\deploy.py  configs\mmpose\pose-detection_yolox-pose_onnxruntime_dynamic.py E:\python_workspace\mmyolo\configs\yolox\pose\yolox-pose_tiny_8xb32-300e-rtmdet-hyp_coco.py checkpoint\pose\yolox-pose_tiny_8xb32-300e-rtmdet-hyp_coco_20230427_080351-2117af67.pth demo\resources\human-pose.jpg --work-dir model_deploy\pose\yolox-pose_tiny --show

### Environment

```Shell
10/19 23:25:14 - mmengine - INFO - TorchVision: 0.13.0+cu116
10/19 23:25:14 - mmengine - INFO - OpenCV: 4.8.1
10/19 23:25:14 - mmengine - INFO - MMEngine: 0.9.0
10/19 23:25:14 - mmengine - INFO - MMCV: 2.0.1
10/19 23:25:14 - mmengine - INFO - MMCV Compiler: MSVC 192930152
10/19 23:25:14 - mmengine - INFO - MMCV CUDA Compiler: 11.6
10/19 23:25:14 - mmengine - INFO - MMDeploy: 1.3.0+c4dc10d
10/19 23:25:14 - mmengine - INFO -

10/19 23:25:14 - mmengine - INFO - **********Backend information**********
10/19 23:25:14 - mmengine - INFO - tensorrt:    None
10/19 23:25:14 - mmengine - INFO - ONNXRuntime: 1.16.1
10/19 23:25:14 - mmengine - INFO - ONNXRuntime-gpu:     1.14.0
10/19 23:25:14 - mmengine - INFO - ONNXRuntime custom ops:      NotAvailable
10/19 23:25:14 - mmengine - INFO - pplnn:       None
10/19 23:25:14 - mmengine - INFO - ncnn:        None
10/19 23:25:14 - mmengine - INFO - snpe:        None
10/19 23:25:14 - mmengine - INFO - openvino:    None
10/19 23:25:14 - mmengine - INFO - torchscript: 1.12.0+cu116
10/19 23:25:14 - mmengine - INFO - torchscript custom ops:      NotAvailable
d:\Anaconda3\lib\site-packages\pkg_resources\__init__.py:116: PkgResourcesDeprecationWarning: 4.0.0-unsupported is an invalid version and will not be supported in a future release
  warnings.warn(
10/19 23:25:15 - mmengine - INFO - rknn-toolkit:        None
10/19 23:25:15 - mmengine - INFO - rknn-toolkit2:       None
10/19 23:25:15 - mmengine - INFO - ascend:      None
10/19 23:25:15 - mmengine - INFO - coreml:      None
10/19 23:25:15 - mmengine - INFO - tvm: None
10/19 23:25:15 - mmengine - INFO - vacc:        None
10/19 23:25:15 - mmengine - INFO -

10/19 23:25:15 - mmengine - INFO - **********Codebase information**********
10/19 23:25:15 - mmengine - INFO - mmdet:       3.0.0
10/19 23:25:15 - mmengine - INFO - mmseg:       None
10/19 23:25:15 - mmengine - INFO - mmpretrain:  None
10/19 23:25:15 - mmengine - INFO - mmocr:       None
10/19 23:25:15 - mmengine - INFO - mmagic:      None
10/19 23:25:15 - mmengine - INFO - mmdet3d:     None
10/19 23:25:15 - mmengine - INFO - mmpose:      1.1.0
10/19 23:25:15 - mmengine - INFO - mmrotate:    None
10/19 23:25:15 - mmengine - INFO - mmaction:    1.2.0
10/19 23:25:15 - mmengine - INFO - mmrazor:     None
10/19 23:25:15 - mmengine - INFO - mmyolo:      0.6.0
```

### Error traceback

```Shell
10/19 23:24:05 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
d:\Anaconda3\lib\site-packages\scipy\__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.4)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "
10/19 23:24:07 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
10/19 23:24:07 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
e:\python_workspace\mmpose\mmpose\datasets\datasets\utils.py:102: UserWarning: The metainfo config file "configs/_base_/pose/coco.py" does not exist. A matched config file "e:\python_workspace\mmpose\mmpose\.mim\configs\_base_\datasets\coco.py" will be used instead.
  warnings.warn(
Loads checkpoint by local backend from path: checkpoint\pose\yolox-pose_tiny_8xb32-300e-rtmdet-hyp_coco_20230427_080351-2117af67.pth
Process Process-2:
Traceback (most recent call last):
  File "d:\Anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "d:\Anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "e:\python_workspace\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "e:\python_workspace\mmdeploy\mmdeploy\apis\pytorch2onnx.py", line 64, in torch2onnx
    data, model_inputs = task_processor.create_input(
  File "e:\python_workspace\mmdeploy\mmdeploy\codebase\mmpose\deploy\pose_detection.py", line 265, in create_input
    data.update(meta_data)
TypeError: 'NoneType' object is not iterable
10/19 23:24:08 - mmengine - ERROR - e:\python_workspace\mmdeploy\mmdeploy\apis\core\pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by jonahpearl** [comment]
Any notes on how to fix this?
