### ISSUE TITLE
[Bug] mmdeploy转换mmyolo模型为openvino模型时报错

### ISSUE THREAD

**Issue by vicnoah** [open-mmlab/mmdeploy#2549]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

进行模型转换时报错。
```
root@17859c654b14:~/workspace# python3 mmdeploy/tools/deploy.py mmdeploy/configs/mmdet/detection/detection_openvino_dynamic-300x300.py mmyolo/configs/rtmdet/rtmdet_tiny_fast_1xb12-40e_rail.py /mydata/rail_inter_coco.pth mmdeploy/tests/data/tiger.jpeg --work-dir deploy_result/rail_inter --device cpu --log-level INFO
11/15 03:32:26 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
11/15 03:32:27 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
11/15 03:32:27 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: /mydata/rail_inter_coco.pth
11/15 03:32:28 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
11/15 03:32:28 - mmengine - INFO - Export PyTorch model to ONNX: deploy_result/rail_inter/end2end.onnx.
11/15 03:32:28 - mmengine - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
/root/workspace/mmdeploy/mmdeploy/core/optimizers/function_marker.py:160: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/usr/local/lib/python3.8/dist-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/usr/local/lib/python3.8/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/usr/local/lib/python3.8/dist-packages/mmyolo/models/task_modules/coders/distance_point_bbox_coder.py:45: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert points.size(-2) == pred_bboxes.size(-2)
/usr/local/lib/python3.8/dist-packages/mmyolo/models/task_modules/coders/distance_point_bbox_coder.py:46: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert points.size(-1) == 2
/usr/local/lib/python3.8/dist-packages/mmyolo/models/task_modules/coders/distance_point_bbox_coder.py:47: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(-1) == 4
/usr/local/lib/python3.8/dist-packages/mmyolo/models/dense_heads/yolov5_head.py:377: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  img_meta) in zip(flatten_decoded_bboxes, flatten_cls_scores,
/usr/local/lib/python3.8/dist-packages/mmyolo/models/dense_heads/yolov5_head.py:399: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if scores.shape[0] == 0:
/usr/local/lib/python3.8/dist-packages/mmdet/models/utils/misc.py:336: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  num_topk = min(topk, valid_idxs.size(0))
/usr/local/lib/python3.8/dist-packages/mmengine/structures/instance_data.py:306: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  return len(self.values()[0])
/usr/local/lib/python3.8/dist-packages/mmengine/structures/instance_data.py:152: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(value) == len(self), 'The length of ' \
/usr/local/lib/python3.8/dist-packages/mmcv/ops/nms.py:276: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if boxes.size(-1) == 5:
/usr/local/lib/python3.8/dist-packages/mmcv/ops/nms.py:293: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  max_coordinate + torch.tensor(1).to(boxes))
/usr/local/lib/python3.8/dist-packages/mmcv/ops/nms.py:302: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if boxes_for_nms.shape[0] < split_thr:
/usr/local/lib/python3.8/dist-packages/mmcv/ops/nms.py:123: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
/usr/local/lib/python3.8/dist-packages/mmcv/ops/nms.py:124: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/onnx/export.py", line 131, in export
    torch.onnx.export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/root/workspace/mmdeploy/mmdeploy/apis/onnx/optimizer.py", line 27, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 437, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 388, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 121, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: InstanceData
11/15 03:32:29 - mmengine - ERROR - /root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

### Reproduction

执行的命令
```
python3 mmdeploy/tools/deploy.py mmdeploy/configs/mmdet/detection/detection_openvino_dynamic-300x300.py mmyolo/configs/rtmdet/rtmdet_tiny_fast_1xb12-40e_rail.py /mydata/rail_inter_coco.pth mmdeploy/tests/data/tiger.jpeg --work-dir deploy_result/rail_inter --device cpu --log-level INFO
```

### Environment

```Shell
11/15 03:33:54 - mmengine - INFO -

11/15 03:33:54 - mmengine - INFO - **********Environmental information**********
11/15 03:33:54 - mmengine - INFO - sys.platform: linux
11/15 03:33:54 - mmengine - INFO - Python: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
11/15 03:33:54 - mmengine - INFO - CUDA available: False
11/15 03:33:54 - mmengine - INFO - numpy_random_seed: 2147483648
11/15 03:33:54 - mmengine - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
11/15 03:33:54 - mmengine - INFO - PyTorch: 1.10.0+cu113
11/15 03:33:54 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

11/15 03:33:54 - mmengine - INFO - TorchVision: 0.11.0+cu113
11/15 03:33:54 - mmengine - INFO - OpenCV: 4.5.4
11/15 03:33:54 - mmengine - INFO - MMEngine: 0.7.4
11/15 03:33:54 - mmengine - INFO - MMCV: 2.0.1
11/15 03:33:54 - mmengine - INFO - MMCV Compiler: GCC 9.3
11/15 03:33:54 - mmengine - INFO - MMCV CUDA Compiler: 11.3
11/15 03:33:54 - mmengine - INFO - MMDeploy: 1.2.0+6cd29e2
11/15 03:33:54 - mmengine - INFO -

11/15 03:33:54 - mmengine - INFO - **********Backend information**********
11/15 03:33:54 - mmengine - INFO - tensorrt:    8.2.3.0
11/15 03:33:54 - mmengine - INFO - tensorrt custom ops: Available
11/15 03:33:54 - mmengine - INFO - ONNXRuntime: None
11/15 03:33:54 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
11/15 03:33:54 - mmengine - INFO - ONNXRuntime custom ops:      Available
11/15 03:33:54 - mmengine - INFO - pplnn:       0.8.1
11/15 03:33:54 - mmengine - INFO - ncnn:        1.0.20230224
11/15 03:33:54 - mmengine - INFO - ncnn custom ops:     Available
11/15 03:33:54 - mmengine - INFO - snpe:        None
11/15 03:33:54 - mmengine - INFO - openvino:    2022.3.0
11/15 03:33:54 - mmengine - INFO - torchscript: 1.10.0+cu113
11/15 03:33:54 - mmengine - INFO - torchscript custom ops:      Available
11/15 03:33:54 - mmengine - INFO - rknn-toolkit:        None
11/15 03:33:54 - mmengine - INFO - rknn-toolkit2:       None
11/15 03:33:54 - mmengine - INFO - ascend:      None
11/15 03:33:54 - mmengine - INFO - coreml:      None
11/15 03:33:54 - mmengine - INFO - tvm: None
11/15 03:33:54 - mmengine - INFO - vacc:        None
11/15 03:33:54 - mmengine - INFO -

11/15 03:33:54 - mmengine - INFO - **********Codebase information**********
11/15 03:33:54 - mmengine - INFO - mmdet:       3.2.0
11/15 03:33:54 - mmengine - INFO - mmseg:       None
11/15 03:33:54 - mmengine - INFO - mmpretrain:  None
11/15 03:33:54 - mmengine - INFO - mmocr:       None
11/15 03:33:54 - mmengine - INFO - mmagic:      None
11/15 03:33:54 - mmengine - INFO - mmdet3d:     None
11/15 03:33:54 - mmengine - INFO - mmpose:      None
11/15 03:33:54 - mmengine - INFO - mmrotate:    None
11/15 03:33:54 - mmengine - INFO - mmaction:    None
11/15 03:33:54 - mmengine - INFO - mmrazor:     None
11/15 03:33:54 - mmengine - INFO - mmyolo:      0.6.0
```

**Comment by BingoZZBZZ** [comment]
你好问题解决了吗

**Comment by vicnoah** [comment]
> 你好问题解决了吗

解决了，记得是需要改编译配置

**Comment by bnddwwj** [comment]
> > 你好问题解决了吗
> 
> 解决了，记得是需要改编译配置

可以分享一下具体修改哪里的配置吗

**Comment by vicnoah** [comment]
> > > 你好问题解决了吗
> > 
> > 
> > 解决了，记得是需要改编译配置
> 
> 可以分享一下具体修改哪里的配置吗

参考这里的方法。https://github.com/open-mmlab/mmdeploy/issues/2372#issue-1864483473

**Comment by bnddwwj** [comment]
> > > > 你好问题解决了吗
> > > 
> > > 
> > > 解决了，记得是需要改编译配置
> > 
> > 
> > 可以分享一下具体修改哪里的配置吗
> 
> 参考这里的方法。[#2372 (comment)](https://github.com/open-mmlab/mmdeploy/issues/2372#issue-1864483473)
谢谢，解决了，如果使用mmyolo进行训练的，那么部署的时候要用mmyolo中congfig里面的deploy.py文件
