### ISSUE TITLE
mmdeploy_python error

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdeploy#255]
when I run the py program, it reports error

```python
import mmdeploy_python
import sys
import cv2
detector = mmdeploy_python.Detector('/project/train/models', 'cuda', 0)
img = cv2.imread('/home/data/599/fire_14837.jpg')
result = detector([img])
print(result)
```

key error

```shell
[2022-03-21 22:31:59.171] [mmdeploy] [warning] [resize.cpp:71] neither 'scale' or 'scale_factor' is provided in input value. 'img_scale' will be used
[ERROR][2022-03-21 22:31:59.172][resize.cu:1202] CUDA error: no kernel image is available for execution on the device
[2022-03-21 22:31:59.172] [mmdeploy] [error] [transform_module.cpp:35] error: unknown (6) @ /project/mmlab_template/mmdeploy/csrc/preprocess/cuda/resize_impl.cpp:88
[2022-03-21 22:31:59.172] [mmdeploy] [error] [module_adapter.h:34] unhandled exception: unknown (6) @ /project/mmlab_template/mmdeploy/csrc/preprocess/cuda/resize_impl.cpp:88
[2022-03-21 22:31:59.172] [mmdeploy] [error] [detector.cpp:145] exception caught: unknown (6) @ /project/mmlab_template/mmdeploy/csrc/experimental/module_adapter.h:35
Traceback (most recent call last):
  File "/project/mmlab_template/common/ji.py", line 6, in <module>
    result = detector([img])
RuntimeError: failed to apply detector, code: 6
```

detail info are following

```shell
[2022-03-21 22:31:57.952] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
[2022-03-21 22:31:58.072] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "stream": "<any>"
  },
  "input": [
    "image"
  ],
  "name": "mmdetection",
  "output": [
    "det"
  ],
  "params": {
    "model": "/project/train/models"
  },
  "type": "Inference"
}
[2022-03-21 22:31:58.072] [mmdeploy] [info] [model.cpp:38] DirectoryModel successfully load sdk model /project/train/models
[2022-03-21 22:31:58.072] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "transforms": [
    {
      "type": "LoadImageFromFile"
    },
    {
      "keep_ratio": true,
      "size": [
        800,
        1333
      ],
      "type": "Resize"
    },
    {
      "mean": [
        123.675,
        116.28,
        103.53
      ],
      "std": [
        58.395,
        57.12,
        57.375
      ],
      "to_rgb": true,
      "type": "Normalize"
    },
    {
      "size_divisor": 32,
      "type": "Pad"
    },
    {
      "keys": [
        "img"
      ],
      "type": "ImageToTensor"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "flip",
        "valid_ratio",
        "pad_shape",
        "filename",
        "img_norm_cfg",
        "flip_direction",
        "scale_factor",
        "ori_shape",
        "img_shape",
        "ori_filename"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
[2022-03-21 22:31:58.072] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "transforms": [
    {
      "type": "LoadImageFromFile"
    },
    {
      "keep_ratio": true,
      "size": [
        800,
        1333
      ],
      "type": "Resize"
    },
    {
      "mean": [
        123.675,
        116.28,
        103.53
      ],
      "std": [
        58.395,
        57.12,
        57.375
      ],
      "to_rgb": true,
      "type": "Normalize"
    },
    {
      "size_divisor": 32,
      "type": "Pad"
    },
    {
      "keys": [
        "img"
      ],
      "type": "ImageToTensor"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "flip",
        "valid_ratio",
        "pad_shape",
        "filename",
        "img_norm_cfg",
        "flip_direction",
        "scale_factor",
        "ori_shape",
        "img_shape",
        "ori_filename"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
[2022-03-21 22:31:58.072] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "module": "Net",
  "name": "retinanet",
  "output": [
    "infer_output"
  ],
  "type": "Task"
}
[2022-03-21 22:31:58.072] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "module": "Net",
  "name": "retinanet",
  "output": [
    "infer_output"
  ],
  "type": "Task"
}
[2022-03-21 22:31:58.072] [mmdeploy] [info] [cuda_device.cpp:84] Default CUDA allocator initialized
[2022-03-21 22:31:58.780] [mmdeploy] [warning] [trt_net.cpp:24] TRTNet: TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.1.0
[2022-03-21 22:31:59.111] [mmdeploy] [warning] [trt_net.cpp:24] TRTNet: TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.1.0
[2022-03-21 22:31:59.153] [mmdeploy] [info] [common.h:15] config: {
  "component": "ResizeBBox",
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output",
    "infer_output"
  ],
  "module": "mmdet",
  "name": "postprocess",
  "output": [
    "post_output"
  ],
  "params": {
    "max_per_img": 100,
    "min_bbox_size": 0,
    "nms": {
      "iou_threshold": 0.5,
      "type": "nms"
    },
    "nms_pre": 1000,
    "score_thr": 0.05
  },
  "type": "Task"
}
[2022-03-21 22:31:59.153] [mmdeploy] [info] [common.h:15] config: {
  "component": "ResizeBBox",
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output",
    "infer_output"
  ],
  "module": "mmdet",
  "name": "postprocess",
  "output": [
    "post_output"
  ],
  "params": {
    "max_per_img": 100,
    "min_bbox_size": 0,
    "nms": {
      "iou_threshold": 0.5,
      "type": "nms"
    },
    "nms_pre": 1000,
    "score_thr": 0.05
  },
  "type": "Task"
}
[2022-03-21 22:31:59.171] [mmdeploy] [warning] [resize.cpp:71] neither 'scale' or 'scale_factor' is provided in input value. 'img_scale' will be used
[ERROR][2022-03-21 22:31:59.172][resize.cu:1202] CUDA error: no kernel image is available for execution on the device
[2022-03-21 22:31:59.172] [mmdeploy] [error] [transform_module.cpp:35] error: unknown (6) @ /project/mmlab_template/mmdeploy/csrc/preprocess/cuda/resize_impl.cpp:88
[2022-03-21 22:31:59.172] [mmdeploy] [error] [module_adapter.h:34] unhandled exception: unknown (6) @ /project/mmlab_template/mmdeploy/csrc/preprocess/cuda/resize_impl.cpp:88
[2022-03-21 22:31:59.172] [mmdeploy] [error] [detector.cpp:145] exception caught: unknown (6) @ /project/mmlab_template/mmdeploy/csrc/experimental/module_adapter.h:35
Traceback (most recent call last):
  File "/project/mmlab_template/common/ji.py", line 6, in <module>
    result = detector([img])
RuntimeError: failed to apply detector, code: 6
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 0 (.call): inf ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 1 (mmdetection.call): inf ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 2 (.call): inf ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 3 (Preprocess.call): inf ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 4 (Preprocess): -nan ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 5 (Preprocess.ret): -nan ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 6 (retinanet.call): -nan ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 7 (retinanet): -nan ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 8 (retinanet.ret): -nan ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 9 (postprocess.call): -nan ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 10 (postprocess): -nan ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 11 (postprocess.ret): -nan ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 12 (.ret): -nan ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 13 (mmdetection.ret): -nan ms
[2022-03-21 22:31:59.183] [mmdeploy] [info] [graph.cpp:20] node 14 (.ret): -nan ms
```

**Comment by lvhan028** [comment]
If you google this error “CUDA error: no kernel image is available for execution on the device”, you will find it is usually caused by the mismatched CUDA compute capability and NVIDIA GPU. 
Can you list the information of executing `nvidia-smi` and the CUDA version you are using?

**Comment by vansin** [comment]
thanks~
