### ISSUE TITLE
[Bug] Failure to Deploy Rotated Detection (rotated_rtmdet) in MMRotate to Jetson Xavier NX

### ISSUE THREAD

**Issue by zyan-repository** [open-mmlab/mmdeploy#2550]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I am encountering issues deploying the rotated_rtmdet model from MMRotate v1.0.0rc1 on the Jetson Xavier NX with JetPack version 4.6. The model was trained on an x86 platform and exported as an ONNX model. I attempted to convert this ONNX model to a TensorRT model using the onnx2tensorrt.py script on the Jetson platform.

I followed the steps for setting up the environment on the Jetson platform and compiled the TensorRT operators. 

How can I get support for NMSRotated? Is this a bug, or is there an error in my steps?

### Reproduction

command: 
```
python tools/onnx2tensorrt.py /home/nxin/zyan/mmdeploy/configs/mmrotate/rotated-detection_tensorrt-fp16_static-1024x1024.py /home/nxin/zyan/output_model.onnx model
```
report error:
```
11/17 10:59:21 - mmengine - INFO - onnx2tensorrt:
        onnx_path: /home/nxin/zyan/output_model.onnx
        deploy_cfg: /home/nxin/zyan/mmdeploy/configs/mmrotate/rotated-detection_tensorrt-fp16_static-1024x1024.py
11/17 10:59:21 - mmengine - INFO - Successfully loaded tensorrt plugins from /home/nxin/zyan/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +353, GPU +0, now: CPU 430, GPU 6051 (MiB)
[TensorRT] WARNING: onnx2trt_utils.cpp:364: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] INFO: No importer registered for op: NMSRotated. Attempting to import as plugin.
[TensorRT] INFO: Searching for plugin: NMSRotated, plugin_version: 1, plugin_namespace:
[TensorRT] ERROR: 3: getPluginCreator could not find plugin: NMSRotated version: 1
Traceback (most recent call last):
  File "tools/onnx2tensorrt.py", line 73, in <module>
    main()
  File "tools/onnx2tensorrt.py", line 67, in main
    device_id=device_id)
  File "/home/nxin/zyan/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 171, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 331 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
```

### Environment

```Shell
11/17 10:58:58 - mmengine - INFO - **********Environmental information**********
11/17 10:59:00 - mmengine - INFO - sys.platform: linux
11/17 10:59:00 - mmengine - INFO - Python: 3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 19:12:04) [GCC 9.4.0]
11/17 10:59:00 - mmengine - INFO - CUDA available: True
11/17 10:59:00 - mmengine - INFO - numpy_random_seed: 2147483648
11/17 10:59:00 - mmengine - INFO - GPU 0: Xavier
11/17 10:59:00 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
11/17 10:59:00 - mmengine - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.300
11/17 10:59:00 - mmengine - INFO - GCC: gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
11/17 10:59:00 - mmengine - INFO - PyTorch: 1.10.0
11/17 10:59:00 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_53,code=sm_53;-gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72
  - CuDNN 8.2.1
    - Built with CuDNN 8.0
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=8.0.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -DMISSING_ARM_VST1 -DMISSING_ARM_VLD1 -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=open, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON,

11/17 10:59:00 - mmengine - INFO - TorchVision: 0.11.1
11/17 10:59:00 - mmengine - INFO - OpenCV: 4.8.1
11/17 10:59:00 - mmengine - INFO - MMEngine: 0.1.0
11/17 10:59:00 - mmengine - INFO - MMCV: 2.0.0rc1
11/17 10:59:00 - mmengine - INFO - MMCV Compiler: GCC 7.5
11/17 10:59:00 - mmengine - INFO - MMCV CUDA Compiler: 10.2
11/17 10:59:00 - mmengine - INFO - MMDeploy: 1.0.0rc1+09f1952
11/17 10:59:00 - mmengine - INFO -

11/17 10:59:00 - mmengine - INFO - **********Backend information**********
11/17 10:59:00 - mmengine - INFO - tensorrt:    8.0.1.6
11/17 10:59:00 - mmengine - INFO - tensorrt custom ops: Available
11/17 10:59:00 - mmengine - INFO - ONNXRuntime: None
11/17 10:59:00 - mmengine - INFO - ONNXRuntime-gpu:     1.10.0
11/17 10:59:00 - mmengine - INFO - ONNXRuntime custom ops:      Available
11/17 10:59:00 - mmengine - INFO - pplnn:       None
11/17 10:59:00 - mmengine - INFO - ncnn:        None
11/17 10:59:00 - mmengine - INFO - snpe:        None
11/17 10:59:00 - mmengine - INFO - openvino:    None
11/17 10:59:00 - mmengine - INFO - torchscript: 1.10.0
11/17 10:59:00 - mmengine - INFO - torchscript custom ops:      NotAvailable
11/17 10:59:00 - mmengine - INFO - rknn-toolkit:        None
11/17 10:59:00 - mmengine - INFO - rknn2-toolkit:       None
11/17 10:59:00 - mmengine - INFO - ascend:      None
11/17 10:59:00 - mmengine - INFO - coreml:      None
11/17 10:59:00 - mmengine - INFO - tvm: None
11/17 10:59:00 - mmengine - INFO -

11/17 10:59:00 - mmengine - INFO - **********Codebase information**********
11/17 10:59:00 - mmengine - INFO - mmdet:       None
11/17 10:59:00 - mmengine - INFO - mmseg:       None
11/17 10:59:00 - mmengine - INFO - mmcls:       None
11/17 10:59:00 - mmengine - INFO - mmocr:       None
11/17 10:59:00 - mmengine - INFO - mmedit:      None
11/17 10:59:00 - mmengine - INFO - mmdet3d:     None
11/17 10:59:00 - mmengine - INFO - mmpose:      None
11/17 10:59:00 - mmengine - INFO - mmrotate:    None
11/17 10:59:00 - mmengine - INFO - mmaction:    None
```

**Comment by Boomerl** [comment]
It is supposed to use `python tools/deploy.py /path/to/deploy_cfg /path/to/model_cfg /path/to/checkpoint ...` to convert rotated_rtmdet to a tensorrt model.

**Comment by zyan-repository** [comment]
> It is supposed to use `python tools/deploy.py /path/to/deploy_cfg /path/to/model_cfg /path/to/checkpoint ...` to convert rotated_rtmdet to a tensorrt model.

I don't understand the difference between these two methods. I have considered this approach, but there are problems with direct conversion in practice: this method requires the installation of mmrotate, which supports Python versions starting from 3.7. This is significantly different from the Python 3.6 that comes with JetPack. This means that I can't use the approach outlined in the mmdeploy Jetson documentation to build the environment, as the Python 3.6 version of TensorRT will become unusable. This poses significant challenges in setting up the environment.

**Comment by zyan-repository** [comment]
I would like to know how mmdeploy supports the conversion of mmrotate models on the Jetson platform. Starting from the deploy script, how should I set up the environment? 
I tried to build it according to the version correspondence in the documentation, but it was not successful. Changing the environment or version might be easy on an x86 architecture, but I want to know how it should be done on the Jetson platform.

**Comment by Boomerl** [comment]
Is it convenient for you to update JetPack? MMDeploy has implemented the NMSRotated op for the TensorRT backend, and you should use the `tools/deploy.py` to convert the model. MMDeploy rewrites some func of mmrotate to support deployment for different backends, so you may need to install mmrotate to convert rotated_rtmdet to a TensorRT  model.

**Comment by zyan-repository** [comment]
> Is it convenient for you to update JetPack? MMDeploy has implemented the NMSRotated op for the TensorRT backend, and you should use the `tools/deploy.py` to convert the model. MMDeploy rewrites some func of mmrotate to support deployment for different backends, so you may need to install mmrotate to convert rotated_rtmdet to a TensorRT model.

Thank you for your response. I have resolved the issue. The solution was as follows: 
Instead of using the ONNX conversion script on the x86 platform, I used the TensorRT conversion script. Then, I took the intermediate ONNX output from the TensorRT conversion script and used it on the Jetson platform with the `tools/onnx2tensorrt.py` script to convert it to TensorRT successfully. This did not require an additional Python version.
