### ISSUE TITLE
[Bug] AttributeError: VACC

### ISSUE THREAD

**Issue by Jasonlaiya** [open-mmlab/mmdeploy#2588]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

我能转换出onnx模型但不能可视化好像，那么这样该如何验证我的onnx模型是否正确呢，或者您能帮我看看为啥无法可视化

### Reproduction

python ./mmdeploy/tools/deploy.py mmdeploy\configs\mmdet\detection\detection_onnxruntime_static.py configs\retinanet\retinanet_r50_fpn_1x_coco.py checkpoints\retinanet_r50_fpn_1x_coco_20200
130-c2398f9e.pth data/coco/val2017/000000000139.jpg --test-img data/coco/val2017/000000000139.jpg --work-dir mmdeploy_model/retinanet --show --dump-info

### Environment

```Shell
023-12-06 19:49:26,848 - mmdeploy - INFO - **********Environmental information**********
2023-12-06 19:49:32,052 - mmdeploy - INFO - sys.platform: win32
2023-12-06 19:49:32,052 - mmdeploy - INFO - Python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
2023-12-06 19:49:32,052 - mmdeploy - INFO - CUDA available: True
2023-12-06 19:49:32,052 - mmdeploy - INFO - GPU 0: NVIDIA GeForce GTX 1080 Ti
2023-12-06 19:49:32,052 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
2023-12-06 19:49:32,053 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.64
2023-12-06 19:49:32,053 - mmdeploy - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.36.32537 版
2023-12-06 19:49:32,053 - mmdeploy - INFO - GCC: n/a
2023-12-06 19:49:32,053 - mmdeploy - INFO - PyTorch: 1.13.1+cu117
2023-12-06 19:49:32,053 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,c
ode=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigo
bj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_
KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, U
SE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

2023-12-06 19:49:32,053 - mmdeploy - INFO - TorchVision: 0.14.1+cu117
2023-12-06 19:49:32,053 - mmdeploy - INFO - OpenCV: 4.8.1
2023-12-06 19:49:32,054 - mmdeploy - INFO - MMCV: 1.7.0
2023-12-06 19:49:32,054 - mmdeploy - INFO - MMCV Compiler: MSVC 192829924
2023-12-06 19:49:32,054 - mmdeploy - INFO - MMCV CUDA Compiler: 11.7
2023-12-06 19:49:32,054 - mmdeploy - INFO - MMDeploy: 0.14.0+
2023-12-06 19:49:32,054 - mmdeploy - INFO -

2023-12-06 19:49:32,054 - mmdeploy - INFO - **********Backend information**********
2023-12-06 19:49:32,108 - mmdeploy - INFO - tensorrt:   None
2023-12-06 19:49:32,148 - mmdeploy - INFO - ONNXRuntime:        1.15.1
2023-12-06 19:49:32,148 - mmdeploy - INFO - ONNXRuntime-gpu:    1.9.0
2023-12-06 19:49:32,148 - mmdeploy - INFO - ONNXRuntime custom ops:     Available
2023-12-06 19:49:32,173 - mmdeploy - INFO - pplnn:      None
2023-12-06 19:49:32,237 - mmdeploy - INFO - ncnn:       None
2023-12-06 19:49:32,307 - mmdeploy - INFO - snpe:       None
2023-12-06 19:49:32,315 - mmdeploy - INFO - openvino:   None
2023-12-06 19:49:32,317 - mmdeploy - INFO - torchscript:        1.13.1+cu117
2023-12-06 19:49:32,318 - mmdeploy - INFO - torchscript custom ops:     NotAvailable
2023-12-06 19:49:32,392 - mmdeploy - INFO - rknn-toolkit:       None
2023-12-06 19:49:32,393 - mmdeploy - INFO - rknn2-toolkit:      None
2023-12-06 19:49:32,424 - mmdeploy - INFO - ascend:     None
2023-12-06 19:49:32,439 - mmdeploy - INFO - coreml:     None
2023-12-06 19:49:32,451 - mmdeploy - INFO - tvm:        None
2023-12-06 19:49:32,452 - mmdeploy - INFO -

2023-12-06 19:49:32,452 - mmdeploy - INFO - **********Codebase information**********
2023-12-06 19:49:32,458 - mmdeploy - INFO - mmdet:      2.28.2
2023-12-06 19:49:32,458 - mmdeploy - INFO - mmseg:      None
2023-12-06 19:49:32,458 - mmdeploy - INFO - mmcls:      None
2023-12-06 19:49:32,459 - mmdeploy - INFO - mmocr:      None
2023-12-06 19:49:32,459 - mmdeploy - INFO - mmedit:     None
2023-12-06 19:49:32,459 - mmdeploy - INFO - mmdet3d:    None
2023-12-06 19:49:32,459 - mmdeploy - INFO - mmpose:     None
2023-12-06 19:49:32,459 - mmdeploy - INFO - mmrotate:   None
2023-12-06 19:49:32,460 - mmdeploy - INFO - mmaction:   None
```

### Error traceback

```Shell
E:\Anaconda3\envs\om\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition
, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
E:\Anaconda3\envs\om\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition
, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
f:\mmdetection-master\mmdetection-master\mmdet\datasets\utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in
your config file.
  warnings.warn(
E:\Anaconda3\envs\om\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition
, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
2023-12-06 19:44:25,475 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
load checkpoint from local path: checkpoints\retinanet_r50_fpn_1x_coco_20200130-c2398f9e.pth
f:\mmdetection-master\mmdetection-master\mmdet\datasets\utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in
your config file.
  warnings.warn(
2023-12-06 19:44:27,383 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
2023-12-06 19:44:27,384 - mmdeploy - INFO - Export PyTorch model to ONNX: mmdeploy_model/retinanet\end2end.onnx.
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\core\optimizers\function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so th
is value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\codebase\mmdet\models\detectors\base.py:24: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of it
erations executed (and might lead to errors or silently give incorrect results).
  img_shape = [int(val) for val in img_shape]
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\codebase\mmdet\models\detectors\base.py:24: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, s
o this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  img_shape = [int(val) for val in img_shape]
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\codebase\mmdet\models\dense_heads\base_dense_head.py:98: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Pyt
hon values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\pytorch\functions\topk.py:28: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors o
ut of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  k = torch.tensor(k, device=input.device, dtype=torch.long)
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\codebase\mmdet\core\bbox\delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python
 values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\codebase\mmdet\core\bbox\delta_xywh_bbox_coder.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python
 values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\codebase\mmdet\core\post_processing\bbox_nms.py:212: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python
values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not is_dynamic_batch(deploy_cfg) and batch_size == 1:
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\codebase\mmdet\core\post_processing\bbox_nms.py:133: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this funct
ion to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  iou_threshold = torch.tensor([iou_threshold], dtype=torch.float32)
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\codebase\mmdet\core\post_processing\bbox_nms.py:134: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this funct
ion to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  score_threshold = torch.tensor([score_threshold], dtype=torch.float32)
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\mmcv\ops\nms.py:38: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treat
ed as a constant in the future. This means that the trace might not generalize to other inputs!
  score_threshold = float(score_threshold)
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\mmcv\ops\nms.py:39: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treat
ed as a constant in the future. This means that the trace might not generalize to other inputs!
  iou_threshold = float(iou_threshold)
E:\Anaconda3\envs\om\lib\site-packages\mmcv\ops\nms.py:171: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as
a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
E:\Anaconda3\envs\om\lib\site-packages\mmcv\ops\nms.py:172: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as
a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
E:\Anaconda3\envs\om\lib\site-packages\torch\onnx\symbolic_opset9.py:5408: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose
, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  warnings.warn(
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\mmcv\ops\nms.py:81: FutureWarning: 'torch.onnx._patch_torch._graph_op' is deprecated in version 1.13 and will be removed in version 1.14. Please note 'g.op()' is to be removed from torch.
Graph. Please open a GitHub issue if you need this functionality..
  max_output_boxes_per_class = g.op(
E:\Anaconda3\envs\om\lib\site-packages\mmdeploy\mmcv\ops\nms.py:95: FutureWarning: 'torch.onnx._patch_torch._graph_op' is deprecated in version 1.13 and will be removed in version 1.14. Please note 'g.op()' is to be removed from torch.
Graph. Please open a GitHub issue if you need this functionality..
  return g.op('NonMaxSuppression', boxes, scores,
2023-12-06 19:44:33,884 - mmdeploy - INFO - Execute onnx optimize passes.
2023-12-06 19:44:33,887 - mmdeploy - WARNING - Can not optimize model, please build torchscipt extension.
More details: https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/experimental/onnx_optimizer.md
2023-12-06 19:44:35,717 - mmdeploy - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
Traceback (most recent call last):
  File "./mmdeploy/tools/deploy.py", line 334, in <module>
    main()
  File "./mmdeploy/tools/deploy.py", line 228, in main
    if backend == Backend.VACC:
  File "E:\Anaconda3\envs\om\lib\enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: VACC
```

**Comment by Jasonlaiya** [comment]
12/07 11:11:04 - mmengine - INFO - **********Environmental information**********
12/07 11:11:07 - mmengine - INFO - sys.platform: win32
12/07 11:11:07 - mmengine - INFO - Python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
12/07 11:11:07 - mmengine - INFO - CUDA available: True
12/07 11:11:07 - mmengine - INFO - numpy_random_seed: 2147483648
12/07 11:11:07 - mmengine - INFO - GPU 0: NVIDIA GeForce GTX 1080 Ti
12/07 11:11:07 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
12/07 11:11:07 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.64
12/07 11:11:07 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.36.32537 版
12/07 11:11:07 - mmengine - INFO - GCC: n/a
12/07 11:11:07 - mmengine - INFO - PyTorch: 2.1.0
12/07 11:11:07 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192930151
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,c
ode=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.8.1  (built against CUDA 12.0)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.8.1, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /bigobj /FS -DUSE_PTHREADPOOL -
DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /utf-8 /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AV
X=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPA
CK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

12/07 11:11:07 - mmengine - INFO - TorchVision: 0.16.0+cu121
12/07 11:11:07 - mmengine - INFO - OpenCV: 4.8.1
12/07 11:11:07 - mmengine - INFO - MMEngine: 0.9.1
12/07 11:11:07 - mmengine - INFO - MMCV: 2.1.0
12/07 11:11:07 - mmengine - INFO - MMCV Compiler: MSVC 192930148
12/07 11:11:07 - mmengine - INFO - MMCV CUDA Compiler: 12.1
12/07 11:11:07 - mmengine - INFO - MMDeploy: 1.0.0+
12/07 11:11:07 - mmengine - INFO -

12/07 11:11:07 - mmengine - INFO - **********Backend information**********
12/07 11:11:07 - mmengine - INFO - tensorrt:    None
12/07 11:11:07 - mmengine - INFO - ONNXRuntime: 1.8.1
12/07 11:11:07 - mmengine - INFO - ONNXRuntime-gpu:     None
12/07 11:11:07 - mmengine - INFO - ONNXRuntime custom ops:      Available
12/07 11:11:07 - mmengine - INFO - pplnn:       None
12/07 11:11:08 - mmengine - INFO - ncnn:        None
12/07 11:11:08 - mmengine - INFO - snpe:        None
12/07 11:11:08 - mmengine - INFO - openvino:    None
12/07 11:11:08 - mmengine - INFO - torchscript: 2.1.0+cu121
12/07 11:11:08 - mmengine - INFO - torchscript custom ops:      NotAvailable
12/07 11:11:08 - mmengine - INFO - rknn-toolkit:        None
12/07 11:11:08 - mmengine - INFO - rknn-toolkit2:       None
12/07 11:11:08 - mmengine - INFO - ascend:      None
12/07 11:11:08 - mmengine - INFO - coreml:      None
12/07 11:11:08 - mmengine - INFO - tvm: None
12/07 11:11:08 - mmengine - INFO - vacc:        None
12/07 11:11:08 - mmengine - INFO -

12/07 11:11:08 - mmengine - INFO - **********Codebase information**********
12/07 11:11:08 - mmengine - INFO - mmdet:       3.1.0
12/07 11:11:08 - mmengine - INFO - mmseg:       None
12/07 11:11:08 - mmengine - INFO - mmcls:       None
12/07 11:11:08 - mmengine - INFO - mmocr:       None
12/07 11:11:08 - mmengine - INFO - mmedit:      None
12/07 11:11:08 - mmengine - INFO - mmdet3d:     None
12/07 11:11:08 - mmengine - INFO - mmpose:      None
12/07 11:11:08 - mmengine - INFO - mmrotate:    None
12/07 11:11:08 - mmengine - INFO - mmaction:    None
12/07 11:11:08 - mmengine - INFO - mmrazor:     None

**Comment by Jasonlaiya** [comment]
以上是我更新后的环境，但依然报错
12/07 11:10:33 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected f
ailure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
12/07 11:10:33 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpect
ed failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "./mmdeploy/tools/deploy.py", line 334, in <module>
    main()
  File "./mmdeploy/tools/deploy.py", line 128, in main
    export2SDK(
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\backend\sdk\export_info.py", line 347, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\backend\sdk\export_info.py", line 262, in get_deploy
    _, customs = get_model_name_customs(
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\backend\sdk\export_info.py", line 61, in get_model_name_customs
    task_processor = build_task_processor(
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\apis\utils\utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\codebase\base\mmcodebase.py", line 45, in build_task_processor
    return cls.task_registry.build(
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\codebase\mmdet\deploy\object_detection.py", line 132, in __init__
    super().__init__(model_cfg, deploy_cfg, device)
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\codebase\base\task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\utils\manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\registry\default_scope.py", line 34, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None

**Comment by yinfan98** [comment]
@Jasonlaiya I replied your new issue.
I think the most direct way is to use docker...

**Comment by Jasonlaiya** [comment]
Your response has been very helpful in solving this problem for me.I change my mmdetection-master 2 to mmdetection-main 3，now it works. However if I want to use master2, I guess it's better use docker.
