### ISSUE TITLE
[Bug] AssertionError: scope_name should be a string, but got None

### ISSUE THREAD

**Issue by Jasonlaiya** [open-mmlab/mmdeploy#2590]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

python ./mmdeploy/tools/deploy.py mmdeploy\configs\mmdet\detection\detection_onnxruntime_static.py configs\fcos\fcos_r50_caffe_fpn_gn-head_mstrain_640-800_2x_coco.py checkpoints\fcos
_r50_caffe_fpn_gn-head_mstrain_640-800_2x_coco-d92ceeea.pth demo\demo.jpg --test-img demo\demo.jpg --work-dir mmdeploy_model/fcos --show --dump-info我运行以上指令时报错，AssertionError: scope_name should be a string, but got None

### Reproduction

python ./mmdeploy/tools/deploy.py mmdeploy\configs\mmdet\detection\detection_onnxruntime_static.py configs\fcos\fcos_r50_caffe_fpn_gn-head_mstrain_640-800_2x_coco.py checkpoints\fcos
_r50_caffe_fpn_gn-head_mstrain_640-800_2x_coco-d92ceeea.pth demo\demo.jpg --test-img demo\demo.jpg --work-dir mmdeploy_model/fcos --show --dump-info

### Environment

```Shell
12/07 11:24:46 - mmengine - INFO - **********Environmental information**********
12/07 11:24:50 - mmengine - INFO - sys.platform: win32
12/07 11:24:50 - mmengine - INFO - Python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
12/07 11:24:50 - mmengine - INFO - CUDA available: True
12/07 11:24:50 - mmengine - INFO - numpy_random_seed: 2147483648
12/07 11:24:50 - mmengine - INFO - GPU 0: NVIDIA GeForce GTX 1080 Ti
12/07 11:24:50 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
12/07 11:24:50 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.64
12/07 11:24:50 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.36.32537 版
12/07 11:24:50 - mmengine - INFO - GCC: n/a
12/07 11:24:50 - mmengine - INFO - PyTorch: 2.1.0
12/07 11:24:50 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192930151
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,c
ode=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.8.1  (built against CUDA 12.0)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.8.1, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /bigobj /FS -DUSE_PTHREADPOOL -
DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /utf-8 /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AV
X=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPA
CK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

12/07 11:24:50 - mmengine - INFO - TorchVision: 0.16.0+cu121
12/07 11:24:50 - mmengine - INFO - OpenCV: 4.8.1
12/07 11:24:50 - mmengine - INFO - MMEngine: 0.9.1
12/07 11:24:50 - mmengine - INFO - MMCV: 2.1.0
12/07 11:24:50 - mmengine - INFO - MMCV Compiler: MSVC 192930148
12/07 11:24:50 - mmengine - INFO - MMCV CUDA Compiler: 12.1
12/07 11:24:50 - mmengine - INFO - MMDeploy: 1.0.0+
12/07 11:24:50 - mmengine - INFO -

12/07 11:24:50 - mmengine - INFO - **********Backend information**********
12/07 11:24:50 - mmengine - INFO - tensorrt:    None
12/07 11:24:50 - mmengine - INFO - ONNXRuntime: 1.8.1
12/07 11:24:50 - mmengine - INFO - ONNXRuntime-gpu:     None
12/07 11:24:50 - mmengine - INFO - ONNXRuntime custom ops:      Available
12/07 11:24:50 - mmengine - INFO - pplnn:       None
12/07 11:24:50 - mmengine - INFO - ncnn:        None
12/07 11:24:50 - mmengine - INFO - snpe:        None
12/07 11:24:50 - mmengine - INFO - openvino:    None
12/07 11:24:50 - mmengine - INFO - torchscript: 2.1.0+cu121
12/07 11:24:50 - mmengine - INFO - torchscript custom ops:      NotAvailable
12/07 11:24:50 - mmengine - INFO - rknn-toolkit:        None
12/07 11:24:50 - mmengine - INFO - rknn-toolkit2:       None
12/07 11:24:50 - mmengine - INFO - ascend:      None
12/07 11:24:50 - mmengine - INFO - coreml:      None
12/07 11:24:50 - mmengine - INFO - tvm: None
12/07 11:24:50 - mmengine - INFO - vacc:        None
12/07 11:24:50 - mmengine - INFO -

12/07 11:24:50 - mmengine - INFO - **********Codebase information**********
12/07 11:24:50 - mmengine - INFO - mmdet:       3.1.0
12/07 11:24:50 - mmengine - INFO - mmseg:       None
12/07 11:24:50 - mmengine - INFO - mmcls:       None
12/07 11:24:50 - mmengine - INFO - mmocr:       None
12/07 11:24:50 - mmengine - INFO - mmedit:      None
12/07 11:24:50 - mmengine - INFO - mmdet3d:     None
12/07 11:24:50 - mmengine - INFO - mmpose:      None
12/07 11:24:50 - mmengine - INFO - mmrotate:    None
12/07 11:24:50 - mmengine - INFO - mmaction:    None
12/07 11:24:50 - mmengine - INFO - mmrazor:     None
```

### Error traceback

```Shell
12/07 11:23:04 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected f
ailure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
12/07 11:23:04 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpect
ed failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "./mmdeploy/tools/deploy.py", line 334, in <module>
    main()
  File "./mmdeploy/tools/deploy.py", line 128, in main
    export2SDK(
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\backend\sdk\export_info.py", line 347, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\backend\sdk\export_info.py", line 262, in get_deploy
    _, customs = get_model_name_customs(
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\backend\sdk\export_info.py", line 61, in get_model_name_customs
    task_processor = build_task_processor(
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\apis\utils\utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\codebase\base\mmcodebase.py", line 45, in build_task_processor
    return cls.task_registry.build(
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\codebase\mmdet\deploy\object_detection.py", line 132, in __init__
    super().__init__(model_cfg, deploy_cfg, device)
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmdeploy\codebase\base\task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\utils\manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\registry\default_scope.py", line 35, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None
```

**Comment by Jasonlaiya** [comment]
thanks bor, it works!
