### ISSUE TITLE
[Bug] 使用onnx-sim对转出的onnx模型retinanet和fcos-r50进行简化模型时报错onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Gather, node name: /Gather_4): [ShapeInferenceError] Inferred shape and existing shape differ in rank: (3) vs (0)

### ISSUE THREAD

**Issue by Jasonlaiya** [open-mmlab/mmdeploy#2599]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

使用onnx-sim对转出的onnx模型retinanet和fcos-r50进行简化模型时报错onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Gather, node name: /Gather_4): [ShapeInferenceError] Inferred shape and existing shape differ in rank: (3) vs (0)

Traceback (most recent call last):
  File "onnx-sim.py", line 4, in <module>
    model_simp, check = simplify(onnx_model)
  File "E:\Anaconda3\envs\deploy\lib\site-packages\onnxsim\onnx_simplifier.py", line 204, in simplify
    tensor_size_threshold,
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Gather, node name: /Gather_4): [ShapeInferenceError] Inferred shape and existing shape differ in rank: (3) vs (0)

### Reproduction

import onnx
from onnxsim import simplify
onnx_model = onnx.load("mmdeploy_model/re/end2end.onnx")  # load onnx model
model_simp, check = simplify(onnx_model)
assert check, "Simplified ONNX model could not be validated"
onnx.save(model_simp, "mmdeploy_model/re/outputre_simplified.onnx")
print('finished exporting onnx')

### Environment

```Shell
12/12 19:54:37 - mmengine - INFO -

12/12 19:54:37 - mmengine - INFO - **********Environmental information**********
12/12 19:54:39 - mmengine - INFO - sys.platform: win32
12/12 19:54:39 - mmengine - INFO - Python: 3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)]
12/12 19:54:39 - mmengine - INFO - CUDA available: False
12/12 19:54:39 - mmengine - INFO - numpy_random_seed: 2147483648
12/12 19:54:39 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.36.32537 版
12/12 19:54:39 - mmengine - INFO - GCC: n/a
12/12 19:54:39 - mmengine - INFO - PyTorch: 1.13.1
12/12 19:54:39 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_100
0000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TO
RCH_VERSION=1.13.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

12/12 19:54:39 - mmengine - INFO - TorchVision: 0.14.1
12/12 19:54:39 - mmengine - INFO - OpenCV: 4.8.1
12/12 19:54:39 - mmengine - INFO - MMEngine: 0.10.1
12/12 19:54:39 - mmengine - INFO - MMCV: 2.1.0
12/12 19:54:39 - mmengine - INFO - MMCV Compiler: MSVC 193632537
12/12 19:54:39 - mmengine - INFO - MMCV CUDA Compiler: not available
12/12 19:54:39 - mmengine - INFO - MMDeploy: 1.3.0+unknown
12/12 19:54:39 - mmengine - INFO -

12/12 19:54:39 - mmengine - INFO - **********Backend information**********
12/12 19:54:39 - mmengine - INFO - tensorrt:    None
12/12 19:54:39 - mmengine - INFO - ONNXRuntime: 1.8.1
12/12 19:54:39 - mmengine - INFO - ONNXRuntime-gpu:     None
12/12 19:54:39 - mmengine - INFO - ONNXRuntime custom ops:      NotAvailable
12/12 19:54:39 - mmengine - INFO - pplnn:       None
12/12 19:54:39 - mmengine - INFO - ncnn:        None
12/12 19:54:40 - mmengine - INFO - snpe:        None
12/12 19:54:40 - mmengine - INFO - openvino:    None
12/12 19:54:40 - mmengine - INFO - torchscript: 1.13.1
12/12 19:54:40 - mmengine - INFO - torchscript custom ops:      NotAvailable
12/12 19:54:40 - mmengine - INFO - rknn-toolkit:        None
12/12 19:54:40 - mmengine - INFO - rknn-toolkit2:       None
12/12 19:54:40 - mmengine - INFO - ascend:      None
12/12 19:54:40 - mmengine - INFO - coreml:      None
12/12 19:54:40 - mmengine - INFO - tvm: None
12/12 19:54:40 - mmengine - INFO - vacc:        None
12/12 19:54:40 - mmengine - INFO -

12/12 19:54:40 - mmengine - INFO - **********Codebase information**********
12/12 19:54:40 - mmengine - INFO - mmdet:       3.2.0
12/12 19:54:40 - mmengine - INFO - mmseg:       None
12/12 19:54:40 - mmengine - INFO - mmpretrain:  None
12/12 19:54:40 - mmengine - INFO - mmocr:       None
12/12 19:54:40 - mmengine - INFO - mmagic:      None
12/12 19:54:40 - mmengine - INFO - mmdet3d:     None
12/12 19:54:40 - mmengine - INFO - mmpose:      None
12/12 19:54:40 - mmengine - INFO - mmrotate:    None
12/12 19:54:40 - mmengine - INFO - mmaction:    None
12/12 19:54:40 - mmengine - INFO - mmrazor:     None
12/12 19:54:40 - mmengine - INFO - mmyolo:      None
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "onnx-sim.py", line 4, in <module>
    model_simp, check = simplify(onnx_model)
  File "E:\Anaconda3\envs\deploy\lib\site-packages\onnxsim\onnx_simplifier.py", line 204, in simplify
    tensor_size_threshold,
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Gather, node name: /Gather_4): [ShapeInferenceError] Inferred shape and existing shape differ in rank: (3) vs (0)
```

**Comment by qyt825** [comment]
你好，请问这个问题解决了吗

**Comment by IronmanVsThanos** [comment]
have U solve this problem

**Comment by Jasonlaiya** [comment]
> have U solve this problem

not yet，but I solved my problem so I give up this one.

**Comment by Jasonlaiya** [comment]
> have U solve this problem
我的思路是这样，在源码导出onnx的时候，不要做constant_fold，然后在使用onnx-sim见模型作为静态模型，但我还没尝试过，如果你也遇到了这样的问题可以试试

**Comment by IronmanVsThanos** [comment]
我在torch.onnx.export中把do_constant_folding = False 但是还是一样的错误。。
