### ISSUE TITLE
install mmdeploy

### ISSUE THREAD

**Issue by Joll123** [open-mmlab/mmdeploy#263]
When I follow the instructions to install mmdeploy, the following problems occur.
git clone git@github.com:NVIDIA/cub.git third_party/cub
Cloning into 'third_party/cub'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by lvhan028** [comment]
> When I follow the instructions to install mmdeploy, the following problems occur. git clone [git@github.com](mailto:git@github.com):NVIDIA/cub.git third_party/cub Cloning into 'third_party/cub'... [git@github.com](mailto:git@github.com): Permission denied (publickey). fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists.

`git clone git@github.com:NVIDIA/cub.git third_party/cub` uses `ssh` protocol. You have to add your ssh key generated by ssh-keygen to your github profile.

You can try `https` protocol instead, like this,
```bash
git clone https://github.com/open-mmlab/mmdeploy.git
cd mmdeploy
git submodule update --init --recursive
```
```

**Comment by Joll123** [comment]
run git submodule update --init --recursive，
Cloning into '/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/third_party/cub'...
fatal: unable to access 'https://github.com/NVIDIA/cub.git/': LibreSSL SSL_connect: Connection reset by peer in connection to github.com:443 
fatal: clone of 'https://github.com/NVIDIA/cub.git' into submodule path '/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/third_party/cub' failed
Failed to clone 'third_party/cub'. Retry scheduled
Cloning into '/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/third_party/pybind11'...
Cloning into '/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/third_party/cub'...
Submodule path 'third_party/cub': checked out 'c3cceac115c072fb63df1836ff46d8c60d9eb304'
Submodule path 'third_party/pybind11': checked out '70a58c577eaf067748c2ec31bfd0b0a614cffba6'
Submodule path 'third_party/cub': checked out 'c3cceac115c072fb63df1836ff46d8c60d9eb304'

**Comment by Joll123** [comment]
when I run torch2onnx, how to solve?
2022-03-23:17:48:42,root ERROR    [utils.py:43] CascadeRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'
Traceback (most recent call last):
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'embed_dim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/detectors/cascade_rcnn.py", line 28, in __init__
    init_cfg=init_cfg)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/detectors/two_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 102, in torch2onnx
    torch_model = task_processor.init_pytorch_model(model_checkpoint)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 94, in init_pytorch_model
    cfg_options)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/apis/inference.py", line 40, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CascadeRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'
2022-03-23 17:48:42,783 - mmdeploy - ERROR - torch2onnx failed.
