### ISSUE TITLE
[Bug] [ONNXRuntimeError] : 1 : FAIL : Node (MatMulBnFusion_Gemm) Op (Gemm) [ShapeInferenceError] First input does not have rank 2

### ISSUE THREAD

**Issue by nfazekas** [open-mmlab/mmdeploy#2676]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

My goal is to export the pointpillars model to ONNX format. After running the deploy script, I get the following error:
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (MatMulBnFusion_Gemm) Op (Gemm) [ShapeInferenceError] First input does not have rank 2

### Reproduction

`conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia`

```
pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.0rc2"
```
```
pip install mmdeploy==1.3.1
pip install mmdeploy-runtime==1.3.1
pip install onnxruntime==1.17.0
```

```
wget https://github.com/microsoft/onnxruntime/releases/download/v1.17.0/onnxruntime-linux-x64-1.17.0.tgz
tar -zxvf onnxruntime-linux-x64-1.17.0.tgz
export ONNXRUNTIME_DIR=$(pwd)/onnxruntime-linux-x64-1.17.0
export LD_LIBRARY_PATH=$ONNXRUNTIME_DIR/lib:$LD_LIBRARY_PATH
```

`git clone -b main https://github.com/open-mmlab/mmdeploy.git`

```
git clone -b 3.x https://github.com/open-mmlab/mmdetection.git
cd mmdetection
mim install -v -e .
cd ..
```
`mim install "mmdet3d>=1.1.0"`

`mim download mmdet3d --config pointpillars_hv_secfpn_8xb6-160e_kitti-3d-3class --dest .`

```
python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime_dynamic.py \
    pointpillars/pointpillars_hv_secfpn_8xb6-160e_kitti-3d-3class.py \
    pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth \
    /home/cuda/Documents/Research/KITTI/data_object_velodyne/testing/velodyne/000000.bin \
    --work-dir mmdeploy_model/pointpillars \
    --device cpu
```

### Environment

```Shell
02/20 15:54:10 - mmengine - INFO - **********Environmental information**********
02/20 15:54:11 - mmengine - INFO - sys.platform: linux
02/20 15:54:11 - mmengine - INFO - Python: 3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
02/20 15:54:11 - mmengine - INFO - CUDA available: True
02/20 15:54:11 - mmengine - INFO - MUSA available: False
02/20 15:54:11 - mmengine - INFO - numpy_random_seed: 2147483648
02/20 15:54:11 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 4060
02/20 15:54:11 - mmengine - INFO - CUDA_HOME: /usr
02/20 15:54:11 - mmengine - INFO - NVCC: Cuda compilation tools, release 10.1, V10.1.24
02/20 15:54:11 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
02/20 15:54:11 - mmengine - INFO - PyTorch: 2.0.1
02/20 15:54:11 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

02/20 15:54:11 - mmengine - INFO - TorchVision: 0.15.2
02/20 15:54:11 - mmengine - INFO - OpenCV: 4.9.0
02/20 15:54:11 - mmengine - INFO - MMEngine: 0.10.3
02/20 15:54:11 - mmengine - INFO - MMCV: 2.0.1
02/20 15:54:11 - mmengine - INFO - MMCV Compiler: GCC 9.3
02/20 15:54:11 - mmengine - INFO - MMCV CUDA Compiler: 11.7
02/20 15:54:11 - mmengine - INFO - MMDeploy: 1.3.1+
02/20 15:54:11 - mmengine - INFO -

02/20 15:54:11 - mmengine - INFO - **********Backend information**********
02/20 15:54:11 - mmengine - INFO - tensorrt:	None
02/20 15:54:11 - mmengine - INFO - ONNXRuntime:	1.17.0
02/20 15:54:11 - mmengine - INFO - ONNXRuntime-gpu:	None
02/20 15:54:11 - mmengine - INFO - ONNXRuntime custom ops:	Available
02/20 15:54:11 - mmengine - INFO - pplnn:	None
02/20 15:54:11 - mmengine - INFO - ncnn:	None
02/20 15:54:11 - mmengine - INFO - snpe:	None
02/20 15:54:11 - mmengine - INFO - openvino:	None
02/20 15:54:11 - mmengine - INFO - torchscript:	2.0.1
02/20 15:54:11 - mmengine - INFO - torchscript custom ops:	NotAvailable
02/20 15:54:11 - mmengine - INFO - rknn-toolkit:	None
02/20 15:54:11 - mmengine - INFO - rknn-toolkit2:	None
02/20 15:54:11 - mmengine - INFO - ascend:	None
02/20 15:54:11 - mmengine - INFO - coreml:	None
02/20 15:54:11 - mmengine - INFO - tvm:	None
02/20 15:54:11 - mmengine - INFO - vacc:	None
02/20 15:54:11 - mmengine - INFO -

02/20 15:54:11 - mmengine - INFO - **********Codebase information**********
02/20 15:54:11 - mmengine - INFO - mmdet:	3.0.0
02/20 15:54:11 - mmengine - INFO - mmseg:	None
02/20 15:54:11 - mmengine - INFO - mmpretrain:	None
02/20 15:54:11 - mmengine - INFO - mmocr:	None
02/20 15:54:11 - mmengine - INFO - mmagic:	None
02/20 15:54:11 - mmengine - INFO - mmdet3d:	1.4.0
02/20 15:54:11 - mmengine - INFO - mmpose:	None
02/20 15:54:11 - mmengine - INFO - mmrotate:	None
02/20 15:54:11 - mmengine - INFO - mmaction:	None
02/20 15:54:11 - mmengine - INFO - mmrazor:	None
02/20 15:54:11 - mmengine - INFO - mmyolo:	None
```

### Error traceback

```Shell
(openmmlab-mmdeploy-2) cuda@cuda:~/Documents/Research/mmdeploy17$ cd pointpillars/
(openmmlab-mmdeploy-2) cuda@cuda:~/Documents/Research/mmdeploy17/pointpillars$ ls
(openmmlab-mmdeploy-2) cuda@cuda:~/Documents/Research/mmdeploy17/pointpillars$ mim download mmdet3d --config pointpillars_hv_secfpn_8xb6-160e_kitti-3d-3class --dest .
processing pointpillars_hv_secfpn_8xb6-160e_kitti-3d-3class...
downloading ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MiB 14.6 MB/s eta 0:00:00
Successfully downloaded hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth to /home/cuda/Documents/Research/mmdeploy17/pointpillars
Successfully dumped pointpillars_hv_secfpn_8xb6-160e_kitti-3d-3class.py to /home/cuda/Documents/Research/mmdeploy17/pointpillars
(openmmlab-mmdeploy-2) cuda@cuda:~/Documents/Research/mmdeploy17/pointpillars$ cd ..
(openmmlab-mmdeploy-2) cuda@cuda:~/Documents/Research/mmdeploy17$ python mmdeploy/tools/deploy.py     mmdeploy/configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime_dynamic.py     pointpillars/pointpillars_hv_secfpn_8xb6-160e_kitti-3d-3class.py     pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth     /home/cuda/Documents/Research/KITTI/data_object_velodyne/testing/velodyne/000000.bin     --work-dir mmdeploy_model/pointpillars     --device cpu
02/20 15:08:16 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
02/20 15:08:19 - mmengine - WARNING - Failed to search registry with scope "mmdet3d" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet3d" is a correct scope, or whether the registry is initialized.
02/20 15:08:19 - mmengine - WARNING - Failed to search registry with scope "mmdet3d" in the "mmdet3d_tasks" registry tree. As a workaround, the current "mmdet3d_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet3d" is a correct scope, or whether the registry is initialized.
/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdet3d/models/dense_heads/anchor3d_head.py:94: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  warnings.warn(
Loads checkpoint by local backend from path: pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth
02/20 15:08:19 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
02/20 15:08:19 - mmengine - INFO - Export PyTorch model to ONNX: mmdeploy_model/pointpillars/end2end.onnx.
/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdeploy/codebase/mmdet3d/models/pillar_encode.py:42: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  f_center = features[..., :3] - (coors[..., 1:] * torch.tensor(
/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdeploy/codebase/mmdet3d/models/pillar_encode.py:43: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  [self.vz, self.vy, self.vx]).to(device) + torch.tensor([
/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdet3d/models/detectors/voxelnet.py:42: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  batch_size = voxel_dict['coors'][-1, 0].item() + 1
/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmcv/cnn/bricks/wrappers.py:87: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if x.numel() == 0 and obsolete_torch_version(TORCH_VERSION, (1, 4)):
02/20 15:08:21 - mmengine - INFO - Execute onnx optimize passes.
02/20 15:08:21 - mmengine - WARNING - Can not optimize model, please build torchscipt extension.
More details: https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/experimental/onnx_optimizer.md
================ Diagnostic Run torch.onnx.export version 2.0.1 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

02/20 15:08:22 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
02/20 15:08:23 - mmengine - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in main process
02/20 15:08:23 - mmengine - INFO - Finish pipeline mmdeploy.apis.utils.utils.to_backend
02/20 15:08:23 - mmengine - INFO - visualize onnxruntime model start.
02/20 15:08:28 - mmengine - WARNING - Failed to search registry with scope "mmdet3d" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet3d" is a correct scope, or whether the registry is initialized.
02/20 15:08:28 - mmengine - WARNING - Failed to search registry with scope "mmdet3d" in the "mmdet3d_tasks" registry tree. As a workaround, the current "mmdet3d_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet3d" is a correct scope, or whether the registry is initialized.
02/20 15:08:28 - mmengine - WARNING - Failed to search registry with scope "mmdet3d" in the "backend_voxel_detectors" registry tree. As a workaround, the current "backend_voxel_detectors" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet3d" is a correct scope, or whether the registry is initialized.
02/20 15:08:28 - mmengine - INFO - Successfully loaded onnxruntime custom ops from /home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdeploy/lib/libmmdeploy_onnxruntime_ops.so
2024-02-20:15:08:29 - root - ERROR - [ONNXRuntimeError] : 1 : FAIL : Node (MatMulBnFusion_Gemm) Op (Gemm) [ShapeInferenceError] First input does not have rank 2
Traceback (most recent call last):
  File "/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdeploy/utils/utils.py", line 41, in target_wrapper
    result = target(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdeploy/apis/visualize.py", line 65, in visualize_model
    model = task_processor.build_backend_model(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdeploy/codebase/mmdet3d/deploy/voxel_detection.py", line 64, in build_backend_model
    model = build_voxel_detection_model(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py", line 409, in build_voxel_detection_model
    backend_detector = __BACKEND_MODEL.build(
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
          ^^^^^^^^^^^^^^^
  File "/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py", line 48, in __init__
    self._init_wrapper(
  File "/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py", line 62, in _init_wrapper
    self.wrapper = BaseBackendModel._build_wrapper(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdeploy/codebase/base/backend_model.py", line 65, in _build_wrapper
    return backend_mgr.build_wrapper(backend_files, device, input_names,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdeploy/backend/onnxruntime/backend_manager.py", line 35, in build_wrapper
    return ORTWrapper(
           ^^^^^^^^^^^
  File "/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/mmdeploy/backend/onnxruntime/wrapper.py", line 63, in __init__
    sess = ort.InferenceSession(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/cuda/anaconda3/envs/openmmlab-mmdeploy-2/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (MatMulBnFusion_Gemm) Op (Gemm) [ShapeInferenceError] First input does not have rank 2
02/20 15:08:29 - mmengine - ERROR - /home/cuda/Documents/Research/mmdeploy17/mmdeploy/tools/deploy.py - create_process - 82 - visualize onnxruntime model failed.
```

**Comment by riccardo-donati** [comment]
Had the same error when trying to load the onnx file. This is probably due to a compatibility issue between the onnx runtime and the onnx operation set version. Pointpillars should use the version 11, check your onnx compatibility (refer to this https://onnxruntime.ai/docs/reference/compatibility.html) and install the correct version of onnx runtime (1.12 should work with onnx 11)

**Comment by nfazekas** [comment]
Thank you, it works now. (For me it worked also with 1.16)
