### ISSUE TITLE
about swin model deployment

### ISSUE THREAD

**Issue by Joll123** [open-mmlab/mmdeploy#268]
I run ./tools/deploy.py expecting to export the .onnx model, I get an error. How to deal with it?

2022-03-23 17:48:30,339 - mmdeploy - INFO - torch2onnx start.
2022-03-23:17:48:42,root ERROR [utils.py:43] CascadeRCNN: SwinTransformer: init() got an unexpected keyword argument 'embed_dim'
Traceback (most recent call last):
File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
return obj_cls(**args)
TypeError: init() got an unexpected keyword argument 'embed_dim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
return obj_cls(**args)
File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/detectors/cascade_rcnn.py", line 28, in init
init_cfg=init_cfg)
File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/detectors/two_stage.py", line 32, in init
self.backbone = build_backbone(backbone)
File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 20, in build_backbone
return BACKBONES.build(cfg)
File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
return self.build_func(*args, **kwargs, registry=self)
File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
return build_from_cfg(cfg, registry, default_args)
File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
raise type(e)(f'{obj_cls.name}: {e}')
TypeError: SwinTransformer: init() got an unexpected keyword argument 'embed_dim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/utils/utils.py", line 38, in target_wrapper
result = target(*args, **kwargs)
File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 102, in torch2onnx
torch_model = task_processor.init_pytorch_model(model_checkpoint)
File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 94, in init_pytorch_model
cfg_options)
File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/apis/inference.py", line 40, in init_detector
model = build_detector(config.model, test_cfg=config.get('test_cfg'))
File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 59, in build_detector
cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
return self.build_func(*args, **kwargs, registry=self)
File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
return build_from_cfg(cfg, registry, default_args)
File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
raise type(e)(f'{obj_cls.name}: {e}')
TypeError: CascadeRCNN: SwinTransformer: init() got an unexpected keyword argument 'embed_dim'
2022-03-23 17:48:42,783 - mmdeploy - ERROR - torch2onnx failed.

**Comment by Joll123** [comment]
I run ./tools/deploy.py expecting to export the .onnx model, I get an error. How to deal with it?


2022-03-23 17:48:30,339 - mmdeploy - INFO - torch2onnx start.
2022-03-23:17:48:42,root ERROR    [utils.py:43] CascadeRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'
Traceback (most recent call last):
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'embed_dim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/detectors/cascade_rcnn.py", line 28, in __init__
    init_cfg=init_cfg)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/detectors/two_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 102, in torch2onnx
    torch_model = task_processor.init_pytorch_model(model_checkpoint)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 94, in init_pytorch_model
    cfg_options)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/apis/inference.py", line 40, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CascadeRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'
2022-03-23 17:48:42,783 - mmdeploy - ERROR - torch2onnx failed.

**Comment by AllentDan** [comment]
Hi, could you please post the script you used? Swin models are not in the support list now. We are going to support them as soon as possible.

**Comment by Joll123** [comment]
@AllentDan  thanks，Is there a planned time？And support yolox?
addict==2.4.0
albumentations==1.1.0
brotlipy==0.7.0
cached-property==1.5.2
certifi==2021.10.8
cffi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/croot-2p6q7e2r/cffi_1642701115063/work
charset-normalizer==2.0.12
click==7.1.2
colorama==0.4.4
cryptography @ file:///opt/concourse/worker/volumes/live/dfab5924-fd99-4f24-7939-7dbf6f1585f3/volume/cryptography_1639414584824/work
cycler==0.11.0
Cython==0.29.27
flatbuffers==2.0
fonttools==4.29.1
h5py==3.6.0
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
imageio==2.16.0
importlib-metadata==4.11.1
instaboostfast==0.1.2
joblib==1.1.0
kiwisolver==1.3.2
lvis==0.5.3
Markdown==3.3.6
matplotlib==3.5.1
mkl-fft==1.3.1
mkl-random @ file:///opt/concourse/worker/volumes/live/133f1d0b-8fd8-4fa0-679e-7214401cbd75/volume/mkl_random_1626186083386/work
mkl-service==2.4.0
mmcv-full==1.4.0
-e git+https://github.com/open-mmlab/mmdeploy.git@f01506c62af1881adedd4b35d692fb61f41db8e4#egg=mmdeploy
mmdet==2.21.0
model-index==0.1.11
networkx==2.6.3
numpy @ file:///opt/concourse/worker/volumes/live/046e897c-3622-47d5-79cf-02f72d341f0d/volume/numpy_and_numpy_base_1634106712173/work
olefile==0.46
onnx==1.11.0
onnxruntime==1.10.0
opencv-python==4.5.5.62
opencv-python-headless==4.5.5.62
ordered-set==4.1.0
packaging==21.3
pandas==1.3.5
panopticapi @ git+https://github.com/cocodataset/panopticapi.git@7bb4655548f98f3fedc07bf37e9040a992b054b0
Pillow==8.4.0
protobuf==3.19.4
pycocotools @ git+https://github.com/cocodataset/cocoapi.git@8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9#subdirectory=PythonAPI
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
pyparsing==3.0.7
PySocks @ file:///opt/concourse/worker/volumes/live/ef943889-94fc-4539-798d-461c60b77804/volume/pysocks_1605305801690/work
python-dateutil==2.8.2
pytz==2021.3
PyWavelets==1.2.0
PyYAML==6.0
qudida==0.0.4
requests @ file:///opt/conda/conda-bld/requests_1641824580448/work
scikit-image==0.19.1
scikit-learn==1.0.2
scipy==1.7.3
six @ file:///tmp/build/80754af9/six_1644875935023/work
tabulate==0.8.9
terminaltables==3.1.10
threadpoolctl==3.1.0
tifffile==2021.11.2
timm==0.5.4
torch==1.11.0
torchaudio==0.11.0
torchvision==0.12.0
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1631814937681/work
urllib3 @ file:///opt/conda/conda-bld/urllib3_1643638302206/work
yapf==0.32.0
zipp==3.7.0

**Comment by AllentDan** [comment]
I mean, maybe you could post the converting script you used that triggerred the error above. Yolox is in the support list.

**Comment by Joll123** [comment]
python ./tools/deploy.py 
./configs/mmdet/detection/detection_onnxruntime_static.py ~/Desktop/Swin-Transformer-Object-Detection/configs/swin/cascade_mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.py ~/Desktop/moby_cascade_mask_rcnn_swin_tiny_patch4_window7_3x.pth ~/Desktop/1.jpg --work-dir ~/Desktop/onnx/
the config file is from GitHub code.

**Comment by AllentDan** [comment]
Thanks. We will inform you as soon as we support it. You can enjoy YOLOX now. 😃

**Comment by Joll123** [comment]
thanks

**Comment by Joll123** [comment]
@AllentDan I tried YOLOX model conversion, but got error.

2022-03-24 14:28:15,969 - mmdeploy - INFO - torch2onnx start.
load checkpoint from local path: /Users/jinhonglong/Desktop/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth
2022-03-24:14:28:31,root ERROR    [utils.py:43] export() got an unexpected keyword argument 'strip_doc_string'
Traceback (most recent call last):
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 111, in torch2onnx
    output_file=output_file)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 53, in torch2onnx_impl
    strip_doc_string=onnx_cfg.get('strip_doc_string', True))
TypeError: export() got an unexpected keyword argument 'strip_doc_string'
2022-03-24 14:28:32,256 - mmdeploy - ERROR - torch2onnx failed.

**Comment by AllentDan** [comment]
Seems `strip_doc_string` get deprecated in the latest pytorch. Maybe you could remove the argument `strip_doc_string` at the line 53 of `mmdeploy/apis/pytorch2onnx.py`. The tested pytorch version of MMDeploy is 1.8. And we are gonna fix the bug ASAP.

**Comment by Joll123** [comment]
@AllentDan thank you, it works. Could NMS be deleted during model conversion?

**Comment by Joll123** [comment]
@AllentDan thank you, it works. Could NMS be deleted during model conversion?

**Comment by Joll123** [comment]
I try to run model conversion by detection_onnxruntime_static.py, got a error that Sizes of tensors must match except in dimension 1.

2022-03-25:09:56:50,root ERROR    [utils.py:43] Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23 for tensor number 1 in the list.
Traceback (most recent call last):
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 111, in torch2onnx
    output_file=output_file)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 52, in torch2onnx_impl
    'keep_initializers_as_inputs'],
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/onnx/__init__.py", line 309, in export
    export_modules_as_functions)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 122, in export
    custom_opsets=custom_opsets, export_modules_as_functions=export_modules_as_functions)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 724, in _export
    dynamic_axes=dynamic_axes)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 499, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 440, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 391, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/jit/_trace.py", line 132, in forward
    self._force_outplace,
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 177, in wrapper
    return self.func(self, *args, **kwargs)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/base.py", line 69, in base_detector__forward
    return __forward_impl(ctx, self, img, img_metas=img_metas, **kwargs)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/core/optimizers/function_marker.py", line 247, in g
    rets = f(*args, **kwargs)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/base.py", line 28, in __forward_impl
    return self.simple_test(img, img_metas, **kwargs)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 177, in wrapper
    return self.func(self, *args, **kwargs)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/single_stage.py", line 27, in single_stage_detector__simple_test
    feat = self.extract_feat(img)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/detectors/single_stage.py", line 45, in extract_feat
    x = self.neck(x)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/necks/yolox_pafpn.py", line 139, in forward
    torch.cat([upsample_feat, feat_low], 1))
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23 for tensor number 1 in the list.
2022-03-25 09:56:50,857 - mmdeploy - ERROR - torch2onnx failed.

**Comment by AllentDan** [comment]
You can either use `configs/mmdet/detection/detection_onnxruntime_dynamic.py` to export the model or specify the shape of input that is divisible by 32  at line 3 of `configs/mmdet/_base_/base_static.py` such as input_shape=[512, 512]

**Comment by Joll123** [comment]
could I delete NMS during model conversion?  and if use other NMS, it is ok?

**Comment by AllentDan** [comment]
Should be ok.

**Comment by Joll123** [comment]
I modify the argument with_nms=False at the lines 18 of the mmdeploy/codebase/mmdet/models/dense_heads/yolox_head.py. Don't using NMS.

2022-03-25 11:08:34,234 - mmdeploy - WARNING - The library of onnxruntime custom ops does             not exist: 
2022-03-25:11:08:37,root ERROR    [utils.py:43] index 4 is out of bounds for axis 2 with size 4
Traceback (most recent call last):
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/apis/visualize.py", line 72, in visualize_model
    result = task_processor.run_inference(model, model_inputs)[0]
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 199, in run_inference
    return model(**model_inputs, return_loss=False, rescale=True)
  File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 193, in forward
    outputs = End2EndModel.__clear_outputs(outputs)
  File "/Users/jinhonglong/Desktop/mmdeploy/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 106, in __clear_outputs
    inds = test_outputs[0][i, :, 4] > 0.0
IndexError: index 4 is out of bounds for axis 2 with size 4
2022-03-25 11:08:37,788 - mmdeploy - ERROR - visualize onnxruntime model failed.

**Comment by AllentDan** [comment]
Seems you exported onnx model successifully. You should implement your own nms then.

**Comment by lvhan028** [comment]
Closing since no activity in this thread for over a month, please reopen if you still have questions, thanks!
