### ISSUE TITLE
[Bug] Deploy rotated_rtmdet to tensorrt did not create dynamic batch engine

### ISSUE THREAD

**Issue by wantacool** [open-mmlab/mmdeploy#2705]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I was able to deploy the Rotated-RTMDet pretrained model to tensorrt backend through deploy.py using a customized config for batch_size > 1. However the created tensorrt engine did not run on batch-size>1 in test.py. It seems like the created engine is not for dynamic batch but batch_size=1 only. I had tested a few variants of model config/checkpoints and received the same errors. 

### Deployment:
`python tools/deploy.py configs/mmrotate/rotated-detection_tensorrt_dynamic-320x320-1024x1024-batch.py $MMROTATE_DIR/configs/rotated_rtmdet/rotated_rtmdet_m-3x-dota.py $MMROTATE_DIR/checkpoints/rotated_rtmdet_m-3x-dota-beeadda6.pth $MMROTATE_DIR/demo/dota_demo.jpg --dump-info --device cuda --work-dir $MMROTATE_DIR/rotated_rtmdet/rotated_rtmdet_m-3x-dota
`
### Config: rotated-detection_tensorrt_dynamic-320x320-1024x1024-batch.py
```
_base_ = ['./rotated-detection_static.py', '../_base_/backends/tensorrt.py']

onnx_config = dict(
    output_names=['dets', 'labels'],
    input_shape=None,
    dynamic_axes={
        'input': {
            0: 'batch',
            2: 'height',
            3: 'width'
        },
        'dets': {
            0: 'batch',
            1: 'num_dets',
        },
        'labels': {
            0: 'batch',
            1: 'num_dets',
        },
    },
)

backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 1024, 1024],
                    opt_shape=[5, 3, 1024, 1024],
                    max_shape=[32, 3, 1024, 1024])))
    ])
```
### Test
`python tools/test.py configs/mmrotate/rotated-detection_tensorrt_dynamic-320x320-1024x1024-batch.py mmrotate_configs/rotated_rtmdet_m-3x-dota_ms.py --model $MMROTATE_DIR/rotated_rtmdet/rotated_rtmdet_m-3x-dota_ms/end2end.engine --device cuda --batch-size 5`

### Environment

```Shell
03/19 20:27:00 - mmengine - INFO - 

03/19 20:27:00 - mmengine - INFO - **********Environmental information**********
03/19 20:27:02 - mmengine - INFO - sys.platform: linux
03/19 20:27:02 - mmengine - INFO - Python: 3.9.16 (main, Mar  8 2023, 14:00:05) [GCC 11.2.0]
03/19 20:27:02 - mmengine - INFO - CUDA available: True
03/19 20:27:02 - mmengine - INFO - MUSA available: False
03/19 20:27:02 - mmengine - INFO - numpy_random_seed: 2147483648
03/19 20:27:02 - mmengine - INFO - GPU 0,1: NVIDIA RTX A6000
03/19 20:27:02 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
03/19 20:27:02 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.8, V11.8.89
03/19 20:27:02 - mmengine - INFO - GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
03/19 20:27:02 - mmengine - INFO - PyTorch: 2.0.1+cu118
03/19 20:27:02 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

03/19 20:27:02 - mmengine - INFO - TorchVision: 0.15.2+cu118
03/19 20:27:02 - mmengine - INFO - OpenCV: 4.8.1
03/19 20:27:02 - mmengine - INFO - MMEngine: 0.10.3
03/19 20:27:02 - mmengine - INFO - MMCV: 2.0.1
03/19 20:27:02 - mmengine - INFO - MMCV Compiler: GCC 9.3
03/19 20:27:02 - mmengine - INFO - MMCV CUDA Compiler: 11.8
03/19 20:27:02 - mmengine - INFO - MMDeploy: 1.3.1+bc75c9d
03/19 20:27:02 - mmengine - INFO - 

03/19 20:27:02 - mmengine - INFO - **********Backend information**********
03/19 20:27:02 - mmengine - INFO - tensorrt:    8.6.1.post1
03/19 20:27:02 - mmengine - INFO - tensorrt custom ops: Available
03/19 20:27:02 - mmengine - INFO - ONNXRuntime: None
03/19 20:27:02 - mmengine - INFO - ONNXRuntime-gpu:     1.16.3
03/19 20:27:02 - mmengine - INFO - ONNXRuntime custom ops:      Available
03/19 20:27:02 - mmengine - INFO - pplnn:       None
03/19 20:27:02 - mmengine - INFO - ncnn:        None
03/19 20:27:02 - mmengine - INFO - snpe:        None
03/19 20:27:02 - mmengine - INFO - openvino:    None
03/19 20:27:02 - mmengine - INFO - torchscript: 2.0.1+cu118
03/19 20:27:02 - mmengine - INFO - torchscript custom ops:      NotAvailable
03/19 20:27:02 - mmengine - INFO - rknn-toolkit:        None
03/19 20:27:02 - mmengine - INFO - rknn-toolkit2:       None
03/19 20:27:02 - mmengine - INFO - ascend:      None
03/19 20:27:02 - mmengine - INFO - coreml:      None
03/19 20:27:02 - mmengine - INFO - tvm: None
03/19 20:27:02 - mmengine - INFO - vacc:        None
03/19 20:27:02 - mmengine - INFO - 

03/19 20:27:02 - mmengine - INFO - **********Codebase information**********
03/19 20:27:02 - mmengine - INFO - mmdet:       3.0.0
03/19 20:27:02 - mmengine - INFO - mmseg:       None
03/19 20:27:02 - mmengine - INFO - mmpretrain:  None
03/19 20:27:02 - mmengine - INFO - mmocr:       None
03/19 20:27:02 - mmengine - INFO - mmagic:      None
03/19 20:27:02 - mmengine - INFO - mmdet3d:     None
03/19 20:27:02 - mmengine - INFO - mmpose:      None
03/19 20:27:02 - mmengine - INFO - mmrotate:    1.0.0rc1
03/19 20:27:02 - mmengine - INFO - mmaction:    None
03/19 20:27:02 - mmengine - INFO - mmrazor:     None
03/19 20:27:02 - mmengine - INFO - mmyolo:      None
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/home/wantacool/Work/mmdeploy/tools/test.py", line 159, in <module>
    main()
  File "/home/wantacool/Work/mmdeploy/tools/test.py", line 153, in main
    runner.test()
  File "/home/wantacool/miniconda3/envs/torch_env/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1823, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/home/wantacool/miniconda3/envs/torch_env/lib/python3.9/site-packages/mmengine/runner/loops.py", line 443, in run
    self.run_iter(idx, data_batch)
  File "/home/wantacool/miniconda3/envs/torch_env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wantacool/miniconda3/envs/torch_env/lib/python3.9/site-packages/mmengine/runner/loops.py", line 462, in run_iter
    outputs = self.runner.model.test_step(data_batch)
  File "/home/wantacool/miniconda3/envs/torch_env/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/home/wantacool/miniconda3/envs/torch_env/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 361, in _run_forward
    results = self(**data, mode=mode)
  File "/home/wantacool/miniconda3/envs/torch_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wantacool/miniconda3/envs/torch_env/lib/python3.9/site-packages/mmdeploy/codebase/mmrotate/deploy/rotated_detection_model.py", line 114, in forward
    outputs = self.predict(inputs)
  File "/home/wantacool/miniconda3/envs/torch_env/lib/python3.9/site-packages/mmdeploy/codebase/mmrotate/deploy/rotated_detection_model.py", line 150, in predict
    outputs = self.wrapper({self.input_name: imgs})
  File "/home/wantacool/miniconda3/envs/torch_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wantacool/miniconda3/envs/torch_env/lib/python3.9/site-packages/mmdeploy/backend/tensorrt/wrapper.py", line 148, in forward
    assert s_min <= s_input <= s_max, \
AssertionError: Input shape should be between (1, 3, 1024, 1024) and (1, 3, 1024, 1024) but get (5, 3, 1024, 1024).
```

**Comment by dou3516** [comment]
same issue

**Comment by Petros626** [comment]
any success?
