### ISSUE TITLE
jetson install mmdelpoy is erro

### ISSUE THREAD

**Issue by 827346462** [open-mmlab/mmdeploy#314]
hi. I use jetson Xavier NX install mmdeploy.
i use MMCV_WITH_OPS=1 pip install -e .

jetpack:4.6
pytorch:1.8

i follow this https://mmdeploy.readthedocs.io/en/latest/tutorials/how_to_install_mmdeploy_on_jetsons.html#install-mmcv.

begin erro :
Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full
    ERROR: Command errored out with exit status 1:
     command: /home/lcfc/archiconda3/envs/mmdeploy/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lcfc/Public/mmcv/setup.py'"'"'; __file__='"'"'/home/lcfc/Public/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/lcfc/Public/mmcv/
    Complete output (53 lines):
    running develop
    running egg_info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    adding license file 'LICENSES.md'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    /home/lcfc/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py:369: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/lcfc/Public/mmcv/setup.py", line 405, in <module>
        zip_safe=False)
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/lcfc/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/lcfc/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 378, in build_extensions
        self._check_abi()
      File "/home/lcfc/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 734, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/home/lcfc/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 282, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/home/lcfc/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 242, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['which', 'aarch64-conda_cos7-linux-gnu-c++']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/lcfc/archiconda3/envs/mmdeploy/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lcfc/Public/mmcv/setup.py'"'"'; __file__='"'"'/home/lcfc/Public/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
(mmdeploy) lcfc@lcfc-desktop:~/Public/mmcv$ pip install -r requirements/optional.txt
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting ninja
  Downloading https://mirrors.aliyun.com/pypi/packages/50/55/d38eb201d17615aff69601882d72156c2054856cd492777cfda28f4e3fee/ninja-1.10.2.3-py2.py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (126 kB)
     |████████████████████████████████| 126 kB 1.8 MB/s
Installing collected packages: ninja
Successfully installed ninja-1.10.2.3
(mmdeploy) lcfc@lcfc-desktop:~/Public/mmcv$ MMCV_WITH_OPS=1 pip install -e .
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Obtaining file:///home/lcfc/Public/mmcv
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in /home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/site-packages (from mmcv-full==1.4.8) (2.4.0)
Requirement already satisfied: numpy in /home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/site-packages (from mmcv-full==1.4.8) (1.19.5)
Requirement already satisfied: packaging in /home/lcfc/.local/lib/python3.6/site-packages (from mmcv-full==1.4.8) (21.3)
Requirement already satisfied: Pillow in /home/lcfc/.local/lib/python3.6/site-packages (from mmcv-full==1.4.8) (8.4.0)
Requirement already satisfied: pyyaml in /home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/site-packages (from mmcv-full==1.4.8) (6.0)
Requirement already satisfied: yapf in /home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/site-packages (from mmcv-full==1.4.8) (0.32.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/lcfc/.local/lib/python3.6/site-packages (from packaging->mmcv-full==1.4.8) (3.0.7)
Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full
    ERROR: Command errored out with exit status 1:
     command: /home/lcfc/archiconda3/envs/mmdeploy/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lcfc/Public/mmcv/setup.py'"'"'; __file__='"'"'/home/lcfc/Public/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/lcfc/Public/mmcv/
    Complete output (51 lines):
    running develop
    running egg_info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    adding license file 'LICENSES.md'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/lcfc/Public/mmcv/setup.py", line 405, in <module>
        zip_safe=False)
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/lcfc/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/lcfc/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 378, in build_extensions
        self._check_abi()
      File "/home/lcfc/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 734, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/home/lcfc/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 282, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/home/lcfc/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 242, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/home/lcfc/archiconda3/envs/mmdeploy/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['which', 'aarch64-conda_cos7-linux-gnu-c++']' returned non-zero exit status 1.

when i install aarch64-conda_cos7-linux-gnu-c++ by  'conda install gfortran_linux-64'

now:
Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full
    ERROR: Command errored out with exit status 1:
     command: /home/lcfc/archiconda3/envs/mmdeploy/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lcfc/Public/mmcv/setup.py'"'"'; __file__='"'"'/home/lcfc/Public/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/lcfc/Public/mmcv/
    Complete output (26 lines):
    running develop
    running egg_info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    adding license file 'LICENSES.md'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._ext' extension
    /home/lcfc/archiconda3/envs/mmdeploy/bin/aarch64-conda-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem /home/lcfc/archiconda3/envs/mmdeploy/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/lcfc/archiconda3/envs/mmdeploy/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/lcfc/archiconda3/envs/mmdeploy/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/lcfc/archiconda3/envs/mmdeploy/include -fPIC -DMMCV_WITH_CUDA -I/home/lcfc/Public/mmcv/mmcv/ops/csrc/common -I/home/lcfc/Public/mmcv/mmcv/ops/csrc/common/cuda -I/home/lcfc/.local/lib/python3.6/site-packages/torch/include -I/home/lcfc/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/lcfc/.local/lib/python3.6/site-packages/torch/include/TH -I/home/lcfc/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/lcfc/archiconda3/envs/mmdeploy/include/python3.6m -c ./mmcv/ops/csrc/pytorch/riroi_align_rotated.cpp -o build/temp.linux-aarch64-3.6/./mmcv/ops/csrc/pytorch/riroi_align_rotated.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1
    Assembler messages:
    Error: unknown architecture `nocona'

    Error: unrecognized option -march=nocona
    cc1plus: warning: command-line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    cc1plus: error: unknown value 'nocona' for '-march'
    cc1plus: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8-r native
    cc1plus: error: unknown value 'haswell' for '-mtune'
    cc1plus: note: valid arguments are: cortex-a34 cortex-a35 cortex-a53 cortex-a57 cortex-a72 cortex-a73 thunderx thunderxt88p1 thunderxt88 octeontx octeontx81 octeontx83 thunderxt81 thunderxt83 emag xgene1 falkor qdf24xx exynos-m1 phecda thunderx2t99p1 vulcan thunderx2t99 cortex-a55 cortex-a75 cortex-a76 cortex-a76ae cortex-a77 cortex-a78 cortex-a78ae cortex-a78c cortex-a65 cortex-a65ae cortex-x1 ares neoverse-n1 neoverse-e1 octeontx2 octeontx2t98 octeontx2t96 octeontx2t93 octeontx2f95 octeontx2f95n octeontx2f95mm a64fx tsv110 thunderx3t110 zeus neoverse-v1 saphira neoverse-n2 cortex-a57.cortex-a53 cortex-a72.cortex-a53 cortex-a73.cortex-a35 cortex-a73.cortex-a53 cortex-a75.cortex-a55 cortex-a76.cortex-a55 cortex-r82 generic
    /home/lcfc/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py:369: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    error: command '/home/lcfc/archiconda3/envs/mmdeploy/bin/aarch64-conda-linux-gnu-cc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/lcfc/archiconda3/envs/mmdeploy/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lcfc/Public/mmcv/setup.py'"'"'; __file__='"'"'/home/lcfc/Public/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
 
but i look env have "aarch64-conda-linux-gnu-cc "

please sloved this .thanks

**Comment by AllentDan** [comment]
Hi, @827346462. Did you follow the steps of the document before building mmcv from source?

**Comment by tehkillerbee** [comment]
@827346462 It looks like you have missing dependencies, including ninja. 

I normally install at least the following:
```
sudo apt-get install protobuf-compiler libprotoc-dev libssl-dev curl ninja-build -y
sudo apt-get install libopenblas-dev python3-venv python3-dev python3-setuptools -y
sudo python3 get-pip.py
pip3 install testresources
pip3 install --upgrade setuptools wheel
sudo apt-get purge cmake
sudo snap install cmake --classic
```

**Comment by 827346462** [comment]
>


> 嗨，@827346462。在从源代码构建 mmcv 之前，是否遵循了文档的步骤？

是的，我按照文档进行构建。前面都没出现问题。

**Comment by AllentDan** [comment]
Hi, @827346462, Sorry that we haven't had this error either. But like the comment above, dependencies are highly likely missed. Wish you found the solution.

**Comment by lvhan028** [comment]
Closing since no activity in this thread for more than 3 weeks, please reopen if you still have questions, thanks!
