### ISSUE TITLE
 API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setBindingDimensions::926, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdeploy#317]
when I run follow shell
```shell
export DNAME=10185
export img_paht=/home/data/918/ZDScrowddensity20220402_V1_train_60927.jpg
export algorthm_path=yolox/yolox_s_8x8_300e_coco

export TENSORRT_DIR=/project/TensorRT-8.2.3.0
export LD_LIBRARY_PATH=$TENSORRT_DIR/lib:$TENSORRT_DIR
export CUDNN_DIR=/project/cuda
export LD_LIBRARY_PATH=${CUDNN_DIR}/lib64:${LD_LIBRARY_PATH}

python /project/mmlab_template/mmdeploy/tools/test.py \
/project/mmlab_template/mmdeploy/configs/mmdet/detection/detection_tensorrt-fp16_dynamic-320x320-1344x1344.py \
/project/mmlab_template/configs/${DNAME}/${algorthm_path}.py \
--model /project/train/models/${DNAME}/${algorthm_path}/end2end.engine \
--out /project/train/models/${DNAME}/${algorthm_path}/out.pkl \
--speed-test \
--device cuda
```

```shell
(cvmart) ➜  yolox_s_8x8_300e_coco bash /project/mmlab_template/cvmart/10185/test.sh
[2022-04-07 19:29:27.437] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2022-04-07 19:29:29,223 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /project/mmlab_template/mmdeploy/build/lib/libmmdeploy_tensorrt_ops.so
2022-04-07 19:29:29,223 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /project/mmlab_template/mmdeploy/build/lib/libmmdeploy_tensorrt_ops.so
[04/07/2022-19:29:29] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.1.0
[04/07/2022-19:29:30] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.1.0
[04/07/2022-19:29:30] [TRT] [E] 1: [graphContext.h::MyelinGraphContext::24] Error Code 1: Myelin (Compiled against cuDNN 11.2.1.0 but running against cuDNN 11.1.0.0.)
[                                                  ] 0/100, elapsed: 0s, ETA:[04/07/2022-19:29:32] [TRT] [E] 3: [executionContext.cpp::setBindingDimensions::926] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setBindingDimensions::926, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
[04/07/2022-19:29:32] [TRT] [E] 3: [executionContext.cpp::getBindingDimensions::978] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::getBindingDimensions::978, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
Traceback (most recent call last):
  File "/project/mmlab_template/mmdeploy/tools/test.py", line 137, in <module>
    main()
  File "/project/mmlab_template/mmdeploy/tools/test.py", line 126, in main
    outputs = task_processor.single_gpu_test(model, data_loader,
  File "/project/mmlab_template/mmdeploy/mmdeploy/codebase/base/task.py", line 137, in single_gpu_test
    return self.codebase_class.single_gpu_test(model, data_loader, show,
  File "/project/mmlab_template/mmdeploy/mmdeploy/codebase/mmdet/deploy/mmdetection.py", line 142, in single_gpu_test
    outputs = single_gpu_test(model, data_loader, show, out_dir, **kwargs)
  File "/project/mmlab_template/mmdetection/mmdet/apis/test.py", line 29, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/mmcv/parallel/data_parallel.py", line 50, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/project/mmlab_template/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 193, in forward
    outputs = self.forward_test(input_img, img_metas, *args, **kwargs)
  File "/project/mmlab_template/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 268, in forward_test
    outputs = self.wrapper({self.input_name: imgs})
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/project/mmlab_template/mmdeploy/mmdeploy/backend/tensorrt/wrapper.py", line 118, in forward
    shape = tuple(self.context.get_binding_shape(idx))
ValueError: __len__() should return >= 0
```

**Comment by grimoire** [comment]
Could you add some log in `mmdeploy/backend/tensorrt/wrapper.py` before `self.context.set_binding_shape(idx, tuple(input_tensor.shape))` and `shape = tuple(self.context.get_binding_shape(idx))` about the `input_name` `idx` and `output_name`?
By the way, I think this
```bash
export LD_LIBRARY_PATH=$TENSORRT_DIR/lib:$TENSORRT_DIR
```
is not what you expected, right?

**Comment by lvhan028** [comment]
Closing it due to no activity over a month. Free free to reopen it if it still exists

**Comment by santiweide** [comment]
Hi I have met the same problem using tensor rt 8.4.0.6, is there any clues?

**Comment by baoxin1100** [comment]
遇到同样的问题，请问怎么解决？

**Comment by grimoire** [comment]
The input shape of yolox is 640x640, please edit the config to meet the shape.
