### ISSUE TITLE
mmocr support: how can I convert mmocr models to onnx model?

### ISSUE THREAD

**Issue by SpaceView** [open-mmlab/mmdeploy#370]
I'm trying to deploy and test mmocr models in windows 10, with onnxruntime. following the below link 
https://mmdeploy.readthedocs.io/en/latest/tutorials/how_to_convert_model.html
by default I suppose this is not difficult for  someone familiar with mmocr, but difficult for me since I'm new to mmocr.
It says convert model to onnx
```
python ./tools/deploy.py 
    ${DEPLOY_CFG_PATH} 
    ${MODEL_CFG_PATH} 
    ${MODEL_CHECKPOINT_PATH} 
    ${INPUT_IMG} 
    --test-img ${TEST_IMG} 
    --work-dir ${WORK_DIR}
    --calib-dataset-cfg ${CALIB_DATA_CFG} 
    --device ${DEVICE} 
    --log-level INFO 
    --show 
    --dump-info
```
it seems DEPLOY_CFG_PATH  means 
open-mmlab/mmdetection/configs/mmdet/detection/detection_onnxruntime_dynamic.py
or 
open-mmlab/mmdeploy\configs\mmocr\text-detection\text-detection_onnxruntime_dynamic.py

and  (MODEL_CFG_PATH) for mmocr means
open-mmlab/mmocr\configs\textdet\dbnet\dbnet_r18_fpnc_1200e_icdar2015.py

am I right on this configuration?
the problem, I cannot got the onnx anyway, there are always some errors keep showing up, e.g.
```
(open-mmlab) E:\vOpenMM\mmdeploy>python  tools/deploy.py  configs/mmdet/detection/detection_onnxruntime_dynamic.py     E:/vOpenMM/mmocr/configs/textdet/panet/panet_r18_fpem_ffm_600e_icdar2015.py   panet_r18_fpem_ffm_sbn_600e_icdar2015_20210219-42dbe46a.pth   r1920x1080.png    --show  --device cuda:0   --dump-info  --work-dir .
D:\anaconda3\envs\open-mmlab\lib\site-packages\mmdet\datasets\utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
Traceback (most recent call last):
  File "tools/deploy.py", line 306, in <module>
    main()
  File "tools/deploy.py", line 102, in main
    dump_info(deploy_cfg, model_cfg, args.work_dir, pth=checkpoint_path)
  File "D:\anaconda3\envs\open-mmlab\lib\site-packages\mmdeploy-0.4.0-py3.8.egg\mmdeploy\utils\export_info.py", line 364, in dump_info
    pipeline_info = get_pipeline(deploy_cfg, model_cfg, work_dir=work_dir)
  File "D:\anaconda3\envs\open-mmlab\lib\site-packages\mmdeploy-0.4.0-py3.8.egg\mmdeploy\utils\export_info.py", line 305, in get_pipeline
    postprocess = get_postprocess(deploy_cfg, model_cfg)
  File "D:\anaconda3\envs\open-mmlab\lib\site-packages\mmdeploy-0.4.0-py3.8.egg\mmdeploy\utils\export_info.py", line 249, in get_postprocess
    params = task_processor.get_postprocess()
  File "D:\anaconda3\envs\open-mmlab\lib\site-packages\mmdeploy-0.4.0-py3.8.egg\mmdeploy\codebase\mmdet\deploy\object_detection.py", line 297, in get_postprocess
    if 'rpn' in postprocess:
TypeError: argument of type 'NoneType' is not iterable
```
another way, 
```
(open-mmlab) E:\vOpenMM\mmdeploy>python  tools/deploy.py  configs/mmdet/detection/detection_onnxruntime_dynamic.py     E:/vOpenMM/mmocr/configs/textdet/panet/panet_r18_fpem_ffm_600e_icdar2015.py   panet_r18_fpem_ffm_sbn_600e_icdar2015_20210219-42dbe46a.pth   r1920x1080.png  --work-dir .
2022-04-16 01:04:22,963 - mmdeploy - INFO - torch2onnx start.
2022-04-16:01:04:30,root ERROR    [utils.py:43] 'PANet is not in the models registry'
Traceback (most recent call last):
  File "D:\anaconda3\envs\open-mmlab\lib\site-packages\mmdeploy-0.4.0-py3.8.egg\mmdeploy\utils\utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "D:\anaconda3\envs\open-mmlab\lib\site-packages\mmdeploy-0.4.0-py3.8.egg\mmdeploy\apis\pytorch2onnx.py", line 104, in torch2onnx
    torch_model = task_processor.init_pytorch_model(model_checkpoint)
  File "D:\anaconda3\envs\open-mmlab\lib\site-packages\mmdeploy-0.4.0-py3.8.egg\mmdeploy\codebase\mmdet\deploy\object_detection.py", line 93, in init_pytorch_model
    model = init_detector(self.model_cfg, model_checkpoint, self.device,
  File "D:\anaconda3\envs\open-mmlab\lib\site-packages\mmdet\apis\inference.py", line 43, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "D:\anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "D:\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "D:\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\utils\registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'PANet is not in the models registry'
2022-04-16 01:04:31,086 - mmdeploy - ERROR - torch2onnx failed.
```
when I try `print(mmocr.models) ` I can only get the following error:
AttributeError: module 'mmocr' has no attribute 'models'

Can anyone give some detailed instruction on mmocr deploying?

**Comment by grimoire** [comment]
@AllentDan

**Comment by AllentDan** [comment]
PANet is not on the [support list](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/supported_models.md) by now and will be supported in the short future.

**Comment by SpaceView** [comment]
> PANet is not on the [support list](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/supported_models.md) by now and will be supported in the short future.

This is a pity since most of the mmocr models are not supported yet.

**Comment by AllentDan** [comment]
> > PANet is not on the [support list](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/supported_models.md) by now and will be supported in the short future.
> 
> This is a pity since most of the mmocr models are not supported yet.

If you are in an emergency, there are deployment codes for PANet in the MMOCR codebase. And we are gonna support it soon in MMDeploy.

**Comment by lvhan028** [comment]
Close it for no activity for a long time.
