### ISSUE TITLE
I want to convert the pytorch model to TensorRT on windows10, but I encountered a problem, and now I want to ask if you have any solutions

### ISSUE THREAD

**Issue by 1wang11lijian1** [open-mmlab/mmdeploy#373]
PS C:\Users\12481\MMDeploy> python C:/users/12481/mmdeploy/tools/deploy.py `
>>     C:/users/12481/mmdeploy/configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py `
>>     C:/users/12481/mmdetection/configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py `
>>     C:/Users/12481/Desktop/win/WIN/checkpoints/epoch_12.pth `
>>     C:/Users/12481/Desktop/win/WIN/under_pre_image `
>>     --work-dir C:/Users/12481/Desktop/win/WIN/work_dir `
>>     --device cuda:0 `
>>     --dump-info
Traceback (most recent call last):
  File "C:/users/12481/mmdeploy/tools/deploy.py", line 11, in <module>
    from mmdeploy.apis import (create_calib_table, extract_model,
  File "c:\users\12481\mmdeploy\mmdeploy\apis\__init__.py", line 6, in <module>
    from .pytorch2torchscript import torch2torchscript, torch2torchscript_impl
  File "c:\users\12481\mmdeploy\mmdeploy\apis\pytorch2torchscript.py", line 9, in <module>
    from mmdeploy.backend.torchscript import get_ops_path
  File "c:\users\12481\mmdeploy\mmdeploy\backend\__init__.py", line 7, in <module>
    from mmdeploy.backend.tensorrt import is_available as trt_available
  File "c:\users\12481\mmdeploy\mmdeploy\backend\tensorrt\__init__.py", line 33, in <module>
    from .utils import create_trt_engine, load_trt_engine, save_trt_engine
  File "c:\users\12481\mmdeploy\mmdeploy\backend\tensorrt\utils.py", line 6, in <module>
    import tensorrt as trt
  File "C:\ProgramData\Anaconda3\envs\mmdeploy\lib\site-packages\tensorrt\__init__.py", line 127, in <module>
    ctypes.CDLL(find_lib(lib))
  File "C:\ProgramData\Anaconda3\envs\mmdeploy\lib\site-packages\tensorrt\__init__.py", line 93, in find_lib
    "Could not find: {:}. Is it on your PATH?\nNote: Paths searched were:\n{:}".format(name, paths)
_**FileNotFoundError: Could not find: nvinfer.dll. Is it on your PATH?**_
Note: Paths searched were:
['C:\\ProgramData\\Anaconda3\\envs\\mmdeploy\\lib\\site-packages\\cv2\\../../x64/vc14/bin', 'C:\\ProgramData\\Anaconda3\\envs\\mmdeploy', 'C:\\ProgramData\\Anaconda3\\envs\\mmdeploy\\Library\\mingw-w64\\bin', 'C:\\ProgramData\\Anaconda
3\\envs\\mmdeploy\\Library\\usr\\bin', 'C:\\ProgramData\\Anaconda3\\envs\\mmdeploy\\Library\\bin', 'C:\\ProgramData\\Anaconda3\\envs\\mmdeploy\\Scripts', 'C:\\ProgramData\\Anaconda3\\envs\\mmdeploy\\bin', 'C:\\ProgramData\\Anaconda3\\c
ondabin', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\bin', 'C:\\Program Files\\NVIDI
A GPU Computing Toolkit\\CUDA\\v10.2\\libnvvp', 'C:\\ProgramData\\Anaconda3', 'C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin', 'C:\\ProgramData\\Anaconda3\\Library\\usr\\bin', 'C:\\ProgramData\\Anaconda3\\Library\\bin', 'C:\\Prog
ramData\\Anaconda3\\Scripts', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0', 'C:\\WINDOWS\\System32\\OpenSSH', 'C:\\Program Files\\dotnet', 'C:\\Program Files\\N
VIDIA Corporation\\Nsight Compute 2019.5.0', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\lib\\x64
', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\include', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\extras\\CUPTI\\lib64', 'C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v10.2\\bin\\win64', '
C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v10.2\\common\\lib\\x64', 'C:\\Program Files\\CMake\\bin', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0', 'C:\
\Windows\\System32\\OpenSSH', 'C:\\Users\\12481\\AppData\\Local\\Microsoft\\WindowsApps', '.', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.3.3\\bin', '.', 'C:\\Users\\12481\\.dotnet\\tools']
PS C:\Users\12481\MMDeploy>

**Comment by lvhan028** [comment]
It looks like tensorrt's lib path hasn't been added to the environment variable `path`.
Please read the build doc for windows platform from [here](https://mmdeploy.readthedocs.io/en/latest/build/windows.html#install-inference-engines-for-mmdeploy). And set the correct path of `TensorRT` and `cuDNN` to `path`.

**Comment by 1wang11lijian1** [comment]
Thanks, I have solved it! Now I have a very important question, how can I call TensorRT's inference engine SDK through C++ or C#?

> It looks like tensorrt's lib path hasn't been added to the environment variable `path`. Please read the build doc for windows platform from [here](https://mmdeploy.readthedocs.io/en/latest/build/windows.html#install-inference-engines-for-mmdeploy). And set the correct path of `TensorRT` and `cuDNN` to `path`.

Thanks, I have solved it! Now I have a very important question, how can I call TensorRT's inference engine SDK through C++ or C#?

**Comment by 1wang11lijian1** [comment]
> It looks like tensorrt's lib path hasn't been added to the environment variable `path`. Please read the build doc for windows platform from [here](https://mmdeploy.readthedocs.io/en/latest/build/windows.html#install-inference-engines-for-mmdeploy). And set the correct path of `TensorRT` and `cuDNN` to `path`.

Thanks, I have solved it! Now I have a very important question, how can I call TensorRT's inference engine SDK through C++ or C#?

**Comment by lvhan028** [comment]
1. make sure to add `--dump-info` when converting the model. Let's suppose the parameters to `--work-dir` is `/tmp/test`
2. When you use SDK, actually you don't need to care about the way to TensorRT's inference engine. SDK does this work for you.

**Comment by lvhan028** [comment]
Closing it for no activity for a long time, feel free to reopen it if it is still an issue for you.
