### ISSUE TITLE
Enabling DLA cores on Jetson NX, AGX

### ISSUE THREAD

**Issue by tehkillerbee** [open-mmlab/mmdeploy#385]
Hey guys,

I have been experimenting with enabling DLA cores on Jetson NX, AGX platforms. 

I tried adding the following to `MMDeploy/mmdeploy/backend/tensorrt/utils.py` in a naive attempt to enable DLA cores for all supported layers.

```python
...
    if int8_mode:
        config.set_flag(trt.BuilderFlag.INT8)
        assert int8_param is not None
        config.int8_calibrator = HDF5Calibrator(
            int8_param['calib_file'],
            input_shapes,
            model_type=int8_param['model_type'],
            device_id=device_id,
            algorithm=int8_param.get(
                'algorithm', trt.CalibrationAlgoType.ENTROPY_CALIBRATION_2))
        if version.parse(trt.__version__) < version.parse('8'):
            builder.int8_mode = int8_mode
            builder.int8_calibrator = config.int8_calibrator

    config.default_device_type = trt.DeviceType.DLA
    config.DLA_core = 0
    config.set_flag(trt.BuilderFlag.GPU_FALLBACK)
    config.set_flag(trt.BuilderFlag.STRICT_TYPES)
    print('Using DLA core %d.' % config.DLA_core)

    # create engine
    with torch.cuda.device(device):
        engine = builder.build_engine(network, config)
...
```
Following deploy config has been used:
```
_base_ = ['../MMDeploy/configs/mmdet/instance-seg/instance-seg_tensorrt-fp16_static-800x1344.py']

onnx_config = dict(input_shape=(768, 768))
backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 768, 768],
                    opt_shape=[1, 3, 768, 768],
                    max_shape=[1, 3, 768, 768])))
    ])


# overwriting parameters you want to change
codebase_config = dict(
    post_processing=dict(
        max_output_boxes_per_class=1000,
        #keep_top_k=100
    ))

```

* With fp16, the conversion fails with the following error. There are also quite a few minor(?) errors `Internal DLA error for layer xx`
```
...
[TensorRT] WARNING: Default DLA is enabled but layer Reshape_1026 is not supported on DLA, falling back to GPU.
[TensorRT] INFO: [MemUsageSnapshot] Builder begin: CPU 778 MiB, GPU 14363 MiB
[TensorRT] WARNING: DLA allows only same dimensions inputs to Elementwise.
[TensorRT] WARNING: Internal DLA error for layer Mul_246. Switching to GPU fallback.
[TensorRT] WARNING: Input tensor has less than 4 dimensions for Mul_246. At least one shuffle layer will be inserted which cannot run on DLA.
[TensorRT] WARNING: DLA allows only same dimensions inputs to Elementwise.
[TensorRT] WARNING: Internal DLA error for layer Mul_246. Switching to GPU fallback.
[TensorRT] WARNING: Input tensor has less than 4 dimensions for Mul_261. At least one shuffle layer will be inserted which cannot run on DLA.
[TensorRT] WARNING: DLA allows only same dimensions inputs to Elementwise.
[TensorRT] WARNING: Internal DLA error for layer Mul_261. Switching to GPU fallback.
[TensorRT] WARNING: Input tensor has less than 4 dimensions for Mul_276. At least one shuffle layer will be inserted which cannot run on DLA.
...
[TensorRT] ERROR: 2: [graphOptimizer.cpp::isSqueezeNode::1760] Error Code 2: Internal Error (Assertion params.reshapeDimensions.nbDims == -1 || params.reshapeDimensions.nbDims == outputExtent.nbDims failed.)
2022-04-20:10:05:37,root ERROR    [utils.py:43] Failed to create TensorRT engine
Traceback (most recent call last):
  File "/home/nvidia/git/sscale_deployment/logends/MMDeploy/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "/home/nvidia/git/sscale_deployment/logends/MMDeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 83, in onnx2tensorrt
    device_id=device_id)
  File "/home/nvidia/git/sscale_deployment/logends/MMDeploy/mmdeploy/backend/tensorrt/utils.py", line 122, in create_trt_engine
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine
2022-04-20 10:05:38,416 - mmdeploy - ERROR - onnx2tensorrt of ../mmdeploy_workdir/end2end.onnx failed.
```

* With INT8, the results appear somewhat better but still an error occurs.
```
[TensorRT] INFO: ---------- Layers Running on DLA ----------
[TensorRT] INFO: [DlaLayer] {ForeignNode[Conv_0...Conv_177]}
[TensorRT] INFO: [DlaLayer] {ForeignNode[Add_132...Sigmoid_601]}
[TensorRT] INFO: [DlaLayer] {ForeignNode[Add_142...Mul_618]}
[TensorRT] INFO: [DlaLayer] {ForeignNode[Add_559...Add_693]}
[TensorRT] INFO: [DlaLayer] {ForeignNode[Mul_202...Add_381]}
[TensorRT] INFO: [DlaLayer] {ForeignNode[Add_247...Add_277]}
[TensorRT] INFO: [DlaLayer] {ForeignNode[Add_740...Sub_743]}
[TensorRT] INFO: [DlaLayer] {ForeignNode[Mul_744...Mul_747]}
[TensorRT] INFO: ---------- Layers Running on GPU ----------
[TensorRT] INFO: [GpuLayer] 1605[Constant]
[TensorRT] INFO: [GpuLayer] 1175[Constant]
[TensorRT] INFO: [GpuLayer] 1054[Constant]
[TensorRT] INFO: [GpuLayer] 933[Constant]
[TensorRT] INFO: [GpuLayer] 812[Constant]
[TensorRT] INFO: [GpuLayer] 691[Constant]
...
[TensorRT] INFO: [GpuLayer] Reshape_1013 + Reshape_1015 + Unsqueeze_1016 + Reshape_1026
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 8536, GPU 18294 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 8537, GPU 18304 (MiB)
[TensorRT] WARNING: Detected invalid timing cache, setup a local cache instead
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 8536, GPU 18294 (MiB)
[TensorRT] ERROR: 2: [optimizer.cpp::getFormatRequirements::3600] Error Code 2: Internal Error (Assertion !n->candidateRequirements.empty() failed.no supported formats)
2022-04-20:08:42:22,root ERROR    [utils.py:43] Failed to create TensorRT engine
Traceback (most recent call last):
  File "/home/nvidia/git/sscale_deployment/logends/MMDeploy/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "/home/nvidia/git/sscale_deployment/logends/MMDeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 83, in onnx2tensorrt
    device_id=device_id)
  File "/home/nvidia/git/sscale_deployment/logends/MMDeploy/mmdeploy/backend/tensorrt/utils.py", line 122, in create_trt_engine
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine
2022-04-20 08:42:23,544 - mmdeploy - ERROR - onnx2tensorrt of ../mmdeploy_workdir/end2end.onnx failed.
```

Are there anyone who have done similar experiments with DLA cores and MMDeploy?

**Comment by lzhangzz** [comment]
Had some experience working with the DLA on AGX Xavier. 

Which model are you testing? DLA support for various operators are quite limited, I suggest you start by trying simple models from MMClassification.

**Comment by lvhan028** [comment]
Closing since no further discussion for quite a long time. Feel free to open it if it is still an issue.
