### ISSUE TITLE
check_env.py error in openvino

### ISSUE THREAD

**Issue by zranguai** [open-mmlab/mmdeploy#432]
when i run python tools/check_env.py, the error occurred:
```
python ${MMDEPLOY_DIR}/tools/check_env.py
Traceback (most recent call last):
  File "/home/zranguai/Deploy/MMDeploy/tools/check_env.py", line 3, in <module>
    from mmcv.utils import collect_env as collect_base_env
  File "/home/zranguai/Downloads/enter/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/zranguai/Downloads/enter/envs/openmmlab/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/home/zranguai/Downloads/enter/envs/openmmlab/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/home/zranguai/Downloads/enter/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 39, in <module>
    from .env import collect_env
  File "/home/zranguai/Downloads/enter/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/env.py", line 9, in <module>
    import cv2
  File "/opt/intel/openvino_2021/python/python3/cv2/__init__.py", line 129, in <module>
    bootstrap()
  File "/opt/intel/openvino_2021/python/python3/cv2/__init__.py", line 112, in bootstrap
    import cv2
ImportError: libopencv_ml.so.4.5: cannot open shared object file: No such file or directory
```
but when i run in the pycharm it running good
```
2022-05-02 21:47:56,546 - mmdeploy - INFO - 

2022-05-02 21:47:56,546 - mmdeploy - INFO - **********Environmental information**********
2022-05-02 21:47:57,226 - mmdeploy - INFO - sys.platform: linux
2022-05-02 21:47:57,227 - mmdeploy - INFO - Python: 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
2022-05-02 21:47:57,227 - mmdeploy - INFO - CUDA available: True
2022-05-02 21:47:57,227 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3060
2022-05-02 21:47:57,227 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2022-05-02 21:47:57,227 - mmdeploy - INFO - NVCC: Build cuda_11.1.TC455_06.29190527_0
2022-05-02 21:47:57,227 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
2022-05-02 21:47:57,227 - mmdeploy - INFO - PyTorch: 1.8.0+cu111
2022-05-02 21:47:57,227 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

2022-05-02 21:47:57,227 - mmdeploy - INFO - TorchVision: 0.9.0+cu111
2022-05-02 21:47:57,227 - mmdeploy - INFO - OpenCV: 4.5.4
2022-05-02 21:47:57,227 - mmdeploy - INFO - MMCV: 1.4.0
2022-05-02 21:47:57,227 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2022-05-02 21:47:57,227 - mmdeploy - INFO - MMCV CUDA Compiler: 11.1
2022-05-02 21:47:57,227 - mmdeploy - INFO - MMDeploy: 0.4.0+8aba06d
2022-05-02 21:47:57,227 - mmdeploy - INFO - 

2022-05-02 21:47:57,227 - mmdeploy - INFO - **********Backend information**********
2022-05-02 21:47:57,329 - mmdeploy - INFO - onnxruntime: 1.8.1	ops_is_avaliable : True
2022-05-02 21:47:57,329 - mmdeploy - INFO - tensorrt: None	ops_is_avaliable : False
2022-05-02 21:47:57,329 - mmdeploy - INFO - ncnn: None	ops_is_avaliable : False
2022-05-02 21:47:57,329 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-05-02 21:47:57,330 - mmdeploy - INFO - openvino_is_avaliable: True
2022-05-02 21:47:57,330 - mmdeploy - INFO - 

2022-05-02 21:47:57,330 - mmdeploy - INFO - **********Codebase information**********
2022-05-02 21:47:57,330 - mmdeploy - INFO - mmdet:	2.24.0
2022-05-02 21:47:57,330 - mmdeploy - INFO - mmseg:	None
2022-05-02 21:47:57,330 - mmdeploy - INFO - mmcls:	0.17.0
2022-05-02 21:47:57,330 - mmdeploy - INFO - mmocr:	None
2022-05-02 21:47:57,330 - mmdeploy - INFO - mmedit:	None
2022-05-02 21:47:57,330 - mmdeploy - INFO - mmdet3d:	None
2022-05-02 21:47:57,330 - mmdeploy - INFO - mmpose:	None

Process finished with exit code 0
```

**Comment by AllentDan** [comment]
Hi, please make sure the python environments are the same for both the terminal and Pycharm you used.

**Comment by zranguai** [comment]
I solved this problem by commenting these lines in ~/.bashrc
+ before
```bash
# set env for openvino
source /opt/intel/openvino_2021/bin/setupvars.sh
source /opt/intel/openvino_2021/opencv/setupvars.sh
export INTEL_OPENVINO_DIR=/opt/intel/openvino_2021
export LD_LIBRARY_PATH=/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64
```

+ after
```bash
# set env for openvino
source /opt/intel/openvino_2021/bin/setupvars.sh
# source /opt/intel/openvino_2021/opencv/setupvars.sh
export INTEL_OPENVINO_DIR=/opt/intel/openvino_2021
# export LD_LIBRARY_PATH=/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64
```
