### ISSUE TITLE
I get an error when trying to deploy yolox to tensorrt.

### ISSUE THREAD

**Issue by NJIMAMTO** [open-mmlab/mmdeploy#453]
I tried to deploy the yolox tiny model to TensorRT by executing the following command, 
but an error occurs during the conversion stage from ONNX to TensorRT.

```
python {mmdeployDIR}/tools/deploy.py \
{mmdeployDIR}/configs/mmdet/detection/detection_tensorrt_dynamic-160x160-608x608.py \
{mmdetecitonDIR}/configs/yolox/mmdetection_custom_dataset.py \
{mmdetecitonDIR}/checkpoints/yolox_tiny_8x8_300e_coco_20211124_171234-b4047906.pth \
{mmdetecitonDIR}/demo/demo.jpg --work-dir deploy_test/ --show --device cuda --dump-info
```

The execution environment is as follows

```
Python: 3.6.9
GPU: Tesla T4
NVCC: Cuda compilation tools, release 11.1, V11.1.105
PyTorch: 1.10.1+cu111
TorchVision: 0.11.2+cu111
OpenCV: 4.5.4-dev
MMCV: 1.4.8
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.1
MMDetection: 2.23.0+
```

The output when the command is executed is as follows

```
2022-05-09 10:15:15,164 - mmdeploy - INFO - torch2onnx start.
load checkpoint from local path: {mmdetecitonDIR}//checkpoints/yolox_tiny_8x8_300e_coco_20211124_171234-b4047906.pth
2022-05-09 10:15:58,128 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-05-09:10:15:58,mmdeploy WARNING  [utils.py:92] DeprecationWarning: get_onnx_config will be deprecated in the future. 
{mmdeployDIR}/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
{mmdeployDIR}/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:260: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  dets, labels = TRTBatchedNMSop.apply(boxes, scores, int(scores.shape[-1]),
{mmdeployDIR}/mmdeploy/mmcv/ops/nms.py:177: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out_boxes = min(num_boxes, after_topk)
{mmdeployDIR}/mmdeploy/mmcv/ops/nms.py:181: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  (batch_size, out_boxes)).to(scores.device)
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
2022-05-09 10:16:05,280 - mmdeploy - INFO - torch2onnx success.
2022-05-09 10:16:05,541 - mmdeploy - INFO - onnx2tensorrt of deploy_test/end2end.onnx start.
2022-05-09 10:16:19,570 - mmdeploy - INFO - Successfully loaded tensorrt plugins from {mmdeployDIR}/build/lib/libmmdeploy_tensorrt_ops.so
2022-05-09:10:16:19,mmdeploy INFO     [init_plugins.py:32] Successfully loaded tensorrt plugins from {mmdeployDIR}/build/lib/libmmdeploy_tensorrt_ops.so
[05/09/2022-10:16:19] [TRT] [I] [MemUsageChange] Init CUDA: CPU +315, GPU +0, now: CPU 406, GPU 242 (MiB)
[05/09/2022-10:16:20] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 423 MiB, GPU 242 MiB
[05/09/2022-10:16:20] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 651 MiB, GPU 316 MiB
[05/09/2022-10:16:21] [TRT] [W] onnx2trt_utils.cpp:365: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[05/09/2022-10:16:21] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/09/2022-10:16:21] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/09/2022-10:16:21] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/09/2022-10:16:21] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/09/2022-10:16:21] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/09/2022-10:16:21] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/09/2022-10:16:21] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/09/2022-10:16:21] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/09/2022-10:16:21] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/09/2022-10:16:21] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/09/2022-10:16:21] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/09/2022-10:16:21] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[05/09/2022-10:16:21] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace: 
[05/09/2022-10:16:21] [TRT] [I] Successfully created plugin: TRTBatchedNMS
[05/09/2022-10:16:24] [TRT] [E] 4: [graphShapeAnalyzer.cpp::processCheck::593] Error Code 4: Internal Error (Concat_355: dimensions not compatible for concatenation)
2022-05-09:10:16:24,root ERROR    [utils.py:43] Failed to create TensorRT engine
Traceback (most recent call last):
  File "{mmdeployDIR}/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "{mmdeployDIR}/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 83, in onnx2tensorrt
    device_id=device_id)
  File "{mmdeployDIR}/mmdeploy/backend/tensorrt/utils.py", line 116, in create_trt_engine
```

**Comment by RunningLeon** [comment]
@NJIMAMTO Hi, what have changed in the model config `mmdetection_custom_dataset`? It works fine with standard checkpoint and config on my machine.

**Comment by NJIMAMTO** [comment]
@RunningLeon 
Oops, my bad. I forgot to explain.

Based on "yolox_tiny_8x8_300e_coco.py" modified to be able to train on its own data set.
The source code is shown below.

```python
_base_ = './yolox_tiny_8x8_300e_coco.py'

# 1. dataset settings
dataset_type = 'CocoDataset'
classes = ('1', '2')

img_scale = (640, 640)  # height, width

train_pipeline = [
    dict(type='Mosaic', img_scale=img_scale, pad_val=114.0),
    dict(
        type='RandomAffine',
        scaling_ratio_range=(0.1, 2),
        border=(-img_scale[0] // 2, -img_scale[1] // 2)),
    dict(
        type='MixUp',
        img_scale=img_scale,
        ratio_range=(0.8, 1.6),
        pad_val=114.0),
    dict(type='YOLOXHSVRandomAug'),
    dict(type='RandomFlip', flip_ratio=0.5),
    # According to the official implementation, multi-scale
    # training is not considered here but in the
    # 'mmdet/models/detectors/yolox.py'.
    dict(type='Resize', img_scale=img_scale, keep_ratio=True),
    dict(
        type='Pad',
        pad_to_square=True,
        # If the image is three-channel, the pad value needs
        # to be set separately for each channel.
        pad_val=dict(img=(114.0, 114.0, 114.0))),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1, 1), keep_empty=False),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Pad',
                pad_to_square=True,
                pad_val=dict(img=(114.0, 114.0, 114.0))),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]

train_dataset = dict(
    type='MultiImageMixDataset',
    dataset=dict(
        type=dataset_type,
        ann_file='{custom_dataset_dir}/train.json',
        img_prefix='{custom_dataset_dir}',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True)
        ],
        filter_empty_gt=False,
    ),
    pipeline=train_pipeline)

data = dict(
    samples_per_gpu=8,
    workers_per_gpu=4,
    persistent_workers=True,
    train=train_dataset,
    val=dict(
        type=dataset_type,
        ann_file='{custom_dataset_dir}/valid.json',
        img_prefix='{custom_dataset_dir}',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file='{custom_dataset_dir}/test.json',
        img_prefix='{custom_dataset_dir}',
        pipeline=test_pipeline))
```

For reference, the following is the output when the model config is changed to "yolox_tiny_8x8_300e_coco.py," which is the base model, and deployed.

```
2022-05-10 04:52:09,150 - mmdeploy - INFO - torch2onnx start.
load checkpoint from local path: {mmdetecitonDIR}/checkpoints/yolox_tiny_8x8_300e_coco_20211124_171234-b4047906.pth
2022-05-10 04:53:12,408 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-05-10:04:53:12,mmdeploy WARNING  [utils.py:92] DeprecationWarning: get_onnx_config will be deprecated in the future. 
{mmdeployDIR}/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
{mmdeployDIR}/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:260: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  dets, labels = TRTBatchedNMSop.apply(boxes, scores, int(scores.shape[-1]),
{mmdeployDIR}/mmdeploy/mmcv/ops/nms.py:177: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out_boxes = min(num_boxes, after_topk)
{mmdeployDIR}/mmdeploy/mmcv/ops/nms.py:181: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  (batch_size, out_boxes)).to(scores.device)
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
2022-05-10 04:53:23,485 - mmdeploy - INFO - torch2onnx success.
2022-05-10 04:53:23,740 - mmdeploy - INFO - onnx2tensorrt of deploy_test/end2end.onnx start.
2022-05-10 04:53:39,368 - mmdeploy - INFO - Successfully loaded tensorrt plugins from {mmdeployDIR}/build/lib/libmmdeploy_tensorrt_ops.so
2022-05-10:04:53:39,mmdeploy INFO     [init_plugins.py:32] Successfully loaded tensorrt plugins from {mmdeployDIR}/build/lib/libmmdeploy_tensorrt_ops.so
[05/10/2022-04:53:42] [TRT] [I] [MemUsageChange] Init CUDA: CPU +315, GPU +0, now: CPU 407, GPU 242 (MiB)
[05/10/2022-04:53:45] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 424 MiB, GPU 242 MiB
[05/10/2022-04:53:45] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 652 MiB, GPU 316 MiB
[05/10/2022-04:53:46] [TRT] [W] onnx2trt_utils.cpp:365: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[05/10/2022-04:53:46] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/10/2022-04:53:46] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/10/2022-04:53:46] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/10/2022-04:53:46] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/10/2022-04:53:46] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/10/2022-04:53:46] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/10/2022-04:53:46] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/10/2022-04:53:46] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/10/2022-04:53:46] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/10/2022-04:53:46] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/10/2022-04:53:46] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[05/10/2022-04:53:46] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[05/10/2022-04:53:46] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace: 
[05/10/2022-04:53:46] [TRT] [I] Successfully created plugin: TRTBatchedNMS
[05/10/2022-04:53:55] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.8.0 but loaded cuBLAS/cuBLAS LT 110.9.2
[05/10/2022-04:53:55] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +515, GPU +222, now: CPU 3988, GPU 1736 (MiB)
[05/10/2022-04:53:55] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +118, GPU +54, now: CPU 4106, GPU 1790 (MiB)
[05/10/2022-04:53:55] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[05/10/2022-04:53:56] [TRT] [E] 4: [shapeCompiler.cpp::evaluateShapeChecks::924] Error Code 4: Internal Error (kOPT values for profile 0 violate shape constraints: condition '==' violated. Concat_355: dimensions not compatible for concatenation)
2022-05-10:04:53:56,root ERROR    [utils.py:43] Failed to create TensorRT engine
Traceback (most recent call last):
  File "{mmdeployDIR}/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "{mmdeployDIR}/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 83, in onnx2tensorrt
    device_id=device_id)
  File "{mmdeployDIR}/mmdeploy/backend/tensorrt/utils.py", line 116, in create_trt_engine
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine
2022-05-10 04:53:57,116 - mmdeploy - ERROR - onnx2tensorrt of deploy_test/end2end.onnx failed.
```

**Comment by NJIMAMTO** [comment]
@RunningLeon
Thank you for your reply.

I checked the version and it was tensorrt==8.4.0.6.
So I downgraded to tensorrt==8.2.1.8.
However, the execution result remains the same and the deployment fails.

Please let me know if there are other areas that are affected.

**Comment by RunningLeon** [comment]
@NJIMAMTO Hi,  could test with config and ckpt from mmdet with following script?
```
python tools/deploy.py \
configs/mmdet/detection/detection_tensorrt_dynamic-160x160-608x608.py \
../mmdetection/configs/yolox/yolox_tiny_8x8_300e_coco.py \
https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_tiny_8x8_300e_coco/yolox_tiny_8x8_300e_coco_20211124_171234-b4047906.pth \
../mmdetection/demo/demo.jpg \
--work-dir ./work-dirs/mmdet/yolox/trt \
--device cuda
```

**Comment by NJIMAMTO** [comment]
@RunningLeon
Hmmm...I changed it and run it, but the error seems to be the same...

**Comment by RunningLeon** [comment]
@NJIMAMTO That's weird. Let's start from the very first. Have you build mmdeploy tensorrt custom ops following here: https://mmdeploy.readthedocs.io/en/latest/backends/tensorrt.html#build-custom-ops?

**Comment by NJIMAMTO** [comment]
@RunningLeon
Yes, I believe I built according to the above.
I re-built and deployed again, but the result was the same...

**Comment by RunningLeon** [comment]
@NJIMAMTO Hi, maybe you could send me config and ckpt and I'll try on my machine.

**Comment by NJIMAMTO** [comment]
@RunningLeon
How do I send it?

**Comment by RunningLeon** [comment]
google drive is OK for me.

> @RunningLeon How do I send it?

**Comment by NJIMAMTO** [comment]
@RunningLeon 
[Google Drive Link](https://drive.google.com/drive/folders/1kpG_EDJZmjVGDqJUrxtwNGiLtp8IjIPS?usp=sharing)
Please contact us if you cannot see this link.

**Comment by RunningLeon** [comment]
@NJIMAMTO Hi, I may need pth file trained with your custom yolox config, not following one that downloaded from mmdet.

![image](https://user-images.githubusercontent.com/28671653/168292225-1a1dc967-e66b-4d13-a250-9890ad5d8cfb.png)

**Comment by NJIMAMTO** [comment]
@RunningLeon 
Oops sorry, added the specified file.
Note that please rewrite the load_from in the config file to match your path.

**Comment by RunningLeon** [comment]
@NJIMAMTO Hi, thanks for your patience. I've tested your yolox of custom model config and ckpt. 
1. The only problem I met is that deploy config `configs/mmdet/detection/detection_tensorrt_dynamic-160x160-608x608.py` assumes input shape is from 160x160 to 608x608, while input shape from your custom model cfg is 640x640, which is not in the range. You could use `configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py` or customize your own deploy config.
2. I have successfully deployed your yolox with  `configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py` with the same script.
3. Since you have same error when deploying tiny yolox provided by mmdet, it's more likely because there's something wrong with your environment. Strongly suggest to use docker file by referring to https://mmdeploy.readthedocs.io/en/latest/tutorials/how_to_use_docker.html

**Comment by NJIMAMTO** [comment]
@RunningLeon 
Thank you.
I deployed via Docker and it completed successfully.
I should have used Docker from the beginning...sorry.

**Comment by RunningLeon** [comment]
@NJIMAMTO No problem. Good to know it solved. If you like our project,  could give us a star. Besides, PR is always welcome. :nerd_face:
