### ISSUE TITLE
AssertionError: active_rotated_filter_forward miss in module _ext

### ISSUE THREAD

**Issue by GeneralJing** [open-mmlab/mmdeploy#459]
command:
python tools/deploy.py ./configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-kitti.py ../mmdetection3d/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py ../mmdetection3d/checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth ../mmdetection3d/demo/data/kitti/kitti_000008.bin --work-dir converted_model/ --device cuda:0 --show

errors:
[2022-05-10 09:25:19.443] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
2022-05-10 09:25:19,473 - mmdeploy - INFO - torch2onnx start.
[2022-05-10 09:25:20.534] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
2022-05-10:09:25:20,root ERROR    [utils.py:43] active_rotated_filter_forward miss in module _ext
Traceback (most recent call last):
  File "/home/data/projects//work/MMDeploy/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "/home/data/projects/work/MMDeploy/mmdeploy/apis/pytorch2onnx.py", line 102, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/home/data/projects/work/MMDeploy/mmdeploy/apis/utils.py", line 21, in build_task_processor
    import_codebase(codebase_type)
  File "/home/data/projects/work/MMDeploy/mmdeploy/codebase/__init__.py", line 30, in import_codebase
    importlib.import_module(f'mmdeploy.codebase.{lib}')
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data/projects/work/MMDeploy/mmdeploy/codebase/mmdet3d/__init__.py", line 2, in <module>
    from .deploy import MMDetection3d, VoxelDetection
  File "/home/data/projects/work/MMDeploy/mmdeploy/codebase/mmdet3d/deploy/__init__.py", line 3, in <module>
    from .voxel_detection import VoxelDetection
  File "/home/idriver/data/projects/jzy/work/MMDeploy/mmdeploy/codebase/mmdet3d/deploy/voxel_detection.py", line 9, in <module>
    from mmdet3d.core.bbox import get_box_type
  File "/home/data/projects/work/mmdetection3d/mmdet3d/core/__init__.py", line 2, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/data/projects/work/mmdetection3d/mmdet3d/core/anchor/__init__.py", line 2, in <module>
    from mmdet.core.anchor import build_prior_generator
  File "/home/data/projects/work/mmdetection/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/data/projects/work/mmdetection/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/data/projects/work/mmdetection/mmdet/core/bbox/samplers/__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/data/projects/work/mmdetection/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/opt/conda/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/opt/conda/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 8, in <module>
    ext_module = ext_loader.load_ext(
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: active_rotated_filter_forward miss in module _ext
2022-05-10 09:25:20,868 - mmdeploy - ERROR - torch2onnx failed.

**Comment by VVsssssk** [comment]
Hi, can you show env by `python tools/check_env.py `? I think it seems like your mmcv problem.

**Comment by GeneralJing** [comment]
it's the problem of mmcv. the origin mmcv-full was replaced when i was installing mmdetection3d.
