### ISSUE TITLE
RuntimeError: Failed to parse onnx, In node 116 (importFallbackPluginImporter): UNSUPPORTED_NODE

### ISSUE THREAD

**Issue by GeneralJing** [open-mmlab/mmdeploy#463]
command:
python tools/deploy.py ./configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-kitti.py ../mmdetection3d/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py ../mmdetection3d/checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth ../mmdetection3d/demo/data/kitti/kitti_000008.bin --work-dir converted_model/ --device cuda:0 --show

errors:
2022-05-11 09:06:23,320 - mmdeploy - INFO - torch2onnx start.
2022-05-11:09:06:29,trimesh WARNING  [collision.py:11] No FCL -- collision checking will not work
/home/idriver/data/projects/mmdetection3d/mmdet3d/models/backbones/mink_resnet.py:9: UserWarning: Please follow `getting_started.md` to install MinkowskiEngine.`
  warnings.warn(
/home/idriver/data/projects/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py:84: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  warnings.warn(
load checkpoint from local path: ../mmdetection3d/checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth
2022-05-11 09:06:37,223 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-05-11:09:06:37,mmdeploy WARNING  [utils.py:91] DeprecationWarning: get_onnx_config will be deprecated in the future. 
/home/idriver/data/projects/MMDeploy/mmdeploy/codebase/mmdet3d/models/pillar_encode.py:41: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  f_center = features[..., :3] - (coors[..., 1:] * torch.tensor(
/home/idriver/data/projects/MMDeploy/mmdeploy/codebase/mmdet3d/models/pillar_encode.py:42: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  [self.vz, self.vy, self.vx]).to(device) + torch.tensor([
/home/idriver/data/projects/MMDeploy/mmdeploy/codebase/mmdet3d/models/voxelnet.py:53: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert batch_size == 1
2022-05-11 09:06:39,085 - mmdeploy - INFO - torch2onnx success.
2022-05-11 09:06:39,087 - mmdeploy - INFO - onnx2tensorrt of converted_model/end2end.onnx start.
2022-05-11 09:06:40,722 - mmdeploy - WARNING - Could not load the library of tensorrt plugins.             Because the file does not exist: 
2022-05-11:09:06:40,mmdeploy WARNING  [init_plugins.py:35] Could not load the library of tensorrt plugins.             Because the file does not exist: 
[TensorRT] WARNING: /workspace/TensorRT/t/oss-cicd/oss/parsers/onnx/onnx2trt_utils.cpp:227: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: /workspace/TensorRT/t/oss-cicd/oss/parsers/onnx/onnx2trt_utils.cpp:255: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: /workspace/TensorRT/t/oss-cicd/oss/parsers/onnx/onnx2trt_utils.cpp:255: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: /workspace/TensorRT/t/oss-cicd/oss/parsers/onnx/onnx2trt_utils.cpp:255: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: /workspace/TensorRT/t/oss-cicd/oss/parsers/onnx/onnx2trt_utils.cpp:255: One or more weights outside the range of INT32 was clamped
[TensorRT] INFO: No importer registered for op: ScatterND. Attempting to import as plugin.
[TensorRT] INFO: Searching for plugin: ScatterND, plugin_version: 1, plugin_namespace: 
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin ScatterND version 1
2022-05-11:09:06:51,root ERROR    [utils.py:43] Failed to parse onnx, In node 116 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

Traceback (most recent call last):
  File "/home/data/projects/MMDeploy/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "/home/data/projects/MMDeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 75, in onnx2tensorrt
    engine = create_trt_engine(
  File "/home/data/projects/MMDeploy/mmdeploy/backend/tensorrt/utils.py", line 76, in create_trt_engine
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 116 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

2022-05-11 09:06:51,430 - mmdeploy - ERROR - onnx2tensorrt of converted_model/end2end.onnx failed.

**Comment by GeneralJing** [comment]
solved.

**Comment by KangolHsu** [comment]
Solution?

**Comment by GeneralJing** [comment]
compile and produce the plugin file

**Comment by JinqingZhengTju** [comment]
> compile and produce the plugin file

Hi, I have met the same question. Can you tell me how to solve this kind of problem?
