### ISSUE TITLE
Could not find any implementation for node

### ISSUE THREAD

**Issue by DeepBlue97** [open-mmlab/mmdeploy#48]
env:
cuda 11.1
torch 1.8.2
python 3.8.12
tensorrt 8.2.2.1

====== log start ======

(mmdeploy_torch182) aiuser@aiuser-System-Product-Name:/workspace/lab_mmdeploy/work_dir$ python /home/aiuser/workspace/lab_mmdeploy/MMDeploy/tools/deploy.py /home/aiuser/workspace/lab_mmdeploy/MMDeploy/configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py /home/aiuser/workspace/mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py /home/aiuser/workspace/mmdetection/checkpoints/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth /home/aiuser/workspace/mmdetection/demo/COCO_test2014_000000118888.jpg --work-dir /home/aiuser/workspace/lab_mmdeploy/work_dir --device cuda:0 --dump-info
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
/home/aiuser/miniconda3/envs/mmdeploy_torch182/lib/python3.8/site-packages/mmdet/datasets/utils.py:65: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
warnings.warn(
2022-01-06:14:51:37,root INFO [deploy.py:72] torch2onnx start.
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
load checkpoint from local path: /home/aiuser/workspace/mmdetection/checkpoints/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth
/home/aiuser/miniconda3/envs/mmdeploy_torch182/lib/python3.8/site-packages/mmdet/datasets/utils.py:65: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
warnings.warn(
/home/aiuser/workspace/lab_mmdeploy/MMDeploy/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
ys_shape = tuple(int(s) for s in ys.shape)
/home/aiuser/miniconda3/envs/mmdeploy_torch182/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
/home/aiuser/miniconda3/envs/mmdeploy_torch182/lib/python3.8/site-packages/mmdet/core/anchor/anchor_generator.py:333: UserWarning: grid_anchors would be deprecated soon. Please use grid_priors
warnings.warn('grid_anchors would be deprecated soon. '
/home/aiuser/miniconda3/envs/mmdeploy_torch182/lib/python3.8/site-packages/mmdet/core/anchor/anchor_generator.py:369: UserWarning: single_level_grid_anchors would be deprecated soon. Please use single_level_grid_priors
warnings.warn(
/home/aiuser/workspace/lab_mmdeploy/MMDeploy/mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py:77: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/home/aiuser/workspace/lab_mmdeploy/MMDeploy/mmdeploy/pytorch/functions/topk.py:54: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
if k > size:
/home/aiuser/workspace/lab_mmdeploy/MMDeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
assert pred_bboxes.size(0) == bboxes.size(0)
/home/aiuser/workspace/lab_mmdeploy/MMDeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
assert pred_bboxes.size(1) == bboxes.size(1)
/home/aiuser/workspace/lab_mmdeploy/MMDeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:167: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
dets, labels = TRTBatchedNMSop.apply(boxes, scores, int(scores.shape[-1]),
/home/aiuser/workspace/lab_mmdeploy/MMDeploy/mmdeploy/mmcv/ops/nms.py:177: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
out_boxes = min(num_boxes, after_topk)
/home/aiuser/miniconda3/envs/mmdeploy_torch182/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py:2620: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
warnings.warn("Exporting aten::index operator of advanced indexing in opset " +
2022-01-06:14:51:59,root INFO [deploy.py:86] torch2onnx success.
2022-01-06:14:52:00,root INFO [deploy.py:72] onnx2tensorrt of /home/aiuser/workspace/lab_mmdeploy/work_dir/end2end.onnx start.
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
2022-01-06:14:52:02,root INFO [init_plugins.py:34] Successfully loaded tensorrt plugins from /home/aiuser/workspace/lab_mmdeploy/MMDeploy/build/lib/libmmdeploy_tensorrt_ops.so
[01/06/2022-14:52:02] [TRT] [I] [MemUsageChange] Init CUDA: CPU +323, GPU +0, now: CPU 390, GPU 235 (MiB)
[01/06/2022-14:52:02] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 390 MiB, GPU 235 MiB
[01/06/2022-14:52:03] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 525 MiB, GPU 269 MiB
[01/06/2022-14:52:03] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[01/06/2022-14:52:03] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:05] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:05] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:05] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:05] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:05] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:06] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:06] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[01/06/2022-14:52:06] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace:
[01/06/2022-14:52:06] [TRT] [I] Successfully created plugin: TRTBatchedNMS
[01/06/2022-14:52:06] [TRT] [I] No importer registered for op: MMCVMultiLevelRoiAlign. Attempting to import as plugin.
[01/06/2022-14:52:06] [TRT] [I] Searching for plugin: MMCVMultiLevelRoiAlign, plugin_version: 1, plugin_namespace:
[01/06/2022-14:52:06] [TRT] [I] Successfully created plugin: MMCVMultiLevelRoiAlign
[01/06/2022-14:52:06] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:06] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:06] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:07] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:07] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:07] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:07] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:07] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:07] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:07] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[01/06/2022-14:52:08] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
[01/06/2022-14:52:08] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[01/06/2022-14:52:08] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace:
[01/06/2022-14:52:08] [TRT] [I] Successfully created plugin: TRTBatchedNMS
[01/06/2022-14:52:08] [TRT] [I] No importer registered for op: MMCVMultiLevelRoiAlign. Attempting to import as plugin.
[01/06/2022-14:52:08] [TRT] [I] Searching for plugin: MMCVMultiLevelRoiAlign, plugin_version: 1, plugin_namespace:
[01/06/2022-14:52:08] [TRT] [I] Successfully created plugin: MMCVMultiLevelRoiAlign
[01/06/2022-14:52:09] [TRT] [I] No importer registered for op: grid_sampler. Attempting to import as plugin.
[01/06/2022-14:52:09] [TRT] [I] Searching for plugin: grid_sampler, plugin_version: 1, plugin_namespace:
[01/06/2022-14:52:09] [TRT] [I] Successfully created plugin: grid_sampler
[01/06/2022-14:52:09] [TRT] [W] Output type must be INT32 for shape outputs
[01/06/2022-14:52:09] [TRT] [W] Output type must be INT32 for shape outputs
[01/06/2022-14:52:09] [TRT] [W] Output type must be INT32 for shape outputs
[01/06/2022-14:52:09] [TRT] [W] Output type must be INT32 for shape outputs
[01/06/2022-14:52:15] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.3 but loaded cuBLAS/cuBLAS LT 11.3.0
[01/06/2022-14:52:15] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +93, GPU +164, now: CPU 3413, GPU 1473 (MiB)
[01/06/2022-14:52:15] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +397, GPU +172, now: CPU 3810, GPU 1645 (MiB)
[01/06/2022-14:52:15] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[01/06/2022-14:52:28] [TRT] [I] Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[01/06/2022-14:52:50] [TRT] [W] Myelin graph with multiple dynamic values may have poor performance if they differ. Dynamic values are:
[01/06/2022-14:52:50] [TRT] [W] (# 2 (SHAPE input))
[01/06/2022-14:52:50] [TRT] [W] (# 3 (SHAPE input))
[01/06/2022-14:53:20] [TRT] [W] Myelin graph with multiple dynamic values may have poor performance if they differ. Dynamic values are:
[01/06/2022-14:53:20] [TRT] [W] (# 3 (SHAPE input))
[01/06/2022-14:53:20] [TRT] [W] (# 2 (SHAPE input))
[01/06/2022-14:53:21] [TRT] [W] Skipping tactic 0 due to insuficient memory on requested size of 1459519488 detected for tactic 0.
[01/06/2022-14:53:21] [TRT] [E] 10: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[2337...Reshape_1696]}.)
2022-01-06:14:53:21,root ERROR [deploy.py:67] Failed to create TensorRT engine
Traceback (most recent call last):
File "/home/aiuser/workspace/lab_mmdeploy/MMDeploy/tools/deploy.py", line 62, in target_wrapper
result = target(*args, **kwargs)
File "/home/aiuser/workspace/lab_mmdeploy/MMDeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 64, in onnx2tensorrt
engine = create_trt_engine(
File "/home/aiuser/workspace/lab_mmdeploy/MMDeploy/mmdeploy/backend/tensorrt/utils.py", line 115, in create_trt_engine
assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine
2022-01-06:14:53:22,root ERROR [deploy.py:83] onnx2tensorrt of /home/aiuser/workspace/lab_mmdeploy/work_dir/end2end.onnx failed.
(mmdeploy_torch182) aiuser@aiuser-System-Product-Name:/workspace/lab_mmdeploy/work_dir$

====== log end======

ps: the node 2337 is a "Gather" op

**Comment by lvhan028** [comment]
@VVsssssk Could you please investigate this issue?

**Comment by VVsssssk** [comment]
Hello, I think if you want to convert a mask-rcnn model, you need to use $MMDEPLOY_DIR/config/mmdet/instance-seg/instance-seg_tensorrt_dynamic-320x320-1344x1344.py as deploy config.

**Comment by DeepBlue97** [comment]
> Hello, I think if you want to convert a mask-rcnn model, you need to use $MMDEPLOY_DIR/config/mmdet/instance-seg/instance-seg_tensorrt_dynamic-320x320-1344x1344.py as deploy config.

Wonderful, it solved my problem!

**Comment by FusionModele** [comment]
Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[Flatten_972...Slice_1023]}.)
2022-04-11:08:01:44,root ERROR    [utils.py:43] Failed to create TensorRT engine
---------------------------------------------------------------------------------------------
While trying to convert the Faster-RCNN in [MMDetection] to TensorRT:
!python /content/drive/MyDrive/mmdeploy/tools/deploy.py \
   /content/drive/MyDrive/mmdeploy/configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py \
    /content/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    /content/drive/MyDrive/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    /content/mmdetection/demo/demo.jpg \
    --work-dir /content/drive/MyDrive \
    --device cuda:0 \
    --dump-info
----------------------------
---------I got this :----------
load checkpoint from local path: /content/drive/MyDrive/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
/content/mmdetection/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
2022-04-11 08:00:35,728 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-04-11:08:00:35,mmdeploy WARNING  [utils.py:92] DeprecationWarning: get_onnx_config will be deprecated in the future. 
/content/drive/MyDrive/mmdeploy/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/content/mmdetection/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
/content/mmdetection/mmdet/core/anchor/anchor_generator.py:333: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/content/mmdetection/mmdet/core/anchor/anchor_generator.py:370: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '
/content/drive/MyDrive/mmdeploy/mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py:78: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/content/drive/MyDrive/mmdeploy/mmdeploy/pytorch/functions/topk.py:56: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k > size:
/content/drive/MyDrive/mmdeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/content/drive/MyDrive/mmdeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
/content/drive/MyDrive/mmdeploy/mmdeploy/codebase/mmdet/deploy/utils.py:47: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(max_shape) == 2, '`max_shape` should be [h, w]'
/content/drive/MyDrive/mmdeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:260: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  dets, labels = TRTBatchedNMSop.apply(boxes, scores, int(scores.shape[-1]),
/content/drive/MyDrive/mmdeploy/mmdeploy/mmcv/ops/nms.py:177: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out_boxes = min(num_boxes, after_topk)
/content/drive/MyDrive/mmdeploy/mmdeploy/mmcv/ops/nms.py:181: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  (batch_size, out_boxes)).to(scores.device)
/usr/local/lib/python3.7/dist-packages/torch/onnx/symbolic_opset9.py:2819: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  "If indices include negative values, the exported graph will produce incorrect results.")
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
2022-04-11 08:00:50,512 - mmdeploy - INFO - torch2onnx success.
2022-04-11 08:00:52,238 - mmdeploy - INFO - onnx2tensorrt of /content/drive/MyDrive/end2end.onnx start.
all params: {'fp16_mode': False, 'max_workspace_size': 1099511627776, 'input_shapes': {'input': {'min_shape': [1, 3, 320, 320], 'opt_shape': [1, 3, 800, 1344], 'max_shape': [1, 3, 1344, 1344]}}}
2022-04-11 08:00:56,754 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /content/drive/MyDrive/mmdeploy/build/lib/libmmdeploy_tensorrt_ops.so
2022-04-11:08:00:56,mmdeploy INFO     [init_plugins.py:32] Successfully loaded tensorrt plugins from /content/drive/MyDrive/mmdeploy/build/lib/libmmdeploy_tensorrt_ops.so
[04/11/2022-08:00:58] [TRT] [I] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 0, GPU 112 (MiB)
[04/11/2022-08:00:59] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 0 MiB, GPU 112 MiB
[04/11/2022-08:01:00] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 0 MiB, GPU 112 MiB
[04/11/2022-08:01:00] [TRT] [W] onnx2trt_utils.cpp:365: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[04/11/2022-08:01:00] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[04/11/2022-08:01:03] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[04/11/2022-08:01:03] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[04/11/2022-08:01:04] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[04/11/2022-08:01:04] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace: 
[04/11/2022-08:01:04] [TRT] [I] Successfully created plugin: TRTBatchedNMS
[04/11/2022-08:01:04] [TRT] [I] No importer registered for op: MMCVMultiLevelRoiAlign. Attempting to import as plugin.
[04/11/2022-08:01:04] [TRT] [I] Searching for plugin: MMCVMultiLevelRoiAlign, plugin_version: 1, plugin_namespace: 
[04/11/2022-08:01:04] [TRT] [I] Successfully created plugin: MMCVMultiLevelRoiAlign
[04/11/2022-08:01:04] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[04/11/2022-08:01:04] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[04/11/2022-08:01:04] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[04/11/2022-08:01:04] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[04/11/2022-08:01:04] [TRT] [W] onnx2trt_utils.cpp:391: One or more weights outside the range of INT32 was clamped
[04/11/2022-08:01:04] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
[04/11/2022-08:01:05] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[04/11/2022-08:01:05] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace: 
[04/11/2022-08:01:05] [TRT] [I] Successfully created plugin: TRTBatchedNMS
[04/11/2022-08:01:09] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.8.0 but loaded cuBLAS/cuBLAS LT 11.3.0
[04/11/2022-08:01:09] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +48, now: CPU 0, GPU 609 (MiB)
[04/11/2022-08:01:10] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +46, now: CPU 0, GPU 655 (MiB)
[04/11/2022-08:01:10] [TRT] [W] TensorRT was linked against cuDNN 8.3.2 but loaded cuDNN 8.0.5
[04/11/2022-08:01:10] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[04/11/2022-08:01:40] [TRT] [W] Myelin graph with multiple dynamic values may have poor performance if they differ. Dynamic values are: 
[04/11/2022-08:01:40] [TRT] [W]  (# 2 (SHAPE input))
[04/11/2022-08:01:40] [TRT] [W]  (# 3 (SHAPE input))
[04/11/2022-08:01:43] [TRT] [W] Skipping tactic 0 due to Myelin error: Myelin compiler is built against cuBLAS 11.8.1.0 but compiling graph against cuBLAS 10.2.1.0
[04/11/2022-08:01:44] [TRT] [E] 10: [optimizer.cpp::computeCosts::2033] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[Flatten_972...Slice_1023]}.)
2022-04-11:08:01:44,root ERROR    [utils.py:43] Failed to create TensorRT engine
Traceback (most recent call last):
  File "/content/drive/MyDrive/mmdeploy/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "/content/drive/MyDrive/mmdeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 83, in onnx2tensorrt
    device_id=device_id)
  File "/content/drive/MyDrive/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 116, in create_trt_engine
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine
2022-04-11 08:01:45,692 - mmdeploy - ERROR - onnx2tensorrt of /content/drive/MyDrive/end2end.onnx failed.
--------------------------------------------------------------------------------------------------------------------------------
env:
cuda 11.2
torch 1.10.0
python 3.7
tensorrt 8.4.0.6

**Comment by leemengwei** [comment]
@FusionModele  Hi
Have you solve it ?  I got  almost exact the same error :   Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[Flatten_977...Slice_1053]}.)
