### ISSUE TITLE
pytorch2onnx error on Jetson nano

### ISSUE THREAD

**Issue by sunjiahao1999** [open-mmlab/mmdeploy#641]
Follow [build for jetson](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/jetsons.md) to build the environment, but get unexpected wrong when deploying yolov3 on Jetson nano. Looking for help! p.s. onnx version is "1.8.0".

**Reproduction**

the command

```none
python ./tools/deploy.py \
>     configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py \
>     /home/admin/mmdetection/configs/yolo/yolov3_d53_mstrain-608_273e_coco.py \
>    /home/admin/mmdetection/checkpoints/yolov3_d53_fp16_mstrain-608_273e_coco_20210517_213542-4bc34944.pth \
>     /home/admin/mmdetection/demo/demo.jpg \
>     --work-dir work_dir \
>     --show \
>     --device cuda:0
```

**Environment**

```none
2022-06-24 10:26:33,350 - mmdeploy - INFO - **********Environmental information**********
2022-06-24 10:26:43,906 - mmdeploy - INFO - sys.platform: linux
2022-06-24 10:26:43,907 - mmdeploy - INFO - Python: 3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 19:12:04) [GCC 9.4.0]
2022-06-24 10:26:43,908 - mmdeploy - INFO - CUDA available: True
2022-06-24 10:26:43,909 - mmdeploy - INFO - GPU 0: NVIDIA Tegra X1
2022-06-24 10:26:43,910 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda-10.2
2022-06-24 10:26:43,910 - mmdeploy - INFO - NVCC: Build cuda_10.2_r440.TC440_70.29663091_0
2022-06-24 10:26:43,910 - mmdeploy - INFO - GCC: gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
2022-06-24 10:26:43,911 - mmdeploy - INFO - PyTorch: 1.10.0
2022-06-24 10:26:43,912 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:

  - GCC 7.5
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_53,code=sm_53;-gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72
  - CuDNN 8.2.1
    - Built with CuDNN 8.0
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=8.0.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -DMISSING_ARM_VST1 -DMISSING_ARM_VLD1 -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=open, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON, 

2022-06-24 10:26:43,912 - mmdeploy - INFO - TorchVision: 0.11.1
2022-06-24 10:26:43,913 - mmdeploy - INFO - OpenCV: 4.6.0
2022-06-24 10:26:43,913 - mmdeploy - INFO - MMCV: 1.4.0
2022-06-24 10:26:43,914 - mmdeploy - INFO - MMCV Compiler: GCC 7.5
2022-06-24 10:26:43,914 - mmdeploy - INFO - MMCV CUDA Compiler: 10.2
2022-06-24 10:26:43,914 - mmdeploy - INFO - MMDeploy: 0.5.0+0cac515
2022-06-24 10:26:43,915 - mmdeploy - INFO - 

2022-06-24 10:26:43,915 - mmdeploy - INFO - **********Backend information**********
2022-06-24 10:26:48,232 - mmdeploy - INFO - onnxruntime: None	ops_is_avaliable : False
2022-06-24 10:26:48,434 - mmdeploy - INFO - tensorrt: 8.2.1.8	ops_is_avaliable : True
2022-06-24 10:26:48,543 - mmdeploy - INFO - ncnn: None	ops_is_avaliable : False
2022-06-24 10:26:48,562 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-06-24 10:26:48,569 - mmdeploy - INFO - openvino_is_avaliable: False
2022-06-24 10:26:48,569 - mmdeploy - INFO - 

2022-06-24 10:26:48,570 - mmdeploy - INFO - **********Codebase information**********
2022-06-24 10:26:48,582 - mmdeploy - INFO - mmdet:	2.25.0
2022-06-24 10:26:48,583 - mmdeploy - INFO - mmseg:	None
2022-06-24 10:26:48,583 - mmdeploy - INFO - mmcls:	None
2022-06-24 10:26:48,583 - mmdeploy - INFO - mmocr:	None
2022-06-24 10:26:48,583 - mmdeploy - INFO - mmedit:	None
2022-06-24 10:26:48,583 - mmdeploy - INFO - mmdet3d:	None
2022-06-24 10:26:48,584 - mmdeploy - INFO - mmpose:	None
2022-06-24 10:26:48,584 - mmdeploy - INFO - mmrotate:	None
```

**Error traceback**

```none
[2022-06-24 09:01:04.799] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
[2022-06-24 09:01:14.637] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
[2022-06-24 09:01:25.599] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
2022-06-24 09:01:25,619 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
load checkpoint from local path: /home/admin/mmdetection/checkpoints/yolov3_d53_fp16_mstrain-608_273e_coco_20210517_213542-4bc34944.pth
/home/admin/mmdetection/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
2022-06-24 09:02:31,911 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-06-24 09:02:31,942 - mmdeploy - INFO - Export PyTorch model to ONNX: work_dir/end2end.onnx.
/home/admin/mmdeploy/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
Traceback (most recent call last):
  File "./tools/deploy.py", line 366, in <module>
    main()
  File "./tools/deploy.py", line 136, in main
    device=args.device)
  File "/home/admin/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 354, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/admin/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 322, in call_function
    return self.get_result_sync(call_id)
  File "/home/admin/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 303, in get_result_sync
    ret = self.get_caller(func_name).pop_mp_output(call_id)
  File "/home/admin/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 80, in pop_mp_output
    f'`{self._func_name}` with Call id: {call_id} failed.'
AssertionError: `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed.

```

**Comment by AllentDan** [comment]
Did you unlock the limit of Nano like [here](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/jetsons.md#runtime)?

**Comment by AllentDan** [comment]
Besides, please check RAM size through `nvidia-smi` and make sure it is big enough.

**Comment by sunjiahao1999** [comment]
Thanks for reply. I set `MAX N` mode and change deploy_cfg topk=1000. The torch2onnx bug seems to be solved, but there is another bug as following when onnx2tenorrt :(
```none
[06/24/2022-16:29:30] [TRT] [I] Total Activation Memory: 294057472
[06/24/2022-16:29:32] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU -18, now: CPU 2556, GPU 3879 (MiB)
[06/24/2022-16:29:33] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 2557, GPU 3889 (MiB)
[06/24/2022-16:29:37] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +22, GPU +512, now: CPU 22, GPU 512 (MiB)
[06/24/2022-16:29:37] [TRT] [E] 1: Unexpected exception std::bad_alloc
Process Process-3:
Traceback (most recent call last):
  File "/home/sjh/archiconda3/envs/mmlab/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/sjh/archiconda3/envs/mmlab/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sjh/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 105, in __call__
    ret = func(*args, **kwargs)
  File "/home/sjh/mmdeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 88, in onnx2tensorrt
    device_id=device_id)
  File "/home/sjh/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 155, in from_onnx
    save(engine, output_file_prefix + '.engine')
  File "/home/sjh/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 21, in save
    f.write(bytearray(engine.serialize()))
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "./tools/deploy.py", line 366, in <module>
    main()
  File "./tools/deploy.py", line 215, in main
    partition_type=partition_type)
  File "/home/sjh/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 354, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/sjh/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 322, in call_function
    return self.get_result_sync(call_id)
  File "/home/sjh/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 303, in get_result_sync
    ret = self.get_caller(func_name).pop_mp_output(call_id)
  File "/home/sjh/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 80, in pop_mp_output
    f'`{self._func_name}` with Call id: {call_id} failed.'
AssertionError: `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed.
```

**Comment by AllentDan** [comment]
Well, please try configs with low resolution for yolo like [detection_tensorrt_dynamic-160x160-608x608.py](https://github.com/open-mmlab/mmdeploy/blob/master/configs/mmdet/detection/detection_tensorrt_dynamic-160x160-608x608.py) or static configs. Besides, models with [320*320](https://github.com/open-mmlab/mmdetection/tree/master/configs/yolo/yolov3_d53_320_273e_coco.py) are suggested.

**Comment by AllentDan** [comment]
You may try the retinanet with resnet18 backbone first following the [build for jetson](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/jetsons.md)

**Comment by tehkillerbee** [comment]
@sunjiahao1999 For the onnx2tenorrt error, it looks like you are running out of RAM

**Comment by AllentDan** [comment]
CLose since no activity for quite a long time
