### ISSUE TITLE
TypeError: `engine` should be str or trt.ICudaEngine

### ISSUE THREAD

**Issue by WYL-Projects** [open-mmlab/mmdeploy#648]
Hello, when I use **mmdeploy.backend. tensorrt.TRTwrapper**  loads the TRT file,  the TRT file I loaded is a file converted by others through tensorrt7.1, the following information is output:

> 2022-06-26 11:26:30,878 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /home/wyl/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
2022-06-26 11:26:30,878 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /home/wyl/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
Traceback (most recent call last):
  File "/home/wyl/detr3d/detr3d_car_copy.py", line 94, in <module>
    model = TRTWrapper(engine='/home/wyl/detr3d/curvelanes_small.trt',
  File "/home/wyl/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/wrapper.py", line 87, in __init__
    raise TypeError(f'`engine` should be str or trt.ICudaEngine, \
TypeError: `engine` should be str or trt.ICudaEngine,                 but given: <class 'NoneType'>

My environment is:
```
Ubuntu 18.04 
anaconda 3
python 3.8.13
cuda 11.1
pytorch 1.9.1
mmcv 1.5.0
mmdeploy 0.5.0
tensorrt 8.2.3.0
```

I hope the leaders can provide me with some solutions, thank you very much indeed!

**Comment by AllentDan** [comment]
Apparently, the TRT version you used is not the same as the TRT converting engine file version. The only solution is to make them the same.

**Comment by ghazalehtrb** [comment]
Hi, I'm getting a similar error. I built the engine with mmdeploy/tools/deploy.py and it doesn't give any errors but when I want to test the same engine with mmdeploy/tools/test.py, I'm getting the following error:

```
[08/31/2022-16:39:44] [TRT] [E] 6: The engine plan file is not compatible with this version of TensorRT, expecting library version 8.4.1.5 got 8.4.3.1, please rebuild.
[08/31/2022-16:39:44] [TRT] [E] 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "mmdeploy/tools/test.py", line 151, in <module>
    main()
  File "mmdeploy/tools/test.py", line 120, in main
    model = task_processor.init_backend_model(args.model, uri=args.uri)
  File "/media/andrea/Disk_21/Desktop/ARES/leav-action-recognition-pipeline/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 73, in init_backend_model
    model = build_object_detection_model(
  File "/media/andrea/Disk_21/Desktop/ARES/leav-action-recognition-pipeline/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 734, in build_object_detection_model
    backend_detector = __BACKEND_MODEL.build(
  File "/media/andrea/Disk_21/Data/swift-storage-data/env/lib/python3.8/site-packages/mmcv/utils/registry.py", line 236, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/media/andrea/Disk_21/Desktop/ARES/leav-action-recognition-pipeline/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 27, in __build_backend_model
    return registry.module_dict[partition_name](
  File "/media/andrea/Disk_21/Desktop/ARES/leav-action-recognition-pipeline/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 64, in __init__
    self._init_wrapper(
  File "/media/andrea/Disk_21/Desktop/ARES/leav-action-recognition-pipeline/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 78, in _init_wrapper
    self.wrapper = BaseBackendModel._build_wrapper(
  File "/media/andrea/Disk_21/Desktop/ARES/leav-action-recognition-pipeline/mmdeploy/mmdeploy/codebase/base/backend_model.py", line 66, in _build_wrapper
    return TRTWrapper(
  File "/media/andrea/Disk_21/Desktop/ARES/leav-action-recognition-pipeline/mmdeploy/mmdeploy/backend/tensorrt/wrapper.py", line 87, in __init__
    raise TypeError(f'`engine` should be str or trt.ICudaEngine, \
TypeError: `engine` should be str or trt.ICudaEngine, but given: <class 'NoneType'>
```

**Comment by AllentDan** [comment]
`The engine plan file is not compatible with this version of TensorRT, expecting library version 8.4.1.5 got 8.4.3.1, please rebuild.`

**Comment by JackIRose** [comment]
> `The engine plan file is not compatible with this version of TensorRT, expecting library version 8.4.1.5 got 8.4.3.1, please rebuild.`

I use python deploy.py got engine file, but when I use from mmdeploy.backend.tensorrt import TRTWrapper  load generated engine file got follow error:
Could not load the library of tensorrt plugins.             Because the file does not exist:
[04/23/2024-16:19:26] [TRT] [E] 1: [pluginV2Runner.cpp::nvinfer1::rt::load::293] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[04/23/2024-16:19:26] [TRT] [E] 4: [runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)  
Traceback (most recent call last):
