### ISSUE TITLE
NotImplementedError: SOLOv2 does not support ONNX EXPORT

### ISSUE THREAD

**Issue by dygcjlu** [open-mmlab/mmdeploy#656]
1 i am trying to convert SOLOv2 model from Pytorch to Onnx with the following command.

python tools/deployment/pytorch2onnx.py     /home/xxd/dyg/open-mmlab/mmdetection/configs/solov2/solov2_r50_fpn_1x_coco.py     /home/xxd/dyg/open-mmlab/mmdetection/work_dirs/solov2_r50_fpn_1x_coco/epoch_5.pth     --output-file /home/xxd/dyg/open-mmlab/mmdetection/work_dirs/solov2_r50_fpn_1x_coco/epoch_5.onnx     --input-img /media/xxd/Data2/datasets/voc/test_img/2008_002378.jpg     --test-img /media/xxd/Data2/datasets/voc/test_img/2008_002378.jpg     --shape 640 480     --show     --verify

2 then i got the following error information.

tools/deployment/pytorch2onnx.py:297: UserWarning: Arguments like `--mean`, `--std`, `--dataset` would be         parsed directly from config file and are deprecated and         will be removed in future releases.
  warnings.warn('Arguments like `--mean`, `--std`, `--dataset` would be \
/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/onnx/symbolic.py:481: UserWarning: DeprecationWarning: This function will be deprecated in future. Welcome to use the unified model deployment toolbox MMDeploy: https://github.com/open-mmlab/mmdeploy
  warnings.warn(msg)
load checkpoint from local path: /home/xxd/dyg/open-mmlab/mmdetection/work_dirs/solov2_r50_fpn_1x_coco/epoch_5.pth
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 333, in <module>
    pytorch2onnx(
  File "tools/deployment/pytorch2onnx.py", line 89, in pytorch2onnx
    torch.onnx.export(
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/onnx/utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/onnx/utils.py", line 437, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/onnx/utils.py", line 388, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/home/xxd/dyg/open-mmlab/mmdetection/mmdet/models/detectors/base.py", line 169, in forward
    return self.onnx_export(img[0], img_metas[0])
  File "/home/xxd/dyg/open-mmlab/mmdetection/mmdet/models/detectors/base.py", line 359, in onnx_export
    raise NotImplementedError(f'{self.__class__.__name__} does '
NotImplementedError: SOLOv2 does not support ONNX EXPORT

**Comment by RunningLeon** [comment]
@dygcjlu Hi, SOLOv2 is not supported by far. You can refer to [supported_models](https://mmdeploy.readthedocs.io/en/latest/03-benchmark/supported_models.html).

**Comment by dygcjlu** [comment]
> @dygcjlu Hi, SOLOv2 is not supported by far. You can refer to [supported_models](https://mmdeploy.readthedocs.io/en/latest/03-benchmark/supported_models.html).

Thanks for your quick response.

**Comment by abhiagwl4262** [comment]
Hey @RunningLeon, Any progress on this ?

**Comment by RunningLeon** [comment]
@abhiagwl4262 solov2 is not supported by now. The most related PR is closed https://github.com/open-mmlab/mmdeploy/pull/649 by the contributor. Maybe you could try on this PR and check if it works.
