### ISSUE TITLE
Convertion SwinTransformer to ONNX, NotImplementedError: [Adaptive pool]:input size not accessible

### ISSUE THREAD

**Issue by lx-r** [open-mmlab/mmdeploy#658]
```sh
export DEPLOY_CFG_PATH="/aihub/doing/mmdeploy/configs/mmseg/segmentation_onnxruntime_static-512x512.py"
export MODEL_CFG_PATH="/aihub/doing/mmsegmentation/work_dirs112/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.py"
export MODEL_CHECKPOINT_PATH="/aihub/doing/mmsegmentation/work_dirs112/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K/best_mIoU_iter_15096.pth"
export INPUT_IMG="/aihub/1654077548404731.png"
export TEST_IMG="/aihub/1654077548404731.png"
export WORK_DIR="/aihub/doing/mmsegmentation/work_dirs112/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K"
export CALIB_DATA_CFG="/aihub/da"

python ./tools/deploy.py \
    ${DEPLOY_CFG_PATH} \
    ${MODEL_CFG_PATH} \
    ${MODEL_CHECKPOINT_PATH} \
    ${INPUT_IMG} \
    --test-img ${TEST_IMG} \
    --work-dir ${WORK_DIR} \
    --calib-dataset-cfg ${CALIB_DATA_CFG} \
    --log-level INFO \
    --show \
    --dump-info
```
With the script above to export swin tiny, Error occured as follows:

```sh
Traceback (most recent call last):
  File "/home/lx/sw/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/lx/sw/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 105, in __call__
    ret = func(*args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 86, in torch2onnx
    export(
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 354, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 324, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 273, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 105, in __call__
    ret = func(*args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/onnx/export.py", line 121, in export
    torch.onnx.export(
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 719, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/core/rewriters/rewriter_utils.py", line 371, in wrapper
    return self.func(self, *args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/onnx/optimizer.py", line 10, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 503, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 232, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 354, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1061, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/core/rewriters/rewriter_utils.py", line 360, in __call__
    return self.func(self, *args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/pytorch/ops/adaptive_avg_pool.py", line 72, in adaptive_avg_pool2d__default
    return adaptive_avg_pool2d(*args)
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 172, in wrapper
    return fn(g, *args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/pytorch/ops/adaptive_avg_pool.py", line 22, in symbolic_fn
    raise NotImplementedError(
NotImplementedError: [Adaptive pool]:input size not accessible
```
The `input` parameter in the symbolic_fn is of type `torch._C.Value` and `input.isCompleteTensor()` is `False`,
```python
    if not input.isCompleteTensor():
        if output_size == [1] * len(output_size):
            return g.op('GlobalMaxPool', input), None
        raise NotImplementedError(
            '[Adaptive pool]:input size not accessible')
```
Have Anyone Ecounted the Same Problem? 
Any help would be great appreciated!

**Comment by AllentDan** [comment]
Hi, @lx-r. Upernet is not in the supported model [list](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/03-benchmark/supported_models.md) now.

**Comment by AllentDan** [comment]
Hi, Please use the latest MMDeploy. Latest MMDeploy works fine.

**Comment by lx-r** [comment]
@AllentDan Thanks for your kind reply, with the latest mmdeploy, it worked with the input resolution **`512x512`,`256x256`,`1024x1024`,`1024x512`** set in `segmentation_onnxruntime_static-512x512.py`
```python
_base_ = ['./segmentation_static.py', '../_base_/backends/onnxruntime.py']

onnx_config = dict(input_shape=[512, 512])

```

However, there are still two problems：
 - **1.If I set the input shape to other smaller values, like `128x128` or `128x64`, it throw exception as the following:**
  ```sh
    out_h = (H + 2 * self.sampler.padding[0] - self.sampler.dilation[0] *
  /home/lx/.local/lib/python3.8/site-packages/mmseg/models/utils/embed.py:322: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
    out_w = (W + 2 * self.sampler.padding[1] - self.sampler.dilation[1] *
  Traceback (most recent call last):
    File "./tools/deploy.py", line 366, in <module>
      main()
    File "./tools/deploy.py", line 129, in main
      torch2ir(ir_type)(
    File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 354, in _wrap
      return self.call_function(func_name_, *args, **kwargs)
    File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 322, in call_function
      return self.get_result_sync(call_id)
    File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 303, in get_result_sync
      ret = self.get_caller(func_name).pop_mp_output(call_id)
    File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 79, in pop_mp_output
      assert call_id in self._mp_dict, \
  AssertionError: `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed.
  ```

- **2.If I set the input shape to values which are not the multiple of 64, like `524, 512`, it still gave the `NotImplementedError` like:**
```sh 
Traceback (most recent call last):
  File "/home/lx/sw/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/lx/sw/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 105, in __call__
    ret = func(*args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 86, in torch2onnx
    export(
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 354, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 324, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 273, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 105, in __call__
    ret = func(*args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/onnx/export.py", line 121, in export
    torch.onnx.export(
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 719, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/core/rewriters/rewriter_utils.py", line 371, in wrapper
    return self.func(self, *args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/onnx/optimizer.py", line 10, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 503, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 232, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 354, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1061, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/core/rewriters/rewriter_utils.py", line 360, in __call__
    return self.func(self, *args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/pytorch/ops/adaptive_avg_pool.py", line 71, in adaptive_avg_pool2d__default
    return adaptive_avg_pool2d(*args)
  File "/home/lx/.local/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 172, in wrapper
    return fn(g, *args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/pytorch/ops/adaptive_avg_pool.py", line 21, in symbolic_fn
    raise NotImplementedError(
NotImplementedError: [Adaptive pool]:input size not accessible
Traceback (most recent call last):
  File "./tools/deploy.py", line 366, in <module>
    main()
  File "./tools/deploy.py", line 129, in main
    torch2ir(ir_type)(
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 354, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 322, in call_function
    return self.get_result_sync(call_id)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 303, in get_result_sync
    ret = self.get_caller(func_name).pop_mp_output(call_id)
  File "/home/lx/.local/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 79, in pop_mp_output
    assert call_id in self._mp_dict, \
AssertionError: `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed.
```

**Comment by AllentDan** [comment]
Well, seems too small input resolution causes the stride of pooling to be zero which is not acceptable. Besides, 524x512 worked fine in my testing.

**Comment by lx-r** [comment]
@AllentDan **Great Thanks**, It worked fine after building the newest mmdeploy from source code(`master:0f0f676d1f43`) in linux.

By the way, 

which version of mmdeploy is pointed by the word "latest", building from the newest source code or the latest prebuild package in the release page [here](https://github.com/open-mmlab/mmdeploy/releases) ?

**Comment by AllentDan** [comment]
Sorry for not making it clear. In my testing at master branch of the codebase, it worked fine.
