### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by Pentahill** [open-mmlab/mmdeploy#66]
raised error when convert mmdetection model to openvino 

**command**

```
python tools/deploy.py configs/mmdet/detection/detection_openvino_dynamic-800x1344.py mmdetection/configs/retinanet/retinanet_r50_fpn_1x_coco.py mmdetection/checkpoints/retinanet/retinanet_r50_fpn_1x_coco_20200130-c2398f9e.pth det.jpg --work-dir ../deploy_result --device cpu
```

**env**

- TorchVision: 0.11.2+cu102
- OpenCV: 4.5.5
- MMCV: 1.4.2
- MMCV Compiler: GCC 8.3
- MMCV CUDA Compiler: not available
- MMDeployment: 0.1.0+fbce75e
- onnxruntime: None ops_is_avaliable : False
- tensorrt: None ops_is_avaliable : False
- ncnn: None ops_is_avaliable : False
- pplnn_is_avaliable: False
- openvino_is_avaliable: True

**Error traceback**

```
2022-01-12 02:16:04,908 - mmdeploy - INFO - torch2onnx start.
load checkpoint from local path: /tmp/mmlab_deploy/mmdetection/checkpoints/retinanet/retinanet_r50_fpn_1x_coco_20200130-c2398f9e.pth
/usr/local/lib/python3.8/site-packages/mmdet/datasets/utils.py:65: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
/home/user/.local/lib/python3.8/site-packages/torch/onnx/utils.py:97: UserWarning: `strip_doc_string' is deprecated and ignored. Will be removed in next PyTorch release. It's combined with `verbose' argument now. 
  warnings.warn("`strip_doc_string' is deprecated and ignored. Will be removed in "
/home/user/MMDeploy/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/home/user/MMDeploy/mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py:94: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/home/user/MMDeploy/mmdeploy/pytorch/functions/topk.py:27: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  k = torch.tensor(k, device=input.device, dtype=torch.long)
/home/user/MMDeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/home/user/MMDeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
/home/user/MMDeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:97: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  deltas.size(-1) // 4)
/home/user/MMDeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:98: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  stds = deltas.new_tensor(stds).view(1, -1).repeat(1, deltas.size(-1) // 4)
/home/user/MMDeploy/mmdeploy/codebase/mmdet/deploy/utils.py:45: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(max_shape) == 2, '`max_shape` should be [h, w]'
/home/user/MMDeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:109: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  iou_threshold = torch.tensor([iou_threshold], dtype=torch.float32)
/home/user/MMDeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:110: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  score_threshold = torch.tensor([score_threshold], dtype=torch.float32)
/home/user/MMDeploy/mmdeploy/mmcv/ops/nms.py:40: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  score_threshold = float(score_threshold)
/home/user/MMDeploy/mmdeploy/mmcv/ops/nms.py:41: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  iou_threshold = float(iou_threshold)
/home/user/.local/lib/python3.8/site-packages/mmcv/ops/nms.py:159: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
/home/user/.local/lib/python3.8/site-packages/mmcv/ops/nms.py:160: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
/home/user/.local/lib/python3.8/site-packages/mmcv/ops/nms.py:29: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if max_num > 0:
/home/user/.local/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py:2815: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  warnings.warn("Exporting aten::index operator of advanced indexing in opset " +
2022-01-12 02:16:33,191 - mmdeploy - INFO - torch2onnx success.
2022-01-12 02:16:33,311 - mmdeploy - INFO - onnx2openvino with ../deploy_result/end2end.onnx start.
2022-01-12 02:16:36,469 - mmdeploy - INFO - Args for Model Optimizer: mo --input_model="../deploy_result/end2end.onnx" --output_dir="../deploy_result" --output="dets,labels" --input="input" --input_shape="[1, 3, 800, 1344]" --disable_fusing 
2022-01-12 02:18:01,536 - mmdeploy - INFO - Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/home/user/MMDeploy/../deploy_result/end2end.onnx
	- Path for generated IR: 	/home/user/MMDeploy/../deploy_result
	- IR output name: 	end2end
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	input
	- Output layers: 	dets,labels
	- Input shapes: 	[1, 3, 800, 1344]
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	False
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	False
ONNX specific parameters:
	- Inference Engine found in: 	/home/user/.local/lib/python3.8/site-packages/openvino
Inference Engine version: 	2021.4.2-3976-0943ed67223-refs/pull/539/head
Model Optimizer version: 	2021.4.2-3976-0943ed67223-refs/pull/539/head
[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: /home/user/deploy_result/end2end.xml
[ SUCCESS ] BIN file: /home/user/deploy_result/end2end.bin
[ SUCCESS ] Total execution time: 84.31 seconds. 
[ SUCCESS ] Memory consumed: 674 MB. 

2022-01-12 02:18:01,537 - mmdeploy - INFO - Successfully exported OpenVINO model: ../deploy_result/end2end.xml
2022-01-12 02:18:01,803 - mmdeploy - INFO - onnx2openvino with ../deploy_result/end2end.onnx success.
2022-01-12 02:18:01,803 - mmdeploy - INFO - visualize openvino model start.
/usr/local/lib/python3.8/site-packages/mmdet/datasets/utils.py:65: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
dict_keys(['TopK_1171.0', 'TopK_1305.0', 'TopK_564.0', 'TopK_656.0', 'TopK_748.0', 'TopK_840.0', 'TopK_932.0', 'dets', 'labels'])
2022-01-12:02:18:18,root ERROR    [utils.py:41] dictionary keys changed during iteration
Traceback (most recent call last):
  File "/home/user/MMDeploy/mmdeploy/utils/utils.py", line 36, in target_wrapper
    result = target(*args, **kwargs)
  File "/home/user/MMDeploy/mmdeploy/apis/visualize.py", line 60, in visualize_model
    result = task_processor.run_inference(model, model_inputs)[0]
  File "/home/user/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 188, in run_inference
    return model(**model_inputs, return_loss=False, rescale=True)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 186, in forward
    outputs = self.forward_test(input_img, img_metas, *args, **kwargs)
  File "/home/user/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 261, in forward_test
    outputs = self.wrapper({self.input_name: imgs})
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/MMDeploy/mmdeploy/backend/openvino/wrapper.py", line 130, in forward
    outputs = self.__process_outputs(outputs)
  File "/home/user/MMDeploy/mmdeploy/backend/openvino/wrapper.py", line 111, in __process_outputs
    for output_name in outputs.keys():
RuntimeError: dictionary keys changed during iteration
2022-01-12 02:18:19,123 - mmdeploy - ERROR - visualize openvino model failed.
```

**Comment by RunningLeon** [comment]
@SingleZombie Hi, could you take a look at this issue? Thanks.

**Comment by SemyonBevzuk** [comment]
@SingleZombie
Hi, I had a similar problem with Python 3.8.
In the PR #58 this problem has been fixed.
https://github.com/open-mmlab/mmdeploy/blob/d5f463dc4de13ab21a15b368e1529dbbaf65ae9b/mmdeploy/backend/openvino/wrapper.py#L110-L117

**Comment by SingleZombie** [comment]
> @SingleZombie Hi, I had a similar problem with Python 3.8. In the PR #58 this problem has been fixed.
> 
> https://github.com/open-mmlab/mmdeploy/blob/d5f463dc4de13ab21a15b368e1529dbbaf65ae9b/mmdeploy/backend/openvino/wrapper.py#L110-L117

Thank you. I think this issue will be solved after the PR is merged.

**Comment by Pentahill** [comment]
thanks, it solved my problem
