### ISSUE TITLE
deploy OrientedRcnn  

### ISSUE THREAD

**Issue by Proient** [open-mmlab/mmdeploy#660]
I try to deploy the oritened-rcnn by run the flowing cmd:
```
python tools/deploy.py 
configs/mmrotate/rotated-detection_tensorrt_dynamic-320x320-1024x1024.py 
../mmrotate/configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py 
../mmrotate/checkpoint/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth 
../mmrotate/demo/demo.jpg --work-dir work_dirs --show --device cuda:0
```
I occurred the errors:
```
Process Process-2:
Traceback (most recent call last):
  File "/home/ldd/miniforge3/envs/mmdeploy-use/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ldd/miniforge3/envs/mmdeploy-use/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/media/ldd/3962-3830/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 105, in __call__
    ret = func(*args, **kwargs)
  File "/media/ldd/3962-3830/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 86, in torch2onnx
    export(
  File "/media/ldd/3962-3830/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 354, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/media/ldd/3962-3830/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 324, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/media/ldd/3962-3830/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 273, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/media/ldd/3962-3830/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 105, in __call__
    ret = func(*args, **kwargs)
  File "/media/ldd/3962-3830/mmdeploy/mmdeploy/apis/onnx/export.py", line 122, in export
    torch.onnx.export(
  File "/home/ldd/miniforge3/envs/mmdeploy-use/lib/python3.8/site-packages/torch/onnx/__init__.py", line 319, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/ldd/miniforge3/envs/mmdeploy-use/lib/python3.8/site-packages/torch/onnx/utils.py", line 113, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/ldd/miniforge3/envs/mmdeploy-use/lib/python3.8/site-packages/torch/onnx/utils.py", line 734, in _export
    params_dict = torch._C._jit_pass_onnx_deduplicate_initializers(graph, params_dict,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)
Traceback (most recent call last):
  File "tools/deploy.py", line 366, in <module>
    main()
  File "tools/deploy.py", line 129, in main
    torch2ir(ir_type)(
  File "/media/ldd/3962-3830/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 354, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/media/ldd/3962-3830/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 322, in call_function
    return self.get_result_sync(call_id)
  File "/media/ldd/3962-3830/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 303, in get_result_sync
    ret = self.get_caller(func_name).pop_mp_output(call_id)
  File "/media/ldd/3962-3830/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 79, in pop_mp_output
    assert call_id in self._mp_dict, \
AssertionError: `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed.
```
How to solve the issue?
that's my `pip3 list` results:
```
Package                       Version                 Location
----------------------------- ----------------------- -----------------------------------
absl-py                       1.0.0
actionlib                     1.13.2
addict                        2.4.0
angles                        1.9.13
attrs                         21.4.0
bondpy                        1.8.6
cachetools                    5.0.0
camera-calibration            1.16.0
camera-calibration-parsers    1.12.0
catkin                        0.8.10
certifi                       2022.6.15
charset-normalizer            2.0.12
click                         8.1.3
cmake                         3.22.4
colorama                      0.4.5
commonmark                    0.9.1
controller-manager            0.19.5
controller-manager-msgs       0.19.5
cv-bridge                     1.16.0
cycler                        0.11.0
Cython                        0.29.28
diagnostic-analysis           1.11.0
diagnostic-common-diagnostics 1.11.0
diagnostic-updater            1.11.0
dill                          0.3.5.1
dynamic-reconfigure           1.7.2
e2cnn                         0.2.1
flatbuffers                   2.0
fonttools                     4.33.3
gazebo_plugins                2.9.2
gazebo_ros                    2.9.2
gencpp                        0.6.5
geneus                        3.0.0
genlisp                       0.4.18
genmsg                        0.5.16
gennodejs                     2.0.2
genpy                         0.6.15
google-auth                   2.6.6
google-auth-oauthlib          0.4.6
grpcio                        1.46.1
h5py                          3.7.0
idna                          3.3
image-geometry                1.16.0
imageio                       2.19.1
importlib-metadata            4.11.3
iniconfig                     1.1.1
interactive-markers           1.12.0
joint-state-publisher         1.15.1
joint-state-publisher-gui     1.15.1
kiwisolver                    1.4.3
laser_geometry                1.6.7
loguru                        0.6.0
Markdown                      3.3.7
matplotlib                    3.5.2
message-filters               1.15.14
mmcv-full                     1.5.3                   /media/3962-3830/mmcv
mmdeploy                      0.5.0                   /media/3962-3830/mmdeploy
mmdet                         2.25.0
mmrotate                      0.3.1
model-index                   0.1.11
mpmath                        1.2.1
multiprocess                  0.70.13
ndindex                       1.6
networkx                      2.8
ninja                         1.10.2.3
numpy                         1.22.3
oauthlib                      3.2.0
onnx                          1.8.1
onnx-simplifier               0.3.5
onnxoptimizer                 0.2.7
onnxruntime                   1.8.0
opencv-python                 4.5.5.64
openmim                       0.2.0
ordered-set                   4.1.0
packaging                     21.3
pandas                        1.4.3
pbr                           5.9.0
Pillow                        9.1.1
pip                           21.2.4
pluggy                        1.0.0
protobuf                      3.20.1
py                            1.11.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycocotools                   2.0.2
Pygments                      2.12.0
pyparsing                     3.0.9
pytest                        7.1.2
python-dateutil               2.8.2
python-qt-binding             0.4.4
pytz                          2022.1
PyWavelets                    1.3.0
PyYAML                        6.0
qt-dotgraph                   0.4.2
qt-gui                        0.4.2
qt-gui-cpp                    0.4.2
qt-gui-py-common              0.4.2
requests                      2.28.0
requests-oauthlib             1.3.1
resource_retriever            1.12.7
rich                          12.4.4
rosbag                        1.15.14
rosboost-cfg                  1.15.8
rosclean                      1.15.8
roscreate                     1.15.8
rosgraph                      1.15.14
roslaunch                     1.15.14
roslib                        1.15.8
roslint                       0.12.0
roslz4                        1.15.14
rosmake                       1.15.8
rosmaster                     1.15.14
rosmsg                        1.15.14
rosnode                       1.15.14
rosparam                      1.15.14
rospy                         1.15.14
rosservice                    1.15.14
rostest                       1.15.14
rostopic                      1.15.14
rosunit                       1.15.8
roswtf                        1.15.14
rqt_action                    0.4.9
rqt_bag                       0.5.1
rqt_bag_plugins               0.5.1
rqt_console                   0.4.11
rqt_dep                       0.4.12
rqt_graph                     0.4.14
rqt_gui                       0.5.3
rqt_gui_py                    0.5.3
rqt_image_view                0.4.16
rqt_launch                    0.4.9
rqt_logger_level              0.4.11
rqt-moveit                    0.5.10
rqt_msg                       0.4.10
rqt_nav_view                  0.5.7
rqt_plot                      0.4.13
rqt_pose_view                 0.5.11
rqt_publisher                 0.4.10
rqt_py_common                 0.5.3
rqt_py_console                0.4.10
rqt-reconfigure               0.5.5
rqt-robot-dashboard           0.5.8
rqt-robot-monitor             0.5.14
rqt_robot_steering            0.5.12
rqt_runtime_monitor           0.5.9
rqt-rviz                      0.7.0
rqt_service_caller            0.4.10
rqt_shell                     0.4.11
rqt_srv                       0.4.9
rqt_tf_tree                   0.6.3
rqt_top                       0.4.10
rqt_topic                     0.4.13
rqt_web                       0.4.10
rsa                           4.8
rviz                          1.14.14
scikit-image                  0.19.2
scipy                         1.8.0
sensor-msgs                   1.13.1
setuptools                    61.2.0
six                           1.16.0
smach                         2.5.0
smach-ros                     2.5.0
smclib                        1.8.6
style                         1.1.0
sympy                         1.10.1
tabulate                      0.8.9
tensorboard                   2.9.0
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorrt                      8.4.0.9
terminaltables                3.1.10
testresources                 2.0.1
tf                            1.13.2
tf-conversions                1.13.2
tf2-geometry-msgs             0.7.5
tf2-kdl                       0.7.5
tf2-py                        0.7.5
tf2-ros                       0.7.5
thop                          0.0.31.post2005241907
tifffile                      2022.5.4
tomli                         2.0.1
topic-tools                   1.15.14
torch                         1.12.0a0+2c916ef.nv22.3
torch2trt                     0.2.0                   /media/3962-3830/torch2trt-trt8
torchaudio                    0.11.0
torchvision                   0.12.0
tqdm                          4.64.0
typing_extensions             4.2.0
update                        0.0.1
urllib3                       1.26.9
versioned-hdf5                1.3.10
Werkzeug                      2.1.2
wheel                         0.37.1
xacro                         1.14.13
yapf                          0.32.0
yolox                         0.3.0                   
```
my platform is nvidia orin, the envs contains mmrotate packages and mmdeploy packagese. Thanks!!!
add that's my envs:
```
2022-06-27 18:28:16,552 - mmdeploy - INFO - 

2022-06-27 18:28:16,553 - mmdeploy - INFO - **********Environmental information**********
2022-06-27 18:28:17,466 - mmdeploy - INFO - sys.platform: linux
2022-06-27 18:28:17,467 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 10:59:05) [GCC 10.2.0]
2022-06-27 18:28:17,467 - mmdeploy - INFO - CUDA available: True
2022-06-27 18:28:17,467 - mmdeploy - INFO - GPU 0: Orin
2022-06-27 18:28:17,467 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2022-06-27 18:28:17,467 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.4, V11.4.166
2022-06-27 18:28:17,467 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2022-06-27 18:28:17,467 - mmdeploy - INFO - PyTorch: 1.12.0a0+2c916ef.nv22.3
2022-06-27 18:28:17,467 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.4
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: NO AVX
  - CUDA Runtime 11.4
  - NVCC architecture flags: -gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72;-gencode;arch=compute_87,code=sm_87
  - CuDNN 8.3.2
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=11.4, CUDNN_VERSION=8.3.2, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=open, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=0, USE_NNPACK=0, USE_OPENMP=ON, USE_ROCM=OFF, 

2022-06-27 18:28:17,467 - mmdeploy - INFO - TorchVision: 0.12.0
2022-06-27 18:28:17,467 - mmdeploy - INFO - OpenCV: 4.5.5
2022-06-27 18:28:17,467 - mmdeploy - INFO - MMCV: 1.5.3
2022-06-27 18:28:17,467 - mmdeploy - INFO - MMCV Compiler: GCC 9.4
2022-06-27 18:28:17,467 - mmdeploy - INFO - MMCV CUDA Compiler: 11.4
2022-06-27 18:28:17,467 - mmdeploy - INFO - MMDeploy: 0.5.0+fa034e0
2022-06-27 18:28:17,467 - mmdeploy - INFO - 

2022-06-27 18:28:17,467 - mmdeploy - INFO - **********Backend information**********
2022-06-27 18:28:19,495 - mmdeploy - INFO - onnxruntime: 1.8.0	ops_is_avaliable : True
2022-06-27 18:28:19,559 - mmdeploy - INFO - tensorrt: 8.4.0.9	ops_is_avaliable : True
2022-06-27 18:28:19,594 - mmdeploy - INFO - ncnn: None	ops_is_avaliable : False
2022-06-27 18:28:19,605 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-06-27 18:28:19,614 - mmdeploy - INFO - openvino_is_avaliable: False
2022-06-27 18:28:19,614 - mmdeploy - INFO - 

2022-06-27 18:28:19,614 - mmdeploy - INFO - **********Codebase information**********
2022-06-27 18:28:22,984 - mmdeploy - INFO - mmdet:	2.25.0
2022-06-27 18:28:22,985 - mmdeploy - INFO - mmseg:	None
2022-06-27 18:28:22,985 - mmdeploy - INFO - mmcls:	None
2022-06-27 18:28:22,985 - mmdeploy - INFO - mmocr:	None
2022-06-27 18:28:22,985 - mmdeploy - INFO - mmedit:	None
2022-06-27 18:28:22,985 - mmdeploy - INFO - mmdet3d:	None
2022-06-27 18:28:22,985 - mmdeploy - INFO - mmpose:	None
2022-06-27 18:28:22,985 - mmdeploy - INFO - mmrotate:	0.3.1
```

**Comment by grimoire** [comment]
I am not sure. Could you try doing inference in https://github.com/open-mmlab/mmdeploy/blob/4d9e20960dad41565ba16feb4027fa53a35d860b/mmdeploy/apis/onnx/export.py#L122 before export , see what cause the device mismatch?

**Comment by Proient** [comment]
sorry, my torch is download a wrong version, it is CPU not gpu . Thanks!
