### ISSUE TITLE
error ocured when convert onnx to tensorrt on window10

### ISSUE THREAD

**Issue by centerzong** [open-mmlab/mmdeploy#708]
Thanks for your bug report. We appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

**Environment**

1. Please run `python tools/check_env.py` to collect necessary environment information and paste it here.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
2022-07-06 10:00:02,645 - mmdeploy - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
2022-07-06 10:00:23,286 - mmdeploy - INFO - Start pipeline mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt in subprocess
2022-07-06 10:00:24,096 - mmdeploy - INFO - Successfully loaded tensorrt plugins from d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\lib\mmdeploy_tensorrt_ops.dll
[07/06/2022-10:00:29] [TRT] [I] [MemUsageChange] Init CUDA: CPU +525, GPU +0, now: CPU 4637, GPU 1273 (MiB)
[07/06/2022-10:00:32] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 4683 MiB, GPU 1273 MiB
[07/06/2022-10:00:32] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 4866 MiB, GPU 1317 MiB
[07/06/2022-10:00:33] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[07/06/2022-10:00:33] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[07/06/2022-10:00:34] [TRT] [E] If_371_OutputLayer: IIfConditionalOutputLayer inputs must have the same shape.
Process Process-3:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mmDetecttionlab\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\envs\mmDetecttionlab\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 105, in __call__
    ret = func(*args, **kwargs)
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\backend\tensorrt\onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\backend\tensorrt\utils.py", line 113, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 371 (parseGraph): INVALID_NODE: Invalid Node - If_371
If_371_OutputLayer: IIfConditionalOutputLayer inputs must have the same shape.

Traceback (most recent call last):
  File "./tools/deploy.py", line 364, in <module>
    main()
  File "./tools/deploy.py", line 208, in main
    onnx2tensorrt(
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 354, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 322, in call_function
    return self.get_result_sync(call_id)
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 303, in get_result_sync
    ret = self.get_caller(func_name).pop_mp_output(call_id)
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 79, in pop_mp_output
    assert call_id in self._mp_dict, \
AssertionError: `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed.

**Comment by irexyc** [comment]
Which command do you use? Moreover, if the config you used is different from mm-xxx repos, please also paste them.

**Comment by centerzong** [comment]
thanks for your help.
**I use this command**: python ./tools/deploy.py configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py D:/workspace/AIWork/ai-desktop/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py ./tools/faster_rcnn/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth ./tools/faster_rcnn/demo.jpg --work-dir work-dir --show --device cuda --show --dump-info
**My GPU is Rtx3070** cuda11.3 pytorch1.12. 
**This is all the info** :d:\workspace\aiwork\mmdetection\mmdet\datasets\utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
2022-07-06 10:26:04,220 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
load checkpoint from local path: ./tools/faster_rcnn/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
d:\workspace\aiwork\mmdetection\mmdet\datasets\utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
2022-07-06 10:26:10,972 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
2022-07-06 10:26:10,974 - mmdeploy - INFO - Export PyTorch model to ONNX: work-dir\end2end.onnx.
d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\core\optimizers\function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
d:\workspace\aiwork\mmdetection\mmdet\models\dense_heads\anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
d:\workspace\aiwork\mmdetection\mmdet\core\anchor\anchor_generator.py:333: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors``
  warnings.warn('``grid_anchors`` would be deprecated soon. '
d:\workspace\aiwork\mmdetection\mmdet\core\anchor\anchor_generator.py:369: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors``
  warnings.warn(
d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\codebase\mmdet\models\dense_heads\rpn_head.py:78: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\pytorch\functions\topk.py:56: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k > size:
d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\codebase\mmdet\core\bbox\delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\codebase\mmdet\core\bbox\delta_xywh_bbox_coder.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\codebase\mmdet\deploy\utils.py:47: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(max_shape) == 2, '`max_shape` should be [h, w]'
d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\codebase\mmdet\core\post_processing\bbox_nms.py:259: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  dets, labels = TRTBatchedNMSop.apply(boxes, scores, int(scores.shape[-1]),
d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\mmcv\ops\nms.py:177: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out_boxes = min(num_boxes, after_topk)
C:\ProgramData\Anaconda3\envs\mmDetecttionlab\lib\site-packages\torch\onnx\symbolic_opset9.py:4182: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  warnings.warn(
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
2022-07-06 10:26:55,918 - mmdeploy - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
2022-07-06 10:27:19,696 - mmdeploy - INFO - Start pipeline mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt in subprocess
2022-07-06 10:27:20,423 - mmdeploy - INFO - Successfully loaded tensorrt plugins from d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\lib\mmdeploy_tensorrt_ops.dll
[07/06/2022-10:27:28] [TRT] [I] [MemUsageChange] Init CUDA: CPU +525, GPU +0, now: CPU 4988, GPU 1273 (MiB)
[07/06/2022-10:27:31] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 5032 MiB, GPU 1273 MiB
[07/06/2022-10:27:32] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 5218 MiB, GPU 1317 MiB
[07/06/2022-10:27:32] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[07/06/2022-10:27:32] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[07/06/2022-10:27:33] [TRT] [E] If_371_OutputLayer: IIfConditionalOutputLayer inputs must have the same shape.
Process Process-3:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mmDetecttionlab\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\envs\mmDetecttionlab\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 105, in __call__
    ret = func(*args, **kwargs)
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\backend\tensorrt\onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\backend\tensorrt\utils.py", line 113, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 371 (parseGraph): INVALID_NODE: Invalid Node - If_371
If_371_OutputLayer: IIfConditionalOutputLayer inputs must have the same shape.

Traceback (most recent call last):
  File "./tools/deploy.py", line 364, in <module>
    main()
  File "./tools/deploy.py", line 208, in main
    onnx2tensorrt(
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 354, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 322, in call_function
    return self.get_result_sync(call_id)
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 303, in get_result_sync
    ret = self.get_caller(func_name).pop_mp_output(call_id)
  File "d:\workspace\aiwork\ai-desktop\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 79, in pop_mp_output
    assert call_id in self._mp_dict, \
AssertionError: `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed.

**Comment by centerzong** [comment]
I run the script check_env.py, get the follow infomation.
2022-07-06 16:40:33,695 - mmdeploy - INFO - **********Environmental information**********
2022-07-06 16:40:43,611 - mmdeploy - INFO - sys.platform: win32
2022-07-06 16:40:43,612 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
2022-07-06 16:40:43,613 - mmdeploy - INFO - CUDA available: True
2022-07-06 16:40:43,613 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3070
2022-07-06 16:40:43,613 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
2022-07-06 16:40:43,614 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.109
2022-07-06 16:40:43,614 - mmdeploy - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30143 版
2022-07-06 16:40:43,614 - mmdeploy - INFO - GCC: n/a
2022-07-06 16:40:43,615 - mmdeploy - INFO - PyTorch: 1.12.0+cu113
2022-07-06 16:40:43,615 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: NO AVX
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

2022-07-06 16:40:43,616 - mmdeploy - INFO - TorchVision: 0.13.0+cu113
2022-07-06 16:40:43,617 - mmdeploy - INFO - OpenCV: 4.5.4
2022-07-06 16:40:43,618 - mmdeploy - INFO - MMCV: 1.5.0
2022-07-06 16:40:43,619 - mmdeploy - INFO - MMCV Compiler: MSVC 192930143
2022-07-06 16:40:43,620 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2022-07-06 16:40:43,621 - mmdeploy - INFO - MMDeploy: 0.5.0+cb09d22
2022-07-06 16:40:43,622 - mmdeploy - INFO -

2022-07-06 16:40:43,624 - mmdeploy - INFO - **********Backend information**********
2022-07-06 16:40:44,624 - mmdeploy - INFO - onnxruntime: 1.11.1 ops_is_avaliable : True
2022-07-06 16:40:44,682 - mmdeploy - INFO - tensorrt: 8.2.4.2   ops_is_avaliable : True
2022-07-06 16:40:44,786 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-07-06 16:40:44,803 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-07-06 16:40:44,864 - mmdeploy - INFO - openvino_is_avaliable: False
2022-07-06 16:40:44,865 - mmdeploy - INFO -

2022-07-06 16:40:44,867 - mmdeploy - INFO - **********Codebase information**********
2022-07-06 16:40:44,896 - mmdeploy - INFO - mmdet:      2.23.0
2022-07-06 16:40:44,897 - mmdeploy - INFO - mmseg:      0.23.0
2022-07-06 16:40:44,898 - mmdeploy - INFO - mmcls:      0.23.1
2022-07-06 16:40:44,899 - mmdeploy - INFO - mmocr:      0.6.0
2022-07-06 16:40:44,900 - mmdeploy - INFO - mmedit:     None
2022-07-06 16:40:44,901 - mmdeploy - INFO - mmdet3d:    None
2022-07-06 16:40:44,902 - mmdeploy - INFO - mmpose:     None
2022-07-06 16:40:44,903 - mmdeploy - INFO - mmrotate:   None

**Comment by irexyc** [comment]
I can't reproduce your problem. Can you share you onnx model?

**Comment by centerzong** [comment]
I stored my onnx here. thanks foryour help.
链接：https://pan.baidu.com/s/1er-KZTLhp7Vi7Qm1faU9lQ 
提取码：1234

**Comment by irexyc** [comment]
@centerzong 
I reproduce your problem with pytorch1.12. 
You may use lower version of pytorch like pytorch1.8.0+cu111.

@RunningLeon 
The master branch can't convert the model to onnx, the log is [here](https://justpaste.it/7r5yn)

If remove squeeze__default op, the problem is like @centerzong (don't know if he also delete the squeeze op).

**Comment by RunningLeon** [comment]
Could use torch==1.8.0. We have no test on pytorch>=1.10

**Comment by centerzong** [comment]
thanks for your help.
