### ISSUE TITLE
got error when convert mmdet model to onnx model

### ISSUE THREAD

**Issue by JustWeZero** [open-mmlab/mmdeploy#709]
I got an error when calling tools/deploy.py,traceback is:
Traceback (most recent call last):
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 101, in torch2onnx
    optimize=optimize)
  File "/home/group5/lzj/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/apis/onnx/export.py", line 132, in export
    verbose=verbose)
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/torch/onnx/__init__.py", line 320, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/torch/onnx/utils.py", line 111, in export
    custom_opsets=custom_opsets, use_external_data_format=use_external_data_format)
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/torch/onnx/utils.py", line 729, in _export
    dynamic_axes=dynamic_axes)
  File "/home/group5/lzj/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 373, in wrapper
    return self.func(self, *args, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/apis/onnx/optimizer.py", line 10, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/torch/onnx/utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/torch/onnx/utils.py", line 437, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/torch/onnx/utils.py", line 388, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/torch/jit/_trace.py", line 132, in forward
    self._force_outplace,
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 373, in wrapper
    return self.func(self, *args, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/base.py", line 71, in base_detector__forward
    return __forward_impl(ctx, self, img, img_metas=img_metas, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/core/optimizers/function_marker.py", line 261, in g
    rets = f(*args, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/base.py", line 27, in __forward_impl
    return self.simple_test(img, img_metas, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 373, in wrapper
    return self.func(self, *args, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/two_stage.py", line 58, in two_stage_detector__simple_test
    proposals, _ = self.rpn_head.simple_test_rpn(x, img_metas)
  File "/home/group5/lzj/mmdetection/mmdet/models/dense_heads/dense_test_mixins.py", line 125, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas)
  File "/home/group5/lzj/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 373, in wrapper
    return self.func(self, *args, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py", line 123, in rpn_head__get_bboxes
    max_shape=img_metas[0]['img_shape'])
TypeError: 'NoneType' object is not subscriptable

while I found,in dense_test_mixins.py,line 125:
"proposal_list = self.get_bboxes(*rpn_outs, img_metas)"
I can got correct img_metas,but in mmdeploy rpn_head.py,line 123:
max_shape=img_metas[0]['img_shape'])
It seems like the variable "img_metas" didn't pass correctly.so is this a bug?or how can I fix it?please help.

**Comment by RunningLeon** [comment]
@JustWeZero Hi, please post the script you ran here and the messages from `pytorch tools/check_env.py`.

**Comment by RunningLeon** [comment]
@JustWeZero Hi, could test standard config and ckpt from mmdet: https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py?

**Comment by JustWeZero** [comment]
Thank you for your reply! I have tried converting standard model. but I got a same error.Here is my script: 
python ./tools/deploy.py \
    configs/mmdet/detection/detection_tensorrt-int8_dynamic-320x320-1344x1344.py \
    ../mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    ../mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    ../mmdetection/demo/demo.jpg \
    --test-img ../mmdetection/demo/demo.jpg \
    --work-dir ../mmdetection/demo/demo_deploy \
    --calib-dataset-cfg ../mmdetection/configs/_base_/datasets/coco_detection.py \
    --device cuda:0 \
    --log-level INFO \
    --show \
    --dump-info

**Comment by JustWeZero** [comment]
ok I think I found where the problem is. It looks like when I updated my mmdetection's codes with git, some codes were wrong merged. I'll fix it and try again.

**Comment by RunningLeon** [comment]
@JustWeZero If there's something wrong with mmdeploy, pls. let me know.

**Comment by JustWeZero** [comment]
@RunningLeon hello, after I correct my codes, I got another problem, which I don't know how to fix it. 
python tools/check_env.py:
2022-07-07 12:46:53,111 - mmdeploy - INFO - 

2022-07-07 12:46:53,111 - mmdeploy - INFO - **********Environmental information**********
fatal: not a git repository (or any of the parent directories): .git
2022-07-07 12:46:55,244 - mmdeploy - INFO - sys.platform: linux
2022-07-07 12:46:55,244 - mmdeploy - INFO - Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
2022-07-07 12:46:55,244 - mmdeploy - INFO - CUDA available: True
2022-07-07 12:46:55,244 - mmdeploy - INFO - GPU 0,1,2,3: Tesla T4
2022-07-07 12:46:55,244 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2022-07-07 12:46:55,245 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.89
2022-07-07 12:46:55,245 - mmdeploy - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
2022-07-07 12:46:55,245 - mmdeploy - INFO - PyTorch: 1.10.0
2022-07-07 12:46:55,245 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

2022-07-07 12:46:55,245 - mmdeploy - INFO - TorchVision: 0.11.1
2022-07-07 12:46:55,245 - mmdeploy - INFO - OpenCV: 4.5.5
2022-07-07 12:46:55,245 - mmdeploy - INFO - MMCV: 1.3.18
2022-07-07 12:46:55,245 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2022-07-07 12:46:55,245 - mmdeploy - INFO - MMCV CUDA Compiler: 10.2
2022-07-07 12:46:55,245 - mmdeploy - INFO - MMDeploy: 0.6.0+
2022-07-07 12:46:55,245 - mmdeploy - INFO - 

2022-07-07 12:46:55,245 - mmdeploy - INFO - **********Backend information**********
2022-07-07 12:46:56,063 - mmdeploy - INFO - onnxruntime: 1.10.0 ops_is_avaliable : True
2022-07-07 12:46:56,103 - mmdeploy - INFO - tensorrt: 8.2.3.0   ops_is_avaliable : True
2022-07-07 12:46:56,122 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-07-07 12:46:56,123 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-07-07 12:46:56,123 - mmdeploy - INFO - openvino_is_avaliable: False
2022-07-07 12:46:56,123 - mmdeploy - INFO - 

2022-07-07 12:46:56,124 - mmdeploy - INFO - **********Codebase information**********
2022-07-07 12:46:56,125 - mmdeploy - INFO - mmdet:      2.25.0
2022-07-07 12:46:56,125 - mmdeploy - INFO - mmseg:      None
2022-07-07 12:46:56,125 - mmdeploy - INFO - mmcls:      0.19.0
2022-07-07 12:46:56,125 - mmdeploy - INFO - mmocr:      None
2022-07-07 12:46:56,125 - mmdeploy - INFO - mmedit:     None
2022-07-07 12:46:56,125 - mmdeploy - INFO - mmdet3d:    None
2022-07-07 12:46:56,125 - mmdeploy - INFO - mmpose:     None
2022-07-07 12:46:56,125 - mmdeploy - INFO - mmrotate:   None

stacktrace:
/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/mmcv/utils/registry.py:252: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
/home/group5/lzj/mmdetection/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
2022-07-07 12:44:01,684 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/mmcv/utils/registry.py:252: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
load checkpoint from local path: ../mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
/home/group5/lzj/mmdetection/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
2022-07-07 12:44:15,486 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-07-07 12:44:15,486 - mmdeploy - INFO - Export PyTorch model to ONNX: ../mmdetection/demo/demo_deploy/end2end.onnx.
/home/group5/lzj/mmdeploy/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/home/group5/lzj/mmdetection/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
/home/group5/lzj/mmdetection/mmdet/core/anchor/anchor_generator.py:333: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/home/group5/lzj/mmdetection/mmdet/core/anchor/anchor_generator.py:370: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '
/home/group5/lzj/mmdeploy/mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py:78: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/home/group5/lzj/mmdeploy/mmdeploy/pytorch/functions/topk.py:56: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k > size:
/home/group5/lzj/mmdeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/home/group5/lzj/mmdeploy/mmdeploy/codebase/mmdet/deploy/utils.py:47: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(max_shape) == 2, '`max_shape` should be [h, w]'
/home/group5/lzj/mmdeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:259: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  dets, labels = TRTBatchedNMSop.apply(boxes, scores, int(scores.shape[-1]),
/home/group5/lzj/mmdeploy/mmdeploy/mmcv/ops/nms.py:178: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out_boxes = min(num_boxes, after_topk)
/home/group5/lzj/mmdeploy/mmdeploy/mmcv/ops/nms.py:181: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  (batch_size, out_boxes)).to(scores.device))
/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:2819: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  "If indices include negative values, the exported graph will produce incorrect results.")
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
2022-07-07 12:44:26,296 - mmdeploy - INFO - Execute onnx optimize passes.
2022-07-07 12:44:26,296 - mmdeploy - WARNING - Can not optimize model, please build torchscipt extension.
More details: https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/experimental/onnx_optimizer.md
2022-07-07 12:44:28,529 - mmdeploy - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
2022-07-07 12:44:31,505 - mmdeploy - INFO - Start pipeline mmdeploy.apis.calibration.create_calib_input_data in subprocess
/home/group5/anaconda3/envs/SSPNet/lib/python3.7/site-packages/mmcv/utils/registry.py:252: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
load checkpoint from local path: ../mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
loading annotations into memory...
Done (t=0.62s)
creating index...
index created!
Process Process-3:
Traceback (most recent call last):
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/group5/anaconda3/envs/SSPNet/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/apis/calibration.py", line 68, in create_calib_input_data
    model, cfg=deploy_cfg, backend=backend, ir=ir)
  File "/home/group5/lzj/mmdeploy/mmdeploy/core/rewriters/rewriter_manager.py", line 54, in patch_model
    **kwargs)
  File "/home/group5/lzj/mmdeploy/mmdeploy/core/rewriters/module_rewriter.py", line 78, in patch_model
    env = collect_env(Backend.get(backend), ir)
  File "/home/group5/lzj/mmdeploy/mmdeploy/utils/constants.py", line 15, in get
    raise KeyError(f'Cannot get key by value "{value}" of {cls}')
KeyError: 'Cannot get key by value "Backend.TENSORRT" of <enum \'Backend\'>'
2022-07-07 12:44:46,728 - mmdeploy - ERROR - `mmdeploy.apis.calibration.create_calib_input_data` with Call id: 1 failed. exit.

script:
python ./tools/deploy.py \
    configs/mmdet/detection/detection_tensorrt-int8_dynamic-320x320-1344x1344.py \
    ../mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    ../mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    ../mmdetection/demo/demo.jpg \
    --test-img ../mmdetection/demo/demo.jpg \
    --work-dir ../mmdetection/demo/demo_deploy \
    --calib-dataset-cfg ../mmdetection/configs/_base_/datasets/coco_detection.py \
    --device cuda:0 \
    --log-level INFO \
    --show \
    --dump-info
I have updated the mmdeploy code to latest, and I have checked my TensorRT installtion, and ran sampleMNIST successfully (the running result is fail, but got no error). I didn't know how to fix it. Thanks a lot.

**Comment by RunningLeon** [comment]
@JustWeZero Hi, thanks for your feedback. It turns out a bug and will be fixed. For now you could change https://github.com/open-mmlab/mmdeploy/blob/585e34b229df9953d76f05d6d36644599cc8df30/mmdeploy/apis/calibration.py#L65
 to `backend = get_backend(deploy_cfg).value`
