### ISSUE TITLE
error ocured when convert onnx to tensorrt on window10 in pytorch 1.12.0

### ISSUE THREAD

**Issue by aodeluo** [open-mmlab/mmdeploy#723]
**Environment**
2022-07-08 08:07:08,159 - mmdeploy - INFO - sys.platform: win32
2022-07-08 08:07:08,159 - mmdeploy - INFO - Python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)]
2022-07-08 08:07:08,159 - mmdeploy - INFO - CUDA available: True
2022-07-08 08:07:08,159 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3050 Ti Laptop GPU
2022-07-08 08:07:08,159 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4
2022-07-08 08:07:08,159 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.4, V11.4.152
2022-07-08 08:07:08,160 - mmdeploy - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30145 版
2022-07-08 08:07:08,160 - mmdeploy - INFO - GCC: n/a
2022-07-08 08:07:08,161 - mmdeploy - INFO - PyTorch: 1.12.0
2022-07-08 08:07:08,161 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

2022-07-08 08:07:08,161 - mmdeploy - INFO - TorchVision: 0.13.0
2022-07-08 08:07:08,161 - mmdeploy - INFO - OpenCV: 4.6.0
2022-07-08 08:07:08,162 - mmdeploy - INFO - MMCV: 1.5.3
2022-07-08 08:07:08,162 - mmdeploy - INFO - MMCV Compiler: MSVC 192930145
2022-07-08 08:07:08,162 - mmdeploy - INFO - MMCV CUDA Compiler: 11.4
2022-07-08 08:07:08,162 - mmdeploy - INFO - MMDeploy: 0.6.0+
2022-07-08 08:07:08,163 - mmdeploy - INFO -

2022-07-08 08:07:08,163 - mmdeploy - INFO - **********Backend information**********
2022-07-08 08:07:08,854 - mmdeploy - INFO - onnxruntime: 1.8.1  ops_is_avaliable : True
2022-07-08 08:07:08,886 - mmdeploy - INFO - tensorrt: 8.2.3.0   ops_is_avaliable : True
2022-07-08 08:07:08,904 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-07-08 08:07:08,906 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-07-08 08:07:08,908 - mmdeploy - INFO - openvino_is_avaliable: False
2022-07-08 08:07:08,909 - mmdeploy - INFO -

2022-07-08 08:07:08,919 - mmdeploy - INFO - **********Codebase information**********
2022-07-08 08:07:08,924 - mmdeploy - INFO - mmdet:      2.25.0
2022-07-08 08:07:08,925 - mmdeploy - INFO - mmseg:      None
2022-07-08 08:07:08,926 - mmdeploy - INFO - mmcls:      0.23.1
2022-07-08 08:07:08,926 - mmdeploy - INFO - mmocr:      None
2022-07-08 08:07:08,926 - mmdeploy - INFO - mmedit:     None
2022-07-08 08:07:08,931 - mmdeploy - INFO - mmdet3d:    None
2022-07-08 08:07:08,931 - mmdeploy - INFO - mmpose:     None
2022-07-08 08:07:08,933 - mmdeploy - INFO - mmrotate:   None
1. Please run `python tools/check_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Commond**
python tools/deploy.py configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py D:\code\mmdetection\configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py D:\code\mmdetection\checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth 
D:\code\mmdetection\demo/demo.jpg 
--work-dir work_dir 
--show 
--device 
cuda:0

**Error traceback**
2022-07-07 22:24:19,098 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
load checkpoint from local path: D:\code\mmdetection\checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
d:\code\mmdetection\mmdet\datasets\utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
2022-07-07 22:24:21,797 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
2022-07-07 22:24:21,798 - mmdeploy - INFO - Export PyTorch model to ONNX: work_dir\end2end.onnx.
d:\code\mmdeploy\mmdeploy\core\optimizers\function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
d:\code\mmdetection\mmdet\models\dense_heads\anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
d:\code\mmdetection\mmdet\core\anchor\anchor_generator.py:333: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors``
  warnings.warn('``grid_anchors`` would be deprecated soon. '
d:\code\mmdetection\mmdet\core\anchor\anchor_generator.py:369: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors``
  warnings.warn(
d:\code\mmdeploy\mmdeploy\codebase\mmdet\models\dense_heads\rpn_head.py:78: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
d:\code\mmdeploy\mmdeploy\pytorch\functions\topk.py:56: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k > size:
d:\code\mmdeploy\mmdeploy\codebase\mmdet\core\bbox\delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
d:\code\mmdeploy\mmdeploy\codebase\mmdet\core\bbox\delta_xywh_bbox_coder.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
d:\code\mmdeploy\mmdeploy\codebase\mmdet\deploy\utils.py:47: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(max_shape) == 2, '`max_shape` should be [h, w]'
d:\code\mmdeploy\mmdeploy\codebase\mmdet\core\post_processing\bbox_nms.py:259: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  dets, labels = TRTBatchedNMSop.apply(boxes, scores, int(scores.shape[-1]),
d:\code\mmdeploy\mmdeploy\mmcv\ops\nms.py:178: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out_boxes = min(num_boxes, after_topk)
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\ASUS\.conda\envs\openmmlab\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\ASUS\.conda\envs\openmmlab\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "d:\code\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "d:\code\mmdeploy\mmdeploy\apis\pytorch2onnx.py", line 92, in torch2onnx
    export(
  File "d:\code\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "d:\code\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "d:\code\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "d:\code\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "d:\code\mmdeploy\mmdeploy\apis\onnx\export.py", line 122, in export
    torch.onnx.export(
  File "C:\Users\ASUS\.conda\envs\openmmlab\lib\site-packages\torch\onnx\__init__.py", line 350, in export
    return utils.export(
  File "C:\Users\ASUS\.conda\envs\openmmlab\lib\site-packages\torch\onnx\utils.py", line 163, in export
    _export(
  File "C:\Users\ASUS\.conda\envs\openmmlab\lib\site-packages\torch\onnx\utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "d:\code\mmdeploy\mmdeploy\core\rewriters\rewriter_utils.py", line 371, in wrapper
    return self.func(self, *args, **kwargs)
  File "d:\code\mmdeploy\mmdeploy\apis\onnx\optimizer.py", line 10, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "C:\Users\ASUS\.conda\envs\openmmlab\lib\site-packages\torch\onnx\utils.py", line 731, in _model_to_graph
    graph = _optimize_graph(
  File "C:\Users\ASUS\.conda\envs\openmmlab\lib\site-packages\torch\onnx\utils.py", line 308, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\ASUS\.conda\envs\openmmlab\lib\site-packages\torch\onnx\__init__.py", line 416, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "C:\Users\ASUS\.conda\envs\openmmlab\lib\site-packages\torch\onnx\utils.py", line 1399, in _run_symbolic_function
    if _need_symbolic_context(symbolic_fn):
  File "C:\Users\ASUS\.conda\envs\openmmlab\lib\site-packages\torch\onnx\utils.py", line 1333, in _need_symbolic_context
    type_hints = typing.get_type_hints(symbolic_fn)
  File "C:\Users\ASUS\.conda\envs\openmmlab\lib\typing.py", line 1255, in get_type_hints
    raise TypeError('{!r} is not a module, class, method, '
TypeError: <mmdeploy.core.rewriters.rewriter_utils.ContextCaller object at 0x000002478B103970> is not a module, class, method, or function.
(Occurred when translating squeeze).
2022-07-07 22:24:27,132 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
If applicable, paste the error trackback here.

**Comment by irexyc** [comment]
Duplicate of #708 

Please use lower version of pytorch. We test with pytorch 1.8.0 and it is ok to convert faster_rcnn model.
