### ISSUE TITLE
Search TRTbatchedNMS fail

### ISSUE THREAD

**Issue by Luwill6** [open-mmlab/mmdeploy#732]
I try to export engine file from mmdeploy, but failed. People said  that TRTbatchedNMS need a Tensorrt8, but my tensorrt version is 8.2.2.1. Hope to get your help

LOG:
_
[07/08/2022-19:34:22] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[07/08/2022-19:34:22] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace: 
Traceback (most recent call last):
  File "/home/lanq/pycharm/mmdeploy-master/tools/deploy.py", line 69, in target_wrapper
    result = target(*args, **kwargs)
  File "/home/lanq/pycharm/mmdeploy-master/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 64, in onnx2tensorrt
    device_id=device_id)
  File "/home/lanq/pycharm/mmdeploy-master/mmdeploy/backend/tensorrt/utils.py", line 75, in create_trt_engine
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 1315 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
2022-07-08:19:34:22,root ERROR    [deploy.py:74] Failed to parse onnx, In node 1315 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
_

**Comment by RunningLeon** [comment]
@Luwill6 Hi, pls. build custom ops for tensorrt. You could refer to https://mmdeploy.readthedocs.io/en/latest/05-supported-backends/tensorrt.html#build-custom-ops

**Comment by Luwill6** [comment]
I build custom ops, but still failed from ONNX to TENSORRT.Here are some infomation.

ERROR info:
**OSError: /home/lanq/pycharm/mmdeploy-master/build/lib/libmmdeploy_tensorrt_ops.so: undefined symbol: getPluginRegistry**

Deploy args:
'--deploy_cfg',default= '../configs/mmdet/_base_/base_tensorrt-fp16_dynamic-320x320-1344x1344.py', help='deploy config path'
'--model_cfg', default='/home/lanq/pycharm/mmdetection-master/configs/mask_rcnn/mask_rcnn_r101_fpn_1x_coco.py',help='model config path')
'--checkpoint', default='/home/lanq/pycharm/mmdetection-master/work_dirs/mask_rcnn_r101_fpn_1x_coco/epoch_150.pth', help='model checkpoint path')

**Comment by RunningLeon** [comment]
@Luwill6 Hi, sorry for the late reply. Seems TensorRT is not correctly installed, there might be multiple version of TensorRT. Pls. follow the [instruction](https://mmdeploy.readthedocs.io/en/latest/05-supported-backends/tensorrt.html#install-tensorrt) and retry.

> @RunningLeon .I build custom ops, but still failed from ONNX to TENSORRT.Here are some infomation.
> 
> ERROR info: **OSError: /home/lanq/pycharm/mmdeploy-master/build/lib/libmmdeploy_tensorrt_ops.so: undefined symbol: getPluginRegistry**
> 
> Deploy args: '--deploy_cfg',default= '../configs/mmdet/_base_/base_tensorrt-fp16_dynamic-320x320-1344x1344.py', help='deploy config path' '--model_cfg', default='/home/lanq/pycharm/mmdetection-master/configs/mask_rcnn/mask_rcnn_r101_fpn_1x_coco.py',help='model config path') '--checkpoint', default='/home/lanq/pycharm/mmdetection-master/work_dirs/mask_rcnn_r101_fpn_1x_coco/epoch_150.pth', help='model checkpoint path')

**Comment by RunningLeon** [comment]
closed for no activity in a long time

**Comment by xiaoxiao42** [comment]
Hi,
I meet same issue
```bash
libmmdeploy_tensorrt_ops.so: undefined symbol: getPluginRegistry
```

the libnvinfer.so is install in /usr/lib/x86_64-linux-gnu, I use docker image pulled from NGC (nvidia official docker-hub), which the TensorRT already installed in it. 

I use ldd to check libmmdeploy_tensorrt_ops.so dependency, here is the output, there is no nvinfer deps in it.

```bash
        linux-vdso.so.1 (0x00007ffd17172000)
        libcublas.so.11 => /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.11 (0x00007f6b9f847000)
        libcudnn.so.8 => /lib/x86_64-linux-gnu/libcudnn.so.8 (0x00007f6b9f61f000)
        libcudart.so.11.0 => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0 (0x00007f6b9f37d000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6b9f19b000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6b9f180000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6b9ef8c000)
        libcublasLt.so.11 => /usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.11 (0x00007f6b8b590000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6b8b56d000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6b8b562000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6b8b55c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6b8b40d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6ba9f25000)
```

**Comment by xiaoxiao42** [comment]
sorry for bother you, I figgured out what happened

**Comment by thuongtrannc** [comment]
Hi @xiaoxiao42, could you describe how can you deal with this issue? I had the same issue when deploying in Jetson.

The error is:

```
OSError: /home/stpc/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so: undefined symbol: getPluginRegistry
09/05 09:53:58 - mmengine - ERROR - /home/stpc/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.utils.utils.to_backend` with Call id: 1 failed. exit.

```

My jetpack version is:

```
Package: nvidia-jetpack
Version: 5.0.2-b231
Architecture: arm64
Maintainer: NVIDIA Corporation
```

TensorRT version is `8.4.1-1+cuda11.4`.

**Comment by thuongtrannc** [comment]
I figured out the issue. It happens because the `CMakeLists.txt` cannot link to `.so` libraries properly. Therefore, I linked the nvinfer libraries using HINTS for the `CMakeLists.txt` file for tensorrt_ops.

```
find_library(NVINFER NAMES nvinfer HINTS /lib/aarch64-linux-gnu)
find_library(NVONNXPARSER nvonnxparser HINTS /lib/aarch64-linux-gnu)
find_library(NVINFER_PLUGIN NAMES nvinfer_plugin HINTS /lib/aarch64-linux-gnu)
```

Then I add it to target_link_libraries 

```
target_link_libraries(	${PROJECT_NAME}_obj PUBLIC 
	  		${TENSORRT_LIBS} 
			cublas 
			cudnn
			${NVINFER} 
		        ${NVONNXPARSER} 
		        ${NVINFER_PLUGIN} )
mmdeploy_export(${PROJECT_NAME}_obj)

# Build module library. It is used to convert onnx model to tensorrt engine
mmdeploy_add_module(${PROJECT_NAME} MODULE EXCLUDE "")
target_link_libraries(	${PROJECT_NAME} PRIVATE 
			${PROJECT_NAME}_obj
			${NVINFER} 
	                ${NVONNXPARSER} 
        	        ${NVINFER_PLUGIN}
			)
add_library(mmdeploy::tensorrt_ops ALIAS ${PROJECT_NAME})
```

Finally, the linked libraries for `libmmdeploy_tensorrt_ops.so` should be:

```
	linux-vdso.so.1 (0x0000ffff98755000)
	libnvinfer.so.8 => /lib/aarch64-linux-gnu/libnvinfer.so.8 (0x0000ffff8586c000)
	libcublas.so.11 => /usr/local/cuda-11.4/lib64/libcublas.so.11 (0x0000ffff7b81a000)
	libcudnn.so.8 => /lib/aarch64-linux-gnu/libcudnn.so.8 (0x0000ffff7b7e4000)
	libcudart.so.11.0 => /usr/local/cuda-11.4/lib64/libcudart.so.11.0 (0x0000ffff7b72f000)
	libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000ffff7b54a000)
	libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffff7b49f000)
	libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000ffff7b47b000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff7b308000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffff98725000)
	libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffff7b2d7000)
	libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffff7b2c3000)
	librt.so.1 => /lib/aarch64-linux-gnu/librt.so.1 (0x0000ffff7b2ab000)
	libnvdla_compiler.so => /usr/lib/aarch64-linux-gnu/tegra/libnvdla_compiler.so (0x0000ffff7ac06000)
	libEGL.so.1 => /lib/aarch64-linux-gnu/libEGL.so.1 (0x0000ffff7abe2000)
	libnvmedia.so => /usr/lib/aarch64-linux-gnu/tegra/libnvmedia.so (0x0000ffff7ab6a000)
	libnvmedia_tensor.so => /usr/lib/aarch64-linux-gnu/tegra/libnvmedia_tensor.so (0x0000ffff7ab49000)
	libnvmedia_dla.so => /usr/lib/aarch64-linux-gnu/tegra/libnvmedia_dla.so (0x0000ffff7ab27000)
	libcublasLt.so.11 => /usr/local/cuda-11.4/lib64/libcublasLt.so.11 (0x0000ffff637c9000)
	libnvos.so => /usr/lib/aarch64-linux-gnu/tegra/libnvos.so (0x0000ffff637a9000)
	libGLdispatch.so.0 => /lib/aarch64-linux-gnu/libGLdispatch.so.0 (0x0000ffff6361e000)
	libnvvideo.so => /usr/lib/aarch64-linux-gnu/tegra/libnvvideo.so (0x0000ffff6353f000)
	libnvsocsys.so => /usr/lib/aarch64-linux-gnu/tegra/libnvsocsys.so (0x0000ffff6352b000)
	libnvrm_mem.so => /usr/lib/aarch64-linux-gnu/tegra/libnvrm_mem.so (0x0000ffff63513000)
	libnvrm_host1x.so => /usr/lib/aarch64-linux-gnu/tegra/libnvrm_host1x.so (0x0000ffff634f2000)
	libnvrm_surface.so => /usr/lib/aarch64-linux-gnu/tegra/libnvrm_surface.so (0x0000ffff634bc000)
	libnvtvmr.so => /usr/lib/aarch64-linux-gnu/tegra/libnvtvmr.so (0x0000ffff633c5000)
	libnvrm_chip.so => /usr/lib/aarch64-linux-gnu/tegra/libnvrm_chip.so (0x0000ffff633b1000)
	libnvrm_sync.so => /usr/lib/aarch64-linux-gnu/tegra/libnvrm_sync.so (0x0000ffff6339a000)
	libnvdc.so => /usr/lib/aarch64-linux-gnu/tegra/libnvdc.so (0x0000ffff6337a000)
	libnvparser.so => /usr/lib/aarch64-linux-gnu/tegra/libnvparser.so (0x0000ffff63330000)
	libnvdla_runtime.so => /usr/lib/aarch64-linux-gnu/tegra/libnvdla_runtime.so (0x0000ffff632a6000)
	libnvrm_stream.so => /usr/lib/aarch64-linux-gnu/tegra/libnvrm_stream.so (0x0000ffff6328d000)
	libnvsciipc.so => /usr/lib/aarch64-linux-gnu/tegra/libnvsciipc.so (0x0000ffff63268000)
	libnvimp.so => /usr/lib/aarch64-linux-gnu/tegra/libnvimp.so (0x0000ffff63251000)
```

It should include `libnvinfer.so` in it!
