### ISSUE TITLE
Error using tools/deploy.py: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0!

### ISSUE THREAD

**Issue by habjoel** [open-mmlab/mmdeploy#733]
Hi there, 
I am trying to use the brand new NVidia Jetson AGX Orin together with MMDetection models. Therefore I am trying to convert a Mask-RCNN model to TensorRT using tools/deploy.py. 

This worked perfectly on my older NVidia Jetson AGX Xavier. However, now I am getting the following error as it executes pytorch2onnx.py:

```sh
022-07-11 09:32:34,791 - mmdeploy - INFO - Execute onnx optimize passes.
2022-07-11 09:32:34,792 - mmdeploy - WARNING - Can not optimize model, please build torchscipt extension.
More details: https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/experimental/onnx_optimizer.md
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mmdeploy_installs/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/mmdeploy_installs/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 92, in torch2onnx
    export(
  File "/mmdeploy_installs/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/mmdeploy_installs/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/mmdeploy_installs/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/mmdeploy_installs/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/mmdeploy_installs/mmdeploy/mmdeploy/apis/onnx/export.py", line 122, in export
    torch.onnx.export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/__init__.py", line 319, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 113, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 734, in _export
    params_dict = torch._C._jit_pass_onnx_deduplicate_initializers(graph, params_dict,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)
2022-07-11 09:32:36,223 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

Below I post my environment (output of tools/check_env.py:
```sh
2022-07-11 10:04:40,107 - mmdeploy - INFO - 

2022-07-11 10:04:40,107 - mmdeploy - INFO - **********Environmental information**********
2022-07-11 10:04:40,397 - mmdeploy - INFO - sys.platform: linux
2022-07-11 10:04:40,397 - mmdeploy - INFO - Python: 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
2022-07-11 10:04:40,397 - mmdeploy - INFO - CUDA available: True
2022-07-11 10:04:40,397 - mmdeploy - INFO - GPU 0: Orin
2022-07-11 10:04:40,397 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2022-07-11 10:04:40,397 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.4, V11.4.166
2022-07-11 10:04:40,397 - mmdeploy - INFO - GCC: aarch64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2022-07-11 10:04:40,398 - mmdeploy - INFO - PyTorch: 1.12.0a0+2c916ef.nv22.3
2022-07-11 10:04:40,398 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.4
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: NO AVX
  - CUDA Runtime 11.4
  - NVCC architecture flags: -gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72;-gencode;arch=compute_87,code=sm_87
  - CuDNN 8.3.2
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=11.4, CUDNN_VERSION=8.3.2, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=open, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=0, USE_NNPACK=0, USE_OPENMP=ON, USE_ROCM=OFF, 

2022-07-11 10:04:40,398 - mmdeploy - INFO - TorchVision: 0.12.0a0+9b5a3fe
2022-07-11 10:04:40,398 - mmdeploy - INFO - OpenCV: 4.5.0
2022-07-11 10:04:40,398 - mmdeploy - INFO - MMCV: 1.5.3
2022-07-11 10:04:40,398 - mmdeploy - INFO - MMCV Compiler: GCC 9.4
2022-07-11 10:04:40,398 - mmdeploy - INFO - MMCV CUDA Compiler: 11.4
2022-07-11 10:04:40,398 - mmdeploy - INFO - MMDeploy: 0.6.0+585e34b
2022-07-11 10:04:40,398 - mmdeploy - INFO - 

2022-07-11 10:04:40,398 - mmdeploy - INFO - **********Backend information**********
2022-07-11 10:04:40,932 - mmdeploy - INFO - onnxruntime: None	ops_is_avaliable : False
2022-07-11 10:04:40,972 - mmdeploy - INFO - tensorrt: 8.4.0.11	ops_is_avaliable : True
2022-07-11 10:04:40,993 - mmdeploy - INFO - ncnn: None	ops_is_avaliable : False
2022-07-11 10:04:40,996 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-07-11 10:04:40,998 - mmdeploy - INFO - openvino_is_avaliable: False
2022-07-11 10:04:40,999 - mmdeploy - INFO - 

2022-07-11 10:04:40,999 - mmdeploy - INFO - **********Codebase information**********
2022-07-11 10:04:41,001 - mmdeploy - INFO - mmdet:	2.25.0
2022-07-11 10:04:41,001 - mmdeploy - INFO - mmseg:	None
2022-07-11 10:04:41,001 - mmdeploy - INFO - mmcls:	None
2022-07-11 10:04:41,001 - mmdeploy - INFO - mmocr:	None
2022-07-11 10:04:41,001 - mmdeploy - INFO - mmedit:	None
2022-07-11 10:04:41,001 - mmdeploy - INFO - mmdet3d:	None
2022-07-11 10:04:41,001 - mmdeploy - INFO - mmpose:	None
2022-07-11 10:04:41,001 - mmdeploy - INFO - mmrotate:	None
```
As further info: The Jetson AGX Orin runs TensorRT 8.4.0.11

Any help on how to resolve this issue would be much appreciated. I'd obviously like to do the model export using the Jetson gpu (cuda:0) and not the cpu.

Thanks in advance!

**Comment by RunningLeon** [comment]
@habjoel Hi, could post here the full script you are running? Have you added `--device cuda:0` to `tools/deploy.py`?

**Comment by habjoel** [comment]
@RunningLeon sorry for answering so late! The exact command I have used is the following:

```
python3 tools/deploy.py configs/mmdet/instance-seg/instance-seg_tensorrt-fp16_static-480x640.py ${MMDET_DIR}/configs/MaskRCNN-ResNet50-Trash/maskrcnn_trash_config.py ${MMDET_DIR}/checkpoints/maskrcnn_trash.pth ${MMDET_DIR}/data/data_train/images/selflabel_7classes/frame001600.jpg --work-dir exports/trt_maskrcnntrash_orin_480x640/ --show --device cuda:0 --dump-info
```

Where the config I am using contains the following:
```
_base_ = [
    '../_base_/base_instance-seg_static.py',
    '../../_base_/backends/tensorrt-fp16.py'
]

onnx_config = dict(input_shape=(640, 480))
backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 480, 640],
                    opt_shape=[1, 3, 480, 640],
                    max_shape=[1, 3, 480, 640])))
    ])
```
(Pretty much the same as `instance-seg_tensorrt-int8_static-800x1344.py` just with changed input dimensions)

**Comment by RunningLeon** [comment]
@habjoel Hi, have you changed any code in mmdet? Maybe you could check which tensor is on the cpu, especially those tensors created with `torch.tensor`, `torch.arange` and the device is not set to 'cuda'.

**Comment by habjoel** [comment]
@RunningLeon I have not changed any code in mmdet. I simply used configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py and die some transfer learning on it. It has been working perfectly on the Xavier but I cannot manage to do it on the Orin.

Where exactly should I look for `torch.tensor` or `torch.arange`?

Thanks!

**Comment by RunningLeon** [comment]
@habjoel That's weird. If you have not changed any code with mmdet, pls. make sure the version is same on the two devices. BTW, maybe you could try convert with cpu by changing `torch_model.cpu()`, `model_inputs.cpu()` :
https://github.com/open-mmlab/mmdeploy/blob/6e58c3c37a7036454d7134cb39383495cb6e3619/mmdeploy/apis/pytorch2onnx.py#L90-L100

**Comment by habjoel** [comment]
@RunningLeon thanks for the suggestion. I changed `torch_model` and `model_inputs` to `torch_model.cpu()` and `model_inputs.cpu()` respectively. 
Now I am running into some kind of error with onnx2tensorrt: 
```
untimeError: Failed to parse onnx, In node 294 (parseGraph): INVALID_NODE: Invalid Node - TopK_294
This version of TensorRT only supports input K as an initializer. Try applying constant folding on the model using Polygraphy: https://github.com/NVIDIA/TensorRT/tree/master/tools/Polygraphy/examples/cli/surgeon/02_folding_constants
```
Is this something that occurs when converting to ONNX on CPU rather than GPU? In any case, I am going to try and apply constant folding using the suggested tool and then run `tools/onnx2tensorrt.py` on the newly folded ONNX model.

**Comment by RunningLeon** [comment]
@habjoel It's weird since mmdeploy has rewriting for TopK and the K would be converted from `Tensor` to `int` by [topk__tensorrt](https://github.com/open-mmlab/mmdeploy/blob/6e58c3c37a7036454d7134cb39383495cb6e3619/mmdeploy/pytorch/functions/topk.py#L40). Could you check it goes with `topk__tensorrt` or [topk__dynamic](https://github.com/open-mmlab/mmdeploy/blob/6e58c3c37a7036454d7134cb39383495cb6e3619/mmdeploy/pytorch/functions/topk.py#L13)?

**Comment by habjoel** [comment]
So I got it working using [polygraphy surgeon sanitize](https://github.com/NVIDIA/TensorRT/tree/master/tools/Polygraphy/examples/cli/surgeon/02_folding_constants) and then tools/onnx2tensorrt.py on the folded .onnx model. The results look fine.

Sorry, where from should `topk_tensorrt` or `topk_dynamic` be called? I am happy to check but I have no clue about those functions...

Thanks!

**Comment by RunningLeon** [comment]
@habjoel `topk_tensorrt` should be called where `torch.topk` and `tensor.topk` is used. You could just add some printing message in the both functions.

**Comment by habjoel** [comment]
@RunningLeon please excuse me for this very late answer. I checked and found out that indeed `topk_tensorrt` is called and not `topk_dynamic`.

I don't know what exactly the issue could be!

**Comment by RunningLeon** [comment]
@habjoel That's werid. maskrcnn+torch==1.12.0 on 2080 tested OK for latest mmdeploy, could you try again with the latest mmdeploy?

**Comment by habjoel** [comment]
@RunningLeon yes, thanks for your help. everything worked using mmdeploy 0.8.0 :)
