### ISSUE TITLE
mmdeploy - ERROR - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed. exit

### ISSUE THREAD

**Issue by anshkumar** [open-mmlab/mmdeploy#780]
I was trying to convert Swin-T Mask R-CNN but getting following error:

```
[07/05/2022-13:55:25] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[07/05/2022-13:55:25] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace: 
Process Process-3:
Traceback (most recent call last):
  File "/home/sort/miniconda3/envs/openmmlab/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sort/miniconda3/envs/openmmlab/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sort/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/sort/mmdeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "/home/sort/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 113, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 2160 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

2022-07-05 13:55:26,152 - mmdeploy - ERROR - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed. exit.
```
I'm using following command:

```
python ./tools/deploy.py \
    'configs/mmdet/_base_/base_tensorrt-fp16_static-1050x1050.py' \
    '/home/sort/ved/sort/onion_l2/mask_rcnn_swin-t-p4-w7_fpn_fp16_ms-crop-3x_coco.py' \
    '/home/sort/ved/sort/onion_l2/mask_rcnn_swin/epoch_5.pth' \
    '/home/sort/ved/sort/onion_l2/data/val/images/10000000000001.0.jpg' \
    --test-img '/home/sort/ved/sort/onion_l2/data/val/images/1000000000012.0.jpg' \
    --work-dir '/home/sort/ved/sort/onion_l2/mmdeploy_out/' \
    --log-level DEBUG\
    --show \
    --device cuda:1
```
In file configs/mmdet/_base_/base_tensorrt-fp16_static-1050x1050.py I'm using 1056x1056 as dimensions.

**Comment by anshkumar** [comment]
Here's the output:
```
(openmmlab) sort@sort-X570S-AORUS-MASTER:~/mmdeploy$ python tools/check_env.py2022-07-20 19:14:53,072 - mmdeploy - INFO - 

2022-07-20 19:14:53,073 - mmdeploy - INFO - **********Environmental information**********
2022-07-20 19:14:53,209 - mmdeploy - INFO - sys.platform: linux
2022-07-20 19:14:53,209 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
2022-07-20 19:14:53,209 - mmdeploy - INFO - CUDA available: True
2022-07-20 19:14:53,209 - mmdeploy - INFO - GPU 0: NVIDIA Graphics Device
2022-07-20 19:14:53,209 - mmdeploy - INFO - GPU 1: NVIDIA GeForce RTX 3090
2022-07-20 19:14:53,209 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2022-07-20 19:14:53,209 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.1, V11.1.105
2022-07-20 19:14:53,209 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2022-07-20 19:14:53,209 - mmdeploy - INFO - PyTorch: 1.11.0
2022-07-20 19:14:53,209 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

2022-07-20 19:14:53,210 - mmdeploy - INFO - TorchVision: 0.12.0
2022-07-20 19:14:53,210 - mmdeploy - INFO - OpenCV: 4.6.0
2022-07-20 19:14:53,210 - mmdeploy - INFO - MMCV: 1.5.3
2022-07-20 19:14:53,210 - mmdeploy - INFO - MMCV Compiler: GCC 9.4
2022-07-20 19:14:53,210 - mmdeploy - INFO - MMCV CUDA Compiler: 11.1
2022-07-20 19:14:53,210 - mmdeploy - INFO - MMDeploy: 0.6.0+029ed69
2022-07-20 19:14:53,210 - mmdeploy - INFO - 

2022-07-20 19:14:53,210 - mmdeploy - INFO - **********Backend information**********
2022-07-20 19:14:54,335 - mmdeploy - INFO - onnxruntime: 1.11.1 ops_is_avaliable : True
2022-07-20 19:14:54,353 - mmdeploy - INFO - tensorrt: 8.4.1.5   ops_is_avaliable : True
2022-07-20 19:14:54,367 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-07-20 19:14:54,369 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-07-20 19:14:54,371 - mmdeploy - INFO - openvino_is_avaliable: False
2022-07-20 19:14:54,371 - mmdeploy - INFO - 

2022-07-20 19:14:54,371 - mmdeploy - INFO - **********Codebase information**********
2022-07-20 19:14:54,373 - mmdeploy - INFO - mmdet:      2.25.0
2022-07-20 19:14:54,373 - mmdeploy - INFO - mmseg:      None
2022-07-20 19:14:54,373 - mmdeploy - INFO - mmcls:      0.23.1
2022-07-20 19:14:54,373 - mmdeploy - INFO - mmocr:      None
2022-07-20 19:14:54,373 - mmdeploy - INFO - mmedit:     None
2022-07-20 19:14:54,373 - mmdeploy - INFO - mmdet3d:    None
2022-07-20 19:14:54,373 - mmdeploy - INFO - mmpose:     None
2022-07-20 19:14:54,373 - mmdeploy - INFO - mmrotate:   None
```

**Comment by AllentDan** [comment]
Hi, did you build MMDeploy from the source? Is there a file `mmdeploy/lib/libmmdeploy_tensorrt_ops.so`?

**Comment by anshkumar** [comment]
Building MMDeploy fixed this. But when running the `.engine` file I'm getting following error:
```
[07/21/2022-11:57:57] [TRT] [I] [MemUsageChange] Init CUDA: CPU +329, GPU +0, now: CPU 338, GPU 447 (MiB)
[07/21/2022-11:57:57] [TRT] [I] Loaded engine size: 109 MiB
[07/21/2022-11:57:57] [TRT] [W] Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
[07/21/2022-11:57:58] [TRT] [E] 1: [pluginV2Runner.cpp::load::293] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[07/21/2022-11:57:58] [TRT] [E] 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
```

Code:
```
import tensorrt as trt
logger = trt.Logger(trt.Logger.INFO)
trt.init_libnvinfer_plugins(logger, "")
engine_file = "/home/sort/ved/sort/onion/mmdeploy_out/end2end.engine"
with open(engine_file, 'rb') as f, trt.Runtime(logger) as runtime:
    model = runtime.deserialize_cuda_engine(f.read())
```

**Comment by AllentDan** [comment]
> Building MMDeploy fixed this. But when running the `.engine` file I'm getting following error:
> 
> ```
> [07/21/2022-11:57:57] [TRT] [I] [MemUsageChange] Init CUDA: CPU +329, GPU +0, now: CPU 338, GPU 447 (MiB)
> [07/21/2022-11:57:57] [TRT] [I] Loaded engine size: 109 MiB
> [07/21/2022-11:57:57] [TRT] [W] Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
> [07/21/2022-11:57:58] [TRT] [E] 1: [pluginV2Runner.cpp::load::293] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
> [07/21/2022-11:57:58] [TRT] [E] 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
> ```
> 
> Code:
> 
> ```
> import tensorrt as trt
> logger = trt.Logger(trt.Logger.INFO)
> trt.init_libnvinfer_plugins(logger, "")
> engine_file = "/home/sort/ved/sort/onion/mmdeploy_out/end2end.engine"
> with open(engine_file, 'rb') as f, trt.Runtime(logger) as runtime:
>     model = runtime.deserialize_cuda_engine(f.read())
> ```

Add the following two lines at the beginning of your codes:
```
from mmdeploy.backend.tensorrt import load_tensorrt_plugin
load_tensorrt_plugin()
```

**Comment by anshkumar** [comment]
It worked. Here's the final code:
```
from mmdeploy.backend.tensorrt import load_tensorrt_plugin
load_tensorrt_plugin()

import numpy as np
import os
import pycuda.driver as cuda
import pycuda.autoinit
import tensorrt as trt

from collections import OrderedDict, namedtuple
import torch
import cv2

device = 'cuda:0'
TRT_LOGGER = trt.Logger()

# Filenames of TensorRT plan file and input/output images.
engine_file = "/home/sort/ved/sort/apple_l2/mmdeploy_out/end2end.engine"
input_file = '/home/sort/ved/sort/apple_l2/data/val/images/970000000001.0.jpg'

# For torchvision models, input images are loaded in to a range of [0, 1] and
# normalized using mean = [0.485, 0.456, 0.406] and stddev = [0.229, 0.224, 0.225].
def preprocess(image):
    # Mean normalization
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image_width = image.shape[1]
    image_height = image.shape[0]
    mean = np.array([0.485, 0.456, 0.406]).astype('float32')
    stddev = np.array([0.229, 0.224, 0.225]).astype('float32')
    image = (image.astype('float32') / float(255.0) - mean) / stddev
    image = np.moveaxis(image, 2, 0)
    image = np.expand_dims(image, axis=0)
    return image

def postprocess(bindings):
    results = bindings['dets'].data
    labels = bindings['labels'].data
    # masks = bindings['y.60'].data
    masks = bindings['masks'].data

    bboxes = results[0,:,:-1]
    scores = results[0,:,-1]
    labels = labels[0, :]
    masks = masks[0, :, :, :]

    masks = masks[scores > 0.3].cpu().detach().numpy()
    bboxes = bboxes[scores > 0.3].cpu().detach().numpy()
    labels = labels[scores > 0.3].cpu().detach().numpy()
    scores = scores[scores > 0.3].cpu().detach().numpy()
    return [bboxes, scores, labels, masks]

Binding = namedtuple('Binding', ('name', 'dtype', 'shape', 'data', 'ptr'))
logger = trt.Logger(trt.Logger.INFO)
with open(engine_file, 'rb') as f, trt.Runtime(logger) as runtime:
    model = runtime.deserialize_cuda_engine(f.read())
bindings = OrderedDict()
for index in range(model.num_bindings):
    name = model.get_binding_name(index)
    dtype = trt.nptype(model.get_binding_dtype(index))
    shape = tuple(model.get_binding_shape(index))
    data = torch.from_numpy(np.empty(shape, dtype=np.dtype(dtype))).to(device)
    bindings[name] = Binding(name, dtype, shape, data, int(data.data_ptr()))
binding_addrs = OrderedDict((n, d.ptr) for n, d in bindings.items())
context = model.create_execution_context()

image_cv = cv2.imread(input_file)
image = torch.from_numpy(preprocess(image_cv)).to(device)
binding_addrs['input'] = int(image.data_ptr())
stream = cuda.Stream()
context.execute_async_v2(bindings=list(binding_addrs.values()), stream_handle=stream.handle)
stream.synchronize()
bboxes, scores, labels, masks = postprocess(bindings)
```
