### ISSUE TITLE
KeyError: 'Cannot get key by value "Backend.TENSORRT" of <enum \'Backend\'>'

### ISSUE THREAD

**Issue by anshkumar** [open-mmlab/mmdeploy#799]
I'm getting following error while converting mask-rcnn to tensorRT-INT8:
```
Traceback (most recent call last):
  File "/home/sort/miniconda3/envs/openmmlab/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sort/miniconda3/envs/openmmlab/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sort/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/sort/mmdeploy/mmdeploy/apis/calibration.py", line 67, in create_calib_input_data
    patched_model = patch_model(
  File "/home/sort/mmdeploy/mmdeploy/core/rewriters/rewriter_manager.py", line 53, in patch_model
    return MODULE_REWRITER.patch_model(model, cfg, backend, ir, recursive,
  File "/home/sort/mmdeploy/mmdeploy/core/rewriters/module_rewriter.py", line 78, in patch_model
    env = collect_env(Backend.get(backend), ir)
  File "/home/sort/mmdeploy/mmdeploy/utils/constants.py", line 15, in get
    raise KeyError(f'Cannot get key by value "{value}" of {cls}')
KeyError: 'Cannot get key by value "Backend.TENSORRT" of <enum \'Backend\'>'
2022-07-23 19:44:06,811 - mmdeploy - ERROR - `mmdeploy.apis.calibration.create_calib_input_data` with Call id: 1 failed. exit.
```

Here is the command I'm using:
```
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/home/sort/ved/TensorRT-8.4.1.5/lib

python /home/sort/mmdeploy/tools/deploy.py \
    'instance-seg_tensorrt-int8_static.py' \
    'mask_rcnn_swin-t-p4-w7_fpn_fp16_apple_l2.py' \
    'mask_rcnn_swin/epoch_50.pth' \
    'data/val/images/970000000001.0.jpg' \
    --test-img 'data/val/images/4510000000002.0.jpg' \
    --work-dir 'mmdeploy_out/' \
    --log-level DEBUG\
    --show \
    --device cuda:0 \
```

`instance-seg_tensorrt-int8_static.py` is as follows:
```
_base_ = [
    '/home/sort/mmdeploy/configs/mmdet/_base_/base_instance-seg_static.py',
    '/home/sort/mmdeploy/configs/_base_/backends/tensorrt-int8.py'
]

onnx_config = dict(input_shape=(800, 800))
backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 800, 800],
                    opt_shape=[1, 3, 800, 800],
                    max_shape=[1, 3, 800, 800])))
    ])
```
Environment info:
```
2022-07-23 19:10:29,800 - mmdeploy - INFO - 

2022-07-23 19:10:29,800 - mmdeploy - INFO - **********Environmental information**********
2022-07-23 19:10:29,993 - mmdeploy - INFO - sys.platform: linux
2022-07-23 19:10:29,993 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
2022-07-23 19:10:29,993 - mmdeploy - INFO - CUDA available: True
2022-07-23 19:10:29,993 - mmdeploy - INFO - GPU 0: NVIDIA Graphics Device
2022-07-23 19:10:29,993 - mmdeploy - INFO - GPU 1: NVIDIA GeForce RTX 3090
2022-07-23 19:10:29,993 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2022-07-23 19:10:29,993 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.1, V11.1.105
2022-07-23 19:10:29,993 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2022-07-23 19:10:29,993 - mmdeploy - INFO - PyTorch: 1.11.0
2022-07-23 19:10:29,993 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

2022-07-23 19:10:29,993 - mmdeploy - INFO - TorchVision: 0.12.0
2022-07-23 19:10:29,993 - mmdeploy - INFO - OpenCV: 4.6.0
2022-07-23 19:10:29,993 - mmdeploy - INFO - MMCV: 1.5.3
2022-07-23 19:10:29,993 - mmdeploy - INFO - MMCV Compiler: GCC 9.4
2022-07-23 19:10:29,993 - mmdeploy - INFO - MMCV CUDA Compiler: 11.1
2022-07-23 19:10:29,993 - mmdeploy - INFO - MMDeploy: 0.6.0+029ed69
2022-07-23 19:10:29,993 - mmdeploy - INFO - 

2022-07-23 19:10:29,993 - mmdeploy - INFO - **********Backend information**********
2022-07-23 19:10:30,247 - mmdeploy - INFO - onnxruntime: 1.11.1	ops_is_avaliable : True
2022-07-23 19:10:30,262 - mmdeploy - INFO - tensorrt: 8.4.1.5	ops_is_avaliable : True
2022-07-23 19:10:30,272 - mmdeploy - INFO - ncnn: None	ops_is_avaliable : False
2022-07-23 19:10:30,273 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-07-23 19:10:30,274 - mmdeploy - INFO - openvino_is_avaliable: False
2022-07-23 19:10:30,274 - mmdeploy - INFO - 

2022-07-23 19:10:30,274 - mmdeploy - INFO - **********Codebase information**********
2022-07-23 19:10:30,275 - mmdeploy - INFO - mmdet:	2.25.0
2022-07-23 19:10:30,275 - mmdeploy - INFO - mmseg:	None
2022-07-23 19:10:30,275 - mmdeploy - INFO - mmcls:	0.23.1
2022-07-23 19:10:30,275 - mmdeploy - INFO - mmocr:	None
2022-07-23 19:10:30,275 - mmdeploy - INFO - mmedit:	None
2022-07-23 19:10:30,275 - mmdeploy - INFO - mmdet3d:	None
2022-07-23 19:10:30,275 - mmdeploy - INFO - mmpose:	None
2022-07-23 19:10:30,275 - mmdeploy - INFO - mmrotate:	None
```

**Comment by RunningLeon** [comment]
@anshkumar Hi, thanks for your feedback. It's fixed in https://github.com/open-mmlab/mmdeploy/pull/719.
