### ISSUE TITLE
[E:onnxruntime:, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute]

### ISSUE THREAD

**Issue by fat-921** [open-mmlab/mmdeploy#807]
This error occurs when I run test.py and I don't understand what it means.I execute the following:
'''python tools/test.py D:\mmdeploy-master\mmdeploy-master\configs\mmseg\segmentation_onnxruntime_dynamic.py
D:\mmsegmentation-master\mmsegmentation-master\configs\my_pspnet_config.py
--model
D:\tmp\fsr_ort\end2end.onnx
--speed-test
--device
cpu
'''
results are as follows:

2022-07-25 14:39:10,524 - mmseg - INFO - Loaded 18 images
2022-07-25 14:39:10,524 - mmdeploy - INFO - Sorting the dataset by 'height' and 'width' is not possible.
2022-07-25 14:39:10,640 - mmdeploy - INFO - Successfully loaded onnxruntime custom ops from             D:\mmdeploy-master\mmdeploy-master\mmdeploy\lib\mmdeploy_onnxruntime_ops.dll
[                                                  ] 0/18, elapsed: 0s, ETA:2022-07-25 14:39:13.4829820 [E:onnxruntime:, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Conv node. Name:'371_nchwc' Status Message: nchwc_ops.cc:194 onnxruntime::contrib::NchwcConv::Compute output and sum shape must match

Process finished with exit code -1073741819 (0xC0000005)

**Comment by RunningLeon** [comment]
@fat-921 Hi, have you changed anything in mmseg? Could you try to convert the model with static deploy config(e.g., `segmentation_onnxruntime_static-1024x2048.py`)?

**Comment by fat-921** [comment]
> @fat-921 Hi, have you changed anything in mmseg? `PSPNet` only supports static shape per [here](https://mmdeploy.readthedocs.io/en/latest/03-benchmark/supported_models.html#supported-models). Could you try to convert the model with static deploy config(e.g., `segmentation_onnxruntime_static-1024x2048.py`)?

Yes, I have tried it.I execute the following:
‘’‘
python tools/deploy.py 
D:\mmdeploy-master\mmdeploy-master\configs\mmseg\segmentation_onnxruntime_static-1024x2048.py
D:/mmsegmentation-master/mmsegmentation-master/configs/my_pspnet_config.py
D:/mmsegmentation-master/mmsegmentation-master/tools/work_dirs/my_pspnet_config/latest.pth
D:/mmsegmentation-master/mmsegmentation-master/demo/0_c11.bmp
--work-dir
/tmp/fsr_ort_3
--device
cpu
--dump-info
’‘’


results are as follows:
'''
2022-07-25 16:20:58,555 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
d:\mmsegmentation-master\mmsegmentation-master\mmseg\models\losses\cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
load checkpoint from local path: D:/mmsegmentation-master/mmsegmentation-master/tools/work_dirs/my_pspnet_config/latest.pth
2022-07-25 16:20:59,231 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-07-25 16:20:59,232 - mmdeploy - INFO - Export PyTorch model to ONNX: /tmp/fsr_ort_3\end2end.onnx.
D:\mmdeploy-master\mmdeploy-master\mmdeploy\codebase\mmseg\models\segmentors\base.py:39: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  img_shape = [int(val) for val in img_shape]
D:\mmdeploy-master\mmdeploy-master\mmdeploy\codebase\mmseg\models\decode_heads\psp_head.py:31: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  size = [int(val) for val in size]
2022-07-25 16:21:01,392 - mmdeploy - INFO - Execute onnx optimize passes.
2022-07-25 16:21:01,392 - mmdeploy - WARNING - Can not optimize model, please build torchscipt extension.
More details: https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/experimental/onnx_optimizer.md
2022-07-25 16:21:01,705 - mmdeploy - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
2022-07-25 16:21:01,906 - mmdeploy - INFO - visualize onnxruntime model start.
2022-07-25 16:21:03,247 - mmdeploy - INFO - Successfully loaded onnxruntime custom ops from             D:\mmdeploy-master\mmdeploy-master\mmdeploy\lib\mmdeploy_onnxruntime_ops.dll
2022-07-25:16:21:03 - mmdeploy - INFO - Successfully loaded onnxruntime custom ops from             D:\mmdeploy-master\mmdeploy-master\mmdeploy\lib\mmdeploy_onnxruntime_ops.dll
2022-07-25 16:21:04.4681912 [E:onnxruntime:, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running ReorderOutput node. Name:'ReorderOutput' Status Message: D:\a\_work\1\s\onnxruntime\contrib_ops\cpu\nchwc_ops.cc:126 onnxruntime::contrib::ReorderOutput::Compute X_rank == 4 was false. 

2022-07-25 16:21:23,311 - mmdeploy - ERROR - visualize onnxruntime model failed.

Process finished with exit code 1

'''
It returns the same error.

**Comment by RunningLeon** [comment]
@fat-921 Hi, pls. run `python tools/check_env.py` and post env info here. If possible, could try with `onnxruntime==1.8.0`.

**Comment by fat-921** [comment]
> @fat-921 Hi, pls. run `python tools/check_env.py` and post env info here. If possible, could try with `onnxruntime==1.8.0`.

ok, there are my envs:
'''
2022-07-25 16:40:49,114 - mmdeploy - INFO - 

2022-07-25 16:40:49,114 - mmdeploy - INFO - **********Environmental information**********
2022-07-25 16:40:50,698 - mmdeploy - INFO - sys.platform: win32
2022-07-25 16:40:50,698 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
2022-07-25 16:40:50,698 - mmdeploy - INFO - CUDA available: True
2022-07-25 16:40:50,698 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3060 Ti
2022-07-25 16:40:50,698 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
2022-07-25 16:40:50,698 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.58
2022-07-25 16:40:50,698 - mmdeploy - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30146 版
2022-07-25 16:40:50,698 - mmdeploy - INFO - GCC: n/a
2022-07-25 16:40:50,698 - mmdeploy - INFO - PyTorch: 1.10.1
2022-07-25 16:40:50,698 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 

2022-07-25 16:40:50,698 - mmdeploy - INFO - TorchVision: 0.11.2
2022-07-25 16:40:50,698 - mmdeploy - INFO - OpenCV: 4.6.0
2022-07-25 16:40:50,698 - mmdeploy - INFO - MMCV: 1.5.3
2022-07-25 16:40:50,698 - mmdeploy - INFO - MMCV Compiler: MSVC 192930146
2022-07-25 16:40:50,698 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2022-07-25 16:40:50,698 - mmdeploy - INFO - MMDeploy: 0.6.0+unknown
2022-07-25 16:40:50,698 - mmdeploy - INFO - 

2022-07-25 16:40:50,698 - mmdeploy - INFO - **********Backend information**********
2022-07-25 16:40:50,962 - mmdeploy - INFO - onnxruntime: 1.8.1	ops_is_avaliable : True
2022-07-25 16:40:50,994 - mmdeploy - INFO - tensorrt: None	ops_is_avaliable : False
2022-07-25 16:40:51,035 - mmdeploy - INFO - ncnn: None	ops_is_avaliable : False
2022-07-25 16:40:51,044 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-07-25 16:40:51,047 - mmdeploy - INFO - openvino_is_avaliable: False
2022-07-25 16:40:51,047 - mmdeploy - INFO - 

2022-07-25 16:40:51,047 - mmdeploy - INFO - **********Codebase information**********
2022-07-25 16:40:51,049 - mmdeploy - INFO - mmdet:	None
2022-07-25 16:40:51,049 - mmdeploy - INFO - mmseg:	0.26.0
2022-07-25 16:40:51,049 - mmdeploy - INFO - mmcls:	0.23.1
2022-07-25 16:40:51,049 - mmdeploy - INFO - mmocr:	None
2022-07-25 16:40:51,049 - mmdeploy - INFO - mmedit:	None
2022-07-25 16:40:51,049 - mmdeploy - INFO - mmdet3d:	None
2022-07-25 16:40:51,049 - mmdeploy - INFO - mmpose:	None
2022-07-25 16:40:51,049 - mmdeploy - INFO - mmrotate:	None

Process finished with exit code 0
'''

**Comment by fat-921** [comment]
> @fat-921 Hi, pls. run `python tools/check_env.py` and post env info here. If possible, could try with `onnxruntime==1.8.0`.

I have tried onnxruntime==1.8.0，the same error is reported

**Comment by fat-921** [comment]
The error was resolved when I changed the data_root in D:/mmsegmentation-master/mmsegmentation-master/configs/my_pspnet_config.py to a relative path。but when i run **python tools/test.py**, have another mistake。
I execute the following：
`
python tools/test.py
D:\mmdeploy-master\mmdeploy-master\configs\mmseg\segmentation_onnxruntime_static-1024x2048.py
D:\mmsegmentation-master\mmsegmentation-master\configs\my_pspnet_config.py
--model
D:\tmp\fsr_ort_2\end2end.onnx
--device
cpu
--show-dir
D:\mmdeploy-master\mmdeploy-master\test_image\test1
`
results are as follows:
`
2022-07-25 17:21:01,566 - mmseg - INFO - Loaded 18 images
2022-07-25 17:21:01,566 - mmdeploy - INFO - Sorting the dataset by 'height' and 'width' is not possible.
2022-07-25 17:21:01,683 - mmdeploy - INFO - Successfully loaded onnxruntime custom ops from             D:\mmdeploy-master\mmdeploy-master\mmdeploy\lib\mmdeploy_onnxruntime_ops.dll
[                                                  ] 0/18, elapsed: 0s, ETA:Traceback (most recent call last):
  File "D:/mmdeploy-master/mmdeploy-master/tools/test.py", line 143, in <module>
    main()
  File "D:/mmdeploy-master/mmdeploy-master/tools/test.py", line 135, in main
    outputs = task_processor.single_gpu_test(model, data_loader, args.show,
  File "D:\mmdeploy-master\mmdeploy-master\mmdeploy\codebase\base\task.py", line 138, in single_gpu_test
    return self.codebase_class.single_gpu_test(model, data_loader, show,
  File "D:\mmdeploy-master\mmdeploy-master\mmdeploy\codebase\mmseg\deploy\mmsegmentation.py", line 146, in single_gpu_test
    outputs = single_gpu_test(
  File "d:\mmsegmentation-master\mmsegmentation-master\mmseg\apis\test.py", line 91, in single_gpu_test
    result = model(return_loss=False, **data)
  File "D:\software\Anaconda3\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\mmcv-master\mmcv\parallel\data_parallel.py", line 51, in forward
    return super().forward(*inputs, **kwargs)
  File "D:\software\Anaconda3\envs\mmdeploy\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\software\Anaconda3\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\mmdeploy-master\mmdeploy-master\mmdeploy\codebase\mmseg\deploy\segmentation_model.py", line 82, in forward
    outputs = self.forward_test(input_img, img_metas, *args, **kwargs)
  File "D:\mmdeploy-master\mmdeploy-master\mmdeploy\codebase\mmseg\deploy\segmentation_model.py", line 107, in forward_test
    outputs = self.wrapper({self.input_name: imgs})
  File "D:\software\Anaconda3\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\mmdeploy-master\mmdeploy-master\mmdeploy\backend\onnxruntime\wrapper.py", line 95, in forward
    self.__ort_execute(self.io_binding)
  File "D:\mmdeploy-master\mmdeploy-master\mmdeploy\utils\timer.py", line 61, in fun
    result = func(*args, **kwargs)
  File "D:\mmdeploy-master\mmdeploy-master\mmdeploy\backend\onnxruntime\wrapper.py", line 111, in __ort_execute
    self.sess.run_with_iobinding(io_binding)
  File "D:\software\Anaconda3\envs\mmdeploy\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 229, in run_with_iobinding
    self._sess.run_with_iobinding(iobinding._iobinding, run_options)
RuntimeError: Error in execution: Got invalid dimensions for input: input for the following indices
 index: 2 Got: 372 Expected: 512
 Please fix either the inputs or the model.

Process finished with exit code 1

`
>

**Comment by RunningLeon** [comment]
@fat-921 Hi, it worked fine on Linux. There might be something wrong with onnxruntime in your env. I found the most related issue is https://github.com/microsoft/onnxruntime/issues/3114. Maybe you could try turn down optimizations for ort.

**Comment by fat-921** [comment]
> @fat-921 Hi, it worked fine on Linux. There might be something wrong with onnxruntime in your env. I found the most related issue is [microsoft/onnxruntime#3114](https://github.com/microsoft/onnxruntime/issues/3114). Maybe you could try turn down optimizations for ort.

Hi,When I input the image size is 336x244, run `tools/test.py`, the data becomes `'ori_shape'=(244,336,3), 'img_shape'=(372, 512, 3), 'pad_shape'=(372, 512, 3)`, I don't know how these numbers change.

execute:
`python tools/test.py D:\mmdeploy-master\mmdeploy-master\configs\mmseg\segmentation_onnxruntime_static-512x512.py D:\mmsegmentation-master\mmsegmentation-master\configs\my_pspnet_config.py --model D:\tmp\fsr_ort_2\end2end.onnx --device cpu --show-dir D:\mmdeploy-master\mmdeploy-master\test_image\test1`


the error:

RuntimeError: Error in execution: Got invalid dimensions for input: input for the following indices
index: 2 Got: 372 Expected: 512
Please fix either the inputs or the model.

**Comment by fat-921** [comment]
> @fat-921 Hi, it worked fine on Linux. There might be something wrong with onnxruntime in your env. I found the most related issue is [microsoft/onnxruntime#3114](https://github.com/microsoft/onnxruntime/issues/3114). Maybe you could try turn down optimizations for ort.

Hi,When I input the image size is 336x244, run `tools/test.py`, the data becomes `'ori_shape'=(244,336,3), 'img_shape'=(372, 512, 3), 'pad_shape'=(372, 512, 3)`, I don't know how these numbers change.

execute:
`python tools/test.py D:\mmdeploy-master\mmdeploy-master\configs\mmseg\segmentation_onnxruntime_static-512x512.py D:\mmsegmentation-master\mmsegmentation-master\configs\my_pspnet_config.py --model D:\tmp\fsr_ort_2\end2end.onnx --device cpu --show-dir D:\mmdeploy-master\mmdeploy-master\test_image\test1`


the error:

RuntimeError: Error in execution: Got invalid dimensions for input: input for the following indices
index: 2 Got: 372 Expected: 512
Please fix either the inputs or the model.

**Comment by RunningLeon** [comment]
> 

@fat-921 Hi, pls. check your test_ pipeline in the config and make sure it gives a fixed shape tensor.

**Comment by fat-921** [comment]
> > 
> 
> @fat-921 Hi, pls. check your `test_ pipeline` in the config and make sure it gives a fixed shape tensor.
> 
> For [cityscapes](https://github.com/open-mmlab/mmsegmentation/blob/03c244769055b1a54b6a457d95268cad58734200/configs/_base_/datasets/cityscapes_832x832.py#L17, you have to modify to
> 
> ```
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(2048, 1024),
>         # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=False),
>             dict(type='RandomFlip'),
>             dict(type='Normalize', **img_norm_cfg),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img']),
>         ])
> ]
> ```

Thanks a lot，I modified the `test_ pipeline` ，take `keep_ratio=False` and updates onnxruntime to the latest version, mean `onnxruntime==1.12.0`. This solved my problem.

**Comment by RunningLeon** [comment]
Glad to know it solved.
