### ISSUE TITLE
Error Code 2: Internal Error (Assertion cublasStatus == CUBLAS_STATUS_SUCCESS failed. )

### ISSUE THREAD

**Issue by brilliant-soilder** [open-mmlab/mmdeploy#874]
When I convert .pth to .engine model on the windows10 system. It successfully converted .onnx, but failed trt ,with an error occured as "Error Code 2: Internal Error (Assertion cublasStatus == CUBLAS_STATUS_SUCCESS failed. )"

Here lays the error info for help:
(trt2) E:\mmdeploy\tools>python deploy.py E:\mmdeploy\configs\mmdet\instance-seg\instance-seg_tensorrt-fp16_dynamic-320x320-1344x1344_2.py E:\mmdetection-2.25.0\configs\mask_rcnn\mask_rcnn_x101_64x4d_fpn_mstrain-poly_3x_coco2.py E:\mmdetection-2.25.0\checkpoints\epoch_36.pth E:\mmdetection-2.25.0\demo\1\1_0050.bmp --work-dir E:\mmdeploy\work_dirs\640x256\30  --device cuda:0 --show --dump-info
[2022-08-08 09:35:43.971] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
[2022-08-08 09:35:45.757] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
e:\mmdetection-2.25.0\mmdet\datasets\utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
[2022-08-08 09:35:51.862] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
2022-08-08 09:35:51,863 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
load checkpoint from local path: E:\mmdetection-2.25.0\checkpoints\epoch_36.pth
e:\mmdetection-2.25.0\mmdet\datasets\utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
2022-08-08 09:35:57,871 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
2022-08-08 09:35:57,871 - mmdeploy - INFO - Export PyTorch model to ONNX: E:\mmdeploy\work_dirs\640x256\30\end2end.onnx.
2022-08-08 09:35:57,931 - mmdeploy - WARNING - Can not find torch._C._jit_pass_onnx_deduplicate_initializers, function rewrite will not be applied
e:\mmdeploy\mmdeploy\core\optimizers\function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
e:\mmdetection-2.25.0\mmdet\models\dense_heads\anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
e:\mmdetection-2.25.0\mmdet\core\anchor\anchor_generator.py:333: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors``
  warnings.warn('``grid_anchors`` would be deprecated soon. '
e:\mmdetection-2.25.0\mmdet\core\anchor\anchor_generator.py:369: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors``
  warnings.warn(
e:\mmdeploy\mmdeploy\codebase\mmdet\models\dense_heads\rpn_head.py:78: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
e:\mmdeploy\mmdeploy\pytorch\functions\topk.py:56: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k > size:
e:\mmdeploy\mmdeploy\codebase\mmdet\core\bbox\delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
e:\mmdeploy\mmdeploy\codebase\mmdet\core\bbox\delta_xywh_bbox_coder.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
e:\mmdeploy\mmdeploy\codebase\mmdet\core\post_processing\bbox_nms.py:259: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  dets, labels = TRTBatchedNMSop.apply(boxes, scores, int(scores.shape[-1]),
e:\mmdeploy\mmdeploy\mmcv\ops\nms.py:178: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out_boxes = min(num_boxes, after_topk)
F:\anaconda\anzhuangweizhi\envs\trt2\lib\site-packages\torch\onnx\symbolic_opset9.py:2603: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  warnings.warn("Exporting aten::index operator of advanced indexing in opset " +
2022-08-08 09:36:03,756 - mmdeploy - INFO - Execute onnx optimize passes.
2022-08-08 09:36:04,894 - mmdeploy - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
[2022-08-08 09:36:07.174] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
2022-08-08 09:36:07,171 - mmdeploy - INFO - Start pipeline mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt in subprocess
2022-08-08 09:36:08,167 - mmdeploy - INFO - Successfully loaded tensorrt plugins from e:\mmdeploy\mmdeploy\lib\mmdeploy_tensorrt_ops.dll
[08/08/2022-09:36:08] [TRT] [I] [MemUsageChange] Init CUDA: CPU +323, GPU +0, now: CPU 4890, GPU 886 (MiB)
[08/08/2022-09:36:08] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 4920 MiB, GPU 886 MiB
[08/08/2022-09:36:08] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 5015 MiB, GPU 922 MiB
[08/08/2022-09:36:09] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[08/08/2022-09:36:09] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[08/08/2022-09:36:11] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[08/08/2022-09:36:11] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace:
[08/08/2022-09:36:11] [TRT] [I] Successfully created plugin: TRTBatchedNMS
[08/08/2022-09:36:11] [TRT] [I] No importer registered for op: MMCVMultiLevelRoiAlign. Attempting to import as plugin.
[08/08/2022-09:36:11] [TRT] [I] Searching for plugin: MMCVMultiLevelRoiAlign, plugin_version: 1, plugin_namespace:
[08/08/2022-09:36:11] [TRT] [I] Successfully created plugin: MMCVMultiLevelRoiAlign
[08/08/2022-09:36:12] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
[08/08/2022-09:36:13] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[08/08/2022-09:36:13] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace:
[08/08/2022-09:36:13] [TRT] [I] Successfully created plugin: TRTBatchedNMS
[08/08/2022-09:36:13] [TRT] [I] No importer registered for op: MMCVMultiLevelRoiAlign. Attempting to import as plugin.
[08/08/2022-09:36:13] [TRT] [I] Searching for plugin: MMCVMultiLevelRoiAlign, plugin_version: 1, plugin_namespace:
[08/08/2022-09:36:13] [TRT] [I] Successfully created plugin: MMCVMultiLevelRoiAlign
[08/08/2022-09:36:13] [TRT] [W] Output type must be INT32 for shape outputs
[08/08/2022-09:36:13] [TRT] [W] Output type must be INT32 for shape outputs
[08/08/2022-09:36:14] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +180, GPU +70, now: CPU 5301, GPU 992 (MiB)
[08/08/2022-09:36:14] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +167, GPU +88, now: CPU 5468, GPU 1080 (MiB)
[08/08/2022-09:36:14] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[08/08/2022-09:37:14] [TRT] [I] Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[08/08/2022-09:41:07] [TRT] [E] 2: [ltWrapper.cpp::nvinfer1::rt::CublasLtWrapper::setupHeuristic::327] Error Code 2: Internal Error (Assertion cublasStatus == CUBLAS_STATUS_SUCCESS failed. )
Process Process-3:
Traceback (most recent call last):
  File "F:\anaconda\anzhuangweizhi\envs\trt2\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "F:\anaconda\anzhuangweizhi\envs\trt2\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "e:\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "e:\mmdeploy\mmdeploy\backend\tensorrt\onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "e:\mmdeploy\mmdeploy\backend\tensorrt\utils.py", line 154, in from_onnx
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine
2022-08-08 09:41:08,084 - mmdeploy - ERROR - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed. exit.

**Comment by brilliant-soilder** [comment]
(trt2) E:\mmdeploy\tools>python check_env.py
2022-08-08 09:42:29,467 - mmdeploy - INFO -

2022-08-08 09:42:29,467 - mmdeploy - INFO - **********Environmental information**********
'tail' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2022-08-08 09:42:32,010 - mmdeploy - INFO - sys.platform: win32
2022-08-08 09:42:32,010 - mmdeploy - INFO - Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
2022-08-08 09:42:32,010 - mmdeploy - INFO - CUDA available: True
2022-08-08 09:42:32,010 - mmdeploy - INFO - GPU 0: GeForce GTX 1650
2022-08-08 09:42:32,010 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
2022-08-08 09:42:32,010 - mmdeploy - INFO - NVCC: Not Available
2022-08-08 09:42:32,020 - mmdeploy - INFO - GCC: n/a
2022-08-08 09:42:32,020 - mmdeploy - INFO - PyTorch: 1.8.0
2022-08-08 09:42:32,020 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

2022-08-08 09:42:32,020 - mmdeploy - INFO - TorchVision: 0.9.0
2022-08-08 09:42:32,020 - mmdeploy - INFO - OpenCV: 4.6.0
2022-08-08 09:42:32,020 - mmdeploy - INFO - MMCV: 1.4.0
2022-08-08 09:42:32,020 - mmdeploy - INFO - MMCV Compiler: MSVC 192930145
2022-08-08 09:42:32,020 - mmdeploy - INFO - MMCV CUDA Compiler: 10.2
2022-08-08 09:42:32,020 - mmdeploy - INFO - MMDeploy: 0.6.0+a15365e
2022-08-08 09:42:32,020 - mmdeploy - INFO -

2022-08-08 09:42:32,020 - mmdeploy - INFO - **********Backend information**********
2022-08-08 09:42:33,235 - mmdeploy - INFO - onnxruntime: 1.8.1  ops_is_avaliable : True
2022-08-08 09:42:33,263 - mmdeploy - INFO - tensorrt: 8.2.3.0   ops_is_avaliable : True
2022-08-08 09:42:33,295 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-08-08 09:42:33,295 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-08-08 09:42:33,295 - mmdeploy - INFO - openvino_is_avaliable: False
2022-08-08 09:42:33,343 - mmdeploy - INFO - snpe_is_available: False
2022-08-08 09:42:33,343 - mmdeploy - INFO -

2022-08-08 09:42:33,345 - mmdeploy - INFO - **********Codebase information**********
2022-08-08 09:42:33,353 - mmdeploy - INFO - mmdet:      2.25.0
2022-08-08 09:42:33,353 - mmdeploy - INFO - mmseg:      None
2022-08-08 09:42:33,353 - mmdeploy - INFO - mmcls:      None
2022-08-08 09:42:33,353 - mmdeploy - INFO - mmocr:      None
2022-08-08 09:42:33,353 - mmdeploy - INFO - mmedit:     None
2022-08-08 09:42:33,363 - mmdeploy - INFO - mmdet3d:    None
2022-08-08 09:42:33,363 - mmdeploy - INFO - mmpose:     None
2022-08-08 09:42:33,365 - mmdeploy - INFO - mmrotate:   None

**Comment by irexyc** [comment]
Can you try to set config according to https://github.com/open-mmlab/mmdeploy/issues/261

**Comment by brilliant-soilder** [comment]
> Can you try to set config according to #261

Success. It works with your suggestion. But some guys runs successfully whther with this option <<"Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output">> and shows no error . SO why is this happened to mine, is it a reason because mmdeploy's version?

**Comment by irexyc** [comment]
The problem is due to the cuda version. If you use cuda11+, you won't meet ` (Assertion cublasStatus == CUBLAS_STATUS_SUCCESS failed. )`

**Comment by dpakprajul** [comment]
> The problem is due to the cuda version. If you use cuda11+, you won't meet ` (Assertion cublasStatus == CUBLAS_STATUS_SUCCESS failed. )`

What can I do if I am using cuda11+? Would you suggest to degrade it? This is working fine when I am using mmdeploy for detection/config/swin and detectoin/config/yolox but stucked in pvt (used int8 config for deployment)
Here is my error message along with my environment:
[11/22/2022-14:23:17] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.
[11/22/2022-14:23:17] [TRT] [E] 2: [ltWrapper.cpp::setupHeuristic::349] Error Code 2: Internal Error (Assertion cublasStatus == CUBLAS_STATUS_SUCCESS failed. )
Process Process-4:
Traceback (most recent call last):
  File "/home/dee08770/anaconda3/envs/mmdeploy/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dee08770/anaconda3/envs/mmdeploy/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dee08770/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/dee08770/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "/home/dee08770/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/utils.py", line 215, in from_onnx
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine
2022-11-22 14:23:18,895 - mmdeploy - ERROR - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 2 failed. exit.
(mmdeploy) dee08770@dione:~/mmdetection$ cd ..
(mmdeploy) dee08770@dione:~$ cd mmdeploy
(mmdeploy) dee08770@dione:~/mmdeploy$ cd tools/
(mmdeploy) dee08770@dione:~/mmdeploy/tools$ python check_env.py
2022-11-22 14:25:21,319 - mmdeploy - INFO - 

2022-11-22 14:25:21,319 - mmdeploy - INFO - **********Environmental information**********
2022-11-22 14:25:22,176 - mmdeploy - INFO - sys.platform: linux
2022-11-22 14:25:22,176 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
2022-11-22 14:25:22,176 - mmdeploy - INFO - CUDA available: True
2022-11-22 14:25:22,176 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 2060
2022-11-22 14:25:22,176 - mmdeploy - INFO - CUDA_HOME: /home/dee08770/anaconda3/envs/mmdeploy
2022-11-22 14:25:22,176 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.122
2022-11-22 14:25:22,176 - mmdeploy - INFO - GCC: gcc (Debian 10.2.1-6) 10.2.1 20210110
2022-11-22 14:25:22,176 - mmdeploy - INFO - PyTorch: 1.12.1
2022-11-22 14:25:22,176 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

2022-11-22 14:25:22,176 - mmdeploy - INFO - TorchVision: 0.13.1
2022-11-22 14:25:22,176 - mmdeploy - INFO - OpenCV: 4.6.0
2022-11-22 14:25:22,176 - mmdeploy - INFO - MMCV: 1.6.2
2022-11-22 14:25:22,176 - mmdeploy - INFO - MMCV Compiler: GCC 9.3
2022-11-22 14:25:22,176 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2022-11-22 14:25:22,176 - mmdeploy - INFO - MMDeploy: 0.9.0+917643f
2022-11-22 14:25:22,176 - mmdeploy - INFO - 

2022-11-22 14:25:22,176 - mmdeploy - INFO - **********Backend information**********
2022-11-22 14:25:23,248 - mmdeploy - INFO - onnxruntime: None   ops_is_avaliable : False
2022-11-22 14:25:23,272 - mmdeploy - INFO - tensorrt: 8.4.1.5   ops_is_avaliable : True
2022-11-22 14:25:23,378 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-11-22 14:25:23,412 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-11-22 14:25:23,460 - mmdeploy - INFO - openvino_is_avaliable: False
2022-11-22 14:25:23,567 - mmdeploy - INFO - snpe_is_available: False
2022-11-22 14:25:23,611 - mmdeploy - INFO - ascend_is_available: False
2022-11-22 14:25:23,641 - mmdeploy - INFO - coreml_is_available: False
2022-11-22 14:25:23,641 - mmdeploy - INFO -
