### ISSUE TITLE
something wrong with segmentation turn onnx and tensorrt

### ISSUE THREAD

**Issue by Nuralill** [open-mmlab/mmdeploy#877]
**Checklist**

I have searched related issues but cannot get the expected help.
I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
The bug has not been fixed in the latest version.
**Describe the bug**

Reproduction

**What command or script did you run?**
`python tools/deploy.py configs/mmseg/segmentation_tensorrt_static-1024x2048.py ../mmsegmentation-master/configs/bisenetv2/bisenetv2_fcn_4x4_1024x1024_160k_cityscapes.py ../mmsegmentation-master/checkpoints/bisenetv2/latest.pth ../mmsegmentation-master/workplace/demo/1.jpg --work-dir ../mmdeploy_out/mmseg/bisenetv2/test/ --device cuda:0 --dump-info`

**Did you make any modifications on the code or config? Did you understand what you have modified?**
I just change the code which relate with my own dataset. 

**Please run python tools/check_env.py to collect necessary environment information and paste it here.**
I think my env has no error,becase I tried fasterrcnn could run succesfully.
```
(mmdet) E:\PycharmProjects\mmdeploy-master>python tools/check_env.py
2022-08-08 16:25:24,121 - mmdeploy - INFO -

2022-08-08 16:25:24,121 - mmdeploy - INFO - **********Environmental information**********
fatal: not a git repository (or any of the parent directories): .git
2022-08-08 16:25:29,013 - mmdeploy - INFO - sys.platform: win32
2022-08-08 16:25:29,014 - mmdeploy - INFO - Python: 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
2022-08-08 16:25:29,014 - mmdeploy - INFO - CUDA available: True
2022-08-08 16:25:29,014 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3060
2022-08-08 16:25:29,014 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
2022-08-08 16:25:29,014 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.58
2022-08-08 16:25:29,014 - mmdeploy - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30146 版
2022-08-08 16:25:29,015 - mmdeploy - INFO - GCC: n/a
2022-08-08 16:25:29,015 - mmdeploy - INFO - PyTorch: 1.10.0+cu113
2022-08-08 16:25:29,015 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/w/b/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

2022-08-08 16:25:29,016 - mmdeploy - INFO - TorchVision: 0.11.0+cu113
2022-08-08 16:25:29,016 - mmdeploy - INFO - OpenCV: 4.6.0
2022-08-08 16:25:29,017 - mmdeploy - INFO - MMCV: 1.6.1
2022-08-08 16:25:29,017 - mmdeploy - INFO - MMCV Compiler: MSVC 192930140
2022-08-08 16:25:29,018 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2022-08-08 16:25:29,018 - mmdeploy - INFO - MMDeploy: 0.6.0+
2022-08-08 16:25:29,023 - mmdeploy - INFO -

2022-08-08 16:25:29,024 - mmdeploy - INFO - **********Backend information**********
2022-08-08 16:25:29,716 - mmdeploy - INFO - onnxruntime: 1.8.1  ops_is_avaliable : False
2022-08-08 16:25:29,775 - mmdeploy - INFO - tensorrt: 8.4.1.5   ops_is_avaliable : True
2022-08-08 16:25:29,901 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-08-08 16:25:29,906 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-08-08 16:25:29,910 - mmdeploy - INFO - openvino_is_avaliable: False
2022-08-08 16:25:30,044 - mmdeploy - INFO - snpe_is_available: False
2022-08-08 16:25:30,045 - mmdeploy - INFO -

2022-08-08 16:25:30,046 - mmdeploy - INFO - **********Codebase information**********
2022-08-08 16:25:30,075 - mmdeploy - INFO - mmdet:      2.25.1
2022-08-08 16:25:30,075 - mmdeploy - INFO - mmseg:      0.27.0
2022-08-08 16:25:30,076 - mmdeploy - INFO - mmcls:      0.23.2
2022-08-08 16:25:30,076 - mmdeploy - INFO - mmocr:      None
2022-08-08 16:25:30,076 - mmdeploy - INFO - mmedit:     None
2022-08-08 16:25:30,077 - mmdeploy - INFO - mmdet3d:    None
2022-08-08 16:25:30,078 - mmdeploy - INFO - mmpose:     None
2022-08-08 16:25:30,078 - mmdeploy - INFO - mmrotate:   None

```
**error:**

```
load checkpoint from local path: ../mmsegmentation-master/checkpoints/bisenetv2/latest.pth
2022-08-08 15:52:33,291 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
2022-08-08 15:52:33,292 - mmdeploy - INFO - Export PyTorch model to ONNX: ../mmdeploy_out/mmseg/bisenetv2/test/end2end.onnx.
2022-08-08 15:52:33,395 - mmdeploy - WARNING - Can not find torch._C._jit_pass_onnx_deduplicate_initializers, function rewrite will not be applied
e:\pycharmprojects\mmdeploy-master\mmdeploy\codebase\mmseg\models\segmentors\base.py:39: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  img_shape = [int(val) for val in img_shape]
2022-08-08 15:52:40,921 - mmdeploy - INFO - Execute onnx optimize passes.
2022-08-08 15:52:41,113 - mmdeploy - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
2022-08-08 15:52:46,085 - mmdeploy - INFO - Start pipeline mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt in subprocess
2022-08-08 15:52:46,647 - mmdeploy - INFO - Successfully loaded tensorrt plugins from e:\pycharmprojects\mmdeploy-master\mmdeploy\lib\mmdeploy_tensorrt_ops.dll
[08/08/2022-15:52:50] [TRT] [I] [MemUsageChange] Init CUDA: CPU +301, GPU +0, now: CPU 12366, GPU 1300 (MiB)
[08/08/2022-15:52:56] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +215, GPU +190, now: CPU 12687, GPU 1469 (MiB)
[08/08/2022-15:52:56] [TRT] [W] onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[08/08/2022-15:52:56] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
[08/08/2022-15:52:58] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +800, GPU +473, now: CPU 13381, GPU 1981 (MiB)
[08/08/2022-15:53:01] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +143, GPU +570, now: CPU 13525, GPU 2551 (MiB)
[08/08/2022-15:53:01] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.2.0
[08/08/2022-15:53:01] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[08/08/2022-15:53:14] [TRT] [I] Some tactics do not have sufficient workspace memory to run. Increasing workspace size will enable more tactics, please check verbose output for requested sizes.
[08/08/2022-15:56:06] [TRT] [I] Detected 1 inputs and 1 output network tensors.
[08/08/2022-15:56:08] [TRT] [I] Total Host Persistent Memory: 74480
[08/08/2022-15:56:08] [TRT] [I] Total Device Persistent Memory: 9247744
[08/08/2022-15:56:08] [TRT] [I] Total Scratch Memory: 159383552
[08/08/2022-15:56:08] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 4 MiB, GPU 707 MiB
[08/08/2022-15:56:08] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 8.3212ms to assign 6 blocks to 76 nodes requiring 506462208 bytes.
[08/08/2022-15:56:08] [TRT] [I] Total Activation Memory: 506462208
[08/08/2022-15:56:08] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 15406, GPU 2214 (MiB)
[08/08/2022-15:56:08] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.2.0
[08/08/2022-15:56:08] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +0, GPU +25, now: CPU 0, GPU 25 (MiB)
[08/08/2022-15:56:08] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
[08/08/2022-15:56:08] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
2022-08-08 15:56:08,619 - mmdeploy - INFO - Finish pipeline mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt
2022-08-08 15:56:10,357 - mmdeploy - INFO - visualize tensorrt model start.
2022-08-08 15:56:15,677 - mmdeploy - INFO - Successfully loaded tensorrt plugins from e:\pycharmprojects\mmdeploy-master\mmdeploy\lib\mmdeploy_tensorrt_ops.dll
2022-08-08:15:56:15 - mmdeploy - INFO - Successfully loaded tensorrt plugins from e:\pycharmprojects\mmdeploy-master\mmdeploy\lib\mmdeploy_tensorrt_ops.dll
2022-08-08 15:56:15,679 - mmdeploy - INFO - Successfully loaded tensorrt plugins from e:\pycharmprojects\mmdeploy-master\mmdeploy\lib\mmdeploy_tensorrt_ops.dll
2022-08-08:15:56:15 - mmdeploy - INFO - Successfully loaded tensorrt plugins from e:\pycharmprojects\mmdeploy-master\mmdeploy\lib\mmdeploy_tensorrt_ops.dll
[08/08/2022-15:56:24] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.2.0
[08/08/2022-15:56:24] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.2.0
2022-08-08:15:56:29 - root - ERROR -
Traceback (most recent call last):
  File "e:\pycharmprojects\mmdeploy-master\mmdeploy\utils\utils.py", line 41, in target_wrapper
    result = target(*args, **kwargs)
  File "e:\pycharmprojects\mmdeploy-master\mmdeploy\apis\visualize.py", line 80, in visualize_model
    show_result=show_result)
  File "e:\pycharmprojects\mmdeploy-master\mmdeploy\codebase\mmseg\deploy\segmentation.py", line 177, in visualize
    opacity=opacity)
  File "e:\pycharmprojects\mmdeploy-master\mmdeploy\codebase\mmseg\deploy\segmentation_model.py", line 147, in show_result
    out_file=out_file)
  File "e:\pycharmprojects\mmsegmentation-master\mmseg\models\segmentors\base.py", line 267, in show_result
    assert palette.shape[0] == len(self.CLASSES)
AssertionError
2022-08-08 15:56:30,977 - mmdeploy - ERROR - visualize tensorrt model failed.
```

**Comment by RunningLeon** [comment]
@Nuralill Hi, for your custom dataset, pls update `CLASSES` and `PALETTE` just like [CityscapesDataset](https://github.com/open-mmlab/mmsegmentation/blob/4eaa8e69191cc293b64dafe47f1f88a7d468c93c/mmseg/datasets/cityscapes.py#L21).
```
@DATASETS.register_module()
class CityscapesDataset(CustomDataset):
    """Cityscapes dataset.
    The ``img_suffix`` is fixed to '_leftImg8bit.png' and ``seg_map_suffix`` is
    fixed to '_gtFine_labelTrainIds.png' for Cityscapes dataset.
    """

    CLASSES = ('road', 'sidewalk', 'building', 'wall', 'fence', 'pole',
               'traffic light', 'traffic sign', 'vegetation', 'terrain', 'sky',
               'person', 'rider', 'car', 'truck', 'bus', 'train', 'motorcycle',
               'bicycle')

    PALETTE = [[128, 64, 128], [244, 35, 232], [70, 70, 70], [102, 102, 156],
               [190, 153, 153], [153, 153, 153], [250, 170, 30], [220, 220, 0],
               [107, 142, 35], [152, 251, 152], [70, 130, 180], [220, 20, 60],
               [255, 0, 0], [0, 0, 142], [0, 0, 70], [0, 60, 100],
               [0, 80, 100], [0, 0, 230], [119, 11, 32]]

```

**Comment by Nuralill** [comment]
Thank you so much ,I found I missed a comma in Classes.

**Comment by RunningLeon** [comment]
No problem. Glad to know it solved.
