### ISSUE TITLE
ImportError: cannot import name '_get_tensor_dim_size'

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmdeploy#88]
Thanks for your bug report. We appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```
[2022-01-19T07:54:57.643Z] Removing intermediate container 1dac7717b7f9

[2022-01-19T07:54:57.643Z]  ---> 1153d2075ef3

[2022-01-19T07:54:57.643Z] Step 17/17 : RUN python3 tools/check_env.py

[2022-01-19T07:54:57.911Z]  ---> Running in ed13e71986f7

[2022-01-19T07:55:01.230Z] Traceback (most recent call last):

[2022-01-19T07:55:01.231Z]   File "tools/check_env.py", line 5, in <module>

[2022-01-19T07:55:01.231Z]     import mmdeploy

[2022-01-19T07:55:01.231Z]   File "/opt/mmdeploy/mmdeploy/__init__.py", line 7, in <module>

[2022-01-19T07:55:01.231Z]     importlib.import_module('mmdeploy.pytorch')

[2022-01-19T07:55:01.231Z]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module

[2022-01-19T07:55:01.231Z]     return _bootstrap._gcd_import(name[level:], package, level)

[2022-01-19T07:55:01.231Z]   File "/opt/mmdeploy/mmdeploy/pytorch/__init__.py", line 3, in <module>

[2022-01-19T07:55:01.231Z]     from .ops import *  # noqa: F401,F403

[2022-01-19T07:55:01.231Z]   File "/opt/mmdeploy/mmdeploy/pytorch/ops/__init__.py", line 6, in <module>

[2022-01-19T07:55:01.231Z]     from .instance_norm import instance_norm__tensorrt

[2022-01-19T07:55:01.231Z]   File "/opt/mmdeploy/mmdeploy/pytorch/ops/instance_norm.py", line 6, in <module>

[2022-01-19T07:55:01.231Z]     from torch.onnx.symbolic_helper import (_get_tensor_dim_size, _get_tensor_rank,

[2022-01-19T07:55:01.231Z] ImportError: cannot import name '_get_tensor_dim_size'

[2022-01-19T07:55:01.808Z] The command '/bin/sh -c python3 tools/check_env.py' returned a non-zero code: 1

```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

**Environment**

```
docker build -t mmdeploy_ubuntu_1804_py_37_torch_160_ort_master:20220119 --build-arg IMAGE=ubuntu_1804_py_37_torch_160 --build-arg BACKEND=ort --build-arg TAG=v1 --
```

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by RunningLeon** [comment]
@del-zhenwu What is your version of torch?

**Comment by del-zhenwu** [comment]
mmdeploy_ubuntu_1804_py_37_torch_160_ort_master

**Comment by RunningLeon** [comment]
@del-zhenwu Please install torch>=1.8.0
https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/build.md#create-environment
