### ISSUE TITLE
 SDK deployment problem

### ISSUE THREAD

**Issue by x12901** [open-mmlab/mmdeploy#891]
I try to deploy c++ under win10,but i got the error.I have two cuda 10.0 and 11.6 on my computer, and I trained with 10.0. 
my conversion command:
`python ./tools/deploy.py configs/mmdet/instance-seg/instance-seg_tensorrt-int8_dynamic-320x320-1344x1344.py F:/CODE/mmdetection-master/configs/mask_rcnn/mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_f.py F:/CODE/mmdetection-master/work_dirs/mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_f/epoch_40.pth F:/CODE/mmdetection-master/data/labelme-bg/99.jpg --work-dir work_dir --show --device cuda:0 --dump-info`
The trained model can be tested for performance
`python tools/test.py configs/mmdet/instance-seg/instance-seg_tensorrt-int8_dynamic-320x320-1344x1344.py  F:/CODE/mmdetection-master/configs/mask_rcnn/mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_f.py  --model work_dir/end2end.engine --speed-test --device cuda:0`
Training commands
 `python tools/train.py configs/mask_rcnn/mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_fxn.py --auto-scale-lr`
CUDA:11.6 
CUDNN:8.4.1.50
TensorRT:8.2.3.0
CMAKE:3.23.1
VS2022
```
F:\CODE\mmdeploy\build\bin\Release>F:\CODE\mmdeploy\build\bin\Release\object_detection.exe cuda  F:\CODE\mmdeploy\work_dir\  F:/CODE/mmdetection-master/data/labelme-bg/99.jpg
loading mmdeploy_execution ...
loading mmdeploy_cpu_device ...
loading mmdeploy_cuda_device ...
loading mmdeploy_graph ...
loading mmdeploy_directory_model ...
[2022-08-12 12:27:53.870] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
loading mmdeploy_transform ...
loading mmdeploy_cpu_transform_impl ...
loading mmdeploy_cuda_transform_impl ...
loading mmdeploy_transform_module ...
loading mmdeploy_net_module ...
loading mmdeploy_mmcls ...
loading mmdeploy_mmdet ...
loading mmdeploy_mmseg ...
loading mmdeploy_mmocr ...
loading mmdeploy_mmedit ...
loading mmdeploy_mmpose ...
loading mmdeploy_mmrotate ...
[2022-08-12 12:27:53.903] [mmdeploy] [info] [model.cpp:38] DirectoryModel successfully load model F:\CODE\mmdeploy\work_dir\
[2022-08-12 12:27:53.977] [mmdeploy] [error] [net_module.cpp:38] Net backend not found: tensorrt, available backends: []
[2022-08-12 12:27:53.978] [mmdeploy] [error] [task.cpp:67] error parsing config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "module": "Net",
  "name": "maskrcnn",
  "output": [
    "infer_output"
  ],
  "type": "Task"
}
[2022-08-12 12:27:53.979] [mmdeploy] [error] [pipeline.cpp:145] Could not create Task: maskrcnn
[2022-08-12 12:27:53.980] [mmdeploy] [error] [pipeline.cpp:159] error parsing config: unknown (6)
[2022-08-12 12:27:53.981] [mmdeploy] [error] [handle.h:31] Failed to create pipeline, config: {
  "context": {
    "device": "<any>",
    "stream": "<any>"
  },
  "pipeline": {
    "input": [
      "image"
    ],
    "output": [
      "det"
    ],
    "tasks": [
      {
        "input": [
          "image"
        ],
        "name": "mmdetection",
        "output": [
          "det"
        ],
        "params": {
          "model": "<any>"
        },
        "type": "Inference"
      }
    ]
  }
}
[2022-08-12 12:27:53.981] [mmdeploy] [error] [pipeline.cpp:27] exception caught: unknown (6)
failed to create detector, code: 6
```
python also has problems
```
(mmdeploy) PS F:\CODE\mmdeploy> python F:\CODE\mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0\sdk\example\python\image_segmentation.py cuda F:\CODE\mmdeploy\work_dir\end2end.engine F:/CODE/mmdetection-master/data/labelme-bg/99.jpg
[2022-08-12 12:46:01.529] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
[2022-08-12 12:46:01.539] [mmdeploy] [error] [model.cpp:44] no ModelImpl can read model F:\CODE\mmdeploy\work_dir\end2end.engine
[2022-08-12 12:46:01.539] [mmdeploy] [error] [model.cpp:15] load model failed. Its file path is 'F:\CODE\mmdeploy\work_dir\end2end.engine'
[2022-08-12 12:46:01.540] [mmdeploy] [error] [model.cpp:20] failed to create model: not supported (2)
Traceback (most recent call last):
  File "F:\CODE\mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0\sdk\example\python\image_segmentation.py", line 52, in <module>
    main()
  File "F:\CODE\mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0\sdk\example\python\image_segmentation.py", line 35, in main
    segmentor = Segmentor(
RuntimeError: failed to create segmentor
```

```
(mmdeploy) PS F:\CODE\mmdeploy> pip list
Package            Version   Editable project location
------------------ --------- --------------------------
addict             2.4.0
appdirs            1.4.4
brotlipy           0.7.0
certifi            2022.6.15
cffi               1.15.1
charset-normalizer 2.1.0
click              8.1.3
colorama           0.4.5
commonmark         0.9.1
cryptography       37.0.4
cycler             0.11.0
dill               0.3.5.1
flatbuffers        2.0
fonttools          4.34.4
graphsurgeon       0.4.5
grpcio             1.47.0
h5py               3.7.0
idna               3.3
importlib-metadata 4.12.0
kiwisolver         1.4.4
Mako               1.2.1
Markdown           3.4.1
MarkupSafe         2.1.1
matplotlib         3.5.2
mmcv-full          1.6.1
mmdeploy           0.7.0
mmdeploy-python    0.7.0
mmdet              2.25.1    f:\code\mmdetection-master
model-index        0.1.11
multiprocess       0.70.13
numpy              1.23.1
onnx               1.12.0
onnx-graphsurgeon  0.3.12
onnxruntime        1.8.1
opencv-python      4.6.0.66
openmim            0.2.0
ordered-set        4.1.0
packaging          21.3
pandas             1.4.3
Pillow             9.2.0
pip                22.1.2
platformdirs       2.5.2
protobuf           3.20.1
pycocotools        2.0.4
pycparser          2.21
pycuda             2022.1
Pygments           2.12.0
pyOpenSSL          22.0.0
pyparsing          3.0.9
PySocks            1.7.1
python-dateutil    2.8.2
pytools            2022.1.12
pytz               2022.1
PyYAML             6.0
regex              2022.7.9
requests           2.28.1
rich               12.5.1
setuptools         61.2.0
six                1.16.0
tabulate           0.8.10
tensorrt           8.2.3.0
terminaltables     3.1.10
torch              1.12.1
torchaudio         0.12.1
torchvision        0.13.1
tqdm               4.64.0
typing_extensions  4.3.0
uff                0.6.9
urllib3            1.26.11
wheel              0.37.1
win-inet-pton      1.1.0
wincertstore       0.2
yapf               0.32.0
zipp               3.8.1
```

```
(openmmlab) PS F:\CODE\mmdetection-master> pip list
Package            Version   Editable project location
------------------ --------- --------------------------
addict             2.4.0
certifi            2022.6.15
charset-normalizer 2.1.0
click              8.1.3
colorama           0.4.5
commonmark         0.9.1
cycler             0.11.0
Cython             0.29.30
flatbuffers        2.0
fonttools          4.34.4
idna               3.3
importlib-metadata 4.12.0
install            1.3.5
kiwisolver         1.4.4
Markdown           3.4.1
matplotlib         3.5.2
mkl-fft            1.3.1
mkl-random         1.2.2
mkl-service        2.4.0
mmcv-full          1.6.1
mmdet              2.25.1    f:\code\mmdetection-master
model-index        0.1.11
numpy              1.21.5
onnx               1.12.0
onnxruntime        1.8.1
opencv-python      4.6.0.66
openmim            0.2.0
ordered-set        4.1.0
packaging          21.3
pandas             1.3.5
Pillow             9.2.0
pip                22.1.2
protobuf           3.20.1
pycocotools        2.0.4
Pygments           2.12.0
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2022.1
PyYAML             6.0
regex              2022.7.9
requests           2.28.1
rich               12.5.1
setuptools         61.2.0
six                1.16.0
tabulate           0.8.10
terminaltables     3.1.10
torch              1.6.0
torchvision        0.7.0
typing_extensions  4.3.0
urllib3            1.26.10
wheel              0.37.1
wincertstore       0.2
yapf               0.32.0
zipp               3.8.1
```

**Comment by irexyc** [comment]
For python code, the model path should be a directory. So, the right command should be:
```
(mmdeploy) PS F:\CODE\mmdeploy> python F:\CODE\mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0\sdk\example\python\image_segmentation.py cuda F:\CODE\mmdeploy\work_dir\ F:/CODE/mmdetection-master/data/labelme-bg/99.jpg
```

For cpp code, it seem you didn't build trt backend. Because there isn't exists `loading  mmdeploy_trt_net ...` in your log. You can provide your build command. 

We also provide prebuilt exe in our release package. You can also try to use it and check if still has errors.

**Comment by x12901** [comment]
> For python code, the model path should be a directory. So, the right command should be:
> 
> ```
> (mmdeploy) PS F:\CODE\mmdeploy> python F:\CODE\mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0\sdk\example\python\image_segmentation.py cuda F:\CODE\mmdeploy\work_dir\ F:/CODE/mmdetection-master/data/labelme-bg/99.jpg
> ```
> 
> For cpp code, it seem you didn't build trt backend. Because there isn't exists `loading mmdeploy_trt_net ...` in your log. You can provide your build command.
> 
> We also provide prebuilt exe in our release package. You can also try to use it and check if still has errors.

Thanks for your help. I am using the release package , it is working now.
