### ISSUE TITLE
mmdet3d pointpillar  onnx2tensorrt RuntimeError: Failed to parse onnx, In node 72 (parseGraph): INVALID_NODE: Invalid Node - Concat_72

### ISSUE THREAD

**Issue by yangyangsu29** [open-mmlab/mmdeploy#893]
env is build with the master's docker/GPU/Dockerfile

python tools/deploy.py \
configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-kitti-32x4.py \
../mmdetection3d/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py \
./checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth \
../mmdetection3d/demo/data/kitti/kitti_000008.bin \
--work-dir work-dirs/mmdet3d/pointpillars/trt  \
--device cuda:7

2022-08-12 07:46:25,793 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
/root/workspace/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py:84: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  warnings.warn(
load checkpoint from local path: ./checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth
2022-08-12 07:46:33,878 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-08-12 07:46:33,878 - mmdeploy - INFO - Export PyTorch model to ONNX: work-dirs/mmdet3d/pointpillars/trt/end2end.onnx.
2022-08-12 07:46:34,016 - mmdeploy - WARNING - Can not find torch._C._jit_pass_onnx_deduplicate_initializers, function rewrite will not be applied
/root/workspace/mmdeploy/mmdeploy/codebase/mmdet3d/models/pillar_encode.py:41: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  f_center = features[..., :3] - (coors[..., 1:] * torch.tensor(
/root/workspace/mmdeploy/mmdeploy/codebase/mmdet3d/models/pillar_encode.py:42: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  [self.vz, self.vy, self.vx]).to(device) + torch.tensor([
/root/workspace/mmdeploy/mmdeploy/codebase/mmdet3d/models/voxelnet.py:53: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert batch_size == 1
2022-08-12 07:46:36,991 - mmdeploy - INFO - Execute onnx optimize passes.
2022-08-12 07:46:38,153 - mmdeploy - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
2022-08-12 07:46:43,608 - mmdeploy - INFO - Start pipeline mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt in subprocess
2022-08-12 07:46:43,974 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /root/workspace/mmdeploy/build/lib/libmmdeploy_tensorrt_ops.so
[08/12/2022-07:46:44] [TRT] [I] [MemUsageChange] Init CUDA: CPU +253, GPU +0, now: CPU 346, GPU 492 (MiB)
[08/12/2022-07:46:44] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 346 MiB, GPU 492 MiB
[08/12/2022-07:46:45] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 457 MiB, GPU 516 MiB
[08/12/2022-07:46:45] [TRT] [W] parsers/onnx/onnx2trt_utils.cpp:364: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[08/12/2022-07:46:45] [TRT] [W] parsers/onnx/onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[08/12/2022-07:46:45] [TRT] [W] parsers/onnx/onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[08/12/2022-07:46:45] [TRT] [E] [graphShapeAnalyzer.cpp::computeOutputExtents::1026] Error Code 4: Miscellaneous (Concat_72: error while computing output extent)
Process Process-3:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "/root/workspace/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 113, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 72 (parseGraph): INVALID_NODE: Invalid Node - Concat_72
[graphShapeAnalyzer.cpp::computeOutputExtents::1026] Error Code 4: Miscellaneous (Concat_72: error while computing output extent)

2022-08-12 07:46:46,629 - mmdeploy - ERROR - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed. exit.

**Comment by RunningLeon** [comment]
same issue with #876

**Comment by RunningLeon** [comment]
@yangyangsu29 Hi, may close it and discuss in https://github.com/open-mmlab/mmdeploy/issues/876
