### ISSUE TITLE
ImportError: mmdet has not been installed. Import mmdeploy.codebase.mmdet failed

### ISSUE THREAD

**Issue by huyuanchao** [open-mmlab/mmdeploy#894]
2022-08-12 07:52:25,383 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
mmdet
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 60, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/root/workspace/mmdeploy/mmdeploy/apis/utils/utils.py", line 22, in build_task_processor
    import_codebase(codebase_type)
  File "/root/workspace/mmdeploy/mmdeploy/codebase/__init__.py", line 32, in import_codebase
    raise ImportError(
ImportError: mmdet has not been installed. Import mmdeploy.codebase.mmdet failed.

**Comment by RunningLeon** [comment]
@huyuanchao Hi,
if you want to convert models from [mmdetection](https://github.com/open-mmlab/mmdeploy), you have to install mmdetection: https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md/#Installation
