### ISSUE TITLE
onnx2tensorrt model_params = get_model_inputs(deploy_cfg)[model_id]  IndexError: list index out of range

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdeploy#932]
```
anaconda  python 3.7 
mmcls                  0.23.2
mmcv-full              1.6.1
mmdeploy               0.7.0
mmdet                  2.25.1
model-index            0.1.11
multiprocess           0.70.13
numpy                  1.21.6
onnx                   1.12.0
onnxruntime            1.8.1
tensorrt               8.2.3.0
```
```
# https://github.com/open-mmlab/mmdeploy/blob/master/docs/zh_cn/02-how-to-run/prebuilt_package_windows.md

from mmdeploy.apis import torch2onnx
from mmdeploy.apis.tensorrt import onnx2tensorrt
from mmdeploy.backend.sdk.export_info import export2SDK
import os

img = 'mmclassification/demo/demo.JPEG'
work_dir = 'work_dir/trt/resnet'
save_file = 'end2end.onnx'
deploy_cfg = 'mmdeploy/configs/mmcls/classification_tensorrt_static-224x224.py'
model_cfg = 'mmclassification/configs/resnet/resnet18_8xb32_in1k.py'
model_checkpoint = 'resnet18_8xb32_in1k_20210831-fbbb1da6.pth'
device = 'cpu'

# 1. convert model to IR(onnx)
torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  model_checkpoint, device)

# 2. convert IR to tensorrt
onnx_model = os.path.join(work_dir, save_file)
save_file = 'end2end.engine'
model_id = 0
device = 'cuda'
onnx2tensorrt(work_dir, save_file, model_id, deploy_cfg, onnx_model, device)

# 3. extract pipeline info for sdk use (dump-info)
export2SDK(deploy_cfg, model_cfg, work_dir, pth=model_checkpoint)

```

```
python TensorRT_Zhuan.py

load checkpoint from local path: F:/MM/mmclassification/work_dirs/efficientnet-b0_8xb32_in1k/epoch_41.pth
2022-08-21 00:16:24,973 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
2022-08-21 00:16:24,974 - mmdeploy - INFO - Export PyTorch model to ONNX: F:/MM/TensorRT_inference/PCB/pcb_TensorRT.onnx.
D:\Anaconda3\envs\MM\lib\site-packages\mmcv\cnn\bricks\conv2d_adaptive_padding.py:51: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  output_h = math.ceil(img_h / stride_h)
D:\Anaconda3\envs\MM\lib\site-packages\mmcv\cnn\bricks\conv2d_adaptive_padding.py:52: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  output_w = math.ceil(img_w / stride_w)
D:\Anaconda3\envs\MM\lib\site-packages\mmcv\cnn\bricks\conv2d_adaptive_padding.py:55: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  (kernel_h - 1) * self.dilation[0] + 1 - img_h, 0))
D:\Anaconda3\envs\MM\lib\site-packages\mmcv\cnn\bricks\conv2d_adaptive_padding.py:58: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  (kernel_w - 1) * self.dilation[1] + 1 - img_w, 0))
D:\Anaconda3\envs\MM\lib\site-packages\mmcv\cnn\bricks\conv2d_adaptive_padding.py:59: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if pad_h > 0 or pad_w > 0:
D:\Anaconda3\envs\MM\lib\site-packages\mmcv\cnn\bricks\conv2d_adaptive_padding.py:61: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  pad_w // 2, pad_w - pad_w // 2, pad_h // 2, pad_h - pad_h // 2
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
2022-08-21 00:16:29,646 - mmdeploy - INFO - Execute onnx optimize passes.
2022-08-21 00:16:29,647 - mmdeploy - WARNING - Can not optimize model, please build torchscipt extension.
More details: https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/experimental/onnx_optimizer.md
Traceback (most recent call last):
  File "TensorRT_Zhuan.py", line 30, in <module>
    onnx2tensorrt(work_dir, save_file, model_id, deploy_cfg, onnx_model, device)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\backend\tensorrt\onnx2tensorrt.py", line 53, in onnx2tensorrt
    model_params = get_model_inputs(deploy_cfg)[model_id]
IndexError: list index out of range

```

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by irexyc** [comment]
Can't reproduce your problem.

Are you converting the `resnet18_8xb32_in1k_20210831-fbbb1da6.pth` ?

The log says the checkpoint is `efficientnet-b0_8xb32_in1k/epoch_41.pth`

Please provide the script you used other than the demo script in `prebuilt_package_windows.md`

**Comment by monkeycc** [comment]
```
from mmdeploy.apis import torch2onnx
from mmdeploy.apis.tensorrt import onnx2tensorrt
from mmdeploy.backend.sdk.export_info import export2SDK
import os

img = "F:/MM/1.jpg"
work_dir = "F:/MM/TensorRT_inference/PCB/"
save_file = 'pcb_TensorRT.onnx'
deploy_cfg = 'F:/MM/MMDeploy/configs/mmcls/classification_onnxruntime_dynamic.py'
model_cfg = "F:/MM/mmclassification/configs/efficientnet/efficientnet-b0_8xb32_in1k.py"
model_checkpoint = "F:/MM/mmclassification/work_dirs/efficientnet-b0_8xb32_in1k/epoch_41.pth"

# img = 'mmclassification/demo/demo.JPEG'
# work_dir = 'work_dir/trt/resnet'
# save_file = 'end2end.onnx'
# deploy_cfg = 'mmdeploy/configs/mmcls/classification_tensorrt_static-224x224.py'
# model_cfg = 'mmclassification/configs/resnet/resnet18_8xb32_in1k.py'
# model_checkpoint = 'resnet18_8xb32_in1k_20210831-fbbb1da6.pth'
device = 'cpu'

# 1. convert model to IR(onnx)
torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  model_checkpoint, device)

# 2. convert IR to tensorrt
onnx_model = os.path.join(work_dir, save_file)
save_file = 'end2end.engine'
model_id = 0
device = 'cuda'
onnx2tensorrt(work_dir, save_file, model_id, deploy_cfg, onnx_model, device)

# 3. extract pipeline info for sdk use (dump-info)
export2SDK(deploy_cfg, model_cfg, work_dir, pth=model_checkpoint)
```

**Comment by irexyc** [comment]
If you wan't to convert the model running by TensorRT, you should use `deploy_cfg` of `classification_tensorrt_xxx.py` both in `torch2onnx` and `onnx2tensorrt` steps. So the errors is because you used a wrong `deploy_cfg`

It should be also noted that the converted onnx model in the first step may not be able to run by onnxruntime.

For now, mmdeploy doesn't support convert the efficientnet model, and we will support it soon.

**Comment by monkeycc** [comment]
大佬
感觉 好麻烦
 

 1. mmdetection  mmsegmentation   mmclassification
 转换的 是否 一定要转换为  onnx ？
mmdeploy 才能用

2.  mmdeploy 能否直接用  mmdetection  mmsegmentation   mmclassification  训练出的模型
或者转换   mmdeploy格式
然后python 直接调用

@irexyc

**Comment by irexyc** [comment]
1. 是的，目前转TRT需要先转成中间表示(ONNX)。直接pytorch -> trt开发起来不太方便。
2. 直接训练出来的模型是pytorch的，如果直接用pytorch模型的话没必要用mmdeploy。如果为了加速，比如tensorrt、手机、芯片等，还是需要转模型的。mmdpeloy也提供了python的接口，只要模型支持转换就可以python调起来。

**Comment by monkeycc** [comment]
谢谢回答 了解

我有时候要用到几个模型

比如

先目标检测 再 分类检测

先 分类 再目标 再分割

之类的

所以考虑 mmdeploy

我这种情况是合适 三个框架混合一起  还是用 mmdpeloy 比较方便

**Comment by irexyc** [comment]
我觉得主要看你用来做什么，比如只是做个demo，对速度没什么要求的话，直接在pytorch上面开发就行了，不用管编译和乱七八糟的环境，pip install 就能搞定。如果对速度有要求的话，可能开发之前要先选模型，看看Tensorrt或者其他backend的加速是否满足要求。

**Comment by irexyc** [comment]
efficientnet 可以尝试升级一下pytorch的版本，我这边测试1.12转tensorrt是可以成功的。
