### ISSUE TITLE
the test pipline in model_cfg when deploying mmdetection model with TensorRT can't use "scale_factor" but "image_scale"

### ISSUE THREAD

**Issue by StevenGerrad** [open-mmlab/mmdeploy#934]
the test pipline config I used when deploying mmdetection model with TensorRT is as shown below (I use `scale_factor=1.0` to replace `img_scale`):
```
test=dict(
        type='CocoDataset',
        ann_file=...,
        img_prefix=...,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                scale_factor=1.0,
                # img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(
                        type='Normalize',
                        mean=[144.578, 107.304, 90.519],
                        std=[78.271, 63.2, 56.992],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
	])
        ])
```
the test pipline config above can be used in mmdetection, but the `tools/deploy.py` in mmdeploy will report an error:
```
Traceback (most recent call last):
  File "tools/deploy.py", line 366, in <module>
    main()
  File "tools/deploy.py", line 121, in main
    export2SDK(deploy_cfg, model_cfg, args.work_dir, pth=checkpoint_path)
  File "e:\project\mmdeploy\mmdeploy\backend\sdk\export_info.py", line 366, in export2SDK
    pipeline_info = get_pipeline(deploy_cfg, model_cfg, work_dir=work_dir)
  File "e:\project\mmdeploy\mmdeploy\backend\sdk\export_info.py", line 305, in get_pipeline
    preprocess = get_preprocess(deploy_cfg, model_cfg)
  File "e:\project\mmdeploy\mmdeploy\backend\sdk\export_info.py", line 201, in get_preprocess
    transform['size'] = pipeline[-1].img_scale[::-1]
  File "E:\ProgramData\Anaconda3\envs\mmdeploy\lib\site-packages\mmcv\utils\config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'img_scale'
```
and if I delete the corresponding code in`mmdeploy\backend\sdk\export_info.py`：
```
if 'transforms' in pipeline[-1]:
        transforms = pipeline[-1]['transforms']
        transforms.insert(0, pipeline[0])
        # for transform in transforms:
        #     if transform['type'] == 'Resize':
        #         transform['size'] = pipeline[-1].img_scale[::-1]
        #         if 'img_scale' in transform:
        #             transform.pop('img_scale')
```
the generated tensorRT file will report error will also report an error when called:
```
[2022-08-21 11:35:02.984] [mmdeploy] [error] [transform_module.cpp:37] error: unknown (6) @ :0
[2022-08-21 11:35:02.984] [mmdeploy] [error] [module_adapter.h:34] unhandled exception: unknown (6) @ :0
[ERROR][2022-08-21 11:35:02.984][resize.cu:1020] Assertion failed: dst != nullptr
```
Is it that mmdetection does not take into account the case where `scale_factor=1.0` is used instead of image_scale at test time? Or is it that tensortRT needs to specify a resize scale.

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by RunningLeon** [comment]
@StevenGerrad Hi, mmdeploy did not consider case where `scale_factor` instead of `img_scale` is used in test_pipeline. You may change it to `img_scale`.
