### ISSUE TITLE
ImportError: DLL load failed while importing mmdeploy_python: 找不到指定的模块。

### ISSUE THREAD

**Issue by bunengxiu** [open-mmlab/mmdeploy#957]
**Help me**
I don't know how to solve this problem, I have been working on this bug for a day, but I still haven't fixed it

**Describe the bug**

1. My computer is window10, 64bit, AMD. follow the tutorial of mmdeploy(https://mmdeploy.readthedocs.io/zh_CN/latest/02-how-to-run/prebuilt_package_windows.html), got end2end.onnx, end2end.engine, deploy.json, detail.json, pipeline.json in work-dir. but run "python .\mmdeploy\demo\python\image_classification.py cpu .\work_dir\onnx\resnet\ .\mmclassification\demo\demo.JPEG" command  on the terminal, got error( DLL load failed while importing mmdeploy_python: 找不到指定的模块。)
2. from mmdeploy_python import Classifier , pycharm shows that Cannot find reference "Classifier" in "__init__.py", but mmdeploy_python is installed(use command: pip mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0\sdk\python\mmdeploy_python-0.7.0-cp39-none-win_amd64.whl)
3. The truth is I have CuDNN 8.5.0 installed, I don't know why it shows that CUDNN 8.3.2 installed when run mmdeploy\tools\check_env.py on terminal， open C:\Users\WJH\Downloads\cudnn-windows-x86_64-8.5.0.96_cuda11-archive\include\cudnn_version.h, show:
        #ifndef CUDNN_VERSION_H_
        #define CUDNN_VERSION_H_
        #define CUDNN_MAJOR 8
        #define CUDNN_MINOR 5
        #define CUDNN_PATCHLEVEL 0

**Reproduction**

1. What command or script did you run?

```
python mmdeploy\demo\python\image_classification.py cuda work_dir\trt\resnet\ mmclassification\demo\demo.JPEG
```

5. Did you make any modifications on the code or config? Did you understand what you have modified?

**Environment**
2022-08-29 17:38:14,612 - mmdeploy - INFO -

2022-08-29 17:38:14,612 - mmdeploy - INFO - **********Environmental information**********
fatal: not a git repository (or any of the parent directories): .git
2022-08-29 17:38:15,713 - mmdeploy - INFO - sys.platform: win32
2022-08-29 17:38:15,713 - mmdeploy - INFO - Python: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
2022-08-29 17:38:15,713 - mmdeploy - INFO - CUDA available: True
2022-08-29 17:38:15,713 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3060
2022-08-29 17:38:15,713 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
2022-08-29 17:38:15,713 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.124
2022-08-29 17:38:15,713 - mmdeploy - INFO - GCC: n/a
2022-08-29 17:38:15,713 - mmdeploy - INFO - PyTorch: 1.12.1+cu116
2022-08-29 17:38:15,714 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_7
5,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /b
igobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILE
R_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_N
CCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

2022-08-29 17:38:15,714 - mmdeploy - INFO - TorchVision: 0.13.1+cu116
2022-08-29 17:38:15,714 - mmdeploy - INFO - OpenCV: 4.6.0
2022-08-29 17:38:15,714 - mmdeploy - INFO - MMCV: 1.6.1
2022-08-29 17:38:15,714 - mmdeploy - INFO - MMCV Compiler: MSVC 192930140
2022-08-29 17:38:15,715 - mmdeploy - INFO - MMCV CUDA Compiler: 11.6
2022-08-29 17:38:15,715 - mmdeploy - INFO - MMDeploy: 0.7.0+
2022-08-29 17:38:15,715 - mmdeploy - INFO -

2022-08-29 17:38:15,715 - mmdeploy - INFO - **********Backend information**********
2022-08-29 17:38:16,073 - mmdeploy - INFO - onnxruntime: None   ops_is_avaliable : False
2022-08-29 17:38:16,098 - mmdeploy - INFO - tensorrt: 8.4.3.1   ops_is_avaliable : True
2022-08-29 17:38:16,128 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-08-29 17:38:16,130 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-08-29 17:38:16,132 - mmdeploy - INFO - openvino_is_avaliable: False
2022-08-29 17:38:16,172 - mmdeploy - INFO - snpe_is_available: False
2022-08-29 17:38:16,172 - mmdeploy - INFO -

2022-08-29 17:38:16,172 - mmdeploy - INFO - **********Codebase information**********
2022-08-29 17:38:16,175 - mmdeploy - INFO - mmdet:      None
2022-08-29 17:38:16,176 - mmdeploy - INFO - mmseg:      None
2022-08-29 17:38:16,176 - mmdeploy - INFO - mmcls:      0.23.2
2022-08-29 17:38:16,176 - mmdeploy - INFO - mmocr:      None
2022-08-29 17:38:16,176 - mmdeploy - INFO - mmedit:     None
2022-08-29 17:38:16,176 - mmdeploy - INFO - mmdet3d:    None
2022-08-29 17:38:16,176 - mmdeploy - INFO - mmpose:     None
2022-08-29 17:38:16,176 - mmdeploy - INFO - mmrotate:   None
**Error traceback**

If applicable, paste the error trackback here.

```
Traceback (most recent call last):
  File "E:\learning\coding\deploy_mmclassification\mmdeploy\demo\python\image_classification.py", line 5, in <mo
dule>
    from mmdeploy_python import Classifier
ModuleNotFoundError: No module named 'mmdeploy_python'

(deploy_mmclassification1) E:\learning\coding\deploy_mmclassification>pip install mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0\sdk\python\mmdeploy_python-0.7.0-cp39-none-win_amd64.whl
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing e:\learning\coding\deploy_mmclassification\mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0\sdk\python\mmdeploy_python-0.7.0-cp39-none-win_amd64.whl
(deploy_mmclassification1) E:\learning\coding\deploy_mmclassification>pip install mmdeploy-0.7.0-windows-amd64-c
uda11.1-tensorrt8.2.3.0\sdk\python\mmdeploy_python-0.7.0-cp39-none-win_amd64.whl
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing e:\learning\coding\deploy_mmclassification\mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0\sdk\python\mmdeploy_python-0.7.0-cp39-none-win_amd64.whl
Installing collected packages: mmdeploy-python
Successfully installed mmdeploy-python-0.7.0

(deploy_mmclassification1) E:\learning\coding\deploy_mmclassification>python mmdeploy\demo\python\image_classification.py cuda work_dir\trt\resnet\ mmclassification\demo\demo.JPEG
Traceback (most recent call last):
  File "E:\learning\coding\deploy_mmclassification\mmdeploy\demo\python\image_classification.py", line 5, in <module>
    from mmdeploy_python import Classifier
  File "D:\python_envs\deploy_mmclassification1\lib\site-packages\mmdeploy_python\__init__.py", line 21, in <module>
    from .mmdeploy_python import *  # noqa
ImportError: DLL load failed while importing mmdeploy_python: 找不到指定的模块。
```

**Bug fix**
I don't know how to solve this problem, I have been working on this bug for a day, but I still haven't fixed it

**Comment by irexyc** [comment]
Can't reproduce your problem.

Have you download cuda related contents like cuda toolkit, cudnn and tensorrt and set environment PATH? You may print your PATH variable by `echo $env:PATH`

**Comment by bunengxiu** [comment]
> `CuDNN 8.3.2 (built against CUDA 11.5)` actually comes from `torch.__config__.show()`. According the log, you've installed tensorrt 8.4.3.1, `2022-08-29 17:38:16,098 - mmdeploy - INFO - tensorrt: 8.4.3.1 ops_is_avaliable : True`. But mmdeploy-tensorrt prebuilt package relies on `tensorrt 8.2.3.0`.
> 
> You can try build mmdeploy from source, referring to [this guide](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/windows.md)

**description**
1. run: torch2onnx
2. run: onnx2tensorrt
get below:
```
.\work_dir\
`-- trt
    `-- resnet
        |-- deploy.json
        |-- detail.json
        |-- end2end.engine
        |-- end2end.onnx
        `-- pipeline.json
```
3. run: python .\mmdeploy\demo\python\image_classification.py cuda .\work_dir\trt\resnet\ .\mmclassification\demo\demo.JPEG
get below:
ImportError: DLL load failed while importing mmdeploy_python: 找不到指定的模块。
4. cannot import Classifier from mmdeploy_python in mmdeploy\demo\python\image_classification.py

**environment**
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\libnvvp
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\lib\x64
C:\Program Files\TensorRT-8.2.3.0\bin

**Error traceback**

Traceback (most recent call last):
  File "E:\learning\coding\deploy_mmclassification\mmdeploy\demo\python\image_classification.py", line 5, in <module>
    from mmdeploy_python import Classifier
  File "D:\python_envs\deploy_mmclassification4\lib\site-packages\mmdeploy_python\__init__.py", line 21, in <module>
    from .mmdeploy_python import *  # noqa
ImportError: DLL load failed while importing mmdeploy_python: 找不到指定的模块。

**Environment**
2022-08-30 02:27:46,947 - mmdeploy - INFO -

2022-08-30 02:27:46,947 - mmdeploy - INFO - **********Environmental information**********
fatal: not a git repository (or any of the parent directories): .git
2022-08-30 02:27:47,954 - mmdeploy - INFO - sys.platform: win32
2022-08-30 02:27:47,955 - mmdeploy - INFO - Python: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
2022-08-30 02:27:47,955 - mmdeploy - INFO - CUDA available: True
2022-08-30 02:27:47,955 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3060
2022-08-30 02:27:47,955 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5
2022-08-30 02:27:47,955 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.5, V11.5.119
2022-08-30 02:27:47,955 - mmdeploy - INFO - GCC: n/a
2022-08-30 02:27:47,956 - mmdeploy - INFO - PyTorch: 1.11.0+cu115
2022-08-30 02:27:47,956 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.5
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_7
5,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.5, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /b
igobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILE
R_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_N
CCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

2022-08-30 02:27:47,956 - mmdeploy - INFO - TorchVision: 0.12.0+cu115
2022-08-30 02:27:47,956 - mmdeploy - INFO - OpenCV: 4.6.0
2022-08-30 02:27:47,956 - mmdeploy - INFO - MMCV: 1.6.1
2022-08-30 02:27:47,956 - mmdeploy - INFO - MMCV Compiler: MSVC 192930140
2022-08-30 02:27:47,957 - mmdeploy - INFO - MMCV CUDA Compiler: 11.5
2022-08-30 02:27:47,957 - mmdeploy - INFO - MMDeploy: 0.7.0+
2022-08-30 02:27:47,957 - mmdeploy - INFO -

2022-08-30 02:27:47,957 - mmdeploy - INFO - **********Backend information**********
2022-08-30 02:27:48,311 - mmdeploy - INFO - onnxruntime: None   ops_is_avaliable : False
2022-08-30 02:27:48,334 - mmdeploy - INFO - tensorrt: 8.2.3.0   ops_is_avaliable : True
2022-08-30 02:27:48,365 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-08-30 02:27:48,367 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-08-30 02:27:48,368 - mmdeploy - INFO - openvino_is_avaliable: False
2022-08-30 02:27:48,409 - mmdeploy - INFO - snpe_is_available: False
2022-08-30 02:27:48,409 - mmdeploy - INFO -

2022-08-30 02:27:48,409 - mmdeploy - INFO - **********Codebase information**********
2022-08-30 02:27:48,412 - mmdeploy - INFO - mmdet:      None
2022-08-30 02:27:48,412 - mmdeploy - INFO - mmseg:      None
2022-08-30 02:27:48,412 - mmdeploy - INFO - mmcls:      0.23.2
2022-08-30 02:27:48,412 - mmdeploy - INFO - mmocr:      None
2022-08-30 02:27:48,413 - mmdeploy - INFO - mmedit:     None
2022-08-30 02:27:48,413 - mmdeploy - INFO - mmdet3d:    None
2022-08-30 02:27:48,413 - mmdeploy - INFO - mmpose:     None
2022-08-30 02:27:48,413 - mmdeploy - INFO - mmrotate:   None

**Comment by irexyc** [comment]
Please print the output of `echo $env:PATH`

You can use this [tool](mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0.zip) to check if the dependences of `mmdeploy_python.cpxx-win_amd64.pyd` exists in your PATH

`mmdeploy_python.cpxx-win_amd64.pyd` exists in the whl package, you can unzip the whl to get it.

**Comment by bunengxiu** [comment]
> Please print the output of `echo $env:PATH`
> 
> You can use this [tool](mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0.zip) to check if the dependences of `mmdeploy_python.cpxx-win_amd64.pyd` exists in your PATH
> 
> `mmdeploy_python.cpxx-win_amd64.pyd` exists in the whl package, you can unzip the whl to get it.

please tell me where tool is? 
Is the tool path mmdeploy/tools/check_env.py ?????

**Comment by irexyc** [comment]
Sorry, the link is wrong. Fixed it.
https://github.com/lucasg/Dependencies/releases

**Comment by bunengxiu** [comment]
> Sorry, the link is wrong. Fixed it. https://github.com/lucasg/Dependencies/releases

=============================
I find  mmdeploy_python.cp39-win_amd64.pyd in mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0\sdk\python\mmdeploy_python\ and open it using DependenciesGui.exe

 but I do not understand showing content in DependenciesGui

**Comment by bunengxiu** [comment]
> Please print the output of `echo $env:PATH`
> 
> You can use this [tool](https://github.com/lucasg/Dependencies/releases) to check if the dependences of `mmdeploy_python.cpxx-win_amd64.pyd` exists in your PATH
> 
> `mmdeploy_python.cpxx-win_amd64.pyd` exists in the whl package, you can unzip the whl to get it.

-----------------------------------------
In mmdeploy/demo/python/image_classification.py
    can not import Classifier from mmdeploy_python
In mmdeploy/demo/python/image_segmentation.py
    can not import Segmentor from mmdeploy_python

Restorer, Detector, TextDetector, TextRecognizer, PoseDetector, RotatedDetector also can not import form mmdeploy_python

**Comment by bunengxiu** [comment]
![1661835395719](https://user-images.githubusercontent.com/42935524/187352574-740efc48-db5b-4c34-b274-43ee6ee634f8.png)

**Comment by irexyc** [comment]
The picture shows that the depencencies of mmdeploy_python.cpxx-win_amd64.pyd already exists in the $env:PATH

I test your environment (cuda11.5 + cudnn8.5 + tensorrt 8.4) and no error occured when import mmdeploy_python.

I don't have a clue to the problem for now. You may try to compile mmdeploy_python yourself according to docs/zh_cn/01-how-to-build/windows.md

**Comment by bunengxiu** [comment]
> The picture shows that the depencencies of mmdeploy_python.cpxx-win_amd64.pyd already exists in the $env:PATH
> 
> I test your environment (cuda11.5 + cudnn8.5 + tensorrt 8.4) and no error occured when import mmdeploy_python.
> 
> I don't have a clue to the problem for now. You may try to compile mmdeploy_python yourself according to docs/zh_cn/01-how-to-build/windows.md

==============================================================
because My NVCUDA64.DLL is NVIDIA CUDA 11.6.127 dirver
yestoday:   
     The environment (cuda11.5 + cudnn8.5 + tensorrt 8.4) is installed
but today:
      The environment (cuda11.5 + cudnn8.3.2 + tensort8.2.30) is installed

**Comment by bunengxiu** [comment]
prebuilded mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0\sdk\python
1. mmdeploy_python-0.7.0-cp36-none-win_amd64.whl.     Yes
2. mmdeploy_python-0.7.0-cp37-none-win_amd64.whl.     Yes
3. mmdeploy_python-0.7.0-cp38-none-win_amd64.whl.     No
4. mmdeploy_python-0.7.0-cp39-none-win_amd64.whl.     No       

I try different python version, I find mmdeploy_python-0.7.0-cp36-none-win_amd64.whl and mmdeploy_python-0.7.0-cp37-none-win_amd64.whl are ok but mmdeploy_python-0.7.0-cp38-none-win_amd64.whl and mmdeploy_python-0.7.0-cp39-none-win_amd64.whl are bad

so the prebuilded mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0.zip is not incomplete

**Comment by irexyc** [comment]
The driver is not the problem as long as it supports cuda which you installed.

Actually, I test both of your environment setting with python38. :joy:

**Comment by Hellcat1005** [comment]
> prebuilded mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0\sdk\python
> 
> 1. mmdeploy_python-0.7.0-cp36-none-win_amd64�.whl.     Yes
> 2. mmdeploy_python-0.7.0-cp37-none-win_amd64�.whl.     Yes
> 3. mmdeploy_python-0.7.0-cp38-none-win_amd64�.whl.     No
> 4. mmdeploy_python-0.7.0-cp39-none-win_amd64�.whl.     No
> 
> I try different python version, I find mmdeploy_python-0.7.0-cp36-none-win_amd64.whl and mmdeploy_python-0.7.0-cp37-none-win_amd64.whl are ok but mmdeploy_python-0.7.0-cp38-none-win_amd64.whl and mmdeploy_python-0.7.0-cp39-none-win_amd64.whl are bad
> 
> so the prebuilded mmdeploy-0.7.0-windows-amd64-cuda11.1-tensorrt8.2.3.0.zip is incomplete

I think you are right. My environment was py38. I used mmdeploy-0.9.0-windows-amd64-cuda11.1-tensorrt8.2.3.0. After pip install mmdeploy_python-0.9.0-cp38-none-win_amd64.whl, I got ImportError: DLL load failed while importing mmdeploy_python. py37 is OK.

**Comment by Tender-hjd** [comment]
@irexyc After my test, you can't build ONNXRuntime-SDK and TensorRT-SDK at the same time in one Python-environment. If you do this, only the first built SDK-backend is available.
What's the possible reason?

**Comment by Tender-hjd** [comment]
> @irexyc After my test, you can't build ONNXRuntime-SDK and TensorRT-SDK at the same time in one Python-environment. If you do this, only the first built SDK-backend is available.
What's the possible reason?

My Python version is 3.8.13.

**Comment by irexyc** [comment]
@Tender-hjd 
Hi, what is your cmake configure command? The backend should be seperate by `;`, so if you want to build with tensorrt and onnxruntime backend, you should pass `-DMMDEPLOY_TARGET_BACKENDS="trt;ort"

**Comment by Tender-hjd** [comment]
@irexyc Everything is ok, Thanks!
