### ISSUE TITLE
Failure of conversion to tensorrt due to illegal memory access

### ISSUE THREAD

**Issue by yeungkong** [open-mmlab/mmdeploy#965]
Hi developers. I am encountering failure of conversion to tensorrt. My environment is like Win10, Cuda11.3, VS2019, cudnn8.2.0, Python3.7, Pytorch1.11.0, mmcv-full1.4.8, mmdet2.23.0, mmdeploy0.7.0, onnxruntime1.12.1, tensorrt8.4.3.1.

I run the following command.
`python ./tools/deploy.py configs/mmdet/detection/detection_tensorrt_dynamic-64x64-608x608.py .../mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco2.py .../mmdetection/work_dirs_maskrcnn2/epoch_200.pth .../mmdetection/demo/tensorrt_demo.png --work-dir .../mmdeploy/work_dir --show  --device cuda:0 --log-leve`

The following is the error message.
```
[08/31/2022-11:35:39] [TRT] [W] Weights [name=Conv_1511.weight] had the following issues when converted to FP16:
[08/31/2022-11:35:39] [TRT] [W]  - Subnormal FP16 values detected.
[08/31/2022-11:35:39] [TRT] [W]  - Values less than smallest positive FP16 Subnormal value detected. Converting to FP16 minimum subnormalized value.
[08/31/2022-11:35:39] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.
[08/31/2022-11:35:42] [TRT] [W] Weights [name=Conv_1520.weight] had the following issues when converted to FP16:
[08/31/2022-11:35:42] [TRT] [W]  - Subnormal FP16 values detected.
[08/31/2022-11:35:42] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.
[08/31/2022-11:35:43] [TRT] [W] Weights [name=Conv_1520.weight] had the following issues when converted to FP16:
[08/31/2022-11:35:43] [TRT] [W]  - Subnormal FP16 values detected.
[08/31/2022-11:35:43] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.
[08/31/2022-11:35:43] [TRT] [W] Weights [name=Conv_1520.weight] had the following issues when converted to FP16:
[08/31/2022-11:35:43] [TRT] [W]  - Subnormal FP16 values detected.
[08/31/2022-11:35:43] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.
[08/31/2022-11:35:43] [TRT] [W] Weights [name=Conv_1520.weight] had the following issues when converted to FP16:
[08/31/2022-11:35:43] [TRT] [W]  - Subnormal FP16 values detected.
[08/31/2022-11:35:43] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.
[08/31/2022-11:35:43] [TRT] [W] Weights [name=Conv_1520.weight] had the following issues when converted to FP16:
[08/31/2022-11:35:43] [TRT] [W]  - Subnormal FP16 values detected.
[08/31/2022-11:35:43] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.
[08/31/2022-11:35:43] [TRT] [W] Weights [name=Conv_1520.weight] had the following issues when converted to FP16:
[08/31/2022-11:35:43] [TRT] [W]  - Subnormal FP16 values detected.
[08/31/2022-11:35:43] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.
[08/31/2022-11:35:43] [TRT] [W] Weights [name=Conv_1520.weight] had the following issues when converted to FP16:
[08/31/2022-11:35:43] [TRT] [W]  - Subnormal FP16 values detected.
[08/31/2022-11:35:43] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.
[08/31/2022-11:35:43] [TRT] [W] Weights [name=Conv_1520.weight] had the following issues when converted to FP16:
[08/31/2022-11:35:43] [TRT] [W]  - Subnormal FP16 values detected.
[08/31/2022-11:35:43] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.
[08/31/2022-11:35:56] [TRT] [E] 1: [graphContext.h::nvinfer1::rt::MyelinGraphContext::~MyelinGraphContext::35] Error Code 1: Myelin (Error 700 destroying stream '0000017043ABCC80'.)
[08/31/2022-11:35:56] [TRT] [W] GPU error during getBestTactic: {ForeignNode[Gather_1593...Reshape_1596]} : an illegal memory access was encountered
[08/31/2022-11:35:56] [TRT] [E] 1: [resizingAllocator.cpp::nvinfer1::internal::ResizingAllocator::allocate::62] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[08/31/2022-11:35:56] [TRT] [W] Requested amount of GPU memory (784 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[08/31/2022-11:35:56] [TRT] [W] Fall back to CPU graph reduction due to insufficient memory.
[08/31/2022-11:35:56] [TRT] [E] 1: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::~StdVirtualMemoryBufferImpl::104] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[08/31/2022-11:35:56] [TRT] [I] Detected 1 inputs and 6 output network tensors.
[08/31/2022-11:35:56] [TRT] [E] 1: [context.cpp::nvinfer1::rt::CommonContext::setStream::121] Error Code 1: Cudnn (CUDNN_STATUS_MAPPING_ERROR)
Process Process-3:
Traceback (most recent call last):
  File "D:\Program_Files\Anaconda3\envs\...\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\Program_Files\Anaconda3\envs\...\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "d:\...\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "d:\...\mmdeploy\mmdeploy\backend\tensorrt\onnx2tensorrt.py", line 88, in onnx2tensorrt
    device_id=device_id)
  File "d:\...\mmdeploy\mmdeploy\backend\tensorrt\utils.py", line 153, in from_onnx
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine
2022-08-31 11:35:58,744 - mmdeploy - ERROR - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed. exit.
```
The illegal memory access happens at the middle of the conversion and it cannot even allocate 784 bytes GPU memory. What can I change to fix this problem? I really need your help. Thank you very much.

**Comment by lvhan028** [comment]
similar to #963 
When deploying mask r-cnn model, the deploy config `configs/mmdet/instance-seg/*` is supposed to be adopted rather than `configs/mmdet/detection/*`

**Comment by yeungkong** [comment]
I see. After I changed the deploy config to `configs/mmdet/instance-seg/*`, my conversion to tensorrt was finally successful. Thank you very much for your help!! Much appreciated.
