### ISSUE TITLE
Multiprocessing support with mmdeploy_python

### ISSUE THREAD

**Issue by diwgan32** [open-mmlab/mmdeploy#971]
**Describe the bug**

The `Detector` api in `mmdeploy_python` fails to load a TensorRT model if it's loaded as a child process vs loaded in the parent process.

**Reproduction**

1. What command or script did you run?

First, I used MMDeploy to generate the TensorRT engine. Here's the code I used to generate the model:

```
python ./tools/deploy.py \
    configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py \
    $PATH_TO_MMDET/configs/yolox/yolox_l_8x8_300e_coco.py \
    https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_l_8x8_300e_coco/yolox_l_8x8_300e_coco_20211126_140236-d3bd2b23.pth \
    $PATH_TO_MMDET/demo/demo.jpg \
    --work-dir work_dir \
    --show \
    --device cuda:0
```

The following simple Python script works to load the model:
```
from mmdeploy_python import Detector
import mmcv

NUM_PROCESSES = 1
video_path = '/root/workspace/videos/handle_cans.mp4'

def run_loop():
    video = mmcv.VideoReader(video_path)
    detector = Detector(model_path='/root/workspace/mmdeploy/work_dir/yolo_l', device_name='cuda', device_id=0)

if __name__ == "__main__":
    run_loop()
```

However, if I do this same thing, but run `run_loop()` as a child process, I get an error. Here's a reproducible example:

```
import multiprocessing as mp
from mmdeploy_python import Detector
import cv2
import numpy as np
import mmcv

NUM_PROCESSES = 1
video_path = '/root/workspace/videos/handle_cans.mp4'

def run_loop():
    video = mmcv.VideoReader(video_path)
    detector = Detector(model_path='/root/workspace/mmdeploy/work_dir/yolo_l', device_name='cuda', device_id=0)


children = []
for i in range(NUM_PROCESSES):
    children.append(
        mp.Process(target=run_loop, args=())
    )
    children[i].start()
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

I made 1 modification to my environment. I used the standard Dockerfile found in mmdeploy, but added the `-DMMDEPLOY_BUILD_SDK_PYTHON_API=ON` flag to the last line of the Dockerfile that compiles mmdeploy. This is meant to turn on support for mmdeploy_python. 

**Environment**

2022-08-31 23:15:16,927 - mmdeploy - INFO -

2022-08-31 23:15:16,928 - mmdeploy - INFO - **********Environmental information**********
2022-08-31 23:15:17,124 - mmdeploy - INFO - sys.platform: linux
2022-08-31 23:15:17,124 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
2022-08-31 23:15:17,124 - mmdeploy - INFO - CUDA available: True
2022-08-31 23:15:17,124 - mmdeploy - INFO - GPU 0,1,2,3: Tesla V100-FHHL-16GB
2022-08-31 23:15:17,125 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2022-08-31 23:15:17,125 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.124
2022-08-31 23:15:17,125 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2022-08-31 23:15:17,125 - mmdeploy - INFO - PyTorch: 1.10.0
2022-08-31 23:15:17,125 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

2022-08-31 23:15:17,125 - mmdeploy - INFO - TorchVision: 0.11.0
2022-08-31 23:15:17,125 - mmdeploy - INFO - OpenCV: 4.6.0
2022-08-31 23:15:17,125 - mmdeploy - INFO - MMCV: 1.5.3
2022-08-31 23:15:17,125 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2022-08-31 23:15:17,125 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2022-08-31 23:15:17,125 - mmdeploy - INFO - MMDeploy: 0.7.0+cad0092
2022-08-31 23:15:17,125 - mmdeploy - INFO -

2022-08-31 23:15:17,125 - mmdeploy - INFO - **********Backend information**********
2022-08-31 23:15:17,616 - mmdeploy - INFO - onnxruntime: 1.8.1	ops_is_avaliable : True
2022-08-31 23:15:17,653 - mmdeploy - INFO - tensorrt: 8.2.4.2	ops_is_avaliable : True
2022-08-31 23:15:17,672 - mmdeploy - INFO - ncnn: None	ops_is_avaliable : False
2022-08-31 23:15:17,673 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-08-31 23:15:17,674 - mmdeploy - INFO - openvino_is_avaliable: False
2022-08-31 23:15:17,692 - mmdeploy - INFO - snpe_is_available: False
2022-08-31 23:15:17,692 - mmdeploy - INFO -

2022-08-31 23:15:17,692 - mmdeploy - INFO - **********Codebase information**********
2022-08-31 23:15:17,694 - mmdeploy - INFO - mmdet:	2.25.1
2022-08-31 23:15:17,694 - mmdeploy - INFO - mmseg:	None
2022-08-31 23:15:17,694 - mmdeploy - INFO - mmcls:	None
2022-08-31 23:15:17,694 - mmdeploy - INFO - mmocr:	None
2022-08-31 23:15:17,694 - mmdeploy - INFO - mmedit:	None
2022-08-31 23:15:17,694 - mmdeploy - INFO - mmdet3d:	None
2022-08-31 23:15:17,694 - mmdeploy - INFO - mmpose:	0.28.1
2022-08-31 23:15:17,694 - mmdeploy - INFO - mmrotate:	None

**Error traceback**

```
[2022-08-31 23:13:49.384] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
[2022-08-31 23:13:50.679] [mmdeploy] [info] [model.cpp:38] DirectoryModel successfully load model /root/workspace/mmdeploy/work_dir/yolo_l
[2022-08-31 23:13:50.679] [mmdeploy] [error] [pipeline.cpp:27] exception caught: unknown (6) @ /root/workspace/mmdeploy/csrc/mmdeploy/device/cuda/cuda_device.cpp:279
Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "mp_test.py", line 16, in run_loop
    detector = Detector(model_path='/root/workspace/mmdeploy/work_dir/yolo_l', device_name='cuda', device_id=0)
RuntimeError: failed to create detector
```

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by diwgan32** [comment]
Just solved this issue, posting here in case it helps others. Turns out that you have to turn on `spawn` mode in multiprocess to get the child process to correctly recognize CUDA drivers. So, the following code snippet works for me:

```
from multiprocessing.connection import wait
import multiprocessing as mp
from mmdeploy_python import Detector, PoseDetector
video_path = '/root/workspace/videos/handle_cans.mp4'

def run_loop():
    video = mmcv.VideoReader(video_path)
    detector = Detector(model_path='/root/workspace/mmdeploy/work_dir/yolo_l', device_name='cuda', device_id=0)

if __name__ == "__main__":
    mp.set_start_method('spawn')
    children = []
    children.append(
        mp.Process(target=run_loop, args=())
    )
    children[0].start()
    children[0].join()
```
