### ISSUE TITLE
Unable to open file (unable to open file: name = 'F:/MM/calib_data.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdeploy#993]
```
from mmdeploy.apis import torch2onnx
from mmdeploy.apis.tensorrt import onnx2tensorrt
from mmdeploy.backend.sdk.export_info import export2SDK
import os

img = r"F:/MM/2048CS/Image_20220624161024647.jpg"
work_dir = "F:/MM/TensorRT_inference/MMint8/"
save_file = 'MM_TensorRTint8.onnx'
deploy_cfg = "F:/MM/MMDeploy/configs/mmdet/detection/detection_tensorrt-int8_static-800x1344.py"
model_cfg = r"F:/MMDetection/mask_rcnn_r50_fpn_1x_coco.py"
model_checkpoint = "F:/MMDetection/MM24.pth"


device = 'cpu'

# 1. convert model to IR(onnx)
torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  model_checkpoint, device)

# 2. convert IR to tensorrt
onnx_model = os.path.join(work_dir, save_file)
save_file = 'xia.engine'
model_id = 0
device = 'cuda'
onnx2tensorrt(work_dir, save_file, model_id, deploy_cfg, onnx_model, device)

# 3. extract pipeline info for sdk use (dump-info)
export2SDK(deploy_cfg, model_cfg, work_dir, pth=model_checkpoint)
```

```

[2022-09-03 11:42:09.765] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
load checkpoint from local path: F:/MMDetection/MM24.pth
D:\Anaconda3\envs\MM\lib\site-packages\mmdet\datasets\utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
2022-09-03 11:42:10,965 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-09-03 11:42:10,965 - mmdeploy - INFO - Export PyTorch model to ONNX: F:/MM/TensorRT_inference/MMint8/MM_TensorRTint8.onnx.
D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\core\optimizers\function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\codebase\mmdet\models\detectors\base.py:24: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  img_shape = [int(val) for val in img_shape]
D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\codebase\mmdet\models\detectors\base.py:24: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  img_shape = [int(val) for val in img_shape]
D:\Anaconda3\envs\MM\lib\site-packages\mmdet\models\dense_heads\anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
D:\Anaconda3\envs\MM\lib\site-packages\mmdet\core\anchor\anchor_generator.py:333: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
D:\Anaconda3\envs\MM\lib\site-packages\mmdet\core\anchor\anchor_generator.py:370: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors``
  '``single_level_grid_anchors`` would be deprecated soon. '
D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\codebase\mmdet\models\dense_heads\rpn_head.py:78: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\pytorch\functions\topk.py:56: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k > size:
D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\codebase\mmdet\core\bbox\delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\codebase\mmdet\core\bbox\delta_xywh_bbox_coder.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\codebase\mmdet\core\post_processing\bbox_nms.py:259: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  dets, labels = TRTBatchedNMSop.apply(boxes, scores, int(scores.shape[-1]),
D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\mmcv\ops\nms.py:178: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!    
  out_boxes = min(num_boxes, after_topk)
D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\mmcv\ops\nms.py:181: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!    
  (batch_size, out_boxes)).to(scores.device))
D:\Anaconda3\envs\MM\lib\site-packages\mmcv\cnn\bricks\wrappers.py:89: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if x.numel() == 0 and obsolete_torch_version(TORCH_VERSION, (1, 4)):
D:\Anaconda3\envs\MM\lib\site-packages\mmcv\cnn\bricks\wrappers.py:45: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if x.numel() == 0 and obsolete_torch_version(TORCH_VERSION, (1, 4)):
D:\Anaconda3\envs\MM\lib\site-packages\torch\onnx\symbolic_opset9.py:4194: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  + "If indices include negative values, the exported graph will produce incorrect results."
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::grid_sampler type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::grid_sampler type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::MMCVMultiLevelRoiAlign type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::grid_sampler type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
2022-09-03 11:42:18,207 - mmdeploy - INFO - Execute onnx optimize passes.
2022-09-03 11:42:18,208 - mmdeploy - WARNING - Can not optimize model, please build torchscipt extension.
More details: https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/experimental/onnx_optimizer.md
2022-09-03 11:42:18,864 - mmdeploy - INFO - Successfully loaded tensorrt plugins from D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\lib\mmdeploy_tensorrt_ops.dll
[09/03/2022-11:42:19] [TRT] [I] [MemUsageChange] Init CUDA: CPU +356, GPU +0, now: CPU 12160, GPU 1296 (MiB)
[09/03/2022-11:42:20] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +356, GPU +104, now: CPU 12669, GPU 1400 (MiB)
[09/03/2022-11:42:20] [TRT] [W] onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[09/03/2022-11:42:20] [TRT] [W] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[09/03/2022-11:42:20] [TRT] [W] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[09/03/2022-11:42:20] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[09/03/2022-11:42:20] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace:
[09/03/2022-11:42:20] [TRT] [I] Successfully created plugin: TRTBatchedNMS
[09/03/2022-11:42:20] [TRT] [I] No importer registered for op: MMCVMultiLevelRoiAlign. Attempting to import as plugin.
[09/03/2022-11:42:20] [TRT] [I] Searching for plugin: MMCVMultiLevelRoiAlign, plugin_version: 1, plugin_namespace:
[09/03/2022-11:42:20] [TRT] [I] Successfully created plugin: MMCVMultiLevelRoiAlign
[09/03/2022-11:42:20] [TRT] [W] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[09/03/2022-11:42:20] [TRT] [W] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[09/03/2022-11:42:20] [TRT] [W] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[09/03/2022-11:42:20] [TRT] [W] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[09/03/2022-11:42:20] [TRT] [W] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[09/03/2022-11:42:20] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
[09/03/2022-11:42:20] [TRT] [I] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[09/03/2022-11:42:20] [TRT] [I] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace:
[09/03/2022-11:42:20] [TRT] [I] Successfully created plugin: TRTBatchedNMS
[09/03/2022-11:42:20] [TRT] [I] No importer registered for op: MMCVMultiLevelRoiAlign. Attempting to import as plugin.
[09/03/2022-11:42:20] [TRT] [I] Searching for plugin: MMCVMultiLevelRoiAlign, plugin_version: 1, plugin_namespace:
[09/03/2022-11:42:20] [TRT] [I] Successfully created plugin: MMCVMultiLevelRoiAlign
[09/03/2022-11:42:20] [TRT] [I] No importer registered for op: grid_sampler. Attempting to import as plugin.
[09/03/2022-11:42:20] [TRT] [I] Searching for plugin: grid_sampler, plugin_version: 1, plugin_namespace:
[09/03/2022-11:42:20] [TRT] [I] Successfully created plugin: grid_sampler
Traceback (most recent call last):
  File "f:/MM/TensorRT_Zhuan.py", line 31, in <module>
    onnx2tensorrt(work_dir, save_file, model_id, deploy_cfg, onnx_model, device)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\backend\tensorrt\onnx2tensorrt.py", line 88, in onnx2tensorrt
    device_id=device_id)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\backend\tensorrt\utils.py", line 145, in from_onnx
    'algorithm', trt.CalibrationAlgoType.ENTROPY_CALIBRATION_2))
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdeploy\backend\tensorrt\calib_utils.py", line 37, in __init__
    calib_file = h5py.File(calib_file, mode='r')
  File "D:\Anaconda3\envs\MM\lib\site-packages\h5py\_hl\files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "D:\Anaconda3\envs\MM\lib\site-packages\h5py\_hl\files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'F:/MM/TensorRT_inference/MMint8/calib_data.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by grimoire** [comment]
You need to create dataset for the quantization if you want to enable TensorRT int8.
https://github.com/open-mmlab/mmdeploy/blob/966d737a1be2fd8ccbfb5e67329e3a3e131141a3/tools/deploy.py#L182

**Comment by Manningchan** [comment]
How to create dataset for the quantization

**Comment by Manningchan** [comment]
> You need to create dataset for the quantization if you want to enable TensorRT int8.
> 
> https://github.com/open-mmlab/mmdeploy/blob/966d737a1be2fd8ccbfb5e67329e3a3e131141a3/tools/deploy.py#L182
How to create dataset for the quantization

**Comment by grimoire** [comment]
Just create the dataset follow mmdet, make sure you can load it from a mmdet style config file.
Feed the dataset config and other parameters to `create_calib_input_data`.

**Comment by monkeycc** [comment]
Thank you. 

`https://mmdeploy.readthedocs.io/zh_CN/latest/05-supported-backends/tensorrt.html?highlight=int8#int8-support`
`https://mmdeploy.readthedocs.io/zh_CN/latest/01-how-to-build/jetsons.html?highlight=int8#model-converter`

Not specified in the tutorial

It is suggested that the document can be improved
